### ISSUE TITLE
Add GM_notification API

### ISSUE THREAD

**Issue by erikvold** [greasemonkey/greasemonkey#1194]
As a user script author I would love to be able to send clickable notifications to my users instead of alert on confirmation windows in many situations.

**Comment by tiansh** [comment]
> In some use cases we might be able to use web notifications instead, which can be added to Firefox using various addons like tab notifier.

But by using web notification api, script can only pop up notifications if user allow the site to do so. User have no choice to disable notifications from the website but enable it from script.

**Comment by mk-pmb** [comment]
Right, I totally missed that aspect. :+1:

**Comment by tiansh** [comment]
Again, this API is needed since the website begin to show notifications which user want to block them. But I need to show notifications too. As the result, user have no chose between disable all these notifications or enable all of them. I need this API so that user may only allow notifications from the userscript.

**Comment by janekptacijarabaci** [comment]
The testing branch:
https://github.com/janekptacijarabaci/greasemonkey/tree/_testBranch_GM_notification

Synchronize API with Tampermonkey
See also https://tampermonkey.net/documentation.php#GM_notification

__This is just a thing for testing! (using the eval() function, etc.)__

__Uses the function "[PopupNotifications](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/PopupNotifications.jsm)" (!= "Web (HTML5) Notification API")!__
(I don't need this feature - for now I'll wait to solve this problem: [bug 862395](https://bugzilla.mozilla.org/show_bug.cgi?id=862395))

**Comment by tiansh** [comment]
@janekptacijarabaci Thanks, but I found it is buggy...

1. PopupNotifications.jsm is not Desktop Notification: The notification will not be shown if the browser window is minimized. (Yes, this is very important otherwise it become much more useless)
2. onclick and ondone should be optional, but currently it will fail without these values

(I'm not sure when bug 862395 will be fixed. But I think it is better to have a buggy but usable one than nothing.)

**Comment by janekptacijarabaci** [comment]
__Test branch updated:__
Popup Notifications => Desktop Notification

**Comment by tiansh** [comment]
@janekptacijarabaci 
Thank you.

To my understanding, currently implementation in the test branch only allow notification when user grant permission to the site to do so. It just like calling `Notification` directly. User still have no choice to disable notification from the site but allow it to userscript.

I am not sure what you do consider this api should be. But I hope this one may work with different permission control to content scripts from the website. (And that is TM currently do. They always allow userscript show notifications)

**Comment by janekptacijarabaci** [comment]
@tiansh 

The question is how to do it...

The Desktop Notification in Chrome (Tampermonkey) is different:
https://developer.chrome.com/extensions/desktop_notifications

System principal (chrome-privileged) should be granted permission. But...
Using message-passing (especially under e10s on) - kills all events (onclick, ondone) - see:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description
There is a partial solution:
http://stackoverflow.com/questions/6754919/json-stringify-function (toString() + eval())
but the result is unusable (for proper function).
Turning this option off (a window without chrome privileges) restored the correct functionality.

I don't have a better idea now...

**Comment by janekptacijarabaci** [comment]
However I have made some attempt...

**Comment by janekptacijarabaci** [comment]
FYI...
RESOLVED FIXED
https://bugzilla.mozilla.org/show_bug.cgi?id=862395

**Comment by VBelozyorov** [comment]
So... Was it implemented or not?

**Comment by Sxderp** [comment]
@VBelozyorov , I don't think it was implemented for 3.x. But for 4.x #2590
