### ISSUE TITLE
document.write() throws security error

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#1230]
Firefox: `Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.12) Gecko/20101026 Firefox/3.6.12`
Greasemonkey: master, commit ccdefe12f733a576710ea459be6612633c71caa8
Script: `document.write('working');`

Result: Error console shows `Error: Security error
Source File: file:///.../test.user.js
Line: 10`, script stops running.
Expected: Document content changes.

Also observed w/ GM 0.8.6.

**Comment by janekptacijarabaci** [comment]
Firefox 40+:
Result: Browser console shows "The operation is insecure.", script stops running.

__However, document.write works in devtools Scratchpad.__

**Comment by janekptacijarabaci** [comment]
RESOLVED FIXED for GM 3.5beta1+:
https://github.com/greasemonkey/greasemonkey/blob/3.5/modules/sandbox.js#L180
