### ISSUE TITLE
setTimeout + NoScript = fail

### ISSUE THREAD

**Issue by computerfreaker** [greasemonkey/greasemonkey#1238]
If NoScript is blocking a site's scripts, setTimeout will silently fail. The site must be unblocked in NoScript for setTimeout to work or even fail.

I posted about the issue on the NoScript forum ( http://forums.informaction.com/viewtopic.php?f=7&t=5470 ) and Giorgio Maone, the NoScript developer, said he can't do anything about it, since setTimeout works outside the Greasemonkey sandbox and is therefore subject to the same blocking as other non-GM scripts. Instead, Mr. Maone suggested a GM_setTimeout function be added to Greasemonkey to run the delayed function within the GM sandbox.

**Comment by Sasstraliss** [comment]
Has this been fixed?
