### ISSUE TITLE
document.location.href = empty string

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#1247]
Originally:
http://groups.google.com/group/greasemonkey-users/t/f452c2c85eb2e09f?hl=en

I have a script which sets the "document.location.href" value.  I noticed that sometimes I ended up with tabs using the "chrome://browser/content/browser.xul" URL.

I tracked this problem down to accidentally setting a blank value to document.location.href.  So basically:

    document.location.href = "";

In a user script, the above line loads chrome://browser/content/browser.xul into a tab.  This causes all kinds of problems with Firefox since it doesn't like loading that URL into a tab.

If I type the following into the awesome bar, it simply reloads the current page:

    javascript:document.location.href = "";

The problem also exists in both Firefox 3.6.13 and Minefield and in both GM 0.8.20100408 and GM 0.9

Why exactly does setting document.location.href to a blank string or null load the browser.xul when called via a user script, but simply reload the page when called from the page itself?

**Comment by johnzenith** [comment]
> Refresh won't work if the url contains hash (#).
So you have to do `window.location.href = window.location.href.split('#')[0]`
