### ISSUE TITLE
implement GM_setClipboard

### ISSUE THREAD

**Issue by 0rt** [greasemonkey/greasemonkey#1514]
useful for return string result for users. It's considerable safe than current hack like bind onclick event with UniversalXPConnect then grant the privilege.

**Comment by Drezzler** [comment]
Is this feature actually working ?

**Comment by Ventero** [comment]
@Drezzler: Seems to be working just fine for me with GM 3.3 (and current git HEAD) in FF39.

**Comment by Drezzler** [comment]
hmm , i am having a hard trying to get it work even with static text ...I am on windows 8.1 and using firefox 38.0.5 , upgrading firefox to FF39 now though .
