### ISSUE TITLE
Private messaging system

### ISSUE THREAD

**Issue by Spamme1** [greasemonkey/greasemonkey#1606]
I have the same script running in two different domains, it's a page with an iframe to another domain. To communicate between the two instances of the script (between the two domains) I use the window post message method, but this method isn't really stealth. If somebody want to detect the script it would be enough to add an event listener to the message event of the window.
It would be nice to have a private messaging system in GM, where you can send private messages to other scripts and they would be undetectable from the document.

**Comment by marsjaninzmarsa** [comment]
Something like [GM_addValueChangeListener()](https://tampermonkey.net/documentation.php#GM_addValueChangeListener) would be nice.
