### ISSUE TITLE
setTimeout broken again in 1.0

### ISSUE THREAD

**Issue by peci1** [greasemonkey/greasemonkey#1620]
Hello, bad news... setTimeout() ceased working for me after update to 1.0

I tried setting:
@grant none
@grant GM_util
@grant GM_util.timeout
@grant setTimeout
none of which work.

Thanks for any help ;)

**Comment by AYOUBZER** [comment]
hello 
i have a problem with the BLS , exactelly in the time out ,
the 504 and 502 error codes . after consulting by Cntr+U ( source code) i have found that the time out is fixed by 200 . 
setTimeout(function(){send=true;},200);  
what i have to do ?????

**Comment by Cerberus-tm** [comment]
@AYOUBZER I don't really understand what you mean, but it sounds as though you were talking about a userscript, not the extension itself. In that case, this is not the place to ask for advice.
