### ISSUE TITLE
User scripts  does not work on  pages  about:neterror

### ISSUE THREAD

**Issue by alex-chan** [greasemonkey/greasemonkey#1649]
```
// ==UserScript==
// @name        HttpsGoogle
// @namespace   gmail.czzsunset.httpsgoogle
// @description Switch Http to Https when google was reset by GFW
// @include     *
// @grant   GM_log
// @version     1
// ==/UserScript==


GM_log('OK');
```

This script does not work on network error pages
But http://stackoverflow.com/questions/3772777/greasemonkey-script-on-firefox-network-error-page says it does. I think this is a bug

My environment is OS X 10.8,  Firefox 15.0.1, Greasemonkey 1.3

**Comment by vanowm** [comment]
How about don't let access to chrome, yet give ability to detect such errors? For example allow scripts redirect to different domain if one is not accessible.
