### ISSUE TITLE
Drag'n' drop into AOM: This add-on could not be installed because it appears to be corrupt

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#1663]
Reported on the -users list:

> Now I tried to reinstall these scripts again.
> Therefore I clicked FF menu Tools--->Add-On--->User Scripts
> and dragged some of the old *.user.js scripts onto FF.
> 
> But much to my surprise a popup bubble appears telling me:
> "This add-on could not be installed because it appears to be corrupt"

Confirmed that this happens in the AOM but not a tab at a web page.

**Comment by QuestioningEspecialy** [comment]
the problem appears to have returned on both Waterfox and LibreWolf
