### ISSUE TITLE
Two install dialogs for local *.user.js files (NoScript conflict)

### ISSUE THREAD

**Issue by Infocatcher** [greasemonkey/greasemonkey#1681]
Copy path to *.user.js (e.g. "D:\test.user.js").
Paste path into URL bar (or just type it) and press Enter: two install dialogs will be opened.

**Comment by janekptacijarabaci** [comment]
Confirmed on:
Firefox 36.0.1
-
Firefox Developer Edition 38.0a2 (2015-03-17)

Not confirmed on:
Firefox Nightly 39.0a1 (2015-03-17)
(NoScript 2.6.3rc1 - 2.6.9.18)
