### ISSUE TITLE
Feature Request:GM_CloseTab 

### ISSUE THREAD

**Issue by Capatcha** [greasemonkey/greasemonkey#1685]
Open a new Tab with Greasemonkey:
var mynewopentab = GM_openInTab("http://www.example.com/");

Later close the previus opened tab.
GM_closeTab(mynewopentab);

I would not like to allow all javascript code to close windows with setting in about:config.
Only the GM Script should could do that.

**Comment by janekptacijarabaci** [comment]
See laso #2134
