### ISSUE TITLE
Need a better way to sync GM_values between tabs

### ISSUE THREAD

**Issue by MayhemYDG** [greasemonkey/greasemonkey#1728]
Currently the only solution is to save the value both with `GM_setValue` and with the localStorage, since it fires the `storage` event on `window` in other tabs.

This is a problem for multiple reasons:
- **Security**: I'm forced to save on localStorage, so everyone (the website, other content scripts) have access to these saved information.
- **Restricted**: localStorage is per-(sub)domain and per-protocol, so it may not fire in all the tabs the user is active in.
- **Performance**: I'm forced to pollute every websites my script is active on (\* subdomains \* protocols) which is a waste of disk space, and a [performance](https://insouciant.org/tech/time-to-load-localstorage-into-memory/) [hazard](https://insouciant.org/tech/localstorage-load-times-redux/).

I'm using localStorage to sync between tabs and it works fine, but as I pointed out it could be [better](https://developer.chrome.com/extensions/storage.html#event-onChanged).

**Comment by ccd0** [comment]
Tampermonkey has implemented this as `GM_addValueChangeListener`.  It would be great to have this in Greasemonkey.

**Comment by tiansh** [comment]
although GM_getValue in a setInterval loop may works, I may prefer to have the api GM_addValueChangeListener which is useful in many conditions. hope it can be implemented. thx.

**Comment by TimidScript** [comment]
+1
