### ISSUE TITLE
Same namespace, same context.

### ISSUE THREAD

**Issue by gera2ld** [greasemonkey/greasemonkey#1748]
This is a new feature of Tampermonkey. [@namespace](http://tampermonkey.net/documentation.php?version=3.0.3389.27&ext=dhdg#@namespace)
Scripts with the same namespace will run within the same context and access each others variables.
Will you think about this in Greasemonkey?

**Comment by marsjaninzmarsa** [comment]
No longer in documentation, reverted? If added to GM need to be opt-in for compat reasons.
