### ISSUE TITLE
Feature Request: Run greasemonkey scripts on page resources

### ISSUE THREAD

**Issue by simonzack** [greasemonkey/greasemonkey#1779]
Can there be a way to run greasemonkey scripts on page resources, or intercept their loading, e.g. ajax requests?

This is useful in many cases, say when an external script needs to be parsed and parts of it changed; changing ajax requests directly; changing images on-the-fly.

Currently the only way to do this is to use a separate addon, or a local filtering proxy. Doing this directly inside a userscript would save a lot of time and greatly increase flexibility.

**Comment by LMLB** [comment]
In case anyone is looking for this in the future: You can (in Firefox only) prevent specific scripts from running with the `beforescriptexecute` event, checking for the specific script in `event.target.src` or `event.target.textContent`, and preventing the script from running with `event.preventDefault()`. There is also the corresponding `afterscriptexecute` event by the way.
