### ISSUE TITLE
Conflict with MyBookmarks extension when installing from bookmark

### ISSUE THREAD

**Issue by Keith94** [greasemonkey/greasemonkey#1814]
Steps to reproduce:

1. Create a bookmark to a user.js link in your bookmarks menu, like this one: https://greasyfork.org/scripts/404-mouseover-popup-image-viewer/code/Mouseover%20Popup%20Image%20Viewer.user.js

2. After installing the [MyBookmarks](https://addons.mozilla.org/addon/mybookmarks/) extension, go to the about:mybookmarks page and left click the bookmark.

3. There will be a bar at the top of the page that says "You've navigated to a User Script but Greasemonkey is disabled" even though it is enabled.

**Comment by janekptacijarabaci** [comment]
It has been fixed in version GM 3.8beta1+.
