### ISSUE TITLE
Request: GM_xmlhttpRequest proxy support

### ISSUE THREAD

**Issue by fwvvdxjo** [greasemonkey/greasemonkey#1829]
Can proxy support be added to GM_xmlhttpRequest?

For example:

GM_xmlhttpRequest({
  method: "GET",
  url: "http://www.example.com/",
  proxy: "http://myportal.com:1234",
  onload: function(response) {
    alert(response.responseText);
  }
});

**Comment by Ede123** [comment]
It might sometimes be helpful when trying to access URLs from a Greasemonkey script that are not publicly accessible (e.g. IP filter).

That said access is normally restricted for a reason and compatibility is probably impossible to achieve.
