### ISSUE TITLE
Request: GM_xmlhttpRequest setting responseType support

### ISSUE THREAD

**Issue by gameclamp** [greasemonkey/greasemonkey#1834]
I want to use GM_xmlhttpRequest to get an image and store it in indexeddb.The responseText should be blob.
https://hacks.mozilla.org/2012/02/storing-images-and-files-in-indexeddb/

**Comment by brunoais** [comment]
Is this closed?

**Comment by pendave** [comment]
Can I set responseType : "arraybuffer" now?

**Comment by janekptacijarabaci** [comment]
> Can I set responseType : "arraybuffer" now?

Yes. See also http://www.greasespot.net/2015/05/greasemonkey-32-release.html

**Comment by pendave** [comment]
I try to rip out the email info from online PDF and firstly the whole text should be get.

So I find http://hublog.hubmed.org/archives/001948.html
and its nice example:
http://git.macropus.org/2011/11/pdftotext/example

I use Greasemonkey version 4.1.10 to do a cross domain version with GM_xmlhttpRequest.
I see responseType : "arraybuffer" should be working but I can't get the script doing right from XMLHttpRequest to GM_xmlhttpRequest.

Here's the script from that site, how can I make it working correctly?
`var pdfsrc = window.location.href;
//using a sample PDF for test now
pdfsrc ='http://git.macropus.org/2011/11/pdftotext/example/journal.pone.0026738.pdf';
html = document.body.innerHTML +'<div style="position: absolute; left: 10px; top: 200px; color: white; z-index: 100;">Attention<br><iframe id="input" src="'+ pdfsrc +'"></iframe><br><iframe id="processor" src="http://hubgit.github.com/2011/11/pdftotext/"></iframe><br><div id="output"></div></div>';
document.body.innerHTML = html;
//document.getElementById("plugin").remove();
var input = document.getElementById("input");
var processor = document.getElementById("processor");
var output = document.getElementById("output");
// listen for messages from the processor
window.addEventListener("message", function(event){
    if (event.source != processor.contentWindow) return;
    switch (event.data){
            // "ready" = the processor is ready, so fetch the PDF file
        case "ready":
            var xhr = new XMLHttpRequest();
            xhr.open('GET', input.getAttribute("src"), true);
            xhr.responseType = "arraybuffer";
            xhr.onload = function(event) {
                processor.contentWindow.postMessage(this.response, "*");
            };
            xhr.send();
            break;
            // anything else is the text of the PDF
        default:
            output.textContent = event.data.replace(/\s+/g, " ");
            break;
    }
}, true);`

Especially here I update with

` case "ready":
            var xhr = new GM_xmlhttpRequest();
            xhr.open('GET', input.getAttribute("src"), true);
            xhr.responseType = "arraybuffer";
            xhr.onload = function(event) {
                processor.contentWindow.postMessage(this.response, "*");
            };
            xhr.send();
            break;`

**Comment by janekptacijarabaci** [comment]
``` javascript
// ==UserScript==
// @name        Greasemonkey - issue - 1834
// @include     http://git.macropus.org/2011/11/pdftotext/example/
// @grant       GM_xmlhttpRequest
// ==/UserScript==

// 1 - GM_xmlhttpRequest(), 2 - XMLHttpRequest()
var what = 1;

var pdfsrc = window.location.href;
// using a sample PDF for test now
if (what == 1) {
  // pdfsrc = "http://www.cbu.edu.zm/downloads/pdf-sample.pdf";
  pdfsrc = "http://git.macropus.org/2011/11/pdftotext/example/journal.pone.0026738.pdf";
} else if (what == 2) {
  pdfsrc = "http://git.macropus.org/2011/11/pdftotext/example/journal.pone.0026738.pdf";
}
html = document.body.innerHTML + `
  <div style="position: absolute; left: 10px; top: 200px; color: white; z-index: 100;">
  Attention<br><iframe id="input" src="`+ pdfsrc +`"></iframe><br>
  <iframe id="processor" src="http://hubgit.github.com/2011/11/pdftotext/"></iframe><br>
  <div id="output"></div></div>
`;
document.body.innerHTML = html;
// document.getElementById("plugin").remove();
var input = document.getElementById("input");
var processor = document.getElementById("processor");
var output = document.getElementById("output");
// listen for messages from the processor
window.addEventListener("message", function (event) {
  if (event.source != processor.contentWindow) return;
  switch (event.data) {
    // "ready" = the processor is ready, so fetch the PDF file
    case "ready":
      if (what == 1) {
        GM_xmlhttpRequest({
          method: "GET",
          responseType: "arraybuffer",
          // url: input.getAttribute("src"),
          url: pdfsrc,
          onload: function (event) {
            var clonedArrayBuffer = new Uint8Array(event.response);
            var clonedArrayBufferStr = "";
            for (var i = 0, count = clonedArrayBuffer.byteLength; i < count; i++) {
              clonedArrayBufferStr += clonedArrayBuffer[i]
                  + (i == (count - 1) ? "" : " ");
            }
            console.log("GM_xmlhttpRequest():" + "\n" + clonedArrayBufferStr);
            processor.contentWindow.postMessage(event.response, "*");
          }
        });
      } else if (what == 2) {
        var xhr = new XMLHttpRequest();
        // var url = input.getAttribute("src");
        var url = pdfsrc;
        xhr.responseType = "arraybuffer";
        xhr.onload = function (event) {
          var clonedArrayBuffer = new Uint8Array(this.response);
          var clonedArrayBufferStr = "";
          for (var i = 0, count = clonedArrayBuffer.byteLength; i < count; i++) {
            clonedArrayBufferStr += clonedArrayBuffer[i]
                + (i == (count - 1) ? "" : " ");
          }
          console.log("XMLHttRequest():" + "\n" + clonedArrayBufferStr);
          processor.contentWindow.postMessage(this.response, "*");
        };
        xhr.open("GET", url);
        xhr.send();
      } else {
        console.log("NOTHING!");
      }
      break; 
    // anything else is the text of the PDF
    default:
      output.textContent = event.data.replace(/\s+/g, " ");
      break;
  }
}, true);
```
