### ISSUE TITLE
Suggestion: add userscripts to the debugger

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#1844]
I'd love to be able to debug userscripts inside Firefox's Debugger.

The same issue for Scriptish is [here](https://github.com/scriptish/scriptish/issues/178)
There it mentions the relevant needed Firefox feature [Add metadata API for add-on globals](https://bugzilla.mozilla.org/show_bug.cgi?id=898559)
(which was added in latest Firefox 26).

**Comment by stevenxxiu** [comment]
Yea it would be great. The scripts can't be debugged right now, they are niether in the page debugger nor in the browser toolbox.

**Comment by mikhoul** [comment]
I agree too it would be really useful and more convenient  !   :+1:
