### ISSUE TITLE
Suggestion: add a tooltip to the toolbar button showing the list of the enabled/disabled installed scripts which match the current page

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#1868]
I'd like to make this suggestion, please:
when mouseover on the toolbar button,
instead of just showing the word 'Greasemonkey'
to show a tooltip with the info of the lower part of the Monkey menu
(=a list of the enabled/disabled installed scripts whose include and exclude rules match the current page)

I.e to show as a tootip this info:
![2014-02-06_102652](https://f.cloud.github.com/assets/723651/2096612/c3d65a4c-8f09-11e3-8f84-19138506e042.png).

**Comment by janekptacijarabaci** [comment]
I propose to close  this issue.

**Comment by arantius** [comment]
Yes per the above merged PR.
