### ISSUE TITLE
Greasemonkey Options window too large for small screens

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#1871]
See: https://groups.google.com/forum/#!topic/greasemonkey-users/4Ymwvpk3tDE

![screenshot](https://lh5.googleusercontent.com/-6H_Cl3eo1ZY/UvQY20KJW3I/AAAAAAAAAMA/doPzAsuMZZs/s1600/greasemonket+screenshot.png)

**Comment by hyiltiz** [comment]
This issue still exists as of now in the latest stable Firefox (38.0.5) on GM installed via Firefox about:addons page.

**Comment by arantius** [comment]
Rather (#2191) it's happened again.
