### ISSUE TITLE
Request: A way to start downloads

### ISSUE THREAD

**Issue by kuehlschrank** [greasemonkey/greasemonkey#1877]
There's currently no reliable way for user scripts to trigger downloads.

AFAIK we have
- `location.href = myUrl` - Problem: Success depends on response headers. Media types supported by Firefox (like images) open inline. Workround: Read file with GM_xhr and make octet-stream data URI. Inefficient and no way to specify file name.
- `a.href = myUrl; a.download = myFilename; a.click();` - Problem: href must be same origin or attribute is ignored.

I suggest new function GM_download() with following features:
- everything GM_xmlhttpRequest has (authentication, custom headers, ...)
- `url` (string) - should also accept data URIs and blob objects
- `filename` (string) - If file extension is missing, try to append one based on MIME type.
- `prompt` (boolean) - If true (or when "Always ask me where to save files" is checked), open Firefox's "You have chosen to open" dialog, otherwise use download directory.

Security considerations:
- Scripts should not be able to choose the directory, just the actual file name.
- Files should never be overwritten unless `prompt` is true. If `prompt` is false and file exists, append "(1)" , "(2)" etc.

**Comment by AlexKey** [comment]
+1

**Comment by tiansh** [comment]
Tampermonkey had added this function and enabled default in TM 3.9 and later.
I think this request should be reconsidered for compatibility issues.

reference: https://gist.github.com/derjanb/4431f674124ef1b11e30

**Comment by Owyn** [comment]
Tampermonkey  already has this feature, if GM implements it too I hope it'd be compatible 

> What is the use-case for this?

downloading.

**Comment by an-electric-sheep** [comment]
> a.href = myUrl; a.download = myFilename; a.click(); - Problem: href must be same origin or attribute is ignored.

1. download Blob with GM_XHR
2. [URL.createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL)
3. a.download = blob; a.click

**Comment by eight04** [comment]
If we can

* Download files without prompting the user
* Creating nested-folders for downloaded files

Then it's possible to create something like image crawler or drag-n-drop image saver with userscript. 
I'm not sure if this should be done by userscript, however. Can GM_download in tampermonkey create sub-folders?
