### ISSUE TITLE
Greasemonkey uses the (browser's?) cache to update

### ISSUE THREAD

**Issue by MayhemYDG** [greasemonkey/greasemonkey#1878]
![2014-02-20 20-41-51](https://f.cloud.github.com/assets/567105/2222557/2c79b810-9a67-11e3-8a47-bac37a034c08.png)
I forced the browser to refresh the meta.js file, then tried to update the script manually again, and it installed the previous version from the cache, with the new version displayed from the meta.js file.

GM 1.15 + Fx 27.0.1.

**Comment by n00b42** [comment]
Every now and then I have problem with the cache when I try to update within less than around 5 minutes (or something like that), first thought it was github gist's fault, but does not look that way:

- Opening:
`https://gist.githubusercontent.com/raw/***id***/`
shows my script and pressing F5 always yields the latest version

- Opening
`https://gist.githubusercontent.com/raw/***id***/myscript.user.js`
shows the GM install/update screen, but shows the current installed version

- Right-Click on Script - "Search Updates" - also does not retrieve the new update.

Note: Explicitly using FFs "Clear Cache" has no influence, so something else seems to cache.

Waiting some minutes always resolves the problem. Then either accessing the URL or pressing "Seach Updates" works as expected.
