### ISSUE TITLE
Greasemonkey won't work on firefox x64

### ISSUE THREAD

**Issue by azev** [greasemonkey/greasemonkey#1887]
From version 1.14 and and up, greasymonkey is not working on Waterfox 27 (Firefox x64).
The addon is loaded but it doesn't work at all.
I had to downgrade to v 1.13, which works.

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
Greasemonkey 3.1beta1, Firefox Nightly 39.0a1 (2015-03-17).
