### ISSUE TITLE
No obvious (UI-)indicator for scripts which will not or cannot receive automatic updates

### ISSUE THREAD

**Issue by hurda** [greasemonkey/greasemonkey#1895]
Currently, scripts which are either modified or don't have the necessary information to be automatically updated give no visual clue that they won't be considered when scanning for updates.

The only clue is "Find updates" being disabled in each script's context-menu.
For disabled scripts this clue doesn't exist at all, as it isn't available for any of them.

So maybe their background-color can be changed (for example like the design for the Java-plugin in Plugins) or something similar, which would immediately give the information regarding the updating-state of each script.

**Comment by arantius** [comment]
@janekptacijarabaci 's above pull request will be merged for version 3.7.  It's not obvious yet, but at least it's something.
