### ISSUE TITLE
Download bar completes, will not install (Windows Locking)

### ISSUE THREAD

**Issue by pixyperson** [greasemonkey/greasemonkey#1919]
Browser:      Firefox 29.0.1
GreaseMonkey: Version 1.15
OS: Windows 8.1

Issue: When I try to install scripts for GreaseMonkey through github, it will appear to download, and the install button seems active, but will not respond to clicking, and the view script source button remains greyed out. It seems to be an issue with github scripts in particular, as I have been able to download and install some userscript.org scripts. I have attached an image as a specific example. This has continued as an issue since a forced update, and reboot, to Mozilla cleared my previously installed scripts, but was probably still an issue, as prior to that I had not visited GitHub. I have restarted my computer and Firefox since discovery of this issue, and it has not improved.

![greasemonkeyissue](https://cloud.githubusercontent.com/assets/7584518/2975631/0a5ce830-db97-11e3-82c2-4cba978b9b7e.png)

**Comment by arantius** [comment]
Finally getting back to this.  Clickable link again, now to history:

https://github.com/w35l3y/userscripts/blob/12833736c41729f396b4eb7787e70e249aa4c40d/scripts/Neopets_Price_Checker/112692.user.js

Running `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`, and clicking the "Raw" link there to install, first (unrelated) I navigate to the script with the install info bar.  Once I click install *there*, I see a `gm-temp` directory created, and a `download.php`, `download-1.php`, etc.  I thought perhaps the many pastebin URLs with similar filenames might hurt things, but that's already handled.

And when I click install, it works as expected.  So I tried again, but I (https://superuser.com/a/649819/76158)[locked a file] in the `gm-temp` directory, while the install window was open.

So *if* the file gets locked, then I see this behavior.  But if I don't manually/externally cause the locking, then I don't see this.  I'm going to close this WAI.  If you still see this problem, please re-open and provide as much detail as you can.
