### ISSUE TITLE
GM_getValue GM_setValue not working

### ISSUE THREAD

**Issue by tomaszs** [greasemonkey/greasemonkey#1931]
Until today everything worked ok. But today it's not. I have current version of FF. No changes to script. GM_getValue throws that it is undefined. setValue also stopped working without any errors thrown. How to fix it?

**Comment by benibela** [comment]
I have a similar issue.
    // ==UserScript==
    // @name        Moodle tricks
    // @namespace   http://benibela.de
    // @include     https://moodle.uni-luebeck.de/*
    // @include     https://www.uni-luebeck.de/studium/studierenden-service-center/service/termine/vorlesungszeiten.html
    // @include     http://www.uni-luebeck.de/studium/studierenden-service-center/service/termine/vorlesungszeiten.html
    // @version     1
    // @grant       GM_addStyle
    // @grant       GM_xmlhttpRequest
    // @grant       GM_setValue 
    // @grant       GM_getValue
    // ==/UserScript==

    GM_setValue("wtf", 123);
    alert(GM_getValue("wtf"));

Now shows a message "undefined"

It worked earlier this day.

Firefox 26, Greasemonkey 1.15 (which seems to be the newest available on addons.mozilla.org)
