### ISSUE TITLE
Feature: Add "more" link on scripts in addon manager

### ISSUE THREAD

**Issue by cletusc** [greasemonkey/greasemonkey#1944]
I would like to see Greasemonkey support of the "more" link in the addon manager for scripts. This would bring you to an expanded "details" page that shows more info about the script.

Here is GM's addon details page marked up.
![greasmonkey's details page marked up](http://puu.sh/9Mzcd.png)

Here is how Scriptish displays one of my scripts.
![scriptish showing a userscript detail page](http://puu.sh/9MAiR.png)

Ideally, the following should be on there.

- `@name`:
- `@author`: The "by author" should ideally be parsed in some standard format, e.g. `name <email> (url)` where it would link to URL if found, otherwise email if found, otherwise no link and display as-is.
- Last updated date
- `@homepageURL`: Other keys that would qualify could be `@homepage`.
- `@supportURL`
- `@icon`
- `@description`

Scriptish also supports `@contributionURL` and `@contributionAmount` [as seen here](https://github.com/scriptish/scriptish/wiki/Manual%3A-Metadata-Block#contributionurl-new-in-scriptish) but I don't know how you feel about implementing them.

Consider this low priority, but still really nice to have especially with [greasyfork looking to support](https://github.com/JasonBarnabe/greasyfork/issues/145) and [openuserjs supporting](https://github.com/OpenUserJs/OpenUserJS.org/pull/189) `@supportURL` and `@homepageURL`.

**Comment by SamB** [comment]
:+1 for `@homepageURL`; I just found your bug tracker solely to advocate for it.

**Comment by arantius** [comment]
This should be in 3.5beta1; let me know what you think:
https://addons.mozilla.org/firefox/downloads/file/354560/greasemonkey-3.5beta1-fx.xpi?src=devhub

**Comment by janekptacijarabaci** [comment]
If the value (homepageurl) does not exist:
![1](https://cloud.githubusercontent.com/assets/2373486/10060818/25afe098-6254-11e5-8d36-c3c0aed3692b.png)

**Comment by arantius** [comment]
@janekptacijarabaci Lately all your comments have been arriving over email but I can't see them on the site; you haven't changed anything recently have you?

Either way; yeah I should have checked for missing homepageURL values, I was expecting that and forgot to.

**Comment by janekptacijarabaci** [comment]
@arantius: I'm sorry. I wanted to write in detail later...

**Comment by jerone** [comment]
Both the homepage url and author don't show up in my addon mananger...

![2015-09-24 19_47_48-add-ons manager](https://cloud.githubusercontent.com/assets/55841/10081440/3314484a-62f5-11e5-8270-eb546f6ecb6e.png)

https://github.com/jerone/UserScripts/blob/master/Github_Comment_Enhancer/Github_Comment_Enhancer.user.js#L6-L9

**Comment by arantius** [comment]
Right, reopening.  It's got to re-scan the contents of the files once to load those values into the config which fills the view.

**Comment by jerone** [comment]
Confirmed fixed in latest beta
