### ISSUE TITLE
HTTP Basic Auth not cached when using GM_xmlhttpRequest

### ISSUE THREAD

**Issue by angrier-muffin** [greasemonkey/greasemonkey#1945]
When initially sending the authorization header with GM_xhr, the server properly validates the user/password and returns the protected page.  Subsequent requests, however, do not work and instead require the authorization header be set explicitly for the request to go through.

Is there a reason why the authorization is not cached after the initial request when sent via GM_xhr?

**Non-GM behavior:** First request prompts user/password.  Subsequent requests do not.

**GM behavior:**

*When first request does not contain authorization header and is sent via GM_xhr:*
Firefox's usual user/password appear and subsequent GM_xhr requests do not require authorization header be set explicitly.

*When first request does contain authorization header and is sent via GM_xhr:*
First request goes through fine without Firefox's prompt.  Each subsequent requests requires authorization headers be explicitly set or Firefox will prompt for user/password.

Perhaps I'm not setting the headers correctly or is this intended behavior?  Here's how I'm sending the request:

```
GM_xmlhttpRequest({
	method: 'GET',
	url: 'https://www.website.com/',
	headers: {
		'Authorization':'Basic ' + base64encodedUserAndPassword,
	},
	onload: function(r) {
		// handle response here
	}
});
```

Is there a way to send the initial request via GM's xhr method without having to send the user/password on each subsequent attempt, or do I simply have to send the initial request and prompt to browser's built in handling, and then send my requests like normal after that?

Is the authorization only cached when done through Firefox's built-in dialog?

**Comment by arantius** [comment]
Today, when I run this script:

```javascript
// ==UserScript==
// @name        GM_xhr HTTP Auth Test
// @include     http://localhost/*
// @exclude     http://localhost/auth*
// @version     1
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  method: 'GET',
  url: "http://localhost/auth/",
  headers: {
    'Authorization': "Basic dGVzdDp0ZXN0",
  },

  onerror: function() { dump('err!\n'); },
  onload: function(xhr) {
    dump('load 1!\n');
    dump(xhr.responseText.substr(0, 128).replace(/\n/g, ' ')+'\n');

    GM_xmlhttpRequest({
      method: 'GET',
      url: "http://localhost/auth/",
      onerror: function() { dump('err!\n'); },
      onload: function(xhr) {
        dump('load 2!\n');
        dump(xhr.responseText.substr(0, 128).replace(/\n/g, ' ')+'\n');
      },
    })
  },
})
```

In my console I see:

```
load 1!
<body> It works! </body> 
load 2!
<body> It works! </body> 
```

Both requests work, despite only the first specifying the auth header.  I don't think I ever tested it before, but it totally works for me now.

If I remove the auth header (and ctrl-shift-delete history to "log out") I get an auth popup and the console shows:

```
load 1!
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>401 Unauthorized</title> </head><body> <h1>Unauthorized</
```

twice.  Works for me, closing as such.

**Comment by janekptacijarabaci** [comment]
__Ad worksforme:__

Gist: https://gist.github.com/janekptacijarabaci/495f56ac22bdf25cdc40

GM 3.4.1:
Show login prompt (GM_xmlhttpRequest() 3)

After applying this fix (https://github.com/greasemonkey/greasemonkey/pull/2008):
Does not show login prompt

**Comment by arantius** [comment]
@janekptacijarabaci That's now normal XHR in the page works, too.

**Comment by janekptacijarabaci** [comment]
I just responded to https://github.com/greasemonkey/greasemonkey/issues/1945#issue-36735175... I personally do not need it.
