### ISSUE TITLE
Include and exclude rules override

### ISSUE THREAD

**Issue by dluciv** [greasemonkey/greasemonkey#1946]
There are some scripts with single `@include` rule equal to `*`. Restricting them to number of particular sites is a pain.

When copying `*` script `@include` rule to user `@exclude`, no other user include rule can apply. When leaving `*` script `@include` rule in place, it is not being overriden by user rules, but added to them, so script runs on all pages.

Scriptish uses other policy: as far as I have seen, the whole user rule block overrides script one for both includes and excludes. Can we support both policies or do something else useful for such scripts?

There is a workaround for it, based on negative lookahead, like adding [`/^https?:\/\/(?!(google\.com|mozilla\.org)\/.*)/`](http://regex101.com/r/yE6rW7/1) to user `@exclude` but it requires single rule to be added and overall there is definitely something idiotic in it.

**Comment by franklinyu** [comment]
This is really useful; why bankrupt this?
