### ISSUE TITLE
GM 2.0 + FF30 and ajax from jQuery

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [greasemonkey/greasemonkey#1952]
Hello, after changing unsafeWindow rules some scripts stop work. I have this situation:
- som page use jQ library by script tag
- from GM script I want get access to this jQuery in page and invoke ajax() method

Before change (older GM and Firefox) I use sth like this:

<pre>
unsafeWindow["$"]["ajax"]({
  "url": "someURL",
  "success": function(result) {
     alert(result["test1"] + result["test2"]);
  },
  "dataType": "json"
}); 
</pre>

and all works fine. Now I get "access denited" info because use object as argument. So in next step I try this:

<pre>
unsafeWindow["$"]["ajax"](cloneInto({
  "url": "someURL",
  "success": function(result) {
     alert(result["test1"] + result["test2"]);
  },
  "dataType": "json"
}, unsafeWindow));
</pre>

When cloning simple object doesn't have problem, but in this code problem make:

<pre>"success": function(result) {
  alert(result["test1"] + result["test2"]);
}</pre>

and generate error:
"Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIXPCComponents_Utils.cloneInto]"

When delete this method don't get any error. So how can I define this success method in GM side when jQ is defined in page side and make all works?

**Comment by CodenameCookie** [comment]
> ```js
> function ajax(url, settings) {
>     // The ajax method.
>     var ajax = unsafeWindow.jQuery.ajax;
>     if (typeof settings === 'undefined') {
>         ajax(cloneInto(url, unsafeWindow, {cloneFunctions: true}));
>         return;
>     }
>     ajax(url, cloneInto(settings, unsafeWindow, {cloneFunctions: true}));
> };
> 
> // Example usage.
> ajax({
>     url: 'someURL'
>     success: function (result) {
>         console.log(result);
>     },
>     dataType: 'json'
> });
> ```

I keep getting 'cloneinto  not defined'.

Is this example just too old to use now?

**Comment by Sxderp** [comment]
> I keep getting 'cloneinto not defined'.
>
> Is this example just too old to use now?

Very much so.
