### ISSUE TITLE
@GM_getResourceURL won't work for setting favicon

### ISSUE THREAD

**Issue by vBm** [greasemonkey/greasemonkey#1955]
I'm trying to replace existing `favicon` of a website with a custom one (so i can indicate that my script 'tweaked' the page)

This is simple testcase. -> https://gist.github.com/vBm/85a254006b6182bb59ba

While this code works perfectly fine using chrome with tampermonkey, on firefox and GM it's not working.

Hope this is 'good' enough report to get it fixed. If you need more info, i'll be eager to provide it ASAP.
Thanks in advance.

`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0`
`GM 2.0`

**Comment by arantius** [comment]
When I install the test case script linked in the original description today, it appears to work.  I see the favicon from the script on my tab.

Can anyone confirm/refute?

**Comment by janekptacijarabaci** [comment]
I confirmed. But...
Firefox 38, Firefox Nightly 41.0a1 (2015-05-29) __only [e10s off]__:
![error](https://cloud.githubusercontent.com/assets/2373486/7886553/16ac3a0e-062b-11e5-975a-0d6a3911e6a7.png)

**Comment by arantius** [comment]
Curious, I don't get that with e10s on or off, in 41.0a1.

**Comment by janekptacijarabaci** [comment]
Yes :-)

I don't know why, but not confirmed:
Ubuntu 15.04 64-bit
Firefox 38.0, Firefox Nightly 41.0a1 (2015-05-29) [e10s on/off]

I confirmed on:
Windows 7/8.1 64-bit (even in a clean profile)
Firefox 38.0.1, Firefox Nightly 41.0a1 (2015-05-29) only [e10s off]

Can anyone confirm, please?

**Comment by arantius** [comment]
Same machine, 38.0, no error (e10s off, not available yet in 38).

**Comment by vBm** [comment]
I can confirm that it works just fine now on

`GM 3.2` + `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0`

**Comment by janekptacijarabaci** [comment]
Do you have any error in the console?

**Comment by vBm** [comment]
> Do you have any error in the console?
None.

**Comment by janekptacijarabaci** [comment]
It's strange. But thanks.

**Comment by arantius** [comment]
On `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0` I get 

    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] scriptProtocol.js:118:0
    [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://greasemonkey/scriptProtocol.js :: ScriptProtocol.newChannel :: line 118"  data: no] tabbrowser.xml:547:0

But it continues to work.  Oh I bet I know why.  The code just did

```javascript
    var mm = Cc["@mozilla.org/childprocessmessagemanager;1"]
        .getService(Ci.nsISyncMessageSender);
```

But this is the parent process, getting the image to go in the UI chrome.  Or at least, why the error.  Still unsure how the image then shows up in the tab though.

**Comment by arantius** [comment]
Can I say again how much I hate e10s? It's so damn hard to work with.  "Oh, J/K LOL *that* kind of message manager isn't the one I wanted this time!  Sucks to be you!"

**Comment by arantius** [comment]
FYI https://bugzilla.mozilla.org/show_bug.cgi?id=1169841
