### ISSUE TITLE
Trusted sites should be able to detect Greasemonkey is installed

### ISSUE THREAD

**Issue by JasonBarnabe** [greasemonkey/greasemonkey#1964]
On Greasy Fork (and pretty much any other script hosting site) there's a big Install button to let people install scripts. Works great if you have Greasemonkey or other managers. If you're new to user scripts and don't have Greasemonkey, the Install button leads you to a page of code with no indication on what you're supposed to do with it.

What would be great is if Greasy Fork could detect that Greasemonkey is installed. If it is, Greasy Fork would have just the Install button. If not, Greasy Fork would have prominent text on the page telling the user what they need to do (but still include the Install button for clients that don't support the detection).

I realize that Greasemonkey tries to operate in stealth mode to prevent affected sites from taking countermeasures. This would have to operate on a whitelist basis.

**Comment by TriMoon** [comment]
Sorry to revive this but....
The reason why @JasonBarnabe  wants to detect if GM is installed, is IMHO not enough to have this functionality via GM.
If any site wants to detect GM or any other userscript handler, they should provide their own userscript for the functionality they want to provide their visitors with.
