### ISSUE TITLE
Url: github.com/...user.js - error in the Browser Console

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#1998]
Example:
https://github.com/w35l3y/userscripts/blob/master/scripts/Neopets_Price_Checker/112692.user.js

Browser console:
https://github.com/greasemonkey/greasemonkey/issues/1875#issuecomment-35026824
(line 278)

**Comment by arantius** [comment]
This fix is now included in version 3.1beta1.  Please browse to [Greasemonkey's AMO page](https://github.com/Ventero/greasemonkey/commit/b8a09369482f87d0d9fa8afb39b5f46439eab0c2) and open "Development Channel" near the bottom to install the beta version.  Can you confirm the fix?  Thank you.

**Comment by janekptacijarabaci** [comment]
Unfortunately, there is still something wrong.

Example:
https://github.com/w35l3y/userscripts/blob/master/scripts/Neopets_Price_Checker/112692.user.js
(F5 page reload)

Browser console:
![1](https://cloud.githubusercontent.com/assets/2373486/6669960/4825134e-cbfc-11e4-87be-7dfdc3d61245.png)
![2](https://cloud.githubusercontent.com/assets/2373486/6669968/53b2e330-cbfc-11e4-86ef-a87416b7a081.png)

**Comment by arantius** [comment]
Moving to 3.2 to fix whatever bits remain.

**Comment by arantius** [comment]
Ah I totally missed one detail!

So https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Frame_script_environment says " docShell 	The nsIDocShell associated with the browser".  And https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIDocShell#loadURI says there's a `loadURI()` method which takes four arguments.  But `docShell` also (??) is a `nsIWebNavigation` https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIWebNavigation#loadURI%28%29 which has a `loadURI()` method which takes *five* arguments!
