### ISSUE TITLE
Support multi-process Firefox

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2004]
See: 

* https://bugzilla.mozilla.org/show_bug.cgi?id=1048164
* https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

A quick skim of that page makes it look like this might be a giant, hairy change.

**Comment by arantius** [comment]
Finally found time to work on this again, just pushed some changes:
https://github.com/arantius/greasemonkey/commits/e10s_sync

I think it might actually be working now.  The only thing I know for certain is still missing is `GM_openInTab()`.  It would be helpful if anyone could test out [this build](https://dl.dropboxusercontent.com/u/6784911/greasemonkey-2015.01.07.beta.xpi) in any version of Firefox, multi-process enabled or not, and let me know about anything that works in version 2.3 but fails in this beta build.

**Comment by Ventero** [comment]
A few issues I noticed while testing this with e10s enabled:

- A bunch of "unsafe CPOW usage" warnings in [windowId.js](https://github.com/arantius/greasemonkey/blob/c4aadf0058823720140dd411f1ce13f1a3b37273/modules/util/windowId.js) lines 8, 17, 23, 28 and [browser.js](https://github.com/arantius/greasemonkey/blob/c4aadf0058823720140dd411f1ce13f1a3b37273/content/browser.js#L263) lines 263 and 267 when opening the monkey menu on any site other than about:blank.
- `GM_info.version` is still unimplemented (in the unfinished commit where I implemented `IPCScript#info`, I didn't have any idea how to get the GM version from the addon manager inside the frame process - and I still don't have a clue). This is of course also reproducable with e10s off.
- Objects returned by `GM_getValue` are privileged JS objects, so none of their properties can be accessed. Example code:

```js
GM_setValue("foo", {k: 1});
var r = GM_getValue("foo");
console.log(r, r.k, Object.keys(r));
// with e10s on throws "Permission denied to access object"
// with e10s off logs: {k: 1}, undefined, []
```
- The `greasemonkey-script` protocol seems to be broken. When for example creating a script node with `src` pointing to a `greasemonkey-script` URI, `ScriptProtocol#newURI` is called, but `newChannel` isn't. Not reproducable with e10s off.

- The following script seems to crash the tab as soon as it runs on an included site. Replacing the alert with a console.log works around the issue, tested in Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0 (FF nightly from 2015-01-10, only reproducable with e10s on).

```js
// ==UserScript==
// @name            GM test
// @namespace       test
// @include         http://example.org/*
// @grant none
// ==/UserScript==
alert(1);
```

**Comment by arantius** [comment]
1. Warnings are for another day.
2. Alert script: cannot reproduce crash, works as expected for me.  `Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0` nightly.
3. Set value with default non-primitive: I don't think that's an intended/supported case.
4. Script protocol: ouch; it's broken even worse for me.

**Comment by arantius** [comment]
I've just merged the e10s_sync branch into master and pushed it.

This bug is my number 1 item to get resolved.  It's been ongoing for months because it's been a repeated exercise in blind-stumbling hair-pulling trying to figure out umpteen undocumented changes.  Plus there's been holidays, other personal projects, and life getting in the way.

*I can really use your help* in figuring out what remains.  Install the next (nightly)[https://arantius.com/misc/gm-nightly/] build (after October 29).  Does anything stop working in stable Firefox versions?  Does anything work with e10s off that breaks with it on?  Or vice versa?

**Comment by arantius** [comment]
Oh, and it's probably worth filing individual bugs for anything that doesn't work as of commit f249351140408712963587ef5616c1bcc0ea5a08 -- the 3.0 milestone's primary purpose is for tracking whatever has to happen for e10s support to be complete.

**Comment by janekptacijarabaci** [comment]
Currently I see no problem (without commit https://github.com/greasemonkey/greasemonkey/commit/f249351140408712963587ef5616c1bcc0ea5a08 - otherwise user scripts will not run).

**Comment by arantius** [comment]
Firefox: 35.0.1

Greasemonkey nightly 2015.01.29: [YouTube Center](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version) (build 471) doesn't work as intended
Switch GM to 2.3: works again.

No idea why yet.

**Comment by arantius** [comment]
I pushed 3.0beta1 on the 20th, three weeks ago.  It's had ~3000 users since then and we've only gotten one bug report (#2103).  We don't have a ton of time left before e10s will be upon us by default.  Moving forward with this release!

**Comment by mzso** [comment]
@arantius commented on [2015. márc. 13. 16:43 CET](https://github.com/greasemonkey/greasemonkey/issues/2004#issuecomment-79060104 "2015-03-13T15:43:48Z - Replied by Github Comment Enhancer"):
> I pushed 3.0beta1 on the 20th, three weeks ago.  It's had ~3000 users since then and we've only gotten one bug report ([#2103](https://github.com/greasemonkey/greasemonkey/issues/2103 "GM_xhr error in multi-process Firefox when referrer is set")).  We don't have a ton of time left before e10s will be upon us by default.  Moving forward with this release!

I used it for a short while but I experienced greatly aggravated memory leaking (multiple OOM per day)  which got back to more usual lower leaking rate after I downgraded to stable.
