### ISSUE TITLE
Need ability for GM to create and interact with a new, pagescript-inaccessible window.

### ISSUE THREAD

**Issue by deant** [greasemonkey/greasemonkey#2018]
Consider the example of a GM script that maintains a list of "blacklisted" users who's posts are automatically hidden from you on a blogging or messaging website.  You'd want a user script (menu) command to pop up an interface to manage the blacklisted users.  You'd need that interface to interact with functions defined in your GM script (e.g. for save, cancel, add, delete, export etc.).

But you'd also need that list to be secure from any potentially malicious on-page scripts that might try to read or change it.  Therefore, your management interface can't just be added to or displayed within the existing page (where page script can get access to it):  You instead need to open it in a new tab, inaccessible to page script altogether.

Ideally you could do this via something like:

```
var newTab = GM_openInTab("about:blank"), newDoc = newTab.document;
newDoc.open();
newDoc.write(newTabHTML);
newDoc.close();
newDoc.getElementById("myButton").addEventListener("click","myButtonClick",false);
...
```

However the problem (al-la [issue#1534](https://github.com/greasemonkey/greasemonkey/issues/1534)) is that attempting something like this throws a "Permission Denied" or "The operation is insecure" exception.  This holds whether or not you use GM_openInTab or window.open, and whether you use newDoc.write() or DOM methods or innerHTML.

I've tested all possible variations of URL, window.open() vs GM_openInTab, and document manipulation methods, using GM 2.2 and FF 31, and the only thing that _does_ work is:
- Use window.open() to open a new window with the same domain as the page you're on; it has to be something that won't redirect to a different domain, and won't contain malicious javascript.  I successfully used a small .gif image!
- _WAIT_ for it to finish loading.
- Now use DOM manipulation or innerHTML to turn it into the page you want.

This is obviously a **very** ugly hack, although it works (so long as the URL you use continues to (a) not redirect to another domain, and (b) not contain malicious javascript in-page... which is actually under the control of their webserver, not your GM script).

The underlying problem is that the sandboxed security context that GM scripts run in for some reason won't recognise an "about:blank" window - even one _created by your GM script_ - as being accessible to scripting.  I'm not 100% sure, but I strongly suspect that this is related to the "Same-origin policy".  However, for normal page scripts, "about:blank" is excepted from this:  You can create and then manipulate the contents of an initially empty window.  That should apply to windows created by GM as well!

I'm also not at all clear why the (wrapped?) window objects returned by window.open() and GM_openInTab() don't amount to the same thing.  But it seems to be impossible to even store the return value of GM_openInTab without raising an exception, regardless of the URL argument initially supplied.

I don't know enough about Firefox internals to say if this is strictly a GM problem, or relates more deeply to the FF security model, but I hope that I've made a sufficiently strong case that wherever the problem lies, something needs to be done about it:  There needs to be a way for GM to pop up and control a new isolated-from-pagescript window or tab, regardless of specifically how this is accomplished. (Though ideally GM_openInTab should work!).

If there _is_ some way to do it that I've missed, then please post an example on the GreaseSpot wiki!

Thanks.

**Comment by tharroun** [comment]
I am hoping there may be some work on this issue. This still seems to be a problem for FF 40.0.3/ GM 3.3.

Here is more weirdness to consider. One solution out there is to inject a script verbatim into the origin webpage

    function addJS_Node () {
         var scriptNode          = document.createElement('script');
         scriptNode.type         = "text/javascript";
         scriptNode.textContent  = '(' + fireNewTab.toString() + ')()';
         var targ = document.getElementsByTagName ('head')[0] || document.body || document.documentElement;
         targ.appendChild(scriptNode);
    }

Then this works in all FF and Chrome:

    function fireNewTab () {
        var newTab = window.open ('about:blank', '_blank');
        var destDoc = newTab.document;
        destDoc.open ();
        destDoc.write ('<html>some stuff</html>');
        destDoc.close ();
    }

But if you use ` fireNewTab.call(this,myhtml).toString()`, then although the data in `myhtml` is passed into the function, open/write/close no longer works at all, and all you get is a blank page. (Adding an event listener doesn't work either.) 

    function fireNewTab (mytext) {
        var newTab = window.open ('about:blank', '_blank');
        var destDoc = newTab.document;
        destDoc.open ();
        destDoc.write ('<html>some stuff</html>'); // does nothing
        //  destDoc.write (mytext); does nothing too.
        destDoc.close ();
    }

**Comment by deant** [comment]
**tharroun**, the problem with the solution you describe is that the newly-opened window is accessible to existing (non-greasemonkey) javascript on the original page.  So the page's developer could add code to the page to detect and interfere with the new window, if (say) they disliked what the greasemonkey script was doing, or wanted to spy on it.  So it's not a full solution to the problem as I posted it.

I'd also note that `fireNewTab.call(this,myhtml).toString()` obviously won't work:  the `fireNewTab.call(this.myhtml)` part *actually calls* `fireNewTab`, and returns the result, which is `null`, since `fireNewTab` doesn't include a `return` statement.  You then attempt to apply `toString()` to that, which will throw a javascript error.

To do what you appear to want to do, OTOH you might try this (untested):

    function addJS_Node(myHTML) {
        var scriptNode = document.createElement('script'), targ = document.getElementsByTagName ('head')[0] || document.body || document.documentElement;
        scriptNode.type = "text/javascript";
        scriptNode.textContent = "(function(html){var d=window.open('about:blank', '_blank').document;d.open();d.write(html);d.close();})(" + JSON.stringify(myHTML).replace(/</g,'\\x3C') + ");";
        targ.appendChild(scriptNode);
    }

This also avoids adding the named function "fireNewTab" into the page's namespace (which might cause a problem, if there's already a function or variable of that name), by using an anonymous function instead.

If the JSON.stringify() function isn't available, you can obviously replace it with your own "stringification" function - it just needs to bracket the string in double-quotes, add backslashes before existing double-quotes or backslashes, and translate cr, lf, tab, ff, backspace characters into \r, \n, \t, \f, \b, as well as any other control-code characters into backslashed hex codes (\uXXXX or \xXX).

**Comment by tharroun** [comment]
Thank you very much deant, you found my answer. I have been trying hard to figure how to get the content of `myhtml` into the injected scripts, and the `JSON.stringify` was the answer I never would have guessed. Works in Chrome and Firefox

    var opengradingwindow = function (myHTML) {
        var scriptNode = document.createElement('script'), targ = document.getElementsByTagName ('head')[0] || document.body || document.documentElement;
        scriptNode.type = "text/javascript";
        scriptNode.textContent = "(function(html){var d=window.open('about:blank', '_blank').document;d.open();d.write(html);d.close();})(" + JSON.stringify(myHTML) + ");";
        targ.appendChild(scriptNode);
    };

Thanks again.
