### ISSUE TITLE
GM_deleteValue Slow

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2025]
If you have a large database and you remove values from it, the process is very very slow and it can hang Firefox if the data content is large. Do you do a compact operation with each delete?

I do not see why the process is so slow.. It's not so bad when adding <strong>new</strong> large data. Removing or replacing existing data is painfully slow.

**Comment by arantius** [comment]
Can you be more objective than "very slow"?  How many milliseconds does it take?  How many would be few enough to no longer be "too slow"?

**Comment by janekptacijarabaci** [comment]
I would add an index on the 'name' field.
See also https://www.sqlite.org/pragma.html#pragma_cache_size

**Comment by TimidScript** [comment]
I no longer have the script but I remember it was in seconds and not ms. The number of records in the database was in the thousands and some records were pretty large.

**Comment by janekptacijarabaci** [comment]
See also:
https://github.com/greasemonkey/greasemonkey/issues/2197

After adding this line to GM_[gs]etValue_Bench.user.js:
`measure('delete', GM_deleteValue, n);`

I propose to close this issue.

**Comment by arantius** [comment]
Agreed, this performs reasonably for me after fixing #2197.
