### ISSUE TITLE
Suggestion - Limit the time for AOM's "check for updates" 

### ISSUE THREAD

**Issue by LL25255252** [greasemonkey/greasemonkey#2029]
Some of my scripts which I downloaded from uso before it became dead and are not yet hosted in other sites (like greasyfork for example) have the @updateURL and @downloadURL pointing to the dead userscript.org .

This cause my AOM's (add-ons manager) "check for updates" to fail without a warning and so my other "good" scripts don't even get to be checked.

After I understood it, I searched my gm_scripts folder to find those scripts and removed those @updateURL and @downloadURL lines.
Now AOM's "check for updates" work correctly.

Not every user understands this issue and knows how to do this workaround so I think it will be a good idea to let the user the ability to set a time limit for every script update check (or at least give a warning).

STR:
- Create a fresh FF profile.
- install GM
- install for example "userstyles.org: stats link" script -  http://userscripts-mirror.org/scripts/show/170913.html
- AOM > "check for updates" doesn't seem to end.

GM 2.2, FF 32, Win 7 64bit
TIA

**Comment by janekptacijarabaci** [comment]
See https://github.com/greasemonkey/greasemonkey/commit/1002ffc50e5c5d62a606f92d72be793a07f0576e#commitcomment-11339858

**Comment by LL25255252** [comment]
Sorry @arantius. Nothing changed with the new GM 3.2. The search for updates time still take the  long time as before GM 3.2
Without the script dfrom the old uso it takes no more than one second.

Tested on a new firefox profile with the same STR as my first post.
Firefox 38.0.1
Win 7 x64

**Comment by arantius** [comment]
Reminder to self: test with script linked above.

**Comment by LL25255252** [comment]
Now with the new 3.3 version
Still it takes too much time to check for updates (tested on a new fresh firefox folder as my first post)
FF 39
Win 7 x64

**Comment by arantius** [comment]
Firefox: `Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0`, `Built from https://hg.mozilla.org/mozilla-central/rev/ca53d4297f02`.
Greasemonkey: 3.3 (753d9f41affbbe73a703b6ff8840060437e92c94).

Only script installed: That linked in the original description.

Open AOM, right click on the script, pick "find updates".  The UI now displays "checking for updates ..." and 45 seconds later it finishes (with no update).  If I pick "check for updates" from the gear menu, "updating add-ons" displays next to it, then changes to "no updates found" 45 seconds later.

As best I can tell this is working as intended.

**Comment by LL25255252** [comment]
Out of curiosity, why wouldn't you limit it to 15 seconds or 5 seconds ?
  
As I said, I personally know to be careful with those userscripts.org scripts. But I think many users are still installing scripts from this site. Part of the reason for that is b/c google search still put userscripts.org at the top before for example greasyfork, github. (I tested it on google with some search terms after signing out).

Will you consider adding alert when the user tries to install a script that needs more than "x" seconds to update ?
