### ISSUE TITLE
FileReader API is unusable on Greasemonkey

### ISSUE THREAD

**Issue by Y0ba** [greasemonkey/greasemonkey#2034]
Using latest nightly (2014.10.11) Greasemonkey. Script:

``` JS
// ==UserScript==
// @name            Greasemonkey + FileReader Bug
// @version         1
// @author          Y0ba
// @grant           GM_openInTab
// @include         http://*
// @include         https://*
// ==/UserScript==

var fr = new FileReader();
fr.onload = function (e) {
    // Error
    alert(new Uint8Array(e.target.result)[0]);
    // Workaround
    //alert(new unsafeWindow.Uint8Array(e.target.result)[0]);
};
fr.readAsArrayBuffer(new Blob([new Uint8Array([1])]));
```

Open any page.
**Expected result**: it should alert `1`.
**Actual result**: an error:

```
Error: Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto().
Source file: file:///C:/Users/.../gm_scripts/Greasemonkey_+_FileReader_Bug/bug.user.js
Line: 13
```

**Comment by Pacopag** [comment]
This seems to have made its way into Firefox 35.  Is there a way around this?  I've got very similar code in a FF addon content script, and it seems like I can construct the Uint8Array from the arraybuffer, but I can't actually do anything with it.  e.g. read its contents.  I get the same error as above.

**Comment by arantius** [comment]
I know nothing about `FileReader()`.

**Comment by Y0ba** [comment]
That's more about typed arrays over xrays. `FileReader` for some reason generates array in other compartment and Firefox forbids to read it.

Error message suggests to use `cloneInto` but it doesn't work. I use `unsafeWindow.Uint8Array` to read array data. Here is cross-browser workaround function:
```js
function getUint8Array(data, i, len) {
		var rv;
		if(typeof i === 'undefined') {
			rv = new Uint8Array(data);
			return rv instanceof Uint8Array ? rv : new unsafeWindow.Uint8Array(data);
		}
		rv = new Uint8Array(data, i, len);
		return rv instanceof Uint8Array ? rv : new unsafeWindow.Uint8Array(data, i, len);
}
```

**Comment by Pacopag** [comment]
That works.  Thanks a pile.  Nothing better than a day where you waste 3 hrs on a problem that someone else fixes with one word.

But they really should come up with a better name than "unsafeWindow".  Who wants to use that?

**Comment by Pacopag** [comment]
Y0ba:  Do you think that unsafeWindow.Uint8Array() will be reliable in the future?  I'm just worried about breakage of my addon upon FF updates moving forward.  I did realize that another workaround is to use FileReader.readAsBinaryString(), then wrap the result in btoa() to get a base64 string, which to me is as good as a Uint8Array.  Do you think the btoa approach might be more forwards-compatible?  Or is unsafeWindow safe to use?

**Comment by desudesutalk** [comment]
@Y0ba, thanks a lot!

By the way: may usage of `unsafeWindow.Uint8Array` make userscript internals accessible in some way for page javascript?

**Comment by Y0ba** [comment]
@desudesutalk @Pacopag It's not secure to use `unsafeWindow`, because page scripts can redefine `Uint8Array` like this:
```js
var realU8A = window.Uint8Array;
window.Uint8Array = function Uint8Array(a, b, c) {
    console.log('Uint8Array constructor called with arguments (%s, %s, %s) from\n%s', a, b, c, new Error().stack);
    return new realU8A(a, b, c);
};
```
Or just break your script `window.Uint8Array = null;`.

Strings are safer but much slower.

**Comment by desudesutalk** [comment]
@Y0ba, I do not care much about data I get through `FileReader`, because it is just image file my script will use later.

I just want to be sure what ther is no way to mess with script internal state and variables (private key especially) through redefining `Uint8Array`. I see no possibility for such hack, but maybe i just do not know something about `unsafeWindow`?
