### ISSUE TITLE
Pale Moon compatibility

### ISSUE THREAD

**Issue by Gittyperson** [greasemonkey/greasemonkey#2038]
Greasemonkey up to v.1.15 works perfectly on this popular browser. Is there a possibility we could see the newer versions working with it?

**Comment by Crazycatz00** [comment]
I messed around with getting Greasemonkey 2.3 working in Palemoon 25.1, and I was able to get it to work; but not without disadvantages:
* `createObjectIn`, `cloneInto`, `exportFunction` are not supported. The export code is fine though; it's just exporting `undefined`.
* `Components.utils.getObjectPrincipal` is not supported. This is only used when checking the callbacks for GM_xmlhttpRequest; I only got it to work by checking if the function exists, and if not bypassing the check (which re-introduces #&#8203;1937 for browsers without support. v1.15 doesn't have any check like this though, from what I can see.).

I'm not sure how big of a security problem it would be to selectively bypass the callback check, but if it's not bad I could try to do a fork for this.

**Comment by DAOWAce** [comment]
So it needed more changes than just the GUID?

Well, I hope the scripts I still use don't need anything from GM versions above what works with PM (1.15), as I'm just about to re-transition off my old v28 Firefox install.

I disagree with PM 25's GUID change which broke most addons in the first place (and halted my initial transition over to it all this time), but oh well, development seldom moves backwards and eventually we just all gotta deal with it.  Still worlds better than dealing with Australis..

**Comment by JamesTheAwesomeDude** [comment]
:+1: Thanks for fixing this! I really appreciate Pale Moon support.

**Comment by koitsu** [comment]
An additional :thumbsup: from me as well for Pale Moon support.  Things like the BTTV addon don't work in PM (for different reasons than GM), so being able to get working GM / Userscripts under PM is super helpful.  Thank you so much for your effort on this.

**Comment by JamesTheAwesomeDude** [comment]
Hey, on the Mozilla Add-Ons page, https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/, the Download button looks like it's to download the latest 3.3 version, but it actually downloads version [0.9.22](https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/versions/0.9.22).

Going to https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/versions/ lists [1.51](https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/versions/1.15.1-signed) as the last compatible version, even though the latest version installs with no issues (if you extract the download link via the Inspect Element tool).

**Comment by arantius** [comment]
We have no control over the behavior of the AMO site, you'll have to report that to Mozilla.
