### ISSUE TITLE
document-start does not work for about:blank

### ISSUE THREAD

**Issue by volkan-k** [greasemonkey/greasemonkey#2041]
Hello,

My userscript runs in about:blank page, but unlike other pages (http, https, ftp) , I am unable to register menu command in about:blank tab. Registered menu commands are not shown.

Could you please advise?

UserScript; https://greasyfork.org/scripts/3851-display-my-ip-address

Looking forward to hear from you,
Thanks

**Comment by janekptacijarabaci** [comment]
This works:
```javascript
@include about:blank
@run-at  document-end
```

This no works:
```javascript
@include about:blank
@run-at  document-start
```

**Comment by arantius** [comment]
So is `about:blank` a red herring?

**Comment by janekptacijarabaci** [comment]
Yes and No.

"about:blank" - supports only: document-end
normal contents - supports: document-end, document-start

**Comment by arantius** [comment]
Is this still broken in (just released) Greasemonkey version 3.2 ?

**Comment by janekptacijarabaci** [comment]
Yes.

Btw, "about:blank" - supports only: document-end (for supports: document-start), offered by the use of:
``` javascript
addEventListener(
    'DOMWindowCreated', contentObserver.blankLoadStart.bind(contentObserver));
```
But this user script:
``` javascript
// ==UserScript==
// @name        Greasemonkey - issue - 2041
// @include     about:blank
// @run-at      document-start
// @grant       none
// ==/UserScript==

alert("hello");
```
...after the restart (if the page loaded is the "about:blank" and enabled browser history), the browser hangs and has to be killed in the Task Manager (and the script must be manually disabled)!

See also #1849 (but don't see the problem there - maybe...)

**Comment by janekptacijarabaci** [comment]
I noticed now...

This user script:
``` javascript
// ==UserScript==
// @name        Greasemonkey - issue - 2041
// @include     about:blank
// @run-at      document-end
// @grant       none
// ==/UserScript==

alert("hello"); // modal window
```
...do the same (on the event DOMContentLoaded). That's not good...

**Comment by arantius** [comment]
@janekptacijarabaci The comments immediately above appear unrelated.  Please report them as a separate issue if you still observe such problems.

**Comment by arantius** [comment]
Firefox: `Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0`, `Built from https://hg.mozilla.org/mozilla-central/rev/ca53d4297f02`.
Greasemonkey: 3.3 (753d9f41affbbe73a703b6ff8840060437e92c94).
Four scripts: https://gist.github.com/arantius/55449c978ceae58f9e9c

Scripts 1, 2, and 4 work fine.  Script 3's menu command is not listed.  Script 3 doesn't even run (!).

Indeed, that's what it says above, but like so many issues recently I'm finding the various scattered comments about so many distinct things mixed together hard to read, so I guess I'm really confirming the above.
