### ISSUE TITLE
Feature: Execute scripts on demand

### ISSUE THREAD

**Issue by AnasHSulaiman** [greasemonkey/greasemonkey#2043]
The most notable use case is to run bookmarklets like [CSS Layout Debugger](https://gist.github.com/addyosmani/fd3999ea7fce242756b1), [CriticalCSS](https://gist.github.com/PaulKinlan/6284142), SaveFrom.net, and many more others.

I imagine the ideal UX for this is having a Sublime-Text-Command-Palette-like interface: An autocomplete input field that uses fuzzy search to filter installed scripts, and runs the first one in the list by simply hitting enter. And this field can be brought up using a shortcut (like ctrl+shift+p).

It would be event better to specify manual scripts using something like `@run-at user-demand`. This is to avoid running some scripts twice.

**Comment by ahspw** [comment]
I have implemented the UI described above with minimum code changes.

Basically, I've added a floating panel that can be activated using CTRL+SHIFT+SPACE. Inside that panel there is a textbox, where can filter for all registered menu commands on the current window, and execute the selected one by hitting enter.

Now any bookmarklet can be simply converted into a user script that registers its function as a menu command, that can be productively executed on demand.

I will submit a pull request in the near future, once I'm done testing.
