### ISSUE TITLE
GM_xmlhttpRequest doesn't remember session

### ISSUE THREAD

**Issue by athoik** [greasemonkey/greasemonkey#2048]
After upgrading Firefox to 33.0.2 a greasemonkey script stopped working.  

It seems that Firefox with the History option "Never remember history" now also forgets session (I was getting error not authenticated) on GM_xmlhttpRequest.

After changed History option to "Remember history" seems that GM_xmlhttpRequest works again.

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
Firefox 38.0.1, GM 3.2

Gist: https://gist.github.com/janekptacijarabaci/495f56ac22bdf25cdc40

Or I did not understand a issue?

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
Firefox 38.0.1, GM 3.2

Gist: https://gist.github.com/janekptacijarabaci/8b969e5f48a305d91fd7

Result:
```GM_xmlhttpRequest() 2: status: 200 statusText: OK``` (show login prompt)
```GM_xmlhttpRequest() 3: status: 200 statusText: OK```

Reloading page (F5):
```GM_xmlhttpRequest() 2: status: 200 statusText: OK``` (does not show login prompt)
```GM_xmlhttpRequest() 3: status: 200 statusText: OK```

__Or I did not understand a issue?__

(Show login prompt - however only e10s off __(?)__)
GM_xmlhttpRequest() 2: status: 401 statusText: Authorization Required
GM_xmlhttpRequest() 3: status: 401 statusText: Authorization Required
![1](https://cloud.githubusercontent.com/assets/2373486/7895635/b7ca3170-0699-11e5-9e01-a94d70862d8a.png)
![2](https://cloud.githubusercontent.com/assets/2373486/7895640/c40a77a6-0699-11e5-9eda-830c9a971fe3.png)
...it comes to the same thing.
XMLHttpRequest() - OK

**Comment by athoik** [comment]
Ok, it seems that it was fixed in a newer FF version. 

Currently the script I am using is working without problems with "Remember history", so I didn't make any further test.

Thanks for confirming that works with latest FF.
