### ISSUE TITLE
greasemonkey isn't running on some iframes

### ISSUE THREAD

**Issue by bobleger** [greasemonkey/greasemonkey#2049]
Example is here:
http://www.theverge.com/2014/10/30/7134235/why-twitters-new-head-of-product-could-be-the-one-to-fix-it

On that article there is a iframe with twitter post from @rsarver

greasemonkey scripts do not run on that iframe. I have other addons that make changes to page formatting such as links and those addons are running on twitter iframe but greasemonkey seems to have some sort of problem.

**Comment by bobleger** [comment]
This problem still happens on latest GM 3.2. Why was this issue closed?

**Comment by arantius** [comment]
Because it's not (or at least is not now) an `<iframe>`.  It is a `<twitterwidget>` (which is some made up non-thing, but definitely not a document).  (And it's a `<blockquote>` until some javascript turns it into that.)
