### ISSUE TITLE
Suggestion GM_setValueGlobal Global Scope

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2056]
The ability to store information in a central database accessible by all scripts.

**Comment by TimidScript** [comment]
If it is only one database it can become bloated if several scripts are writing to it as the number of scripts utilising it increases.

Instead of having one global database allow the script to define a global database name(s). 

Reading is not an issue but altering or amending a large database really slows down the browser and causes irresponsiveness.

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/1728

**Comment by TimidScript** [comment]
Please consider allowing the new databases locations to be a setting value. I would rather have them on a different drive and directory.
