### ISSUE TITLE
@updateURL and @icon relative to @downloadURL

### ISSUE THREAD

**Issue by mk-pmb** [greasemonkey/greasemonkey#2058]
I can't find info on support for relative URLs on the [Metadata Block wikipage](http://wiki.greasespot.net/Metadata_Block) except for resources.
Is it possible? (#1658 sounds like it could…) If not, could you make it possible? Or maybe a @baseURL for the other @'s?
This would help a lot to not repeat yourself when writing user scripts.

**Comment by arantius** [comment]
Docs updated, this has always (for a very long time) worked.

**Comment by mk-pmb** [comment]
Thanks! :+1:
