### ISSUE TITLE
GM_info has wrong value when using windows symlink

### ISSUE THREAD

**Issue by tiansh** [greasemonkey/greasemonkey#2060]
GM_info.script.version and GM_info.scriptMetaStr may have different "version" info if i use symlink on Windows.

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0
Greasemonkey 2.3
NTFS

Here is how to reproduce:
1. install this user script: https://gist.github.com/tiansh/3b4f0870afca2eff8d3a/raw/b82458f265d9861a763b6204d03adad18b8d0ad2/Greasemonkey_GM_info_Test.user.js

``` javascript
// ==UserScript==
// @name Greasemonkey GM_info Test
// @namespace https://github.com/tiansh
// @description Test GM_info
// @include *
// @include http://www.github.com/
// @version 1
// @grant GM_info
// ==/UserScript==

console.log("%s", GM_info.scriptMetaStr);
console.log("%s", JSON.stringify(GM_info.script));
```
1. open the folder contains this user script
2. close firefox
3. move this file to another folder, for example `"D:\Greasemonkey_GM_info_Test.user.js"`
4. open cmd.exe and create a symlink use `mklink Greasemonkey_GM_info_Test.user.js D:\Greasemonkey_GM_info_Test.user.js`
5. reopen firefox
6. edit `"D:\Greasemonkey_GM_info_Test.user.js"`, change version to 2
7. visit any webpage and see console

Here is the console output:

```
"// @name        Greasemonkey GM_info Test
// @namespace   https://github.com/tiansh
// @description Test GM_info
// @include     *
// @include     http://www.github.com/
// @version     2
// @grant       GM_info
"
Greasemonkey_GM_info_Test.user.js:14

"{"description":"Test GM_info","excludes":[],"includes":["*","http://www.github.com/"],"localizedDescription":"Test GM_info","localizedName":"Greasemonkey GM_info Test","matches":[],"name":"Greasemonkey GM_info Test","namespace":"https://github.com/tiansh","resources":{},"run-at":"document-end","version":"1"}"
Greasemonkey_GM_info_Test.user.js:15
```

the GM_info.script.version is "1" and we can found version in GM_info.scriptMetaStr is "2"

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2305 (wontfix)
