### ISSUE TITLE
CloneInto does not copy function from add-on script to page script

### ISSUE THREAD

**Issue by Delgan** [greasemonkey/greasemonkey#2070]
I do not know if this bug comes from GreaseMonkey or Firefox 34, but I hope you can tell me.

Here is a copy of the message I posted on [Stackoverflow](http://stackoverflow.com/questions/27886281/firefox-cloneinto-does-not-copy-function-from-add-on-script-to-page-script) in order to explain the issue.

>I created a Greasemonkey script that contains an object that I would like to make accessible from the internal scripts of the page.
>
>To do so, there are several safe ways described on this page.
>One of them is to use the Components.utils.cloneInto function.
>
>Here is a script example.
>```
>// ==UserScript==
>// @name        Test CloneInto
>// @namespace   Test CloneInto
>// @description Test CloneInto
>// @include     http://stackoverflow.com*
>// @version     1
>// @grant       GM_xmlhttpRequest
>// ==/UserScript==
>
>var myObj = {}
>
>myObj.test = function() {
>  alert("works");
>}
>
>myObj.num = 152;
>
>unsafeWindow.myObj = cloneInto(myObj, unsafeWindow, {cloneFunctions: true});
>
>var scriptDOM = document.createElement("script");
>scriptDOM.type = "text/javascript";
>scriptDOM.innerHTML = "alert(window.myObj.num);\
>                       alert(window.myObj.test);"
>document.getElementsByTagName("head")[0].appendChild(scriptDOM);
>```
>"152" is displayed correctly, but then "undefined" appears instead of my function.
>Yet I used {cloneFunctions: true} as suggested by the documentation.
>
>I use Firefox 34, would anyone have an idea to fix this please?
>
>Edit: It works just fine using Google Chrome and TamperMonkey.

**Comment by arantius** [comment]
If you're not sure it's a bug, heading to the [greasemonkey-users](http://groups.google.com/group/greasemonkey-users) support list first is a good idea.

**Comment by legnaleurc** [comment]
Hi, I made some tests with the same script:

```javascript
// ==UserScript==
// @name        test_1
// @namespace   test
// @include     http://localhost/*
// @version     1
// @grant       unsafeWindow
// ==/UserScript==

var fusobian = {
  u: undefined,
  n: null,
  b: true,
  i: 42,
  s: 'all your base are belong to us',
  f: function () {},
  a: [],
  o: {},
};

console.info(fusobian, fusobian.f);

var unsafe = cloneInto(fusobian, unsafeWindow, {
  cloneFunctions: true,
});

console.info(unsafe, unsafe.f);
```

## Firefox 31.4.0 + (GM 2.0 || GM 2.3)
```
Object { u: undefined, n: null, b: true, i: 42, s: "all your base are belong to us", f: fusobian.f(), a: Array[0], o: Object } function () test_1.user.js:20
Object { u: undefined, n: null, b: true, i: 42, s: "all your base are belong to us", f: function (), a: Array[0], o: Object } function () test_1.user.js:26
```
Works.

## Firefox 32.0.3 + (GM 2.0 || GM 2.3)
```
Object { u: undefined, n: null, b: true, i: 42, s: "all your base are belong to us", f: fusobian.f(), a: Array[0], o: Object } function () test_1.user.js:20
Object { u: undefined, n: null, b: true, i: 42, s: "all your base are belong to us", f: function (), a: Array[0], o: Object } undefined test_1.user.js:26
```
Wired, the cloned function is in the object, but can not access from property.

## Firefox 34 + (GM 2.0 || GM 2.3)
```
Object { u: undefined, n: null, b: true, i: 42, s: "all your base are belong to us", f: fusobian.f(), a: Array[0], o: Object } function () test_1.user.js:20
Object { u: undefined, n: null, b: true, i: 42, s: "all your base are belong to us", a: Array[0], o: Object } undefined test_1.user.js:26
```
Function is totally undefined.

----

I think the upstream changed something from 32, and totally break it from 34.

**Comment by arantius** [comment]
Thanks for the clear and detailed test case.  What happens if you `console.info()` from the page itself, not from the script, after attempting to export the object?

**Comment by legnaleurc** [comment]
GM version seems to be irrelevant so I use 2.3 in all cases.

## Firefox 31.4.0, Firefox 32.0.3
```
< unsafe.f
> function ()

< unsafe.f()
> Error: Permission denied to access object

< unsafe.f.prototype
> undefined

< unsafe.f.toString()
> "function () {
      [native code]
  }"

< unsafe.f.call(this);
> Error: Permission denied to access object

< unsafe.f.apply(this);
> Error: Permission denied to access object
```

## Firefox 34
```
< unsafe.f
> undefined
```

----

I think nothing is working since ESR ...

**Comment by legnaleurc** [comment]
BTW, in Firefox 32, whether cloned object is attached to `unsafeWindow` will get different results.

```
var unsafe = cloneInto(safe, unsafeWindow, {
  cloneFunctions: true,
});
console.info(unsafe.f);

unsafeWindow.unsafe = cloneInto(safe, unsafeWindow, {
  cloneFunctions: true,
});
console.info(unsafeWindow.unsafe.f);
```

In console:
```
undefined
function ()
```

**Comment by arantius** [comment]
Confirmed with script in OP.  But I don't know why yet.

**Comment by janekptacijarabaci** [comment]
See also https://developer.mozilla.org/cs/docs/Components.utils.Sandbox : wantExportHelpers

It's probably better than that:
https://github.com/greasemonkey/greasemonkey/blob/master/modules/sandbox.js#L73
``` javascript
sandbox.createObjectIn = Cu.createObjectIn;
sandbox.exportFunction = Cu.exportFunction;
sandbox.cloneInto = Cu.cloneInto;
```
But it still does not work...

See also:
https://dxr.mozilla.org/mozilla-central/source/js/xpconnect/src/Sandbox.cpp#293
https://dxr.mozilla.org/mozilla-central/source/js/xpconnect/src/XPCComponents.cpp#3393

**Comment by janekptacijarabaci** [comment]
Reported as: https://bugzilla.mozilla.org/show_bug.cgi?id=1160846

**Comment by janekptacijarabaci** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1160846#c4
If that's not possible it should at least notify me that the function has been removed.

**Comment by arantius** [comment]
Coming back to this, I realize I misspoke above.  The test case is detailed, but not clear.  There's a lot of noise in there, and it takes a lot of work to distinguish the one difference from the 15 other things.

Can you trim this down to something that produces *one* value of output, which is wrong, and describe in specifically what way it's wrong?  (I **think** we're just talking about the `f` property??)

**Comment by legnaleurc** [comment]
```
var safe = {
  f: function () {},
};
var unsafe = cloneInto(safe, unsafeWindow, {
  cloneFunctions: true,
});

// expected to be a function, but it's undefined
console.info(unsafe.f);
```

**Comment by arantius** [comment]
Script:
```javascript
// ==UserScript==
// @name        Greasemonkey cloneInto content test
// @namespace   https://github.com/arantius
// @include     http*
// @version     1
// @grant       GM_xmlhttpRequest
// ==/UserScript==

dump('cloneInto script ...');
var script_obj = {'func': function() { alert('Ran script obj func!'); }};
unsafeWindow.script_obj = cloneInto(script_obj, unsafeWindow, {cloneFunctions:true});

function script_func() { alert('ran script func'); }
unsafeWindow.script_func = exportFunction(script_func, unsafeWindow);
dump(' done.\n');
```

Page:
```html
<button onclick="script_func()">Call script_func()</button>
<button onclick="script_obj.func()">Call script_obj.func()</button>
```

I get an alert when clicking the first button, but `TypeError: script_obj.func is not a function` when clicking the second.  If I move that script's code into Greasemonkey directly:

```javascript
function createSandbox(aScript, aContentWin, aUrl, aFrameScope) {
  ...
  dump('cloneInto ext ...');
  var script_obj = {'func': function() { dump('Ran ext obj func!\n'); }};
  aContentWin.wrappedJSObject.script_obj = Components.utils.cloneInto(script_obj, aContentWin.wrappedJSObject, {cloneFunctions:true});

  function script_func() { dump('ran ext func\n'); }
  aContentWin.wrappedJSObject.script_func = Components.utils.exportFunction(script_func, aContentWin);
  dump(' done.\n');

  return sandbox;
}
```

Then both work!  Necessity forced me to switch up how I was referring to the content window.  So the problem must somehow be that the script doesn't have the right window reference, to clone the object into?  I don't know of anything we can change there, though.

**Comment by arantius** [comment]
Note to my future self:

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.Sandbox#options

Do we want to use `wantExportHelpers` ?  Will it help with this?

**Comment by the8472** [comment]
A note here:

```javascript
// @grant       unsafeWindow

var safe = {
  f: function () {},
};
var unsafe = cloneInto(safe, unsafeWindow, {
  cloneFunctions: true,
});

// expected to be a function, but it's undefined
console.info(unsafe.f);
```

1. any `grant` creates the sandbox with an extended principal and turns on xray vision
2. `safe` belongs to the sandbox
3. `unsafe` is an xray wrapper to the cloned object that now lives in the target window
4. xray wrappers on plain javascript objects hide functions
5. the `console.log` *does not try to show `unsafe`* (which may or may not get xray-unwrapped, depending on console context). it tries to get the `f` property first and then hands it to the logger, this fails because the xray wrapper hides the function instance.

Therefore this is an invalid test case, because it only shows what the sandbox sees, not what the content window would see.

**Comment by the8472** [comment]
> Do we want to use wantExportHelpers ? Will it help with this?

just tested with those, seems to work. with the test-case in OP.

**Comment by arantius** [comment]
OP: Does 3.4beta2 fix this?

https://addons.mozilla.org/firefox/downloads/file/341782/greasemonkey-3.4beta2-fx.xpi?src=devhub

**Comment by pwlin** [comment]
Is there any solution to this problem yet?

A simple 
```javascript
// ==UserScript==
// @name        test xmlhttp
// @namespace   http://example.com/
// @include     http://wiki.greasespot.net/GM_xmlhttpRequest
// @version     1
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  method: "GET",
  url: "http://www.google.com/",
  onload: function(response) {
    alert(response.responseText);
  }
});
```
Fails with:
`Components.utils.cloneInto is not a function`
`chrome://greasemonkey-modules/content/xmlhttprequester.js (Line 303)`

It happens with Greasemonkey `3.3` as well as `3.4` on Firefox ESR
