### ISSUE TITLE
scripts are not syncing over the new firefox sync

### ISSUE THREAD

**Issue by ka223** [greasemonkey/greasemonkey#2071]
Hi,

my scripts are not syncing.
The sync option is activated at the greasemonkey (version 2.3) plugin settings.
settings screenshot:
http://www.directupload.net/file/u/58407/tim3n3w4_png.htm

Regards,
ka223

**Comment by chimericdream** [comment]
I am getting the same issue. I have sync enabled, but none of my scripts are syncing across browsers. It looks like the new sync whitelists the type of items to sync. I get the following error for _all_ GM scripts in the sync log:

```
1422640104115	Sync.Store.Addons	DEBUG	userscripts-mirror.org/Feedly Unread Count in Favicon and Title Bar@greasespot.net not syncable: type not in whitelist: greasemonkey-user-script
```

The key part, I think, is the message `type not in whitelist: greasemonkey-user-script`. This seems to imply that the plugin needs to be updated to add user scripts to the whitelist for Firefox sync.

**Comment by arantius** [comment]
Note to self: test version 3.2 to see if above commit helps.

**Comment by arantius** [comment]
*mumble grumble*

I've deferred switching to "new sync" as long as I could.  Old sync pairing is no longer available at all.  Now I can't set up a testing profile to even begin to work on sync related issues.  The setup of a local test sync service is much more heavyweight now.  Bah!

**Comment by arantius** [comment]
Well I got a test instance set up enough to get data to flow; I just watched scripts literally appear on the screen, the ones that were installed on the other test profile on the other side of the Sync connection.  I'm calling this fixed.

**Comment by VengefulAncient** [comment]
So is this supposed to be fixed in 3.2? Unfortunately, I'm still experiencing the same problem, though everything else Syncs as expected.

**Comment by Coolius70** [comment]
I tried gm sync yesterday and it does not seem to work at all. GM 3.2 and FF 38.0.5. Very disappointing for the first try.

**Comment by VengefulAncient** [comment]
Why is this issue marked as closed? It still isn't fixed.

**Comment by arantius** [comment]
[Yes](https://github.com/greasemonkey/greasemonkey/issues/2071#issuecomment-106918550)?  If you still have problems please open a new ticket where any new work can be tracked.
