### ISSUE TITLE
Auto update of scripts stored on a local server

### ISSUE THREAD

**Issue by JohnBac** [greasemonkey/greasemonkey#2072]
I've got the following in my script and force secure updates turned off, but FF does not update the script when I change it.
Can somebody please explain? Thanks.
// @downloadURL		http://sdbeapp32014/DMSTest/GMScripts/sdpusers.user.js
// @updateURL		http://sdbeapp32014/DMSTest/GMScripts/sdpusers.user.js

**Comment by arantius** [comment]
Working as intended. If you edit the script we intentionally do not overwrite your changes with updates.

**Comment by JohnBac** [comment]
Thanks for the answer.
The question is how can I keep a script on an in-house server that is shared amongst several colleagues and automatically update their copies of the script whenever I make updates?

Regards,
John Bacon
John Bacon
Support Engineer (Contractor: Contraste Europe)
ING Belgium, Cours Saint Michel 60 (-2), 1040 Bruxelles, Belgium
Direct: +32 (0)2 73 86689, john.bacon@ING.be<mailto:john.bacon@ING.be>
ESLC_T Support, DMSII, +32 (0)2 73 84242, eslct.dmsii@ING.be<mailto:eslct.dmsii@ING.be>

**Comment by arantius** [comment]
Whoops, I might have jumped the gun on my interpretation of "when I change it".  I meant: if you edit the local copy, i.e. you are a developer working on improving the script.

If "when I change it" means "upload a new version to the server", and end users that have never edited the installed script don't get updates, my response above was inappropriate.

It might be a good idea to head to the greasemonkey-users support list to ask this question, this doesn't quite sound like a bug report yet.

**Comment by JohnBac** [comment]
You’re right it wasn’t meant to be a bug report.
I develop the script on a test server and then upload it to the production server (all in-house, the script is of no use to the wide world)
I need the local in-house users to automatically see the updated script when it is uploaded to the server.
I can’t see how to make that happen.
Regards,
John Bacon
John Bacon
Support Engineer (Contractor: Contraste Europe)
ING Belgium, Cours Saint Michel 60 (-2), 1040 Bruxelles, Belgium
Direct: +32 (0)2 73 86689, john.bacon@ING.be<mailto:john.bacon@ING.be>
ESLC_T Support, DMSII, +32 (0)2 73 84242, eslct.dmsii@ING.be<mailto:eslct.dmsii@ING.be>
