### ISSUE TITLE
Localized version of firefox - copy paste typing 'allow paste' doesn't work

### ISSUE THREAD

**Issue by Miserable-Clown** [greasemonkey/greasemonkey#2074]
Please add a button or remove it instead. I can't paste anything!
Typing "tillåt klistring" doesn't work! It is completely broken! WTF with localization!?

I can not even change to english to figure out the right translation.

**Comment by arantius** [comment]
I don't understand what you're saying or why it has anything to do with Greasemonkey?

**Comment by Miserable-Clown** [comment]
Apologies, I was a bit drunk.

1. Greasemonkey button menu -> new script
2. CTRL + V (paste from clipboard)

This is what I'm talking about.
![paste_blocker](https://cloud.githubusercontent.com/assets/9258311/5789318/00660874-9e66-11e4-896c-82a2fcb88ff8.png)

**Comment by arantius** [comment]
This is apparently a Firefox feature.

https://bugzilla.mozilla.org/show_bug.cgi?id=994134

**Comment by Miserable-Clown** [comment]
Thanks for the link.
Yet another aggravating annoyance "security" feature that doesn't work.
At least in Firefox you can disable them.

For others with the same problem. You disable it by going to about:config and set "devtools.selfxss.count" to a high number eg 999.
