### ISSUE TITLE
GM_listValueot work on firefox 35 anymore

### ISSUE THREAD

**Issue by deltamarkus** [greasemonkey/greasemonkey#2076]
Hello GM_listValue don't work anymore
but someone has an fix for greasymonkey 
see this link  https://greasyfork.org/de/forum/discussion/2918/issue-with-gm-getvalue-from-gm-listvalues-array-in-firefox#latest
please update the greasemonkey version

thank you

**Comment by arantius** [comment]
Dupe of #2033.
