### ISSUE TITLE
GM_listValues returns an array of nulls

### ISSUE THREAD

**Issue by lukeIam** [greasemonkey/greasemonkey#2077]
When `GM_listValues()` is called, an array like this is returned: `[null, null]`
The length of the array is correct, but there are no keys of the stored variables.

Example script:
```JS
// ==UserScript==
// @name        Test
// @namespace   test
// @description test
// @version     1
// @grant       GM_setValue
// @grant       GM_listValues
// ==/UserScript==
GM_setValue("Test","Just a test");
alert(JSON.stringify(GM_listValues()));
```

**Comment by arantius** [comment]
Dupe of #2033.

**Comment by lukeIam** [comment]
sorry for that -> the search for "GM_listValues" didn't show up with that one.
->I'll closethis one
