### ISSUE TITLE
[Question] How does grant none work

### ISSUE THREAD

**Issue by Shadow-pt** [greasemonkey/greasemonkey#2078]
I am trying to understand how the `grant none` feature works in greasemonkey from an addon point of view. I am creating a simple addon that will only insert a userscript.user.js file into a page that meets the url mask, but so far I am using a content script injection technique:
````javascript
var source = function() {
<-Original code is here->
};
var insert = document.createElement('script');
insert.textContent = "(" + source + ")()";
document.head.appendChild(insert);
````

This works for my addon and with Greasemonkey as well (even if grant is none), however what I want is to not have to use a script injection technique and instead run the script on the page just like how `grant none` does, no need to use `unsafeWindow` either. Simply run as if it was a script that was loaded with the page itself.

I have tried looking for documentation that could explain how your `grant none` works, but so far I had no luck. I am stuck with the addon's pageMod + contentScriptFile technique and that's it.

**Comment by arantius** [comment]
1. http://wiki.greasespot.net/@grant
2. Please use the [mailing list](http://groups.google.com/group/greasemonkey-users) for support.  This is for bug reports.

**Comment by Shadow-pt** [comment]
Sorry, couldn't find a specific direction for this kind of question. I had also read the wiki, it simply explains how the feature works from a user perspective, it does not explain how it works from an addon perspective, which is what I am trying to understand. Will use the mailing list from now on, thanks.
