### ISSUE TITLE
Greasemonkey addon breaks firefox profiler

### ISSUE THREAD

**Issue by rewtwa3** [greasemonkey/greasemonkey#2080]
Firefox 35.0
Windows 7

If Greasemonkey addon is enabled then firefox built in dev tools performance/javascript profiler doesn't work.

**Comment by her34** [comment]
This problem makes it difficult to measure performance of scripts.

Steps to reproduce
1) toggle developer tools
2) start recording performance
3) reload tab
4) stop recording performance
5) error: graph never appears. firefox is stuck on loading.

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
Firefox 38.0.1 - Firefox Nightly 41.0a1 (2015-05-15), GM 3.2beta2
(tested in a clean profile + GM)

**Comment by janekptacijarabaci** [comment]
Confirmed on:
Firefox 38

Not confirmed on:
Firefox 39+

RESOLVED FIXED:
https://bugzilla.mozilla.org/show_bug.cgi?id=1139388
