### ISSUE TITLE
GM 2015-1-29 nightly: no scripts run

### ISSUE THREAD

**Issue by 514guy** [greasemonkey/greasemonkey#2082]
Windows 7 Ultimate x86 with ABP dev build, Element Hiding Helper, JRE 8.0.31, on Firefox stable 35.0.1. Using GM stable, or the 2014.10.29 nightly, works as expected. However, when I update to the 2015.1.29 nightly, no scripts are functioning, and no scripts can be added.

**Comment by janekptacijarabaci** [comment]
See https://github.com/greasemonkey/greasemonkey/issues/2004#issuecomment-72161349

**Comment by arantius** [comment]
My own notes:  GM as of f249351140408712963587ef5616c1bcc0ea5a08 which is effectively nightly as in original report.  Firefox 38.0a1 (2015-02-02).

Confirmed.  Scripts just plain don't run.  No errors logged anywhere I can see.

GM as of 987f7f3e92ed550d15ab4b6318cca6f944ac27b1 (parent commit of above): scripts run.  That commit broke something, definitely.
