### ISSUE TITLE
Is there a way to send a GM_xmlhttpRequest without cookies and/or redirects?

### ISSUE THREAD

**Issue by brunoais** [greasemonkey/greasemonkey#2084]
Is there a way to call GM_xmlhttpRequest and not have it follow redirects and/or not send cookies?

**Comment by arantius** [comment]
Cookies or redirects?  Or both?

**Comment by brunoais** [comment]
Sorry about that. Fixed.

**Comment by whatUwant** [comment]
I have a similar request: it would be great if a GM_xmlhttpRequest can be sent without any cookies.

**Comment by janekptacijarabaci** [comment]
See also #2235 (#2254)

**Comment by Celelibi** [comment]
About not following redirects, there's a bug report for firefox since 2008. I guess someone has to implement it to get it done.

https://bugzilla.mozilla.org/show_bug.cgi?id=454644

**Comment by janekptacijarabaci** [comment]
See also http://stackoverflow.com/questions/3820663/is-it-possible-for-xhr-head-requests-to-not-follow-redirects-301-302
