### ISSUE TITLE
Allow script metadata tag @include on blob URL

### ISSUE THREAD

**Issue by Tyf0x** [greasemonkey/greasemonkey#2085]
Hi,

I'm in the need of executing a script on a blob URL page/iframe.

Typically I retrieve a PDF with ajax then generate a blob url from the data. This url is then used as the src of an iframe an look like this: 

```
blob:http://www.XXXXXXXXXX.com/76b5835a-e9e2-4a14-b9f8-7c4cda83377a#type=label&printQty=2
```

Example of meta-tag I used and failed to work:

```
// @include /^blob:(.+?)#(.+?&)?(type=(label|docket)).*/
```

Would it be possible to support script injection in blob URL windows (if this doesn't open a security issue)?

Thanks!

**Comment by arantius** [comment]
Possible?  Of course.  Does it open security issues?  I don't know, but I'm worried that it would.
