### ISSUE TITLE
Scripts running twice when run-at: document-start in Firefox Nightly 38.0a1 (2015-02-07)

### ISSUE THREAD

**Issue by Yonezpt** [greasemonkey/greasemonkey#2086]
Greasemonkey version 2.3

Sample script

````javascript
// ==UserScript==
// @name        Test
// @namespace   Test
// @version     1
// @run-at      document-start
// @match       https://www.google.com/*
// @grant       none
// @noframes
// ==/UserScript==
console.info('Ping');
````

Open https://www.google.com/ and observe the console.

![ss](https://cloud.githubusercontent.com/assets/8498057/6095239/927931d2-af41-11e4-87c5-5d04ade27eb9.png)

The string 'Ping' should only appear once, instead it shows twice.

This does not happen if `run-at` is set to `document-end` or not set (which defaults to `document-end`).

**Comment by janekptacijarabaci** [comment]
Confirmed on: Greasemonkey 2.3
Not confirmed on: Greasemonkey Nightly (2015.02.02)

**Comment by Yonezpt** [comment]
I forgot to include the addon version that I am using, which is v2.3

@janekptacijarabaci Is it safe for me to assume that this GM v2.3 problem has already been addressed and fixed in the GM Nightly version?
