### ISSUE TITLE
weird array behaviour inside a loop?

### ISSUE THREAD

**Issue by Kengur8** [greasemonkey/greasemonkey#2088]
Hey.

I have this function (log is short for console.log)

```javascript
    function matchString(match, list) {
        var mylist = [];
        if (list !== undefined && list !== null) {
            for (var i = 0; i < list.length; i++) {
                log(match);
                log(list);
                log(list[0]);
                if (list[i].indexOf(match) >= 0) {
                    mylist.push(list[i]);
                }
            }
        }
        return mylist;
    }
```

which works perfectly normal in Tampermonkey. But in Greasemonkey I get this in the log

"tf2stars-cache_sound@tf2stars-sound_heavy"
Array [ "tf2stars-cache_data@20150209", "tf2stars-cache_motd@20150209", "tf2stars-cfg" ]
undefined

For some weird reason when i change this

```javascript
if (list !== undefined && list !== null) {
```

to my custom function

```javascript
if (!isEmpty(list)) {
```

it work ok!

**Comment by arantius** [comment]
This report is incomplete.  Knowing, at a minimum, which values of match and list are getting passed in, is important.  Without that, I could only randomly guess.
