### ISSUE TITLE
exportFunction will silently fail and not return?

### ISSUE THREAD

**Issue by Kengur8** [greasemonkey/greasemonkey#2089]
Hey again.

I'm trying to overwrite target window function like this

```javascript
exportFunction(function() { return 0; },
                unsafeWindow, { defineAs: "blahblah" });
```

if "blahblah" exists exportFunction will silently fail and not return?

**Comment by Tyf0x** [comment]
Would this be related? https://github.com/greasemonkey/greasemonkey/issues/1959

**Comment by Kengur8** [comment]
Probably not, because other two exportFunction in the same script work fine.

**Comment by arantius** [comment]
A good bug report is always a *complete* user script.  If I wave my magic wand and guess what your script might be:

```javascript
// ==UserScript==
// @name        Export content_func
// @namespace   https://github.com/arantius
// @include     http://localhost/*
// @version     1
// @grant       none
// ==/UserScript==

window.content_func = function() { dump('script overrode content_func!\n'); }
```

Well that works perfectly.  You mention `exportFunction()` so you must not be using `@grant none` ...

```javascript
// ==UserScript==
// @name        Export content_func
// @namespace   https://github.com/arantius
// @include     http://localhost/*
// @version     1
// @grant       GM_log
// ==/UserScript==

function script_func() { dump('script overrode content_func!\n'); }
var exp_func = exportFunction(script_func, unsafeWindow);
unsafeWindow.content_func = exp_func;
```

That also works exactly as I expect.  I guess `define_as` doesn't do what you want it to.
