### ISSUE TITLE
The items in "User Script Commands" to be sorted by script execution order

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2090]
Currently, clicking on the GM toolbar dropdown button
it shows the scripts sorted by execution order (see the screenshot)

But, the items items in "User Script Commands" seem to be sorted differently.
To reproduce, install two scripts (with the given order) that offer such commands, 
eg. [Mouseover Popup Image Viewer](https://greasyfork.org/scripts/404-mouseover-popup-image-viewer) and [YouTube Link Title](https://greasyfork.org/en/scripts/413-youtube-link-title).
Then open a page, eg. www.github.com (wait for the loading to finish).

If now you click to expand the "User Script Commands" list 
you'll see that the entries appear as in the screenshot:
![screenshot 308](https://cloud.githubusercontent.com/assets/723651/6203257/7d339b7a-b520-11e4-8583-765cec843c0d.png)

I suggest that these entries should also be sorted by execution order.

**Comment by TimidScript** [comment]
The order of execution has no effect on the command menu, so alphabetical makes more sense than execution order.

**Comment by jerone** [comment]
Order by execution isn't even completely true as UserScripts can add a command menu-item any time they want (`setTimeout`). I agree that making it alphabetic makes more sense then the random order it is now. I do wonder if UserScripts authors are going to prefix the menu-items to put then on top (e.g. `1) First item`).
