### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Bogmen** [greasemonkey/greasemonkey#2091]
There is a new version of Firefox 36.0 and greasemonkey don't work anymore.
We need a new version of greasemonkey.

**Comment by jerone** [comment]
This issue title can be a little bit more descriptive.
No issues with FF 36.0/20150222232811 here.
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0`

**Comment by JohnBac** [comment]
Just updated to FF 36.0. My GM scripts run fine.

**Comment by arantius** [comment]
Reopen if you're having issues and you can provide more detail.
