### ISSUE TITLE
GM 3.0B1 GM_openInTab opens 5 tabs

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [greasemonkey/greasemonkey#2094]
i put a `alert` right before it runs `GM_openInTab` an i get 1 alert and 5 tabs
obviously it should only open 1 tab
`Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0`

**Comment by arantius** [comment]
Can you provide a reduced test case?  My standard testing script ( https://gist.github.com/arantius/1157543 ) works as expected.

**Comment by GM-Script-Writer-62850** [comment]
Addons:
http://i.imgur.com/l9xfcaW.png
Browser version:
http://i.imgur.com/g4ZynS6.png
Script:
```
// ==UserScript==
// @name        GM_openInTab
// @namespace   http://userscripts.org/users/62850
// @description Test
// @include     http://www.dd-wrt.com/phpBB2/viewtopic.php?t=171400&start=270
// @version     1
// @grant       GM_openInTab
// ==/UserScript==
GM_openInTab('http://google.com');
```

**Comment by ccd0** [comment]
I'm seeing this too, but at different times, it gives me 1, 2, or 5 tabs, and I haven't figured out why.  I was getting 2 tabs from the following, but after restarting my browser, it's 1 again:

    // ==UserScript==
    // @name        new tab test
    // @namespace   test
    // @include     http://example.com/
    // @version     1
    // @grant       GM_openInTab
    // ==/UserScript==
    
    document.body.addEventListener('click', function() {
      GM_openInTab('http://www.google.com/');
    }, false);

Using `Mozilla/5.0 (X11; Linux i686; rv:36.0) Gecko/20100101 Firefox/36.0 Iceweasel/36.0`.

**Comment by GM-Script-Writer-62850** [comment]
here is another test script
```
// ==UserScript==
// @name        GM_openInTab
// @namespace   http://userscripts.org/users/62850
// @description Test
// @include     *
// @version     1
// @grant       GM_openInTab
// @grant       GM_registerMenuCommand
// ==/UserScript==
GM_registerMenuCommand("GM_openInTab Test",function(){
	alert("`GM_openInTab('http://google.com')` will now be run");
	GM_openInTab('http://google.com');
});
```

**Comment by ccd0** [comment]
Currently getting 4 tabs, and seeing this in the browser console:

    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] framescript.js:283:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content.js:677:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content-sessionStore.js:178:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] framescript.js:283:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content.js:677:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content-sessionStore.js:178:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] framescript.js:283:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content.js:677:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content-sessionStore.js:178:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] framescript.js:283:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content.js:677:0
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content-sessionStore.js:178:0

**Comment by ccd0** [comment]
Currently I'm getting 3 tabs per call.  It goes back to 1 tab per call when I restart my browser.  I updated my test script to

    // ==UserScript==
    // @name        new tab test
    // @namespace   test
    // @include     http://example.com/
    // @version     1
    // @grant       GM_openInTab
    // ==/UserScript==

    document.body.addEventListener('click', function() {
      console.log('before calling GM_openInTab');
      GM_openInTab('http://www.example.com/');
      console.log('after calling GM_openInTab');
    }, false);

and this is what I get in the browser console after clicking 3 times (opening 9 tabs):
http://pastebin.com/uXQrjhUs

These are the extensions I have enabled at the moment. Nothing in common with GM-Script-Writer-62850 other than Greasemonkey.

![screenshot from 2015-03-08 21 13 45](https://cloud.githubusercontent.com/assets/5894749/6549884/7eb12968-c5d8-11e4-90eb-2a842e2d2412.png)

**Comment by arantius** [comment]
Firefox 39 (nightly), e10s enabled, Greasemonkey development at current head.  Installed all the scripts from above, always get exactly one tab as expected.

**Comment by GM-Script-Writer-62850** [comment]
retested using 3.0b1 on ff 38a2 and i got 1 tab, perhaps this was a firefox bug?

**Comment by penguishPenguin** [comment]
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:37.0) Gecko/20100101 Firefox/37.0

I got tabs as many as Firefox windows.
For example, I get 5 tabs when I open 5 Firefox Windows.

**Comment by GM-Script-Writer-62850** [comment]
now i am getting 3, i only have 1 window, but it is probably cause of single window mode

**Comment by penguishPenguin** [comment]
I tested more closely.

The number of tabs I get is as many as the number of windows I opened.
For example, when I start up Firefox and open 4 Firefox windows, (I have 5 Firefox windows)
I get 5 tabs.
And then, I close 4 Firefox windows, (I have 1 Firefox window)
I get 5 tabs.
And Then I open 5 Firefox windows,
I get 10 tabs.

**Comment by janekptacijarabaci** [comment]
Global message manager => Window message manager ?

https://github.com/greasemonkey/greasemonkey/blob/master/content/browser.js#L15

The suggestion (for example):

From:
```javascript
  var messageManager = Components.classes["@mozilla.org/globalmessagemanager;1"]
      .getService(Components.interfaces.nsIMessageListenerManager);
```

To:
```javascript
  var messageManager = window.messageManager;
```

**Comment by arantius** [comment]
Multi-window-opened condition bug confirmed, @janekptacijarabaci 's proposed fix confirmed.

**Comment by arantius** [comment]
This fix is now included in version 3.1beta1.  Please browse to [Greasemonkey's AMO page](https://github.com/Ventero/greasemonkey/commit/b8a09369482f87d0d9fa8afb39b5f46439eab0c2) and open "Development Channel" near the bottom to install the beta version.  Can you confirm the fix?  Thank you.

**Comment by GM-Script-Writer-62850** [comment]
seems good so far

**Comment by ccd0** [comment]
Working here, thanks.

**Comment by jkondratowicz** [comment]
Works, but the behavior of `GM_openInTab` has changed - it no longer obeys `browser.tabs.loadInBackground`. Before latest updates, new tab was opened in background (because of my FF settings), now browser automatically switches to it.

**Comment by janekptacijarabaci** [comment]
@jkondratowicz: See #2105 and #2106.

**Comment by LyKP** [comment]
Installed the 3.1beta1 directly from here https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/versions/

GM_openInTab works as expected now, i.e. a single tab is opened.
