### ISSUE TITLE
Support magic TLDs in the @match metadata block

### ISSUE THREAD

**Issue by DerpMcDerp** [greasemonkey/greasemonkey#2096]
Extend the `@match` metadata block so that `@match http://*.foo.*/whatever` and/or `@match http://*.foo.tld/whatever` work.

**Comment by arantius** [comment]
This would introduce incompatibilities with other user script engines that support `@match`, and negate some of the security benefits.

**Comment by DerpMcDerp** [comment]
If you're worried about security, you could also support an explicit whitelist of the tlds (e.g. `@match http://*.foo.(net|com|co.uk)`) and have greasemonkey filter the given tlds against the magic tld list.
