### ISSUE TITLE
Unable to call toString on GM_getValue

### ISSUE THREAD

**Issue by ktsashes** [greasemonkey/greasemonkey#2097]
Originally in one of my scripts I had a check for the existence of `GM_getValue`, but I hit a bug where some clients were reporting it was present, but would simply `return 'not supported';` when called. So I implemented a second part to the check, which `toString()`'d the function and checked for that string. As of the latest update, however, that check has an issue.

> Error encountered while calling toString.
> Permission denied to access property 'getValue'

I've since patched the script and removed that. Hopefully other userscript clients no longer return the 'not supported' string, but if not I'll have to try and figure something else out. Here's a small script to show the error:

    // ==UserScript==
    // @name        toString Error
    // @namespace   imgimeme.com
    // @include     https://github.com/greasemonkey/greasemonkey
    // @version     1
    // @grant       GM_getValue
    // ==/UserScript==
    try {
        GM_getValue.getValue.toString();
    } catch (e) {
        window.alert('Error encountered while calling toString.\n' + e.message);
    }

**Comment by janekptacijarabaci** [comment]
AFAIK: This bug is fixed for me, too:
https://github.com/greasemonkey/greasemonkey/issues/2129

**Comment by arantius** [comment]
TODO(me): Verify that the above mentioned change also fixed this.

**Comment by arantius** [comment]
As-is, it compliains that `GM_getValue.getValue` is undefined, which is quite true.  If I take out the second incorrect `.getValue`, then it works as expected (if I `alert()` it I get `function () { [native code] }`).

To the OP: In general the right way to do this is to just detect behavior: in this case that would be something like do any set to some sentinel key, do another get, and verify that the value you get back is the value you put in.  If so: it works.

**Comment by ktsashes** [comment]
@arantius Yes, that is a better way to do it. The code I was referring to here was **very** legacy code and has since been cleaned up/cleared out. Thanks
