### ISSUE TITLE
userscript updates activate deactivated userscripts

### ISSUE THREAD

**Issue by Djfe** [greasemonkey/greasemonkey#2098]
if a userscript gets updated Greasemonkey will activate it even if it was disabled before

this is no desired behaviour

**Comment by arantius** [comment]
What does "gets updated" mean?  Everything I've tried keeps them disabled.

**Comment by Djfe** [comment]
What I mean by "gets updated" is: the meta file on the server (that is linked in the client's meta header of the userscript file) announces: "There is an update" -> Greasemonkey updates the userscript from the linked release script.

It shows a header next to the url bar "script x has been updated".
-> I open the addon page and take a look at the list of userscripts and the userscript that just got updated is suddenly activated which it wasn't before the update

I'm developing a userscript.
There is a dev version and a release version.
I only want to have one activated at a time.
If I push another update to my repo greasemonkey will update the release version and activate it which causes problems if i don't notice that both of them are activated at the same time now.

**Comment by arantius** [comment]
Yeah.  Confusing.  Because disabled scripts don't update:

https://github.com/greasemonkey/greasemonkey/blob/master/modules/script.js#L589

So I'm not sure how to proceed.  Some path is passing a force update when it shouldn't?

**Comment by tobbexiv** [comment]
Do you have example code?

I have an Idea why it might be the case: You have an update uri given in both Scripts and it points to the same location (the update location of the production script). Now the disabled production script does not check for updates, but the enabled development script does. Therefore it is recognized to have a new version. Now the update will take place and as it is the update location of the production script, the meta keys match the production script which will get overwritten and activated. To you now it seems that the production script updated itself, but in fact the development script triggered the update.

**Comment by Djfe** [comment]
Header of the master script:
```// ==UserScript==
// @name            Steamgifts++
// @namespace       https://github.com/leomoty/SGPP
// @version         0.3.0 beta
// @description     SG++ for Steamgifts.com
// @author          Leomoty
// @match           http://www.steamgifts.com/*
// @run-at          document-end
// @downloadURL     https://raw.githubusercontent.com/leomoty/SGPP/master/SGPP.user.js
// @updateURL       https://raw.githubusercontent.com/leomoty/SGPP/master/SGPP.meta.js
// @require         http://code.jquery.com/jquery-2.1.3.min.js
// @require         https://raw.githubusercontent.com/dinbror/bpopup/master/jquery.bpopup.min.js
// @resource head   https://raw.githubusercontent.com/leomoty/SGPPSettings/4c83a645dcf111be2fb8b9e1da8b856fa510929c/head.html
// @resource settings   https://raw.githubusercontent.com/leomoty/SGPPSettings/4c83a645dcf111be2fb8b9e1da8b856fa510929c/settings.html
// @grant           GM_addStyle
// @grant           GM_getResourceText
// ==/UserScript==```

Header of the beta version
```// ==UserScript==
// @name            Steamgifts++ Dev
// @namespace       https://github.com/leomoty/SGPP
// @version         0.2.2 beta
// @description     SG++ for Steamgifts.com
// @author          Leomoty
// @match           http://www.steamgifts.com/*
// @include         http://www.steamgifts.com/*
// @run-at          document-end
// @require         http://code.jquery.com/jquery-2.1.3.min.js
// @require         https://raw.githubusercontent.com/dinbror/bpopup/master/jquery.bpopup.min.js
// @resource head   https://raw.githubusercontent.com/leomoty/SGPPSettings/master/head.html
// @resource settings   https://raw.githubusercontent.com/nikop/SGPPSettings/gamesfilter/settings.html
// @grant           GM_addStyle
// @grant           GM_getResourceText
// @grant			GM_xmlhttpRequest
// ==/UserScript==```

The last time I used it/developed it was some month ago, the headers have a changed a bit since then. Maybe it's still happening, I would need to check that.
I'm not sure whether the dev version ever had an updateurl string, but it could be the issue
