### ISSUE TITLE
GM_xhr error in multi-process Firefox when referrer is set

### ISSUE THREAD

**Issue by kuehlschrank** [greasemonkey/greasemonkey#2103]
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:39.0) Gecko/20100101 Firefox/39.0
Greasemonkey 3.0beta1

```javascript
// ==UserScript==
// @name        Test
// @include     *
// @grant       GM_xmlhttpRequest
// ==/UserScript==

	GM_xmlhttpRequest({
		method:  'GET',
		url:     'http://example.com/',
		headers: {'Referer': 'http://example.org/'},
		onload:  function(res) {
			console.log(res.status);
		}
	});
```

Error in console:
Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIObserverService.addObserver]1 Test.user.js:159:0

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1143006

**Comment by arantius** [comment]
I'm gonna throw a try/catch to ignore this in for 3.0 and hope for a real fix in 3.1.

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1108827 ?

**Comment by arantius** [comment]
Work around so that at least the script doesn't completely fail is still in place.  According to https://bugzilla.mozilla.org/show_bug.cgi?id=1143006#c8 this needs to be yet another big rewrite to work in e10s because only the child process knows the value to rewrite, but only the parent process can access this api to write it.  Moving to 3.2.

**Comment by arantius** [comment]
If I run this script
```javascript
// ==UserScript==
// @name        GM_xhr with referer
// @include     *
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  method:  'GET',
  url:     'http://localhost/h.php',
  headers: {'Referer': 'http://example.org/'},
  onload:  function(res) {
    console.log(res.responseText);
  }
});
```
Where said php is
```php
<?var_dump($_SERVER['HTTP_REFERER']);?>
```
I get `string(19) "http://example.org/"` in the console.  This is in nightly 42 with E10S on.  Something changed upstream, I guess?
