### ISSUE TITLE
GM3.0: GM_openInTab doesn't respect browser.tabs.loadInBackground

### ISSUE THREAD

**Issue by roger21** [greasemonkey/greasemonkey#2106]
in GM 3.0 the value given for aLoadInBackground in modules/miscapis.js is forced to a boolean value with the double "!" at line 118

the value of aLoadInBackground is most likely always null since it is never defined or retrieved at line 112 of modules/miscapis.js

if the value of aLoadInBackground is left to null GM_openInTab DOES respect browser.tabs.loadInBackground

with the "!!", aLoadInBackground is forced to false and GM_openInTab will always open new tab in foreground 

the "!!" at line 118 should be removed, no other modification needed

**Comment by arantius** [comment]
Dupe of #2105.
