### ISSUE TITLE
GM3.0: tabs created by GM_openInTab don't end up in the "last closed tabs lists" when closed

### ISSUE THREAD

**Issue by roger21** [greasemonkey/greasemonkey#2107]
either by using the native "reopen last closed tab" feature or using a list (tab mix plus or undo closed tab button), the tabs opened with GM_openInTab can't be reopen when closed (they don't exist anymore ..... they are dead man! DEAD!)

(just to clarify, it was not the case in the previous version of GM)

**Comment by erosman** [comment]
I have also noticed that middle clicking the refresh icon, to duplicate the tab, does not work with tabs opened by GM_openInTab as it opens a blank page.

**Comment by rgant** [comment]
Same issue, but also I've noticed that the `GM_openInTab` command doesn't respect `browser.tabs.loadInBackground`. Although no longer [documented](http://wiki.greasespot.net/GM_openInTab) if I pass a second parameter of `true` after the URL then the tabs do open in the background as I desire. The second parameter doesn't change the root issue that tabs opened by GM are not restored when reloading Firefox.

**Comment by janekptacijarabaci** [comment]
@rgant: (browser.tabs.loadInBackground) See #2105.

**Comment by arantius** [comment]
At least after fixing #2105, tabs all behave as expected.  Please reopen only if a build (3.2 or one of its betas) including that fix still has problems.

**Comment by roger21** [comment]
this is not fixed in 3.2

when you open a tab with gm_openintab and then close it, it is gone forever, you can't re-open it like any other tab

sometimes it works though (in a very thin case):
in one of my scripts i have a straight for loop that increments the page parameter of a url and open each url in a new tab, the first opened tab is lost forever but the other ones can be reopen as any other tab

all my other scripts that retrieve urls from the current page and open them in new tabs with gm_openintab create un-reopenable tabs once they are closed

(none of them specify the new open_in_background parameter)

**Comment by arantius** [comment]
If I install [this script](https://gist.github.com/arantius/1157543), click the "Test GM_openTab" button, then press Ctrl-W, Ctrl-T, the tab reopens.  If I look in History>Recently Closed Tabs, that tab is the first one listed.

If you can post a concrete reduced test case script and describe exactly what fails about it, great.  If not, as best I can tell this is all working.

**Comment by roger21** [comment]
ok, indeed my failing scripts are not that simple and all my attempts to create a simple failing script failed (they worked fine, closed tabs are reopenable) still, my complex-existing-scripts do fail (some tabs or all tabs can't be reopen) i'll try more later :/

**Comment by roger21** [comment]
ok so i found the problem in one of my script

it is a call to GM_getValue that screw up the call to GM_openInTab (the tabs can't be reopened once closed)

here is a basic example that works on this page only and open the 3 next issues: http://roger21.free.fr/test/test_gm_openintab.user.js

my other failing script is not similar but i would hope it is caused by the same core problem...

**Comment by janekptacijarabaci** [comment]
Confirmed on:
Firefox 39 - Firefox 42.0a1 (2015-08-02) - __e10s: off__

No confirmed on:
Firefox Aurora/Developer Edition 41.a2 (2015-08-02) - Firefox 42.0a1 (2015-08-02) - __e10s: on__

**Comment by roger21** [comment]
i added the "usual work around" using window.setTimeout to call GM_openInTab...
http://roger21.free.fr/test/test_gm_openintab_2.user.js
it also works for my other script

**Comment by janekptacijarabaci** [comment]
Is there a problem with sending messages?

After applying this change:
https://github.com/greasemonkey/greasemonkey/compare/master...janekptacijarabaci:_testBranch_GM_openInTab_lastClosedTabsLists_storageFunctions

Confirmed on:
Firefox 40 Beta1 - Firefox Nightly 42.0a1 (2015-08-02) - __e10s: off__

No confirmed on:
__Firefox 39__
Firefox Aurora/Developer Edition 41.a2 (2015-08-02) - Firefox Nightly 42.0a1 (2015-08-02) - __e10s: on__

**Comment by arantius** [comment]
> Is there a problem with sending messages?

You make me laugh.  The message manager is the most hair-pullingly difficult thing in recent memory.  It's exceedingly difficult to get it to work as expected, among the half dozen or so kinds of managers there are, and several kinds of contexts each of them may be operating in.

There's pretty definitely an invisible problem somewhere.

**Comment by janekptacijarabaci** [comment]
Nobody says it's easy.
It was an attempt.

**Comment by janekptacijarabaci** [comment]
It's still a bit strange... But this works:

__modules/storageFront.js__

From:
``` javascript
this._messageManager.sendSyncMessage
```
To:
``` javascript
this._messageManager.sendRpcMessage
```

**Comment by roger21** [comment]
since firefox 40 i can only reopen the first one from "i work" and "i work around"

so they don't work anymore but "i don't work" still don't work tatally

**Comment by roger21** [comment]
with the patch on __ff39__ with my old customized profile everything works (and also my old scripts and my modified script): all tabs are reopenable (and closable)

**Comment by roger21** [comment]
with the patch on __ff40__  with my old customized profile it is the same as without the patch for "i work and "i work around" (i can only reopen the first one), "i don't work" stay fixed though

**Comment by janekptacijarabaci** [comment]
The new test patch...
https://github.com/greasemonkey/greasemonkey/compare/master...janekptacijarabaci:GM_openInTab_closable_reopenable

**Comment by roger21** [comment]
all cases, all perfect

thank you very many

**Comment by arantius** [comment]
Does 3.4beta2 fix this?

https://addons.mozilla.org/firefox/downloads/file/341782/greasemonkey-3.4beta2-fx.xpi?src=devhub

If not this issue should be reopened.

**Comment by roger21** [comment]
> Does 3.4beta2 fix this?

no it does not

**Comment by arantius** [comment]
So when I use my [standard testing script](https://gist.github.com/arantius/1157543), which includes `GM_openInTab`:

1) I can close the tab it opens.
2) I can middle click reload to duplicate the tab it opens.
3) I can close the tab it opens.
4) I can see the tab it opened in the recent list after closing it.

Same if 
How are you seeing any other behavior? Exactly what script on exactly what page, given exactly which action, opens a tab that breaks in the ways described above?

**Comment by janekptacijarabaci** [comment]
This thread is closely related to the thread about #2234...

An example user script:
https://github.com/greasemonkey/greasemonkey/issues/2107#issuecomment-127222951

An example patch:
https://github.com/greasemonkey/greasemonkey/issues/2234#issuecomment-132198817

**Comment by roger21** [comment]
@arantius 

please just try the test script here: https://github.com/greasemonkey/greasemonkey/issues/2107#issuecomment-127222951

it works on this url (this page) : https://github.com/greasemonkey/greasemonkey/issues/2107

the script is very obvious and the code of the script is even more obvious (and you can reproduce it in your own test script by adding the line `var bar=GM_getValue("bar", "pouet");`)

it features one example of the problem, i have another script that has the same problem but i couldn't reduce it to a simple test script, although the solution provided by @janekptacijarabaci solves the problem in all my concerned scripts

**Comment by janekptacijarabaci** [comment]
I waited for confirmation.

**Comment by roger21** [comment]
this is old and i didn't performed comprehensive testing but ifaik / afait this is solved and could be closed

**Comment by roger21** [comment]
same here

this is old and i didn't performed comprehensive testing but ifaik / afait this is solved and could be closed
