### ISSUE TITLE
Script at about:blank stopped working

### ISSUE THREAD

**Issue by klenium** [greasemonkey/greasemonkey#2108]
I have my own script that replaces the newtab's content.

	// ==UserScript==
	// @name newtab
	// @include about:blank
	// ==/UserScript==
	document.body.innerHTML = 'large html';

It worked fine yesterday and before. I didn't change any settings/code. I'm using GM 3.0, but it released 2 days ago, so I don't know why it worked yesterday but doesn't work today.

**Comment by erosman** [comment]
There is an error in console that states:
> about:blank : Unable to run script because scripts are blocked internally.

I am not sure it is due to GM or changes in FF (running 36.0.1)

**Comment by arantius** [comment]
This fix is now included in version 3.1beta1.  Please browse to [Greasemonkey's AMO page](https://github.com/Ventero/greasemonkey/commit/b8a09369482f87d0d9fa8afb39b5f46439eab0c2) and open "Development Channel" near the bottom to install the beta version.  Can you confirm the fix?  Thank you.

**Comment by klenium** [comment]
Yes, it works fine. Thanks.

**Comment by cipriancraciun** [comment]
Looking in the code, the solution I guess was the line below:

    if (/^about:blank/.test(url)) return true;

However this will match any page starting with `about:blank`, including `about:blank-some-other-suffix`.  Although these are less likely, perhaps the regular expression should be anchored also at the end with an `$`, like:

    if (/^about:blank$/.test(url)) return true;

**Comment by arantius** [comment]
This is not an accident.  `about:blank#whatever` is intentionally supported.

**Comment by cipriancraciun** [comment]
Then the correct regular expression would be `/^about:blank(#.*)?$/`.

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/1820
