### ISSUE TITLE
Support @run-at document-idle

### ISSUE THREAD

**Issue by devkev** [greasemonkey/greasemonkey#2109]
Scriptish has a feature where you can specify `@run-at document-idle`.  This runs even later than `document-end`: from the [Scriptish manual](https://github.com/scriptish/scriptish/wiki/Manual:-Metadata-Block#idle-injection) this means:

> Runs a script some time between `document-end` and immediately after the `window-load` (i.e. `window.onload()`) event fires.

I have several scripts that need to run not only after the DOM has been loaded, but also after early page scripts have been run (to fix up some of the mess they make).  In Scriptish this was no problem with `document-idle`, but having switched back to GM (since Scriptish has fallen into disrepair), I now find that these GM UserScripts no longer work.

The only workaround I have been able to come up with is to wrap my entire UserScript in `$(document).ready(function(){ ... })` (using the native jQuery `$` from the page, if it has it, otherwise, `@require`ing jQuery).  This works, but feels quite clunky, and nowhere near as easy as just specifying `@run-at document-idle`.

I saw from [this comment](https://github.com/greasemonkey/greasemonkey/issues/1103#issuecomment-185452) in #1103 that the general policy is not to do anything that users could do themselves.  I understand this point of view, but it still feels to me like there is a point to making common cases easy for script writers to do - that's the whole success of jQuery, for example.  I have no idea how Scriptish actually implements `document-idle`, but it wouldn't surprise me if it was just syntactic sugar for my jQuery hack above.

In any case, Scriptish can do this, so if GM can as well, then that will help people in porting their scripts when returning to GM.  Furthermore, according to [this page](http://www.chromium.org/developers/design-documents/user-scripts), Chrome also uses `document-idle` by default.

**Comment by ArkadiuszMichalski** [comment]
I'm vote to implement this because Scriptish has it and Tampermonkey (for Chrome) by default has something simmilar to works as Stylish (run script after DOMContentLoaded event was dispatched << but we have some delay after dispatched this event) and it will be helpful to faster porting script beetwen different browsers and addons.

**Comment by arantius** [comment]
Compatibility with other user script engines is the first category of things that breaks that general rule.

**Comment by ArkadiuszMichalski** [comment]
Looks like today Tampermonkey 3.11.4615 implemented document-idle as aption (http://tampermonkey.net/changelog.php?ext=gcal) so now in Chrome we have:
- document-idle (more delay than default document-end)
- document-end (some delay because Chrome in this aspect is asynchronous)

**Comment by the8472** [comment]
> I have several scripts that need to run not only after the DOM has been loaded, but also after early page scripts have been run (to fix up some of the mess they make).

have you considered waiting for whatever DOM changes you wish to fix up via [mutation observers](https://developer.mozilla.org/en/docs/Web/API/MutationObserver)?

**Comment by arantius** [comment]
https://github.com/greasemonkey/greasemonkey/commit/759b12fa47aff6e867f6989941882effa99b7a72#commitcomment-13957568

**Comment by arantius** [comment]
Above mentioned issues should be resolved.

**Comment by seriych** [comment]
If I'm not mistaken, it must be '_', not '-': 'document_idle'. And the same with _end and _start
