### ISSUE TITLE
Install button doesn't respond

### ISSUE THREAD

**Issue by jerone** [greasemonkey/greasemonkey#2120]
Just updated from 3.0 to 3.1 and now I can't install any userscripts anymore. The install dialog appears, but the install button doesn't respond after the timer finishes.

The following error appears in the browser console:
```
NS_ERROR_FILE_ACCESS_DENIED: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.moveTo] remoteScript.js:371:0
```

**Steps to reproduce:**

1. Open https://github.com/jerone/UserScripts/tree/master/Github_Comment_Enhancer
2. Click the install button.
3. Wait for timer on install button on the install dialog.
4. Nothing happens (see browser console for error).

**Info:**
Firefox 36.0.1 `Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0`
Greasemonkey 3.1

**Comment by arantius** [comment]
Hm, install works for me, what's different?  I'm on Linux not Windows.  FF `Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0`.

**Comment by jerone** [comment]
Oke, found the reason. Probably because of https://github.com/greasemonkey/greasemonkey/issues/2118 my userscript and its corresponding folder got removed from my profile, while the userscript was still listed in the Monkey-menu. Something errorred while trying to reinstalling the script, while it wasn't available anymore.

**Comment by jerone** [comment]
Apparently this issue only happens when the profile scripts folder and the `config.xml` are out of sync.
