### ISSUE TITLE
Errors in the storageBack.js

### ISSUE THREAD

**Issue by jerone** [greasemonkey/greasemonkey#2121]
Following error appears in the browser console multiple times:
```
NS_ERROR_UNEXPECTED: Unexpected error storageBack.js:75:0
```

**Info:**
Firefox 36.0.1 `Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0`
Greasemonkey 3.1

**Comment by arantius** [comment]
Appears when?

**Comment by jerone** [comment]
As soon as I open a page on GitHub for example. Can't find a good test case.

**Comment by jerone** [comment]
@arantius Any simple way I can read my storage settings from a particulair file? The error seems to be coming from the `GM_ScriptStorageBack.prototype.setValue` every time I load a page.

**Comment by arantius** [comment]
It's not documented/supported but: there should be a `.db` file in `gm_scripts` for each script with settings.  It's just a sqlite3 file.

Exactly what is the contents of `val` when that line is running and errors?

**Comment by jerone** [comment]
I identifed the script which was error; "Standalone Image Background and Transparency", but I don't know which value it was trying to set...

![gm](https://cloud.githubusercontent.com/assets/55841/6754736/caeeb8a0-cf1e-11e4-866e-2c8e9c600ff4.jpg)

**Comment by jerone** [comment]
Also confirming on my home setup:
Firefox 37.0 beta 6 `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0`
Greasemonkey 3.1 beta 2
