### ISSUE TITLE
Error when viewing page source

### ISSUE THREAD

**Issue by jerone** [greasemonkey/greasemonkey#2122]
The following error appears when viewing the page source:
```
TypeError: contentWin is undefined framescript.js:110:0
```
The error is in `ContentObserver.prototype.blankLoad` on line `if (contentWin.location.href.match(/^about:blank/)) {`

**Steps to reproduce:**

1. Open any webpage (this page is sufficient).
2. Right-click and choose option View Page Source.
3. Above error appears in Browser console when the page source window opens.

**Info:**
Firefox 37.0 beta 6 `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0`
Greasemonkey 3.1 beta 2

**Comment by arantius** [comment]
Are you still seeing this?  I'm not.

**Comment by jerone** [comment]
Yes, I am.

Firefox 38.0 beta 6 `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
Greasemonkey 3.1beta2

**Comment by janekptacijarabaci** [comment]
Also, I cannot confirm this (I created a new browser user profile).

Firefox 38.0 beta 6 `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
Greasemonkey 3.1beta2

**Comment by arantius** [comment]
@jerone is there a conflicting extension?  Does this happen in a clean profile?

**Comment by jerone** [comment]
Closing as I can't reproduce it anymore.
