### ISSUE TITLE
GM3.1: GM_openInTab switches focus to new tab, ignores FireFox option

### ISSUE THREAD

**Issue by coverprice** [greasemonkey/greasemonkey#2123]
**Reproduction conditions**
* Using GM 3.0 + 3.1 (Firefox 36.0.3)
* `Tools -> Options -> Tabs -> "When I open a link in a new tab, switch to it immediately"` is *unchecked*
* Call GM_openInTab() on any URL.

**Expected**
Focus will remain on the current tab. (This is the behavior of GM < 3.0)

**Actual**
Focus switches to the new tab.

**Comment by arantius** [comment]
https://github.com/greasemonkey/greasemonkey/issues/2105#issuecomment-80266113
