### ISSUE TITLE
[Request] Gm_closeTab

### ISSUE THREAD

**Issue by erosman** [greasemonkey/greasemonkey#2125]
There are times that closing a tab is required. I am not keen on enabling `dom.allow_scripts_to_close_windows`

Currently, I overcome the issue with a lot of additional code but a built-in function would be greatly beneficial.

````JavaScript
function GM_closeTab() {
  // get the current tab first then ...
  gBrowser.removeCurrentTab();
}
````

**Comment by janekptacijarabaci** [comment]
Duplicate of issue #1685.

**Comment by erosman** [comment]
#1685. Wow .... 7 Jan 2013
I guess the feature is not coming...
