### ISSUE TITLE
script not run without refresh on facebook

### ISSUE THREAD

**Issue by akostadinov** [greasemonkey/greasemonkey#2135]
I'm having a simple script [1] to open mobile facebook for videos to avoid using adobe flash.  From timeline if I right click the "video" link (please see screenshots on script page) then the script is not run. If I refresh the page or open the "video" link in a new tab, then script is run.
This looks to me as a greasemonkey issue as it is similar to #1445

Any way this could be fixed or how can I workaround?

[1] https://greasyfork.org/en/scripts/8176-switch-to-mobile-version-on-facebook-video-page

-- Firefox 36.0, Greasemonkey 3.1

**Comment by janekptacijarabaci** [comment]
AFAIK, because it uses ajax:
https://www.facebook.com/video.php?v=
<=>
https://www.facebook.com/ajax/pagelet/generic.php/PhotoViewerInitPagelet?ajaxpipe=

**Comment by akostadinov** [comment]
Well, if my browser url bar changes, I'd expect greasemonkey scripts to be triggered. And the browser url bar does change. Otherwise how can one detect that the location has changed?

**Comment by arantius** [comment]
In that case WAI see #1970.
