### ISSUE TITLE
Script stop working when require this js library

### ISSUE THREAD

**Issue by idmresettrial** [greasemonkey/greasemonkey#2138]
My script stop working when I use @require with this js library.
It works in Tampermonkey.

This is the minimal code.

>// ==UserScript==
>// @name         test
>// @version      1
>// @namespace    test
>
>// @require      https://cdnjs.cloudflare.com/ajax/libs/masonry/3.2.3/masonry.pkgd.min.js
>
>// @run-at       document-end
>// @grant        none
>// @match        *
>
>// ==/UserScript==
>
>alert('999');

**Comment by arantius** [comment]
Yeah, because that script does things that don't work in a script sandbox.  It uses `this` and `window` interchangeably, which does not work in this environment.

**Comment by idmresettrial** [comment]
I don't know why but I've found a solution: insert a script tag into the head tag.
