### ISSUE TITLE
[Bug] GM_registerMenuCommand + @run-at document-start

### ISSUE THREAD

**Issue by reek** [greasemonkey/greasemonkey#2139]
Hi,

I found that the commadFunc added to GM_registerMenuCommand does not work when the script uses @run-at document-start.

Here is a script to test
https://gist.github.com/reek/0e302e8d2dd4a614b085

I use Firefox 37.0.1 + Greasemonkey 3.1

Thanks
Reek

**Comment by janekptacijarabaci** [comment]
See also #2041

**Comment by janekptacijarabaci** [comment]
See #2052

**Comment by reek** [comment]
Hi,

yes, it's the same problem. but I need my script run at document-start, if I change this setting part of my script will no longer work.

**Comment by janekptacijarabaci** [comment]
@run-at: __document-start__

https://github.com/greasemonkey/greasemonkey/blob/master/content/framescript.js#L225
gScriptRunners[windowId].menuCommands.length = 0
gScriptRunners[windowId].menuCommands[index] = undefined
