### ISSUE TITLE
GM_xmlhttpRequest throws exception when URL is "about:" pages

### ISSUE THREAD

**Issue by piyushsoni** [greasemonkey/greasemonkey#2140]
I'm probably not supposed to even attempt these, but I thought may be it would work solving me a lot of trouble. I was trying to open "about:privatebrowsing" page with it, and it crashed the script

TypeError: this.stringBundle is undefined
Stack trace:
GM_xmlhttpRequester.prototype.contentStartRequest@resource://greasemonkey/xmlhttprequester.js:44:1

**Comment by janekptacijarabaci** [comment]
See #2052

**Comment by piyushsoni** [comment]
@janekptacijarabaci : 
I think there's some confusion. This crash happens irrespective of where the call is being made : private or non-private session. Just calling any "about:.... " URL with GET parameter throws an exception. 

That being said, I was doing that because I wanted a way to check whether I'm running in private browsing mode, as I don't want to execute my script from a private window. Thanks!

**Comment by janekptacijarabaci** [comment]
https://github.com/greasemonkey/greasemonkey/pull/2052/files#diff-27c9e350246e9d22e2b42a722455408aR10

**Comment by arantius** [comment]
Separately filing a feature request specifically for an API that lets you know if you're in private browsing or not makes sense.

GM_xhr reaching about: pages I'm just going to veto. There's too much sensitive stuff (about:memory, about:support, etc) there, and too little of real value.
