### ISSUE TITLE
Please add a user script hosting sitelink

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [greasemonkey/greasemonkey#2144]
Hi,
I found a Chinese user script hosting site, there is hosted so many user scripts for GM, please add this site for your [User Script Hosting](http://wiki.greasespot.net/User_Script_Hosting) page:
http://j.mozest.com/zh-CN/userscript/

**Comment by jerone** [comment]
There's no English version?

**Comment by KrasnayaPloshchad** [comment]
Sure, this site is maintained by Mozest team, Beijing Mozilla Online Ltd also provide some supports.

**Comment by arantius** [comment]
That is a wiki.  Sign up for an account (and let me know the username you selected .. manual approval is the only spam avoidance technique I've found that works) and you can add the link yourself.

**Comment by arantius** [comment]
I'm still happy to approve your wiki account if you contact me directly, then you can edit the wiki yourself.
