### ISSUE TITLE
GM_registerMenuCommand memory leak another test case

### ISSUE THREAD

**Issue by simonzack** [greasemonkey/greasemonkey#2146]
As in #2067, my own user script leaks memory significantly with `GM_registerMenuCommand` as well, until firefox crashes at ~1.5gb of memory used. Commenting it out and memory use becomes rather stable.

To reproduce:
- install https://gist.github.com/simonzack/d5ac206f0fe661cc0c27 with greasemonkey on firefox 38
- do some google searches in a new tab and check the script is active (it should be)
- close the google search tab
- you will see the permanent ghost compartments in about:memory

If you comment out the single call to `GM_registerMenuCommand` at line 216 and remove `// @grant       GM_registerMenuCommand`, no ghost compartments are created and memory usage remains stable.

I've opened up a new issue as I think this test case requires fewer steps to do.

**Comment by arantius** [comment]
Thanks for the additional test case.  However 1) if it's the same issue, it should be tracked in #2067 and 2) a three thousand line script is still not a convenient reduced test case.
