### ISSUE TITLE
GitHub edit no longer works (again)

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2147]
Unable to "edit this file" on GitHub. I know this issue was fixed, but its broken again on GM 3.1.

**Comment by janekptacijarabaci** [comment]
Can you show me an example of the URL you're trying?

**Comment by arantius** [comment]
Following the link in #1998 and clicking the edit pencil WFM, brings up an editor.  Can you be more specific about "unable to"?  What exactly happens?  What do you expect?  How do those differ?

**Comment by TimidScript** [comment]
Sorry my bad. It was a script that was causing the problem.
