### ISSUE TITLE
GM_registerMenuCommand and wildcard (*)

### ISSUE THREAD

**Issue by bewam** [greasemonkey/greasemonkey#2148]
Hello,

I use a "GLOBAL" script that run on every page I visit. I've recently use the GM_registerMenuCommand function in this script. The command wasn't recognized by the browser saying it's undefined.
For the workaround, I had to add a web site, in plus, to have it to work.
...
//@include https://duckduckgo.com/*
//@include *
... 

Now, my script runs as it has to.
Thanks for your great addon.

**Comment by janekptacijarabaci** [comment]
I think we need a more detailed example.

**Comment by bewam** [comment]
what's working:
-------------------------------------------
...
// @grant       GM_registerMenuCommand
// @include     https://duckduckgo.com/*
// @include     *
// ==/UserScript==
GM_registerMenuCommand("blah ....
-------------------------------------------
what isn't working:
-------------------------------------------
// @grant       GM_registerMenuCommand
// @include     *
// ==/UserScript==
GM_registerMenuCommand("blah ....

**Comment by jerone** [comment]
Did you add the [`@grant GM_registerMenuCommand`](http://wiki.greasespot.net/@grant) in the header?

**Comment by bewam** [comment]
**It works.**
It's embarrassing; can someone close this issue?
I can't reproduce no more. I spend hours to look up for a solution where there's nothing problematic.
@jerone: yes, I did.
