### ISSUE TITLE
document-start doesn't work as expected since version 3.1

### ISSUE THREAD

**Issue by vOidSenses** [greasemonkey/greasemonkey#2150]
To simply put, I'm not being able to retrieve any element on document start using xpath.

```javascript
if ('loading' == document.readyState) {
var temp = window.document.evaluate("//div", window.document, null,
XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE, null);
}
```
something like this always returns null in the "temp" var when it should return a bunch of div objects

**Comment by arantius** [comment]
A) Since 3.1, or 3.0?
B) Really really this changed from 2.x to 3.x?

**Comment by vOidSenses** [comment]
A) on my laptop i prevented the 3.1 update (it has 3.0) and some scripts that depended on that xpath usage are working there but those same scripts stopped working on my desktop after the update, so thats why i'm assuming it's a 3.1 problem only, but i could be wrong

B) I actually tested that previous code by outputting the variable content to the console and it works just fine on document-end, it's only a problem at document-start. I can't really say how it was working before 3.0 version simply because i was using a different solution, I was using unsafe-window with an event listener like the old versions of greasemonkey, which while might not have anything to do with this particular problem made me change the code a lot trying to figure out the problem. Don't know if it's useful information or not

**Comment by arantius** [comment]
The easier you make it, the more likely the bug would be fixed.

If you can provide a complete exact super-short script, and a specific URL where to run it, AND also test it in 2.3, 3.0, and 3.1, and explain all the results, that makes things easier to work on.

**Comment by vOidSenses** [comment]
´´´javascript
// ==UserScript==
// @name        BugTest
// @namespace   BugTest
// @description Testing document-start properly
// @include     https://github.com/greasemonkey/greasemonkey/issues/2150*
// @version     1
// @grant       none
// @run-at 			document-start
// ==/UserScript==

/* please comment this if when using document-end */
if ('loading' == document.readyState) {
  console.log("Debug text before variable");
  var temp = window.document.evaluate("//div", window.document, null, XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE, null);
  console.log("Error here -> "+temp.snapshotLength+" divs");
  // output should be around 150 divs, but it's 0
}
´´´

I took the if part from the greasemonkey wiki, and unless i understood wrong document.readyState only displays either "loading" or "interactive" depending on document-start or end. I don't have the now to test this on older versions, tomorrow i'll dig this.

To make things clear, I simply want to change a page before it renders so I don't see elements shifting.

**Comment by janekptacijarabaci** [comment]
To me, it seems logical:

``` javascript
// ==UserScript==
// @name        BugTest
// @namespace   BugTest
// @description Testing document-start properly
// @include     https://github.com/greasemonkey/greasemonkey/issues/2150*
// @version     1
// @grant       none
// @run-at      document-start
// ==/UserScript==

if ("loading" == document.readyState) {
  console.log("Debug text before variable - " + document.readyState);
  var temp = window.document.evaluate("//div", window.document, null,
             XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE, null);
  var temp2 = window.document.getElementsByTagName("div");
  console.log("document.readyState: " + document.readyState
            + " ; (XPathResult / getElementsByTagName) -> "
            + temp.snapshotLength + " / " + temp2.length + " divs");
}

document.onreadystatechange = function () {
  if (("interactive" == document.readyState) || ("complete" == document.readyState)) {
    console.log("Debug text before variable - " + document.readyState);
    var temp = window.document.evaluate("//div", window.document, null,
               XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE, null);
    var temp2 = window.document.getElementsByTagName("div");
    console.log("document.readyState: " + document.readyState
              + " ; (XPathResult / getElementsByTagName) -> "
              + temp.snapshotLength + " / " + temp2.length + " divs");
  }
}
```

__loading = is loading__

**Comment by vOidSenses** [comment]
I'm really confused now because i can't explain why my scripts stopped working after the update

I actually started using the loading readystate AFTER the update because thats the example in the wiki about document-start and mozilla documentation even states the "complete" state which is not mentioned in the wiki so I even considered to not be available in greasemonkey, your script definitely is enlightening because i wasn't aware on the onreadystatechange variable in each the "complete" state shows up

I jumped to the conclusion that something was wrong with document-start. What i was using before was simply an event listener, I'll need to dig some of my code and look for differences, I'll report back asap

**Comment by vOidSenses** [comment]
Okay this is getting weird... I partially found the problem but at the same time I didn't

The whole readyState thing is actually completely irrelevant, that was me not understanding the problem and the solution. To make it perfectly clear, I have a really old script that I use to change (mainly remove) some stuff from specific websites I use often, I keep coming back to it do add more stuff for it to remove. In my last script update greasemonkey throw me a warning because I wasn't using any "grant" metablock, so I added the only grant that made sense to me which is the "unsafeWindow" because right at the top I'm using something like this

```javascript
const d = ((typeof unsafeWindow === "object") ? unsafeWindow : window).document;
d.addEventListener('DOMNodeInserted', deletes, false);
```
This is the listener I was referring earlier to be able to change something before being rendered to remove the flicker effect from changing stuff in a page.

Coincidentally just a few hours later and update to greasemonkey was released and only after the update did I noticed my script wasn't working, but the truth is that the script isn't working in 3.0 either and the reason is the grant metablock that I added, if I remove it completely the scripts works, any grant that I add breaks it. I don't know if this is a bug or not but it breaks even on document-end. This is what lead me to use the readyState as an alternative (which is not) trying to figure out the problem.

Now, this is not actually resolved yet. The pages where I'm using this script are not removing the elements before the rendering begins, they actually do the flicker effect where the element renders and only after a little while it goes away. Which is weird because I have this script working for years now and it's the first time this happens. So I went to check my laptop which has version 3.0 and the flicker does NOT show up. I ended reverting on my desktop to version 3.0 too and did some experiments trying to match the same addons and what not, and no matter what I do the flicker is still there and pretty obvious while on my laptop is completely gone as it always was.

I really don't know what do here.

**Comment by arantius** [comment]
> any grant that I add breaks it.

Specify `@grant none`.

> they actually do the flicker effect where the element renders and only after a little while it goes away

This is expected.  http://wiki.greasespot.net/DOMContentLoaded#Flicker

Otherwise: please take this to http://groups.google.com/group/greasemonkey-users for support.

**Comment by vOidSenses** [comment]
Thx, completely missed the "none" ... that one works.

I know the flicker effect is an expect behavior but why was it working for years and it still works on my laptop but it doesn't work on my desktop?
