### ISSUE TITLE
Address "unsafe CPOW usage" warnings

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2151]
I'm seeing them now for:

Line 266 and 270 of `browser.js`, in:

    function GM_showPopup(aEvent) {
      function urlsOfAllFrames(contentWindow) {
        var urls = [contentWindow.location.href];
        function collect(contentWindow) {
          urls = urls.concat(urlsOfAllFrames(contentWindow));
        }
        Array.prototype.slice.call(contentWindow.frames).forEach(collect);
        return urls;
      }
        
The `var urls = ...` and the `Array.prototype.slice...` lines.  Line 17, 23, and 28 of `windowId.js`.

Maybe others I haven't noticed yet.

**Comment by janekptacijarabaci** [comment]
Current:
![cpow](https://cloud.githubusercontent.com/assets/2373486/7550145/e58a340a-f656-11e4-96aa-e04a17791dad.png)

**Comment by janekptacijarabaci** [comment]
I've pushed a fix to the testing branch: https://github.com/greasemonkey/greasemonkey/compare/master...janekptacijarabaci:_testBranch_unsafe_CPOW_usage

The suggestion (for example).
__It is necessary to test all options!__

__Warning: Thus it will not work in Firefox 24- (e.g. PaleMoon)! This works in Firefox 25+__

**Comment by arantius** [comment]
Merged by hand.

**Comment by arantius** [comment]
This should be in 3.5beta1; let me know what you think:
https://addons.mozilla.org/firefox/downloads/file/354560/greasemonkey-3.5beta1-fx.xpi?src=devhub
