### ISSUE TITLE
Greasemonkey 3.0: abort() method throwing error with GM_xmlhttpRequest

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2154]
Source: https://groups.google.com/forum/#!topic/greasemonkey-users/xEFODGFI85M
See also https://github.com/greasemonkey/greasemonkey/issues/2033#issuecomment-70368813 ( \__exposedProps\__ )

> Under Greasemonkey 3.0/3.1, the following error is thrown when using abort() with GM_xmlhttpRequest:
``` javascript
Exposing privileged or cross-origin callable is prohibited
```
> Under Greasemonkey 2.3, it completes normally, and the 'abort OK' message is displayed. Under Greasemonkey 3.0/3.1, it won't.

> Here is a sample script that shows the problem:

> ``` javascript
>// ==UserScript==
>// @name        Abort Test
>// @namespace   http://gmscripts.locusprime.net
>// @include     http*://*
>// @grant       GM_log
>// @grant       GM_xmlhttpRequest
>// ==/UserScript==
>
> var req = GM_xmlhttpRequest({
>   method: "GET",
>   url: "https://www.github.com/",
>   onload: function (result) {
>     GM_log(result.responseText);
>   }
>});
>
> req.abort();
> GM_log("abort OK");
> ```

**Comment by arantius** [comment]
Fix above confirmed.
