### ISSUE TITLE
GM_getValue with unset name returns null

### ISSUE THREAD

**Issue by penguishPenguin** [greasemonkey/greasemonkey#2156]
GM_getValue with unset name returns null instead of undefined.

Greasemonkey 3.2beta1
Firefox 38.0 Beta 9 (64-bit)

**Comment by janekptacijarabaci** [comment]
https://github.com/greasemonkey/greasemonkey/commit/97df401b342b471393b9f36a4daa91f8d3557d5f#diff-b628e9db31be9450438b22a3379c9c89R63

**Comment by arantius** [comment]
9ba4cb28bd78f261957c3f4348bbf06b12b9ec70
