### ISSUE TITLE
toolbar menu items not working correctly

### ISSUE THREAD

**Issue by atomGit** [greasemonkey/greasemonkey#2159]
clicking a menu item in the toolbar icon menu runs the wrong script

this seems to have started since the GM 3.* beta releases

ff 37 and possibly earlier
GM 3.* beta + (currently 3.1)
windows

1 create an empty profile
2 install: https://addons.mozilla.org/en-Us/firefox/addon/greasemonkey/ and restart
3 install: https://greasyfork.org/en/scripts/4407-ts-linx-amender
4 install: https://greasyfork.org/en/scripts/4255-linkify-plus-plus (or any other script that will add a menu item to User Script Commands menu)
5 restart FF - for some reason User Script Commands > Configure Linlify Plus Plus menu item was not present until i restarted
6 from GM toolbar icon, click Script Commands > update TS Linx Amender ... the config UI for Linkify Plus Plus opens instead

**Comment by arantius** [comment]
Which version of GM exactly?  Have you tried 3.2beta1 (released just a few days ago)?  It has the fix for #2139 and that might be the same issue causing this bug.

**Comment by atomGit** [comment]
3.2beta 1 solves the problem :)
