### ISSUE TITLE
Feature Request: Add some metadata to specify what URL patterns are accessible via GM_xmlhttpRequest

### ISSUE THREAD

**Issue by tiansh** [greasemonkey/greasemonkey#2160]
I wonder if there can be a feature that user can know what URL will the script visit via `GM_xmlhttpRequest`. And user can whitelist or blacklist some URL in script settings. This makes `GM_xmlhttpRequest` more secure.

The format of metadata may be similar to `@include` and `@exclude`. For example `@xhr-include`, `@xhr-exclude`. (Name may be discussed later) If not given, imply `@xhr-include *`, so that it may not break any scripts.

It works as same as `@include`, which will be shown to user when installing some script.

When performing an `GM_xmlhttpRequest`, check the list first, and URLs not in the whitelist or blacklisted will be disallowed. GM may throw an exception / response 403 / response 400 / response 200 with empty body / stop execution / fail silently with console.warn ... (still need discussed later)

**Comment by janekptacijarabaci** [comment]
See https://github.com/greasemonkey/greasemonkey/issues/1052
See also https://github.com/greasemonkey/greasemonkey/issues/1056

**Comment by tiansh** [comment]
Sorry i didn't find out that post before...
