### ISSUE TITLE
Can't open the script's settings

### ISSUE THREAD

**Issue by klenium** [greasemonkey/greasemonkey#2166]
![a](https://cloud.githubusercontent.com/assets/4959489/7549749/868c131e-f643-11e4-85fd-1004d240497c.png)
When I click on any script's (on the image, newtab's) Settings button, I get this popup.
Wanted to report it, but when I tried to [change the browser's language](https://support.mozilla.org/hu/questions/1018686), and I changed `general.useragent.locale` from `hu` to `en`, it worked fine, no error message, I could change the settings.
Firefox 37.0.2
Greasemonkey 3.2beta1

**Comment by janekptacijarabaci** [comment]
See https://github.com/greasemonkey/greasemonkey/commit/4d5039598c8f929da89477334ebcae5cc1444a80#diff-4180afff8de1e69055ace9baaca05e2bR8

See also http://beta.babelzilla.org/projects/p/greasemonkey/ - 100% (the strings are not there)

**Comment by janekptacijarabaci** [comment]
There is potentially the same problem:
https://github.com/greasemonkey/greasemonkey/pull/1788/files#diff-8fad38f74dac8df01765cc6e05c3e644R29

**Comment by arantius** [comment]
Version 3.2beta2 should fix this

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/?page=1#version-3.2beta2

Give it a few minutes to show up.
