### ISSUE TITLE
Enable update on modified userscripts via wrench-drop-down>check for updates and via automatic FF update checking

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2167]
(in continuance of [this comment](https://github.com/greasemonkey/greasemonkey/issues/1743#issuecomment-18154419) (issue #1743)

What about enabling update for modified scripts via

1. wrench-drop-down>check for updates 
2. FIrefox automatic checking for updates?

Currently, if you modify a script, then updating for it gets disabled
(there's no `Automatic updates:    Default/On/Off` radio buttons on any script anymore
when you doubleclick it in Addons Manager)
and you only can update it via "forced find update" .

I suggest, whenever there's a new version available for a modified script,
the script to become updated,
and the user to get a relevant notification about it
(that *"the script x that was previously locally modified, has been updated"*,
instead of the standard notification that *"script x has been updated"*).

Therefore I'd say that the `Automatic updates: Default/On/Off` should be available for modified scripts too, so that the user can decide whether he wants auto-updating or not.

**Comment by arantius** [comment]
This feature is very intentionally designed this way.  If you've modified the script, it's possible or likely that those changes exist only on your disk.  "Updating" the script would destroy these changes, which may be very valuable to you.  If you really want to throw them away, "Forced find updates" is the supported way to do that.
