### ISSUE TITLE
GM script does not always run in first tab after opening browser, have to close tab and open another

### ISSUE THREAD

**Issue by lope** [greasemonkey/greasemonkey#2171]
GM does not run my script in the first browser tab that opens automatically at my home URL.
I have to open another tab (which also opens at my home URL, and GM runs the script reliably) and close the first tab.

If I try navigate to a different page using the first tab (that GM does not work in), the problem persists, GM does not run on subsequent pages. It is like GM ignores the first tab?

To reproduce this issue try this:
1. Setup about:config
'browser.newtab.url',HOMEPAGE_PATH
'browser.startup.homepage',HOMEPAGE_PATH

where HOMEPAGE_PATH is a URL, like http://127.0.0.1/test.html or http://192.168.155.1/test.html etc

2. Setup the GM script below to be enabled and run before any other script
3. Close FF and reopen it
4. Take note of whether GM runs in the first tab, if it doesn't work, try browsing to other URLs in first tab.
5. Try open a new tab, and check if GM runs in it.

Example script:

// == UserScript==
// @name	Foo
// @namespace	1234567abcdef
// @include	*
// @grant	none
// @run-at	document-start
// ==/UserScript==
alert('hello');

**Comment by janekptacijarabaci** [comment]
"document-element-inserted" doesn't see __browser.newtab.url__, __browser.startup.homepage__

See (supports only "__about:blank__"):
https://github.com/greasemonkey/greasemonkey/commit/0dbdc9aa008ca894a5e98448273b4a37013c1787

See also (supports only @run-at "__document-end__"):
https://github.com/greasemonkey/greasemonkey/issues/2041#issuecomment-85392887

**Comment by janekptacijarabaci** [comment]
Example script:
```// == UserScript==``` => ```// ==UserScript==```

Not confirmed on:
Firefox 38.0.1, GM 3.2beta2

**Comment by lope** [comment]
@janekptacijarabaci thank you!
Wow it looks like you've solved my problem.
Strangely that error I had in my userscript stopped it from working in the first browser tab, but it worked on subsequent browser tabs!
