### ISSUE TITLE
GM prevents Firefox add ons update

### ISSUE THREAD

**Issue by sgfc1** [greasemonkey/greasemonkey#2174]
When I open Add-ons and click Extensions and check for updates manually. It gets stuck at "Updating add-ons" but as soon as I remove Greasemonkey 3.1 it'll pass from Updating add-ons to "No updates found".

Windows Pro 8.1 64-bit
Firefox 38.0.1
Greasemonkey 3.1 no scripts

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
Windows 7/8.1 32/64-bit
Firefox 38.0.1, Firefox Nightly 41.0a1 (2015-05-21)
GM 3.1, GM 3.2beta2

Try to take a look at browser's console for errors (warnings).

**Comment by arantius** [comment]
I've not strictly confirmed this issue specifically, but I think I've seen it, personally, recently.  (Recent Firefox on Linux.)

**Comment by SINE** [comment]
Yes, Greasemonkey also doesn't update scripts any more, I can confirm this.

Firefox 38.0.1
Windows 7 64-bit

**Comment by arantius** [comment]
I definitely get updates.  Have this past week.

**Comment by SINE** [comment]
You are using Linux, it might be OS related

**Comment by sgfc1** [comment]
I found the problem thanks to janekptacijarabaci. One of the scripts is trying to update from a dead site.

**Comment by janekptacijarabaci** [comment]
See also: https://github.com/greasemonkey/greasemonkey/issues/2029

**Comment by sgfc1** [comment]
I tried to remove the updateURL manually from the config.xml and it didn't help. But I'll see what other URL's may be useless. For now I just removed greasemonkey and the gm_scripts.

**Comment by sgfc1** [comment]
Yeah that fixed it janekptacijarabaci, thanks.
