### ISSUE TITLE
Greasemonkey Script not updating

### ISSUE THREAD

**Issue by SINE** [greasemonkey/greasemonkey#2175]
I'm trying to get my userscript updating, tried all variations that came to my mind (with meta.js, without meta.js, with download URL and also without etc.).

My userscript: https://github.com/SINE/163music_custom/raw/master/163translated.user.js

Now if you edit the script and changet the version from 4 to something lower, then it won't update, even if I click on Update in about:addons > Userscripts.

System:
Windows 7 x64
Firefox 38.0.1

Possibly related to:
#2174

**Comment by arantius** [comment]
> Now if you edit the script and ...

This is by design, so that your edits are not destroyed by the update mechanism.  If you click *force* updates, then it will destroy your local edits if the server says there's an update.

**Comment by SINE** [comment]
Works, I didn't see that function.
Thank you very much arantius
