### ISSUE TITLE
[e10s on] Drag & Drop file (*.user.js) - the tab has crashed

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2176]
Firefox Nightly 41.0a1 (2015-05-22) - __e10s on__
GM 3.2beta2

Drag & Drop file (*.user.js) - the tab has crashed:

![0](https://cloud.githubusercontent.com/assets/2373486/7774676/587c479a-00ad-11e5-9630-38e9008cf7f7.png)
![1](https://cloud.githubusercontent.com/assets/2373486/7774681/5f813406-00ad-11e5-9a6a-a404be871e31.png)
![2](https://cloud.githubusercontent.com/assets/2373486/7774685/651ced24-00ad-11e5-8a84-b5d3b5dea2d5.png)

**Comment by arantius** [comment]
Confirmed, and fix confirmed and merged.
