### ISSUE TITLE
[e10s on] Url: github.com/...user.js (I reopen a closed issue #1998)

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2178]
See: https://github.com/greasemonkey/greasemonkey/issues/1998

Firefox Aurora 40.0a2 (2015-05-22) - __e10s on__
Firefox Nightly 41.0a1 (2015-05-22) - __e10s on__
GM 3.2beta2

![3](https://cloud.githubusercontent.com/assets/2373486/7775042/dec05f2e-00af-11e5-98e1-9fa0651c01f9.png)

**Comment by arantius** [comment]
What's the broken behavior?

**Comment by janekptacijarabaci** [comment]
The page will not load at all...

**Comment by janekptacijarabaci** [comment]
Confirmed on:
Firefox Aurora 40.0a2 (2015-05-29)
Not confirmed on:
Firefox Nightly 41.0a1 (2015-05-29)

I'd rather have waited...

**Comment by stormdr1ve** [comment]
I have the same issue - FF Dev edition 40.0a2 (2015-05-29) and at least a couple of builds before this.
E10S is **enabled**
I'm using Greasemonkey 3.2beta4
This is being logged to the browser console:
![Browser console error message](http://img.jackw.net/161433079757.png)
It's blaming line 32 of `/modules/util/showInstallDialog.js`, so it looks like this is the faulty code (from line 10):
```javascript
function showInstallDialog(aUrlOrRemoteScript, aBrowser, aRefererUrl){
  var rs = null;
  if ('string' == typeof (aUrlOrRemoteScript){
    rs = new RemoteScript(aUrlOrRemoteScript);
  } else {
    rs = aUrlOrRemoteScript;
  }
  //rs is remaining null
  [...]
}
```
This problem only occurs when there is no referrer set - if it is set, the install dialog shows up correctly.

**Comment by janekptacijarabaci** [comment]
Confirmed on:
Firefox Aurora 40.0a2 (2015-06-06)
Not confirmed on:
Firefox Aurora 40.0a2 (2015-06-09)
Firefox Nightly 41.0a1 (2015-05-29)

Closing this for now...
