### ISSUE TITLE
[e10s off] Two install dialogs for local and remote *.user.js files

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2179]
Firefox 38.0.1
Firefox Nightly 41.0a1 (2015-05-22) - __e10s off__
GM 3.2beta2

See: https://groups.google.com/forum/#!searchin/greasemonkey-users/twice/greasemonkey-users/_XIYLjkWAb0/EU5HGI47oU0J

See also: #1681

**Comment by janekptacijarabaci** [comment]
See also https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_chrome_scripts#nsIContentPolicy

**Comment by CoolCmd** [comment]
FF 39, GM 3.2
- hit Ctrl+L
- type file:///blabla.user.js
- two dialogs are shown

**Comment by arantius** [comment]
I definitely just saw this on `Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0` `Built from https://hg.mozilla.org/mozilla-central/rev/ca53d4297f02`, when dragging-and-dropping a file from the desktop onto the main content pane.  E10S off.  Restart and it still happens.  Enable E10S (which forces restart) and it stops.

**Comment by arantius** [comment]
I'm inclined to delay this if just waiting for E10S to land will "fix" it.

**Comment by Owyn** [comment]
just noticed that same goes for any urls, example http:
https://github.com/YePpHa/YouTubeCenter/raw/master/dist/YouTubeCenter.user.js
open two install dialogues

**Comment by arantius** [comment]
Firefox stable (40.0.3) e10s isn't an option: works.
Firefox nightly (44.0a1) e10s off: works
Firefox nightly (44.0a1) e10s on: works

Works for me.  Either fixed upstream or perhaps by the8472's recent optimization effors.

**Comment by janekptacijarabaci** [comment]
I try it all the time, but for me it takes (Firefox Nightly 44.0a1 (2015-09-23))...

**Comment by CoolCmd** [comment]
ff 42 DE - 1 dialog

**Comment by dogancelik** [comment]
I have this same issue on Firefox 41 (Stable) and Firefox 43 (Aurora). Multi-process is not enabled.

2 to 4 dialogs pop up for same file if you drag and drop from a folder. (Windows 7 64-bit)
