### ISSUE TITLE
Sync resurrects deleted scripts

### ISSUE THREAD

**Issue by Gollam** [greasemonkey/greasemonkey#2186]
If Greasemonkey script syncing is enabled, it keeps returning the scripts which I deleted long time ago. I deleted them on all my firefox instances, but they keep returning. As a workaround, I had to disable script syncing.

**Comment by arantius** [comment]
A less invasive workaround would be to disable, rather than uninstall, the script.  I'd wager that if you disable it for a few days, then uninstall, *if* it does indeed come back, it should come back disabled.

**Comment by Gollam** [comment]
Yes, in fact they were already disabled almost a year ago, because I did not use them. That's why I tried to delete them, but they always come back, disabled.

**Comment by jerone** [comment]
I'm having the same issue. If I remove a script they return some time later. This happens on all my synced machines. It doesn't help if I enable/disable a script first before removing. The returned script where installed at least a year ago, if that matters.

**Comment by jerone** [comment]
@arantius Is there something about information I can provide, putting this issue on the roadmap? Just synced Firefox on a complete new clean install and a few removed scripts appeared in my list again!

**Comment by arantius** [comment]
The first most obvious thing to look for is any errors in the log around the time that you install/uninstall the affected scripts.

**Comment by arantius** [comment]
Pretty sure I see what's going on here.  The uninstall-by-sync is not *quite* completing correctly.  It leaves just enough data (the contents in config.xml, but not the script files) to cause enough of a Sync record to be created again.  At least in some circumstances.

**Comment by arantius** [comment]
Version 3.4beta3 might fix this:

https://addons.mozilla.org/firefox/downloads/file/344478/greasemonkey-3.4beta3-fx.xpi?src=devhub

Even if so, there's at least one small remaining issue: if the add-ons manager is open while Sync uninstalls a script, it's still visible until close/reopen.

**Comment by arantius** [comment]
I believe the changes referenced above fixes this.
