### ISSUE TITLE
[e10s on] GM_xmlhttpRequest - does not show login prompt

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2190]
Ad https://github.com/greasemonkey/greasemonkey/issues/2048#issuecomment-106991407... continued.

Confirmed on:
Firefox Aurora 40.0a2 (2015-05-29)
Firefox Nightly 41.0a1 (2015-05-29)
GM 3.2

Gist: https://gist.github.com/janekptacijarabaci/8b969e5f48a305d91fd7

**[e10s off]**:
Result:
`GM_xmlhttpRequest() 2: status: 200 statusText: OK` (show login prompt)
`GM_xmlhttpRequest() 3: status: 200 statusText: OK`

Reloading page (F5):
`GM_xmlhttpRequest() 2: status: 200 statusText: OK` (does not show login prompt)
`GM_xmlhttpRequest() 3: status: 200 statusText: OK`

**[e10s on]**:
(does not show login prompt)
Result:
`GM_xmlhttpRequest() 2: status: 401 statusText: Authorization Required`
`GM_xmlhttpRequest() 3: status: 401 statusText: Authorization Required`

XMLHttpRequest() - OK (show login prompt)

**Comment by janekptacijarabaci** [comment]
See also https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_frame_scripts#XUL_and_browser_UI

**Comment by arantius** [comment]
Confirmed, I hate e10s SO MUCH.  Also, simpler reproduction script for my future reference:

```javascript
// ==UserScript==
// @name        GM_xhr HTTP Auth Test
// @include     http://localhost/*
// @exclude     http://localhost/auth*
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  method: 'GET',
  url: "http://localhost/auth/",
  onload: function(xhr) {
    dump('script '+xhr.responseText.substr(0, 128).replace(/\n/g, ' ')+'\n');
  },
});
```

I have basically no idea how to address this or even why it might be happening.

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1217876
