### ISSUE TITLE
Script preferences window too large

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2191]
See: https://groups.google.com/forum/#!topic/greasemonkey-users/qu1ywWZo8lo

**Comment by NoneGiven** [comment]
Any word on when this will land? I've long had a batch file to hide/unhide the Windows taskbar that I can access in a few keystrokes, and this STILL proves to be a gigantic headache for me whenever I want to do something with my userscripts (especially back and forth between browsers). I can only imagine how frustrating it is for everyone else with screen resolutions like mine.
