### ISSUE TITLE
Allow user scripts for the new Firefox Reader facility `about:reader`

### ISSUE THREAD

**Issue by cipriancraciun** [greasemonkey/greasemonkey#2195]
With the latest edition of Firefox, they have integrated the Pocket "reader", which when activated will load a "reading" version of the original page at an URL like `about:reader?...`.

However user scripts are not allowed for `about` pages, including the `about:reader`.

I've made a small hack in `modules/util/isGreasemonkeyable.js`, by adding a line like the one below just after `if (/^about:blank/.test(url)) return true;`:

    if (/^about:reader(\?.*)?$/.test(url)) return true;

**Comment by arantius** [comment]
I'll bet dollars to donuts that like other `about:` pages, it has chrome privileges, so it will never be greaseable.

**Comment by cipriancraciun** [comment]
I didn't say (although I wanted to) in my initial comment that I have **zero** knowledge about what my update implied.  Perhaps it just opened a large security whole in my browser, but since I use only user scripts written by me, I am less concerned with potential security issues from my own scripts.

But, indeed a more knowledgeable person, in the inner workings of both Firefox and Grease Monkey, should look into this.

**Comment by arantius** [comment]
What exactly are the steps to launch such an `about:reader` page?  I couldn't figure it out in the ~2 minutes I spent trying.

**Comment by cipriancraciun** [comment]
For example open the following link, and in the address bar, at the right, just before the reload button there is a small button like a book.  Just press it.

  http://getpocket.com/blog/2015/06/pocket-is-now-built-into-firefox/

(I guess you need the latest Firefox 38.0, and this feature works only on some pages like the one above.)

**Comment by arantius** [comment]
Oh, no `about:` shows in the UI in that case.  But I'm clear what you're talking about and I can check what that context is.

**Comment by cipriancraciun** [comment]
Indeed the address bar still shows the original URL, but if you run inside the console `document.URL`, something like `about:reader?...` appears.

(I applied the patch described in the first comment and it works.)

**Comment by janekptacijarabaci** [comment]
The example is:
about:reader?url=https%3A%2F%2Fsupport.mozilla.org%2Fcs%2Fquestions%2F1063000

**Comment by arantius** [comment]
This should be in 3.5beta1; let me know what you think:
https://addons.mozilla.org/firefox/downloads/file/354560/greasemonkey-3.5beta1-fx.xpi?src=devhub

**Comment by cipriancraciun** [comment]
Perfect.  Works like a charm for reader URL's.

Thanks.
