### ISSUE TITLE
Cannot download userscript with match pattern "*.url.com/*", but works correctly when script is created locally

### ISSUE THREAD

**Issue by Yonezpt** [greasemonkey/greasemonkey#2201]
In my script I have recently added the following match pattern:

`// @match       *.youtube.com/* `

Which works as expected, but if I try to update the script online then Greasemonkey throws a download error:

![ss](https://cloud.githubusercontent.com/assets/8498057/8251562/1c46a31c-166d-11e5-9ca2-c8b56bd58bf4.png)

I've also tried the same steps with Tampermonkey and it doesn't have any issues accepting that pattern during online download.

**Comment by arantius** [comment]
It doesn't work, it just doesn't show you this error.  Read the documentation ( http://wiki.greasespot.net/Metadata_Block#.40match ).  Match must always start with a scheme.

**Comment by Yonezpt** [comment]
So it is, a simple alert test script showed that the pattern was not working and instead defaulting to run in all pages.

Would it be possible for version 3.3 to adopt [Firefox](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/page-mod) and [Chrome's](https://developer.chrome.com/extensions/match_patterns) pattern that assumes that if the pattern starts with `*.` then it will work for any protocol of the url that follows?
