### ISSUE TITLE
View source not working in Firefox beta 39.0b7

### ISSUE THREAD

**Issue by acrobat1** [greasemonkey/greasemonkey#2202]
In  Firefox beta 39.0b7 the view source context (right-click) option doesn't work, it now prompts directly for script installation instead of opening the code in a tab: for instance, on this page https://greasyfork.org/en/scripts/3840-translate-on-google right-click the **Install this script button**, then click **View User Script Source**.
The gm-temp folder is created containing the actual script, but it doesn't get displayed in the browser even when  dragging the script it in a tab.

**Comment by janekptacijarabaci** [comment]
__Confirmed on:__
Firefox 39.0 beta 7
Firefox Aurora 40.0a2 (2015-06-19) [e10s on/off]
Firefox Nightly 41.0a1 (2015-06-20) [e10s on/off]

__Not confirmed on:__
Firefox 38.0.5

And apparently it's the similar bug as https://github.com/greasemonkey/greasemonkey/issues/2178
![1](https://cloud.githubusercontent.com/assets/2373486/8268115/e25d8b22-1778-11e5-8d07-b9b799ec1867.png)

**Comment by yfdyh000** [comment]
Hi @arantius, the seems is not works for the "View User Script Source" menu.

**Comment by arantius** [comment]
Does 3.4beta2 fix this?

https://addons.mozilla.org/firefox/downloads/file/341782/greasemonkey-3.4beta2-fx.xpi?src=devhub

**Comment by yfdyh000** [comment]
Looks works fine for Fx40~43, but the seems breaking for 35.0.1 (our min are 35.0).

**Comment by arantius** [comment]
Launched Firefox 35.0.1, view source works from both context menu and install dialog.  Breaking how?
