### ISSUE TITLE
[Feature request] Allow @match wildcard scheme

### ISSUE THREAD

**Issue by Yonezpt** [greasemonkey/greasemonkey#2203]
I would like to ask if it will be possible to implement [Firefox](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/page-mod) and [Chrome's](https://developer.chrome.com/extensions/match_patterns) wildcard scheme which allows scripts to cover same pages across different protocols.

With this pattern the developer will only have to create one line for all schemes he wants to cover:

 `@match *.github.com/*`

Instead of having to cover all types:

````javascript
@match http://www.github.com/*
@match https://www.github.com/*
@match ftp://www.github.com/*
etc.
````

Resulting in an easier to read, cleaner and more compact code which will save more bandwidth.

EDIT: I am now wondering if `@include` already allows this...

**Comment by LouCypher** [comment]
Use `@match   *://example.com/*`. See
https://developer.chrome.com/extensions/match_patterns

On Monday, June 22, 2015, Particle <notifications@github.com> wrote:

> I would like to ask if it will be possible to implement Firefox
> <https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/page-mod>
> and Chrome's <https://developer.chrome.com/extensions/match_patterns>
> wildcard scheme which allows scripts to cover same pages across different
> protocols.
>
> With this pattern the developer will only have to create one line for all
> protocols he wants to cover:
>
> @match *.github.com/*
>
> Instead of having to cover all types:
>
> @match http://www.github.com/*
> @match https://www.github.com/*
> @match ftp://www.github.com/*
> etc.
>
> Resulting in an easier to read, cleaner and more compact code which will
> save more bandwidth.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greasemonkey/greasemonkey/issues/2203>.
>


-- 
Zulkarnain K.
https://mozillians.org/u/zoolcar9
https://github.com/LouCypher

**Comment by Yonezpt** [comment]
@LouCypher Seems like it works, I keep forgetting the `://`. Thanks for the quick help.
