### ISSUE TITLE
GM_xmlhttpRequest does not work on pages with url "Data:text/html,<html><body>..."

### ISSUE THREAD

**Issue by User4martin** [greasemonkey/greasemonkey#2206]
If a page was generated using an url like
data:text/html,<html><body>Foo</body></html>

GM_xmlhttpRequest will give an error that it is not defined

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2042

**Comment by arantius** [comment]
> GM_xmlhttpRequest will give an error that it is not defined

Oh! Are you saying' you're passing "data:...." to the `url` parameter of GM_xhr?

**Comment by User4martin** [comment]
No, I have 
  data:text/html,Foo
in the url bar of my Firefox

```javascript
  GM_xmlhttpRequest({
    method: "GET",
    url: new_dest,
    onload: function(response) {
      alert(response.responseText);
    }
  }) ;
```
"new_dest" contains a valid url (http/://somedomain.com/page), I checked with console.log before.

Further
```javascript
// ==UserScript==
// @name        adf_vid
// @namespace   mfr
// @version     2
// @include http://mydomain.com/*
// @include data:text/html*
// @grant GM_xmlhttpRequest
// ==/UserScript==

console.log(GM_xmlhttpRequest);
```

When I go to mydomain.com then it logs that this is a function.

When I create the data:text/html,Foo then it logs an error. I believe that error happens before my console.log guess to log, because the argument to console.log is invalid.

--------------
I have a page, that contains a link with the data: url. I want to run my user script when I click this link, and act on the content of the data.
So for I only triggered it from the editor, by using "reload and run" from the context menu.

**Comment by arantius** [comment]
This script:

```javascript
// ==UserScript==
// @name        data xhr test
// @namespace   https://github.com/arantius
// @include     data:*
// @version     1
// @grant       GM_xmlhttpRequest
// ==/UserScript==

try {
  GM_xmlhttpRequest({
    method: 'GET',
    url: 'http://ip.appspot.com/',
    onload: function(x) { console.log(x); },
  });
} catch (e) {
  console.error(e);
}
```

Works for me when I navigate to `data:text/html,Foo`.  I see all the response details logged by the onload handler.  ( `Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0`, Greasemonkey at 14f30ea37bd7d222201fde32527abd3b844a0d89 .)
