### ISSUE TITLE
Cross Origin GM_xmlhttpRequest + Shim Errors

### ISSUE THREAD

**Issue by Ichaelus** [greasemonkey/greasemonkey#2208]
I found out that the method GM_xmlhttpRequest is not working properly for cross origin request if you use @grant none in combination with your [Shim.js](http://wiki.greasespot.net/@grant#Compatibility_Layer). 
```javascript
// ==UserScript==
// @grant       none
// @require    https://gist.githubusercontent.com/arantius/3123124/raw/grant-none-shim.js
// ==/UserScript==
    GM_xmlhttpRequest({
      method: "GET",
      url:url,
      onload: function(response) {
             console.log(response.responseText);
      }
    });   
```

isn't working, while

```javascript
// ==UserScript==
// @grant       GM_xmlhttpRequest
// ==/UserScript==
    GM_xmlhttpRequest({
      method: "GET",
      url:url,
      onload: function(response) {
             console.log(response.responseText);
      }
    });   
```

is bringing the desired result.

The main problem is, that you can't mix both versions like

// @grant       GM_xmlhttpRequest
// @require    https://gist.githubusercontent.com/arantius/3123124/raw/grant-none-shim.js

Therefore the usability of GM is very low for some specific tasks at the moment.

Best wishes

**Comment by arantius** [comment]
I'm quite confused.  You mean the one that [says](https://gist.github.com/arantius/3123124#file-grant-none-shim-js-L57):

> // This naive implementation will simply fail to do cross-domain requests,
> // just like any javascript in any page would.

?  It's not *supposed* to be able to do cross-origin requests, it has no special privilege, it cannot do so.  (It's intended just to help transition by providing an API that's sometimes used anyway even for same-origin requests.)

**Comment by Ichaelus** [comment]
Thank you for your fast reply!
Some times a single letter changes worlds.. I read **The** native implementation instead of **This**.. 
But this only explains why the first implementation isn't working - the second one works fine with cross origin requests, though. My specific Problem is to find a way requesting a file version number from an external server.. I do only see two possibilities: Through GM_xmlhttpRequest or GM_getResourceText.

```JavaScript
// ==UserScript==
// @grant       GM_xmlhttpRequest
// @grant       GM_getResourceText
// @resource    res1 https://external.com/script_version.txt
// ==/UserScript==
    GM_xmlhttpRequest({
      method: "GET",
      url:"https://external.com/script_version.txtt",
      onload: function(response) {
             console.log(response.responseText);
      }
    });
console.log("Resource: "+ GM_getResourceText("res1"));
```

Both of it is working fine, but I got a long script that breaks if I'm not @requiring the shin.js file and therefore missing out @grant privileges.

**Comment by arantius** [comment]
This is working as designed.  Either you `@grant` yourself some special magic API, and this saddles you with the enhanced security sandbox, or you grant `none`, and you don't have either the problems that causes, or the features.

The shim is truly intended as a short term workaround to go from the old model (before `@grant`, where you implicitly had everything), to the new one (`@grant none` is better in every way, if you don't need any granted features).
