### ISSUE TITLE
Encrypted Stored Values

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2210]
GM_setValueX with encryption of value. Use of normal GM_getValue will decrypt it automatically. 

Useful for when storing important information such as login details for a site. One cannot look at the script and figure out the encryption method as it is done internally n GM.

**Comment by arantius** [comment]
What is this supposed to add?  It could only possibly hide data from an already-local attacker (who can read the encrypted file).  Said attacker could just write a script to list, get, and log all values.

**Comment by pyhedgehog** [comment]
Not immediately if user uses master password.

**Comment by TimidScript** [comment]
> What is this supposed to add? It could only possibly hide data from an already-local attacker (who can read the encrypted file). Said attacker could just write a script to list, get, and log all valuesMake the master 

Duh on my behalf.

> Not immediately if user uses master password.

And ability to remember it for whole FF session.

**Comment by pyhedgehog** [comment]
> And ability to remember it for whole FF session. 

Remembering of master password supported by FF itself. Remembering of script value for long time/only session should be configurable if needed at all.
