### ISSUE TITLE
Unique Grants: "Server not found"  

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2211]
This is an odd and unique request, but I thought I might just try my luck. Allow a grant that allows the script to run even when the server isn't found. 

I would like to have the script run even on local files ("files://"). Useful for running script on stored "scrapbook" pages.

**Comment by cletusc** [comment]
You can already run on local files by enabling `extensions.greasemonkey.fileIsGreaseable` in the `about:config`.

**Comment by LouCypher** [comment]
See http://wiki.greasespot.net/Include_and_exclude_rules#Greaseable_schemes



-- 
Zulkarnain K.
https://mozillians.org/u/zoolcar9
https://github.com/LouCypher

**Comment by TimidScript** [comment]
Thank you.

**Comment by arantius** [comment]
So is that all you wanted?

**Comment by TimidScript** [comment]
> So is that all you wanted?

Is it possible to make it run at "Server not found".

**Comment by arantius** [comment]
That's not what you described at first (well, title and description differed..).

But no.  That page runs with chrome privileges, so we will never intentionally allow injection there.

**Comment by TimidScript** [comment]
It was described "Allow a grant that allows the script to run even when the **server isn't found.** "

> page runs with chrome privileges

Didn't know that.
