### ISSUE TITLE
GM_getValue returns null when it should return undefined

### ISSUE THREAD

**Issue by kuehlschrank** [greasemonkey/greasemonkey#2213]
GM_getValue(name, default) is supposed to return undefined when name has not been set and default is not provided.

http://wiki.greasespot.net/GM_getValue#Returns

However, GM_getValue("KeyDoesNotExist") returns null under GM 3.2.

**Comment by janekptacijarabaci** [comment]
The duplicate issue (https://github.com/greasemonkey/greasemonkey/issues/2156).
