### ISSUE TITLE
hitch module not working

### ISSUE THREAD

**Issue by nlpvdkom** [greasemonkey/greasemonkey#2215]
i have an extension that modifies some GM_functions. I used to be able to use hitch module to list functions and modify them for 2.x versions. In new 3.x versions hitch module doesn't work and functions are no longer listing when calling on it.

**Comment by arantius** [comment]
This doesn't exactly sound like a supported use case.  Either way, you're going to need to be *way* more specific if you want anything to happen.

**Comment by arantius** [comment]
Can't handle such a vague request.
