### ISSUE TITLE
unsafeWindow object prototype 

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2217]
If I type this in the `Object.prototype.hello = function () { alert("hello world"); };` in a console I get a new function I can access through objects. 

If I have a script with `window.Object.prototype.hello = function () { alert("hello world"); };`, it gets called straight away by each object in the document., causing a flood of "hello world" alerts (assuming the document has objects).

Is this the correct behaviour?

(I did not know what the title should be for the post)

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/1320

**Comment by the8472** [comment]
This *might* work, but those things are extremely fickle:

```javascript
let define = Object.defineProperty;
let f = function() {
  console.log("hello");
}
let exported = this.exportFunction(f, window);

define(unsafeWindow.Object.prototype, "hello", {value: exported});
```

I have only tested it in the javascript console, it might not actually work for web content due to different security contexts.

If you really want to extend the untrusted content classes it might be better to write an extension for that has full access to all the security stuff (greasemonkey provides no way for [xray-waiving](https://developer.mozilla.org/en-US/docs/Xray_vision) on pure javascript objects).

**Comment by the8472** [comment]
exporting `Cu.waiveXrays()` into the sandbox might also help here.

**Comment by arantius** [comment]
What does "have a script" mean?  What does it `@grant`?

Also, recent update, how about window.eval()?  http://wiki.greasespot.net/Content_Script_Injection

**Comment by TimidScript** [comment]
I think I tested the issue on a was a test script that grants nothing. It was first noted on one of my scripts (Linx Amender).

I just created a new script to test the issue, but the issue is no longer present. It seemed to have fixed itself since then. ^_^

**Comment by TimidScript** [comment]
Spoke too soon. Here's the example code:

`// ==UserScript==
// @name        RandomTEST
// @namespace   Dogs
// @include     *
// @version     1
// @grant       none
// ==/UserScript==


//Object.prototype.hello = function () { alert("hello world"); };
window.Object.prototype.hello = function () { alert("hello world"); };
`

And visit this page: https://addons.mozilla.org/en-US/firefox/

Problem exists with windows.eval() also. Maybe that is the intended behaviour.

**Comment by arantius** [comment]
Cannot reproduce.  If I install that script (in `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0`) and load that page I get no alerts.  If I run `(new Date())` in the console, nothing happens.  But `(new Date()).hello` is a function and calling it alerts hello world.
