### ISSUE TITLE
script not triggered on window.open

### ISSUE THREAD

**Issue by d-faure** [greasemonkey/greasemonkey#2220]
On Firefox 39, using both GM 3.2 and 3.3beta2, the following script declared to be run on each page of a website:

    // ==UserScript==
    // ....
    // @match http://mysite/*
    // ==/UserScript==
    console.log('document.location', document.location);

isn't triggered as expected on page opened by `window.open` javascript calls. Is it due to a FF bug?

**Comment by arantius** [comment]
When I put `<button onclick="window.open('/')">window.open()</button>` in a page and have this script installed:

```javascript
// ==UserScript==
// @name        window.open() test
// @match       http://localhost/*
// @grant       none
// ==/UserScript==

dump('Ran the window.open() test ...\n');
```

the script runs after I click the button.

**Comment by d-faure** [comment]
my page is:

    <html>
    <head>
        <title>GreaseMonkey Test</title>
        <script type="text/javascript">
    function OpenWindow(url, name, features) {
        window.open(url, name, features);
    }
    </script>
    </head>
    <body>
        <h1>GreaseMonkey Test</h1>
        <p><a href="popup.html">Usual</a></p>
        <p><a onclick="Javascript:OpenWindow(this.href,'popup','scrollbars=yes,resizable=yes,width=750,height=350'); return false;" href="popup.html">Popup</a></p>
    </body>
    </html>

Following the first link work as expected, but this is not the case for the 2nd

**Comment by arantius** [comment]
With that exact HTML page and the exact script above installed, clicking both links executes the script, for me.

**Comment by d-faure** [comment]
I double checked with same result with another FF installation 38.0.5 with GM as solely activated addon and the console displayed in the embedded web dev tools.
I upgraded this FF to 39, retest in the same conditions and get the same result again.
Have you tried somewhere else than localhost?

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
GM 3.4beta1
Firefox 40.0.2 and 43.0a1 (2015-08-22) - e10s: on/off

@d-faure: I used exactly the same code as yours (https://github.com/greasemonkey/greasemonkey/issues/2220#issue-95596226, https://github.com/greasemonkey/greasemonkey/issues/2220#issuecomment-122403392). I don't know where is the problem.
