### ISSUE TITLE
GM_xmlhttpRequest binary mode not working 

### ISSUE THREAD

**Issue by flokii** [greasemonkey/greasemonkey#2221]
Binary requests made via GM_xmlhttpRequest fail silently whereas they worked in previous versions.

My debugger logs this error:
TypeError: req.sendAsBinary is not a function                xmlhttprequester.js:182:4

I'm running FF39.0 and GM3.2

**Comment by janekptacijarabaci** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#sendAsBinary()_Requires_Gecko_1.9_(Firefox_3)_Deprecated_since_Gecko_31
(https://bugzilla.mozilla.org/show_bug.cgi?id=853162)

**Comment by trespassersW** [comment]
the following code seems working flawlessly:<code>
GM_xmlhttpRequest({
	method: 'GET',
	url: URL,
//    binary: true, 
  overrideMimeType: "text/plain; charset=x-user-defined",
    ...</code></pre>

**Comment by arantius** [comment]
Looks like this was resolved by PR #2265.
