### ISSUE TITLE
GM 3.3: GM_registerMenuCommand - commandFunc (throws the warning in the Browser Console)

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2225]
![warning](https://cloud.githubusercontent.com/assets/2373486/8888285/b35c3824-32a7-11e5-887e-1cddfe69d276.png)

**Comment by arantius** [comment]
The value isn't used, so the right fix is to not pass it at all.  (Construct a new object that has only the plain string values that are actually used.)
