### ISSUE TITLE
Support Firefox for Android

### ISSUE THREAD

**Issue by ghost** [greasemonkey/greasemonkey#2226]
Please support the mobile version of Firefox, there's a huge demand for Greasemonkey.

**Comment by arantius** [comment]
Might be nice.  Would be a lot of work.

**Comment by derjanb** [comment]
Have you tried [Tampermonkey Dolphin](https://play.google.com/store/apps/details?id=net.tampermonkey.dolphin)?

**Comment by Dol-phin** [comment]
I might kick a donation on your way

@derjanb I don't want to install a proprietary web browser.

**Comment by derjanb** [comment]
@Dol-phin I'm sorry. My small mobile phone display and a too quick look at the issue made me misinterpret this as a request for a [Dolphin Browser](https://play.google.com/store/apps/details?id=mobi.mgeek.TunnyBrowser) add-on.
@arantius Should I wipe my posts to keep the issue comments clean?
Sorry again for spamming. :)

**Comment by arantius** [comment]
Don't sweat it.

**Comment by mikeloeven** [comment]
So what's the status on this there's definitely a great demand for user scripts on Android devices

**Comment by unimatrix725** [comment]
+1 *Necro Warning*
I prefer Firefox (Nightly) to Dolphin or any other browser. I really hope there will be Android support. Is there any reason why it's not supported? I have even tried overriding the compatibility check. I may try downloading, modding, then manually installing....

**Comment by AlexanderOMara** [comment]
Linking so future visitors can find this easier:

https://github.com/greasemonkey/greasemonkey/issues/2275
