### ISSUE TITLE
Support jar:file://  (e.g. zipped Java docs) - easy to implement

### ISSUE THREAD

**Issue by thiesw** [greasemonkey/greasemonkey#2227]
GreaseMonkey supports file:// by setting a config. property.
But jar:file:// does not work which is very usefull to access zipped Java docs with the Javadoc search frame script.
Example: I have the file `d:/Java/jdk-8u51-docs-all.zip`  and in Firefox a bookmark<br> `jar:file:///d:/Java/jdk-8u51-docs-all.zip!/docs/api/index.html`.

Solution is very very simple (I always manually do this in the xpi after an GreaseMonkey update):
In the file `modules\util\isGreasemonkeyable.js` add one single line:

```
case "file":
case "jar":   // new line, jar some kind of file, so use same config. property
  return GM_prefRoot.getValue('fileIsGreaseable'); 
```

**Comment by janekptacijarabaci** [comment]
See also https://groups.google.com/forum/#!topic/greasemonkey-users/cyMYHbs5hVE

**Comment by thiesw** [comment]
Firefox requires signatures now (I know, I can turn this off), so my own fix I have to apply to each new version, does not work because it breaks the signature.
It is a 2 minutes fix - it would really be great to include this in the next release!

**Comment by thiesw** [comment]
Firefox 48 does not allow unsigned addons anymore, so I cannot manually apply this very simple enhancement.
Please, may any of the Greasemonkey authors include this one-liner.

**Comment by jerone** [comment]
I think the best way to get this merged, is send an PR with your changes (maybe behind a flag for this specific feature).

**Comment by janekptacijarabaci** [comment]
Maybe there's a reason why it is not fixed. But I know of no reason.

**Comment by thiesw** [comment]
This is still an issue. If it could create problems, a config.value may be used for the new "protocol", so anybody can switch it off in case of problems (default may be set to "false").
So add the last 2 lines of the following to  modules\util\isGreasemonkeyable.js:

```
case "file":
  return GM_prefRoot.getValue('fileIsGreaseable'); 
case "jar":
  return GM_prefRoot.getValue('jarIsGreaseable');
```

(Creating a pull request might help the fixing, but I had to setup the "environment" for this, just for two lines of code. So maybe a volunteer with already setup environment might create a pull request.)

**Comment by arantius** [comment]
With WebExtensions looming, I'm loath to add any new features.

This one especially, because I believe it to be impossible (not just difficult/weird) to implement under WebExtensions.  ([Content scripts](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts) only work via [matches](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/match_patterns) which has a hard-coded (by the browser) set of allowed schemes.)
