### ISSUE TITLE
about:blank, the script with alert function - after the restart, the browser hangs

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2229]
Firefox 39.0 - Nightly 42.0a1 (2015-07-31)
GM 3.3

This user script (@run-at __document-end/document-start__):

``` javascript
// ==UserScript==
// @name        Greasemonkey - issue - 2229
// @include     about:blank
// @run-at      document-end
// @grant       none
// ==/UserScript==

alert("hello"); // modal window
```
...after restart of the browser - e.g. after installing a new extension, e.g. using drag and drop (if the page loaded is the "about:blank" and enabled browser history), the browser hangs and has to be killed in the Task Manager (and the script must be manually disabled)!

Refs https://github.com/greasemonkey/greasemonkey/issues/2041#issuecomment-107042627, https://github.com/greasemonkey/greasemonkey/issues/2041#issuecomment-107127991, https://github.com/greasemonkey/greasemonkey/issues/2041#issuecomment-126720515

**Comment by arantius** [comment]
Confirmed, with error:

    JavaScript error: resource://gre/components/nsPrompter.js, line 357: NS_ERROR_NOT_AVAILABLE: Cannot call openModalWindow on a hidden window

Somehow we're catching the (content) window loading while the (chrome) window is still invisible, in the session restore path?

**Comment by arantius** [comment]
I found [where this error is thrown](http://mxr.mozilla.org/mozilla-central/source/toolkit/components/prompts/src/nsPrompter.js#356) but if I try to detect this case (invisible window) the same way, it causes Firefox to crash (!).

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1196270

**Comment by janekptacijarabaci** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1196270#c3

I've pushed a fix to the testing branch:
https://github.com/janekptacijarabaci/greasemonkey/compare/master...janekptacijarabaci:_testBranch_aboutBlank_browserHangs
...but: isWindowVisible is always true (send __Sync__ Message)

**Comment by janekptacijarabaci** [comment]
RESOLVED WORKSFORME
https://bugzilla.mozilla.org/show_bug.cgi?id=1196270#c5 :-/

**Comment by janekptacijarabaci** [comment]
@arantius 
IMHO: This bug (also [1196270](https://bugzilla.mozilla.org/show_bug.cgi?id=1196270) - thank you in advance) is fixed for me.
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1196270#c7

__Last bad: 50.0a1 (2016-07-25)__
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Built from https://hg.mozilla.org/mozilla-central/rev/7c669d5d63efceb12696cd65cfa72c296013dafb

__First good: 50.0a1 (2016-07-26)__
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Built from https://hg.mozilla.org/mozilla-central/rev/ff1ef8ec0fd800bf6856c1572c3b1610c45e9b6a

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=7c669d5d63efceb12696cd65cfa72c296013dafb&tochange=ff1ef8ec0fd800bf6856c1572c3b1610c45e9b6a

The suspects are: [1251841](https://bugzilla.mozilla.org/show_bug.cgi?id=1251841), [1261842] (https://bugzilla.mozilla.org/show_bug.cgi?id=1261842) and [1278985](https://bugzilla.mozilla.org/show_bug.cgi?id=1278985).

**Comment by janekptacijarabaci** [comment]
@arantius 
IMHO: This bug (also [1196270](https://bugzilla.mozilla.org/show_bug.cgi?id=1196270) - thank you in advance) is fixed for me.
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1196270#c7

__Last bad: 50.0a1 (2016-07-25)__
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Built from https://hg.mozilla.org/mozilla-central/rev/7c669d5d63efceb12696cd65cfa72c296013dafb

__First good: 50.0a1 (2016-07-26)__
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Built from https://hg.mozilla.org/mozilla-central/rev/ff1ef8ec0fd800bf6856c1572c3b1610c45e9b6a

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=7c669d5d63efceb12696cd65cfa72c296013dafb&tochange=ff1ef8ec0fd800bf6856c1572c3b1610c45e9b6a

The suspects are: [1251841](https://bugzilla.mozilla.org/show_bug.cgi?id=1251841), [1261842] (https://bugzilla.mozilla.org/show_bug.cgi?id=1261842) and [1278985](https://bugzilla.mozilla.org/show_bug.cgi?id=1278985).

**Comment by klenium** [comment]
I reinstalled my win10 and all programs yesterday.
Firefox 54.0.1
Greasemonkey 3.11neta1
The script above still/again blocks FF.

**Comment by janekptacijarabaci** [comment]
Confirmed.
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1357383#c1
AFAIK: then it can be fixed (as described: https://bugzilla.mozilla.org/show_bug.cgi?id=1196270#c0).
