### ISSUE TITLE
[Wishlist] API for external programs

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [greasemonkey/greasemonkey#2231]
I know this suggestion will likely be shot down due to the potential for malicious use, but would it be possible to add an API for userscripts to call external programs?

For example, a userscript to open YouTube videos in a native media player would use this API.

Obviously, it should be implemented in such a way that the user is seriously warned about it (maybe hide it behind several warning dialogues as an advanced preference?) but it would be a useful addition.

**Comment by pyhedgehog** [comment]
-1
Such dangerous "scripts" should be implemented as a separate addon.
However I think it would be fine to pass url for open/save with (possibly) injected mime-type that can be associated by user with external player. It would be more reasonable level of security hazard for me.

**Comment by JamesTheAwesomeDude** [comment]
I tried to create a custom `mpv://` protocol which would be bound to my media player, but I never managed to get the protocol associated with a handler... :disappointed:
