### ISSUE TITLE
[FF40] tabs opened with GM_openInTab can not be closed

### ISSUE THREAD

**Issue by roger21** [greasemonkey/greasemonkey#2234]
Since FF40, some tabs opened with GM_openInTab can't be closed nor accessed (sometimes)

the close button is present (and is responsive) but it does nothing

ctrl+w does nothing

and the tab can't even be selected sometimes

it is not clear how/why some tabs work and some doesn't, closing one tab seems to trigger other tabs to malfunction

the test scripts from issue #2107 can be used to test this issue (all "click me please!" buttons are affected)

(it has been tested on a new firefox profil, a firefox profile with tabmixplus, ctr and other addons and tweaking is not affected by this issue)

**Comment by janekptacijarabaci** [comment]
Can you try it with this "patch"?
https://github.com/greasemonkey/greasemonkey/issues/2107#issuecomment-127280240

**Comment by roger21** [comment]
1. with gm 3.3 and the test script version 2 from #2107 (http://roger21.free.fr/test/test_gm_openintab_2.user.js) and a new firefox profile with FF40:

  * i work -> depending if there are already stuck-unclosable-tabs -> one or two tabs can be close (not the all 3), closed tabs are not all reopenable, if one or more tabs have been closed or if you switch to an unstuck tab, the remaining stuck tabs become un-selectable

  * i don't work -> all the tabs are closable, none are reopenable

  * i work around -> exactly the same as "i work"


2. with gm 3.3 __with the patch__ from janekptacijarabaci from #2107 (I replaced all the this._messageManager.sendSyncMessage with this._messageManager.sendRpcMessage in modules/storageFront.js since you didn't tell the line) and the test script version 2 and a new firefox profile with FF40:

  * i work -> exactly the same as previously (also closed tabs are not all reopenable)

  *i don't work -> all the tabs are closable, __all__ are reopenable

  * i work around -> exactly the same as "i work"


3. with gm 3.3 and the test script version 2 and an old customized firefox profile with FF40:

  * i work -> all the tabs are closable only one can be reopen (the first opened one apparently)

  * i don't work -> all the tabs are closable, none are reopenable

  * i work around -> exactly the same as "i work"


4. with gm 3.3 __with the patch__ and the test script version 2 and a old customized firefox profile with FF40:

  * i work -> exactly the same as previously (also only one can be reopen)

  * i don't work -> all the tabs are closable, __all__ are reopenable

  * i work around -> exactly the same as "i work"


=> the patch doesn't affect the closability issue (witch remains)

=> the patch doesn't prevail over the closability issue that also make some closed tabs un-reopenable

**Comment by roger21** [comment]
the difference between the new and old profile that doesn't make it work in the new profile is browser.tabs.insertRelatedAfterCurrent in about:config

if it is set to false, everything work smoothly (tabs are closable)

if it is set to true (default) tabs closability is compromised

**Comment by roger21** [comment]
not everything works smoothly, the reopenability is still messed up (same as described previously):

only the first one can be reopened with and without the patch for "'i work" and "i work around"

"i don't work" will work with the patch (tabs can be reopened) and won't work without the patch (tabs can't be reopened)

**Comment by janekptacijarabaci** [comment]
The new test patch...
https://github.com/greasemonkey/greasemonkey/compare/master...janekptacijarabaci:GM_openInTab_closable_reopenable

**Comment by roger21** [comment]
all cases, all perfect

much thanks

**Comment by roger21** [comment]
so i have a problem with this patch

and GM_xmlhttpRequest or XMLHttpRequest (it's the same)

after i open the tabs i silently call again the last tab url of the list (with GM_xmlhttpRequest or XMLHttpRequest) to be sure the server know i opened the last page (not to be confused since all the tabs have been open simultaneously of what i opened or not) - i explicitly send the document.cookie if i use GM_xmlhttpRequest

it used to work perfectly, the server knew i opened all the pages (at least the last one) and doesn't tell there are unseen pages

with the patch it doesn't work anymore, it behaves exactly without the extra call it tells me there are unseen pages ...

so i can't really call for a bug here since all of this is kind of async (the tab opening and the xhr call) - even calling xhr synchronously doesn't fixe it anyway - but voila :(

**Comment by janekptacijarabaci** [comment]
It was only for testing and it probably has more problems...

**Comment by janekptacijarabaci** [comment]
The new test patch (v2)...
https://github.com/greasemonkey/greasemonkey/compare/master...janekptacijarabaci:GM_openInTab_closable_reopenable

**Comment by roger21** [comment]
it seems pretty effective so far, i didn't have the "bug" once with this patch

**Comment by janekptacijarabaci** [comment]
@arantius:
http://roger21.free.fr/test/test_gm_openintab_1.user.js
=>
http://roger21.free.fr/test/test_gm_openintab_2.user.js

Clicked the red "I don't work"
=>
Clicked the orange "I work around :/"

**Comment by arantius** [comment]
I'm not clear what that comment's supposed to mean, but my above steps with that second script, and repeated a third time for the third button, everything continues to work as expected.  I can close all the tabs.

**Comment by janekptacijarabaci** [comment]
I'm sorry. Firefox e10s (e.g. 43a1): e10s must be disabled.

**Comment by arantius** [comment]
Ah, indeed, with e10s off:

When opening the tab:

> NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] tab-content.js:442:0
> NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage] content-sessionStore.js:216:0

When attempting to close it:

> NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebProgress.removeProgressListener] tabbrowser.xml:2250:0

All of these coming from core Firefox, not our code.  So it's hard to know which bit of our code is (indirectly) involved.

**Comment by janekptacijarabaci** [comment]
However, with this patch: #2262 but works for me.

**Comment by arantius** [comment]
At least at this point I have a rough idea why that patch works.  There's a race condition in that this code is itself a message handler; opening a tab causes some sort of message to be sent, putting the manager into a state it can't cope with in single process mode.

This seems like a Firefox bug.  Perhaps we add the timeout as a workaround until it's fixed.

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1200334

**Comment by arantius** [comment]
Merged: 277cc71326fed2ad4b390daa9fb2ebaee9ad080d

**Comment by janekptacijarabaci** [comment]
__The warning!__

_Conflicts, merged fails!_

See #2264

**Comment by janekptacijarabaci** [comment]
Ad https://bugzilla.mozilla.org/show_bug.cgi?id=1200334#c4

I think it's fixed...

__Last bad: 47.0a1 (2016-02-21)__
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
https://hg.mozilla.org/mozilla-central/rev/af6356a3e8c56036b74ba097395356d9c6e6c5a3

__First good: 47.0a1 (2016-02-22)__
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
https://hg.mozilla.org/mozilla-central/rev/e1cf617a1f2813b6cd66f460313a61c223406c9b

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=af6356a3e8c56036b74ba097395356d9c6e6c5a3&tochange=e1cf617a1f2813b6cd66f460313a61c223406c9b

[Bug 1245153](https://bugzilla.mozilla.org/show_bug.cgi?id=1245153) is the suspect.
