### ISSUE TITLE
GM_xmlhttpRequest  overwrite  cookie in headers parameter

### ISSUE THREAD

**Issue by crackevil** [greasemonkey/greasemonkey#2235]
GM_xmlhttpRequest  will add cookie it reads from browser with the cookie in the headers parameter, which is not the logic will work.
please fix it, under the logic either force to use browser cookie or control by input parameter.
thanks

**Comment by janekptacijarabaci** [comment]
AFAIK, dupe issue of #2330.

**Comment by janekptacijarabaci** [comment]
AFAIK, this was fixed in the issue #2330
