### ISSUE TITLE
GM_xmlhttpRequest  fetch cookie using the way different from browser does

### ISSUE THREAD

**Issue by crackevil** [greasemonkey/greasemonkey#2236]
GM_xmlhttpRequest  fetch cookie using the way different from browser does, when there are addons like multifox or cookieswap. cookies other than default profile will be invisible to GM_xmlhttpRequest

**Comment by janekptacijarabaci** [comment]
I would need an example of that (or details).

`Cookies other than default profile will be invisible to GM_xmlhttpRequest` - which is logical... (profiles are separated - but maybe it will be different: https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers)

For internal use (see also https://github.com/greasemonkey/greasemonkey/issues/2235).
