### ISSUE TITLE
Pass sameZoneAs to sandbox constructor to make GCs cheaper

### ISSUE THREAD

**Issue by the8472** [greasemonkey/greasemonkey#2237]
According to about:memory greasemonkey sandboxes all seem to live within the same zone (in process/remote tab child global, depending on e10s).

As I understand it this has a negative impact on GC performance since allocation by greasemonkey scripts triggers GCs in this fairly large zone instead of GCing in a window-specific zone.

This can be mitigated by using the [sameZoneAs option](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.Sandbox#options).

The addon SDK [does this for its sandboxes](https://github.com/mozilla/addon-sdk/blob/8e6cc79651aae915471913e45a2d38a4d651ac6f/lib/sdk/content/sandbox.js#L150), so it's probably best practice.

**Comment by arantius** [comment]
Pull request merged.
