### ISSUE TITLE
Fix breakage introduced by disabling e10s shims

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2246]
Re: 4ae802bb1246474d38b0feeb22fbc5c308a37f0d

FYI @the8472 this does at least break menu commands, when opening the monkey menu errors are logged:

    TypeError: contentWindow is null browser.js:270:17
    TypeError: el is null emptyEl.js:4:10

First when opening, second when closing.  Maybe that's all that's broken?

**Comment by the8472** [comment]
> Maybe that's all that's broken?
Who knows. :P

I'll help with fixing fallout, but first I have to get my other PRs in order if that's ok.

**Comment by arantius** [comment]
Absolutely.  Like I said, just FYI.  This issue is just so that it gets handled before 3.4 is final, even if we just revert for now.

Thanks for all your effort!
