### ISSUE TITLE
Script version no longer displayed in Firefox 40

### ISSUE THREAD

**Issue by MED-PRO** [greasemonkey/greasemonkey#2249]
Hi & thank you for the wonderful extension,
I've noticed that script version which used to be displayed next to script name in Userscript list is disappeared in Firefox 40 (Screenshot) (probably due to new Firefox Gui?)
Can you guys fix this or it should be reported to Mozilla?
Thank you!
![untitled1](https://cloud.githubusercontent.com/assets/10789454/9404556/93981e9e-47e8-11e5-905a-59fe822da1d9.jpg)

**Comment by janekptacijarabaci** [comment]
list of scripts = extensions in the list-view

See https://bugzilla.mozilla.org/show_bug?id=1175324

I'd rather not comment on it...

**Comment by MED-PRO** [comment]
Thank you for reply!

**Comment by arantius** [comment]
As [mentioned](https://github.com/greasemonkey/greasemonkey/pull/2261#issuecomment-138663537) in the pull request, there's an extension to restore this feature for all add-ons.  That seems like the right way for users to proceed, if they want to see version numbers.
