### ISSUE TITLE
If you delete a @require file (eg. a jquery.js) from a script folder, then the script no longer appears (as entry) in config.xml and it becomes removed from Addons|Userscripts list - though the .js file remains

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2250]
To reproduce (using Firefox 40 w/ GM 3.3).
- install a script that has a ` @require`declaration. For example:
```
// ==UserScript==
// @name              Test
// @version           1
// @require           http://code.jquery.com/jquery-2.1.4.min.js
// ==/UserScript==

alert('Test');
```
- Load any page (allowing the script to execute and the `query-2.1.4.min.js` to become downloaded)  
- Then navigate to the script folder `gm_scripts\Test`
and delete the `jquery-2.1.4.min.js`.

<br/>
You'll notice that, the next time you try to run the script, the script is no longer executed.

And if you close and relaunch Firefox then (although the `test.user.js` still exists):
- it  no longer appears (as entry) in the `config.xml` file and consequently
- it no longer appears in Addons | Userscripts list.

I know that  such files are contained in `config.xml` as information of every installed script
but I think that in such case, the missing files should just be re-downloaded, 
instead of the script to "disappear".

**Comment by arantius** [comment]
Manually digging into the `gm_scripts` content like this is not supported.  The only thing that's supported is editing files that already exist.
