### ISSUE TITLE
Basic GM_xmlhttpRequest doesn't call any callbacks.

### ISSUE THREAD

**Issue by n2liquid** [greasemonkey/greasemonkey#2266]
I'm using Firefox 42.0a2 / Greasemonkey 3.3 and this does not work:

```
// ==UserScript==
// @name        XmlHttpRequest
// @namespace   fakens@fakedomain.com
// @include     https://gitter.im/*
// @version     1
// @run-at      document-end
// @grant       GM_xmlhttpRequest
// ==/UserScript==

alert('Hello, world.');

GM_xmlhttpRequest({
  method: "GET",
  url: "http://www.github.com/",
  onload: function() {
    alert('Success.');
  },
  onerror: function() {
      alert('Error.');
  }
});
```

I see the first alert (Hello, world), but not the others (neither Success nor Error). I read somewhere this is a minimal script and that if it doesn't work, it would be a bug, so I'm creating this issue. Is this a bug or am I doing something wrong?

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
Firefox Developer Edition 42.0a2 (2015-09-07)
Greasemonkey 3.3 / 3.4beta3

Open a new and clean profile of Firefox. Check the Browser Console and if you see any error you can screenshot.

**Comment by n2liquid** [comment]
@janekptacijarabaci, apparently restarting Firefox did the trick. Thanks.

**Comment by staabm** [comment]
I get the very same impression with FF46 Developer Edition... the above code doesnt trigger a network request

**Comment by staabm** [comment]
Got it.. missed a `// @grant       GM_xmlhttpRequest` line
