### ISSUE TITLE
Use process scripts

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2267]
https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Message_Manager/Process_scripts

Seems like we want process scripts where we use frame scripts.  Investigate if this is true and if things would be improved by doing so.

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2179 (and [comment](https://github.com/greasemonkey/greasemonkey/issues/2179#issuecomment-112651793))

**Comment by the8472** [comment]
Using JSMs + the CPMM/PPMM is more or less equivalent to process scripts, especially if you do not import the JSM's exported symbols into the frame script scope. Which is what I've done in [this PR](https://github.com/the8472/greasemonkey/commit/6b05c4803c96ef4f947a229679e2160be13577af#diff-57b2f6ecadec34e3d3361ec4d2ec530d) for example

Also, I wrote [this page on frame/process script performance considerations](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Message_Manager/Performance) to highlight how some code patterns can be converted to process scripts.

**Comment by arantius** [comment]
Yes I wouldn't be surprised if sticking with one frame script and JSMs is the right thing in the end, but I wanted to record this option for consideration.  Whichever one works out simpler/easier to maintain.

**Comment by arantius** [comment]
I've thought about this for a while and I think @the8472 has done a good job finding efficiencies, so there's little to gain from a big refactor like this.
