### ISSUE TITLE
Support for relative file path in @require

### ISSUE THREAD

**Issue by dmak** [greasemonkey/greasemonkey#2268]
I use Greasemonkey plugin v3.3 with FF v40.0 on Windows 7 x64.
When I try to use relative path in `@require`, the script is not loaded at all. Example:
```
// ==UserScript==
// ...
@require libs/cookie.js
// ==/UserScript==
...
```
The given library is correctly placed to `%APPDATA\Mozilla\Firefox\Profiles\profile.default\gm_scripts\libs` and the script is located in `gm_scripts\`.

**Comment by janekptacijarabaci** [comment]
From:
```
@require libs/cookie.js
```
To:
```
@require ../libs/cookie.js
```

Or move the folder to "[the script name]":
```
%APPDATA\Mozilla\Firefox\Profiles\profile.default\gm_scripts\[the script name]\libs
```

**Comment by arantius** [comment]
Editing `@require` to point at local files is not supported.  The purpose of this value is to inform Greasemonkey where to *download* the resource at install/update time.

**Comment by dmak** [comment]
Currently `@require` works just fine: I can import functions from another JavaScript file. Maybe that is a side effect?
In any case, is there any way to include JavaScript code from another local file?

**Comment by arantius** [comment]
No.  The value for `@require` is a URL, not a (disk) path.

http://wiki.greasespot.net/Metadata_Block#.40require
