### ISSUE TITLE
Allow .cmd as editor executable

### ISSUE THREAD

**Issue by jerone** [greasemonkey/greasemonkey#2271]
I would like to use [Atom IDE](http://atom.io) as my userscript editor, but Atom's executable (`.exe`) is moved to another folder for every new release. To get around this, Atom supplies a `.cmd` file, but GM doesn't support this file extension to be set as userscript editor.

**Comment by janekptacijarabaci** [comment]
This can be addressed with:
![1](https://cloud.githubusercontent.com/assets/2373486/9836206/b03f9222-5a10-11e5-86f3-fa5baa3324e2.png)

**Comment by jerone** [comment]
[**@janekptacijarabaci**](https://github.com/janekptacijarabaci) commented on [13 sep. 2015 12:15 CEST](https://github.com/greasemonkey/greasemonkey/issues/2271#issuecomment-139857969 "2015-09-13T10:15:37Z - Replied by Github Comment Enhancer"):
> This can be addressed with:  
> 
> [![1](https://cloud.githubusercontent.com/assets/2373486/9836206/b03f9222-5a10-11e5-86f3-fa5baa3324e2.png)](https://cloud.githubusercontent.com/assets/2373486/9836206/b03f9222-5a10-11e5-86f3-fa5baa3324e2.png)

Confirmed, but feels a bit hacky...

**Comment by arantius** [comment]
This should be fixed and included in 3.5beta2, let me know if you still see problems with that version.
https://addons.mozilla.org/firefox/downloads/file/354794/greasemonkey-3.5beta2-fx.xpi?src=devhub
