### ISSUE TITLE
Scripts being deleted when updated

### ISSUE THREAD

**Issue by silverwind** [greasemonkey/greasemonkey#2274]
Since 3.4, when I increment the version of a script like [this](https://silverwind.io/test.user.js) and run the manual update check, I see a download bar and then the script seems to be deleted from the user's list with no way to restore, except a manual reinstallation.

When it happens a `TypeError: oldItem is null` is shown in the error console, pointing to [this line](https://github.com/greasemonkey/greasemonkey/blob/250f1884216a0c89ceea2b8449fc6f0a603d55df/content/addons4-overlay.js#L100).

**Comment by silverwind** [comment]
In case it matters: `test.meta.js` is symlinked to `test.user.js` on the server.

**Comment by janekptacijarabaci** [comment]
Confirmed on:
GM 3.4

Not confirmed on:
GM 3.4beta3-

The problem is that commit: https://github.com/greasemonkey/greasemonkey/commit/47fac825872ad2589586b42f6bbff64b0d22df05

**Comment by silverwind** [comment]
Also, for what it's worth: If I try to reinstall the script, I can't get past the installation popup and the TypeError is seen on every click of the 'Install' button.

**Comment by janekptacijarabaci** [comment]
You must manually edit the file config.xml in in the Firefox profile folder.
_<Script basedir="null"..._

**Comment by janekptacijarabaci** [comment]
One option might be to quickly release a new version, e.g. 3.4.1. But it's just a suggestion...

**Comment by arantius** [comment]
Error seen in console:

    1442434265425   addons.manager  WARN    InstallListener threw exception when calling onInstallStarted: TypeError: install.addon is null (resource:///modules/experiments/Experiments.jsm:871:1) JS Stack trace: 
    Experiments.Experiments.prototype.onInstallStarted@Experiments.jsm:871:1 
    < AMI_callInstallListeners@AddonManager.jsm:1744:15 
    < AMP_callInstallListeners@AddonManager.jsm:2724:1 
    < ScriptInstall.prototype.install/<@addons4.js:307:1 
    < hitch/<@hitch.js:27:12 
    < RemoteScript.prototype._downloadDependencies/<@remoteScript.js:527:7 
    < hitch/<@hitch.js:27:12 
    < timeout/observer.observe@timeout.js:17:7

**Comment by arantius** [comment]
I'm not seeing the same failure.  Can someone produce a detailed set of steps to reproduce please?

**Comment by arantius** [comment]
Ah, possibly the same error, different STR:

1) Open any page with a link to a user script.
2) Open a separate window to the AOM.
3) Install the script.
4) Install the script a second time.

Step 4 implicitly uninstalls the existing script, to install the second copy.  Update does effectively the same thing.  Seems to trigger this issue.  In the console:

    TypeError: oldItem is null
    observer_notifyEvent()     addons4-overlay.js:100
    Config.prototype._notifyObservers()     config.js:39
    Config.prototype._changed()     config.js:48
    Config.prototype.install()     config.js:164
    RemoteScript.prototype.install()     remoteScript.js:359
    onOk()     install.js:77
    anonymous()     dialog.xml line 375 > Function:1
    _fireButtonEvent()     dialog.xml:376
    _doButtonCommand()     dialog.xml:344
    _handleButtonCommand()     dialog.xml:332

**Comment by arantius** [comment]
Please confirm if 3.4.1beta1 ( https://addons.mozilla.org/firefox/downloads/file/352222/greasemonkey-3.4.1beta1-fx.xpi?src=devhub ) fixes this for you or not.

**Comment by janekptacijarabaci** [comment]
The original bug is fixed - for me.

But, this problem persists:
https://github.com/greasemonkey/greasemonkey/issues/2274#issuecomment-140872869

I have to do new issue? (P.S.)
https://github.com/greasemonkey/greasemonkey/issues/2274#issuecomment-140453852

**Comment by janekptacijarabaci** [comment]
Unfortunately, I found another problem:
![1](https://cloud.githubusercontent.com/assets/2373486/9919355/8594d91a-5ccc-11e5-872a-21ba1de3cae0.png)

Confirmed on:
3.4.1beta1

Not confirmed on:
3.4beta3-

**Comment by arantius** [comment]
Did 3b621bc87885268c5c834e147119722562cf8e9f just after cutting the build for this fix.

**Comment by arantius** [comment]
@janekptacijarabaci I really appreciate all the effort you put in, but wow you're hard to understand sometimes!  I'm going to take "The original bug is fixed - for me." to mean it's worth moving forward with this dot release.

As far as the "just one script" thing you've mentioned just above, please report a distinct issue.  And please include steps to reproduce; I don't know how to trigger it.

**Comment by arantius** [comment]
Pushing 3.4.1 release with just this fix now.

**Comment by silverwind** [comment]
The fix looks to be working, thanks for the quick fix!
