### ISSUE TITLE
Launching script editor fails

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2285]
Firefox: Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0
Greasemonkey: 12ec962049fe27010a7db8f25a1373b2ac166e5f

Monkey menu, new script, fill out, press ok.  Result:

    NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 
    0x80520012 (NS_ERROR_FILE_NOT_FOUND) 
    [nsIXPCComponents_Utils.import] openInEditor.js:1:0

The script is created and installed, the editor just doesn't open.

**Comment by arantius** [comment]
Actually all attempts to edit a script.

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
Windows 7/8.1

Confirmed on:
Ubuntu 15.04
