### ISSUE TITLE
No script execution at all 

### ISSUE THREAD

**Issue by vsemozhetbyt** [greasemonkey/greasemonkey#2289]
GM 3.5beta1 on Firefox Nightly 44.0a1 (2015-09-23)

No scripts execute. Checks in the GM menu say GM and the page script is active. No error messages in the web console or in the browser console.

**Comment by JohnBac** [comment]
I had the same problem with FF 41.0 and 3.5beta1 which had been running ok until 41.0
Switched to GM 3.4.1 and FF41.0  everything works

**Comment by vsemozhetbyt** [comment]
But in the GM 3.4.1 on Firefox Nightly 44.0a1 I can't edit scripts. See https://github.com/greasemonkey/greasemonkey/issues/2288 . Need to switch GM versions hither and thither.

**Comment by arantius** [comment]
Firefox 41: Confirmed.
Firefox 44.0a1: Not confirmed.

This is why I used to only develop on stable Firefox, so I didn't test things in a way that wouldn't end up working for regular people on the stable branch.  But now I have to use the non-stable branch.  *Thanks Mozilla!*  

@vsemozhetbyt This is what you get with pre-release builds.  Patience please.

Either way, I stay on GM betas to help test that in my stable day-to-day profile, so I'll also be interested in getting this fixed soon.  I strongly suspect something in #2259 and including it for more testing was clearly a good idea.

**Comment by arantius** [comment]
73736edf03220f4dd1fa4224ae65dfaa15c845b4 should fix this.

This should be fixed and included in 3.5beta2, let me know if you still see problems with that version.
https://addons.mozilla.org/firefox/downloads/file/354794/greasemonkey-3.5beta2-fx.xpi?src=devhub

**Comment by vsemozhetbyt** [comment]
GM 3.5beta2 on Firefox Nightly 44.0a1 (2015-09-23) is OK. Thank you!
