### ISSUE TITLE
[e10s off] Two install dialogs (copying *.user.js files by using the drag-and-drop method)

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2292]
Ad https://github.com/greasemonkey/greasemonkey/issues/2179 (worksforme)

I try it all the time, but for me it takes (__copying *.user.js files by using the drag-and-drop method__):
Windows 7/8.1 / Ubuntu 15.04
Firefox 41.0 / Firefox Nightly 44.0a1 (2015-09-25) __e10s: off__
*Completely empty profile (except GM)*
~~GM 3.4.1~~
GM 3.5beta2

Result: Two install dialogs...

![example](https://cloud.githubusercontent.com/assets/2373486/10117772/d3fc0e50-6462-11e5-9c40-ba55c743fa2c.gif)

__Please check it again. Thank you :-)__

**Comment by arantius** [comment]
Ah, thanks for the detail!

**Comment by janekptacijarabaci** [comment]
__Btw__

Confirmed on:
Firefox 36.0+

Not confirmed on:
Firefox 35.0-

(any version of GM)

**Comment by rn10950** [comment]
I can confirm that this happens with Firefox 42 on Windows XP [with e10s] and Firefox 38 ESR on Mac OS X Yosemite.

**Comment by daniels1989** [comment]
Possibly related. I get the same behaviour when installing a .user.js from a public Dropbox url.

Windows 7
Firefox 41.0.1
GM 3.4.1

Sample: https://dl.dropboxusercontent.com/u/936879/test.user.js

**Comment by arantius** [comment]
Returning to this.  Greasemonkey development at 9dac77c4fc9cb89b31701e41c321f6712055a81c .  Experiments include A) clicking a link in the main browser pane and B) file>open and C) drag/drop of a file onto the main browser page.

Firefox Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0, e10s on:
In all cases, I get a single installation window.

Firefox Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0, e10s off:
Clicking a link: one window.  File>open: two windows.  Drag/drop: two windows.

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0, e10s off (stable version has no e10s at all):
Clicking a link: one window.  File>open: two windows.  Drag/drop: two windows. (Same as nightly FF.)

Confirmed.  Only with e10s off, which (at least now) also affects stable Firefoxen.

**Comment by arantius** [comment]
I've looked into this a bit, but a clean solution that will work for all of file:// and http:// and for e10s on and for e10s off is currently eluding me.

**Comment by arantius** [comment]
3.7beta1 should fix this https://addons.mozilla.org/firefox/downloads/file/370567/greasemonkey-3.7beta1-fx.xpi?src=devhub

I'd appreciate any feedback either way.

**Comment by janekptacijarabaci** [comment]
It looks good. Thanks.

**Comment by janekptacijarabaci** [comment]
Update: https://github.com/greasemonkey/greasemonkey/issues/2292#issuecomment-143562376
