### ISSUE TITLE
Editor does not open in Nightly 44.0a1

### ISSUE THREAD

**Issue by func0der** [greasemonkey/greasemonkey#2295]
I can not open or edit user scripts in Nightly 44.0a1, because the editor neither an external one nor the Firefox internal does open.
The error console of Nightly does tell me this:

```
Failed to load module chrome://greasemonkey-modules/content/util/openInEditor.js. XPCOMUtils.jsm:277:0
NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
```

Seems like a file can not be imported.
If I try to open the given url from the error message in the browser I get a file with content. So that works.

I do not know if that is a bug of Firefox or a change you need to prepare Greasemonkey for.
It does not seem to happen in the newest Firefox version 41.0.1, though.

func0der

**Comment by arantius** [comment]
What version of Greasemonkey?  This sounds like #2258 which should be fixed in 3.5beta3

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/3.5beta3

**Comment by func0der** [comment]
Sorry, I forgot that.

I have 3.4.1.
I will try to install the beta and check if that helps.

**Comment by func0der** [comment]
Hey it works.

Great!
Thank you :)
