### ISSUE TITLE
Error opening input stream (invalid filename?)

### ISSUE THREAD

**Issue by func0der** [greasemonkey/greasemonkey#2296]
Hey there,

I have just updated to the new 3.5beta3 and have the following problem with Firefox 44.0.a1 on OS X.

The scripts are not called anymore. I get an error like this all the time in the Firefox console:

```
Error opening input stream (invalid filename?): file:///Users/[USER]/Library/Application%20Support/Firefox/Profiles/ol8ivicq.default/gm_scripts/[SCRIPT_NAME]/[SCRIPT_NAME].user.js
```

Anyone else encountering this bug?

func0der

**Comment by janekptacijarabaci** [comment]
Maybe you need to reinstall Greasemonkey.

I didn't try on Mac OS X, but... According to the error message... The problem may be in this line:
https://github.com/greasemonkey/greasemonkey/blob/master/modules/sandbox.js#L180
But indeed it may be a bug in Firefox.

**Comment by func0der** [comment]
Downgrade a Nightly?
That may be possible. But if FF changes that way, it should be fixed. I am going to try the newest version now and report back.

**Comment by func0der** [comment]
Nah, still a problem. Re-installing it did not help.

**Comment by janekptacijarabaci** [comment]
I thought stable version would be installed.
Possibly other versions: 42beta, 43DeveloperEdition.

**Comment by the8472** [comment]
does this happen with e10s off? also, try lowering `security.sandbox.content.level` in about:config and see if it makes a difference. I believe there are some bugs regarding process isolation.

**Comment by func0der** [comment]
@the8472 E10s was a good point. Seems like that breaks it somehow.
A non-e10s tap does execute the scripts.
So this is a FF bug then?

@janekptacijarabaci The developer edition works. I have not tried the beta yet. But I guess it is a problem with e10s since it works without it.

**Comment by janekptacijarabaci** [comment]
I think that there is a bug in the browser (AFAIK).

"The developer edition works" - including e10s?

Try older versions (try rolling back a few nightly versions):
http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2015/
and that should report the bug in bugzilla.mozilla.org.

**Comment by janekptacijarabaci** [comment]
See also:

https://bugzilla.mozilla.org/show_bug.cgi?id=337030
(https://bugzilla.mozilla.org/show_bug.cgi?id=337030#c2)

https://discussion.evernote.com/topic/27050-archived-firefox-scriptloader-errors-webclipper/

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2305#issuecomment-150898122

**Comment by arantius** [comment]
Linux, Firefox 41.0.2, Greasemonkey 3.5beta4: scripts execute fine
Linux, Firefox 45.0a1, Greasemonkey at 18f06d99caf80611956c239841455172f8d308f8: scripts execute fine
Mac, Firefox 42.0, Greasemonkey 3.5beta4: scripts execute fine
Mac, Firefox 45.0a1, Greasemonkey 3.5beta4: confirmed

Oh, wonderful, a bug that manifests only in (Firefox) nightly, only on one platform.  

If I open `file:///Users/$USER/` in Firefox and try to click the `Library` link, it refuses to load in Nightly, but works in Firefox.  That's got to be related.

**Comment by the8472** [comment]
Might be a nightly bug wrt. symlink handling then?

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1221148

I agree/hope it's probably a Firefox bug.  In my testing there's no symlinks involved anywhere.

**Comment by tonycpsu** [comment]
Anyone get bitten by this one in the latest 48.0a1 nightly?  It seemed like other recent nightlies had fixed this, but after applying the 2016-04-19 update, all my Greasemonkey scripts fail to load because of the file:/// sandboxing problem.  Downgrading to an earlier nightly fixes it, but obviously that's not a long-term solution.

**Comment by janekptacijarabaci** [comment]
Not confirmed (I can not test it on OS X), but:

http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1f16d3da9280e40ada252acf8110b91ee1edbb08&tochange=ae7413abfa4d3954a6a4ce7c1613a7100f367f9a

[Bug 1261751](https://bugzilla.mozilla.org/show_bug.cgi?id=1261751) is the suspect.

**Comment by tonycpsu** [comment]
Bugzillla's not letting me see Bug 1261751 for some reason -- is there any other way I can follow the upstream progress to see when this is fixed?

**Comment by janekptacijarabaci** [comment]
I don't know if the bug is reported and I can't find anything about that.

**Comment by the8472** [comment]
as I mentioned previously, lowering the sandboxing level should fix this for the moment

**Comment by janekptacijarabaci** [comment]
See also bug [1187099](https://bugzilla.mozilla.org/show_bug.cgi?id=1187099), [1196384](https://bugzilla.mozilla.org/show_bug.cgi?id=1196384).

**Comment by strugee** [comment]
@arantius I'm a bit confused as to what just happened - is this now basically a WONTFIX?

FWIW I can't reproduce this with `security.sandbox.content.level` set to `3` on macOS, Nightly built 2017-07-23. So I guess this isn't an issue anymore anyway?

**Comment by janekptacijarabaci** [comment]
@strugee
See #2485
