### ISSUE TITLE
problem with GM_xmlhttpRequest and location

### ISSUE THREAD

**Issue by beta002** [greasemonkey/greasemonkey#2297]
i have file a.php with content :
<?php
$cc = $_POST['type'];
if($cc=="submit"){
header("Location: http://localhost/abc.mp4");
setcookie("codeSubmit", "abcdefgh123");
}
?>

for get link mp4 and cookie, need send post request to file a.php
like this : http://i.imgur.com/83b5kNu.png

so, how can i use GM_xmlhttpRequest for post to a.php and get link mp4 and cookie

**Comment by janekptacijarabaci** [comment]
``` javascript
// ==UserScript==
// @name      Greasemonkey - issue - 2297
// @include   http://localhost/*
// @grant     GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  "method": "POST",
  "data": "type=submit",
  "url": "http://localhost/a.php",
  "headers": {
    "Content-Type": "application/x-www-form-urlencoded"
  },
  "onload": function (response) {
    console.log(response.finalUrl);
    // see https://fetch.spec.whatwg.org/#forbidden-response-header-name
    console.log(document.cookie);
  }
});
```

Next time please use https://groups.google.com/forum/#!forum/greasemonkey-users

**Comment by beta002** [comment]
if file mp4 is exist, and not in localhost with size 1GB
so, your example load with very longtime
can to avoid load content file mp4 ?

and when run GM_xmlhttpRequest in localhost with a.php in other domain
document.cookie not work, it return empty

**Comment by janekptacijarabaci** [comment]
You could add some return value.
You could use eg. XML:
http://stackoverflow.com/questions/18275529/javascript-ajax-call-a-php-that-returns-xml

**Comment by franklinyu** [comment]
Do you controls the php site? Why `POST` to get a resource, instead of `GET`? If you `GET` the large MP4 video, you can just play it with [`<video>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video), which saves you and your user.
