### ISSUE TITLE
Allow Options dialog resizing

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2300]
A follow-on from #2194 .  There, we partially improved this by allowing resizing when launching from the monkey menu, but the Options button from the AOM still launches a non-resizable window.

**Comment by janekptacijarabaci** [comment]
> the Options button from the AOM still launches a non-resizable window.

https://github.com/greasemonkey/greasemonkey/pull/2194#issuecomment-144629645

**Comment by arantius** [comment]
Yes, that is why I reported this for separate tracking.  (I don't really like that hack ...)

**Comment by janekptacijarabaci** [comment]
OK, I understand (but it works very long time - and no one cares - it indicates something that can be done).
