### ISSUE TITLE
Script editing fails with 'TypeError: GM_util.openInEditor is not a function' with today's Nightly(2015-10-22)

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2304]
STR:
- install [today's Nightly x64 (2015-10-22)](http://ftp.mozilla.org/pub/firefox/nightly/latest-trunk/firefox-44.0a1.en-US.win64.installer.exe)
and either GM 3.5 beta 4 or 3.5 stable
- install any script
- have in GM either the default editor or an external one
- now, open Browser Console and:
  - right-click on the script in the monkey menu, and then
  - about:addons|User scripts|rightclick the script|edit

You'll get in each case:

```
TypeError: GM_util.openInEditor is not a function      browser.js:267:5
TypeError: GM_util.openInEditor is not a function      addons4-overlay.js:164:37
```

**Comment by janekptacijarabaci** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1203159

Some things I just don't understand...

**Comment by arantius** [comment]
Merged.  df7654bb44ba9b08e6b7e86edab107b20d573f58
