### ISSUE TITLE
Symbolic linking doesn't work anymore

### ISSUE THREAD

**Issue by dogancelik** [greasemonkey/greasemonkey#2305]
I use symlinks in my computer for developing user scripts so I don't have edit *user.js* file in *gm_scripts* folder.

In recent update 3.5, symlinks stopped working.

**Original file:**

```
---\irccloud-sws\build\send_with_style.user.js
```

**Symlink file:**

```
---\Firefox\Data\profile\gm_scripts\Send_with_Style\send_with_style.user.js
```

* I tested it with hardlinks and hardlinks work.
* I tested this problem with Firefox 41 (Stable) and Firefox 43 (Aurora) and it occurs on both versions.
* Firefox 41 had only Greasemonkey installed and the problem still occurred.
* I get no errors on Browser Console and Page Console

**Info:** Windows 7 64-bit, Firefox 41/43, Greasemonkey 3.5

**Comment by janekptacijarabaci** [comment]
Confirmed.

The problem is this line:
https://github.com/greasemonkey/greasemonkey/blob/3.5/modules/sandbox.js#L180
(Cc["@mozilla.org/moz/jssubscript-loader;1"].getService(Ci.mozIJSSubScriptLoader) vs symbolic links)

**Comment by janekptacijarabaci** [comment]
The suggestion:

``` javascript:
subLoader.loadSubScriptWithOptions(url, {
  target: sandbox,
  charset: "UTF-8",
  async: true
});
```

or (return to the original code - relative):

``` javascript:
var code = GM_util.fileXhr(url, "application/javascript");
Components.utils.evalInSandbox(code, sandbox, gMaxJSVersion, url, 1);
```

**Comment by janekptacijarabaci** [comment]
A fix, for example: https://github.com/janekptacijarabaci/greasemonkey/tree/_fix_symlink

**Comment by arantius** [comment]
This is explicitly not a supported feature.  I'm not going to test every future change to see if Windows symlinks in who knows what patterns continue to act as they do.

@janekptacijarabaci as per your fixes, for `document-start` to work we must support a sync case, and I approve of the performance improvements that led to this change, so I'm going to leave this as is.

**Comment by the8472** [comment]
One possible fix would be monitoring the original for changes and then loading from a copy.

monitor file `var mutable = "myscript.user.js"` (which can be a symlink) -> on change copy it to `var immutable = sha1(script contents)+".js"` -> load scripts from immutable, beam down new URL on update.

**Comment by tiansh** [comment]
A possible warkaround for user is
`mklink /j Firefox\Data\profile\gm_scripts\Send_with_Style irccloud-sws\build`
instead of 
`mklink Firefox\Data\profile\gm_scripts\Send_with_Style\send_with_style.user.js irccloud-sws\build\send_with_style.user.js`
// But DO NOT USE greasemonkey's update function, or other files will be removed.

**Comment by 12425** [comment]
A hard link works for me.
```
cd gm_scripts\Send_with_Style\
mklink /H send_with_style.user.js irccloud-sws\build\send_with_style.user.js
```
