### ISSUE TITLE
Sorting by namespace

### ISSUE THREAD

**Issue by dogancelik** [greasemonkey/greasemonkey#2306]
It would be nice if a user could sort their scripts by namespace (this does not change execution order) so they can see the all scripts by same author without scrolling up and down the page.

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2145, https://github.com/greasemonkey/greasemonkey/issues/2090

**Comment by dogancelik** [comment]
I want to clarify my issue is about `about:addons` page.
