### ISSUE TITLE
More information for user scripts in List View (Add-ons page)

### ISSUE THREAD

**Issue by dogancelik** [greasemonkey/greasemonkey#2309]
The current add-on page shows these information in List view:

```
Icon  |  Script name                                        |  Options - Disable - Remove
      |  Script description - More link                     |
```

It would be nice if people could choose what they prefer to show in list view:

```
Icon  |  Script name - Script version - (Script namespace)  |  Options - Disable - Remove
      |  Script description - More link                     |
```

(ignore dashes, they are here to separate buttons, links and text to distinguish visually)

User should be enable these extra information by enabling/disabling them in Greasemonkey options dialog.

**Comment by janekptacijarabaci** [comment]
See https://github.com/greasemonkey/greasemonkey/issues/2249 (dupe of https://github.com/greasemonkey/greasemonkey/issues/2249)

**Comment by dogancelik** [comment]
Yes it is related, the linked add-on fixes the version issue, yet namespace in main label is still unavailable.

**Comment by arantius** [comment]
Not gonna put the namespace there.  Utility is too low, this is not information that most anyone needs most any time.
