### ISSUE TITLE
Editing a @require line doesn't make the different version of the relevant file to be downloaded anymore

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2311]
To reproduce 
(using GM 3.5beta4 stable in Nightly 44 x64)
_(it doesn't occur in GM 3.5 stable in Firefox 41.0.2 stable)_ :

create an empty userscript, e.g. `test`, containing just this line:
`// @require     http://code.jquery.com/jquery-1.11.3.min.js`
and reload the page.
You'll see in `gm_scripts\test` that the `jquery-1.11.3.min.js` is downloaded

Now edit that line into 
`// @require     http://code.jquery.com/jquery-2.1.4.min.js` 
and reload the page. 
You'll see now that the new file is not downloaded (the previous, `query-1.11.3.min.js` remains).

**Comment by janekptacijarabaci** [comment]
See https://github.com/greasemonkey/greasemonkey/issues/2250

**Comment by arantius** [comment]
Editing the metadata to specify a different require *should* cause them to be downloaded again.

@darkred You said "reproduce using GM 3.5beta4" and "doesn't occur in GM 3.5 stable" but also changed the Firefox versions.  Testing all combinations would be helpful.

**Comment by darkred** [comment]
[**@arantius**](https://github.com/arantius) commented on [Oct 26, 2015, 3:13 PM GMT+2](https://github.com/greasemonkey/greasemonkey/issues/2311#issuecomment-151129522 "2015-10-26T13:13:50Z - Replied by Github Comment Enhancer"):
> Editing the metadata to specify a different require _should_ cause them to be downloaded again.
> 
> [@darkred](https://github.com/darkred) You said "reproduce using GM 3.5beta4" and "doesn't occur in GM 3.5 stable" but also changed the Firefox versions.  Testing all combinations would be helpful.

But, 3.5 beta4 and 3.5 stable are in effect the same.
The only different between the two .xpi files is the different hashes and the `<em:version>3.5beta4</em:version>` --> `<em:version>3.5</em:version>` . 

What do you want me to test? The betas 1, 2 and 3?

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
3.5 stable + https://github.com/greasemonkey/greasemonkey/commit/df7654bb44ba9b08e6b7e86edab107b20d573f58
Firefox 44.0a1 Nightly x64 (2015-10-23)
Firefox 44.0a1 Nightly (2015-10-25)

**Comment by janekptacijarabaci** [comment]
GM 3.5 stable + https://github.com/greasemonkey/greasemonkey/commit/df7654bb44ba9b08e6b7e86edab107b20d573f58

Confirmed on:
Firefox 44.0a1 Nightly x64 (2015-10-23) (e10s: on/off)
Firefox 44.0a1 Nightly (2015-10-25) (e10s: on/off)

Not confirmed on:
Firefox 43.0a2 Developer Edition (2015-10-25)
Firefox 41.0.2

**Comment by janekptacijarabaci** [comment]
The problem is this line:
https://github.com/greasemonkey/greasemonkey/blob/3.5/modules/requestObserver.js#L20

Firefox 43.0a2 Developer Edition (2015-10-25)
Firefox 41.0.2
`channel.loadInfo.contentPolicyType == Ci.nsIContentPolicy.TYPE_(SUB)DOCUMENT`

Firefox 44.0a1 Nightly x64 (2015-10-23) (e10s: on/off)
Firefox 44.0a1 Nightly (2015-10-25) (e10s: on/off)
`channel.loadInfo.contentPolicyType == undefined`
