### ISSUE TITLE
Greasemonkey resource don't make local copy

### ISSUE THREAD

**Issue by timswadhin415** [greasemonkey/greasemonkey#2313]
In chrome tampermonkey you can add local resource files stored on user's computer. Those files are accessed from location set in script meta data. This is beneficial because any changes made to the resource file will be reflected in next website reload.  In greasemonkey local resource files are copied into script folder. Changes made to original resource file has no effect on scripts and there is not an easy way to update the copies in each script folder.

Can you change this or add new setting so greasemonkey resource files are not copied and instead accessed from their original location?

**Comment by arantius** [comment]
This is working as intended and will not change.
