### ISSUE TITLE
unable to add new script

### ISSUE THREAD

**Issue by Gercho4** [greasemonkey/greasemonkey#2317]
After installing the new version i see that the option for adding a new script is not working. I have 2 scripts added and I want to add a new one. When I click on new user script and  fill in the name, it tells me that a script with that name already exists it doesn't matter what I put as a name.

**Comment by janekptacijarabaci** [comment]
Dupe of #2304
This is already fixed in the nightly: https://arantius.com/misc/gm-nightly/
