### ISSUE TITLE
GM doesn't store user defined excludes

### ISSUE THREAD

**Issue by z0rc** [greasemonkey/greasemonkey#2318]
I'm using https://github.com/Owyn/HandyImage within GM. Adding user excludes works only until Firefox restart. Script options shows that user excluded are empty, every time, even after adding them, closing the options window and opening options again.

Also with this script options windows take 15-20 seconds to open, completely locking Firefox in process. Probably due to big number of `@match`.

**Comment by janekptacijarabaci** [comment]
What is Operating System (OS)?
Version of Firefox/GM?

> I'm using https://github.com/Owyn/HandyImage within GM. Adding user excludes works only until Firefox restart. Script options shows that user excluded are empty, every time, even after adding them, closing the options window and opening options again.

Not confirmed on:
Windows 7/8.1
Ubuntu 15.10
GM 3.5
Firefox Nightly 45.0a1 (2015-10-31)
Firefox 41.0.2

Check the Browser Console and if you see any error you can screenshot.

**Comment by z0rc** [comment]
Windows 10, GM 3.5, Firefox 41.0.2
![clipboard 1](https://cloud.githubusercontent.com/assets/787519/10865611/77e6eb30-8019-11e5-97ac-203faee7e5c7.png)
Nightly 45.0a1 (2015-10-31)
![clipboard 2](https://cloud.githubusercontent.com/assets/787519/10865612/8013d570-8019-11e5-80b5-ab84b6c89e08.png)

**Comment by janekptacijarabaci** [comment]
A fix (maybe) for this problem: https://github.com/janekptacijarabaci/greasemonkey/tree/scriptPrefs_veryManyMatches

**Comment by ClairelyClaire** [comment]
Was this ever fixed? I'm on 56.0b10 64-bit and GM 3.11.
