### ISSUE TITLE
Script values syncing

### ISSUE THREAD

**Issue by ebugusey** [greasemonkey/greasemonkey#2322]
Firefox 41.0.2; Greasemonkey 3.5
Firefox no longer syncs script values. Is this feature gone for good? There is still default preferences for it in https://github.com/greasemonkey/greasemonkey/blob/master/defaults/preferences/greasemonkey.js and there are records in weave log:

```
1446477324874   Sync.Declined   DEBUG   Handling remote declined: ["greasemonkey"]
1446477324874   Sync.Declined   DEBUG   Handling local declined: ["greasemonkey"]
```

**Comment by janekptacijarabaci** [comment]
about:config: extensions.greasemonkey.sync.values = true ?

See also https://groups.google.com/forum/#!topic/greasemonkey-users/2uXRQal8NTo

**Comment by arantius** [comment]
This was always an experimental feature, hidden behind a preference with no UI, and never supported.

I'm not totally clear what "Sync.Declined" means exactly.

**Comment by janekptacijarabaci** [comment]
> I'm not totally clear what "Sync.Declined" means exactly.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=978876

**Comment by ebugusey** [comment]
>about:config: extensions.greasemonkey.sync.values = true ?
Yes, this one.
>See also https://groups.google.com/forum/#!topic/greasemonkey-users/2uXRQal8NTo
Script themselves are syncing. But values are not.
