### ISSUE TITLE
Audio loaded through @resource no longer playing. FF42/GM3.5

### ISSUE THREAD

**Issue by daniels1989** [greasemonkey/greasemonkey#2326]
I load a small audio file through @resource/GM_getResourceURL, and while it returns a GM string and inserts it correctly into each source element, it wont actually play the files anymore. Loading images still works as normal.

Firefox 42
Greasemonkey 3.5

Small test script with two audio files and an image: https://dl.dropboxusercontent.com/u/936879/test.user.js

**Comment by janekptacijarabaci** [comment]
This is not the bug of GM.

1) "&lt;sound>" => "&lt;source>"

2) 
![error_002](https://cloud.githubusercontent.com/assets/2373486/10991069/657a9f06-845a-11e5-9a08-5bc8b17a6594.png)

The following works:
``` javascript
<source src="https://dl.dropboxusercontent.com/u/936879/test.mp3" type="audio/mpeg"></source>
<source src="https://dl.dropboxusercontent.com/u/936879/test.ogg" type="audio/ogg"></source>
```

**Comment by daniels1989** [comment]
woops, that was an error in the test script. changed it to <source>. Now it wont even show the controls though. Like, it briefly shows and then fades out.

**Comment by janekptacijarabaci** [comment]
> Like, it briefly shows and then fades out.

Ad 2)
Throws an error in the Browser Console...
I suppose that's associated.

**Comment by daniels1989** [comment]
So it's acting like GM strings aren't valid anymore for audio/source tags. Because this doesnt work in FF42/GM3.5, whereas it does work in FF41/GM3.5 (just tested that)
```html
<source src="greasemonkey-script:7ca92a11-b6cc-45a9-b728-23bdf2c28c68/b" type="audio/ogg">
```
Using the full url obviously works in both firefox versions.
```html
<source src="https://dl.dropboxusercontent.com/u/936879/test.ogg" type="audio/ogg">
```

**Comment by janekptacijarabaci** [comment]
See https://hg.mozilla.org/mozilla-central/rev/f4fa8c49ebc6

**Comment by arantius** [comment]
This is a bug, but as you've reported it happens when changing FF version and keeping GM stable, it's probably not ours.  https://bugzilla.mozilla.org/show_bug.cgi?id=1222761

**Comment by the8472** [comment]
There seem to be a few new flags in [nsIProtocolHandler](http://mxr.mozilla.org/mozilla-central/source/netwerk/base/nsIProtocolHandler.idl#289) I wonder if they would make a difference.

**Comment by janekptacijarabaci** [comment]
> There seem to be a few new flags in nsIProtocolHandler (URI_SAFE_TO_LOAD_IN_SECURE_CONTEXT) I wonder if they would make a difference.

Unfortunately, I see no difference.

**Comment by janekptacijarabaci** [comment]
Ad https://bugzilla.mozilla.org/show_bug.cgi?id=1222761#c4

For example: https://github.com/janekptacijarabaci/greasemonkey/tree/_testBranch_scriptProtocol

channel.originalURI = file://...mp3(ogg)
channel.loadFlags |= Ci.nsIChannel.LOAD_REPLACE

Unfortunately, I see no difference.

**Comment by Ventero** [comment]
As comments 1 and 4 on the upstream bug report reference, the actual issue is that we don't set the originalURI on the channel, which means the protocol handler actually treats it as a file URI channel.

Setting the originalURI to the URI the channel was requested for seems to indeed fix the problem (https://github.com/Ventero/greasemonkey/commit/690364bd01527cc3a274794fb0680a3666857681).

URI_SAFE_TO_LOAD_IN_SECURE_CONTEXT is only relevant for loading http (or other insecure) content in a secure (i.e. https) environment.

**Comment by arantius** [comment]
Thanks for confirming @Ventero !

**Comment by janekptacijarabaci** [comment]
Oh, so it has to be reversed... :-) originalURI = (file://... => greasemonkey-script://...)

**Comment by daniels1989** [comment]
That was fast. Thanks everyone. ^^
