### ISSUE TITLE
Add the "mozAnon / anonymous" argument to GM_xmlhttpRequest (i.e. send request without cookies)

### ISSUE THREAD

**Issue by roger21** [greasemonkey/greasemonkey#2330]
firefox/gecko provides an argument (mozAnon) to the xmlHttpRequest constructor that allows not to send cookies (and other stuff) with the request

that argument should be added to the GM_xmlhttpRequest constructor

everything is explained here https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#XMLHttpRequest%28%29 and it pretty much works afait

**Comment by janekptacijarabaci** [comment]
See also #2235 (#2254)

**Comment by arantius** [comment]
Since we're not in a window scope we have to create the XHR instance manually and I don't know how to pass an argument in, there, or how to set this readonly property afterwards.

**Comment by roger21** [comment]
hello, thx for the fix, it works fine as far as i tested

but since your last message was leading me to think it was dead, i gave it a shot myself and i come up with a different solution which doesn't require to switch to `Components.utils.importGlobalProperties(['XMLHttpRequest']);`

it is based on https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXMLHttpRequest which uses .loadFlags (in Example 2), loadFlags is not readonly (despite channel being readonly) and it must be set after the req.open (otherwise channel is not created yet)

so on line 148 of modules/xmlhttprequester.js i added::

`
  if (details.mozAnon && details.mozAnon === true) {
    req.channel.loadFlags |= Components.interfaces.nsIRequest.LOAD_ANONYMOUS;
  }
`
[no other modification from GM3.6]

it works fine too

**Comment by janekptacijarabaci** [comment]
@roger21 
See also https://github.com/greasemonkey/greasemonkey/issues/2330#issuecomment-155727121

But the author decided otherwise.

**Comment by derjanb** [comment]
> arantius closed this in 535d996 16 hours ago

Would it be possible to name it ```anonymous``` instead of ```mozAnon```?

**Comment by arantius** [comment]
Maybe both?

**Comment by arantius** [comment]
This should be fixed in build 3.8beta3; confirmation would be helpful.

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/3.8beta3

**Comment by roger21** [comment]
it works fine [mozAnon;anonymous][none;both][true;false][intra-site;cross-site]

**Comment by roger21** [comment]
the mode is not existing in GM4 could it be added?
