### ISSUE TITLE
@match cannot match anyhost with a given port and path, include can

### ISSUE THREAD

**Issue by estani** [greasemonkey/greasemonkey#2339]
For example

    // ==UserScript==
    // @name         test
    // @match         http://*:8080/*
    // ==/UserScript==
    alert('8080');

does not match anything on port 8080, but

    // ==UserScript==
    // @name         test
    // @include        http://*:8080/*
    // ==/UserScript==
    alert('8080');

does

**Comment by janekptacijarabaci** [comment]
Not confirmed on:
http://portquiz.net:8080/
http://portquiz.net:8080/path
GM 3.7beta1
FF 42.0 / 45.0a1 (2015-12-03) e10s: on/off

**Comment by estani** [comment]
wrong repo, sorry. Was meant for Tampermonkey
