### ISSUE TITLE
'Includes' before 'Excludes'

### ISSUE THREAD

**Issue by BlueMax** [greasemonkey/greasemonkey#2343]
I want to run run `Aak|Reek` GM script on specific websites only that i define in the add-on user-defined include pane. The script already contains `@include http*://*` that renders my (strict) includes useless. If i try to set `http*://*`to the blacklist my whitelist doesn't get honored at all. If i remove `@include http*://*` in the script itself the script doesn't get updated anymore (modification detected).

How can i have a strict whitelist without modifying the script so update functionality remains intact?

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2260

**Comment by BlueMax** [comment]
Thanks. I hope this will be solved soon. There are scripts that have significant performance impact that should be limited.
