### ISSUE TITLE
API for monkey-patching the content

### ISSUE THREAD

**Issue by KOLANICH** [greasemonkey/greasemonkey#2344]
Sometimes it is needed to patch the content the webpage receives through network: scripts, sounds, and responses to xhr/fetch requests.  We need API to do this.

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/1673

**Comment by arantius** [comment]
I don't think #1673 is related.  But I also vote against adding this feature.  There's serious performance and security considerations, it won't be compatible with any other user script engine, it will be hard to build and support, and it will probably be impossible once WebExtensions happens.

**Comment by KOLANICH** [comment]
>probably be impossible once WebExtensions happens.

WebExt has a dedicated API for intercepting HTTP queries: WebRequest.

**Comment by KOLANICH** [comment]
@arantius
