### ISSUE TITLE
Partial page freeze with firefox nightly

### ISSUE THREAD

**Issue by Erepb** [greasemonkey/greasemonkey#2352]
It probably will be hard to reproduce, but i play Ingress and there is a web site with a map there:
https://www.ingress.com/intel (unfortunately you have to be registered to open it)
there is also a greasemonkey script that replaces original code with it's own:
http://iitc.jonatkins.com/?page=desktop
In FF nightly after trying to zoom in/out page stops responding on other zoom and drag events however some other things work. I tried both with e10s enabled and disabled.
I don't see any suspicious activity in firebug's console.
Please tell me what additional info you need.

**Comment by ngyikp** [comment]
Does this still happen even on Firefox stable?

**Comment by janekptacijarabaci** [comment]
All variables (zoomAnimation and _zoomAnimated) set to false. How much did that help?

**Comment by Erepb** [comment]
No, it happens only on nightly FF

**Comment by Erepb** [comment]
Setting zoomAnimation to false solved issue

**Comment by janekptacijarabaci** [comment]
> Setting zoomAnimation to false solved issue

You could try different nightly versions (..."mozilla-central") of Firefox.
(https://ftp.mozilla.org/pub/firefox/nightly/2015/ and https://ftp.mozilla.org/pub/firefox/nightly/2016/)

**Comment by Erepb** [comment]
I'm fine with disabled zoomAnimation. Just wonder on which side is the issue: FF or greasemonkey. From what side i should wait the fix.
