### ISSUE TITLE
User script won't update 

### ISSUE THREAD

**Issue by ianion** [greasemonkey/greasemonkey#2353]
I have Firefox 43.0.4 and GM 3.6.
User script update manual and automatic is not working. All links are working properly. My meta is this.
// ==UserScript==
// @name             MyScript
// @namespace        https://site.com/
// @version          4.5
// @description      MyScript tool
// @downloadURL      https://site.com/docs/user.js
// @resource         CSS https://site.com/docs/user.css?49
// @noframes
// @grant            GM_addStyle
// @grant            GM_updatingEnabled
// @grant            GM_getResourceText
// @grant            GM_getValue
// @grant            GM_setValue
// ==/UserScript==

**Comment by janekptacijarabaci** [comment]
Contains too little informations about the problem...
