### ISSUE TITLE
@require JQuery breaks site's legacy JQuery

### ISSUE THREAD

**Issue by SINE** [greasemonkey/greasemonkey#2359]
Hello GM and JS gurus!

I'm trying to include JQuery into a userscript for use with a website running an IPB v 3.x forum ( http://forums.joinsquad.com ). When I do that, certain site functions stop working, unfortunately. Same issue on Chrome with Tampermonkey (even worse there, the links I refer to below don't work at all).

I only noticed this after I put a lot of work into my script, which is frustrating. So I'm wondering if there's something I did wrong or if it is an issue that can be resolved.

##### Reproduction:
* [ ] Install and activate the userscript: [userscript-jquery.zip](https://github.com/greasemonkey/greasemonkey/files/101869/userscript-jquery.zip)
* [ ] Go to http://forums.joinsquad.com (it's a legit website by a game development company, nothing to fear)
* [ ] Register and sign in, on the top right you have the user navigation buttons; css selector:
```
    #user_navigation
```
* [ ] Now you could click on the mail button for example, to get a little popup of your PMs. If the userscript is active, you will not get the popup, though. Clicking will use the HTML link and redirect you, instead of calling the according javascript function to show you the popup.

###### The console throws an error: 
![joinsquad-userscript-jquery-typeerror-githubissue](https://cloud.githubusercontent.com/assets/11297260/12530408/16d18bae-c1df-11e5-8125-c5e6beb7ca53.jpg)

Chrome's Tampermonkey will not even redirect you to the according href urls.

Anything I can do to @require the jquery without these issues? One of my scripts has
```
    // @run-at			document-start
```
 running that I would prefer to use with JQuery included.

Thanks for your attention.

**Comment by arantius** [comment]
http://wiki.greasespot.net/Third-Party_Libraries

**Comment by SINE** [comment]
Thanks, I used the suggested no-conflict setting which worked perfectly:
´´´
this.$ = this.jQuery = jQuery.noConflict(true);
´´´
