### ISSUE TITLE
(GM nightly in FF Nightly) Frequently when trying to install any script, it's name appears having: '%20' (instead of spaces) and 'runs on: *'

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2360]
To reproduce (using FF 47.0a1 x64 (2016-01-27) with a fresh profile, with only latest GM nightly 2016.01.21, in win10 x64):
e.g. visit [this page](https://greasyfork.org/en/scripts/6367-github-sortable-filelist) and press `Install`
The GM install window will appear like this:
![](https://i.imgur.com/BOyy8Gb.jpg)
Now, press `Cancel`, and try again. It most probably occur again.

After a few tries, the normal window will be displayed:
![](https://i.imgur.com/U77IPKa.jpg)

The issue never occurs in FF 44 stable x64 with GM 3.6.

**Comment by janekptacijarabaci** [comment]
Confirmed.

Ad https://github.com/greasemonkey/greasemonkey/commit/9adfced7a8cae4e56f3437d9b890ab21b7eed138

``` javascript
-function parse(aSource, aUri, aFailWhenMissing, aNoMetaOk) { 
+function parse(aSource, aUri, aFailWhenMissing) {
```
≠
``` javascript
-  var script = scope.parse(aSource, this._uri, true, aFatal); 
+  var script = scope.parse(aSource, this._uri, aFatal);
```

function parse(aSource, aUri, aNoMetaOk)
 =
scope.parse(aSource, this._uri, aFatal);

or

function parse(aSource, aUri, aFailWhenMissing)
 =
scope.parse(aSource, this._uri, true);

etc.
