### ISSUE TITLE
Tab Mix Plus' tab open location modification, does not work with userscripts

### ISSUE THREAD

**Issue by mzso** [greasemonkey/greasemonkey#2365]
Hi!

I described the problem here: https://greasyfork.org/en/forum/discussion/comment/21391

Basically when that script opens a tab it's always at the end instead of next to the current tab, which I have set in TMP.
It didn't use to be like this. It got broken sometime last year.

**Comment by arantius** [comment]
See also #2269 .  It's very difficult to get all the features to work at all on their own.  Trying to let another extension further change things is unlikely to happen.  If you can find TMP's author and get them to work together with us, maybe.

**Comment by onemen** [comment]
I'm the developer of Tab Mix Plus.

currently the incompatibility is because Tab mix fork  gBrowser.addTab to move the tab to its place but GM do it in GM_openInTab because it need to move the tab after scriptTab that is not always the current tab or last related tab that addTab.

the only safe fix to this issue is to add a preference to let the user decide where to open the tab
(unless the script call GM_openInTab with {insert: ???} argument)
```
    var prefRel = (aMessage.data.afterCurrent === null)
        ? getBool("extensions.greasemonkey.insertAfterScriptTab")
        : aMessage.data.afterCurrent;
    if (prefRel) {
      tabBrowser.moveTabTo(newTab, scriptTab._tPos + 1);
    } else {
      tabBrowser.moveTabTo(newTab, tabBrowser.tabs.length - 1);
    }
```

**Comment by the8472** [comment]
GM sets an ownerTab on the new tab, couldn't TMP just move it to the desired place after it has been created based on that information?

**Comment by onemen** [comment]
GM_BrowserUI.openInTab moveis the new tab after "TabOpen" event was fired (by gBrowser.addTab)
I can't rely on "TabMove" event to be from GM_BrowserUI.openInTab

This propose patch will allow Tabmix to override the preference that GM_BrowserUI.openInTab uses to move the tab. Tabmix is using  "extensions.tabmix.openTabNext"

**In Tab mix code i will add this**
```
    if (GM_BrowserUI && GM_BrowserUI.insertAfterScriptTab) {
      GM_BrowserUI.insertAfterScriptTab = "extensions.tabmix.openTabNext";
    }
```
**GM patch**
```
+ GM_BrowserUI.insertAfterScriptTab = "browser.tabs.insertRelatedAfterCurrent";
  GM_BrowserUI.openInTab = function(aMessage) {
    var browser = aMessage.target;
    var tabBrowser = browser.getTabBrowser();
    var scriptTab = tabBrowser.getTabForBrowser(browser);
    var scriptTabIsCurrentTab = scriptTab == tabBrowser.mCurrentTab;
    // Work around a race condition in Firefox code with E10S disabled.
    // See #2107 and #2234
    // Todo: Remove timeout when http://bugzil.la/1200334 is resolved.
    GM_util.timeout(function () {
      var newTab = tabBrowser.addTab(
          aMessage.data.url,
          {
              'ownerTab': scriptTab,
              'relatedToCurrent': scriptTabIsCurrentTab,
          });

      var getBool = Services.prefs.getBoolPref;

      var prefBg = (aMessage.data.inBackground === null)
          ? getBool("browser.tabs.loadInBackground")
          : aMessage.data.inBackground;
      if (scriptTabIsCurrentTab && !prefBg) tabBrowser.selectedTab = newTab;

      var prefRel = (aMessage.data.afterCurrent === null)
-         ? getBool("browser.tabs.insertRelatedAfterCurrent")
+         ? getBool(this.insertAfterScriptTab)
          : aMessage.data.afterCurrent;
      if (prefRel) {
        tabBrowser.moveTabTo(newTab, scriptTab._tPos + 1);
      } else {
        tabBrowser.moveTabTo(newTab, tabBrowser.tabs.length - 1);
      }
    }, 0);
  };
```

**Comment by mzso** [comment]
[**@arantius**](https://github.com/arantius) commented on [2016. febr. 16. 16:01 CET](https://github.com/greasemonkey/greasemonkey/issues/2365#issuecomment-184716867 "2016-02-16T15:01:47Z - Replied by Github Comment Enhancer"):
> See also [#2269](https://github.com/greasemonkey/greasemonkey/issues/2269 "Mysterious focus order when closing tabs opened by GM_openInTab") .  It's very difficult to get all the features to work at all on their own.  Trying to let another extension further change things is unlikely to happen.  If you can find TMP's author and get them to work together with us, maybe.

But maybe you could check/evaluate the proposed patch by the TMP dev.

**Comment by mzso** [comment]
Can I ask what does the Pony milestone mean? :)
