### ISSUE TITLE
GM_xmlhttpRequest success callback 'onload' not executing for injected code

### ISSUE THREAD

**Issue by roopalrjain** [greasemonkey/greasemonkey#2366]
I am new to greasemonkey script, I am trying to make a POST request using GM_xmlhttpRequest but on success my onload function is not executing.

I know that GM_ functions do not work for injected code so I exported them to unsafeWindow.

Below is the code which I am injected into the page (although code is very long, I am pasting only relevant part).

    function localGMCode(window, unsafeWindow) {
        window.GMUtils = {
            injectFunctionsIntoPage: function () {
                var gmInjectFuncs = {
                    GMxmlhttpRequest: function(object) { return GM_xmlhttpRequest(object); },
                };
                if ((typeof createObjectIn !== 'undefined') && (typeof exportFunction !== 'undefined')) {
                    var injectedGM = createObjectIn(unsafeWindow, {defineAs: "unsafeObj"});
                    exportFunction(gmInjectFuncs.GMxmlhttpRequest, injectedGM, {defineAs: "GMxmlhttpRequest" });
                    return true;
                }
                return false;
            },
    
            GMxmlhttpRequest: function(object) {
                console.log(object);
                if (typeof GM_xmlhttpRequest !== 'undefined') {
                    return GM_xmlhttpRequest(object);
                } else if (typeof iGraphHelperGM !== 'undefined') {
                    return iGraphHelperGM.GMxmlhttpRequest(object);
                }
                return null;
            },
        };
    
        window.WikiSnapshot = {
            uploadDataToS3: function(snapshotUrl , iGraphUrl) {
                try {
                    setTimeout(function() {
                        GMUtils.GMxmlhttpRequest({
                            method : 'POST',
                            url: <some url>,
                            onload: function(response){
                                console.log("Inside onload of GM_xmlhttpRequest");
                            },
                        });
                    },0);
                } catch (e) { console.log(e); }
            },
        };
    }

In above code when ever GMxmlhttpRequest is getting completed, onload function is not executing, (I have already tried onerror , onreadystagechane and other callback function, issue is something else).

Below is the code which is injecting above mention code in page.
    
   function injectMainIGraphHelper() {
        var script = document.createElement('script');
        script.appendChild(document.createTextNode('(' + localGMCode + ');'));
        (document.body || document.head).appendChild(script);
    }

I am running this on Firefox 38.6.0 , Greasemonkey 3.6 Please let me know if any more information is needed to debug this. Thanks in advance...

**Comment by arantius** [comment]
This is not a bug with Greasemonkey, you're looking for support, so you should head to the [http://groups.google.com/group/greasemonkey-users](greasemonkey-users) mailing list.
