### ISSUE TITLE
Greasemonkey 3.6 in SLOW MOTION on 100+ PC's, but fast on others.  A swap to Greasemonkey 2.2 fixes the problem immediately in every case -- but then a prior version of Firefox must be maintained. 

### ISSUE THREAD

**Issue by dwynalda** [greasemonkey/greasemonkey#2368]
I am hoping someone can help me.  I have written a Greasemonkey script that is used by thousands of people around the world.  I have been developing it for 8+ years now and it works really well MOST of the time.  In the past few months I have had increasing numbers of clients contact me to tell me their Greasemonkey website updates are taking about 5 times as long as they used to.    For a long time I thought there was a configuration issue on the consumer's part but now I've been able to document the issue and it does appear to be something with Greasemonkey 3.6.  

Testing (and I've done this on various machines, different operating systems, numerous types of internet connections.   

If running my script in Greasemonkey 3.6 on SPECIFIC MACHINES GM_xmlhttprequests that took <100ms on one box will take 400-600ms.    Existing script analysis of the page delays from <10ms to almost a full second on some sites.   This results in an interaction (XMLhttprequest) speed comparison of 8-10 interactions per second on the fast machine and only 1 to .5 interactions on the slower machines.  (Not slower CPU's, no known configuration is specifically causing this other than it's repeatable). 

The slowdown has persisted through at least 6 major firefox releases (43 through 48).   

Here's the rub -- on ANY of these machines I can go back to Firefox 43 and the problem persists.  But as soon as I install Greasemonkey 2.2.1 instead of Greasemonkey 3.6 the boxes spring into action and are as fast as ever.     This is something that only affects Greasemonkey 3.6 - and only on specific boxes.  

If someone has any advice as to where I might start it would be greatly appreciated.  I have literally weeks of time into analysis of this and am drawing blanks.  I cannot reproduce with a specific OS version, Firefox version etc.   It seems to be totally dependent on the Greasemonkey version -- and only on specific boxes.  (mostly very high end boxes - i7's with 16GB ram etc).  

Any suggestions as to where I might be able to pull information related to the process would be greatly appreciated.  I'd be happy to write a 'problem only' script version - reduced to a smaller amount of code that can replicate the problem (when installed on two different boxes).  

The script I have written helps people play a game so the interaction time is essential for them.

Note that this problem is not consistent with ALL boxes running Greasemonkey 3.6.  Some boxes running GM 3.6 work just fine -- without issue.   Is there something to look for that could be stopping Greasemonkey from acting or slowing it down?   A browser setting that could cause this?   Antivirus?   I'm looking for suggestions as I am not sure where to look next.
The one thing I am able to observe is that the slow boxes are NOT showing out of normal CPU usage but they DO seem to be writing to Disk all of the time (2-6MB/second) whenever a page is active.     Could the setValue and getValue routines be triggering disk writes rather than caching rewrites that are unchanged?
## 

Dan

**Comment by janekptacijarabaci** [comment]
See also https://groups.google.com/forum/#!topic/greasemonkey-users/NRpYjzYc0g0

**Comment by the8472** [comment]
You could try using the gecko profiler to see which functions exactly are blocking: https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler

> Could the setValue and getValue routines be triggering disk writes rather than caching rewrites that are unchanged?

Yes, set/getValue are not optimized in any way, they go straight to the database.

> GM_xmlhttprequests that took <100ms on one box will take 400-600ms. 

that's most likely a separate issue. You probably should file separate issues for different APIs being slow.
