### ISSUE TITLE
Style flicker with GM_getResourceURL

### ISSUE THREAD

**Issue by Watilin** [greasemonkey/greasemonkey#2369]
Hi folks!

This may be an issue, or simply a question. I'd like to inject styles with `GM_getResourceURL` because it enables me to view and edit the stylesheet in Firefox's native console.
```javascript
var $link = document.createElement("link");
$link.rel = "stylesheet";
$link.href = GM_getResourceURL("style-resource");
document.head.appendChild($link);
```

But I recently noticed that it causes a flicker on slow-loading pages, whereas inserting with a `<style>` tag and `GM_getResourceText` (or simply using `GM_addStyle`) does not.

Is this normal? If not, I guess I spotted a bug. But maybe `GM_getResourceURL` relies on some asynchronous file loading, making my issue unfixable. In which case I'd just like to know if my intuition was correct.

**Comment by arantius** [comment]
`GM_getResourceURL()` returns a URL that Firefox can load, like any other.  It should be functionally equivalent to the `file:///` URL which points at the file on disk that is truly being referenced.

In order to help, we'll need at a minimum an exact script that demonstrates the problem, and exact information about at which URL the problem surfaces.

**Comment by Watilin** [comment]
There:
https://github.com/Watilin/gm-issue-2369/blob/master/GM_getResourceURL_CSS_Flicker_Test.user.js
Refresh the page a few times and you should see the flicker.

**Comment by the8472** [comment]
That script runs at `DOMContentLoaded`, which is fairly late. For earlier style insertion you need to use `@run-at document-start`, then check if the `<head>` element is available and insert your style there or use a mutation observer if it is not yet available.

**Comment by Watilin** [comment]
Ok so my issue is just that I don't inject my styles soon enough? I've never noticed it before.

Since it's not a Greasemonkey issue, I'll close this ticket.

I made some further tests with `@run-at document-start` and the flicker didn't occur anymore. Same file as before– I'll keep “it for the record”.

I've got an hypothesis about why flickers don't seem to occur when injecting at `DOMContentLoaded` using a `<style>` tag and `GM_getResourceText`: because the style is parsed inline, it somehow halts the CSS engine, just like inline scripts. Thus the page rendering is delayed until after the injected CSS has been parsed. Do you think this theory is right?
