### ISSUE TITLE
"Operation is insecure" error while trying to convert Image to Data URL

### ISSUE THREAD

**Issue by piyushsoni** [greasemonkey/greasemonkey#2373]
Hi,
I was trying to get the data URL of an image on a webpage I have my script running on, but I get the error : 'The operation is insecure' while doing that. I understand that this is probably due to cross-origin restriction, but I was just wondering if it's an overlook, because the other cross origin restrictions don't apply while working in GM (GM_xmlHTTPRequest). I am using the method given in the top answer here to convert an image object to its corresponding Data URL : http://stackoverflow.com/questions/934012/get-image-data-in-javascript 

Thanks !

**Comment by janekptacijarabaci** [comment]
On what website?

See also https://en.wikipedia.org/wiki/Content_Security_Policy

**Comment by piyushsoni** [comment]
@janekptacijarabaci : Any website (including this one). The method canvas.toDataURL() is the exact method which returns that error. I read about CSP, but isn't GreaseMonkey as an add-on already helping us overcome those restrictions (https://en.wikipedia.org/wiki/Content_Security_Policy#Browser_add-ons_and_extensions_exemption) ? Just like it allows us cross site scripting, IMO it should allow us this as well. 

Thanks,

**Comment by arantius** [comment]
On Mon, Mar 7, 2016 at 11:55 AM, Piyush Soni <notifications@github.com>
wrote:

> I read about CSP, but isn't GreaseMonkey as an add-on already helping us
> overcome those restrictions


Definitely no.  There are a very small and fixed set of privileged APIs
provided, but that in no way extends to generally violating any normal
policies for any possible operation.

If you want support, you should provide an exact/complete script (not just
a theoretical name of a method being called), and exact URL and exact
description of how your expectations are being violated.  The script should
be as small as possible to demonstrate this condition.

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2046

The example:
``` javascript
// ==UserScript==
// @name        Greasemonkey - issue - 2373
// @include     *
// @grant       none
// ==/UserScript==

function getBase64Image(img) {
    // Create an empty canvas element
    var canvas = document.createElement("canvas");
    canvas.width = img.width;
    canvas.height = img.height;

    // Copy the image contents to the canvas
    var ctx = canvas.getContext("2d");
    ctx.drawImage(img, 0, 0);

    // Get the data-URL formatted image
    // Firefox supports PNG and JPEG. You could check img.src to
    // guess the original format, but be aware the using "image/jpg"
    // will re-encode the image.
    var dataURL = canvas.toDataURL("image/png");

    return dataURL.replace(/^data:image\/(png|jpg);base64,/, "");
}

if (document.getElementsByTagName("img")[0]) {
  try {
    console.log("getBase64Image - " + location.href + ":\n"
      + getBase64Image(document.getElementsByTagName("img")[0]));
  } catch (e) {
    console.log("getBase64Image - " + location.href + ":\n" + e);    
  }
}
```
I see no problem with this.

**Comment by piyushsoni** [comment]
Hi @arantius , @janekptacijarabaci ,
The very example script given above (I have almost the same code) does not work on this particular webpage I'm typing this on (https://github.com/greasemonkey/greasemonkey/issues/2373#issuecomment-193347522). I am not sure how it is working for @janekptacijarabaci but it gives me "The operation is insecure" error (so goes into the catch block in the above script) in the latest version of Firefox. 

Thanks...

**Comment by janekptacijarabaci** [comment]
__github.com__:
Content-Security-Policy: default-src *; base-uri 'self'; block-all-mixed-content; child-src 'self' render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com api.github.com www.google-analytics.com api.braintreegateway.com client-analytics.braintreegateway.com github-cloud.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-src 'self' render.githubusercontent.com; img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com checkout.paypal.com collector.githubapp.com *.gravatar.com *.wp.com *.githubusercontent.com; media-src 'none'; object-src assets-cdn.github.com; plugin-types application/x-shockwave-flash; script-src assets-cdn.github.com; style-src 'self' 'unsafe-inline' assets-cdn.github.com

Can you please give another example?

**Comment by piyushsoni** [comment]
Another website example? amazon.com, stackoverflow.com, youtube.com, mail.yahoo.com, wikipedia.com, and many more - gives the same error on all of them. I'm trying to do some image processing on these images if possible. 

So the question is, should I expect this to be fixed at all (and look for other ways if possible), or are there no hopes here? Thanks ...

**Comment by janekptacijarabaci** [comment]
Copy the above code into the Scratchpad and run it (created a new empty profile without extensions).

``` javascript
getBase64Image
href: http://www.amazon.com/
src: http://g-ecx.images-amazon.com/images/G/01/gno/sprites/nav-sprite-global_bluebeacon-1x_optimized_fresh._CB296386779_.png
SecurityError: The operation is insecure.
```
``` javascript
getBase64Image
href: http://stackoverflow.com/
src: http://i.stack.imgur.com/vobok.png
SecurityError: The operation is insecure.
```
``` javascript
getBase64Image
href: https://www.youtube.com/
src: https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif
SecurityError: The operation is insecure.
```
``` javascript
getBase64Image
href: https://login.yahoo.com/?.src=ym&.intl=us&.lang=en-US&.done=https%3a//mail.yahoo.com
src: https://s1.yimg.com/rz/d/yahoo_en-US_f_p_bestfit_2x.png
SecurityError: The operation is insecure.
```
``` javascript
getBase64Image
href: https://en.wikipedia.org/wiki/Portal:Biography
src: https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/Cscr-featured.svg/20px-Cscr-featured.svg.png
SecurityError: The operation is insecure.
```
``` javascript
getBase64Image
href: http://www.mozilla.cz/
src: http://1.gravatar.com/avatar/a375266f9c45bddb8ae3af9267a65fd7?s=24&d=mm&r=g
SecurityError: The operation is insecure.
```
But:

``` javascript
getBase64Image
href: https://www.google.com/?gws_rd=ssl
src: https://www.google.com/logos/doodles/2016/international-womens-day-2016-5748446948491264-res.png
iVBORw0KGgoAAAANSUhEUgAAAF8AAAApCAYAAABTN/UpAAAAJklEQVRoge3BMQEAAADCoPVPbQ0PoAAAAAAAAAAAAAAAAAAAAI4MPQUAAXe4LNkAAAAASUVORK5CYII=
```

``` javascript
getBase64Image
href: https://en.wikipedia.org/wiki/Main_Page
src: https://en.wikipedia.org/static/images/wikimedia-button.png
iVBORw0KGgoAAAANSUhEUgAAAFgAAAAfCAYAAABjyArgAAAAIUlEQVRoge3BMQEAAADCoPVPbQsvoAAAAAAAAAAAAADgZiq/AAEBxhaoAAAAAElFTkSuQmCC
```
``` javascript
getBase64Image
href: http://www.mozilla.cz/
src: http://www.mozilla.cz/wp-content/themes/OneMozilla-MozillaCZ/img/rss-new-16.png
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABg0lEQVQ4ja2SUWujQBRG/WFK6bRFpMERZycadaRGE6tJDNlNWJZCCezLEvZN6Ft+69mHgiGkZTew9/Gbw5m5945l/Y9yHIlt+9zehjw8aK4WCKGRssT3p3ieQQiN48h/FylVIWWB708JghlhWCNliesm14ksy7IOhzfSdImUJUq9i4TQeF58fWtaz1GqRqma+/voc4lt+ziO5O7uywVgzAqtG7Re4LrJxwIhNEEww/enuG6CbftnYJouiaIVWi8Q4vISazbbEsctUk7RukGpGs8z3NwEAxyGFcZsCMOa0ch8Po/9/jdxvCRN14xGT0PffX8kilbk+RbXnfx9oFnWkWXfeHzMBzhJFpTlD5SqLwWOI892fji8kedbJpNuyF5eflEUO/J8SxA8nSSuO8GYDcZszp6XZR1V9R2lqiFL0zVN84rW85NgPH6mbfe07Z4wPMHz+Y6meWU8fh6yOF7SdT/PMqvvj2RZhzFr+v44HFTVV6LofTsnQUtR7JCyuP5nflR/AGJ15Z+n1Y9kAAAAAElFTkSuQmCC
```

IMHO: This is not a bug in Greasemonkey.

**Comment by arantius** [comment]
On Tue, Mar 8, 2016 at 3:56 AM, Piyush Soni <notifications@github.com>
wrote:

> So the question is, should I expect this to be fixed ..
>

No.  It's not a bug.  It's also not a feature I'd ever expect to add.

**Comment by ArkadiuszMichalski** [comment]
Is there any easy way to solve this problem? Many pages use different domain for static files (including medias, like pictures) and we can't process this file via GM. I saw there was some addons like CORS or other that modificate headers but using them is not practical.

**Comment by piyushsoni** [comment]
@arantius, no problem, I can understand. But yes, as @ArkadiuszMichalski asked if there's any way you can suggest to solve this problem (even if it involves changing my local copy of GreaseMonkey), that will be awesome!

**Comment by the8472** [comment]
@ArkadiuszMichalski, why not just fetch the image file with the privileged XHR and then encode the binary data to base64?

**Comment by piyushsoni** [comment]
At least in my case, the image URL itself is a 'randomized' URL which generates a different one each time, so I won't get the one on the page.

**Comment by the8472** [comment]
you could also manipulate the response headers to include a CORS policy that prevents canvas tainting. or get the file from the cache... there are many ways to do it if you actually write an addon instead of trying to work within GM's limited security scope.

**Comment by ArkadiuszMichalski** [comment]
@the8472 In past, when I try find "easy and fast" solution, fetch not exist, but even now its not solve all problems, like indicated by the @piyushsoni (every request genarate new img, what I experienced too). Now, when we have all this new and useful "HTML5 stuff", restrictions arising from the CSP for such simple things are very annoying for script authors. I know we can use next addon, external tools or other solutions, but it introduces additional dependencies and may not work beetwen different browsers/platforms. Giving some access to the multimedia data (at least read) we would have a new area for a wide range of interesting scripts. In GM we have some control over the behavior of XHR and a similar possibility for multimedia (in particular images) would be useful in such cases. But it seems to me that this never will happen, so for all concerned scripters, however, I recommend increasing the knowledge of other areas, because the browser itself is extremely annoying muzzle.

**Comment by piyushsoni** [comment]
@the8472 : Yes, The only problem is all the add-ons I have written so far were GreaseMonkey scripts converted to add-ons using Scriptify or something :). I don't yet know how to write one from scratch, but currently I am downloading the source of various screenshot taking add-ons to see if I can edit them to my needs (many use pre-compiled code and add dlls so won't be possible there etc.).
