### ISSUE TITLE
no install window

### ISSUE THREAD

**Issue by Owyn** [greasemonkey/greasemonkey#2378]
No install window appear when opening https://raw.githubusercontent.com/Owyn/HandyImage/master/HandyImage.user.js
but window appears if I open exact same file from my local drive

GM 3.7
FF 44\ FF 45

in FF 44 if I reload the tab or hit F6, Enter (reload address) - nothing happened, but in FF 45 reloading address brings it up, but just refreshing page (F5) does nothing - this is relevant to github url

https://greasyfork.org/scripts/109-handy-image/code/Handy%20Image.user.js
for this url nothing helps to bring up the install window except downloading user.js file and dragging it into firefox

**Comment by arantius** [comment]
How about with GM 3.8beta2?

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/?page=1#version-3.8beta2

**Comment by Owyn** [comment]
with beta it works fine, please bring the fix to stable asap.
