### ISSUE TITLE
Script does not start at all

### ISSUE THREAD

**Issue by rekire** [greasemonkey/greasemonkey#2380]
I am writing a small script for an internal tool on my mac work station. On Windows I had never problems. Here is my current script:

```
// ==UserScript==
// @name        Doesn't work
// @namespace   my.namespace
// @description Example
// @include     http://www.example.com:8080/whatever/blah
// @version     1
// @grant       none
// ==/UserScript==
history.replaceState = function(data, title, url) {
    console.log("caught history.replaceState(" + data + ", " + title + ", " + url + ")");
};

GM_log("Hello, World!");
```

That page I am talking about uses POST for every operation, however on the login page via GET is my script also not been executed. Any idea?

**Comment by arantius** [comment]
The problem is on your end.  You've not provided enough detail to explain why.  I'd *guess* that you should move the log first; you might not be allowed to overwrite that browser feature?
