### ISSUE TITLE
Attacker (evil extension) chooses a path *.exe (etc.)

### ISSUE THREAD

**Issue by janekptacijarabaci** [greasemonkey/greasemonkey#2383]
Ad http://www.theregister.co.uk/2016/04/04/top_firefox_extensions_can_hide_silent_malware_using_easy_prefab_tool/

AFAIK:
For example, you could use this: https://github.com/greasemonkey/greasemonkey/commit/7031a322ee537accabe058136efa3084d448bac5
(Components.stack [e.g.: "chrome://greasemonkey/", "chrome://greasemonkey-modules/"] checking, e.g. in function GM_PrefManager, and elsewhere...)

**Comment by arantius** [comment]
Maybe some actual information about what's going on here?

https://www.internetsociety.org/sites/default/files/blogs-media/crossfire-analysis-firefox-extension-reuse-vulnerabilities.pdf

Which says

> These  vulnerabilities  allow  a  seemingly  innocuous  extension
> to reuse security-critical functionality provided by other legit-
> imate, benign extensions to stealthily launch confused deputy-
> style  attacks.

So I generally fail to understand the point.  If you're already an installed extension, you already have access to everything?!?  This is just a detection avoidance scheme?

**Comment by janekptacijarabaci** [comment]
I created this thread mainly for debate :-)

**Comment by jscher2000** [comment]
The researchers seem to recommend namespacing functions and minimizing globals to reduce the extent to which other extensions could access security-sensitive functionality. Sounds good in principle, but I suspect those kinds of changes could introduce a lot of subtle bugs that take considerable time to shake out. So it's difficult to assess whether that risk is worth taking, and whether that time is worth spending all things considered.

**Comment by Ventero** [comment]
@jscher2000 That was the same impression I got from reading the paper, but it's not like just reducing globals is enough to get rid of the issue.

An extension could always just `Cu.import("chrome://greasemonkey-modules/content/util/fileXhr")` to achieve the same effect - namely being able to execute potentially dangerous functions without explicitly having the actual code in their extension.

**Comment by arantius** [comment]
Given the expectation for WebExtensions to obsolete this, I have no plan for investing time in an earlier fix.
