### ISSUE TITLE
GM_xmlhttpRequest connection doesn't abort when the tab is closed

### ISSUE THREAD

**Issue by Unknowny** [greasemonkey/greasemonkey#2385]
I suppose this isn't much of a problem, but I just happened to run into it.
I do `window.addEventListener('beforeunload', handler.abort)` to fix it.

**Comment by janekptacijarabaci** [comment]
Here is a proposal to fix this issue:
https://github.com/janekptacijarabaci/greasemonkey/tree/GM_xmlhttpRequest_closedTab_abort

**Comment by the8472** [comment]
@janekptacijarabaci not sure if that would fix the issue. An XHR can be long-running so it would have to be closed by an event or somehow have the channel tied more closely to the window

**Comment by janekptacijarabaci** [comment]
@the8472 
That is why I did not pull request it yet... :-)
