### ISSUE TITLE
Script refuse to work

### ISSUE THREAD

**Issue by hien4990** [greasemonkey/greasemonkey#2389]
Site:http://www.wilderssecurity.com
Non of scripts use with greasymonkey work
while use with tampermonkey in chrome they are work.
Please fix.

**Comment by janekptacijarabaci** [comment]
Can you please provide an example?

**Comment by hien4990** [comment]
> Can you please provide an example?
example :https://greasyfork.org/vi/scripts/5727-google-translator-tooltip-expanded-fork

**Comment by janekptacijarabaci** [comment]
If you take a look to the Browser Console you can see:
`Content Security Policy: The page's settings blocked the loading of a resource at `...

Dupe of https://github.com/greasemonkey/greasemonkey/issues/2046
