### ISSUE TITLE
Greasemonkey not working with Firefox 49 and Mac osx

### ISSUE THREAD

**Issue by ale82to** [greasemonkey/greasemonkey#2392]
Greasemonkey is not working with Nightly 49 in osx because of sandbox if ES 10 is enabled any fix?

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2296#issuecomment-212077858

**Comment by buttafoo** [comment]
Eh, so what's the fix for this? All my greasemonkey stuff just broke because I upgraded to 49.0.1

**Comment by ERnsTL** [comment]
Greetings, GM is also broken for me with FF49, on Ubuntu.

```
alert("GM_info.isPrivate = " + GM_info.version);
var valueGMs = (typeof GM_setValue === "function");
var valueGMg = (typeof GM_getValue === "function");
alert("GM_getValue is function: " + valueGMg + valueGMs + (typeof GM_getValue));
//FIXME ^ why is GM_*Value false false undefined?
alert("Type of GM_listValues: " + (typeof GM_listValues));
```

Only the GM_info object returns correct numbers, the other functions like ```GM_listValues```, ```GM_getValue```, ```GM_setValue``` are all ```undefined```.
