### ISSUE TITLE
Secure user input

### ISSUE THREAD

**Issue by lkraider** [greasemonkey/greasemonkey#2393]
Currently if a user script requires user input, it has to resort to creating it in the DOM of the website being processed, which opens the input to being handled by the website if it's malicious.

For example, if the user script needs to ask a password that should not go to the website, but just be used to extract data from the website (example encrypted data intended for the user), there is no secure way to present that input control.

This is a request to have Greasemonkey provide a way to gather user input without being possible for the website to intercept the data. Ideally in a way that can be styled and embedded on the page.

**Comment by pyhedgehog** [comment]
Why you can't use `window.prompt`?

**Comment by janekptacijarabaci** [comment]
> Why you can't use  window.prompt ?

You cannot mask the input... (*)

**Comment by pyhedgehog** [comment]
However it doesn't leaks to web page context.
You can use [showModalDialog](https://developer.mozilla.org/en-US/docs/Web/API/Window/showModalDialog) with possible [polyfill](https://github.com/niutech/showModalDialog).

**Comment by janekptacijarabaci** [comment]
> You can use [polyfill](https://github.com/niutech/showModalDialog).

AFAIK: It solves nothing... (document.body.appendChild)
https://github.com/niutech/showModalDialog/blob/gh-pages/showModalDialog.js#L26

Ad:
> Currently if a user script requires user input, it has to resort to creating it in the DOM of the website being processed, which opens the input to being handled by the website if it's malicious.

**Comment by pyhedgehog** [comment]
Yes. Right now you has two options:
 1. Hide password from spy behind your shoulder (and use some html).
 2. Hide password from malicious site (and use `window.prompt`).

**Comment by the8472** [comment]
One solution I can think of is opening a sandboxed iframe with a `data:` uri and change your GM script to also inject itself to data uri iframes. Then you can create the form inside that iframe. and communicate with the parent script either via postMessage or the storage API.

If the iframe is sandboxed then the untrusted page should have no access to the iframe and thus no way of manipulating it.

**Comment by pyhedgehog** [comment]
This is not cross-browser solution, but it may work…

**Comment by the8472** [comment]
Both firefox and chrome support data uris/srcdoc for iframes, [iframe sandboxing](http://caniuse.com/#search=sandbox) and [postmessage](http://caniuse.com/#search=postmessage). Which other browsers have userscript support but don't support sandboxing?

**Comment by lkraider** [comment]
What was the resolution for handling secure input?
