### ISSUE TITLE
Greasemonkey API documentation is outdated

### ISSUE THREAD

**Issue by CoolCmd** [greasemonkey/greasemonkey#2396]
https://github.com/greasemonkey/greasemonkey/issues/2199
https://wiki.greasespot.net/GM_info

**Comment by janekptacijarabaci** [comment]
I would like to change name...

Also:

https://wiki.greasespot.net/GM_info
vs.
`uuid`, `scriptSource`, `localizedDescription`, `localizedName`, `noframes`, ~~unwrap~~

https://wiki.greasespot.net/GM_openInTab
vs.
https://github.com/greasemonkey/greasemonkey/pull/2257 (synchronize API with Tampermonkey)

https://wiki.greasespot.net/GM_getValue, https://wiki.greasespot.net/GM_setValue
vs.
https://github.com/greasemonkey/greasemonkey/issues/2172 (JSON/objects)

https://wiki.greasespot.net/Metadata_Block
vs.
`author`, `installURL`, `homepageURL`

https://wiki.greasespot.net/GM_xmlhttpRequest
vs.
https://github.com/greasemonkey/greasemonkey/commit/59f07764b8c975cc3cef451743e3f2754fc95f45 (add the `responseXML`)
vs.
https://github.com/greasemonkey/greasemonkey/commit/f6c624d7d4e8b09bd5c30784126fa52a2cffec0d (add the `onloadend`/`onloadstart`)
vs.
https://github.com/greasemonkey/greasemonkey/issues/2330 (add the `mozAnon`/`anonymous`)

...and maybe something else.

**Comment by arantius** [comment]
1) The documentation is on a wiki.  Just register (and perhaps ping me with your username .. fighting the spam war is a pain) and you can fix it yourself.
2) No you can't log in with github.  It's standard mediawiki.  All it needs is a username and password.
3) Thanks for your effort @janekptacijarabaci but deciphering those terse notes is a lot of work, so I have not tried to address any of those.  Maybe some time.

**Comment by marsjaninzmarsa** [comment]
@arantius with pleasure, but registration seems to be broken.
