### ISSUE TITLE
there is no http headers when sending binary data

### ISSUE THREAD

**Issue by holynewbie** [greasemonkey/greasemonkey#2397]
I'm using the [Binary library](http://userscripts-mirror.org/scripts/show/69456) for sending a file to my server. But there is something wrong. And the I'm using the HttpFox to check the headers and post data.

when I send an image , the headers are empty

![no headers](http://ww4.sinaimg.cn/large/87c9773cjw1f3wfvjrzroj20lk05j3yx.jpg)

and the picture below shows the  post data

![post data](http://ww4.sinaimg.cn/large/87c9773cjw1f3wftk8yhej20m3086adu.jpg)

But when I send the post without the binary data of the image by annotating the code (at line 76 in the script and the script is in http://userscripts-mirror.org/scripts/source/69456.user.js) ,there  are headers!
```Javascript
//build.push(value);
```
![post data](http://ww4.sinaimg.cn/large/87c9773cjw1f3wg53utntj20lp06j0tw.jpg)

![headers](http://ww4.sinaimg.cn/large/87c9773cjw1f3wg5n4rd4j20r00aqwiq.jpg)

Sorry for my poor English

**Comment by janekptacijarabaci** [comment]
It doesn't look like a bug in Greasemonkey.

HttpFox - 0.8.14.1-signed - __May 14, 2014__
(see also: https://code.google.com/archive/p/httpfox/issues)

In the Browser Console:
![1](https://cloud.githubusercontent.com/assets/2373486/15281117/8cb4676c-1b38-11e6-9843-acfc690017dd.png)

Temporary fix:
_"chrome/content/HttpFox.js" - line 1019_

From:
`request.PostDataParameters[i][1] !== null`

To:
`(request.PostDataParameters[i][1] !== null && request.PostDataParameters[i][1] !== undefined)`

**Comment by holynewbie** [comment]
got it. Thanks.
