### ISSUE TITLE
Option to disable updates by default

### ISSUE THREAD

**Issue by Forkest** [greasemonkey/greasemonkey#2398]
Every user script has an option

> Automatic Updates: Default On Off

But I can't find a way to make Default be considered as Off

**Comment by arantius** [comment]
This should be the Firefox standard update behavior:

https://blog.mozilla.org/addons/how-to-turn-off-add-on-updates/

Does this work for you?

**Comment by Forkest** [comment]
Sorry, that was my misinterpretation, everything works just as with usual Firefox add-ons.
Automatic Updates option only disables automatic installation of the next version, but doesn't stop the browser from trying to download it. `extensions.update.autoUpdateDefault` (which is controlled by Update Add-ons Automatically in the drop-down menu) is reponsible for the default value and it works. Just it isn't what I wanted. Thanks for the `extensions.update.enabled` option, it disables automatic update checks completely, although I hoped for such a setting on a per-script basis.
My real problem is that I install my scripts from a site with basic auth, and it pops out with auth request window almost every day when it tries to update scripts. I was confused about these requests at first, until found out what causes them, now it's just annoying. I see only two options on how to stop them: clear `updateurl` in `gm_scripts\config.xml` or set `updateURL` to `about:blank` in every script. Not very convenient. Besides both methods drop errors in Browser Console when it tries to update, although everything works.

**Comment by arantius** [comment]
Glad you figured this out.  Unfortunately we ride on top of the standard extension/add-on behavior, so we're not in complete control of that.

**Comment by janekptacijarabaci** [comment]
So it's done so intentionally...

Otherwise I suggest (addons4.css):
```
#detail-updates-row {
  display: -moz-box;
}  

#detail-findUpdates-btn {
  display: none;
}
```
AFAIK: The getter and setter are being correctly.
