### ISSUE TITLE
greasemonkey script cannot access the page DOM data

### ISSUE THREAD

**Issue by dutony** [greasemonkey/greasemonkey#2399]
Hi there,

I am trying to use my GM script to get a text string value from one of the DOM elements on the page.

For example, there is "\<p>Hello\</p>" on the page, and I want to pass "Hello" to my GM script. If I do console.log(unsafeWindow), I can even see "Hello" is actually located at: unsafeWindow.content.document.body.childNodes[1].childNodes[0].data

However when I tried to access it like this: var greeting = unsafeWindow.content.document.body.childNodes[1].childNodes[0].data; I get Error: Permission denied to access property "document". And if I try to access it like this: var y = unsafeWindow.document.getElementById("main"); I got the same error.

My grant is set as: @grant  none. Not sure what I am doing wrong here.

**Comment by janekptacijarabaci** [comment]
What is the specific website?

**Comment by dutony** [comment]
It's a website I am developing (there is no public URL yet). I think I know the reason. I am trying to access the unsafeWindow that was triggered by an iframe. It seems that the unsafeWindow from iframe and unsafeWindow from the webpage aren't the same. What's the best way to share the variables/functions between those two?

**Comment by janekptacijarabaci** [comment]
See http://stackoverflow.com/questions/7995223/error-permission-denied-to-access-property-document
