### ISSUE TITLE
script name with suffix ".db" 

### ISSUE THREAD

**Issue by shyangs** [greasemonkey/greasemonkey#2400]
1.  Install https://greasyfork.org/scripts/19997-somthing-db
2.  Install https://greasyfork.org/zh-TW/scripts/19998-somthing
3. Reload page
4. An error occurred

![db](https://cloud.githubusercontent.com/assets/244384/15594512/bfa33b86-23e8-11e6-916b-eddcda6e2fb3.png)

**Comment by janekptacijarabaci** [comment]
Confirmed.

In this example (after item 1) "somthing.db" is the name of the folder. Can't create a file if a folder exists with the same name.

Is there a simple solution for this problem? It's hard to say... (these "folders"/"db files" may already exist)
