### ISSUE TITLE
GM_xmlhttpRequest().abort behavior inconsistent with XMLHttpRequest.abort()

### ISSUE THREAD

**Issue by CoolCmd** [greasemonkey/greasemonkey#2401]
if request is already complete, XMLHttpRequest.abort() do following:
- remove 'load' event from queue
- add 'abort' event to queue
- set 'readyState' = unsent

Greasemonkey doesn't do above steps.

**Comment by janekptacijarabaci** [comment]
Please give a brief example - where you see a problem (XMLHttpRequest() vs. GM_xmlhttpRequest).

**Comment by CoolCmd** [comment]
@arantius agrees to fix this bug if I provide an example?
