### ISSUE TITLE
GM is renaming and duplicating my files

### ISSUE THREAD

**Issue by oabtm** [greasemonkey/greasemonkey#2404]
Hi,
on every script that use @require, GM is duplicating my files as filename-1.js, and use this files instead of mine, i don't know if it's a feature(?), but i searched and i found nothing about how i could disable it.
Could that be caused by the fact that i use another text editor?or that i open them manually instead of clicking on "Edit this user script"?

**Comment by arantius** [comment]
http://www.catb.org/esr/faqs/smart-questions.html

You haven't provided nearly enough detail.  At a minimum, show me the script in question.

**Comment by oabtm** [comment]
@arantius The same thing happen with all scripts.
I just tried this and it happen again:
`// ==UserScript==
// @name        testgithub
// @namespace   test
// @include     *
// @version     1
// @grant       none
// @require     test.js
// ==/UserScript==

console.log(test)
`
test.js:
`var test = "test"
`

**Comment by oabtm** [comment]
@arantius The same thing happen with all scripts.
I just tried this and it happen again:
`// ==UserScript==
// @name        testgithub
// @namespace   test
// @include     *
// @version     1
// @grant       none
// @require     test.js
// ==/UserScript==

console.log(test);
`

**Comment by oabtm** [comment]
@arantius The same thing happen with any script.
I tried this and it happen again.
http://pastebin.com/BV1bYyVN

**Comment by arantius** [comment]
There's no "test.js" file relative to that URL you posted.

https://wiki.greasespot.net/Metadata_Block#.40require

The documentation specifically says that `@require` takes a _URL_, not a path.  You're telling it to download a file called "test.js" and it tries to store it where you've already put it.
