### ISSUE TITLE
Can't create a new script

### ISSUE THREAD

**Issue by Kern3l** [greasemonkey/greasemonkey#2405]
I'm trying to create a new script. In popup window "New script..." I fill a name and correct a regexp with an URL (I'm creating a new script while visiting a page). Like always. Then I click "OK", expecting the popup to close and new script editor to open, but nothing happens. There's a pushing animation of the "OK" button, but the window doesn't close and no other window appears. "Use script from clipboard" misworks the same way.

How can I debug this? Thanks in advance!

Firefox - newest, Greasemonkey - newest.

**Comment by janekptacijarabaci** [comment]
Please try it with a clean profile of Firefox. Check the Browser Console and if you see any error you can screenshot.

What is the specific script name / website (regexp website)?

**Comment by Kern3l** [comment]
Stable, latest (automatic updates on Windows).

With a clean profile it doesn't work in the same way.

Script name - any (I provided random strings when checking now), but it checks input, complaining if I give an empty name.
Website - first examine.com, now firefox start page (from clean profile). I tried empty too, when creating a script from about:addons page.

**Comment by janekptacijarabaci** [comment]
FF 47.0.1, GM 3.8
Not confirmed

Check the Browser Console and if you see any error you can screenshot.
("Tools - Web Developer - Browser Console" - CTRL-SHIFT-J)

**Comment by Kern3l** [comment]
Whoah:
`NS_ERROR_FILE_TOO_BIG: Component returned failure code: 0x8052000f (NS_ERROR_FILE_TOO_BIG) [nsIFile.createUnique]`
I used a solution from here: https://github.com/greasemonkey/greasemonkey/issues/2069 I had -turtles- gm-temp all the way down to 9999. 30KB total :≻ Now I can create a new script. Thanks!
