### ISSUE TITLE
Script wont install on light firefox 47, using GM 3.8

### ISSUE THREAD

**Issue by Question2** [greasemonkey/greasemonkey#2406]
Im trying to install a script on light firefox 47 using GM 3.8, the install window pops up, but clicking install does nothing at all...no error messages or anything.

Error console shows the following : 

Timestamp: 13/7/2016 3:31:38 PM
Error: invalid 'in' operand handler
Source File: resource://gre/modules/RemoteAddonsParent.jsm
Line: 589

Timestamp: 13/7/2016 3:31:38 PM
Error: FEBE.febeLoad is not a function
Source File: chrome://febe/content/febe.js
Line: 28

Timestamp: 13/7/2016 3:31:40 PM
Error: TypeError: GM_util.getService is not a function
Source File: chrome://greasemonkey/content/addons4-overlay.js
Line: 154

Timestamp: 13/7/2016 3:31:41 PM
Error: 1468387901798	addons.manager	ERROR	Exception calling provider <unnamed-provider>.getInstallsByTypes: TypeError: GM_util.getService is not a function (chrome://greasemonkey-modules/content/addons4.js:58:5) JS Stack trace: AddonProvider.getInstallsByTypes@addons4.js:58:5 < callProviderAsync@AddonManager.jsm:254:12 < AddonManagerInternal.getInstallsByTypes/<.nextObject@AddonManager.jsm:1987:9 < AsyncObjectCaller.prototype.callNext@AddonManager.jsm:373:7 < AddonManagerInternal.getInstallsByTypes/<.nextObject/<@AddonManager.jsm:1992:11 < PluginProvider.getInstallsByTypes@PluginProvider.jsm:178:5 < callProviderAsync@AddonManager.jsm:254:12 < AddonManagerInternal.getInstallsByTypes/<.nextObject@AddonManager.jsm:1987:9 < AsyncObjectCaller.prototype.callNext@AddonManager.jsm:373:7 < AsyncObjectCaller.prototype.callNext@AddonManager.jsm:375:7 < AddonManagerInternal.getInstallsByTypes/<.nextObject/<@AddonManager.jsm:1992:11 < this.XPIProvider.getInstallsByTypes@XPIProvider.jsm:4061:5 < callProviderAsync@AddonManager.jsm:254:12 < AddonManagerInternal.getInstallsByTypes/<.nextObject@AddonManager.jsm:1987:9 < AsyncObjectCaller.prototype.callNext@AddonManager.jsm:373:7 < AsyncObjectCaller@AddonManager.jsm:353:3 < AddonManagerInternal.getInstallsByTypes@AddonManager.jsm:1985:5 < this.AddonManager.getInstallsByTypes@AddonManager.jsm:3409:5 < getAddonsAndInstalls@extensions.js:1713:3 < gListView.show@extensions.js:2702:5 < gViewController.loadViewInternal@extensions.js:810:7 < gViewController.loadView@extensions.js:729:5 < gCategories.initialize/<@extensions.js:1767:7 < _fireOnSelect@richlistbox.xml:77:13 < selectItem@listbox.xml:243:11 < onxblmousedown@listbox.xml:974:13
Source File: resource://gre/modules/Log.jsm
Line: 753

Timestamp: 13/7/2016 3:31:41 PM
Error: 1468387901810	addons.manager	ERROR	Exception calling provider <unnamed-provider>.getAddonsByTypes: TypeError: GM_util.getService is not a function (chrome://greasemonkey-modules/content/addons4.js:49:7) JS Stack trace: AddonProvider_getAddonsByTypes@addons4.js:49:7 < callProviderAsync@AddonManager.jsm:254:12 < AddonManagerInternal.getAddonsByTypes/<.nextObject@AddonManager.jsm:2528:9 < AsyncObjectCaller.prototype.callNext@AddonManager.jsm:373:7 < AddonManagerInternal.getAddonsByTypes/<.nextObject/<@AddonManager.jsm:2533:11 < PluginProvider.getAddonsByTypes@PluginProvider.jsm:142:7 < callProviderAsync@AddonManager.jsm:254:12 < AddonManagerInternal.getAddonsByTypes/<.nextObject@AddonManager.jsm:2528:9 < AsyncObjectCaller.prototype.callNext@AddonManager.jsm:373:7 < AddonManagerInternal.getAddonsByTypes/<.nextObject/<@AddonManager.jsm:2533:11 < this.LightweightThemeManager.getAddonsByTypes@LightweightThemeManager.jsm:450:7 < callProviderAsync@AddonManager.jsm:254:12 < AddonManagerInternal.getAddonsByTypes/<.nextObject@AddonManager.jsm:2528:9 < AsyncObjectCaller.prototype.callNext@AddonManager.jsm:373:7 < AddonManagerInternal.getAddonsByTypes/<.nextObject/<@AddonManager.jsm:2533:11 < this.XPIProvider.getAddonsByTypes/<@XPIProvider.jsm:4004:7 < makeSafe/<@XPIProviderUtils.js:168:17 < asyncMap@XPIProviderUtils.js:196:5 < this.XPIDatabase.getAddonList/<@XPIProviderUtils.js:1055:9 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < Promise*this.PromiseWalker.scheduleWalkerLoop@Promise-backend.js:747:11 < this.PromiseWalker.schedulePromise@Promise-backend.js:779:7 < Promise.prototype.then@Promise-backend.js:454:5 < this.Downloads.getList@Downloads.jsm:204:12 < fvd_single_Downloads</this.getActiveDownloads@downloads.js:360:13 < fvd_single_Downloads</this.statusPage@downloads.js:389:4 < FVD_SINGLE/this.setup_buttons@fvd_single.js:2257:3 < FVD_SINGLE/this.browser_progress_listener.onLocationChange@fvd_single.js:2158:6 < wrapProgressListener/ListenerHandler.get/<@RemoteAddonsParent.jsm:949:11 < callListeners@tabbrowser.xml:490:24 < _callProgressListeners@tabbrowser.xml:505:13 < mTabProgressListener/<._callProgressListeners@tabbrowser.xml:560:22 < mTabProgressListener/<.onLocationChange@tabbrowser.xml:812:17 < HTML5History.pushState@extensions.js:325:5 < gViewController.loadView@extensions.js:726:7 < gCategories.initialize/<@extensions.js:1767:7 < _fireOnSelect@richlistbox.xml:77:13 < selectItem@listbox.xml:243:11 < onxblmousedown@listbox.xml:974:13
Source File: resource://gre/modules/Log.jsm
Line: 753

Timestamp: 13/7/2016 3:31:50 PM
Error: TypeError: GM_util.getService is not a function
Source File: chrome://greasemonkey/content/addons4-overlay.js
Line: 154

Timestamp: 13/7/2016 3:31:52 PM
Error: TypeError: NetworkError when attempting to fetch resource.

Timestamp: 13/7/2016 3:31:53 PM
Error: TypeError: GM_util.getService is not a function
Source File: chrome://greasemonkey-modules/content/remoteScript.js
Line: 364

Timestamp: 13/7/2016 3:33:29 PM
Error: TypeError: GM_util.getService is not a function
Source File: chrome://greasemonkey/content/addons4-overlay.js
Line: 154

Timestamp: 13/7/2016 3:33:31 PM
Error: TypeError: GM_util.getService is not a function
Source File: chrome://greasemonkey/content/addons4-overlay.js
Line: 154

Timestamp: 13/7/2016 3:33:32 PM
Error: Error: unsafe CPOW usage forbidden
Source File: chrome://browser/content/tabbrowser.xml
Line: 494

**Comment by Question2** [comment]
This is the script in text form as the github refuses to allow me to upload it, even if i zip it up : 

// ==UserScript==
// @name           HV - Show Gems
// @version        1.0.1
// @namespace      HVSG
// @match          http://hentaiverse.org/*
// ==/UserScript==

if (gem = document.getElementById('ikey_p')) {

	var icon;
	switch (gem.getAttribute('onmouseover').match(/'([^\s]+) Gem/)[1]) {
		case 'Mystic': icon = 'e/channeling.png'; break;
		case 'Health': icon = 'a/hp.png'; break;
		case 'Mana': icon = 'a/mp.png'; break;
		case 'Spirit': icon = 'a/sp.png'; break;
	};
			
	var img = document.querySelector('.btp').appendChild(document.createElement('img'));
	img.src = 'http://ehgt.org/v/' + icon;
	img.style.cssText = 'border: 1px solid black; position: absolute; float: right; right: 6px; top: 8px;';

}

**Comment by arantius** [comment]
> Im trying to install a script on light firefox 47

"Light Firefox"?  Some fork of Firefox?  If it works on real Firefox and not there, the bug is probably in Light Firefox.

**Comment by Question2** [comment]
https://sourceforge.net/projects/lightfirefox/

Thats their site...when i was installing greasemonkey though, it didnt popup with any warning message saying that it was incompatible.
