### ISSUE TITLE
Caching of Local Require File

### ISSUE THREAD

**Issue by benbrad** [greasemonkey/greasemonkey#2408]
I use @require to load a local file shared by several scripts.  When I update the shared file, it's not reloaded by the scripts.  The shared file is copied into the same directory as the sript.  Can I disable this caching?

**Comment by janekptacijarabaci** [comment]
See https://wiki.greasespot.net/Metadata_Block#.40require
`Each @require is downloaded once, when the script is installed`

See also https://github.com/greasemonkey/greasemonkey/issues/2268

**Comment by garyking** [comment]
If you want to use a shared file, then a build system would be best to use, like Gulp. The file that Greasemonkey copies to its own folder can be modified, so use a build system that concatenates the scripts you want together and writes to that file.

**Comment by arantius** [comment]
This behavior is intentional and will not be changed.
