### ISSUE TITLE
Greasemonkey breaks first Firefox Sync

### ISSUE THREAD

**Issue by Paviluf** [greasemonkey/greasemonkey#2409]
Hello,

Greasemonkey breaks first Firefox Sync when you launch the browser. Here are all the infos from Firefox bug tracker :

https://bugzilla.mozilla.org/show_bug.cgi?id=1286618
https://bugzilla.mozilla.org/show_bug.cgi?id=1286618#c9

Thanks !

**Comment by arantius** [comment]
As mentioned at bugzilla, cannot confirm.  (Yet?)

**Comment by arantius** [comment]
This is the half-baked script value sync code; even if value sync is disabled, any `GM_set` increases the sync score; score should not be modified if the feature is disabled.

**Comment by arantius** [comment]
Oh, IOW: #2414 .

**Comment by Paviluf** [comment]
Thank you !
