### ISSUE TITLE
Suggestion Tab ID

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2411]
Ability to tell if you are in the same tab by using an ID for each tab. So even if a new web page is loaded and you want to keep settings according to tab the data is not lost.

**Comment by arantius** [comment]
`window.name = Math.random()` ?  That gets you really close.

**Comment by TimidScript** [comment]
Thanks. Will test it out.

**Comment by TimidScript** [comment]
Reopened: Problems occur if more than one script tries to utilize it.

**Comment by marsjaninzmarsa** [comment]
Just namespace it, duh. Or even use `GM_info.uuid` for sure.
