### ISSUE TITLE
Issue with disabling  Greasemonkey from the Icon on toolbar

### ISSUE THREAD

**Issue by mikhoul** [greasemonkey/greasemonkey#2416]
I have a small annoying issue on one of my profile I use for developing  with Greasemonkey.

When I want to disable completely GM by pressing the GM Icon on the toolbar the icon become ghosted but the script still work ???  

I don't use the cache, I've tried restarting Firefox, updated to GM Beta but it still do the same... 
Tried also to hard refresh Firefox but nothing work.ed, 

Strangely if I disable the script directly by "unticking" it via the Icon menu it stop to work  http://i.imgur.com/XlDsdir.png as it should do but the Global disabling don't work.

On my other profile it work fine only on my dev  profile, if you have some clue about what is cause of this strange behavior I'd like not to be able to make a new profile with all my custom  settings.

What can I try to resolve this strange issue ? 

Regards

**Comment by janekptacijarabaci** [comment]
If the @include parameter has the value "about:blank" (or about:reader...) - see:
https://github.com/greasemonkey/greasemonkey/pull/2417

If it is otherwise:

Steps to reproduce:
The disabling of Greasemonkey => After reload the page (F5) => The script still work?

Version of Firefox (Stable, Nightly...)? Check the Browser Console and if you see any error you can screenshot.

**Comment by mikhoul** [comment]
No it is not the @include I've double checked even if it was my own script to be sure ;-) 

Steps to reproduce:
Disable Greasemonkey with the Icon ---> Hard Reload the page  => The script still work !  :disappointed: 

Console have no error.

Tested with Firefox 47.0.1 with GM latest Release and Beta under Windows 7 x64

I've even tried to uninstall reinstall GM and nothing change.

It could be hard to duplicate since on my other profiles with the same Firefox installation I don't see this happening.

Here's the Script if you want to try, right now the script will just throw an "alert()" for debugging purpose  since it's not yet finished :see_no_evil: 
```

// ==UserScript==
// @name        PageOrama CKeditor Boosted
// @namespace   Mikhoul
// @description Change the old CKeditor for a newer version with Full Features
// @include     http*://www.pageorama.com/*
// @version     1
// @require https://greasyfork.org/scripts/12317-checkforbadjavascripts-js/code/checkForBadJavascriptsjs.js?version=73234
// @run-at document-start
// @grant GM_addStyle
// ==/UserScript==

/*- The @grant directive is needed to work around a design change
    introduced in GM 1.0.   It restores the sandbox. MIKE MIKE MIKE   
*/



function insertNewJavascriptSource() {

var scriptNode          = document.createElement ("script");
scriptNode.setAttribute ("src", "http://cdn.ckeditor.com/4.5.10/full-all/ckeditor.js");
document.head.appendChild (scriptNode);

}


function replaceTargetJavascript (scriptNode) {
    var scriptSrc   = scriptNode.textContent;
    scriptSrc       = scriptSrc.replace (
        /CKEDITOR.replace(.*)[\s\S]*\}\);/,
        
		"/7777/"
    );

    addJS_Node (scriptSrc);
}



checkForBadJavascripts ( [
  //  [true, /pageorama/, insertNewJavascriptSource ],
	[false, /480/, replaceTargetJavascript]
] );



document.body.appendChild( document.createElement( 'script'));
document.body.lastChild.innerHTML = 'function myFunc() { alert( "the Zalert"); } myFunc();'; // add content i.e. function definition and a make a call

```

**Comment by janekptacijarabaci** [comment]
Thank you for your example. Your issue has to do with that bug (#2417) :-)
