### ISSUE TITLE
Script synchroization not working

### ISSUE THREAD

**Issue by davidfoerster** [greasemonkey/greasemonkey#2421]
I'm using Firefox Sync to synchronize my browser profile between multiple operating systems on the same machine (Windows and Linux) and just noticed that Greasemonkey scripts aren't synchronized. The add-on version is 3.8.

Can I gather any logs to help debug this issue?

**Comment by n00b42** [comment]
I have the same problem.

Syncing between two of my instances works fine (both Linux, might be a coincidence), but syncing with a third one (Windows) does not work (both ways).

Some of the scripts are local (written by myself, but they sync fine between the first two instances)

[error-sync-1471556495974.txt](https://github.com/greasemonkey/greasemonkey/files/425992/error-sync-1471556495974.txt)

**Comment by janekptacijarabaci** [comment]
Ad n00b42:
See also https://github.com/greasemonkey/greasemonkey/issues/1573#issuecomment-25669956

**Comment by n00b42** [comment]
@janekptacijarabaci Thanks, I did not know that only the URLs are synced. Then everything is clear and I could solve it by hosting my scripts online.

@davidfoerster Is your problem the same, meaning do you "try" to synchronize local scripts, or is it a different problem?

**Comment by davidfoerster** [comment]
Yes, that's it. Hosted scripts are synchronised but local ones aren't. I guess I know what I'll have to do then.

**Comment by janekptacijarabaci** [comment]
@arantius
AFAIK:
However, the following error message (`NS_ERROR_FILE_UNRECOGNIZED_PATH`):
https://github.com/greasemonkey/greasemonkey/issues/2421#issuecomment-240874522
in the log should not be there.
