### ISSUE TITLE
GreaseMonkey Update Cache Issue (Minor problem)

### ISSUE THREAD

**Issue by n00b42** [greasemonkey/greasemonkey#2425]
Every now and then I have problem with the cache when I try to update within less than around 5 minutes (or something like that), first thought it was github gist's fault, but does not look that way:

```
Opening:
https://gist.githubusercontent.com/raw/***id***/
shows my script and pressing F5 always yields the latest version

Opening
https://gist.githubusercontent.com/raw/***id***/myscript.user.js
shows the GM install/update screen, but shows the current installed version

Right-Click on Script - "Search Updates" - also does not retrieve the new update.
```

Note: Explicitly using FFs "Clear Cache" has no influence, so something else seems to cache.

Waiting some minutes always resolves the problem. Then either accessing the URL or pressing "Seach Updates" works as expected.

**Comment by n00b42** [comment]
Seems related to #1878 even though this very old issue was resolved by a patch.

**Comment by janekptacijarabaci** [comment]
This url:
`https://gist.githubusercontent.com/[user]/raw/***id***/myscript.user.js`
is redirected to: 
`https://gist.githubusercontent.com/[user]/raw/***id***/***revision-id***/myscript.user.js`
__after every change__.

See `https://gist.github.com/[user]/***id***/revisions` - buttons "View".

AFAIK: It doesn't look like a bug in Greasemonkey.

**Comment by janekptacijarabaci** [comment]
__gist.githubusercontent.com__

The file is cached and served from the cache server ():

![all](https://cloud.githubusercontent.com/assets/2373486/18018963/17ba1338-6bda-11e6-90a0-a40e3d82137a.png)

It doesn't look like a bug in Greasemonkey.
