### ISSUE TITLE
Test in Firefox 50

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2426]
https://bugzilla.mozilla.org/show_bug.cgi?id=1214824

Firefox 50 is intentionally breaking CPOW wrappers.  We need to test and see if we're accidentally relying on them anywhere.

**Comment by janekptacijarabaci** [comment]
See also https://arewee10syet.com/
CPOWs: 0 :-)
(this is CPOW data returned to telemetry)

**Comment by arantius** [comment]
Some simple testing also shows no warnings or errors logged.
