### ISSUE TITLE
GM_setValue()/GM_getValue() + e10s + many tabs

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [greasemonkey/greasemonkey#2427]
Are there any guidelines on how to properly use this two methods in e10s (with many process and many tabs which operate on the same entry)? In single proces model I don't have any problem with tons of tabs, but when I switch to e10s (set 16 process) then script is not working properly, it loses data between tabs, generally has a gap beetwen read / write operations.

I see that each script has own database in `gm_scripts` folder. Can you explain how GM make read/save in e10s? It happend directly in content process (process/frame script) or in chrome? This operation is synchronous or asynchronous?

To simplify the problem is as follows:
- 10 tabs must log 50 account (at the same time), get some data, save this data, and log out.
- each tab is run in separate content process.

All tabs operate on the same data, like `GM_getValue("data")`, this data store basic structure (string in JSON format), and when tab work it take some free account (mark that this account now is not free), log account, save data for this account, log out. The same happend in all other tabs in the same time. 

Actually we don't have any command to check if entry was modified before we want save them, in practice we can manually save some time (when invoke `GM_setValue`), other tab can read that time and before next save it can once again check that time, if entry has been modified then tab can repeat it actions. But I'm not sure if that solution will help in e10s.

Do you have any tips what to do, so that each tabs will operate on current/actual data in e10s?

**Comment by ArkadiuszMichalski** [comment]
I try older GM (3.8 to 3.4) and the same. To ensure that tabs don't share cookie (and other data) I use New Container Tab (news from Nightly). I open 4 container in new window and observing action. And see this:
1. Sometimes one tab want to log the same account what other tab.
2. Even if [1] not happend, then I still see some gap in log data, probably some tabs operate on not actual data and save them.

Maybe I should split data from one entry to more (each account would have own entry)? But some small part must be shared beetwen all process (I mean the one that informs which accounts are free or taked).

**Comment by janekptacijarabaci** [comment]
See also #1728

**Comment by ArkadiuszMichalski** [comment]
Sure, but disadvantages of localStorage are significant (isolate to per-(sub)domain and per-protocol) and in Contextual Identity this data are not share beetwen each container.

In e10s world (when we want share data beetwen process) probably in chrome there should be some filtration. Consider this ("CP" is single tab in own content process):
- CP1 read data
- CP2 write data
- CP1 write data << this action should be stopped because we read data and before saving other process change them. We should be able to call at this point some callback to take other steps (for example refresh page so script once again will make action). It's just a hypothetical assumption that illustrates the problem.

**Comment by ArkadiuszMichalski** [comment]
Hmm, I save for data additional timestamp by using `performance.now()`, at the beginning script get this time and before save new data once again check this time, if it change then save data with new time, in other case reload page. 
And now test this new case in 4 containers and 50 accounts. Now is little better, see less gaps and see in logs that sometimes time was change before next save. But gaps still exist and it was only 4 containers. In single process version I don't have any gaps, even when run 10, 20, 30 or more tabs in the same time. It must somehow be resolved on the GM side, as users we don't have more solutions.

**Comment by arantius** [comment]
Greasemonkey is great for fixing and enhancing the web, it's why I love it.  What you're describing, however, "log [into] 50 account[s], get some data, save this data, and log out" instead sounds like *abusing* somebody's web service.  It's not the sort of thing I like to invest my personal time into, for zero compensation.

Maybe I've interpreted this wrong, and if so please explain what you're really doing.  But otherwise, I'm pretty darn sure that true multi-threading and parallel processing is a legitimately hard thing to do well, and I don't believe a change to GM is going to make that magically go away.

**Comment by ArkadiuszMichalski** [comment]
I use a lot of scripts to automate my work, life is too short to do everything by hand.  Some times ago I test e10s in this scenerio because [new Firefox has big performance problem with a single process when we operate in more tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1140892).  At that time e10s was not better but lately I notice that something move forward so once again start testing. And in ocassion I noticed that I have a problem with sharing data when using e10s (comparing to single process) so report this. I silently hoped that maybe there is some magical solution to solve this. 

Probably this will involve a small group of users GM, but it may increase when e10s is turned on by default. Any useful information (eg. how GM read/write data or how to live in e10s) can be subsequently useful for others in future. I know that the work in parallel is not to easier, but on the other hand, it is an interesting challenge.  Maybe changing GM functions is not the best idea but in the future adding an additional mechanism that allows convenient to share data between processes probably would be useful for more users.

Backing to case I make some correct for above solution and once again checki this, but this time in 5 tabs (one normal + 4 containers). Now get only 0-2 gaps, in most case only 0 or 1 (before was 5 or more), so see progress. Next step will be:
- run all in RAMDisk to see if less latency will helps
- split data to the minimum amount of shared, mabye will helps
- implement save/get data via NodeJS (if synchronous XHR will still exist) or fork GM (but I still don't know addons ecosystem).
Of course the easiest way is once again checked problematic account but this is only a temporary solution, problem may be repeated in the other cases, so better have something that works in each of them.

**Comment by the8472** [comment]
> and I don't believe a change to GM is going to make that magically go away.

Maybe an optional parameter + return value to GM_setValue to implements CAS?

**Comment by ArkadiuszMichalski** [comment]
I will check sync XHR + filtration by NodeJS in different scenarios, sth like this:

```json
{
	"entry1" : {
		"tab1": 10,
		"tab2": 20,
	"last_write": 20
	},
	"entry2" : {
		"tab1": xxx,
		"tab2": xxx ,
	"last_write": xxx
	}
}
```
In NodeJS we will remember that tab1 last time read "entry1" in 10. When now tab1 want write "entry1" then check state of "last_write" for "entry1", if it's bigger so probably other tabs change data - stop writing for that tabs and run callback defined by user for tab1, if not bigger then write to database (here in variable) and update "last_write". Of course we need to consider other border cases, like tab1 wants 3x write data, etc., but I will catch them in practice.
