### ISSUE TITLE
Small bug: Scrript that don't install.

### ISSUE THREAD

**Issue by mikhoul** [greasemonkey/greasemonkey#2433]
I don't know why this script don't want to install: http://userscripts-mirror.org/scripts/show/48536

It tried with the button on the page and directly by drag n drop and both time the install button stay ghosted after the timeout. :crying_cat_face: 

I'm using GM 3.9 under Win 7  :octocat:

**Comment by janekptacijarabaci** [comment]
It's not a bug in GM:

![a](https://cloud.githubusercontent.com/assets/2373486/18876843/774c827c-84cb-11e6-940f-ba045960f73d.png)

http://userscripts.org/scripts/source/51513.user.js
=>
http://userscripts-mirror.org/scripts/source/51513.user.js

**Comment by mikhoul** [comment]
Sorry I did not look in the source code.

Have a great day !  :smile:
