### ISSUE TITLE
Auto repair when lost internet connection or other network error

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [greasemonkey/greasemonkey#2436]
Can you add some simple mechanism to handle lost internet connection or other network error? Actually we can't do anything because scrit not run in `about:neterror`. I understand you cut off this because chrome privilege but in practice we only need refresh page. Step to reproduce:
1. Open some page, like google.com
2. Turn off internet connection.
In address bar we still see https://www.google.com but script not work and we can't do anything via Greasemonkey (but still see all runnning script when press down arrow near monkey icon). 

Maybe add some metadat config option, like `@refreshNetError someMiliseconds`, and when network error occur, adress from adress bar match to include/exclude GM rules then refresh tab after `someMiliseconds`. When our internet will work again then this refresh repair everything because we land on correct page and GM can work again. This is just an example, surely it can be done on xxx ways (like define `GM_netError` function).

Of course we can fix this with using other addons, but it is another unnecessary dependency.

See also this: https://github.com/greasemonkey/greasemonkey/issues/1375#issuecomment-60531762

**Comment by arantius** [comment]
No, this is well outside our intended scope.

**Comment by langren1353** [comment]
Have we reconsidered adding this feature?

This function does not have to given userscript to have this execution permission. It can be set to a built-in switch and turned off by default. Then the user can choose to turn on this function manually.

**Comment by Cerberus-tm** [comment]
Doesn't it make more sense to use an existing extension that can refresh the page under certain conditions? Because this issue does not affect only Greasemonkey, nor Greasemonkey specifically.

**Comment by langren1353** [comment]
> Doesn't it make more sense to use an existing extension that can refresh the page under certain conditions? Because this issue does not affect only Greasemonkey, nor Greasemonkey specifically.

Thank you for reply，I just create an extension for this at https://chromewebstore.google.com/detail/errorreloader/ofgjmebbmpcafcakjjohohbkpaelicfm

**Comment by Cerberus-tm** [comment]
> > Doesn't it make more sense to use an existing extension that can refresh the page under certain conditions? Because this issue does not affect only Greasemonkey, nor Greasemonkey specifically.
> 
> Thank you for reply，I just create an extension for this at https://chromewebstore.google.com/detail/errorreloader/ofgjmebbmpcafcakjjohohbkpaelicfm

Oh, that's very cool! I tried to find such an extension for Firefox, but none seem to have this exact scenario in their description. I have no idea about this, but would it be a lot of work to port it into a Firefox version?

P.S. I am curious: you use both Firefox (Greasemonkey) and Chrome (your refresh extension) at the same time?

**Comment by langren1353** [comment]
> > > 使用现有的可以在特定条件下刷新页面的扩展不是更有意义吗？因为这个问题不仅影响 Greasemonkey，也不专门影响 Greasemonkey。
> > 
> > 
> > [感谢您的回复，我刚刚在https://chromewebstore.google.com/detail/errorreloader/ofgjmebbmpcafcakjjohohbkpaelicfm](https://chromewebstore.google.com/detail/errorreloader/ofgjmebbmpcafcakjjohohbkpaelicfm)为此创建了一个扩展程序[](https://chromewebstore.google.com/detail/errorreloader/ofgjmebbmpcafcakjjohohbkpaelicfm)
> 
> 哦，太酷了！我尝试寻找 Firefox 的此类扩展，但似乎没有一个在描述中提到这种确切的场景。我对此一无所知，但将其移植到 Firefox 版本会很费力吗？
> 
> PS 我很好奇：您同时使用 Firefox（Greasemonkey）和 Chrome（您的刷新扩展）吗？

With AI，everything is possible.
You can directly download the CRX file, and the JavaScript code is not encrypted. If you encounter any issues, feel free to reach out to me.

**Comment by Cerberus-tm** [comment]
@langren1353 
> With AI，everything is possible. You can directly download the CRX file, and the JavaScript code is not encrypted. If you encounter any issues, feel free to reach out to me.

OK I may look into that sometime. I'm still curious how come you use different extensions for Firefox and Chrome.
