### ISSUE TITLE
Problem with Angular and some functions

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [greasemonkey/greasemonkey#2437]
Hi, I try reparsing some angular template using GM and angular inside the page but it's not work. Per documentation (https://docs.angularjs.org/api/ng/function/angular.injector) belove code should work:

``` js
unsafeWindow.angular.element(document).injector().invoke(function($rootScope,$compile) {
  $compile(template)($rootScope);
});
```

In Firefox with GM this not work because get `Error: Permission denied to access property "$inject"`, so I try using `cloneInto`:

``` js
unsafeWindow.angular.element(document).injector().invoke(cloneInto(function($rootScope,$compile) {
  $compile(template)($rootScope);
}, unsafeWindow, {"cloneFunctions": true}));
```

and get `TypeError: $compile is not a function`, we don't have reference to `$compile` and `$rootScope`. Both code (with or without `cloneInto`) works in Chrome and Tampermonkey. Im not sure if its GM bug or Firefox bug (maybe worth to report). Any advice how solw this in Firefox?

Some other infos:
http://stackoverflow.com/questions/22370390/how-can-we-use-compile-outside-a-directive-in-angularjs
http://stackoverflow.com/questions/28714055/angularjs-injector

**Comment by the8472** [comment]
if you use `@grant none` then you should have transparent access to the page scope and can use the untrusted libraries without going through the unsafeWindow security membrane.

**Comment by ArkadiuszMichalski** [comment]
Unfortunately I use `@grant` for some GM APIs but solve this by using `get()` method directly on injector:
https://docs.angularjs.org/api/auto/service/$injector#get
