### ISSUE TITLE
Add a button to selectd userscript to quick add current site to @include or @exclude

### ISSUE THREAD

**Issue by eromoe** [greasemonkey/greasemonkey#2438]
There are many userscripts that work on every site, such as  `anti adblock`, `bypass captcha` , `replace pic` and so on. Such userscripts would cause some problem on some sites, or one don't want them run on some very privacy page. 

It would be much more convenient to add a button than go to `about:addons` and edit the config.

**Comment by mikhoul** [comment]
I agree with you on this missing feature,  A sub-menu to add AND Remove quickly Userscript "on the fly" without going in the addon manager would be VERY useful with "Global" Script". 

What is your take @arantius  and @janekptacijarabaci  about this feature ?  :octocat: 

**Quick mock-up:** 
![Alt Text](http://i.imgur.com/b9WAK9X.png)


Best Regards 😺
