### ISSUE TITLE
Greasemonkey persistence not working on FF 49 Linux

### ISSUE THREAD

**Issue by ERnsTL** [greasemonkey/greasemonkey#2439]
Greetings, GM (using 3.9) is currently broken for me with FF49, on Ubuntu Linux.

See this testing code in a user script:

```
alert("GM_info.isPrivate = " + GM_info.version);
var valueGMs = (typeof GM_setValue === "function");
var valueGMg = (typeof GM_getValue === "function");
alert("GM_getValue is function: " + valueGMg + valueGMs + (typeof GM_getValue));
//FIXME ^ why is GM_*Value false false undefined?
alert("Type of GM_listValues: " + (typeof GM_listValues));
```

If I for example copy-paste above code into an empty userscript for this very page here, then it runs, but only the GM_info object returns correct numbers (version 3.9), the other functions like ```GM_listValues```, ```GM_getValue```, ```GM_setValue``` are all ```undefined```.

**Comment by janekptacijarabaci** [comment]
Not confirmed on Ubuntu 16.04, FF 49.0, GM 3.9

Are you using this setting?
https://wiki.greasespot.net/@grant

**Comment by ERnsTL** [comment]
Aha! Changing from
```
// @grant       none
```
to
```
// @grant       GM_getValue
// @grant       GM_setValue
```
made the script work. That made all the difference!

I was unaware that these methods need to be explicitly imported.

Thanks for pointing it out. No bug then :-)
