### ISSUE TITLE
Preference for disabling userscript updates in Private Browsing Mode

### ISSUE THREAD

**Issue by mkotelba** [greasemonkey/greasemonkey#2443]
Checking for the availability of userscript and or associated resource update(s) and actually downloading updated files during PBM both leak data that can potentially be used to "fingerprint" a given user/machine/browser/connection, even if:
- The underlying TCP/IP connection is 100% secure/anonymous.
- All updateUrls + remote resource URLs are secure (mandatory HTTPS usage via the "Require secure updates" Greasemonkey option) and trusted by the user.

I am requesting that a new boolean preference be added for disabling userscript + associated resource update checks _and_ actual updates.

This should probably be a global preference in Greasemonkey Options, but could also be overrideable on a per-userscript basis, if its useful.
---

As a workaround, I've been using this snippet at the top of my personal/private userscripts, though I am unsure of its effectiveness (is the GM_info object live?):

``` javascript
var info = GM_info;

if (info.isPrivate) {
        info.scriptWillUpdate = false;
}
```
---

_See also_: [Private Browsing #1235](http://github.com/greasemonkey/greasemonkey/issues/1235)

**Comment by the8472** [comment]
> resource update(s) and actually downloading updated files

Conceptually this is a browser-global action happening with elevated privileges and the default cookie store. Private browsing windows are window-scoped behavior with a separate cookie store.

So it doesn't really make sense to tie userscript update checks to private browsing mode.

Additionally, GM_XMLHTTPRequests already takes the private browsing nature into account.

And the script itself can make the decision based on GM_info.isPrivate as you already noticed.

**Comment by arantius** [comment]
I agree that this doesn't really make sense.  Do extensions ever stop auto-updating (when enabled), because private browsing is or is not in use?
