### ISSUE TITLE
Scripts with same or similar name

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2447]
I have two scripts that have the same name just different casing. It is difficult to tell them apart and it would have been worse if they had the same casing. Include the author's name or namespace if the former isn't present. Specifically in the drop down menu.

**Comment by the8472** [comment]
rename them?

**Comment by TimidScript** [comment]
Not my scripts. If I rename. I would have to do manual updates, and rename it after each manual update.
