### ISSUE TITLE
How could the variable created inside function() inside GM_xmlhttpRequest be passed to outside?

### ISSUE THREAD

**Issue by pendave** [greasemonkey/greasemonkey#2448]
Help me please.

How could the variable created inside function() inside GM_xmlhttpRequest be passed to outside?

> if(myElement.nextSibling.nextSibling.nextSibling.getAttribute("style")=="color:#1bdcbe"){
        href = "https://xxxxxxxxxx.com/search?term="+info;
        var ret = GM_xmlhttpRequest({
            method: "GET",
            url: href,
            onload: function(res) {
                //alert(res.responseText);
                alert(eval('('+res.responseText+')').results[0].trackViewUrl);
                trackUrl = eval('('+ res.responseText +')').results[0].trackViewUrl;
            }
        });
        html =  myElement.nextSibling.nextSibling.nextSibling.innerHTML + "&nbsp;&nbsp;&nbsp;&nbsp;<a href='" + trackUrl + "' target='_blank' class='btn'><span>Here</span></a>";
        myElement.nextSibling.nextSibling.nextSibling.innerHTML = html;
    }

![t5u 3_x j ff pnw 5l8g_r](https://cloud.githubusercontent.com/assets/1331881/20035259/374dba6c-a418-11e6-90d3-aab9ba06b551.png)

Even I var that variable outside, no result...

![t5u 3_x j ff pnw 5l8g_r](https://cloud.githubusercontent.com/assets/1331881/20035269/74237f08-a418-11e6-97ec-8e8605234cea.png)

**Comment by pendave** [comment]
![d ufn1y8sh o6twk r q 0](https://cloud.githubusercontent.com/assets/1331881/20035331/7a0c3962-a41a-11e6-966f-32fd1e4fb3a9.png)

**Comment by pendave** [comment]
Or the contrary to pass the variable i in for() into the inner function()?

![9_z 3ulfc0qx w5ex zbig4](https://cloud.githubusercontent.com/assets/1331881/20035728/ba1b40ce-a42a-11e6-86d5-c91e15f8fd40.png)

If don't use this way:
![0m z 80kso fuzk4v zmj5l](https://cloud.githubusercontent.com/assets/1331881/20035731/d6166c36-a42a-11e6-85cb-4f11efdf54c2.png)

**Comment by pendave** [comment]
How could I use JavaScript Closures?

**Comment by pendave** [comment]
I do it referring to 


http://userscripts-mirror.org/topics/51161

http://userscripts-mirror.org/topics/193

But I can't understand this:


Function.prototype.bind = function( thisObject ) {
  var method = this;
  var oldargs = [].slice.call( arguments, 1 );
  return function () {
    var newargs = [].slice.call( arguments );
    return method.apply( thisObject, oldargs.concat( newargs ));
  };
}

My solution:

![uma c8 xuo4bqonze ui](https://cloud.githubusercontent.com/assets/1331881/20452892/e577132c-ae4f-11e6-910d-d74b16d2a0e6.png)

**Comment by marsjaninzmarsa** [comment]
Please format code with ``` and no `>`.
You can always use global variables (`window.something`) or pass reference to object.
