### ISSUE TITLE
[Question] How copy or move Greasemonkey scripts from Pale Moon to Firefox?

### ISSUE THREAD

**Issue by Kristinita** [greasemonkey/greasemonkey#2451]
### Briefly

I can not find, how I can copy or move my Greasemonkey scripts from Pale Moon — Firefox-based browser — to Firefox.

### Detail

Before I use [**Pale Moon**](https://www.palemoon.org/) browser, now I migrate to Firefox. I use more than 20 Greasemonkey scripts in Pale Moon, scripts folder is `J:\Pale Moon\User\Palemoon\Profiles\Default\nh451pl4.default\gm_scripts`. My Firefox scripts folder is `E:\Firefox\Data\profile\gm_scripts`. I not understand, how I can move or copy my Pale Moon scripts to Firefox.

### Did not help

I try copy content of folder `J:\Pale Moon\User\Palemoon\Profiles\Default\nh451pl4.default\gm_scripts` to `E:\Firefox\Data\profile\gm_scripts`, but I can not see copied scripts in `about:addons` → User Script of Firefox.

Thanks.

**Comment by janekptacijarabaci** [comment]
It works for me. Did you copy the entire folder (i.e. `config.xml`, e.g.)?

**Comment by Kristinita** [comment]
I'm sorry, I incorrect merge code from old `config.xml` to new `config.xml`. Now Pale Moon scripts worked for me. Thank you very much!
