### ISSUE TITLE
How could GM_xmlhttpRequest fetch the 'Location' in the Response Headers?

### ISSUE THREAD

**Issue by pendave** [greasemonkey/greasemonkey#2452]
How could GM_xmlhttpRequest fetch the 'Location' in the Response Headers?

It displays status:200 when I use GM_xmlhttpRequest, but actually it needs to be 302.

![vrlq zv jqwuskkhgym 1ji](https://cloud.githubusercontent.com/assets/1331881/20571909/3e0246b4-b1e4-11e6-952a-139bd0ad4da7.png)

Anyone help?

**Comment by pendave** [comment]
Hello super @janekptacijarabaci please help me :)

**Comment by janekptacijarabaci** [comment]
See https://wiki.greasespot.net/GM_xmlhttpRequest - `finalUrl`

**Comment by pendave** [comment]
No result for getting Location

**Comment by janekptacijarabaci** [comment]
In that case, I need a concrete example.

**Comment by franklinyu** [comment]
I think *questions* like this, instead of *problems*, should be asked in [user forum](https://groups.google.com/forum/#!forum/greasemonkey-users) instead.
