### ISSUE TITLE
How to call ajax in greasemonkey ? 

### ISSUE THREAD

**Issue by pikachu1590** [greasemonkey/greasemonkey#2457]
HI,

I want to know, how to pass Http request through GreaseMoneky. I have tried several ways, it's not working. Also getting an issue like

"localhost uses an invalid security certificate.
The certificate is not trusted because it is self-signed.
Error code: SEC_ERROR_UNKNOWN_ISSUER
";

please advise.

**Comment by janekptacijarabaci** [comment]
See http://stackoverflow.com/questions/25723415/bypassing-ssl-certificate-error-in-jquery-and-ajax
