### ISSUE TITLE
wiki.greasespot.net - SSL cipher out of date

### ISSUE THREAD

**Issue by MNGrrrl** [greasemonkey/greasemonkey#2458]
wiki.greasespot.net uses an unsupported protocol for Chrome (version =  53 or greater )
Error is ERR_SSL_OBSOLETE_CIPHER -- this indicates the problem is the cipher DHE, which was obsoleted in v53.

**Comment by arantius** [comment]
I was working on a server upgrade (which took a long time ...) when this was reported.  It's now complete.

Today I have no issues opening it in Chrome 55, and [SSL labs](https://www.ssllabs.com/ssltest/analyze.html?d=wiki.greasespot.net&latest) gives me an A.
