### ISSUE TITLE
responseHeaders not available until readyState 4 (expected 2)

### ISSUE THREAD

**Issue by Rob--W** [greasemonkey/greasemonkey#2460]
In XMLHttpRequest, there are multiple readyStates of interest: 2 (response headers received)and 4 (load finished).

I created a script that checks responseHeaders at readyState 2, and if it indicates support for range requests, I abort the request and restart the request with a much smaller range.
In theory, this works. However, it does not work in GreaseMonkey because it only sets the headers when the request has fully finished:
https://github.com/greasemonkey/greasemonkey/blob/3f462ac1305712ce65b3e2b19c9c8c31f377cc8e/modules/xmlhttprequester.js#L253-L254
git blame shows that this logic was already in place in the initial commit of the repo, so I did not discover why the implementation is like this.

This, and the fact that HTTP cookies are not included in the request is the reason why I switched to a full WebExtension for the script. It would still be good to fix the issue in GM though.

**Comment by janekptacijarabaci** [comment]
> git blame shows that this logic was already in place in the initial commit of the repo, so I did not discover why the implementation is like this.

AFAIK not:
https://addons.mozilla.org/cs/firefox/files/browse/3733/file/chrome/greasemonkey/content/xmlhttprequester.js#L123

But if there isn't a serious reason for not:
#2461

> the fact that HTTP cookies are not included in the request

See also #2236 
But AFAIK, you can use:
```
"headers": {
    "cookie": document.cookie
},
```

**Comment by Rob--W** [comment]
"AFAIK not" = "there is no reason for the limitation"?

That cookie suggestion does not work for http-only cookies, and neither for redirects.

**Comment by janekptacijarabaci** [comment]
I edited it, I'm sorry.

> There is no reason for the limitation?

I think it's for no reason. AFAIK.
