### ISSUE TITLE
[GM3.9] Scratchpad not working correctly

### ISSUE THREAD

**Issue by PenelopeFudd** [greasemonkey/greasemonkey#2463]
I've been trying to get a new script to work using GM_xmlhttpRequest, but I've been getting the following error:
`Exception: ReferenceError: GM_xmlhttpRequest is not defined`

I found out what's going wrong: the "Reload and Run" function doesn't bring in the GM_xmlhttpRequest function.  I haven't tested further to see if any GM_* functions were loaded.  To make my script work, I have to save it and reload the web page manually with Ctrl-R.

Also, the right-click menu says that Ctrl-Shift-R will reload and run the script, but apparently it instead opens the 'Replace all' box at the top of the window.

The right-click menu also has an 'evaluate function' option; I'm not sure if it's working.  If I type alert("hello world"), right click on it and select evaluate function, should an alert box pop up somewhere?

Finally, from looking at the Mozilla documentation, the editor can be configured with a 'Run' button between 'Save As...' and 'Pretty Print', but at this point I don't know if running the script that way will find GM_xmlhttpRequest either.

Apart from that, great work, thanks!

**Comment by janekptacijarabaci** [comment]
> I've been trying to get a new script to work using GM_xmlhttpRequest, but I've been getting the following error:
Exception: ReferenceError: GM_xmlhttpRequest is not defined 

Since it is an internal function (Greasemonkey) so does not affect Scratchpad.

> I found out what's going wrong: the "Reload and Run" function doesn't bring in the GM_xmlhttpRequest function. I haven't tested further to see if any GM_* functions were loaded. To make my script work, I have to save it and reload the web page manually with Ctrl-R.

> Also, the right-click menu says that Ctrl-Shift-R will reload and run the script, but apparently it instead opens the 'Replace all' box at the top of the window.

> The right-click menu also has an 'evaluate function' option; I'm not sure if it's working. If I type alert("hello world"), right click on it and select evaluate function, should an alert box pop up somewhere?

>Finally, from looking at the Mozilla documentation, the editor can be configured with a 'Run' button between 'Save As...' and 'Pretty Print', but at this point I don't know if running the script that way will find GM_xmlhttpRequest either.

See #2419 and [bug 995756](https://bugzilla.mozilla.org/show_bug.cgi?id=995756)

**Comment by PenelopeFudd** [comment]
One more thing:  I have the following script:
console.log("Version 1")
If I save it (Ctrl-S), then reload the page (Ctrl-R in browser), the console shows 'Version 1'.

If I then change the version string to "Version 2", clear the console, and then use the right-click menu to reload-and-run, the console says:
Version 1
Version 2

If I then change the version string to "Version 3", the console says:
Version 1
Version 3

And finally, if I hit 'Ctrl-S' and right-click reload-and-run:
Version 3
Version 3

In short, when you save your script and click 'reload and run', the script runs twice: once as a greasemonkey plugin, and once as a scratchpad program.

It's still beneficial to click 'reload-and-run', because of the syntax checking and the commented error messages inserted at the end of the file.  As soon I've fixed enough errors so that the current error is 'Exception: ReferenceError: GM_xmlhttpRequest is not defined' (or some other GM_* function), then I hit Ctrl-S and Ctrl-R in the browser to actually test my code.

**Comment by arantius** [comment]
> use the right-click menu to reload-and-run

Aha, this is why.  We know this doesn't work so we remove it .. from the main menu.  Didn't know it's also in the context menu.  You shouldn't use this feature and we should make it impossible to do so.
