### ISSUE TITLE
Feature request: Allow automatic updates from http-URLs

### ISSUE THREAD

**Issue by ckmod** [greasemonkey/greasemonkey#2464]
Dear guys,

I have written a script that is deployed on a local wiki that is reachable only via http. For me, there is no way to make them offer https also (big company). Automatic updates are not executed.

I need the ability to have the automatic update work also with http-URLs. Maybe you could provide a configuration option to enable this.

Best regards
Claus

My Environment
Windows 7
Firefox 45.4.0
Greasemonkey 3.9

**Comment by janekptacijarabaci** [comment]
Did you try the following settings?
![1](https://cloud.githubusercontent.com/assets/2373486/21344020/fd4eda86-c699-11e6-851f-268bf46049ce.png)

**Comment by ckmod** [comment]
Hi,

I overlooked this  :blush:. Currently I am trying if deactiving this helps me. I will let you know.

I would suggest another German translation. 
Current: "Sicherheitsupdate erforderlich."
Suggestion: "Erlaube Updates über nicht verschlüsselte Verbindungen (http)."

Cheers
Claus

**Comment by arantius** [comment]
Translations are open to contributions:
http://beta.babelzilla.org/projects/p/greasemonkey/
