### ISSUE TITLE
Possible to change firefox about:config variables through GM?

### ISSUE THREAD

**Issue by ganego** [greasemonkey/greasemonkey#2465]
Since GM does not offer GM_download, I have to use https://gist.github.com/ccloli/832a8350b822f3ff5094 (GM_download_polyfill.js) or https://github.com/eligrey/FileSaver.js/ . Now the problem with that is, that Firefox will show a "save as" prompt because in the FF options it is set that FF should ask for each download (what I normally want).

Tampermonkey offers the nice feature that this "save as" prompt will not be shown and the file directly saved without any questions asked - exactly what I want for my user script.

Since I could not find out how TM does this, I had the idea to set the FF about:config variable "browser.download.useDownloadDir" (this tells FF to download to the folder and don't ask) to true, initiate the download and set it to false again.

Is that possible?

**Comment by an-electric-sheep** [comment]
That would be very unsafe, especially if it's just for the purpose of downloading a file. There are many dangerous options in about:config.

**Comment by ganego** [comment]
Well I agree, just adding GM_download() like tampermonkey would be nice and the easy way to solve the problem.

**Comment by arantius** [comment]
#1877 exists

Arbitrary preference changing will not be added to Greasemonkey.

**Comment by CennoxX** [comment]
>Since I could not find out how TM does this, I had the idea to set the FF about:config variable "browser.download.useDownloadDir" (this tells FF to download to the folder and don't ask) to true, initiate the download and set it to false again.
>
>Is that possible?

@ganego: No, it is not possible. The about:config variables of Firefox can indeed be changed in a file ([Prefs.js file](http://kb.mozillazine.org/Prefs.js_file)), but those changes are only applied if Firefox isn't running. Otherwise the changes are ignored and resetted after a restart of Firefox.
