### ISSUE TITLE
Convert to WebExtension?

### ISSUE THREAD

**Issue by theres-waldo** [greasemonkey/greasemonkey#2466]
Mozilla recently [announced](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/) that starting in Firefox 57, Firefox will no longer support addons that are not WebExtensions.

Is it possible to convert Greasemonkey to be a WebExtension, so it can continue working in Firefox 57 and beyond?

**Comment by janekptacijarabaci** [comment]
See also #2275

**Comment by arantius** [comment]
As mentioned in #2275 but worth repeating:

1. I expect this to be a _huge_ amount of work
2. "By the end of 2017, and with the release of Firefox 57 ..." so we've got a year.
3. If e10s is any guide, we'll have way more than a year.

This is important, yes.  But resolving in favor of #2275 which already covers this.
