### ISSUE TITLE
Possibly causing crash in conjunction with NoScript

### ISSUE THREAD

**Issue by rugk** [greasemonkey/greasemonkey#2467]
The full report is available here: https://bugzilla.mozilla.org/show_bug.cgi?id=1320571

It's not yet sure that Greasemonkey is really (the/a) cause here, but to be sure, it would be nice you could investigate it. I am willing to share a profile where I can reproduce it with any Greasemonkey dev.

**Comment by janekptacijarabaci** [comment]
Ad https://bugzilla.mozilla.org/show_bug.cgi?id=1320571#c18
> Actually even some Greasemonkey scripts are needed, *but* all of them are disabled. (when deleting the disabled scripts however, it does not work).

AFAIK: Could be related to "pseudo-disable the script" issue:
https://github.com/greasemonkey/greasemonkey/issues/2416 (https://github.com/greasemonkey/greasemonkey/issues/2417)
