### ISSUE TITLE
Only update scripts when newer version is a valid script

### ISSUE THREAD

**Issue by tiansh** [greasemonkey/greasemonkey#2468]
I hope greasemonkey could refuse updating a script if the newer version cannot pass syntax checking.
(Here, syntax checking means something like `try { new Function(script_code); } catch (e) { /* not pass */ }`)

The story (why):
One of my user complain to me that my script stop working after recent updating. After I helped the user debug the issue, we found that the newer version he installed is not downloaded completely, which meanse there is only half of codes and even not a valid script. I'm just hosting my script on GitHub pages, and I'm not sure why this happened. But I hope greasemonkey may refuse update script if the script cannot pass syntax checking.
the user is using fx 50.1 with gm 3.9

**Comment by franklinyu** [comment]
I think providing an example may help, such as [this scrupt](https://github.com/tiansh/yawf/blob/master/Yet_Another_Weibo_Filter.user.js) (609 kB).
