### ISSUE TITLE
Installation prompt appears on primary monitor only

### ISSUE THREAD

**Issue by Keith94** [greasemonkey/greasemonkey#2469]
## Steps to reproduce

1. Install Greasemonkey 3.9 and restart Firefox
2. Move the browser window to a non-primary monitor (I have only two)
3. Visit https://www.4chan-x.net/ and click the `.user.js` install link

## Expected result
Install prompt appears on the same monitor as Firefox

## Actual result
Install prompt always appears on the primary monitor

**Comment by janekptacijarabaci** [comment]
Some options are (e.g.) on:
http://stackoverflow.com/questions/57652/how-do-i-get-javascript-to-open-a-popup-window-on-the-current-monitor
