### ISSUE TITLE
Error opening input stream (invalid filename?)

### ISSUE THREAD

**Issue by excel23** [greasemonkey/greasemonkey#2471]
My userscripts stopped working in FF. When i press Ctrl+Shift+J i get this list of errors:

TypeError: el is null  in emptyEl.js:4:10
and
Error opening input stream (invalid filename?): moz-extension://09fbe67a-7cc6-495c-9d27-16b1c9d1f18c/data/content.js  ExtensionContent.jsm:226

My srcipts are correct and should work but they don't. I have two scripts installed and they stopped to work together. 
I tried to uninstall scripts, greasemonkey, clear firefox cash, opening independent profile without greasemonkey ever installed with "Firefox.exe -p" command but i still can't manage why it's not working, I'm pretty sure the key is in this errors.

**Comment by janekptacijarabaci** [comment]
What is your operating system (the version, the version of Greasemonkey)?

See also #2296

**Comment by excel23** [comment]
Oops forget to mention!
I have Windows 7 x64 with all updates installed. FF 51.0.1(x32)
Don't know about the strange names, but it's worked like a charm just few days ago

Found 2 more errors in Ctrl+Shift+J:
```
"Handler function threw an exception: TypeError: this.transport is null
Stack: send@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1470:5
NEA_addSecurityInfo@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/webconsole.js:2191:5
NetworkResponseListener.prototype._getSecurityInfo<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:488:5
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
NetworkResponseListener.prototype.onStartRequest@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:429:5
Line: 1470, column: 5"
```
```
Async statement execution returned with '19', 'NOT NULL constraint failed: expiration_notify.guid'  nsPlacesExpiration.js:714

PEX_handleError resource://gre/components/nsPlacesExpiration.js:714:5
```

**Comment by janekptacijarabaci** [comment]
Unfortunately, I don't know what it is:
`moz-extension://09fbe67a-7cc6-495c-9d27-16b1c9d1f18c/data/content.js`

**Comment by arantius** [comment]
None of the errors posted yet besides the first (`TypeError: el is null in emptyEl.js:4:10`) seem to have anything to do with Greasemonkey, and that one should be unrelated to whether scripts run or not (if anything is broken, it would just be the UI/display).  Most of the rest clearly point at something else.  Please read and follow:

https://wiki.greasespot.net/Troubleshooting_(Users)

**Comment by excel23** [comment]
I thought that resource://gre/ is greasemonkey errors.
Thanks for attention, guys. It's so strange, but i do nothing and today all errors gone, and greasemonkey works again

**Comment by janekptacijarabaci** [comment]
@arantius 
`TypeError: el is null in emptyEl.js:4:10`
It is a known error. It usually means a syntax error (somewhere in the main code of GM).
Or e.g.: #2246 

@excel23 
I would check the PC for malware, etc.

**Comment by excel23** [comment]
@janekptacijarabaci 
I'm sure that pc don't have malware cause i have AV and I'm usually check it with autoruns from sysinternals suite

**Comment by excel23** [comment]
@janekptacijarabaci 
as about strange path i found this in about:config:
{"jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack":"09fbe67a-7cc6-495c-9d27-16b1c9d1f18c"}

**Comment by janekptacijarabaci** [comment]
OK, this is https://addons.mozilla.org/en-US/firefox/addon/google-search-link-fix/

But... It's better to try in new/clean profile.

And if it works, it can be closed.
