### ISSUE TITLE
Writing to unsafeWindow cannot be accessed by content page

### ISSUE THREAD

**Issue by X01X012013** [greasemonkey/greasemonkey#2472]
It seems that functions written to unsafeWindow cannot be accessed by the content page in Firefox. 
![image](https://cloud.githubusercontent.com/assets/7283682/22404660/dee3aec8-e5f2-11e6-8606-bc3031798a26.png)
After further research, it looks like Firefox changed the way plug-ins interacts with the content page: 
https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/

The script in question is https://github.com/X01X012013/AdBlockProtector and it works perfectly in Tampermonkey in Firefox.

**Comment by arantius** [comment]
See section "The Real Fix" in the mozilla page you linked, and http://www.greasespot.net/2014/06/greasemonkey-20-release.html .

**Comment by X01X012013** [comment]
It looks like your [Wiki](https://wiki.greasespot.net/UnsafeWindow) is outdated. Could you update that? 

The new APIs are only for FireFox, this change breaks compatibility. Why can't you patch the plug-in instead? Like what Tampermonkey did? 
Currently I made a dropper to escape the sandbox.
