### ISSUE TITLE
Pale Moon 27.0.3 cannot edit scripts

### ISSUE THREAD

**Issue by zootboy** [greasemonkey/greasemonkey#2478]
Running Pale Moon 27.0.3 on Linux, Greasemonkey 3.9. I get the following error when I try to edit a script:

Error: TypeError: GM_util.openInEditor is not a function
Source File: chrome://greasemonkey/content/addons4-overlay.js
Line: 165

Trying the same action in Firefox 51 on the same machine successfully opens the editor window.

**Comment by janekptacijarabaci** [comment]
Dupe of #2456
