### ISSUE TITLE
The Update Made Scripts Disappear

### ISSUE THREAD

**Issue by GuardianMajor** [greasemonkey/greasemonkey#2481]
Since the update, there are several of my scripts that no longer show up under the manager and by virtue of that will not run. There is zero explanation as to why these scripts disappeared.

I checked the local profile and under `gm_scripts` the scripts that are no longer appearing show up and they are valid and can be opened and even dropped into other installations just fine. But they will NOT show up on the existing profile and removing them and trying to add them back gets the error warning to the tune of "can't parse script" which makes absolutely no sense, or it wouldn't work on other installations.

So what is going on here? I need these scripts back and functional and I don't feel like starting all over with a clean profile since this profile is less than a month old. How in the world does an update to fix bugs break existing functionality?

Forgot to add: This particular install is on Firefox 51.0.1 (32-bit) and the scripts work just fine with 3.10 and these scripts on Firefox Developer Edition (latest nightly)(64-bit) and other 51.x/32 profiles (both old and new).

**Comment by arantius** [comment]
Which scripts?

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2480#issuecomment-279223506

**Comment by GuardianMajor** [comment]
@arantius how is that relevant? the scripts installed on the profile. I mean is this a trick question?

**Comment by GuardianMajor** [comment]
@janekptacijarabaci thank you, this might actually be what's happening but if I understood correctly that only happened on the nightlies? right? surprisingly, my aurora nightly is just fine with the SAME exact scripts on all the profiles. Let's see how they resolve it and it might make this issue moot. Thanks again for the heads up.

**Comment by arantius** [comment]
Come back when you can communicate respectfully.

**Comment by GuardianMajor** [comment]
@arantius excuse me, I am not sure what you mean by respectfully, but I have said and done nothing disrespectful, perhaps you need to read without ego and judgement. You ask the most improperly deficient question of "which scripts" and you expect what I replied is rude? You serious? Grow up.
