### ISSUE TITLE
WebExt: Execute scripts at all three runAt times

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2483]
Come up with a working plan for how to execute user scripts, of course not known until run time.  Compatible with all three runAt times -- critically `document_start`.

See https://github.com/arantius/greasemonkey/tree/8a255bde1aa6312715740fd0157d582a2d6cb183 for my research so far, where the approach is:
* Use one background script.  (It will have access to storage/whatever APIs, where the scripts are stored, so can know the content of scripts to execute.)
* Observe something (**what?**) to trigger ..
* .. call `tabs.executeScript()` to fire off each user script.

This "works" except there's no event I've yet found to observe that works for all three run times.  There's `webNavigation`'s `onBeforeNavigate` which is in fact *too soon*, it (as the name implies) fires before the navigation, when the current document is still active.  But the next point is `onCommitted`, and at that point it's too late for start, inline scripts have already executed.

**Comment by arantius** [comment]
To research:

* Observe `webRequest` instead of `webNavigation`.  Does that give us a handle at start time?
* Inject one webext content script, at document_start, for every page.  Have it somehow know which scripts to execute, synchronously.  (Because anything async would push us past start time.)

**Comment by the8472** [comment]
Re: https://bugzilla.mozilla.org/show_bug.cgi?id=1332273#c8

> I'd like to be able to store (in background) a blob, later get (only) its URL and pass that URL (synchronously) to content script(s), but I know of no way to do any of those things.

I haven't worked out all the details myself, but i think the background page could store blobs in IndexedDB, then convert them to blob URIs via URL.createObjectURL() at startup time and pass them to the hypothetical synchronous configuration API and then *maybe* load them via <script src=""> APIs for `@grant none` scripts if CSPs blob origin policies don't interfere.

For other grant modes we'll need a new API equivalent to the subscript loader.

There's a lot of ifs in there, but that would be the optimal course I think.

**Comment by RoxKilly** [comment]
Isn't IndexedDB [disabled in Private browsing](https://bugzilla.mozilla.org/show_bug.cgi?id=781982) mode on Firefox?

**Comment by arantius** [comment]
I don't think that affects the background script(s)?

**Comment by ExE-Boss** [comment]
This is possible by using a content script that runs at `document_start` and looks something like this: (possibly won’t work for already loaded tabs, use jQuery for that)
```javascript
// execute `document_start` scripts here...

document.addEventListener("DOMContentLoaded", event => {
    // execute `document_end` scripts here...
});

window.addEventListener("load", event => {
    // execute `document_idle` scripts here...
});
```
or something like this: (might be more error prone)
```javascript
let run = [false, false, false];

document_start();

if (document.readyState === "complete") {
    document_idle();
} else if (document.readyState === "interactive") {
    document_end();
}

document.onreadystatechange = () => {
    switch (document.readyState) {
        case "loading":     break;
        case "interactive": document_end();
        case "complete":    document_idle();
    }
};

function document_start() {
    if (run[0]) return;
    run[0] = true;

    // execute `document_start` scripts here...
}

function document_end() {
    if (!run[0]) document_start();
    if (run[1])  return;
    run[1] = true;

    // execute `document_end` scripts here...
}

function document_idle() {
    if (!run[1]) document_end();
    if (run[2])  return;
    run[2] = true;

    // execute `document_idle` scripts here...
}
```

Another way is to use three separate content scripts, where each of them runs at a different time.
For this the `manifest.json` contains the following: (guaranteed to probably work (might have a race condition))
```json5
"content_scripts": [
    {
        "matches": ["<all_urls>"],
        "run_at": "document_start",
        "js": ["document_start_handler.js"]
    },
    {
        "matches": ["<all_urls>"],
        "run_at": "document_end",
        "js": ["document_end_handler.js"]
    },
    {
        "matches": ["<all_urls>"],
        "run_at": "document_idle",
        "js": ["document_idle_handler.js"]
    }
]
```

It is also possible to use jQuery, which might be the least error prone way, but this all needs extensive testing: (again, runs at `document_start` but needs to be bundled with jQuery)
```javascript
function document_start() {
    // execute `document_start` scripts here...
}

function document_end() {
    // execute `document_end` scripts here...
}

function document_idle() {
    // execute `document_idle` scripts here...
}

// Use jQuery to execute all the functions:
document_start();

// `$(document).ready(document_end)` is deprecated since 3.0
$(document_end);

// jQuery used to have a method for this: `$(window).load(document_idle)`
if (document.readyState === "complete") {
    document_idle();
} else {
    $(window).on("load", document_idle);
}
```

**Comment by arantius** [comment]
As written this issues is too broad.  I'm splitting this into separate issues to be tracked more easily:

#2525, #2526
