### ISSUE TITLE
Manipulate DOM inside an iframe

### ISSUE THREAD

**Issue by hoandang** [greasemonkey/greasemonkey#2487]
Hi, does greasemonkey script support manipulating the iframe content from this url (the review popup)?

http://search.google.com/local/writereview?placeid=ChIJj61dQgK6j4AR4GeTYWZsKWw

**Comment by arantius** [comment]
Of any document for any window the script is executing in.

(In the future, please post support questions to the forum https://groups.google.com/forum/#!forum/greasemonkey-users and not the bug list.)
