### ISSUE TITLE
Add Automated Testing

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2491]
I spent a bunch of time trying to add unit tests to my work-in-progress WebExt branch.

First I tried straight node + random libraries for a while.  Easy start, but only for well isolated helper libraries.  Something like the script detector or install dialog or script registry relies on tons of APIs that environment does not provide.  Got messy fast.

Then I looked into using https://github.com/acvetkov/sinon-chrome which provides great environments.  But I couldn't get a recent enough interpreter, so all kinds of ES2015 features didn't work.  (Apparently this exists in a beta of phantomjs.  Couldn't get that running on Ubuntu 14.04 LTS.

**Comment by arantius** [comment]
https://developers.google.com/web/updates/2017/04/headless-chrome  
Headless chrome is a thing now, which seems like it might be useful.

https://github.com/Standard8/example-webextension  
I'm also looking into this example, which has some sort of unit testing set up.

**Comment by Sxderp** [comment]
> Apparently this exists in a beta of phantomjs. Couldn't get that running on Ubuntu 14.04 LTS.

Couldn't get PhantomJS to work in general, or the beta?

**Comment by arantius** [comment]
The beta, it depends on glibc of a higher version than Ubuntu Trusty has available, despite offering a "trusty" deb.

**Comment by arantius** [comment]
I'm spending a lot of time on this and accomplishing very little.

At this point I've got npm, karma, mocha, sinon-chrome and some other stuff all mixed together.  It "should" work.  I can write and run basic unit tests.  I can't do *anything* that relies on chrome/webext APIs.  Which means I can't actually test the code of the project.

https://stackoverflow.com/questions/45308351/

**Comment by Sxderp** [comment]
Woow, I missed this. Are you still having problems?
I'll take a look at it tomorrow and see if I can get some basic tests running.

**Comment by arantius** [comment]
I've gotten some things to run with karma, but that just got me far enough to learn that sinon-chrome is not at all what I want.  I want it to faithfully emulate real extension API behavior.  It actually just provides stubs that you'd have to configure completely anyway, so its value is lost on me.

**Comment by arantius** [comment]
(Sigh, keep hitting the wrong button.)

**Comment by arantius** [comment]
I've got an early start going:

https://github.com/arantius/greasemonkey/tree/automated-tests

Time will tell how this progresses.  I'm keeping this in a personal branch until it's further along on purpose.

**Comment by arantius** [comment]
I've improved the above mentioned branch to the point I'm confident it's worth moving forward with, so I merged it to master.  I also marked this bug closed; this work is not done but adding tests for everything is just too big for one issue.  I expect test coverage will improve as time goes forward, separate of any particular issue.
