### ISSUE TITLE
Not work on Firefox 54.0a2 (2017-04-08)

### ISSUE THREAD

**Issue by bluelovers** [greasemonkey/greasemonkey#2493]
Not work on Firefox 54.0a2 (2017-04-08)

script list is empty

**Comment by SmartViking** [comment]
Same here (same version of firefox; although I just upd). When I try to create a new user script, it says "A script with that name is already installed. OK to overwrite?", even though there's no script with that name. The problem occurred with versions `54.0~a2~hg20170403r375673-0ubuntu1~umd2~xenial` and
`54.0~a2~hg20170407r375800-0ubuntu1~umd1~xenial`

**Comment by janekptacijarabaci** [comment]
Did you check the Browser Console for errors? If you see any error you can screenshot.

**Comment by SmartViking** [comment]
![greasemonkey](https://cloud.githubusercontent.com/assets/593262/24836691/8fd3dbac-1d22-11e7-9446-8c65e2c8d972.png)

This error happens when I try to interact with GreaseMonkey.

**Comment by arantius** [comment]
#2488

**Comment by arantius** [comment]
I've just pushed version 3.11beta1: https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta?page=1#version-3.11beta1

It would be very useful if you could install it and confirm that it fixes this issue.

**Comment by SmartViking** [comment]
I clicked "Add to Firefox" on the latest version and restarted, and the problem does not occur. I patched my local version previously, although I suppose that has been replaced when I updated to version 3.11beta1
