### ISSUE TITLE
Unable to load scripts or add new ones

### ISSUE THREAD

**Issue by whatUwant** [greasemonkey/greasemonkey#2496]
Firefox 54b1 on macOS 10.12.5 Beta

- After the recent update of Firefox 54b1, all my scripts stopped appearing in Greasemonkey, and stopped working as well. 
Everything was fine in Firefox 53b10.
- If I try to create a new script from clipboard, only `config.xml` is updated. The script file itself is not saved in the `gm_scripts` folder.
- If I try to install a script hosted on the internet, the download progress bar does not move at all and the "Install" button is grayed out.

This problem is not reproducible in a new Firefox profile. Therefore I suspect it's caused by compatibility issue with other add-ons. Is there a way to find out what is happening behind the curtain?

**Comment by janekptacijarabaci** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2485 and `Workarounds`

**Comment by arantius** [comment]
I've just pushed version 3.11beta1: https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta?page=1#version-3.11beta1

It would be very useful if you could install it and confirm that it fixes this issue.

**Comment by whatUwant** [comment]
Thanks. The problem seems to be resolved.
