### ISSUE TITLE
FF 54.0b1 no longer access user scripts 

### ISSUE THREAD

**Issue by telanus** [greasemonkey/greasemonkey#2497]
Using Firefox on Ubuntu Mate 16.04.1, and all worked up to 3 days ago, Got a notice to do routine software updates like normal from Ubuntu and a few other PPA's, one included the newest Firefox. Yesterday I started FF and noticed that one of the userscripts (https://www.gog.com/forum/general/barefoot_essentials_2_gogcom_enhancement) I use no longer run.

Did check the browser console and this is a error I get when starting Greasemonkey:
```
TypeError: GM_util.getPreferredLocale is not a function[Learn More]  script.js:148:9
	getBestLocalization chrome://greasemonkey-modules/content/script.js:148:9
	Script_getLocalizedDescription chrome://greasemonkey-modules/content/script.js:156:20
	appendScriptAfter chrome://greasemonkey/content/browser.js:331:5
	asyncShowPopup/< chrome://greasemonkey/content/browser.js:395:17
	forEach self-hosted:252:13
	asyncShowPopup chrome://greasemonkey/content/browser.js:393:3
	callback chrome://greasemonkey/content/browser.js:298:5
TypeError: el is null
```

**Comment by arantius** [comment]
#2488

**Comment by arantius** [comment]
I've just pushed version 3.11beta1: https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta?page=1#version-3.11beta1

It would be very useful if you could install it and confirm that it fixes this issue.

**Comment by telanus** [comment]
@arantius Works Great thanx :dancing_women:
