### ISSUE TITLE
Make last standard version before FX57

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [greasemonkey/greasemonkey#2498]
Is there any chance you land last GM version in old style? Actually you can still do this and it will be accept by AMO, after FX57 no, so a lot of people will stick with FX56. I know you invest time for WebExt, but some bugs was fixed (https://github.com/greasemonkey/greasemonkey/pulls) and can be close also in standard version, without much effort.

**Comment by arantius** [comment]
Was already planned, thanks to known issues w.r.t. Firefox 54.

I'll push _bug fixes_ as necessary until 57.  No features.
