### ISSUE TITLE
Conflict with NoScript breaks video playback

### ISSUE THREAD

**Issue by brndd** [greasemonkey/greasemonkey#2500]
GreaseMonkey 3.11 may have introduced a peculiar conflict with NoScript that causes the playback of WebM and MP4 files to break when certain userscripts are enabled in conjuction with seemingly completely unrelated addons. I initially posted this on the [NoScript forums](https://forums.informaction.com/viewtopic.php?f=10&t=22780&p=87901), because I thought it was a bug with the new NoScript version, but after some extra debugging it seems to happen with the older NoScript releases as well, and so I suspect it is actually caused by the new GreaseMonkey version, which was released at the same time. This bug only manifested yesterday, and this exact configuration of addons and userscripts has worked fine for me for years.

The bug occurs when NoScript is used in conjuction with GreaseMonkey that is running the [Anti-Adblock Killer](https://github.com/reek/anti-adblock-killer) userscript, but *only* when a third addon such as [RefControl](https://addons.mozilla.org/en-US/firefox/addon/refcontrol/) or [Send Tab to Device](https://addons.mozilla.org/en-US/firefox/addon/send-tab-to-device/) is also running. It causes video (WebM/mp4) playback to stop working. Videos will either refuse to play back entirely, or will only load a little bit from the beginning. This only seems to affect remote files, not local files.

**Reproduction steps**

1) Install the following addons in a fresh profile:
* [NoScript 5.0.3](https://addons.mozilla.org/en-US/firefox/addon/noscript/)
* [RefControl](https://addons.mozilla.org/en-US/firefox/addon/refcontrol/)
* [GreaseMonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)

2) Install and enable the [Anti-Adblock Killer](https://github.com/reek/anti-adblock-killer) userscript in GreaseMonkey (enabling the uBlock filter list is not necessary)

3) Clear your browser cache and restart your browser

4) Video playback will now be broken

5) Disable any single one of the three addons above or the userscript, clear your cache, and restart your browser

6) Video playback will now work

Here is an assortment of random video files for testing:

https://mygi.ga/rHt/adRUo.webm
https://puu.sh/dKXfa.webm
http://cdn.ebin.pw/src/Alegz%20Jones%20Rants%20about%20Obama's%20New%20Ketchup%20Law-Wxp0SDAiXmI.mp4

**Comment by eight04** [comment]
I have the same issue, but I didn't test which add-on involves. Also, I think this only happens with `document-start` scripts enabled.

**Comment by WarriorAtWar** [comment]
I was having the same issue with just Greasemonkey 3.10 and the AdsBypasser script.
Manually upgrading to Greasemonkey 3.11 fixed this.

**Comment by janekptacijarabaci** [comment]
This:
https://github.com/greasemonkey/greasemonkey/commit/1531f342d512e9a0981897194bf3bf7ced09a1c7
is practically the only change in the source code (https://github.com/greasemonkey/greasemonkey/compare/3.9...3.10)

**Comment by WarriorAtWar** [comment]
After upgrading to the latest NoScript version (v5.0.5rc1, not available in AMO) the issue presents itself again.
As of now I'm using a couple of global rules on Greasemonkey (to avoid having to edit AdsBypasser or any other userscript) for some websites to exclude execution on MP4 or WebM URLs.

Really weird behaviour.

**Comment by brndd** [comment]
@janekptacijarabaci this issue is not relevant to 3.9...3.10, it's caused by some change in 3.10...3.11

**Comment by brndd** [comment]
Seems to be fixed in NoScript 5.0.4, although not explicitly mentioned in changelog (there is some mention about fixing file:/// URLs but that doesn't seem relevant). Can anyone confirm?
