### ISSUE TITLE
"Cannot request arbritrary files" error in version 3.11

### ISSUE THREAD

**Issue by gabrielfin** [greasemonkey/greasemonkey#2502]
There's been a recent change in PR #2486 which broke my scripts.
I'm using linux, and I have some scripts which have symlinks to a Dropbox folder. So basically: `gm_scripts/myscript` links to `~/Dropbox/myscript`

The recent update throws the error "Cannot request arbritrary files", because apparently it's trying to access `~/Dropbox/myscript/somerequiredfile.js` instead of `gm_scripts/myscript/somerequiredfile.js`

**Comment by arantius** [comment]
This is not a supported configuration.
