### ISSUE TITLE
GM_getValue in AJAX callback sometimes throwing exception since Firefox 53

### ISSUE THREAD

**Issue by ccd0** [greasemonkey/greasemonkey#2503]
Seems to be a race condition of some sort. Only seems to happen when GM_setValue has been called recently.

Script to reproduce:
```
// ==UserScript==
// @name        GM_setValue test
// @namespace   test
// @include     http://example.com/
// @version     1
// @grant       GM_getValue
// @grant       GM_setValue
// ==/UserScript==

function getTest() {
  try {
    let n = GM_getValue('foo');
    console.log('get', n);
  } catch(err) {
    console.error(err);
  }
}

for (let i = 0; i < 10; i++) {
  let x = new XMLHttpRequest();
  x.open('GET', 'http://example.com/');
  x.onload = function() {
    console.log(x.status, x.statusText);
    getTest();
  };
  x.send();
}

let t = Date.now();
console.log('set', t);
GM_setValue('foo', t);
```

Tested with:
Greasemonkey	3.11
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

Here's one of the errors thrown:
"Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage]"

GM_ScriptStorageFront.prototype.getValue@chrome://greasemonkey-modules/content/storageFront.js:59:15
hitch/<@chrome://greasemonkey-modules/content/util/hitch.js:27:12
getTest@file:///C:/Users/anon/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default/gm_scripts/GM_setValue_test/GM_setValue_test.user.js:12:13
x.onload@file:///C:/Users/anon/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default/gm_scripts/GM_setValue_test/GM_setValue_test.user.js:24:5
waitForSyncCallback@resource://services-common/async.js:98:7
makeSpinningCallback/callback.wait@resource://services-common/async.js:168:27
promiseSpinningly@resource://services-common/async.js:234:12
get changedIDs@resource://services-sync/engines.js:98:5
_saveChangedID@resource://services-sync/engines.js:139:5
addChangedID@resource://services-sync/engines.js:160:7
notifyEvent@chrome://greasemonkey-modules/content/sync.js:229:11
Config.prototype._notifyObservers@chrome://greasemonkey/content/config.js:47:5
Config.prototype._changed@chrome://greasemonkey/content/config.js:56:3
Script.prototype._changed@chrome://greasemonkey-modules/content/script.js:91:3
GM_ScriptStorageBack.prototype.setValue@chrome://greasemonkey-modules/content/storageBack.js:83:3
service.prototype.handleScriptValMsg@jar:file:///C:/Users/anon/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default/extensions/%7Be4a8a97b-f2ed-450b-b12d-ee082ba24781%7D.xpi!/components/greasemonkey.js:243:12
GM_ScriptStorageFront.prototype.setValue@chrome://greasemonkey-modules/content/storageFront.js:52:3
hitch/<@chrome://greasemonkey-modules/content/util/hitch.js:27:12
@file:///C:/Users/anon/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default/gm_scripts/GM_setValue_test/GM_setValue_test.user.js:31:1
evalWithWrapper@chrome://greasemonkey-modules/content/sandbox.js:191:7
evalWithCatch@chrome://greasemonkey-modules/content/sandbox.js:215:7
runScriptInSandbox@chrome://greasemonkey-modules/content/sandbox.js:230:3
injectScripts@chrome://greasemonkey/content/framescript.js:119:5
runScripts@chrome://greasemonkey/content/framescript.js:149:3
contentLoad@chrome://greasemonkey/content/framescript.js:72:3

**Comment by arantius** [comment]
Firefox is _crashing_?  Or logging an error and the script stops running?

**Comment by ccd0** [comment]
Sorry, not crashing. Just throwing an exception.

**Comment by ccd0** [comment]
Is Greasemonkey abandoned?

**Comment by arantius** [comment]
Grasemonkey 3: yes.  Greasemonkey 4: no.

**Comment by ccd0** [comment]
Update: Errors no longer happening as of 3.16, at least for this test script.
