### ISSUE TITLE
Open script in external editor and/or open directory with the script

### ISSUE THREAD

**Issue by vanowm** [greasemonkey/greasemonkey#2504]
Hello.
Would be nice if we could open scripts in external editor or at least able open the folder where the script is from toolbar button.

**Comment by arantius** [comment]
You can.  Look in the options.

**Comment by vanowm** [comment]
Sorry, I didn't make myself clear, what I meant was have an choice where open the script in without changing any settings each time.

Sometimes I don't want open my editor which restores previous session with 50 other files in it, using built-in editor would be fine, but sometimes I'd like use my editor.
Having an option to specify which editor to use by default and yet have an option at toolbar button to open in another editor - that would be very helpful (I think simplest way would be track if CTRL or SHIFT key was pressed down when right click on script in toolbar menu, or a checkbox)
Even if we could do this from within built-in editor that would be just fine too.

Heck, I'd settle if we could open folder where the script is...

**Comment by arantius** [comment]
> Heck, I'd settle if we could open folder where the script is...

That feature's existed (in the script manager dialog, right click) for quite some time.

**Comment by vanowm** [comment]
Yes, it does, but having hundreds of userscripts this process is quiet inconvenient...
