### ISSUE TITLE
Latest version completely rewrote all my scripts

### ISSUE THREAD

**Issue by PaulBags** [greasemonkey/greasemonkey#2505]
Latest version completely rewrote all my scripts. What the hell guys?

**Comment by arantius** [comment]
What in the world does "completely rewrote" mean?

**Comment by JackTheDipper** [comment]
Maybe the same as for me? I lost all my user scripts without warning/error. My script list is just empty now. :-\

Using Greasemonkey 3.8 (latest AMO version) on Firefox 54.
