### ISSUE TITLE
Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage]

### ISSUE THREAD

**Issue by fdellwing** [greasemonkey/greasemonkey#2506]
I get the following error while running a userscript more than ~5 times at the same time. (Yes, this is a very likely situation for this script, because you open a lot of new tabs)

> 
> 19:48:41.905 Exception { message: "Component returned failure code: 0x…", result: 2147549183, name: "NS_ERROR_UNEXPECTED", filename: "chrome://greasemonkey-modules/conte…", lineNumber: 59, columnNumber: 0, data: null, stack: "GM_ScriptStorageFront.prototype.get…", location: XPCWrappedNative_NoHelper } 1 mm_skills_0_21.user.js:936:3
> 
> filename: chrome://greasemonkey-modules/content/storageFront.js
> message: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage]
> stack: "GM_ScriptStorageFront.prototype.getValue@chrome://greasemonkey-modules/content/storageFront.js:59:15hitch/<@chrome://greasemonkey-modules/content/util/hitch.js:27:12saveSkillDescIntoStorage@file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/gm_scripts/Mach_fertigkeiten_huebsch/mm_skills_0_21.user.js:925:14skillDescMain@file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/gm_scripts/Mach_fertigkeiten_huebsch/mm_skills_0_21.user.js:1602:2@file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/gm_scripts/Mach_fertigkeiten_huebsch/mm_skills_0_21.user.js:356:2evalWithWrapper@chrome://greasemonkey-modules/content/sandbox.js:191:7evalWithCatch@chrome://greasemonkey-modules/content/sandbox.js:215:7runScriptInSandbox@chrome://greasemonkey-modules/content/sandbox.js:230:3injectScripts@chrome://greasemonkey/content/framescript.js:119:5runScripts@chrome://greasemonkey/content/framescript.js:149:3contentLoad@chrome://greasemonkey/content/framescript.js:72:3openTabPrompt@resource://gre/components/nsPrompter.js:420:13openPrompt@resource://gre/components/nsPrompter.js:535:17alert@resource://gre/components/nsPrompter.js:602:9transmitErrorMessageToServer@file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/gm_scripts/Mach_fertigkeiten_huebsch/mm_skills_0_21.user.js:384:3saveSkillDescIntoStorage@file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/gm_scripts/Mach_fertigkeiten_huebsch/mm_skills_0_21.user.js:937:3skillDescMain@file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/gm_scripts/Mach_fertigkeiten_huebsch/mm_skills_0_21.user.js:1602:2@file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/gm_scripts/Mach_fertigkeiten_huebsch/mm_skills_0_21.user.js:356:2evalWithWrapper@chrome://greasemonkey-modules/content/sandbox.js:191:7evalWithCatch@chrome://greasemonkey-modules/content/sandbox.js:215:7runScriptInSandbox@chrome://greasemonkey-modules/content/sandbox.js:230:3injectScripts@chrome://greasemonkey/content/framescript.js:119:5runScripts@chrome://greasemonkey/content/framescript.js:149:3contentLoad@chrome://greasemonkey/content/framescript.js:72:3waitForSyncCallback@resource://services-common/async.js:98:7makeSpinningCallback/callback.wait@resource://services-common/async.js:168:27promiseSpinningly@resource://services-common/async.js:234:12get changedIDs@resource://services-sync/engines.js:97:5addChangedID@resource://services-sync/engines.js:158:1notifyEvent@chrome://greasemonkey-modules/content/sync.js:229:11Config.prototype._notifyObservers@chrome://greasemonkey/content/config.js:47:5Config.prototype._changed@chrome://greasemonkey/content/config.js:56:3Script.prototype._changed@chrome://greasemonkey-modules/content/script.js:91:3GM_ScriptStorageBack.prototype.setValue@chrome://greasemonkey-modules/content/storageBack.js:83:3service.prototype.handleScriptValMsg@jar:file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/extensions/%7Be4a8a97b-f2ed-450b-b12d-ee082ba24781%7D.xpi!/components/greasemonkey.js:243:12GM_ScriptStorageFront.prototype.setValue@chrome://greasemonkey-modules/content/storageFront.js:52:3hitch/<@chrome://greasemonkey-modules/content/util/hitch.js:27:12onload@file:///C:/Users/Zero10/AppData/Roaming/Mozilla/Firefox/Profiles/71wnn5e5.dev-edition-default/gm_scripts/Dunuins_Countdown/dunuins_countdown_gm_0_4_12.user.js:143:57GM_xmlhttpRequester.prototype.setupRequestEvent/</<@chrome://greasemonkey-modules/content/xmlhttprequester.js:285:31setTimeout handler*GM_xmlhttpRequester.prototype.setupRequestEvent/<@chrome://greasemonkey-modules/content/xmlhttprequester.js:284:5fileXhr@chrome://greasemonkey-modules/content/util/fileXhr.js:20:3loadFile@chrome://greasemonkey-modules/content/util/loadFile.js:63:10evalWithWrapper@chrome://greasemonkey-modules/content/sandbox.js:189:18evalWithCatch@chrome://greasemonkey-modules/content/sandbox.js:215:7runScriptInSandbox@chrome://greasemonkey-modules/content/sandbox.js:230:3injectScripts@chrome://greasemonkey/content/framescript.js:119:5runScripts@chrome://greasemonkey/content/framescript.js:149:3contentLoad/<@chrome://greasemonkey/content/framescript.js:73:32observe@chrome://greasemonkey-modules/content/util/timeout.js:17:7"
> 

This is the code that throws the error:

```javascript
function saveSkillDescIntoStorage(skillName, content) {
	var functionName = "saveSkillDescIntoStorage";
	try {
		
	var skill = GM_getValue(world + '_' + skillName, false)
	
	//If it is only a placeholder or if the content is different from the saved content save the readout.
	if (skill == 'Platzhalter')
		GM_setValue(world + '_' + skillName, JSON.stringify(content));
	else if (skill != JSON.stringify(content))
		GM_setValue(world + '_' + skillName, JSON.stringify(content));
	else
		return false;
	
	} catch(e) {
		console.log(e);
		transmitErrorMessageToServer(functionName, e);
	}
}
```

It is pretty hard to really log this error, because the error object GM throws is protected as hell. I cant even run toString oder JSON.stringify on it and me error function fails completely...

This seems to be a problem like in #2503 bit without the xmlhttprequest.

**Comment by janekptacijarabaci** [comment]
Use `sendRpcMessage` instead of `sendSyncMessage`?
See also https://github.com/greasemonkey/greasemonkey/issues/2107#issuecomment-127280240

Maybe it would help...

**Comment by fdellwing** [comment]
Will try this, but it is not a solution, because I cannot tell everyone using this script to hack into GM themself.

**Comment by janekptacijarabaci** [comment]
Yes. but... It doesn't happen often (throws this errors). I can't verify if this is the solution (or at least partially - if it was better than nothing).

**Comment by fdellwing** [comment]
I tried this, but firefox deactivated the addon because reasons. Any ideas how to get around that?

**Comment by fdellwing** [comment]
Ok, got it to work.

The problem is gone after replacing all 4 occurences of this._messageManager.sendSyncMessage with this._messageManager.sendRpcMessage.

But as I statet above, I need this to be fixxed from official site :/

**Comment by janekptacijarabaci** [comment]
Thank you.

**Comment by fdellwing** [comment]
Thank you, too.

**Comment by makyen** [comment]
For me, this issue immediately began occurring upon upgrade to Firefox 53.0. In the script I'm working on, under normal use, the exception occurs 100% of the time for some calls to `GM_getValue()`, but not all. It does not occur at all using the same profile and the same conditions, under Firefox 52.0.2.

The above pull request, #2507, does fix the problem in FF53.0.3 (testing in FF53.0.3 required [disabling signature checking](https://stackoverflow.com/a/42403531/3773011)).

**Comment by fdellwing** [comment]
Dafuq happened?

**Comment by arantius** [comment]
Handled in #2537 .

**Comment by arantius** [comment]
This should be fixed in: https://addons.mozilla.org/firefox/downloads/file/722216/greasemonkey-3.12beta1-fx.xpi?src=devhub

Testing this beta version and reporting back here would be very useful!
