### ISSUE TITLE
[security] Scripts can modify domains they operate on in slient updates

### ISSUE THREAD

**Issue by Eccenux** [greasemonkey/greasemonkey#2514]
GM version: 3.1.1

Steps to reproduce the problem
---------------------------------------
Note! To reproduce you need a server.
a. Unzip [Test tool zip](https://f.enux.pl/gm/test-update/test-update.zip).
b. Modify code of scripts so that both `@updateURL` and `@downloadURL` points to your server.
c. Copy `v1_innocent/fraudulent-tool.*.js` to your server.
d. Install the Test tool.
e. Copy `v2_expansion/fraudulent-tool.*.js` to your server.
f. Initiate scripts update.

Current behaviour
---------------------------------------
No feedback is provided for a user about `@include` expansion. The script just starts working on a completely different domain.

Expected behaviour
---------------------------------------
If an update would allow running scripts on new domains users must be notified of the change with a warning stating new domains. There should also be a consent required.

Something like:
```
Script {oldMeta[@name]} is trying to expand to new servers.
Be advised that this might be an attack!

New permissions are:
{newMeta[@include]}

Are you sure you want to update?
[Yes, update] [Show source] [[No, keep old]]
```
"No, keep old" should be default.

**Comment by tiansh** [comment]
What if the script is using regular expression for `@ include` ?

**Comment by Eccenux** [comment]
Then every change to that expression should be accepted by users. Unless maybe the expression is simple enough to be sure the domain didn't change. I think that would be a separate issue though.

But for regular expression changes this should probably be the message:
```
Script {oldMeta[@name]} is expanding to new urls.
Be advised that this might be an attack!

... (the rest would be the same) ...
```
