### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by Sophira** [greasemonkey/greasemonkey#2520]
I believe I've found a potential security issue in Greasemonkey which allows websites to cause userscripts to call custom code even when not using `unsafeWindow`, but I'm unsure. I don't want to post the details here in a public tracker; how can I safely give details of this potential issue?

**Comment by arantius** [comment]
My email is this username at gmail.com, feel free to reach out.

**Comment by Sophira** [comment]
Thank you; I've sent an email!

**Comment by arantius** [comment]
Discussed offline and this turned out to be a benign and intentional behavior.
