### ISSUE TITLE
Having even a trivial @run-at document-start script enabled may make ImageDocuments fail to load

### ISSUE THREAD

**Issue by fstirlitz** [greasemonkey/greasemonkey#2524]
Steps:

0. Install and enable this script:
```js
// ==UserScript==
// @name        EMPTY
// @namespace   empty
// @include     *
// @run-at      document-start
// @version     1
// @grant       none
// ==/UserScript==
```
1. Open a new tab and load [an ImageDocument](https://httpbin.org/image/jpeg).
2. Observe a blank page.

Firefox 54. The issue can be worked around by removing the `// @run-at document-start` directive, disabling all scripts with it, or disabling GM entirely.

**Comment by arantius** [comment]
Does not reproduce, works fine for me, image continues to load.

**Comment by eight04** [comment]
Maybe this is related to #2500.

**Comment by fstirlitz** [comment]
Well, it reproduces every time for me. I do have NoScript installed as well... should probably research this more.

**Comment by fstirlitz** [comment]
Okay, this seems to be an interaction between multiple extensions. I managed to reproduce with only three of my extensions enabled:
- Privacy Badger
- Greasemonkey
- Copy Links

Disabling any one of these will make the bug go away. I can also trigger the bug with a different set of extensions; there is only one extension which I can disable to make the issue disappear *reliably*, and that is GM, so that's where I'm going to put the blame.

**Comment by janekptacijarabaci** [comment]
> Copy Links

Which of them is correct?

**Comment by fstirlitz** [comment]
> Which of them is correct?

What?

**Comment by janekptacijarabaci** [comment]
https://addons.mozilla.org/cs/firefox/addon/copylinks/
or
https://addons.mozilla.org/cs/firefox/addon/copy-links/
?

**Comment by fstirlitz** [comment]
[The one by JackieKu](https://addons.mozilla.org/cs/firefox/addon/copy-links/).

**Comment by janekptacijarabaci** [comment]
It works for me (I don't have the problem mentioned above),

**Comment by ssixty** [comment]
I also have this issue. Either fully disabling Privacy Badger (not just clicking 'disable on this site')  or disabling the one script I have installed using "run-at document-start"  lets me view direct image links again.

**Comment by fstirlitz** [comment]
I am not crazy, it seems! Here's another minimal set of extensions that triggers the bug for me:

- Greasemonkey
- [EPUB Reader](https://www.epubread.com/en/)
- [Y U no validate](http://wodny.org/projects/y-u-no-validate.html)

It seems crucial that at least one WebExtension and one other non-WebExtension has to be included in the set for the issue to appear.

**Comment by ssixty** [comment]
I've now tested in a brand new FF profile with only:

- Greasemonkey + the test script in OP.
- Privacy Badger
- Ubuntu Modifications

Can't load a JPG until I disabling any one of the three extensions, or disable the test script.

**Comment by Sxderp** [comment]
> It seems crucial that at least one WebExtension and one other non-WebExtension has to be included in the set for the issue to appear.

This. uBlock Origin just recently updated to a WebExt hybrid and it broke my images. The fix was to downgrade uBlock Origin...

**Comment by r-a-y** [comment]
I can verify the report by @fstirlitz.

Having any userscript enabled with `@run-at document-start` with a particular WebExtension will cause image URLs to fail.  Switching the script to `document-idle` or `document-end` will fix the image URL problem, but breaks the userscript's functionality relying on document-start.

In my case, the particular extension causing this problem is uBlock Origin 1.14.4 (WebExtension version).  As mentioned by @Sxderp, downgrading to uBo 1.13.8 is a temporary workaround.

**Comment by legnaleurc** [comment]
Hi,
I think this is a bug in Firefox:  https://bugzil.la/1396395
and it has been fixed in future release.

The actual STR is pretty tricky, the key is non-e10s mode, with any WE which will observe http response, and a `@run-at document-start` userscript with GreaseMonkey 3.x.

**Comment by Owyn** [comment]
> Okay, this seems to be an interaction between multiple extensions.

You're right, GM + Ublock origin does this for me, If I disable ublock it start to work fine

**Comment by mazesy** [comment]
No problem here with GreaseMonkey 3.14 / Waterfox 50.1.0 / Windows 7 x64
uBO is 1.14.10 but legacy add-on, not the Webextension, and maybe does that make the difference if the pair GM+uBO is the culprit?

**Comment by madmuffinz** [comment]
I downgraded to ublock origin 1.13.8 (last version that isn't the web extension) and greasemonkey loads images just fine!
As mazesy said, it is ublock origin web extension being the culprit!
