### ISSUE TITLE
My script doesn't run when I @require the `packery.js` lib

### ISSUE THREAD

**Issue by trmdi** [greasemonkey/greasemonkey#2528]
Hi, why doesn't this script run when I require the `packery.js` lib?
Tampermonkey runs it well on both Google Chrome and Firefox.
Everything is up-to-date.

```javascript
// ==UserScript==
// @name        Script not run with packery.js
// @include     https://github.com/*
// @grant       GM_addStyle
// @require     https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js
// @require     https://cdnjs.cloudflare.com/ajax/libs/packery/2.1.1/packery.pkgd.min.js
// ==/UserScript==

alert("hello"); // the script only runs when I delete the line @require packery.js
```

**Comment by arantius** [comment]
This isn't a support forum.

**Comment by trmdi** [comment]
@arantius: I think this is a bug of Greasemonkey.

**Comment by trmdi** [comment]
@desandro: Sorry to bother you, but this isn't a bug of packery, is it? I think that because packery works perfectly with Tampermonkey or a normal html page. The problem only occurs when I require it from this Greasemonkey script.

**Comment by janekptacijarabaci** [comment]
Not related to Greasemonkey.

Scratchpad ("Environment-Browser"):

```
var localUrl1 = "file:///[drive]:/[path]/jquery.min.js";
var localUrl2 = "file:///[drive]:/[path]/packery.pkgd.min.js";

var sandbox = new Components.utils.Sandbox(this, {
  sameZoneAs: this,
  sandboxName: "gm",
  sandboxPrototype: this,
  wantXrays: true,
});

Components.classes["@mozilla.org/moz/jssubscript-loader;1"]
    .getService(Components.interfaces.mozIJSSubScriptLoader)
    .loadSubScript(localUrl1, sandbox, "UTF-8");

Components.classes["@mozilla.org/moz/jssubscript-loader;1"]
    .getService(Components.interfaces.mozIJSSubScriptLoader)
    .loadSubScript(localUrl2, sandbox, "UTF-8");
```

Throws an error:
```
Exception: TypeError: t is undefined
```

**Comment by trmdi** [comment]
@janekptacijarabaci:
First of all, thank you verys much for your reply.

I still don't understand, if this problem doesn't come from greasemonkey, if it's a bug of packery (I hope I'm not misunderstanding you) so why with the same script:
+ tampermonkey on firefox as well as on chrome could run?
+ a normal html web page (not use greasemonkey or tampermonkey at all) could run?

**Comment by janekptacijarabaci** [comment]
Either the bug is in the (XPCOM - that is the difference between Components.utils.Sandbox and WebExtensions) sandbox (but i.e. FF25, and FF25+) or in the script.
I don't know. But AFAIK: the second option is more likely.

**Comment by trmdi** [comment]
Thank you again. You are very polite @janekptacijarabaci

**Comment by janekptacijarabaci** [comment]
However, there have been problems in the past with the Sandbox (XPCOM), see also e.g.:
#1510 
#1571 
#2345 
#2364 

And see also:
https://bugzilla.mozilla.org/show_bug.cgi?id=914970
