### ISSUE TITLE
Feature Request: Export entire API in a namespace object

### ISSUE THREAD

**Issue by mk-pmb** [greasemonkey/greasemonkey#2529]
My current UserScripts are bloated with global variable declarations for my linter. Could we reduce that by adding a namespace object like `GM_API` that aliases all its API globals, ideally without the `GM_` prefix? Then I could tell my linter about only that one container and use them like `var gm = GM_API; gm.addStyle(…)` instead of `GM_addStyle(…)`.

**Comment by arantius** [comment]
This is how 4.x is being written.

**Comment by mk-pmb** [comment]
Nice, thanks!
