### ISSUE TITLE
Add weave/sync support

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2532]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync

Seems to be the only channel for this.  Do some planning for how to make this reliable; detect new remote installs and deletes then apply them locally, reliably.

**Comment by yurikhan** [comment]
This is going to be affected by the “100KB of data” limit imposed by that API, right?

No plans to sync local scripts to Google Drive, or Dropbox, or any kind of user-hosted cloud? Heck, even local filesystem via native messaging?

**Comment by mattrossman** [comment]
Any updates on this?

As a new user this is a pretty critical feature, I'm not sure how else users are expected to keep their custom browser experience in sync between devices. Is there a trick I'm missing?

**Comment by leodoi3** [comment]
I also need a sync feature.
