### ISSUE TITLE
(script editing menu) 'Edit' >'Find' & 'Find next' not working

### ISSUE THREAD

**Issue by gomoku** [greasemonkey/greasemonkey#2535]
When I'm editing a script, when in the menu I click Edit > Find - nothing is happening,
the yellow Find box popups only by shortcut keys Ctrl + F.
Even more odd happens with Edit > Find next, it's always grayed out thus unclicable,
but again, Ctrl + G works.

FF 54.0.1 e10s & HWA + Greasemonkey 3.11

**Comment by janekptacijarabaci** [comment]
This problem is in Scratchpad (Firefox), not related to Greasemonkey.
