### ISSUE TITLE
Broken in Nightly: nsIURI.path renamed to nsIURI.pathQueryRef

### ISSUE THREAD

**Issue by RealDolos** [greasemonkey/greasemonkey#2536]
Somehow the mozilla folks found it necessary to do this purely cosmetic change and break a ton of stuff in the process incl their own testing infrastructure (so no idea if that commit will actually stick in the long run).

https://bugzilla.mozilla.org/show_bug.cgi?id=1326520

Affected in greasemonkey are at least:
 - Update checking (because it tries to rename `user.js` to `meta.js`)
 - `MatchPattern` i.e. `@match`

**Comment by jasontibbitts** [comment]
That PR does fix the issue for me.  It's so nice to have greasemonkey working again.

**Comment by arantius** [comment]
Ah, this is unnecessary.
