### ISSUE TITLE
Secure user input

### ISSUE THREAD

**Issue by lkraider** [greasemonkey/greasemonkey#2539]
Currently if a user script requires user input, it has to resort to creating it in the DOM of the website being processed, which opens the input to being handled by the website if it's malicious.

For example, if the user script needs to ask a password that should not go to the website, but just be used to extract data from the website (example encrypted data intended for the user), there is no secure way to present that input control.

This is a request to have Greasemonkey provide a way to gather user input without being possible for the website to intercept the data. Ideally in a way that can be styled and embedded on the page.

See #2393

**Comment by the8472** [comment]
I don't think this is easy. It's possible to inject an isolate iframe into a page and communicate with it. But ensuring that the page isn't clickjacking the iframe (fighting it with overlays, z-index etc.) would be hard.

The only safe way to do something like that right now is to open a popup with all the UX annoyances that involves. FF bug [1364404](https://bugzilla.mozilla.org/show_bug.cgi?id=1364404) or [1340930](https://bugzilla.mozilla.org/show_bug.cgi?id=1340930) may provide the necessary building blocks, but those are a far way off.
