### ISSUE TITLE
Can't load resource from GM_getResourceURL

### ISSUE THREAD

**Issue by eight04** [greasemonkey/greasemonkey#2543]
I noticed that an userscript failed to load CSS after my Firefox upgraded.

Firefox Developer Edition
Version 	56.0b2
Build ID 	20170810180547

Steps to reproduce:

1. A clean profile
2. Install [Better Standalone Image](https://greasyfork.org/en/scripts/31865-better-standalone-image)
3. Open an image (e.g. http://i.imgur.com/hpk02cI.jpg)
4. The CSS isn't loaded.
5. Find the URL of the style and try to open it in a new tab
6. Access to the file was denied

![http://i.imgur.com/fDCFnjk.png](http://i.imgur.com/fDCFnjk.png)
![http://i.imgur.com/S2zUD3Y.png](http://i.imgur.com/S2zUD3Y.png)

**Comment by janekptacijarabaci** [comment]
Confirmed.

Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=0faada5c2f308f101ab7c54a87b3dce80b97d0e3&tochange=a8bb5530a0925ac0823bdb6d525cbc6f304f8928

Bug/s [1377595](https://bugzilla.mozilla.org/show_bug.cgi?id=1377595) / [1366694](https://bugzilla.mozilla.org/show_bug.cgi?id=1366694) is/are the suspect.

---

A fix:
`about:config`
`security.sandbox.content.level` = `1` (or `2`)

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1388046#c6
