### ISSUE TITLE
Marked as legacy in latest Firefox

### ISSUE THREAD

**Issue by JonnyTech** [greasemonkey/greasemonkey#2544]
The Greasemonkey extension in Firefox 55+ is marked as "legacy" and will stop working in Firefox 57 unless a config option is used, or the addon is rewritten with the WebExtension API:

https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

> Starting in Firefox 57, which will be released in November 2017, only add-ons built with this new technology will work in Firefox.

I cannot find any mention of this in the other issues - are there any plans to implement this?

**Comment by JonnyTech** [comment]
Ah, I found a discussion on the mailing list - for reference to others, it is here: https://groups.google.com/forum/#!topic/greasemonkey-users/Va5kqhkgVG8

**Comment by arantius** [comment]
https://github.com/greasemonkey/greasemonkey/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0
