### ISSUE TITLE
Migrate legacy -> webext

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2551]
Migrate scripts/settings from legacy extension to a webext accessible location.

**Comment by arantius** [comment]
https://stackoverflow.com/questions/45948501

Embedded webextensions are a thing, but not for us (?).

**Comment by ngyikp** [comment]
It's possible to use embedded WebExtension for overlay add-ons: https://github.com/mdn/webextensions-examples/tree/master/embedded-webextension-overlay

**Comment by arantius** [comment]
Thank you for that link.  Another example of Mozilla's [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) being disappointing.

**Comment by davidhedlund** [comment]
@arantius is Greasemonkey a hybrid WebExtension yet?

**Comment by davidhedlund** [comment]
@arantius An add-on is a hybrid WE if it has a "hasEmbeddedWebExtension" key available in the install.rdf, its not found in the current version of Greasemonkey.

I didn't know that was the standard procedure when I asked, sorry.

**Comment by arantius** [comment]
The point of this issue is to make it one, so the fact that it's not been closed should help you figure that out.  I've just barely started work on this.

**Comment by davidhedlund** [comment]
@arantius A Hybrid WebExtensions is not the same as a WebExtension.

**Comment by arantius** [comment]
1. Install developer edition ( https://www.mozilla.org/en-US/firefox/developer/ )
2. Create a profile for testing
3. Toggle xpinstall.signatures.required to false
4. Install greasemonkey-2017.09.05.beta.xpi (including restart)
5. Install any user script (preferably something that's easy to tell is running)
6. Install greasemonkey-4.0alpha1.xpi

At this point I'd expect the webext alpha to have a script installed at this point, but no dice.

**Comment by StrikerFX** [comment]
Where can I find the download link of the two versions: greasemonkey-2017.09.05.beta and greasemonkey-4.0alpha1.xpi?

**Comment by hook54321a** [comment]
Will the non-webext version still be maintained? Quite a few people still use it on Pale Moon.

**Comment by Sxderp** [comment]
@hook54321a, Since all the issues regarding GreaseMonkey that had to do with <4.0 have been closed, I'd reckon the answer to that is no.

**Comment by arantius** [comment]
https://mail.mozilla.org/pipermail/dev-addons/2017-September/003151.html

I've got "working" code for this (all log messages are as expected), which doesn't work (data isn't actually migrated).

**Comment by arantius** [comment]
The failure mentioned above was arantius/greasemonkey@d94af37e571648aff7d8614277b49120e5c48639 .  I've got one working end to end test of this now, so the plan is to clean it up, finalize a 3.x release and get it out ASAP.

**Comment by Sxderp** [comment]
> The failure mentioned above was arantius/greasemonkey@d94af37 . I've got one working end to end test of this now, so the plan is to clean it up, finalize a 3.x release and get it out ASAP.

Rip. Just set up to test the problems. Anyway, at least it's resolved.

**Comment by arantius** [comment]
https://addons.mozilla.org/firefox/downloads/file/722216/greasemonkey-3.12beta1-fx.xpi?src=devhub

I've added support for pushing data into the (embedded) webextension in 3.12.  This is impossible to test without building yourself a webext version of Greasemonkey, but testing that 3.12 continues to work without new bugs would be helpful.
