### ISSUE TITLE
Direct Image URLS No Longer Showing Images for Many Sites

### ISSUE THREAD

**Issue by Zetawilk** [greasemonkey/greasemonkey#2554]
Many websites with links directly to image URLs are no longer displaying those images at the image URL when Greasemonkey is enabled.

**Comment by eight04** [comment]
Probably duplicate of #2524.

**Comment by ssixty** [comment]
Could we get #2524 re-opened please?

**Comment by janekptacijarabaci** [comment]
See also https://github.com/gorhill/uBlock/issues/2930#issuecomment-325972269
