### ISSUE TITLE
My Firefox does not load images directly when Greasemonkey is turned on

### ISSUE THREAD

**Issue by allanf181** [greasemonkey/greasemonkey#2562]
![image](https://user-images.githubusercontent.com/14101716/30465392-4ab2c346-99ad-11e7-9c79-3991019cd991.png)
![image](https://user-images.githubusercontent.com/14101716/30465399-57313cc4-99ad-11e7-8e49-ada9eec28c82.png)

**Comment by allanf181** [comment]
It's not scripts because I've tried to deactivate them one by one.

**Comment by janekptacijarabaci** [comment]
See #2524, #2554, https://github.com/EFForg/privacybadger/issues/1653 and https://github.com/gorhill/uBlock/issues/2930.

**Comment by ProudNoob** [comment]
Don't know if it helps but I had the same issue. The culprit turned out to be the Stackoverflow Dark userstyle script. Turning it off from Greasemonkey solved the issue

**Comment by arantius** [comment]
Whoops, above commit was intended for #2652, not this.
