### ISSUE TITLE
4.x No logging of Script Errors

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2564]
Currently if there's a problem with a user script, most notably syntax errors, no errors are logged to the page console (ctrl+shift+k) or the browser console (ctrl+shift+j). There is an error (probably just the default) in the addon debuging console.

**Comment by arantius** [comment]
I *hope* https://bugzilla.mozilla.org/show_bug.cgi?id=1353468 will help.  But really, we have little to no control.

**Comment by fdellwing** [comment]
This is not really a problem of GM. If you have an error in your JS ist will die silently everytime. If you really want to make sure your code runs, learn to wrap everything in try catch, everything.

But there is a problem with that method in GM 4.x, see #2584

**Comment by watercrossing** [comment]
Could this be documented somewhere more obvious? Finding the addon debugging process is not trivial (https://developer.mozilla.org/en-US/Add-ons/Add-on_Debugger)
