### ISSUE TITLE
When a script is updated, provide link to the script home page

### ISSUE THREAD

**Issue by gbakeman** [greasemonkey/greasemonkey#2566]
I have a userscript (Iridium) that frequently receives updates. To view updates normally, I'd open the greasemonkey userscripts window, click on the script, then click on its homepage URL to see what's changed. It would be really great if the popup window that notifies me of a new update would have the URL there to make it a little easier to view the changes (or even better, if the changes are shown inline).

**Comment by arantius** [comment]
I think adding a quick way to view the homepage makes sense and is doable.  

For all the other possible things (main script, any includes, any resources, possibly images, etc.) that could change: that's a bit much.

**Comment by iology** [comment]
I think a diff report is better than going to the homepage.

The report only contains only the diff for the main .user.js.

**Comment by iology** [comment]
It is also nice to view the diff before installing.

**Comment by tgp1994** [comment]
@iology While having a diff might be nice, as far as normal software releases go this seems pretty out of the ordinary to me. I'm more used to reading succinct changelogs written by the developer, which is sort of what I was expecting. I think @arantius has already decided to go with just showing a link to the homepage though.

**Comment by arantius** [comment]
There is no "notify of an update" window.

The monkey menu recently got a homepage link (for scripts that specify `@homepageURL` -- and were installed after support was added).  Only in the latest nightlies so far ( http://arantius.com/misc/gm-nightly/ ).  Is this enough?

**Comment by tgp1994** [comment]
> There is no "notify of an update" window.

I think you're quoting my original post there? When I wrote this originally (for GM 3?), I recall that Greasemonkey would show a small window when a script was updated. Of course that all changed when Firefox moved to the new extension system.

I'd be happy with having the homepage link. Thank you for your work!
