### ISSUE TITLE
Add "install disabled" feature to fill the "view script source" feature

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2567]
To enable review of user script content, allow installation directly into a disabled state.  So the script will never run -- the user can open, review, edit the script and only then enable it.

**Comment by StigNygaard** [comment]
I'm not sure I fully understand how this is supposed to work, and if I will be happy with it (I'm very skeptical).
But as a quick fix while waiting, couldn't we at least get a view-source: link in the install dialog?

**Comment by Sxderp** [comment]
While this would be a nice feature, this may not be totally required to 'replace view source' if / when #2719 is merged. By moving detection to the background we can then open a popup box (or new tab) for the installation and let the user script continue to load / display in the original tab.

**Comment by arantius** [comment]
I fat fingered the wrong issue number in 54dfa85e69482bb2fa4c9f86d035f8879c016c9c, which resolved this.
