### ISSUE TITLE
GM.getResourceUrl is synchronous

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2571]
Every other `GM.` method returns a promise.  `GM.getResourceUrl` directly returns its value.

A) Switch `GM.getResourceUrl` to also return a promise
or
B) Document the difference to other methods

**Comment by Sxderp** [comment]
Maybe I'm misinterpreting what you're trying to indicate but it seems to return a promise already?

[latest commit](https://github.com/greasemonkey/greasemonkey/blob/10f3ef620c21865cf1db778b4cfd193d31a7f20e/src/bg/api-provider-source.js#L61)

**Comment by arantius** [comment]
Indeed!  I was rushed and confused.
