### ISSUE TITLE
After updating 3.11 -> 3.12, whenever I close Firefox, 2 firefox.exe instances remain

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2573]
Using GM 3.11 (with a lot of usescripts and stored settings) in FF 55.0.3 x64 in win10.
Multiprocess is enabled. I quote from about:support :
```
Multiprocess Windows 	1/1 (Enabled by default)
Web Content Processes 	1/1
```

Whenever I run Firefox I see 3 firefox.exe instances in Task Manager _(provided that I have opened a web page, not only Firefox internal pages, otherwise they are 2)_.

So, today, I updated GM 3.11 -> 3.12, restarted Firefox(pressed 'Restart now'), all seemed to work ok, and then closed Firefox:
I noticed in Task Manager that unfortunately, 2 firefox.exe processes remained  
and after 1 min the Mozilla Crash Reporter was displayed (and those 2 processes were eventually terminated).
Here is the [crash report](https://crash-stats.mozilla.com/report/index/7c18a99c-428b-40a8-8e30-360e81170921) 
and here is the related bugzilla bug: [1377277 - Crash in shutdownhang | NtWaitForAlertByThreadId | RtlSleepConditionVariableSRW | SleepConditionVariableSRW | mozilla::detail::ConditionVariableImpl::wait | mozilla::CondVar::Wait | nsEventQueue::GetEvent | nsThread::nsChainedEventQueue::GetEvent | nsT...](https://bugzilla.mozilla.org/show_bug.cgi?id=1377277) 

After that, whenever I close Firefox, 2 firefox.exe processes remain, every single time,
and so either I have to kill them manually, or wait for the Crash Reporter and have them terminated automatically.  

What I did was restore my Firefox profile from yesterday (having GM 3.11)
and disabled automatic updating for GM.
       
I understand that this probably  is a Firefox bug and not caused by GM,
nevertheless I wanted to report this to you.
I've also posted a link to this issue to the bugzilla bug.

PS. I couldn't recreate it in a fresh profile.
But, in my normal profile, even after disabling all other installed extensions
(AdBlock Plus, EHE for ABP, NoScript, RES Suite, Stylish)
the issue remains (the 2 firefox.exe processes are not closed)

**Comment by frankhalligan** [comment]
Same issue here. Just to add, my "fix" was to do an install of 3.11 directly over 3.12, no need to restore an older profile

**Comment by NellePfannerstill72** [comment]
I have same issue. I installed Greasemonkey 4 from dev channel and it showed only couple of installed scripts. Maybe 3.12 version has problem with migrating scripts to new storage and that causes breakage? I have about 20 scripts installed with some disabled.

**Comment by NellePfannerstill72** [comment]
More people are affected: https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/reviews/

**Comment by fireattack** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1402201

**Comment by jerone** [comment]
Confirmed!
Restarting FF doesn't work anymore; it idles with minimal memory forever.
With GM disabled, FF cleanly restarts again.

_Windows 10 64-bit_
_FF 55.0.3 64-bit_
_GM 3.13_

**Comment by NellePfannerstill72** [comment]
It would be nice to at least revert changes from 3.12 otherwise people are going to destroy this great addon in reviews.

**Comment by darkred** [comment]
@arantius, maybe you wanted to close #2579 instead of this?

**Comment by arantius** [comment]
Yep!

**Comment by fireattack** [comment]
None seemed to mention it here, but it will only do so with certain scripts.

In all 30+ scripts I have, only [this one](https://sleazyfork.org/en/scripts/3575-better-better-booru) causes this shut down hang problem.

**Comment by mooms06** [comment]
+1 to fireattack, I have a dozen script installed, and only one is causing the issue: [Dealabs Compagon](https://greasyfork.org/fr/scripts/21921-dealabs-compagnon).
It seems it's a specific (uncommon?) function that's causing the issue.

**Comment by NellePfannerstill72** [comment]
In my case troublemaker script was https://greasyfork.org/en/scripts/6456-install-user-script
This was also my only script with` // @run-at       document-end` which is also the case with two scripts posted above? Coincidence?

**Comment by fireattack** [comment]
I have other scripts that have `// @run-at       document-end` that didn't cause problem, though.

It could still be a requirement, just not sufficiency.

**Comment by PHIL-IP** [comment]
I have try with all my script disable and the problem is the same for me under FF 55.0.3 and Windows 10 (64) multiprocess is disable for me.

**Comment by fireattack** [comment]
You need to *remove* problematic scripts, not just disabled, to fix it

**Comment by fdellwing** [comment]
I do not have that problem with my scripts. So I can confirm, it is only a problem with some scripts.

**Comment by killerz298** [comment]
I reverted to 3.11 while I wait for a fix. Hopefully we don't have to wait for the new extension.

**Comment by arantius** [comment]
Both of the scripts linked above use a `data:` URL for their `@icon`.  I've got a workaround prepared which causes the crash not to happen (I think..), but also want to make it really work, which it probably doesn't today.

**Comment by jerone** [comment]
[**@arantius**](https://github.com/arantius) commented on [Sep 25, 2017, 5:59 PM GMT+2](https://github.com/greasemonkey/greasemonkey/issues/2573#issuecomment-331927903 "2017-09-25T15:59:09Z - Replied by Github Reply Comments"):
> Both of the scripts linked above use a `data:` URL for their `@icon`. 

I can confirm that I have at least [one](https://github.com/jesus2099/konami-command/blob/master/INSTALL-USER-SCRIPT.user.js) script that uses an `data:` URL for their `@icon`.

**Comment by arantius** [comment]
Above few commits should resolve this.

**Comment by jerone** [comment]
[**@arantius**](https://github.com/arantius) commented on [Sep 25, 2017, 8:44 PM GMT+2](https://github.com/greasemonkey/greasemonkey/issues/2573#issuecomment-331975433 "2017-09-25T18:44:32Z - Replied by Github Reply Comments"):
> Above few commits should resolve this.

I can confirm ✔️  that v3.14 allows restarts of FF again. 🎉
