### ISSUE TITLE
Provide polyfill to migrate from old API

### ISSUE THREAD

**Issue by eight04** [greasemonkey/greasemonkey#2578]
Since all APIs become async in Greasemonkey 4, I think it worth providing a polyfill which wraps old API (`GM_getValue`, `GM_setValue`, etc) into Promises. So script authors can write the script in Promise-based API but also support old environment (Tampermonkey/Violentmonkey/Greasemonkey 3).
```js
// ==UserScript==
// @name test
// @namespace test.com
// @include *
// @grant GM_getValue
// @grant GM.getValue
// @require GM_polyfill.js
// ==/UserScript==

GM.getValue("myValue").then(console.log);
```
GM_polyfill.js:
```js
if (typeof GM === "undefined") {
	var GM = (function(GM){
		GM.getValue = function() {
			return Promise.resolve(GM_getValue.apply(null, arguments));
		};
		// and other APIs...
	})({});
}
```
This should help moving from old API to the new one.

I know this can be done by script authors, but I think it would be best if Greasemonkey can make an official one just like [webextension-polyfill](https://github.com/mozilla/webextension-polyfill).

**Comment by mikhoul** [comment]
I agree 500% on this one, it will help to keep available and compatible all the Userscripts available easily for the end user and at the same time developers will be able to take advantage of the new async  API.

It will keep everything going lot more smoothly for everybody (users and devs).

**Comment by arantius** [comment]
Intended to be a part of #2559 .
