### ISSUE TITLE
pages not rendering with userscript on first time open

### ISSUE THREAD

**Issue by Owyn** [greasemonkey/greasemonkey#2583]
If you click a link\write address manually - page won't load at all - previous page would still be rendered in firefox, but reloading page or opening it again anyhow would make it work (but only for that page), opening incognito mode clears working pages list and all would be not loading again.

userscript: https://greasyfork.org/scripts/110-center-image/code/Center%20Image.user.js

example pages: 

https://68.media.tumblr.com/a0534d20a6e15509adfcdc76224dcee5/tumblr_oweeno7Zjt1w8bgs7o1_1280.jpg 

https://68.media.tumblr.com/f1b6a491c834fc6985f60f2eb3cb775d/tumblr_oweeno7Zjt1w8bgs7o2_1280.jpg

https://68.media.tumblr.com/e8b59c15313812eb6bc3a54467e43fa7/tumblr_ovvj5goZRz1w8bgs7o1_1280.jpg

FF 55
GM 3.13

Worked fine before (FF updated or GM, no idea)

**Comment by arantius** [comment]
#2524
