### ISSUE TITLE
Search does not work (completely) in the editor

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2588]
1. Install https://greasyfork.org/en/scripts/404-mouseover-popup-image-viewer
2. Open the script editor
3. Ctrl-F register

You'll find the `@grant` line, but never the usage.

Possibly: https://github.com/codemirror/CodeMirror/issues/4491

**Comment by Sxderp** [comment]
I noticed this but never filed an issue. If I'm remembering my tests correctly, if you scroll to the bottom and then back you should hit all the references. I can't retest at the moment, on my phone.
