### ISSUE TITLE
4.x no way to view source on install dialog

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2589]
In 3.x versions there was a button that could be pressed to view the source of the user script before installing. There is nothing for the 4.x dialog box. 

I have some code that fetches and views the source but I haven't published it yet. I'm not sure if it should be behind a button like 3.x or if it should show the source unconditionally on the install page. 

The code is fetched using an async xhr. The additional network request is pretty much the only reason I'd consider having it behind a button rather than unconditionally shown. 

I had debated on, before redirecting to the install dialog page, passing the source to a background script and then fetching it in the install dialog content script. But that seemed like a lot of work to avoid one network request.

**Comment by arantius** [comment]
See #2567

**Comment by fdellwing** [comment]
#2567 is not even close to be the same functionality:

Give the following situation:

You have a userscript installed, you change something or the author of the script changes something. In 3.x you just pressed "view sourcecode" and could diff or look at the changelog. Now you need to open your version, copy it to an external programm, install the new version and than inspect it.

I'm not a fan of this at all.

**Comment by arantius** [comment]
Ah, you didn't quite explain yourself above.  So you're imagining:

1. Install script
2. Time passes
3. Server side copy of script changes
4. Manually install the script again

And at this point you want to review the source?

If so, short answer is my plans for the (near?) future would make this trivially easy but short term issues have forced me to delay that.  Including https://bugzilla.mozilla.org/show_bug.cgi?id=1402110

**Comment by fdellwing** [comment]
I would like to see the script at your point 3. Without installing it again.

**Comment by arantius** [comment]
Yes, you can press cancel at step 4 if you want, but you have to select the script somehow.

**Comment by Sxderp** [comment]
My use case was more in line with initial install. However, I didn't think of the [use case](https://github.com/greasemonkey/greasemonkey/issues/2589#issuecomment-332259997) that @arantius pointed out. Mostly because 90%+ of my scripts are self-written and the few that aren't don't have auto-update.

However, I would like to point out that #2567 is somewhat inconvenient in my initial use case. While the suggested feature 'solves' the problem it does so in a roundabout manner, with additional user action required.

**Comment by arantius** [comment]
But it makes it equally practical to evaluate the whole script: resources, requires, and all.
