### ISSUE TITLE
Cannot create new scripts

### ISSUE THREAD

**Issue by rol09003** [greasemonkey/greasemonkey#2596]
The new version of GreaseMonkey won't let me create a new script. It sends me to the new script prompt, but when I fill in the fields, and click "OK" it just sits there, and doesn't add a new script. I have checked the manage script section. I am also running GreaseMonkey 3.15, and Firefox 56.0 (32bit). Is there a fix for this in the works?

**Comment by arantius** [comment]
How embarrassing.  In a rush, I didn't test well and broke all script installs.

**Comment by jmichaelrollins89** [comment]
No worries. I depend on GreaseMonkey for work, so I just wanted to see if it was my system, or something else. Thanks for looking into it so quickly. Do we know when to expect a fix?

**Comment by arantius** [comment]
bf8ab30b3c88281639a393d354e1508849bd8e3e
