### ISSUE TITLE
scripts won't enable/disable until restart firefox

### ISSUE THREAD

**Issue by idxlics** [greasemonkey/greasemonkey#2597]
firefox 56.0 + greasemonkey 3.15
two problems:
1. After updated to 3.15, when I click the script enable/disable button, the button remains the same state. For example, I click the enable button, and there is still a enable button, until I switch to another tab on the left in the addons menu then switch back to user scripts tab.

2. Then I found that although I enable/disable a script and it does show that the script has been enabled/disabled, the script remains its previous state until I restart firefox. For example, I enable a script, but the script keeps disabled until restart firefox, or I disable a script, but the script keeps enabled until restart firefox.

**Comment by Sxderp** [comment]
This was closed. Why? Did you find a solution? Let people know.
