### ISSUE TITLE
Greasemonkey 4.x does not work when cookies are disabled

### ISSUE THREAD

**Issue by mazesy** [greasemonkey/greasemonkey#2598]
Greasemonkey 3.16 / Waterfox 55.1.0.1 (=Firefox 55.0.3) / Windows 7 x64

I'm facing the same issue with Greasemonkey 3.16 as I did with uBO either migration either Webextension.

Greasemonkey 3.16 runs fine, it has added in my profile's _gm_scripts_ sub-folder .db files corresponding to the folders containing my css files: OK

If I install GM3.16 with` network.cookie.cookieBehavior` = 0 or 1 (allow all/allow same host) then GM 3.16 will install its subfolder in my profile's _storage_  folder (IndexedDB)

If I install GM 3.16 with network.cookie.`cookieBehavior` = 2 (all cookies disallowed) then GM 3.16 will **not** install its subfolder in my profile's _storage_ storage folder (IndexedDB)

This seems a common issue to all Webextensions using IndexedDB (so sorry for pointing this as GM specific). At this time I'm running ubO's legacy version. 

I'd wish to know concerning Greasemonkey if I'd rather continue using latest non-migration total legacy version 3.11 (until IndexedDB gets fixed) or stick on latest 3.16 migration version considering it is not dispatched in the _storage_ folder when cookies are set to be all disallowed.

**Comment by arantius** [comment]
The only differences since 3.11 is for migration to webextensions.  All recent development is for being Firefox 57+ compatible.

Sounds like a bug that cookieBehavior breaks extensions, but in Firefox -- I can't help with that.

**Comment by Thorin-Oakenpants** [comment]
@mazesy see https://github.com/ghacksuserjs/ghacks-user.js/issues/250

Cookies control access to local dom and to IDB (and maybe chrome workers cache etc). Web extensions that use local dom storage and/or IDB need a cookie exception added against the UUID, even if it doesn't use or set a cookie. The UUID will differ for each user

Mozilla needs to fix moz-extensions and internals (eg see console errors with `...profile\storage\permanent` when IDB is disabled) so they are separate from content.

**Comment by mazesy** [comment]
`Web extensions that use local dom storage and/or IDB need a cookie exception added against the UUID`

I know how to set cookie exceptions for sites but how to set a cookie exception for a Webextension? I had that in mind but as a concept because I really don't see how to set such cookie exceptions.

`Mozilla needs to fix moz-extensions and internals`

Indeed. It's been said, it's even written in your Pants' Ghacks user.js file:
```
/* 2701: disable cookies on all sites [SETUP]
 * You can set exceptions under site permissions or use an extension
 * 0=allow all 1=allow same host 2=disallow all 3=allow 3rd party if it already set a cookie
 * [SETTING] Options>Privacy>History>Custom Settings>Accept cookies from sites
 * [NOTE] This also controls access to 3rd party Web Storage, IndexedDB, Cache API and Service Worker Cache
 * [1] https://www.fxsitecompat.com/en-CA/docs/2015/web-storage-indexeddb-cache-api-now-obey-third-party-cookies-preference/ ***/
// user_pref("network.cookie.cookieBehavior", 2);
```
**This also controls access to 3rd party Web Storage, IndexedDB, Cache API and Service Worker Cache**

That is the whole problem. I linger to understand the power of cookies in the Firefox scheme. I cannot imagine this is deliberate and do hope this will be fixed in Firefox 57. Cookies may be set to blocked, there is no reason for this to interfere with Webextensions (those that use IndexedDB) install/process.

At this time, considering I have set cookies to be blocked I:
- run uBO in latest legacy add-on version (fortunately Gorhill provides both legacy & Webextension);
- run outdated Greasemonkey (legacy);
- run outdated Viewhance (legacy).
All other Webextensions that do not rely on IndexedDB pose not one problem.

So, please Mozilla, consider the Webextensions requiring IndexedDB as a major issue and focus on that.

**Comment by Luke-Baker** [comment]
[1406675](https://bugzilla.mozilla.org/show_bug.cgi?id=1406675) - WebExtension cannot use IndexedDB at all if "Accept cookies from websites" is disabled
> That's highly unlikely given the time and people we have available to do it and the high bar that is being set for 57 uplifts at this point. Perhaps someone else has the knowledge, skills and time to move quickly on it.

**Comment by arantius** [comment]
Reopen because this is not just migration, this is all of the (web) extension not working.

**Comment by arantius** [comment]
The Firefox 59 announcement says this is fixed:

https://blog.mozilla.org/addons/2018/01/26/extensions-firefox-59/
