### ISSUE TITLE
Script settings not migrated correctly

### ISSUE THREAD

**Issue by ccd0** [greasemonkey/greasemonkey#2600]
If you do `GM_setValue("key", "string")` in Greasemonkey 3.16, then install GM 4.0alpha4 and read the data, you get not `"string"` as expected but `"\"string\""`.

I tested with this script
https://pastebin.com/dG4Vzq9x
in Debian's build of Firefox 56.0.

Clicking the set button in Greasemonkey 3.16 and then the get button gives this in the console, as expected:
```
true "string" "string"  Settings_migration_test.user.js:38:3
true 42 42  Settings_migration_test.user.js:38:3
true false false  Settings_migration_test.user.js:38:3
true "\"string\"" "\"string\""  Settings_migration_test.user.js:38:3
true "42" "42"  Settings_migration_test.user.js:38:3
true "false" "false"  Settings_migration_test.user.js:38:3
true "42.5" "42.5"  Settings_migration_test.user.js:38:3
true "{\"key\":\"val\"}" "{\"key\":\"val\"}"  Settings_migration_test.user.js:38:3
true "[\"item\"]" "[\"item\"]"  Settings_migration_test.user.js:38:3
true "null" "null"  Settings_migration_test.user.js:38:3
```

After installing Greasemonkey 4.0alpha4 and pressing the get button:
```
false "string" "\"string\""  Settings%20migration%20test:380:3
false 42 "42"  Settings%20migration%20test:380:3
false false "false"  Settings%20migration%20test:380:3
false "\"string\"" "\"\\\"string\\\"\""  Settings%20migration%20test:380:3
false "42" "\"42\""  Settings%20migration%20test:380:3
false "false" "\"false\""  Settings%20migration%20test:380:3
false "42.5" "\"42.5\""  Settings%20migration%20test:380:3
false "{\"key\":\"val\"}" "\"{\\\"key\\\":\\\"val\\\"}\""  Settings%20migration%20test:380:3
false "[\"item\"]" "\"[\\\"item\\\"]\""  Settings%20migration%20test:380:3
true "null" "null"  Settings%20migration%20test:380:3
```

Setting the values in Greasemonkey 4.0alpha4 causes them to be fetched correctly, so this is only a migration problem:
```
true "string" "string"  Settings%20migration%20test:380:3
true 42 42  Settings%20migration%20test:380:3
true false false  Settings%20migration%20test:380:3
true "\"string\"" "\"string\""  Settings%20migration%20test:380:3
true "42" "42"  Settings%20migration%20test:380:3
true "false" "false"  Settings%20migration%20test:380:3
true "42.5" "42.5"  Settings%20migration%20test:380:3
true "{\"key\":\"val\"}" "{\"key\":\"val\"}"  Settings%20migration%20test:380:3
true "[\"item\"]" "[\"item\"]"  Settings%20migration%20test:380:3
true "null" "null"  Settings%20migration%20test:380:3
```

**Comment by Sxderp** [comment]
I think I know the problem. I haven't tested it though. The migration script uses the GM_ScriptStorageBack class to directly fetch the values. However, in scripts there's [additional parsing](https://github.com/arantius/greasemonkey/blob/3.x/modules/storageFront.js#L62-L68) done by the GM_ScriptStorageFront class. Therefore the processed (for storage) value is migrated, rather than the unprocessed raw value.

The solution is probably duplicate the parsing in the migration or use the GM_ScriptStorageFront to do the migration.

**Comment by arantius** [comment]
Will need to fix, as per pull request, and also make sure to overwrite existing badly migrated values.
