### ISSUE TITLE
Upgrade from 3.15 to 3.16 makes script very slow

### ISSUE THREAD

**Issue by LoveIsGrief** [greasemonkey/greasemonkey#2602]
Hello,

I have a [custom script](https://gist.github.com/anonymous/f463ba1f2e559ba9b8d95862cf768681) that helps me on reddit and in version 3.15 it runs barely using any resources, but in 3.16 it suddenly slows the whole page down to 0.5 fps.

[This seems to be the only change](https://github.com/greasemonkey/greasemonkey/compare/3.15...3.16) between the versions, but it significantly slowed down the script.

```
$ firefox --version
Mozilla Firefox 55.0.2

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

$ uname -a
Linux loneliverse 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ccd0** [comment]
Based on sticking a `dump` statement after the `this._convertScriptToWebext(script);` line, the code in
https://github.com/greasemonkey/greasemonkey/compare/3.15...3.16
seems to be running after every call to GM_setValue, which I don't think was intended since there's already a line here
https://github.com/greasemonkey/greasemonkey/blob/3.16/modules/storageBack.js#L84
that migrates just the one setting being changed.

**Comment by Sxderp** [comment]
@LoveIsGrief, you think you could check out my [branch](https://github.com/Sxderp/greasemonkey/tree/prevent-double-migrate-value) and see if that fixes it for you. Also, thanks to @ccd0 for pointing this issue out.

**Comment by LoveIsGrief** [comment]
@Sxderp I haven't migrated my script to 4.0 yet ☹️  Can't test it.

**Comment by fdellwing** [comment]
Can confirm, that something in 3.14+ is making the getter and setter calls really slow.

**Comment by arantius** [comment]
Please try, and let me know if it helps:

https://addons.mozilla.org/firefox/downloads/file/735451/greasemonkey-3.17beta1-fx.xpi

**Comment by ccd0** [comment]
It fixes the slowdown I was seeing in my script; thanks.

**Comment by fdellwing** [comment]
Works.
