### ISSUE TITLE
Wildcard protocol in @match causes exception to be thrown

### ISSUE THREAD

**Issue by ccd0** [greasemonkey/greasemonkey#2605]
This is with Greasemonkey 4.0alpha5.

Test script:
```
// ==UserScript==
// @name        Match Test
// @namespace   test
// @match       *://example.com/*
// @grant       none
// ==/UserScript==
 
console.log('working');
```

Attempting to install gives the error:
`Error: Ignoring @match pattern *://example.com/* because:
Error: @match: Invalid protocol specified.  parse-user-script.js:105:15`

I tried editing the above to `http://example.com/*` so it can be installed, then changing back to `*` in the internal editor, but the change seems to be ignored, with the script continuing to run only on http://example.com/ and not on https://example.com/. But I have several already installed scripts throwing exceptions like the following:
```
Failed checking whether [Greasemonkey Script redacted/redacted; 1] runs at "http://example.com/" : Error: @match: Invalid protocol specified.
Stack trace:
MatchPattern@moz-extension://cc378fe9-abb7-4288-ba89-75a43a8f29cf/src/third-party/MatchPattern.js:72:11
_testMatch@moz-extension://cc378fe9-abb7-4288-ba89-75a43a8f29cf/src/user-script-obj.js:28:20
runsAt@moz-extension://cc378fe9-abb7-4288-ba89-75a43a8f29cf/src/user-script-obj.js:138:11
scriptsToRunAt@moz-extension://cc378fe9-abb7-4288-ba89-75a43a8f29cf/src/bg/user-script-registry.js:233:19
@moz-extension://cc378fe9-abb7-4288-ba89-75a43a8f29cf/src/bg/execute.js:16:3
  user-script-registry.js:236:7
```

**Comment by Sxderp** [comment]
There's something wrong with the MatchPattern .js file. 'What' depends on what you're looking at. But for simplicity.

```javascript
var REG_PARTS = new RegExp('^([a-z*]+:)//([^/]+)(?:(/.*))$');
var pattern = '*://example.com/*'
var m = pattern.match(REG_PARTS);
console.log(m)
#[ '*://example.com/*',
#  '*:',
#  'example.com',
#  '/*',
#  index: 0,
#  input: '*://example.com/*' ]
```

If you look at m[1] (the protocol match portion) and then [these lines](https://github.com/greasemonkey/greasemonkey/blob/c2874104d94e0cb2df5633ddb29b8dae55cb18d0/src/third-party/MatchPattern.js#L71-L73), the wildcard check isn't working properly. The regex find `*:` as the protocol.

**Comment by GuardianMajor** [comment]
I don't like it and do it for sake of functionality but I have been using `@include` instead of `@match` and the wildcard patters hold there, so in the meantime you can try that until it gets resolved. I have had to do that for a few of our scripts until the `@match` becomes more reliable and stable, and it has been working just fine without much issues, so that's an option as a workaround for now.

Also, try `http*://example.com/*` and see if that helps, there was a time that was a workaround, not sure if it still is or not for retaining `@match` over using `@include` - good luck.

**Comment by GuardianMajor** [comment]
@arantius nice patch, that should do it, thank you. Will run some tests on it and let you know if anything.
