### ISSUE TITLE
Request: XUL branch

### ISSUE THREAD

**Issue by hook54321a** [greasemonkey/greasemonkey#2606]
I think that there should be an XUL branch, for reference, potential critical security fixes, and possibly for fixes that people happen to submit pull requests to. I'm assuming that at some point it will stop working in browsers that still use XUL based extensions, right before that point the branch should be made.

**Comment by Sxderp** [comment]
There's the 3.x branch? Isn't that what you'd be looking for?

**Comment by arantius** [comment]
https://github.com/greasemonkey/greasemonkey/tree/3.x
