### ISSUE TITLE
Cancelable GM.xmlHttpRequest

### ISSUE THREAD

**Issue by Y0ba** [greasemonkey/greasemonkey#2607]
Currently GM.xmlHttpRequest cannot be canceled.

Since GM.xhr now is async maybe it's better to use [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) for that in FF57+?

**Comment by fdellwing** [comment]
What do you mean with "cannot be canceled"? An AJAX call can never be canceled. If you want to make sure, it does not run forever, give it a timeout.

**Comment by Y0ba** [comment]
It can. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort

**Comment by 7nik** [comment]
GM.xmlHttpRequest supports `onabort` listener but doesn't allow to `abort` the request. L - logic.
