### ISSUE TITLE
Highlight metadata tokens in the editor

### ISSUE THREAD

**Issue by badbrainz** [greasemonkey/greasemonkey#2615]
A custom codemirror mode could help users spot errors such as unknown keywords and invalid values (e.g. a deprecated grant).

see my branch 39a6bdd1f614faf8e179662bd0a0c0a6b1bafab4

![screenshot](https://user-images.githubusercontent.com/10160581/31553986-fee102fc-aff0-11e7-8fbc-a61d4718244b.png)

**Comment by arantius** [comment]
Hm.  Just because Greasemonkey doesn't use it, this doesn't mean nothing else does.  I feel like we'd get complaints if we add this, but don't track every valid-for-any-reason key that everything uses for all time.
