### ISSUE TITLE
Add code snippets to the editor

### ISSUE THREAD

**Issue by badbrainz** [greasemonkey/greasemonkey#2616]
How about a snippets hint addon?

see my branch b633ccae6c26525b4f7e80f7fda958bbdc9be673

**Comment by q700611** [comment]
https://github.com/greasemonkey/greasemonkey/commit/b633ccae6c26525b4f7e80f7fda958bbdc9be673

**Comment by arantius** [comment]
I'm uneasy about this.  Maybe far down the line a way for the user to register their own snippets?  But (for example) I've got issues with the particular content of some of the snippets you've chosen to list.
