### ISSUE TITLE
Help users debug invalid metadata

### ISSUE THREAD

**Issue by badbrainz** [greasemonkey/greasemonkey#2617]
Greasemonkey already has a parser for this. The errors could be sent to the codemirror lint addon to produce gutter/text markers.

see this branch aee6329bb7ac184d85fff29a3ee3c0e514eceea7

![lint](https://user-images.githubusercontent.com/10160581/31572979-13d7ca1c-b067-11e7-9b8d-5e56adc5280c.png)

**Comment by arantius** [comment]
Merged: aee6329bb7ac184d85fff29a3ee3c0e514eceea7
