### ISSUE TITLE
Help users autocomplete metadata keys/values

### ISSUE THREAD

**Issue by badbrainz** [greasemonkey/greasemonkey#2619]
With a few modifications to codemirror's hint addon, an extra div can be displayed next to the popup containing a description and perhaps a "more..." link to the greasespot wiki.

see this branch c6f24935ebdeff255c5f1acff1a90c80a5e4679f

![metahint](https://user-images.githubusercontent.com/10160581/31697451-7678580a-b36c-11e7-9a98-cbfe38551028.png)

**Comment by Sxderp** [comment]
I like the look of the modifications you've made (in other issues too). Though, I haven't had a chance to test them out personally. 
Also, why don't you make standard pull requests rather than opening issues?

**Comment by arantius** [comment]
Agreed.  A commit is not a branch, and an issue is not a pull request.

Great work, but just a little more would make it even easier to incorporate it.

**Comment by badbrainz** [comment]
Sorry. I'm still getting used to github AND git. I'll try again.

**Comment by arantius** [comment]
No worries!  I realized that you did indeed make branches for these, and just link to commits.  So I've already merged a couple of the ones I completely agree with.  And plan to look into the rest.
