### ISSUE TITLE
tabs is not defined in edit-user-script:addRequireTab()

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2621]
[Here](https://github.com/greasemonkey/greasemonkey/blob/029d1e595c0f0e1a4e10acbe95b186be9690d5ae/src/content/edit-user-script.js#L29) the `tabs` variable  is never declared in the global scope nor in the function. This does not cause any errors. Most likely due to an obscure _feature_ which [adds element IDs](https://stackoverflow.com/questions/7114956/automatically-created-variables-from-ids-in-js) to the global scope.

For completeness, and sanity, I suggest either:
1. add `let tabs = document.getElementById('tabs');` to `addRequireTab()`
2. add `const tabs = document.getElementById('tabs');` to the global scope and adjust [this line](https://github.com/greasemonkey/greasemonkey/blob/029d1e595c0f0e1a4e10acbe95b186be9690d5ae/src/content/edit-user-script.js#L45) (remove it) and [this line](https://github.com/greasemonkey/greasemonkey/blob/029d1e595c0f0e1a4e10acbe95b186be9690d5ae/src/content/edit-user-script.js#L94) (change it) as needed.

I wasn't sure what solution to use, in regard to coding style, so I created the issue rather than a pull request with a fix.

**Comment by arantius** [comment]
Indeed, this was copy/pasted from very similar code a few lines down, where `tabs` is set explicitly beforehand.  Either solution would be good, I'd probably prefer #2.
