### ISSUE TITLE
Drop GM.xmlHttpRequest

### ISSUE THREAD

**Issue by KOLANICH** [greasemonkey/greasemonkey#2622]
It is an old API. Instead of plugging promises there we should just state that users should use Fetch instead.

**Comment by damoclark** [comment]
Hey @KOLANICH ,

According to the [Google Developer website](https://developers.google.com/web/ilt/pwa/working-with-the-fetch-api#cross-origin_requests):

> Fetch (and XMLHttpRequest) follow the same-origin policy. This means that browsers restrict cross-origin HTTP requests from within scripts. 

This is why GM.xmlHttpRequest exists.  Or are you suggesting to replace xmlHttpRequest with a fetch-compatible API that similarly ignores the same-origin policy?

D.

**Comment by KOLANICH** [comment]
Yes.

**Comment by silverwind** [comment]
I'd like to see a `GM.fetch` method with the same semantics as `window.fetch`, but cross-origin. This issue is mislabled, it's probably out of question to drop `GM.xmlHttpRequest` for compatibilty reasons.

**Comment by KOLANICH** [comment]
>GM.fetch method with the same semantics as window.fetch

Why not to just use window.fetch with some restrictions lifted? This should remove the need to adapt the code for GM, you should be able to use the same code you can use in devtools console in the target website origin.

**Comment by silverwind** [comment]
> Why not to just use window.fetch with some restrictions lifted

If it's possible for a extension to lift the same-origin restriction from `window.fetch`. Might be as simple as wrapping it and adding a `mode: cross-origin` option, which could only be available in GM scripts.

**Comment by KOLANICH** [comment]
>If it's possible for a extension to lift the same-origin restriction from window.fetch, that'd even be nicer. 

Most of js objects are monkey-patcheable and userscripts are meant to be executed in own contexts, so, I guess that `window` of webpage and `window` of userscript are differrent variable bindings.

**Comment by AlttiRi** [comment]
> I'd like to see a `GM.fetch` method with the same semantics as `window.fetch`, but cross-origin. This issue is mislabled, it's probably out of question to drop `GM.xmlHttpRequest` for compatibilty reasons.

I have create an issue that asks exactly for it. _(but in Tampermonkey repo)_
https://github.com/Tampermonkey/tampermonkey/issues/1278

**Comment by arantius** [comment]
The short answer is that we're not going to break existing scripts by removing GM XHR.  Separately, making fetch() work cross-origin might be a valid feature request (but probably on the wrong side of cost/benefit).
