### ISSUE TITLE
Drop GM.{get,set, delete}Value and listValues

### ISSUE THREAD

**Issue by KOLANICH** [greasemonkey/greasemonkey#2623]
Users should use ```storage.*``` from the webext spec instead.

**Comment by arantius** [comment]
Which `*Storage` is (intentionally) available, and cross origin?

**Comment by arantius** [comment]
It is only a mistake, which I'd expect to be patched, that webext APIs are currently available to scripts.

**Comment by KOLANICH** [comment]
@arantius, I mean to make the API compatible. There is a nice thing, Proxy, which can help you to filter the things and put the scripts into own scopes.

**Comment by arantius** [comment]
That would make an easy port of old scripts via e.g. https://arantius.com/misc/greasemonkey/imports/greasemonkey4-polyfill.js into a more difficult action.

**Comment by KOLANICH** [comment]
Can't you write a polifill utilizing the webext API instead of new ```GM.``` one?
