### ISSUE TITLE
Provide unsafeWindow

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2624]
In order to break as few scripts as possible, `unsafeWindow` should at a minimum be an alias for `window`; ideally an actually unsafe window.

**Comment by Sxderp** [comment]
> ideally an actually unsafe window.
That'll be 'fun'. You used to be able to just attach objects to the window using standard properties, now they have to be [cloned into](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Sharing_content_script_objects_with_page_scripts) the context. Are you suggesting creating wrappers for that?
