### ISSUE TITLE
absolute / relative src path inconsistency

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2629]
We have [relative paths](https://github.com/greasemonkey/greasemonkey/blob/1f5992e3c3c66e3a1304daee4310831c3839bc44/src/content/edit-user-script.html#L18-L21).
We have [absolute paths](https://github.com/greasemonkey/greasemonkey/blob/1f5992e3c3c66e3a1304daee4310831c3839bc44/src/content/manage-user-scripts.html#L45-L48).

I'd prefer if everything had absolute paths as I think they look nicer (and easier to keep track of). But either way, they should be consistent.

This also includes lines like [this](https://github.com/greasemonkey/greasemonkey/blob/1f5992e3c3c66e3a1304daee4310831c3839bc44/src/content/manage-user-scripts.html#L49) (same directory no `./`) and [this](https://github.com/greasemonkey/greasemonkey/blob/1f5992e3c3c66e3a1304daee4310831c3839bc44/src/content/edit-user-script.html#L27) (same directory has `./`). I'd say either put the full path here or remove the `./`.

Of course this doesn't just apply to `<script>` tags but all resources.

**Comment by Sxderp** [comment]
@aratius, you added this to a milestone but never commented on what styling would be preferred.

**Comment by arantius** [comment]
Yes, my thoughts are complex.

I actually don't think a simple "consistency" is the best thing.  I see value in e.g. the `install-dialog.html` file having a script that just says `src="install-dialog.js"`.

**Comment by Sxderp** [comment]
About about, if you have to travel up, give full path. If you stay in the same directory, or travel down, give relative path without `./`

**Comment by arantius** [comment]
Hopefully I haven't missed any.  I decided to go with always explicitly absolute (starts "/") or explicitly relative (starts ".").
