### ISSUE TITLE
Firefox for Android compatibility

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2632]
Today it's possible to install Greasemonkey 4.0 in Firefox for Android.  Adopt this as a supported platform and make sure all intended features work.  Currently known issues:

* The install dialog appearance is suboptimal for moble.
* The browser action dialog doesn't open.

**Comment by arantius** [comment]
For future reference: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Developing_WebExtensions_for_Firefox_for_Android

**Comment by Sxderp** [comment]
Also of value:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Differences_between_desktop_and_Android

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by Sxderp** [comment]
I haven't been able to find any information on whether a WebExtension can detect if it's installed on a mobile platform. This could be useful for Greasemonkey, but I think it'd be more useful to pass this information into the userscript scope, assuming it's available.

**Comment by IlBaffo** [comment]
Is this still relevant?
I cannot install on 57.0.4.
![screenshot_20180111-205018](https://user-images.githubusercontent.com/7044910/34844494-f6cdff9e-f711-11e7-818d-631bd036a37c.png)

**Comment by Sxderp** [comment]
There are still a bunch of things that could be done in terms of Android compatibility (like making the monkey menu font sizes 10x larger, or set some kind of scaling.. I don't know the details, but the text is very small).

As for not being able to install, I don't know about that. I've installed it directly using `.xpi` files. So I'm not sure about any AMO flags.

**Comment by arantius** [comment]
Stable releases are marked not compatible.  Try beta if you're into experimentation.

**Comment by davidhedlund** [comment]
Thank you for your effort to make GM Android compatible. Unfortunately I cannot install GM 4.1 on Firefox for Android 57.0.4

![screenshot_2018-01-16-21-26-06](https://user-images.githubusercontent.com/6416073/35011477-859fd100-fb06-11e7-91e8-0c9414518a0c.png)

**Comment by Sxderp** [comment]
@davidhedlund see post by arantius right above yours.

**Comment by davidhedlund** [comment]
@Sxderp Sorry.

**Comment by davidhedlund** [comment]
@Sxderp How do I install beta then? I don't find the work "beta" at https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/

**Comment by davidhedlund** [comment]
@arantius @Sxderp How do I install the beta version of GM? I don't find the word "beta" at https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/

**Comment by IlBaffo** [comment]
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta

**Comment by davidhedlund** [comment]
@IlBaffo Thanks.

**Comment by arantius** [comment]
I'm gonna mark this as closed, support isn't great (and there's issues for improving it) but you can indeed install Greasemonkey and scripts and get basic management done.
