### ISSUE TITLE
User Script Management empty

### ISSUE THREAD

**Issue by lucaswerkmeister** [greasemonkey/greasemonkey#2633]
I hope I’m not just being stupid, but I can’t figure out how to add user scripts in the WebExtension version of GreaseMonkey. Here’s a full screenshot of the “Manage User Scripts” page (Dev Tools, right click the root `<html>` element, Screenshot Node):
![screen shot 2017-10-26 at 16 14 03](https://user-images.githubusercontent.com/2346599/32057893-d76760cc-ba68-11e7-9e20-c87d63df65bc.png)

There’s no UI that I can see to add user scripts. There are no errors in the Web Console (other than “Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.”) or in the Browser Console.

I assume there must be some bug that’s preventing the Manage User Scripts page from being properly populated?

GreaseMonkey version: 4.0alpha10  
Firefox version: 57.0b11
OS: Ubuntu 17.04

**Comment by arantius** [comment]
> There’s no UI that I can see to add user scripts. 

Just click on a link to a script.  For now ( #2612 ) only on the internet.

**Comment by lucaswerkmeister** [comment]
Does the link target need to send a JS content type or something? I still can’t figure out how to use a script hosted on gist.github.com (the Raw link just shows me the plain code, as the response is `Content-Type: text/plain`).

**Comment by arantius** [comment]
There's also #2631 sadly.
