### ISSUE TITLE
Install dialog should allow viewing the source of the file

### ISSUE THREAD

**Issue by salty-horse** [greasemonkey/greasemonkey#2644]
The GM4 install dialog takes over when loading a *.user.js URL, and offers very user-friendly information about what's being installed.
There's no easy way to to view the source of the file before installing - I had to resort to external tools.

The install dialog should include the full source code, perhaps hidden behind a button click.

**Comment by Sxderp** [comment]
See #2589 
I suppose if there's enough concern @arantius may change his viewpoint on the issue.

**Comment by salty-horse** [comment]
Thanks. I think I missed it because I only searched for open bugs. Feel free to close this as a duplicate.

My specific use-case isn't mentioned, though. I sometimes genuinely want to read the script I browsed to, without any intention of installing it. The current behavior doesn't allow it.

**Comment by arantius** [comment]
Yes I still intend #2567 to fill this need, giving you the ability to view the script and all requires (not to mention resources) before you run it.
