### ISSUE TITLE
Fetch does not work with relative URLs

### ISSUE THREAD

**Issue by Brcrwilliams** [greasemonkey/greasemonkey#2647]
When attempting to use Fetch with a relative URL, an error occurs. Take the following example script:

```
// ==UserScript==
// @name         Fetch Test
// @namespace    foo
// @version      0.1
// @description  Test
// @author       Brian Williams
// @match        https://github.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    fetch('/greasemonkey/greasemonkey/wiki').then(res => res.text()).then(body => console.log(body));
})();
```

Observed behavior: The following error occurs: `TypeError: /greasemonkey/greasemonkey/wiki is not a valid URL.`

Expected behavior: A request is made to https://github.com/greasemonkey/greasemonkey/wiki and the response body is logged to console. Fetch _does_ behave this way when used in a normal web page script and also when used in Tampermonkey.

**Comment by Sxderp** [comment]
Sounds like a bug with fetch and WebExtension content scripts. Does Tampermonkey work on the Chrome version (where most people use it) or on the Firefox version?

I can't find anything specific on bugzilla but then I'm horrendous at searching it.

**Comment by Brcrwilliams** [comment]
@Sxderp based on my testing, Tampermonkey works on both Firefox and Chrome.

**Comment by arantius** [comment]
I expect this is blocked by #2549 .

**Comment by Sxderp** [comment]
Ah! There's something. Buried in MDN.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#Content_script_requests_happen_in_the_context_of_extension_not_content_page

So, either get the Mozilla guys to make some kind of workaround (probably very unlikely, considering the effort / gain curves), jerry rig some kind of workaround in GreaseMonkey (assuming TamperMonkey-Firefox works, that's probably what happened there), or ignore it and have everyone use absolute urls.
