### ISSUE TITLE
GMv4 polyfill not returning Promise

### ISSUE THREAD

**Issue by skatsuta** [greasemonkey/greasemonkey#2649]
I'm working on updating my GM scripts to support v4 and using [the polyfill](https://arantius.com/misc/greasemonkey/imports/greasemonkey4-polyfill.js) mentioned in [this blog post](https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html), but new GM APIs do not work correctly.

I found the polyfill does not return `Promise` and so new APIs don't work with `.then()` or `async`/`await` as expected.
I believe here is the fix:
https://arantius.com/misc/greasemonkey/imports/greasemonkey4-polyfill.js
```diff
-    new Promise((resolve, reject) => {
+    return new Promise((resolve, reject) => {
```

Thank you.

**Comment by skatsuta** [comment]
Created a PR greasemonkey/gm4-polyfill#3 to fix this issue.

**Comment by Eselce** [comment]
There is already a bug fix that fixes two bugs

* The missing return statement
* GM.info is an object, not a member function (though it has some)

See:
* damoclark/gm4-polyfill forked from greasemonkey/gm4-polyfill
* damoclark/gm4-polyfill#1 (https://github.com/damoclark/gm4-polyfill/pull/1)
* https://groups.google.com/forum/#!topic/greasemonkey-users/TafDe71sZlw

Waiting for it for some days, but obviously the communication/handling is lacking... ;-(

Please merge and upload THAT bug fix correcting both bugs!

I thought, it would be useless to create an own pull request, as it is known for over a week (Oct 30)

**Comment by skatsuta** [comment]
@Eselce Thank you for letting know this is a know issue! I didn't know that. Closing.
