### ISSUE TITLE
Firefox Nightly 58 - Overflow Menu width

### ISSUE THREAD

**Issue by Acid-Crash** [greasemonkey/greasemonkey#2650]
On latest Firefox Nightly 58 when button is placed inside Overflow Menu there is a graphical bug with menu width.
![gm](https://user-images.githubusercontent.com/32600318/32546511-0ee84e52-c488-11e7-93bd-c5d047dede4b.png)
It looks like menu isn't extending to full container width.

**Comment by Sxderp** [comment]
The menu will somewhat be overhauled per #2639. I figure this will be fixed when those issues are addressed. I want to work on it but have recently been swamped.

**Comment by Sxderp** [comment]
Turns out this was a very simple fix. Submitted a pull for it.

**Comment by SW1FT** [comment]
This issue seems to be back in 4.3beta1.
![overflow](https://user-images.githubusercontent.com/6627739/35471994-82bee718-035e-11e8-8ca0-196321bb0398.png)

**Comment by arantius** [comment]
> This issue seems to be back in 4.3beta1.

See #2816

**Comment by arantius** [comment]
22fa2cda5a6149a9d695606a92302ed840964c21 closed this (but I typoed 2650 instead)
