### ISSUE TITLE
Menu doesn't open (matchPattern.doMatch is not a function)

### ISSUE THREAD

**Issue by McBen** [greasemonkey/greasemonkey#2651]
Greasemonkey 4.1beta2
Firefox 58.0b1 - Linux/Kubuntu

no menu
![image](https://user-images.githubusercontent.com/29117/32602580-de37b332-c546-11e7-846d-73688d23efd1.png)

only on empty tab's menu is shown

**Comment by arantius** [comment]
We'll need more details to do anything.

https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help

Also especially: Does anything show up in the [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) when clicking the button?

**Comment by johnp** [comment]
Browser console output:
```
Error: WebExtension context not found!  ExtensionParent.jsm:829:13
matchPattern.doMatch is not a function  user-script-obj.js:36
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
```

This happens on the latest nightly (f63559d7e6a570e4e73ba367964099394248e18d), Fedora 26 KDE with `layers.acceleration.force-enabled=true` and `layout.display-list.retain=true` with Greasemonkey 4.1beta2.

**Comment by McBen** [comment]
>> matchPattern.doMatch is not a function  user-script-obj.js:36

**Comment by arantius** [comment]
Ok, at a minimum we should be catching and more gracefully handling this failure.  It's definitely `.doMatch` as @McBen points out.  I'm not yet sure how it's happening though.

@johnp Does that line in the console offer a way to expand the error and see the whole trace back?  If so can you copy it here?

**Comment by McBen** [comment]
more details are out of my scope: trying to get a traceback leads me to a "security-error: moz-null is not allowed to load/view user-script-obj"

atleast I can say that most of the scripts I use have a include & match clause like:
```
// @include        https://plus.google.com/circles
// @match        https://plus.google.com/*
```

**Comment by arantius** [comment]
Oh; this may be a migration data bug.  Do you know which scripts you have installed?  Can you re-install each of them?

**Comment by McBen** [comment]
looks like it solved the problem.

I completely removed all scripts and reinstalled a good part of them (10 of 30+)

**Comment by johnp** [comment]
@arantius here's the full trace back:

```
_testMatch moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/user-script-obj.js:36:10
runsAt moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/user-script-obj.js:152:11
loadScripts moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/browser/monkey-menu.js:37:13
<anonymous> moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/browser/monkey-menu.js:54:11
apply self-hosted:4249:5
applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:283:16
wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:452:13
```

I cannot uninstall or install any scripts, if I for example try to install Iridium from [this](https://raw.githubusercontent.com/ParticleCore/Iridium/beta/src/userscript/Iridium.user.js) URL i get this:

```
Failed checking whether [Greasemonkey Script wOxxOm.scripts/GitHub file list beautifier; 3.0.3] runs at "https://raw.githubusercontent.com/ParticleCore/Iridium/beta/src/userscript/Iridium.user.js" : TypeError: matchPattern.doMatch is not a function
Stack trace:
_testMatch@moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/user-script-obj.js:36:10
runsAt@moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/user-script-obj.js:152:11
scriptsToRunAt@moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/user-script-registry.js:232:19
@moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/execute.js:16:3
  user-script-registry.js:235:7
	scriptsToRunAt moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/user-script-registry.js:235:7
	<anonymous> moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/execute.js:16:3
Error: WebExtension context not found!  ExtensionParent.jsm:829:13
Loading failed for the <script> with source “https://cdn.syndication.twimg.com/widgets/timelines/paged/679072730780594176?callback=__twttr.callbacks.tl_i0_679072730780594176_new&dnt=false&domain=www.petri.com&lang=en&since_id=928647925567295490&suppress_response_codes=true&t=1678125&tz=GMT%2B0000”.  installing-wsus-2016:1
Could not execute user script: [Greasemonkey Script AdsBypasser/AdsBypasser; 5.73.0] 
 Error: Missing host permission for the tab  execute.js:29:7
	<anonymous> moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/execute.js:29:7
GET 
https://raw.githubusercontent.com/favicon.ico 
[HTTP/1.1 400 Bad Request 0ms]
```

Furthermore I don't see a Greasemonkey menu in the add-ons manager, but I figured it was removed. Should there be one? Here's the output from the browser console when opening the add-on manager:

```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
	withLastError resource://gre/modules/ExtensionCommon.jsm:407:9
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:460:11
Failed checking whether [Greasemonkey Script wOxxOm.scripts/GitHub file list beautifier; 3.0.3] runs at about:blank : TypeError: matchPattern.doMatch is not a function
Stack trace:
_testMatch@moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/user-script-obj.js:36:10
runsAt@moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/user-script-obj.js:152:11
scriptsToRunAt@moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/user-script-registry.js:232:19
@moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/execute.js:16:3
  user-script-registry.js:235:7
	scriptsToRunAt moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/user-script-registry.js:235:7
	<anonymous> moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/execute.js:16:3
```

Unfortunately I can't recall my full list of userscripts from the top of my head.

**Comment by Sxderp** [comment]
Pushed a branch that at least allows for graceful failure. Doesn't solve the problem, but it might help figure out why a non string non MatchPattern argument is passed into _testMatch.

I'm pretty sure what @arantius said is right. It's some sort of data migration error.

**Comment by johnp** [comment]
Ok, the monkey menu now seems to be working but I still have no script installation support or add-on manager entry. This is the error I get now:
```
matchPattern is not a string nor MatchPattern object: Object { _pattern: "https://github.com/*", _all: false, _scheme: "https", _hostExpr: /^github\.com$/i, _pathExpr: /^\/.*$/i }  user-script-obj.js:36:5
	_testMatch moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/user-script-obj.js:36:5
	runsAt moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/user-script-obj.js:155:11
	scriptsToRunAt moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/user-script-registry.js:231:19
	executeUserscriptOnNavigation moz-extension://9bf950af-5873-43e7-8013-4fb3e7e5e973/src/bg/execute.js:12:3
```

**Comment by arantius** [comment]
When do you get that error?  What are you clicking on/doing at the time?

**Comment by Sxderp** [comment]
MatchPattern objects get saved into the database, right? I think something may have happened during saving to cause an invalid MatchPattern object to be saved?

Perhaps the object shouldn't be saved directly? Recreate the MatchPattern object each time the script is loaded from the database using the array of match patterns?

**Comment by arantius** [comment]
> MatchPattern objects get saved into the database, right?

They shouldn't; I don't think IndexedDB is capable of storing non-primitive types.  The `details` (in this case, strings) should be what's saved.  ( https://github.com/greasemonkey/greasemonkey/blob/8e1e30c515ce31731fe07c209feada06a59daf9b/src/bg/user-script-registry.js#L211-L213 )

There was a temporary bug in 3.12+ that did this by accident.

**Comment by arantius** [comment]
Pull #2744 should address this.

**Comment by arantius** [comment]
Scratch that, #2743 .

**Comment by tukkek** [comment]
I am having a very similar problem on Firefox 52.5.0 on Debian Linux. Menu won't open regardless of being in the toolbar or in the Firefox "Open menu" button. Should I open a new bug?

This completely breaks Greasemonkey since I can't even enable/disable it anymore (short of removing the extension itself) or access any functionality at all.

Console log:

```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. ExtensionCommon.jsm:265
	withLastError resource://gre/modules/ExtensionCommon.jsm:265:9
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:316:11
userScriptsDetail is undefined  monkey-menu.js:34
	loadScripts moz-extension://1b66bdbb-7aea-4eb3-87e5-b163c6371dba/src/browser/monkey-menu.js:34:3
	onLoad/</< moz-extension://1b66bdbb-7aea-4eb3-87e5-b163c6371dba/src/browser/monkey-menu.js:138:11
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:71:14
	runSafeSync resource://gre/modules/ExtensionUtils.jsm:104:37
	runSafe resource://gre/modules/ExtensionCommon.jsm:123:32
	bound runSafe self-hosted:917:17
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:310:31
```

**Comment by arantius** [comment]
Please open a new issue, this is something different.
