### ISSUE TITLE
Active/disabled flag not saved

### ISSUE THREAD

**Issue by McBen** [greasemonkey/greasemonkey#2652]
Greasemonkey 4.1beta2
Firefox 58.0b1 - Linux/Kubuntu

on FF startup GM is always active even if disable in previous session

**Comment by Sxderp** [comment]
After tracing the toggle button through a message and quite a few function calls, we're eventually lead [here](https://github.com/greasemonkey/greasemonkey/blob/c194621bdc89cebbb8bd54ebef807fe5e4cdb9ae/src/bg/is-enabled.js#L26-L29). In which an 'EnabledChanged' message is sent but nothing is listening. So, the setting isn't saved nor is it actually loaded it's currently, from what I can tell, [hard coded as enabled](https://github.com/greasemonkey/greasemonkey/blob/c194621bdc89cebbb8bd54ebef807fe5e4cdb9ae/src/bg/is-enabled.js#L9) on startup.

Looks like this needs to be added as a database entry somewhere so it's saved.

**Comment by arantius** [comment]
Indeed; `setGlobalEnabled()` should be doing some persistence.

The `EnabledChanged` message was an analog from 3.x whereby there were multiple places that it could be changed, so the change was broadcasted to enable all the UIs to update when any one of them was used.  Might be obsolete now.

**Comment by arantius** [comment]
This shouldn't have been closed!

**Comment by arantius** [comment]
This (user scripts execute at full extension-content-script privs) should be temporary, but for now I have to agree.

**Comment by arantius** [comment]
We're already using local storage in one place.  And there's not much a script could do with access to this single value.  So for now, it's easy and we're going there.

**Comment by arantius** [comment]
The above fix has been packaged in a new beta version:
https://addons.mozilla.org/firefox/downloads/file/830369/greasemonkey-4.2beta1-an+fx.xpi?src=devhub

Testing and confirmation would be appreciated!

**Comment by arantius** [comment]
As written this causes Greasemonkey to disable itself upon first launch (because the setting is "enabled", is not present, so is not truthy).  That shouldn't happen.

**Comment by arantius** [comment]
The above fix is packaged in version 4.2beta2:
https://addons.mozilla.org/firefox/downloads/file/833159/greasemonkey-4.2beta2-an+fx.xpi?src=devhub

Testing is always appreciated!

**Comment by arantius** [comment]
Actually I mean b994449c94d71eaf5d33a245043dae4054774bf1 (where I typoed 2562 instead of 2652).
