### ISSUE TITLE
TypeError: GM.xmlHttpRequest is not a function

### ISSUE THREAD

**Issue by jurgenhaas** [greasemonkey/greasemonkey#2655]
In addition to #2654 I've tried to copy the missing function into the user script and then the TogglButtonGM is known and will be instantiated but I then get the error that GM.xmlHttpRequest is not a function. The script being executed is at https://greasyfork.org/scripts/2670-toggllibrary/code/TogglLibrary.js and I can't figure out what's wrong. Any help much appreciated.

**Comment by Eselce** [comment]
I'm just working on some script migration myself and so I'm sure, that this is just a similar problem to what I have to fight with...
"is not a function" most definitely means "is undefined", please try to print out "typeof GM.xmlHttpRequest".
I've checked the spelling, the case of the 'h', what about "@grant GM.xmlHttpRequest" ?
(Okay, in #2654 there is one)...

**Comment by jurgenhaas** [comment]
Yes, the @grant is there and it's not a typo either. Both of these

```
console.log(typeof GM.xmlHttpRequest);
console.log(typeof GM.xmlhttpRequest);
```

respond with a undefined.

**Comment by Eselce** [comment]
I have some issues with this new GM object, sometimes it doesn't quite work as I would expect.
Even gm4-polyfill.js isn't always able to add members to it. But I've switched to the migration of some of my scripts now to get more information, it's just a matter of time... ;-)

**Comment by Eselce** [comment]
okaaaaaaay... just wrote a short test script to get some answers... and got some more questions...

Just an intermediate statement: I got that same error, but strangely enough, I **also** got the correct response!

My only solution is: GM.xmlHttpRequest did return undefined, not the expected Promise...

**Comment by Eselce** [comment]
Confirmed: `GM.xmlHttpRequest` returned `undefined`.

And `GM` looked like this: `Object { info: {…}, getValue: GM_getValue(), setValue: GM_setValue(), xmlHttpRequest: GM_xmlHttpRequest() }`

With https://arantius.com/misc/greasemonkey/imports/greasemonkey4-polyfill.js: `Object { info: {…}, getValue: GM_getValue(), setValue: GM_setValue(), xmlHttpRequest: GM_xmlHttpRequest(), addStyle: GM_addStyle(), registerMenuCommand: GM_registerMenuCommand() }`

**Comment by Eselce** [comment]
Hmm, that means, the error in your library occurs here: `});` (closes `GM.xmlHttpRequest({`).
Is your library still working (if you ignore the error message)?
I can't find a line, where you ever use the return value!

Well, I see in the wiki help:
`Returns undefined`
My bad, I expected a promise....

**Comment by Eselce** [comment]
Okay, I was wrong, but another detail makes me wonder again!
If `undefined` is returned, then why should the wiki help say in detail:

`synchronous` When `true`, this is a synchronous request. [...] In this mode, more data will be available in the `return` value.

Is this an artefact from `GM_xmlhttpRequest`?
See: https://wiki.greasespot.net/index.php?title=GM.xmlHttpRequest&oldid=7386

Returns
(Compatibility: version 0.8.5+) In the normal (asynchronous) case, an object with one method: abort().
(Compatibility: version 0.9.9+) In the synchronous case, an object with the abort() method, and properties describing the response

**Comment by tobbexiv** [comment]
The wiki seems to be updated without removing this. In the [source code](https://github.com/greasemonkey/greasemonkey/blob/master/src/bg/api-provider-source.js#L252) there is also a TODO. I also created #2648 for this issue with not being able to use synchronous xmlHttpRequests. Additionally there is #2607 for aborting xmlHttpRequests.

**Comment by Eselce** [comment]
Just  found it: // TODO: Return an object which can be `.abort()`ed.
Just needed 2 minutes longer...
That explains THIS all!
Thank you!
