### ISSUE TITLE
Use of storage.local

### ISSUE THREAD

**Issue by noscript** [greasemonkey/greasemonkey#2656]
With GM before 4.0 there was a way to put the scripts under revision control by sym-linking `<profile>/gm_scripts/` to my `.dotfiles` repo. WebExtensions do not have direct access to files system, but according to MDN there is [storage.local](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/local). It seems that GM 4.0 already uses `storage.local` but only to store `previousWelcomeUrl`.

Would it be possible to store scripts in `storage.local` as well?

**Comment by arantius** [comment]
No.
