### ISSUE TITLE
installation dialogue does not get triggered

### ISSUE THREAD

**Issue by pcuinty** [greasemonkey/greasemonkey#2662]
when opening a user script file e.g. ``file:///home/user/Desktop/testscript.user.js`` the install dialog does not get triggered. Is there a way to manually install a script?

Firefox 58.0a1
Ubuntu 16.04
Greasemonkey 4.0

**Comment by Sxderp** [comment]
Dupe #2612

**Comment by pcuinty** [comment]
I read #2612, although I have to admit I only understood half of it. Unfortunately I still don't know how to install my local user script. The manual states a popup should appear as soon as I open a file. I couldn't find any help for the case it doesn't appear.

**Comment by Eselce** [comment]
In parts (currently): Use "New user script ...", paste your code in, and save.

**Comment by pcuinty** [comment]
Thank you for your reply, I really appreciate it. Unfortunately I couldn't find "new user script..."

My greasemonkey looks like this:

![screenshot_2017-11-23_14-21-22](https://user-images.githubusercontent.com/14926781/33175031-97101ed0-d05a-11e7-9d95-ab46b06af063.png)

**Comment by Eselce** [comment]
Oh, sorry, it's not in GM 4.0, but definitively in the newest 4.1beta version (4 / soon 5)

**Comment by StigNygaard** [comment]
Except pasting script into "New user script..." doesn't seem to work. At least not in currently beta version. #2721 
You might need to upload it to Greasy Fork or similar (Another bug prevents install from Github :-( ).
Or maybe wait for next beta or 2.1final.

**Comment by Sxderp** [comment]
> Except pasting script into "New user script..." doesn't seem to work.

Yeah, I feel like a hotfix should have been pushed to AMO when the fix was merged into master.

**Comment by Eselce** [comment]
Works for me in most cases (and much easier than uploading somewhere)...
@Sxderp Guess you're right.
