### ISSUE TITLE
RFE: Script auto updates

### ISSUE THREAD

**Issue by BALTAGY** [greasemonkey/greasemonkey#2667]
Hi,

I can't find a way to check for script update in v4, is there a way to add an update option and script version ?

Thanks

**Comment by Sxderp** [comment]
Automatic updating / update searching hasn't been implemented yet.

**Comment by silverwind** [comment]
👍, I'm also missing a manual "Update" button on individual scripts.

**Comment by arantius** [comment]
This is one of the many missing features from earlier versions, which will eventually be restored.

For now you have to re-visit the original script by hand, to install a new version.

**Comment by tgp1994** [comment]
IMO this is a pretty big one, especially since you currently cannot install scripts from most host sites. I can't even remember what the process is now, I think it involves deleting the old script then manually pasting in the new one.

**Comment by Nothing4You** [comment]
Why could you not install scripts from host sites? Installing `my.user.js` works fine for me by clicking a link on a website.
It's a much larger issue for me though as we have scripts that regularly change and that simply doesn't work currently.

**Comment by tgp1994** [comment]
There's a firefox security "feature" that somehow blocks scripts hosted on GitHub from being installed, see Greasemonkey issue #2631. I'm not sure how it didn't catch your website though.

**Comment by arantius** [comment]
#2531
