### ISSUE TITLE
Configurable indentation style for built in editor

### ISSUE THREAD

**Issue by DoomTay** [greasemonkey/greasemonkey#2669]
Right now lines are indented with two spaces. What if you wanted to do four spaces or tab?

**Comment by Sxderp** [comment]
I know there's a TODO somewhere (probably in the code). If there's no issue open for this then this can stay open for tracking purpose.

**Comment by DoomTay** [comment]
Hmm...looks like there's something kind of in the works, but at the moment it only allows for spaces

https://github.com/greasemonkey/greasemonkey/blob/b27e7aed4f3ca2822a3ba67d59dbda5fcd048d71/src/content/edit-user-script.js#L4-L13
