### ISSUE TITLE
GM 4 Scripts Error: expected expression, got ')'

### ISSUE THREAD

**Issue by erosman** [greasemonkey/greasemonkey#2670]
Hi

Working scripts under GM 3 fail under GM 4

```
Could not execute user script: [Greasemonkey Script .../....; 1.0] 
 Error: expected expression, got ')'
Stack trace:
Async*@moz-extension://ffbb8d40-70fc-42b4-9d63-f5ac882801f8/src/bg/execute.js:23:5
  execute.js:29:7
```

Any idea what the cause is?

**Note:** There is no JS error in the code. (tested)

After testing .... it seem the following fails

```
// ==UserScript==
// @name          Clean URL
// @namespace     erosman
// @description   Clean URLs
// @include       *
// @grant         none
// @author        erosman
// @version       1.0
// ==/UserScript==


(function() { 


})(); // end of anonymous function
```

Fix: adding an extra line or removing the end comment eliminates the error.

The following works fine .... (added a blank line)

```
// ==UserScript==
// @name          Clean URL
// @namespace     erosman
// @description   Clean URLs
// @include       *
// @grant         none
// @author        erosman
// @version       1.0
// ==/UserScript==
*/

(function() { 


})(); // end of anonymous function

```

Following works as well ... (removed the end comment)

```
// ==UserScript==
// @name          Clean URL
// @namespace     erosman
// @description   Clean URLs
// @include       *
// @grant         none
// @author        erosman
// @version       1.0
// ==/UserScript==
*/

(function() { 


})();
```

**Comment by Sxderp** [comment]
The way the parsing works is to create a function for the userscript and then call it. The current implementation defines the script on a [single line](https://github.com/greasemonkey/greasemonkey/blob/71e9be5e38f984977f128bb439130ada6446c185/src/user-script-obj.js#L252). If the userscript ends in a comment than it causes the function definition to be invalid.

**Comment by Sxderp** [comment]
Submitted a pull to resolve the issue.

**Comment by arantius** [comment]
Short term workaround: edit your scripts so they don't have a `//` line comment on the last line.

Will be fixed in next release.

**Comment by erosman** [comment]
> Short term workaround: edit your scripts so they don't have a // line comment on the last line.

Obviously as pointed out in my initial post, I had already worked that out. ;)

**Comment by arantius** [comment]
Sorry you edited that in after your first post, so I didn't see it (read the message as delivered to my email).

**Comment by erosman** [comment]
> Sorry you edited that in after your first post, so I didn't see it (read the message as delivered to my email).

Strange... since the edited post contains the data about it having a comment at the end. The original first post didn't have that information and only listed the error without showing the code.

**Comment by arantius** [comment]
Todo me (or @Sxderp ?) add a unit test to ensure this issue doesn't regress in the future.

**Comment by Sxderp** [comment]
Ah yes. I'll get on that. Submit as new pull request? If you want it in the same that'll be delaying the fix for a bit, unless you do it. Not sure when I can get around to the test cases[1].

[1] node and friends not setup

**Comment by arantius** [comment]
Base pull is already merged.

**Comment by Sxderp** [comment]
Added pull for tests
