### ISSUE TITLE
GM.openInTab opens the tab in the wrong place

### ISSUE THREAD

**Issue by AndersOhrt** [greasemonkey/greasemonkey#2672]
I've upgraded to Firefox 57, and migrated my script from GM_openInTab to GM.openInTab. I have browser.tabs.insertRelatedAfterCurrent = false. When tabs are opened, they are placed incorrectly, as if insertRelatedAfterCurrent was true.

**Comment by xor10** [comment]
Webextensions don't have access to this setting. :(
The solution would be to create a settings page to allow the user to set this.

**Comment by AndersOhrt** [comment]
Adding another parameter to the function would also work in my case, as it is now my script is worthless.
