### ISSUE TITLE
GM4 await promise is a lie

### ISSUE THREAD

**Issue by Owyn** [greasemonkey/greasemonkey#2678]
````
// ==UserScript==
// @name        False promises
// @match	      *://github.com/*
// @grant        GM.getValue
// @grant        GM.setValue
// ==/UserScript==

var cfg_bgclr;
async function loadCfg()
{
	if (typeof GM.getValue !== "undefined")
	{
		GM.setValue("bgColor", "black"); // lets pretend it was there
		cfg_bgclr = await GM.getValue("bgColor");
	}
  console.log("the type is: " + typeof GM.getValue);
	console.log("the bg color is: " + cfg_bgclr);
}
loadCfg();

document.body.bgColor = cfg_bgclr;
console.log("the color is: " + cfg_bgclr);

````

console output:
![console](https://user-images.githubusercontent.com/1309656/32856866-21bf050a-ca57-11e7-8de0-7cd1f58eabf3.jpg)

element inspect:
![elem](https://user-images.githubusercontent.com/1309656/32856877-2e01721c-ca57-11e7-92f2-f3bbe9b930b2.jpg)

as you can see, promise is a lie, I can't just set it and `await` for it be assigned transparently later, I must wait, a fix, if possible, would be welcomed.

**Comment by tobbexiv** [comment]
I can not see any bug here. To me it seems more that you did not understand the concept of Promises, yet. Promises and async functions (which return a promise when called) are asynchronous. So they are executed not in the order as they are listed. You should also await the setValue as it also returns a Promise and is asynchronous.

I would recommend to you to check out a few scripts that use the new API and also read the examples on MDN linked in the GM 4.0 announcement.

A version of your script example that should give the output expected by you:
```
// ==UserScript==
// @name	False promises
// @match	*://github.com/*
// @grant	GM.getValue
// @grant	GM.setValue
// ==/UserScript==

var cfg_bgclr;
async function loadCfg()
{
	if (typeof GM.getValue !== "undefined")
	{
		await GM.setValue("bgColor", "black"); // lets pretend it was there
		cfg_bgclr = await GM.getValue("bgColor");
	}
	console.log("the type is: " + typeof GM.getValue);
	console.log("the bg color is: " + cfg_bgclr);
}
loadCfg().then(function() {
	document.body.bgColor = cfg_bgclr;
	console.log("the color is: " + cfg_bgclr);
});
```

**Comment by arantius** [comment]
Tobias has this.  You didn't wait for the set to complete, in your original code.

**Comment by Owyn** [comment]
Yes, thank you for the clarification, I was expecting too much, like a pointer value or smth.

Sadly waiting for GM.getValue is pretty long, it made a script slow down noticeably visually which needs configuration before proceeding, it was almost instant before in GM3 but not it flashes and has like a 0.5sec delay before execution.

I have
````
async function loadCfg()
{
	if (typeof GM.getValue !== "undefined")
	{
		cfg_bgclr = await GM.getValue("bgColor", "grey");
		cfg_fitWH = await GM.getValue("fitWH", true);
		cfg_fitB = await GM.getValue("fitB", false);
		cfg_fitS = await GM.getValue("fitS", true);
		cfg_js = await GM.getValue("js", "");
	}
	startOurBuisinessWeGotConfigs();
}
loadCfg();
````

am I understanding it right that it halts execution on each line awaiting for each reply that getValue was successfull not executing the next getValue before it? 
Is there an easy way to make those 5 GM.GetValue to be executed asynchronously to each other while making sure values are received?

**Comment by Eselce** [comment]
Yes, use Promise.all() for this task!

**Comment by Eselce** [comment]
One of several possibilities:
```
async function loadCfg()
{
	if (typeof GM.getValue !== "undefined")
	{
		const defaults = {
			"bgColor" : "grey",
			"fitWH"   : true,
			"fitB"    : false,
			"fitS"    : true,
			"js"      : ""
		};
		const keys = Object.keys(defaults);
		const results = keys.map(key => GM.getValue(key, defaults[key]);
		const values = await Promise.all(results);
		[cfg_bgclr, cfg_fitWH, cfg_fitB, cfg_fitS, cfg_js] = values;
	}
	startOurBuisinessWeGotConfigs();
}
loadCfg();
```

**Comment by Eselce** [comment]
Well, actually you could (should you?) substitute the 4 lines with this:
```
[cfg_bgclr, cfg_fitWH, cfg_fitB, cfg_fitS, cfg_js] =
	await Promise.all(Object.keys(defaults).map(key => GM.getValue(key, defaults[key])));
```
