### ISSUE TITLE
V4 (jQuery) AJAX requests don't work anymore

### ISSUE THREAD

**Issue by ulrichb** [greasemonkey/greasemonkey#2680]
The following script shows `Error - status: 0, statusText: SyntaxError: The URI is malformed` instead of the AJAX result.

This worked in v3 and also works with Chrome Tampermonkey.

```JS
// ==UserScript==
// @name        Test User Script
// @include     https://www.wikipedia.org/*
// @version     0.1
// @grant       none
// @require     https://code.jquery.com/jquery-3.2.1.min.js
// @noframes
// ==/UserScript==


console.log('jQuery version', $.fn.jquery);
console.log($.get);

alert('hi. now some ajax request ...');

$.get('/').done(x => {
	alert(`ajax result:\n${x.substring(0, 100)}...`);
})
.fail(jqXhr => {
	alert(`Error - status: ${jqXhr.status}, statusText: ${jqXhr.statusText}`);
});
```

**Comment by Sxderp** [comment]
Use absolute paths. This is an issue with Firefox and content scripts.

**Comment by ulrichb** [comment]
Thanks for the other issue.

I've already tried that in my real user script ... I then got a 403. First I thought of a GM sandboxing issue. But now I think the (next) issue is that the request doesn't use the browsers cookies and therefore the server returns 403 (unfortunately I got no entry in the Network tab). 
Again: In GM 3 / Tampermonkey this works fine.

**Comment by arantius** [comment]
#2549
