### ISSUE TITLE
The name of unknown key in userscript meta data warning is truncated: @supportURL triggers an 'Expected "author", "description", ... or "version" but "s" found.' warning

### ISSUE THREAD

**Issue by juozaspo** [greasemonkey/greasemonkey#2684]
Having `@supportURL` or any other unknown key such as gibberish in userscript meta info triggers CodeMirror lint warning with truncated key name: 
`Expected "author", "description", "downloadURL", "exclude", "grant", "homepageURL", "icon", "include", "installURL", "match", "name", "namespace", "noframes", "require", "resource", "run-at", "updateURL" or "version" but "s" found.` 
Full text captured using firefox debug tools, screenshots below.
![pazymejimas 2017-11-16 15 14 43](https://user-images.githubusercontent.com/6626242/32893396-f636f4ca-cae1-11e7-947f-2874205f58f7.png)
![pazymejimas 2017-11-18 16 17 46](https://user-images.githubusercontent.com/6626242/32981217-30143fd6-cc7c-11e7-8d83-7e242c9c6ed7.png)
Greasemonkey 4.1beta3 and 4.1beta4

**Comment by Sxderp** [comment]
Would be nice if it reported the entire string "supportURL."

**Comment by Eselce** [comment]
You guessed it: Same with @copyright and "c" found... ;-)

**Comment by arantius** [comment]
#2703 has been packaged in a new beta version:
https://addons.mozilla.org/firefox/downloads/file/830369/greasemonkey-4.2beta1-an+fx.xpi?src=devhub

Testing and confirmation would be appreciated!

**Comment by Eselce** [comment]
You've probably already registered, that it works fine.

For me, it was @copyright (I use it, although GM doesn't accept it).

GM 4.1 (and earlier) mentioned "c", while this fix extends it to "copyright".
The whole word is underlined to mark the failure.
