### ISSUE TITLE
Switch to install dialog

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2687]
Away from whole-tab UI.

I always wanted this but there's [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1402110) in the WebExt API which makes opening a dialog broken.

Might make sense to revamp when we show the install dialog at the same time as how, addressing #2631 as well.

**Comment by Sxderp** [comment]
Dupe #2641
=-)

**Comment by arantius** [comment]
Heh, thanks.
