### ISSUE TITLE
GM.xmlHttpRequest is no longer able to bypass Content-Security-Policy connect-src on Greasemonkey 4

### ISSUE THREAD

**Issue by DoctorMcKay** [greasemonkey/greasemonkey#2688]
https://groups.google.com/forum/#!topic/greasemonkey-users/W82TdrzgQYk

Since updating Firefox to 57 and Greasemonkey to 4, I've been unable to make requests to origins not listed in the parent page's Content-Security-Policy connect-src directive using `GM.xmlHttpRequest`.

**Comment by arantius** [comment]
A reduced test case would be very helpful.

**Comment by DoctorMcKay** [comment]
My apologies. I did some more testing and determined that I misinterpreted the nature of the CSP failure messages I was seeing. It wasn't CSP that was breaking my script.
