### ISSUE TITLE
"Save script" shortcut should match platform (ctrl vs. cmd)

### ISSUE THREAD

**Issue by adaugherity** [greasemonkey/greasemonkey#2690]
After upgrading to FF 57 (which upgraded GM to v4), my script no longer works.  I tried to fix it via the editor, but appeared to be unable to save my changes as there is no save button and Cmd-s brought up the Firefox Save Page As... dialog.

I eventually discovered https://groups.google.com/forum/#!topic/greasemonkey-users/GLTDE-G9LZI indicating there are not (yet) any buttons, and Ctrl-S is the shortcut to save.  That did indeed work, but is unexpected on macOS.  Can we please make the shortcut be ⌘S (Cmd-s) on Mac?

**Comment by arantius** [comment]
This is in build 4.1beta5 ( https://addons.mozilla.org/firefox/downloads/file/793791/greasemonkey-4.1beta5-an+fx.xpi?src=devhub ).  Testing and confirming would be appreciated!

**Comment by adaugherity** [comment]
Tested 4.1b5 on Mac, and the save shortcut is now cmd-s. 👍 

I do see some warnings logged to the browser console -- are these known issues?

Upon opening the editor: 
```
Loading failed for the <script> with source “moz-extension://e8447a6c-bfa1-8e46-a717-cd76d4efe15c/third-party/codemirror/addon/scroll/annotatesscrollbar.js”.
edit-user-script.html:16
```
Saving a script:
```
updater has no added remotes to handle
user-script-obj.js:349:9
```

**Comment by Sxderp** [comment]
> Upon opening the editor:

Not sure about that. Though I think it may be a bug, as far as I know all the codemirror things should load properly.

> Saving a script:

Standard. Just some debug info detailing that there are no `@require` or `@resource` tags.

**Comment by xor10** [comment]
> Not sure about that. Though I think it may be a bug, as far as I know all the codemirror things should load properly.

Typo.
```diff
diff --git a/src/content/edit-user-script.html b/src/content/edit-user-script.html
index 9c1d1b8..d94e7e2 100644
--- a/src/content/edit-user-script.html
+++ b/src/content/edit-user-script.html
@@ -13,7 +13,7 @@
 <script src="../third-party/codemirror/addon/dialog/dialog.js"></script>
 <link rel="stylesheet" href="../third-party/codemirror/addon/dialog/dialog.css">
 
-<script src="../third-party/codemirror/addon/scroll/annotatesscrollbar.js"></script>
+<script src="../third-party/codemirror/addon/scroll/annotatescrollbar.js"></script>
 
 <script src="../third-party/codemirror/addon/search/searchcursor.js"></script>
 <script src="../third-party/codemirror/addon/search/search.js"></script>

```

**Comment by ramast** [comment]
I am using Greasemonkey v4.1 with firefox 57.0.1 and I am unable to save any greasemonkey script. Ctrl+S show firefox's "save page as" dialog and there is no save button as mentioned above. wondering if that has something to do with that fix

**Comment by Eselce** [comment]
Which OS? (Confirmed: There is no button yet!)

**Comment by ramast** [comment]
Sorry I forgot to mention that, I am running Linux 64bit. Firefox installed directly from mozilla not through any kind of package manager

**Comment by Eselce** [comment]
I'm using Linux since 1991, but sorry, no experience with Firefox/Linux here. I assume, that you may use Ctrl-S shortcut. Any hotkey manager active?

**Comment by ramast** [comment]
Ctrl+S is hotkey for Firefox's "Save Page As" menu item.
Firefox receives the hot key and handle it by showing the "Save Page As" dialog.
 I have no knowladge of greasemonkey's coding but I suppose you ask firefox not to handle Ctrl+S and instead notify greasemoneky? if so then probably that part is not working.

**Comment by ramast** [comment]
I tried on a fresh install (without any other addons) and it worked perfectly fine.  So maybe this is caused by addons or because of migration from older version of greasemonkey.

Please disregard my comment, If I figured out the cause and it was a bug I'd raise the issue.

Cheers

**Comment by Eselce** [comment]
As for me, it works perfectly fine as well. You're welcome.

**Comment by Sxderp** [comment]
The problem is usually due to some error with the scripts loading into the editor. I've had it happen before but I usually debug the problem and move on. I'm 90% sure that it can be prevented with some better error handling, but I don't recall where. Unfortunately I haven't run into the problem in a while.

**Comment by mrf345** [comment]
Same issue on Linux, finally solved it by resorting to `onSave()` after looking into the editor sourcecode.
> Buttons are unified across all browsers and operating systems, shortcuts are not !
