### ISSUE TITLE
User scripts for local files ("file:///" protocol)

### ISSUE THREAD

**Issue by FeBe95** [greasemonkey/greasemonkey#2693]
I know it is stated in the Greasemonkey (4) wiki that "User scripts will not run on documents from any other scheme (ftp, file, etc.) or any other part of about. ", but why is this the case? WebExtensions are able to access local files and Violentmonkey for example is able to execute user scripts on "file:///" pages.

**Comment by StigNygaard** [comment]
#2612

**Comment by FeBe95** [comment]
The issue you linked is about installing a local `myscript.user.js` file, whereas my issue is about executing user scripts on pages that are local files.
For example a script that redirects local php files `"file:://C:/xampp/....../index.php"` to `http://localhost/....../index.php`.

**Comment by Sxderp** [comment]
I'm actually not sure about this. Executing a user script on a `file://` protocol shouldn't have any technical limitations.

**Comment by arantius** [comment]
> Executing a user script on a file:// protocol shouldn't have any technical limitations.

Conceptually, no.  Today we `tabs.executeScript()`, which is just a content script, which is limited.  Mozilla really rushed their WebExtension decision.

I hope #2549 will help with this, but we have to wait for Firefox to unblock us there.

**Comment by FeBe95** [comment]
Okay, but without Firefox changing something, Violentmonkey already is able to execute scripts on local pages. Are they doing something fundamentally different ?

**Comment by Sxderp** [comment]
> Conceptually, no. Today we tabs.executeScript(), which is just a content script, which is limited. Mozilla really rushed their WebExtension decision.

Content scripts will run on `file://` There's just some edge case functionality in regard to certain background listeners [matching on them](https://github.com/greasemonkey/greasemonkey/issues/2612#issuecomment-340314062). And of course the async request for them which spawned that particular issue[1]. In fact `webNavigation.onCommitted` matches `file://` protocol just fine.

In the _current_ codebase the only thing preventing scripts from running on `file://` is [here](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/user-script-obj.js#L136-L142).

[1] @erosman made some good points in regard to local file install workflow. I think it should be considered.

**Comment by erosman** [comment]
> In the current codebase the only thing preventing scripts from running on file:// is here.
Is there an update to this?

**Comment by Sxderp** [comment]
> Is there an update to this?

Hasn't changed. Should be a quick fix to _execute_ user scripts on `file://`. Of course, installing still has the same issues as discussed in the other issue.

I'll post back in a few minutes.

**Comment by erosman** [comment]
@Sxderp Thanks
I have been waiting for this for a while as I run some tools on a local file:// which runs into trouble (especially with CORS) if run as a normal page script.
I was about write an addon for myself just for that, if this issue wasn't fixed. ;)

Is there an ETA for the release?

**Comment by Sxderp** [comment]
> Is there an ETA for the release?

Not that I have any control over. It's when @arantius has the time.

**Comment by erosman** [comment]
@arantius Do you have a release date for 4.2?

**Comment by erosman** [comment]
GM 4.2beat2

I am getting an error.

note:
```
Lin 57: console.log(typeof GM.xmlHttpRequest);

Line 191: console.log(typeof GM.xmlHttpRequest);
Line 192:   GM.xmlHttpRequest({
```

Result:
```
function  Tester:417
function  Tester:551
ReferenceError: GM is not defined  Tester.js:190:3
```

Line 190 is not part of Tester.js

**Comment by arantius** [comment]
In what way is this comment related to this issue?

**Comment by erosman** [comment]
> In what way is this comment related to this issue?

I thought it was obvious but I updated the above post for clarification.

**Comment by Sxderp** [comment]
Can't reproduce on a Linux box, could you give us a bare working example?

My test script.

```javascript
// ==UserScript==
// @name     Test File xml
// @version  1
// @grant    GM.xmlHttpRequest
// @match    file:///*
// ==/UserScript==
function results(xml) {
  console.log(xml);
}
console.log(GM);
GM.xmlHttpRequest({'url': 'https://ncgamers.org', 'onload': results});
```

Console
```
Object { info: Object, xmlHttpRequest: GM_xmlHttpRequest(d) }  Test%20File%20xml:281:1
```
```
Object { context: null, finalUrl: "https://ncgamers.org/", lengthComputable: null, loaded: null, readyState: 4, response: "<!DOCTYPE html PUBLIC "-//W3C//DTD …", responseHeaders: "Date: Wed, 10 Jan 2018 16:11:45 GMT…", responseText: "<!DOCTYPE html PUBLIC "-//W3C//DTD …", responseXML: null, status: 200, 2 more… }  Test%20File%20xml:279:3
```

**Comment by erosman** [comment]
> Can't reproduce on a Linux box, could you give us a bare working example?

Oops.... apologies .. that was my mistake. I found the problem (which was with an embedded script version of GM script that I was working on, not GM injected script).

Please disregard my post. It seems to be working just fine.

**Comment by Sxderp** [comment]
I believe this can be closed now.
