### ISSUE TITLE
Maintain the popup scrolling position when viewing a script entry's options 

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2694]
Currently in GM 4.0 when clicking a script entry in the popup to view its options, and press the back '<' arrow,
then is always takes you to the top of the scripts list, regardless of your previous scrolling position.
I believe it would be more convenient if the scrolling position was maintained, 
especially when having lots of user scripts.

**Comment by Sxderp** [comment]
Not too difficult but I did have some jankyness with the UI. If you scroll too soon, say right inside `goToTop`, nothing happens. If you set a timeout then you get janky UI if the timeout is too long. The length required may be processor dependent.

**Comment by Eselce** [comment]
That's for sure: Scrolling through all the active and inactive / page relevant and other scripts is really ugly, if you use more than just a few scripts. Is this really the best way to show an overview of all `GM` scripts?

**Comment by arantius** [comment]
Fixed by #2818 .
