### ISSUE TITLE
Move new user script to top of Monkey Menu

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2697]
I feel like this should be moved to the top of the menu as it's functional, rather than informational.

**Comment by arantius** [comment]
I tried to prioritize it more by "importance" than by function.  How often would I expect it to be clicked on, for any given user?  More often == higher.  I think creating a new script from scratch is a less frequent action than managing/editing/etc. currently installed scripts.

(The enable/disable toggle is one exception.  It might not be the most frequent action, but it also serves the purpose of clearly labeling, right at the top, that this is the *Greasemonkey* menu.)

**Comment by tobbexiv** [comment]
I would not put it to top, but have a divider between creating a new user script and the info links. Then it would be thematically divided into the sections:

Enable / disable GM
*-*-*-*
Scripts for the page
*-*-*-*
Other scripts
*-*-*-*
Greasemonkey functions (create new script, upload script, options, ...)
*-*-*-*
Info urls

**Comment by arantius** [comment]
I'd happily accept a pull for that extra line.  Top: No thanks.
