### ISSUE TITLE
Change the icon of "Greasemonkey is disabled" to something more meaningful

### ISSUE THREAD

**Issue by tiansh** [greasemonkey/greasemonkey#2698]
An [O Mark](https://en.wikipedia.org/wiki/O_mark) is used currently, which is confusing and just telling me "correct" or maybe "enabled". [No Symbol](https://en.wikipedia.org/wiki/No_symbol) or [X Mark](https://en.wikipedia.org/wiki/X_mark) may be a better choice.

Version info: Greasemonkey 4.0

**Comment by Sxderp** [comment]
Agreed

**Comment by arantius** [comment]
It's just a (round) checkbox that can either be checked or not.  Why isn't that meaningful?

I'd interpret the X mark in the opposite way: that's a checked checkbox, that means enabled to me.

**Comment by tobbexiv** [comment]
To me the o usually means a bullet point list or "check here". Additionally this does not change, only the content changes. Thus, I think its clear especially as there is a text next to it so if you really do not understand it, you can read the text.

**Comment by arantius** [comment]
(only) a check mark when enabled and a complete empty space when disabled could also be an unambiguous improvement perhaps?

**Comment by tiansh** [comment]
tick vs. none may be a good choice, just like what firefox does.

![tick](https://user-images.githubusercontent.com/6500326/33000043-a05f8ef2-cde0-11e7-8058-fc51a3500aa3.png)

**Comment by S-ed** [comment]
@tiansh how people suppose to know there should be a 'tick' if there's nothing?

**Comment by Sxderp** [comment]
> how people suppose to know there should be a 'tick' if there's nothing?

Considering Mozilla uses it in their UI I assume there's at least _some_ thought behind it. Although, may be garbage thoughts considering what I've seen from UI/UX guys.

**Comment by S-ed** [comment]
Yeah, the tick is only working for "Toggle Tools" and "Developer Toolbar"...

**Comment by arantius** [comment]
If you think this needs to change: Please open http://fontawesome.io/icons/ and suggest by name the *two* icons that you think should represent A) the enabled and B) the disabled status.  And why the selection of these two is better than the status quo.

**Comment by tiansh** [comment]
here are some choices, imo

enabled | disabled | reason
---- | ---- | ----
toggle-on | toggle-off | widely known, and commonly used for enable / disable features (prefered)
check-circle-o | ban | minimal modification and no ambiguous
check-square-o | square-o | an checkbox input normally use square, at least on windows and mac
check | times | also some-how widely known as a pair of yes / no <br />(maybe not so in some region)

**Comment by Sxderp** [comment]
Here's a set of all of them. I was going to upload to some site that flopped between two images but I couldn't find any site that does that on Google (I know they exist though..).
https://imgur.com/a/7e1xW

I like
> check-circle-o : ban

and
> check-square-o : square-o

**Comment by S-ed** [comment]
`times` looks ambiguous. Like a close button.

**Comment by arantius** [comment]
All suggestions so far: https://jsfiddle.net/arantius/eqetnygd/9/

My notes/opinions:

<dl>
<dt>check-circle-o / circle-o</dt>
<dd>What we've got now.  A circle containing either a check or nothing, I think it's clear.</dd>
<dt>toggle-on / toggle-off</dt>
<dd>Pretty good.  Not super fond of how bold/strong the enabled state is.  (Maybe a slightly different color could help?)</dd>
<dt>check-circle-o / ban</dt>
<dd>The two states are too visually similar.  "Ban" has extra meaning, like a no smoking sign.</dd>
<dt>check-square-o / square-o</dt>
<dd>Could be quite good. But as the check is added, the box moves over, which I dislike.</dd>
<dt>check / times</dt>
<dd>Clear meaning, but very heavy icons.</dd>
<dt>check / nothing</dt>
<dd>Emulates standard (Windows at least) menus.</dd>

**Comment by tobbexiv** [comment]
I find those fine:

check-circle-o / circle-o
toggle-on / toggle-off
check / nothing
