### ISSUE TITLE
Feature request: move (enable) (edit) (delete) buttons on the script list directly

### ISSUE THREAD

**Issue by S-ed** [greasemonkey/greasemonkey#2704]
Greetings!
First of all, thank you for this app.

It would be nice to have the buttons in the script settings directly on the list:

![screenshot 1511068785](https://user-images.githubusercontent.com/3008353/32987673-627b5aa4-cd03-11e7-806e-b0b812355129.png)

ENABLE button may be in the front of the title (on the left).
As for DELETE button, it could be made as in mobile apps, click once - confirmation button slides in (generally red one). Or click and hold for 2 seconds to enable this existing timer (I doubt it will be very annoying to delete many files like that).

Thank you.

**Comment by Sxderp** [comment]
While I like this idea on the desktop my concern is mobile. @arantius has shown interest in ensuring support for mobile platforms. Having a bunch of buttons crammed on one line is just ripe for mis-touches. If there's a reliable way to detect if mobile (I haven't seen any APIs for it) then perhaps the mobile variant can have a vertical ellipsis drop down. Of course, then you have to maintain two codepaths.

**Comment by arantius** [comment]
Even on desktop I dislike this.  For two main reasons:

* See #2698 where serious debate is had over what a circle/box/check/x might mean in relation to "enabled".  Having icons only and no text beside it would have made this work.
* Icons only with no text is awful for accessibility.

The mobile concern also applies.  (Though I've interacted with plenty of things on desktop, designed "mobile first" which I found sub optimal ...)

**Comment by tiansh** [comment]
Edit and delete may be hidden in background since they are not such important and frequently used. 
But maybe "Enable" icon may be there. If you value the accessibility very much, and considered that text should be a must-have, a toggle with "on / off" text on it could be chosen.

![switch](https://user-images.githubusercontent.com/6500326/32999726-9afd5be4-cdde-11e7-8957-89ea72eaf3a5.png)

**Comment by Sxderp** [comment]
> ... If you value the accessibility very much...

What he means by accessibility is not "this is easily accessible, in a general sense (which is nice)" but rather "can someone who has some impairment and requires assistance be able to achieve their goals?"
Most notably is screen readers and / or keyboard navigation (actions). Having a line that has two actions on it, click to see more details or click slightly somewhere else to toggle, isn't very good for keyboard operation.
