### ISSUE TITLE
Can't add requires / resources when downloadURL is null

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2706]
Brought to light be recent button to add a new user script.
Adding a new user script with the button creates a script with a null downloadURL. So when the editor is saved `parseUserScript` [receives a null second argument](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/user-script-obj.js#L301-L302). If a resource is added then this null value is [used as](https://github.com/greasemonkey/greasemonkey/blob/64f1ae1945c54ad343a2aad896b72a71f86fd07a/src/parse-user-script.js#L114) the second argument to `URL`. According to MDN this _shouldn't_ be a problem, but it is. TypeError.

**Comment by arantius** [comment]
This is in build 4.1beta5 ( https://addons.mozilla.org/firefox/downloads/file/793791/greasemonkey-4.1beta5-an+fx.xpi?src=devhub ).  Testing and confirming would be appreciated!
