### ISSUE TITLE
Linting, bracket highlighting and autocomplete hints in the embedded editor

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2710]
> In GM 4.0, there is only an embedded editor.  Browser Extensions have no access to the file system, so you can no longer author user scripts in your familiar text editor.

Therefore, I believe it would be great if you added to the embedded editor
the following features via the relevant CodeMirror addons : 

-  Linting while editing, via the [lint.js addon](http://codemirror.net/doc/manual.html#addon_lint) addon. _Requires [JSHint](https://github.com/jshint/jshint)_. ([demo](http://codemirror.net/demo/lint.html)),
- Highlight matching brackets, via the [matchbrackets.js](http://codemirror.net/doc/manual.html#matchbrackets.js) addon, and
- Autocomplete hints, via the [show-hint.js](http://codemirror.net/doc/manual.html#addon_show-hint) addon ([demo](http://codemirror.net/demo/complete.html)).

_There are many other useful addons in the [CodeMirror addon list](http://codemirror.net/doc/manual.html#addons) of course, 
most notably I'd say, the [foldcode.js](http://codemirror.net/doc/manual.html#addon_foldcode) addon._

_For reference, all the above have been incorporated in Tampermonkey 
(here is [the discussion for the 1st and 3rd](https://github.com/Tampermonkey/tampermonkey/issues/243))._

---

Notes :
- here is the list [of the currently used addons in the embedded editor](https://github.com/greasemonkey/greasemonkey/blob/master/src/content/edit-user-script.html),
- regarding the linter: [as I see](https://github.com/greasemonkey/greasemonkey/commit/aee6329bb7ac184d85fff29a3ee3c0e514eceea7), that the lint addon (w/ parse-meta-line.js) is currently used only to show errors in the _metadata_ block.

**Comment by GM-Script-Writer-62850** [comment]
On this note is it possible for a web extension to open the script in the ide/text editor of our choice (eg notepad++, geany, gedit, nano, etc.)
and more importantly is there a way to get script errors to appear in the web console, it is sooo hard to find a missing bracket

**Comment by Sxderp** [comment]
> On this note is it possible for a web extension to open the script in the ide/text editor of our choice (eg notepad++, geany, gedit, nano, etc.)

I don't think so.

> and more importantly is there a way to get script errors to appear in the web console, it is sooo hard to find a missing bracket

I don't think so. You can try wrapping in try + catch blocks. But that doesn't get everything.

**Comment by monk-time** [comment]
@Sxderp One way to add a way to edit userscripts in native applications is through [native messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging). It would require writing a separate PowerShell (for Windows)/Python (for Linux) script that would save a userscript in a temporary folder, launch an editor associated with it and listen for file changes until the editor (or a moz-extension:// tab) is closed. 

Here's an example of a WebExtension that uses this API to launch any command from the browser with a current tab/link's URL: [Open With](https://github.com/darktrojan/openwith/tree/master/webextension)

This solution would require an additional permission and more setup steps for the user, but more technical-minded script writers should be able to do through them, and those who don't need this feature can continue using the extension as usual.

**Comment by arantius** [comment]
Many of these features would get in my way.  I wouldn't consider forcing
them all on until the editor can be configured by the user, as everyone has
their own opinion about which should be enabled or not.

**Comment by badbrainz** [comment]
I'd like to work on some of these. Maybe an editor options ui, too. I'm adding to my fork some of the heavier tools and a few addons that I think are useful. That'll save you guys some time.

@arantius Why not rename this to "editor wish list"? If u do, please merge #2619 and #2616. I'd like to also add intellisense (tern) to the mix. I have a working implementation here. Very basic at the moment but it does display GM* type definitions + documentation; describing GM.info and how to use the API could be one of the greatest features IMO.

**Comment by Cerberus-tm** [comment]
I think @monk-time has a great point: if this "native messaging" can be used to allow users to edit the userscript in their own editor of choice, then the built-in editor can remain basic. I have no idea how hard it would be to do this, though, as I'm a total layman. I would even be tempted to write an Autohotkey script that automatically copies the userscript from the built-in editor using control-c and then pastes it into Sublime Text for editing, then copy-paste it back upon a file save...

**Comment by arantius** [comment]
It would be easiest for me if there were one issue targeted to discussing each distinct feature, and if discussion is positive then each gets a pull request for the minimum code to add just that feature.

One big kitchen-sink issue for lots of separate things is a good way to get put at the bottom of my priority list.  Time is limited.  I'm aware of those pull requests, but see them as "nice to have", while other critical/broken feature things remain.

**Comment by darkred** [comment]
> It would be easiest for me if there were one issue targeted to discussing each distinct feature,

Here: https://github.com/greasemonkey/greasemonkey/issues/2735, https://github.com/greasemonkey/greasemonkey/issues/2736, https://github.com/greasemonkey/greasemonkey/issues/2737, https://github.com/greasemonkey/greasemonkey/issues/2738

**Comment by arantius** [comment]
Thanks!  I assume those cover this so I'll close this in favor of those smaller issues.

**Comment by lope** [comment]
This is insane!!!

GM is a tool that runs browser extensions.
Now you're trying to reinvent the wheel and make it as good as a code editor! And force me to use it!?
WTF!? Why can't we just use our favorite editor on the filesystem, it would be infinitely simplier than trying to make a code editor that will be as good as every developer's favorite editor.

WTF

**Comment by StigNygaard** [comment]
Ahem @lope , it is not the GM developers who has decided to skip support of using external editor via the filesystem. The new WebExtension system doesn't allow direct access to the filesystem, like the old one did. And extensions for the old extension system (like GM3.x) is not compatible with Firefox 57 and beyond....

**Comment by GM-Script-Writer-62850** [comment]
Is is possible to open the folder containing the script? like the Profile Directory button in about:support

**Comment by StigNygaard** [comment]
There is no folder containing the scripts. As I understand it is all in a database.
