### ISSUE TITLE
"Could not execute user script: [...], <unavailable>"

### ISSUE THREAD

**Issue by Dediggefedde** [greasemonkey/greasemonkey#2711]
Hi!
Good job on rewriting the engine! I'm slowly making progress at adapting my old scripts to Promises...
What I noticed: if you violate the policy that  `GM.xmlHttpRequest` and await `GM.getValue` need to be in an async function, firefox gives you the `<unavailable>` error.

However, not I somehow hit a wall. I wrote a small userscript for deviantart.com and when I try to run it in Firefox, it says `Could not execute user script: [...], <unavailable>`.
Even if I comment everything out, remove the @require jquery line and refresh the page, it's still not able to call the script. No GM.log or console.log show up.
I'm pretty sure to do the Promise-thing right in the script, too...

If I use the exact same script in chrome & tampermonkey, it doesn't even show an error...

Link to the script: http://phi.pf-control.de/userscripts/dev_group_list/131964.user.js

Might this be some caching mistake of an old version or required script?

**Comment by Sxderp** [comment]
Bringing up the browser log (ctrl+shift+j)
```
Could not execute user script: [Greasemonkey Script undefined/百度网盘直接下载助手; 0.9.24] 
 Error: expected expression, got '<'
```

Makes it look like there's a syntax error of some sort. Although I don't see anything that stands out (like a for loop missing a `;`).

Would be great if you could minimize the amount of code that causes the issue.

**Comment by Sxderp** [comment]
So, async functions return promises. If they throw errors they're generally silent unless you use `.catch()` on the promise.

Adjusting the line
```
listverzlad().then(function(e) { console.log('good stuff', e) }).catch(function(e) { console.log('bad stuff', e) });
```
In the console
```
bad stuff TypeError: tghl is undefined
Stack trace:
listverzlad/<@user-script:dev_group_list/dev_group_list:347:8
```
Do note, that the line provided is not the correct line number. Mostly because of the wrapper code and the `@requires` adding many lines to the script.

I think it's your `if(tghl==null)` lines. If `GM.getValue` doesn't have a particular key, I'm pretty sure it returns `undefined`.

**Comment by Dediggefedde** [comment]
Well, thanks for the help with the code, but if I comment out everything after `// ==/UserScript==`
it still says `Could not execute user script: [Greasemonkey Script dev_group_list/dev_group_list; 1.88] 
 <unavailable>`... 
So, aside from mistakes I made within the script, I also guess there is a problem of GM itself to realize changes in the embedded editor...

**Comment by Sxderp** [comment]
> or maybe commented promises are still evaluated?

Shouldn't.
The error you get is in the browser (ctrl+shift+j) console? If so then check the page console (ctrl+shift+k). Check both and see if <unavailable> is listed as something useful in either. If neither of those then check `about:debugging` and scroll to Greasemonkey. Click debug and go to the console tab. Reload your page and see if that has anything useful.

And yes, it's VERY annoying to have three consoles in which certain objects are 'unavailable.'

**Comment by arantius** [comment]
> ... if you violate the policy that GM.xmlHttpRequest and await GM.getValue need to be in an async function ...

There is no such policy.  *If* you use the `await` keyword, this is only valid in an `async` function.  This is only one of several possible code styles.

That said, this looks like more of a support case than a bug, please head to https://groups.google.com/forum/#!forum/greasemonkey-users .
