### ISSUE TITLE
GM.xmlHttpRequest doesn't support onprogress event

### ISSUE THREAD

**Issue by ccloli** [greasemonkey/greasemonkey#2712]
```js
// ==UserScript==
// @name        GM.xmlHttpRequest
// @version     1.0
// @description GM.xmlHttpRequest
// @match       <all_urls>
// @include     *
// @connect     *
// @grant       GM_xmlhttpRequest
// @grant       GM.xmlHttpRequest
// ==/UserScript==

var GM_xmlhttpRequest = GM_xmlhttpRequest || GM.xmlHttpRequest;

GM_xmlhttpRequest({
  method: 'GET',
  url: 'http://localhost/100MB.bin',
  responseType: 'arraybuffer',
  onprogress: res => console.log(res),
  onload: res => console.log('loaded', res.response.byteLength, res.responseHeaders),
  onerror: () => console.log('error')
});
console.log('request started');
```

The log when using GreaseMonkey (onprogress event is not working):
![image](https://user-images.githubusercontent.com/8115912/33008887-e2b6914a-ce0f-11e7-8d5d-bbfd07f539a3.png)

The log when using Tampermonkey (expected, despite the annoying ArrayBuffer converter):
![image](https://user-images.githubusercontent.com/8115912/33009082-93058240-ce10-11e7-990a-ef4460cf64cf.png)

**Comment by arantius** [comment]
This is in build 4.1beta5 ( https://addons.mozilla.org/firefox/downloads/file/793791/greasemonkey-4.1beta5-an+fx.xpi?src=devhub ).  Testing and confirming would be appreciated!
