### ISSUE TITLE
@Match problem (not ports)

### ISSUE THREAD

**Issue by Owyn** [greasemonkey/greasemonkey#2715]
Just noticeed that after migration to new FF and GM4 my match:
`// @match		*://*.gelbooru.com/index.php?page=post&s=view&id=*`
no longer fires on url (example)
https://gelbooru.com/index.php?page=post&s=view&id=2865115

while simple `// @match		*://*.gelbooru.com/*`
fires on that url

was working perfectly in GM3, but in GM4 it has this weird bug... 

whole script if you wonder: https://github.com/Owyn/HandyImage/raw/master/HandyImage.user.js

**Comment by arantius** [comment]
Ok inside `MatchPattern.doMatch` we're doing `this._pathExpr.test(url.pathname)` but pathname is just `/index.php`.  We need to test `this._pathExpr.test(url.pathname + url.search)`.

**Comment by NoneGiven** [comment]
Also, a `@match` like this:

`// @match         https://example.com/path

Will fire on a page like this:

`https://example.com/path?query=whatever`

Is it supposed to do that, even without a trailing `*` in the `@match`?

**Comment by tobbexiv** [comment]
This is due to the same matching issue arantius explained. Everything of the search query is not considered in the matching. In your case it is `?query=whatever` what is ignored at all.

**Comment by arantius** [comment]
This fix should be in 4.1beta6; testing and confirming this would be very appreciated!

https://addons.mozilla.org/firefox/downloads/file/800957/greasemonkey-4.1beta6-an+fx.xpi?src=devhub

**Comment by NoneGiven** [comment]
@arantius Seeing my query string matching scripts run where they're supposed to now in FF 57 (well, except for in frames).
