### ISSUE TITLE
the script editor using system editor?

### ISSUE THREAD

**Issue by RazgrizHsu** [greasemonkey/greasemonkey#2718]
Dear, 

previous version the script allow editor with system text editor
the v4 not found this option,

can you tell me how to using custom editor?

**Comment by Eselce** [comment]
See #2710

**Comment by arantius** [comment]
#2710 is the complete opposite of this issue.

That said, for all intents and purposes you can not, and you won't ever be able to.  (Maybe in the distant future you will, but for now there's a lot of other more important work to be done.)
