### ISSUE TITLE
Consider shipping backwards-compatible APIs for a while

### ISSUE THREAD

**Issue by poke** [greasemonkey/greasemonkey#2725]
Right now, we’re in kind of a terrible situation:

- Users will be auto-updated to Greasemonkey 4 in order to keep the extension working on Firefox 57.
- Greasemonkey 4 is backwards incompatible to the user script API that Greasemonkey originally introduced.
- User scripts have to be updated in order to work with Greasemonkey 4.
- The [CSP bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1411641) in Firefox 57 currently prevents users from being able to update scripts on many domains.

So users will get pushed to GM4 with incompatible scripts that they cannot properly upgrade, which causes many frustrations. This is mainly because GM4 decided to introduce a backwards incompatible API. While I understand the desire to move to a better designed API for user scripts, this puts Greasemonkey in the situation where it’s the *only* user scripting manager that does not support the API it originally introduced.

In order to allow for a transitioning phase for user scripts, especially considering the current problems with updating scripts, I would suggest to include ~~the [available polyfill](https://github.com/greasemonkey/gm4-polyfill)~~ backwards-compatible APIs by default for a while (at least until Firefox 58 is out and fixed that update bug). That way, existing scripts don’t just end up being broken.

**Comment by StigNygaard** [comment]
It wouldn't be enough adding the polyfill by default. The polyfill makes it possible to support Tampermonkey (etc.) _when using the new asynchronous API_. Not the other way around...

**Comment by poke** [comment]
@StigNygaard Oh yes, you’re right. I forgot about what direction the polyfill was for. Then we would need a polyfill that provides the old methods here. Is there no way to patch these into GM4? Or at least provide those that could work?

**Comment by Eselce** [comment]
Hmm, please consider, that it's not THAT easy. You can't trivially reproduce a 3.x `GM_*` function by a function using 4.x `GM.*` functions. You can easily switch from synchronous to `async` functions, but not the other way round.

I've migrated some scripts now, and I used a combination of `Promise`'s `then`/`catch`, `async`/`await`, callback functions and preloaded collections of data (for `GM.getValue`). There was no straight way to do this. I had to change the framework a bit...

**Comment by StigNygaard** [comment]
I have tried creating a simple "synchronous API" which should work both for GM4 and other userscript managers:
https://github.com/StigNygaard/GMCommonAPI.js
But you still need to update your userscripts for it to work...

**Comment by poke** [comment]
I’m not saying it’s easy, and I know that this requires quite some effort.

But right now, GM4 put itself in a pretty bad spot and at the moment, there is really *no reason* for users to stay on it when not only the experience is greatly reduced due to the rewrite (which is totally expected with the WebExtensions move) but also scripts start to break without a chance to update them.

I just believe that this will hurt Greasemonkey in the long run more than it should. I totally understand the desire to use this chance to revamp the user scripting API and it is certainly moving in a better direction. But the timing makes this *very difficult*.

**Comment by Sxderp** [comment]
The API problem stems from WebExtensions being asynchronous. If Tampermonkey is shipping all of the privileged API calls in a synchronous manner on FF57, them I'm curious on how it's done.

**Comment by Eselce** [comment]
@StigNygaard You've said it all:
> Notice, if you are ready to use an asynchronous API in your userscript (including the refactoring probably needed), you can use a library wrapping the classic API into the new asynchronous API. This will give you a larger cross-compatible API than using `GMC`. Adapting your userscripts to use an asynchronous cross-compatible API like `gm4-polyfill.js` is the recommended way to go forward for optimal performance and "API completeness". `GMC` might just be a bit easier and faster to use for some of us.

**Comment by arantius** [comment]
This is effectively impossible, by design decision.
