### ISSUE TITLE
Can not use $ Object in grant none anymore

### ISSUE THREAD

**Issue by fdellwing** [greasemonkey/greasemonkey#2726]
I use the site included jQuery in some scripts and since GM 4 I'm unable to use it. It is always undefined.

Will this be fixxed, or ist this intended?

Because of #2683 I can no simply use my own jQuery.

**Comment by NoneGiven** [comment]
Dupe of #2653 and #2700. If GM sandboxing can be changed, this might work in the future.

You can access jQuery at `window.wrappedJSObject.$` as a workaround.

**Comment by fdellwing** [comment]
Well, it's not optimal, but should work I hope.

**Comment by arantius** [comment]
https://arantius.com/misc/gm-test/jquery.user.js

Works?

**Comment by Sxderp** [comment]
@arantius This was about using the page jQuery object, not one that is added through requires.
