### ISSUE TITLE
Embedded editor doesn't save script with cmd+s on Mac

### ISSUE THREAD

**Issue by timotr** [greasemonkey/greasemonkey#2727]
Adding event.metaKey to keyboard event check would fix this. Currently Ctrl+S does work so it isn't critical.

**Comment by Eselce** [comment]
Do you already use #2691 fixing #2690 ?

**Comment by Sxderp** [comment]
This has been merged but no release has been pushed to AMO.

**Comment by Eselce** [comment]
Yes, but for sure, this is a `duplicate`...

**Comment by Sxderp** [comment]
> Yes, but for sure, this is a duplicate...

Only @arantius has permissions to set tags / close. And today is an American holiday.

**Comment by Eselce** [comment]
@Sxderp  I know, and he was even here for 10 minutes!

I'm not the one to set a `duplicate` tag or close (@arantius, @timotr).
But I'm able to comprehend, that it's a `duplicate` issue.
When I tried to ask a rhethorical question (answer `no`),
you noticed, that it's not been pushed yet. And now,
I'm in the mess having to explain it... ;-)

**Comment by arantius** [comment]
Back and forth between the kitchen! =)
