### ISSUE TITLE
Re-add custom user include/exclude settings, per-script

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2728]
Compare the features of old GM, and TM, and VM.  Pick a nice set of those and add to GM4.

**Comment by arantius** [comment]
ViolentMonkey: You open a script's editor, then there's a "Settings" tab:

![image](https://user-images.githubusercontent.com/84729/42102782-035168b6-7b95-11e8-8d61-1c33abdeeb6e.png)

Which lets you tweak several top level values (name, run at, URLs), plus include/exclude/match/exclude-match rules; each of the latter with a (default checked) "keep original" checkbox.

**Comment by arantius** [comment]
Tampermonkey:

Right in the toolbar popup offers a "..." button with an "exclude" menu item, for the current domain:
![image](https://user-images.githubusercontent.com/84729/42102957-8f73488c-7b95-11e8-8118-67e538910a0c.png)

Also has a settings tab under the script editor:
![image](https://user-images.githubusercontent.com/84729/42103042-ddcb5f06-7b95-11e8-9806-a3129ae0d380.png)

With six different boxes, three display the script's include/match/exclude values, with (checked by default) "Original" checkboxes that can turn off these values, and "user" include/match/exclude" boxes, which each have an add/edit/remove button.  There's helper buttons for coping the script values into a particular user value each.

**Comment by arantius** [comment]
See all the commits I just pushed.  It looks like:

![image](https://user-images.githubusercontent.com/84729/43346403-f6877bda-91be-11e8-89fa-120f36c6ff47.png)

I want to add at least a "+" of the current domain, like exists for global excludes already, before calling this done.  As always, testing of the next nightly build ( http://arantius.com/misc/gm-nightly/ ) including these is greatly appreciated!

**Comment by Eselce** [comment]
Is it "User" opposite to "Global"?

**Comment by arantius** [comment]
Whoops, tagged a commit in the wrong issue (#2531): c543fad0c3b71d0dc89aebcaa6ef552f972ff53a

With that, I'm happy with this feature.
