### ISSUE TITLE
Scripts don't run on pinned tabs?

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2729]
I've got nothing but a vague symptom to describe at this point, but I've seen this commonly over recent time, always running the latest AMO beta:

When I launch my browser, with "tabs from last time", my pinned tabs (at least) don't see matching user scripts execute.  When I later notice this and reload the page, then they do.

**Comment by Sxderp** [comment]
Could have something to do with 'load order'? I vaguely remember reading some comment on Bugzilla that there's no guarantee that an extension will be able to load / execute code before a page first opens on startup.

Could be off base though, I can't remember on what bug I saw this on.

**Comment by xor10** [comment]
> I vaguely remember reading some comment on Bugzilla that there's no guarantee that an extension will be able to load / execute code before a page first opens on startup.

https://bugzilla.mozilla.org/show_bug.cgi?id=1378459
