### ISSUE TITLE
Script editor should expose (text) resources

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2733]
I've got a script ( https://arantius.com/misc/greasemonkey/ebay-butler.user.js ) which has a CSS resource ( https://arantius.com/misc/greasemonkey/imports/ebay-butler.css ).  That resource is injected into the page.  I need to fix its contents.

Now I can only do that by remotely editing the file and re-installing the whole script.  I should be able to edit the resource in place.

**Comment by Sxderp** [comment]
> ... expose (text) resources ...

I suppose detection through mime-type?

Slightly tangent to the issue, should `@require` and `@resource` be re-fetched when the scripts are updated? That is, through the updater interface / autoupdate when said things are implemented. Of course that'd bring up concerns with local modifications, but that issue applies to local modifications of the script itself too.

**Comment by bopoh13** [comment]
Tell me please, why in version 4.x does not work auto-update scripts (scripts loaded from GitHub)? Have you encountered this problem in FF (this may be affected by internal browser settings)?

**Comment by bopoh13** [comment]
Tell me please, why in version 4.x does not work auto-update scripts (scripts loaded from GitHub)? Have you encountered this problem in FF (this may be affected by internal browser settings)? The problem can be due to the fact that [the site have changed](https://github.com/bopoh13/docs/commit/7aca29d2)?

**Comment by arantius** [comment]
This was something I always wanted (see how long ago this was filed), and a recent new batch of work to do got me to look into it again.

**Comment by arantius** [comment]
This should be done.  I could use your help testing this!  Checkout or download Greasemonkey's source code, then follow [the documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing) for installing an extension during development.  As far as I know this will break installed scripts, so you should [use about:profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_manage-profiles-when-firefox-is-open) to create and launch a new blank Firefox profile to do so, rather than overwriting your existing Greasemonkey install.  (Maybe take a Greasemonkey backup first to be safe.)

Any testing results, positive or negative, would be great.
