### ISSUE TITLE
(feature request) Linting in the embedded editor

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2735]
_Split of https://github.com/greasemonkey/greasemonkey/issues/2710 as per https://github.com/greasemonkey/greasemonkey/issues/2710#issuecomment-347647119._

In GM 4.0, there is only an embedded editor.  Browser Extensions have no access to the file system, so you can no longer author user scripts in your familiar text editor.

Here is the list [of the currently used addons in the embedded editor](https://github.com/greasemonkey/greasemonkey/blob/master/src/content/edit-user-script.html),
Regarding the linter: [as I see](https://github.com/greasemonkey/greasemonkey/commit/aee6329bb7ac184d85fff29a3ee3c0e514eceea7), the lint addon (w/ parse-meta-line.js) is currently used only to show errors in the _metadata_ block. 

&nbsp;
I believe it would be great to have **linting while editing**, 
_available via adding the [lint.js](http://codemirror.net/doc/manual.html#addon_lint)  CodeMirror addon. _Requires [JSHint](https://github.com/jshint/jshint)_. ([demo](http://codemirror.net/demo/lint.html)),_

&nbsp;
What do you think? Would you like to have this feature, or it would just get in your way?

**Comment by Cerberus-tm** [comment]
I would like to have linting in the editor. However, I would much prefer to be able to use my own editor (e.g. Sublime Text), if that were possible through 'native messaging'. In that case, the editor itself could remain basic. I'm not a programmer myself, alas, so I have no way to contribute.

If a linter were to be added, I'd much prefer ESLint over JSHint, because ESLint shows many more (useful) errors than JSHint. It seems Violentmonkey (which I've never used myself) uses ESLint, so I guess that would be technically possible?
https://github.com/violentmonkey/violentmonkey/blob/master/.eslintrc.js

**Comment by arantius** [comment]
Because this is the one of the features you've suggested that I personally want the least, I'm choosing this as a place to say in general for all of them: if we add all these features, first we need to build a system for letting each user opt in/out of each of them.

**Comment by darkred** [comment]
> If a linter were to be added, I'd much prefer ESLint over JSHint, because ESLint shows more (useful) errors than JSHint, at least in my experience, and it locates the exact character where the error is more often. It seems Violentmonkey (which I've never used myself) uses ESLint, so I guess that would be technically possible?
> https://github.com/violentmonkey/violentmonkey/blob/master/.eslintrc.js

@Cerberus-tm Violentmonkey doesn't offer linting.
_The file you linked is just a configuration file that one that wants to contribute to that project 
should use in order to follow the style that is already being used in the code ._

Personally I prefer ESLint to JSHint way more, as well, and yes, [ESLint is far more popular than JSHint](http://www.npmtrends.com/jshint-vs-eslint), but 

- in order to work, [you need to specify a configuration file](https://eslint.org/docs/user-guide/getting-started) (local or global) ([screenshot](https://user-images.githubusercontent.com/723651/33399288-c0b15ed4-d55a-11e7-9774-3f5fe01ee21c.jpg)) - [that's not necessary with JSHint](http://jshint.com/docs/).
- Additionally, FWIW, [codemirror-lint-eslint](https://github.com/angelozerr/codemirror-lint-eslint) -which provides the [eslint-lint.js](https://github.com/angelozerr/codemirror-lint-eslint/blob/master/eslint-lint.js), the only CodeMirror addon available to use lint.js with ESLint - is abandoned 3 years now. (also see [here](https://groups.google.com/forum/#!topic/eslint/_If8mxLNdgI))

**Comment by Cerberus-tm** [comment]
@darkred Ah, I see, I jumped to conclusions. A pity that the incorporatable version of ESLint has been abandoned. One more reason to hope for 'native messaging' support (although that might be too complicated, no idea).
