### ISSUE TITLE
Switch to vector icon

### ISSUE THREAD

**Issue by iology** [greasemonkey/greasemonkey#2739]
Tested on Firefox 57, 58
﻿
<img alt="screenshot" src="https://user-images.githubusercontent.com/23622455/33439496-8d7bfab4-d628-11e7-9fcb-d27741b8e018.png" width="345">

```xml
<xul:image
  xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"
  anonid="icon"
  class="icon"
  src="https://addons.cdn.mozilla.net/user-media/addon_icons/0/748-64.png?modified=1510954212"/>
```

The biggest icon provided by GM is not big enough. It should be at least 96x96 (192x192 or larger for high dpi displays).

Firefox can auto-sacle a big image (like 400x400) for GM, so a bigger icon always helps.

UPDATE: opened an issue for Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1422026

**Comment by arantius** [comment]
The first half has nothing to do with us.  The second: We've got the assets we've got, I can't do much about that.

**Comment by iology** [comment]
> We've got the assets we've got, I can't do much about that.

Is contribution welcome? I can try to make a bigger one for you.

**Comment by arantius** [comment]
We're open source, so the simple answer is yes.

I've grown pretty attached to this particular imagery over the years we've had it though so, how closely can you match the style?

**Comment by iology** [comment]
Draft: <img alt="2x" src="https://user-images.githubusercontent.com/23622455/33468192-647a7aa6-d695-11e7-9ac6-84f9d9e701b1.png" width="122">

**Comment by arantius** [comment]
Nice.  Vectors hopefully?

**Comment by iology** [comment]
Yes, in svg format. We can also get a flatter one by removing the gradient effect.

**Comment by arantius** [comment]
Just to sanity check, what I see now.  Both with `Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0`; before is at 9d2783f06f5ff02e693ac0e7c9e54399867f54d3 and after is at 7f6f4164ecf1595d2c9a5307502bc32e63f76969.

Place | Before | After
--- | --- | ---
Toolbar | ![screenshot from 2018-01-19 11 30 24](https://user-images.githubusercontent.com/84729/35160770-2b78553c-fd0c-11e7-8ab6-e3d72d683a85.png) |  ![screenshot from 2018-01-19 11 33 27](https://user-images.githubusercontent.com/84729/35160900-96c1d4b2-fd0c-11e7-995b-20577de1a09e.png)
Add-ons |  ![screenshot from 2018-01-19 11 30 56](https://user-images.githubusercontent.com/84729/35160798-3fb89232-fd0c-11e7-973e-a3dd81415b58.png) | ![screenshot from 2018-01-19 11 33 48](https://user-images.githubusercontent.com/84729/35160909-a03d4ddc-fd0c-11e7-9327-4a0c28c0b60f.png)
Add-ons detail |  ![screenshot from 2018-01-19 11 32 09](https://user-images.githubusercontent.com/84729/35160857-67c6d18a-fd0c-11e7-9c47-5973f6398791.png) | ![screenshot from 2018-01-19 11 35 41](https://user-images.githubusercontent.com/84729/35161008-e5dff1b4-fd0c-11e7-8b0f-939dc47b0dcf.png)

Differences remain, but they're tiny, and the SVG form looks good at all sizes.  Let's move forward!

**Comment by Sxderp** [comment]
> Let's move forward!

Is there anything else, or is it just this issue needs to be closed and #2749 merged?

**Comment by arantius** [comment]
There's just some delay between when I make comments (real time) and when I build/test/merge/push/etc. -- the latter often bundles a few things.

**Comment by iology** [comment]
I'll keep polishing it in my spare time. :D The svg icon is undoubtedly flat because it is hard to have fine-grain control of the gradience effect without utilizing embedded rasterized image.
