### ISSUE TITLE
[Enhancement] Make back button bigger

### ISSUE THREAD

**Issue by stonecrusher** [greasemonkey/greasemonkey#2740]
The UI would be more user friendly if the back button link was the whole green area, not just the little arrow on the left:
![screenshot 90](https://user-images.githubusercontent.com/1388389/33458681-70346c12-d627-11e7-9d95-3e7eb475b090.png)

Firefox 57.0.1 (64-Bit), Greasemonkey 4.0

**Comment by Sxderp** [comment]
I don't think this is entirely clear. To me it doesn't make sense to click on the script name and have that navigate me back. 

On the other hand the back button is somewhat small. I would be in favor of increasing the width 3x or so.

**Comment by Sxderp** [comment]
And perhaps change it to an arrow instead of a chevron.

**Comment by arantius** [comment]
The existing menu is styled after, and generally similar to, the main/hamburger menu in Firefox 57.  A hover effect like it has definitely makes sense.

**Comment by stonecrusher** [comment]
> The existing menu is styled after, and generally similar to, the main/hamburger menu in Firefox 57.

Yep, it has the same problem.

Fortunately when activating / deactivating Greasemonkey you don't need to aim for the little checkbox (or is it "checkcircle" here? Not sure about the english word), it's already user friendly ;-)

I like the link over whole width with hover effect best (also for consistency), but just making the button wider is also ok!

Just wanted to point on that "issue" which is just a minor detail but I had to edit a lot of scripts and test single ones so it became a bit annoying after a while.

**Comment by arantius** [comment]
I believe cfd74d716e8351688be9114f663471196e4122fb effectively did this.

**Comment by stonecrusher** [comment]
Unfortunately not. The button is still small and now the letters are cut at the bottom:
![screenshot 3](https://user-images.githubusercontent.com/1388389/36568358-f683cf12-1829-11e8-9cce-ebfe09f30b4f.png)

**Comment by Sxderp** [comment]
cfd74d7 was to make the UI look and behave like a native FF menu. So that's what it does. As for having the whole top bar go back, i don't know. That doesn't make sense to me. 

On a different note. And something I'd really like to solve, is your text offset issue. 

Can you give me OS, FF version, GM version, OS language settings, FF UI settings (compact, themes etc) and any other information that you'd like to dump (lol).

**Comment by Eselce** [comment]
As a right hander, I really have problems to hit that arrow. I tend to hold the mouse on the right side with my right hand, so that I don't mess around with controls ("neutral mode"). To hit that arrow, I have to move the mouse right over the whole menu to get to the arrow. Would be easier (and faster) to just hit the top bar to return to the main menu.

**Comment by stonecrusher** [comment]
> That doesn't make sense to me.

I don't know what anyone would expect to happen instead. When you get there, you just clicked at the style name before, so what should clicking at the style again do if there are already separate buttons for enable, edit and uninstall? Hovering suggests it has something to do with the back-arrow.  The top most option often is the back-function (see file systems).
Furthermore there's a back arrow in front, the same principle as with the button "enabled". The label also doesn't explicitly tell you, what it does (it disables). Hovering suggests the connection to the preceding icon. If you don't know, you'll find out by clicking there once. Nothing bad happens. Setting a tooltip would be over the top, users are not stupid (ok, no real UI programmer would ever say that...)

----
For the cut off text, as written above:
`Greasemonkey 4.3beta5`
`Firefox 60.0a1 (2018-02-22) (64-Bit)` (happens with all three default schemes)
`Windows 8.1 home`, 125% scaling (should be also pretty standard because with 100% the text is *really* small. Can't remember having changed that.)
German localization for Windows and Firefox

Does not happen with Windows 7 home x32 (english), basic and classic colour schemes, 125% scaling (I think that's standard for nowadays resolutions and called "medium"), same GM and FF versions as above, just x32.

If you need further information, just ask back, I don't know what else could be helpful. But everything should be pretty standard because those are virtual machines with barely any software on it. OS is up to date.

I can't inspect the menu by myself, I always just get to the outer container `browser.webextension-popup-browser`.
Note that it seems that only the last item in a line doesn't have proper vertical alignment. So the text of scripts in the main menu are ok, just the corresponding rightarrow is shifted down. Accordingly new script and help items are shifted.

**Comment by Eselce** [comment]
> Windows 8.1

Third case of Win 8.1 (apart from one Win 7, that was a bit different).
Looks like it's okay with Win 10, Linux, etc.
