### ISSUE TITLE
GM 4.0 cannot access window.*

### ISSUE THREAD

**Issue by AlexP11223** [greasemonkey/greasemonkey#2741]
Is it possible to access `window` in GM4/FF57?

Looks like all my scripts (with `@grant none`) fail when trying to access anything global, such as `window.SECURITYTOKEN`, jQuery embedded on the page (`$`), etc.

**Comment by Sxderp** [comment]
Dupe of #2653 and #2700 
Caused by using an extension 'content script' scope to run userscripts instead of an injected `<script>` tag like VM.

**Comment by Eselce** [comment]
... and #2726 and more...
