### ISSUE TITLE
Test coverage report broken

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2745]
When run:

    Failed to parse file: .../src/bg/user-script-install.js
    04 12 2017 20:32:12.832:ERROR [preprocessor.coverage]: Line 5: Unexpected token function
      at .../src/bg/user-script-install.js
    Failed to parse file: .../src/bg/user-script-registry.js
    04 12 2017 20:32:12.836:ERROR [preprocessor.coverage]: Line 68: Unexpected token function
      at .../src/bg/user-script-registry.js
    04 12 2017 20:33:31.446:WARN [karma]: Port 7328 in use
    Firefox 57.0.0 (Ubuntu 0.0.0) ERROR
      SyntaxError: missing ; before statement
      at http://localhost:7329src/bg/user-script-install.js:1

**Comment by Sxderp** [comment]
Those lines have `async function`.
The coverage apparently doesn't like that construct.
