### ISSUE TITLE
Donate to Greasemonkey

### ISSUE THREAD

**Issue by jasp00** [greasemonkey/greasemonkey#2752]
I would like to thank Greasemonkey by donating a symbolic amount. May I donate to the project or to a charity of your choice?

**Comment by arantius** [comment]
Glad you like it!  There's no structure in place to enable this.  It would be difficult (impossible?) to fairly route/distribute the funds, given the open/shared nature of the project.

**Comment by jasp00** [comment]
Since you have not designated a target, I will choose. I have donated to Debian mentioning your software. Anyone else can [donate](https://www.paypal.com/cgi-bin/webscr?business=debian-payments@spi-inc.org&cmd=_donations&item_name=Debian Project via Software in the Public Interest, Inc.&item_number=https://packages.qa.debian.org/greasemonkey) too.
