### ISSUE TITLE
With GM 4 and FF 57 - where are the userscripts stored

### ISSUE THREAD

**Issue by erjdriver** [greasemonkey/greasemonkey#2753]
With GM 4 and FF 57 - where are the userscripts stored?

When I select "edit" for the script - it opens a tab in the browser.

I'd like to edit the script in my own editor.

**Comment by StigNygaard** [comment]
https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html
https://github.com/greasemonkey/greasemonkey/issues/2513

**Comment by erjdriver** [comment]
Thanks - but I don't see that question being answered on that site.

Though I might be missing it - any help appreciated.

**Comment by StigNygaard** [comment]
> First, there is only an embedded editor.  Browser Extensions have no access to the file system, so you can no longer author user scripts in your familiar text editor.
https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

In https://github.com/greasemonkey/greasemonkey/issues/2513 you find some more info and maybe a tip you can use.

**Comment by erjdriver** [comment]
Ok thanks.
