### ISSUE TITLE
Getting <unavailable> on an await

### ISSUE THREAD

**Issue by erjdriver** [greasemonkey/greasemonkey#2754]
I've got the following construct for GM4

`
async function myfunc()
{
await GM.getValue( "test", "" );
}
`

And it runs.

But when I put in inside the a GM.xmlHttpRequest call 

`async function myfunc()
{
		GM.xmlHttpRequest({
			method: 'POST',
			url: gets("~https://www.test.com/test/connect2"),
			headers: {
			'Accept': HTTP_ACCEPT,
            'User-Agent': HTTP_USER_AGENT,
			'Content-type': 'application/x-www-form-urlencoded',
		},
		data: args,
		onload: function(responseDetails) {

                 await GM.getValue( "test", "" );
                });
}

I get &lt;unavailable> error - unable to run script.

**Comment by TiLied** [comment]
You called [await](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/await) in sync function. Should work. 
```
function myfunc(){
GM.xmlHttpRequest({
method: 'POST',
url: gets("~https://www.test.com/test/connect2"),
headers: {
'Accept': HTTP_ACCEPT,
'User-Agent': HTTP_USER_AGENT,
'Content-type': 'application/x-www-form-urlencoded',
},
data: args,
onload: **async** function(responseDetails) {
             await GM.getValue( "test", "" );
            });
}
```

**Comment by erjdriver** [comment]
You sir - are a genius!
