### ISSUE TITLE
Question about async/await?

### ISSUE THREAD

**Issue by erjdriver** [greasemonkey/greasemonkey#2755]
I've got the following code:

`var g_sys_prefix;

async function myGetValue( pref, def )
{
	if ( g_sys_prefix == undefined )
  {
				console.log( "A" );
  	    g_sys_prefix = await GM.getValue( "prefix", "" );
				console.log( "B" );
  }
	
  console.log( "C" );
  
	return await GM.getValue( g_sys_prefix + pref, def );
}

console.log( "D=" + myGetValue("test") )`
I was expecting a printout of A B C and then D.

But I'm getting A D B and C.

My understanding was AWAIT keyword made it a synchronous call.

I'm porting over a large pre GM4 script and it depends on this synchronous behavior.

**Comment by tobbexiv** [comment]
The async keyword makes the function execution again asynchronous. So a call of myGetValue again returns a Promise which resolves to the value you return.

In an asynchronouse function these two statements have exactly the same effect:
`return await GM.getValue( g_sys_prefix + pref, def );`
`return GM.getValue( g_sys_prefix + pref, def );`
In both cases a Promise is returned which resolves to the function. This is also the reason why the logging is not as you expect.

The easiest solution would be to wrap the `console.log( "D=" + myGetValue("test") )` statemant again in an async function and use the await keyword, however this would lead to a long list of asyn cuntions and a lot of await keywords. A better approach would be to use the `then` property of the Promise object. However, this requires further checks and analysis to avoid unwanted side effects.

**Comment by Eselce** [comment]
... and `then`/`catch` will also return a Promise, so you can't really get rid of the async approach.
Best is to rearrange your program such that the async function makes sense, easiest with `then`:
`myAsyncFun().then(myReceivingFun)`, where myReceivingFun may be `result => value(result)`, `result => { doSth... }` or a `function myReceivingFun(result) { doSth... }`. And it may be chained (this one does not include any `catch` calls):
```
prelimData().then(
        data => stepOne(data)).then(
        resultOne => stepTwo(resultOne)).then(
        resultTwo => stepThree(resultTwo))... ;
```
or shorter
```
prelimData().then(stepOne).then(stepTwo).then(stepThree)....catch(err => console.error(err));
```
`promise.catch(console.error)` will probably work as well. `then` should pass `reject`-ed `Promise`-s through, if I am right.

But generally, the code after this statement will be executed immediately (not waiting for the result),
so probably, you want to have this chain as the last (return?) statement in a function block...

await is just good for local blocking within async functions (serialization of async tasks).

**Comment by erjdriver** [comment]
I got it to work by 

`console.log( "D=" + await myGetValue("test") )`

But as @tobbexiv wrote,  I would eventually have to put an ASYNC before every function declaration and an AWAIT before every function call.

And I've got a 15K line script!

@Eselce - you're saying that I should use THEN chains within each function (as opposed to AWAIT) and then prefix the function with ASYNC. When I call this function, use AWAIT.

e.g.

`async function test()
{
   GM.getValue("var).then(result => { return "ok";}).catch( e => console.error(error));
}

console.log( "result=" + await test() );

console.log( "after await")
`

Please forgive the formatting - i select INSERT CODE and it still does this.

If no error, it'll print 
"result=ok"
"after await"

If error, error will be printed to console AND ??? what happens to the waiting "await test()" call?

Will it ever print "after await"?

**Comment by erjdriver** [comment]
Just wrote a short test snippet.

`async function test()
{
   GM.setValue( "test", "hello").then( () =>
   {
       return GM.getValue( "test" );
   }).then( val =>
   {
	console.log( "result=" + val );
    }).catch (e => console.error(e) );
}

(async function()
{
  await test();
  console.log( "done");
})();
`
I was expecting

result=hello
done

I got the reverse.

I was under the impression that `await test()` would wait for the function to to be done.

I'm sure the correct answer is that test() returns a Promise and I've got to do a THEN etc.

But then what does await do???

I can take out the await and get the same result.

**Comment by Sxderp** [comment]
> How would I chain these calls

```javascript
var v1_promise = GM.getValue('val1');
var v2_promise = GM.getValue('val2');
var v3_promise = GM.getValue('val3');

var get_all = Promise.all([v1_promise, v2_promise, v3_promise]);

get_all.then(items => {
  var v1 = items[0];
  var v2 = items[1];
  var v3 = items[2];
  ...
});
```

**Comment by erjdriver** [comment]
Thank you - 

I was chaining them then().then().then() and was driving me crazy!

**Comment by Sxderp** [comment]
Alternatively, if you're already inside a promise chain.

```javascript
some_async_func().then(() => {
  /* Assume same setup for v*_promise */

  // Just return an array of promises, this /should/ work.
  return [v1_promise, v2_promise, v3_promise];
}).then(items => {
  var v1 = items[0];
  var v2 = items[1];
  var v3 = items[2];
  ...
});
```

**Comment by Sxderp** [comment]
If the above doesn't work, then doing `return Promise.all([v1_promise, v2_promise, v3_promise]);` will definitely work.

**Comment by Eselce** [comment]
@erjdriver I didn't mean to put everything in chains, just the main structures (sorry, I was really tired, when I wrote that!)

I think, it's best to have a mix of `async`/`await`, `then`/`catch`, `Promise`/`Promise.all`...
For your GetValue calls: I would definitely group it together, `Promise.all` is a very good choice for that. Preload the data you need for your project, after that, execute your main function.

A very special alternative: In my most challenging script(s), I already had a framework to fetch data (sooner or later). What I did, was to extend the property showing if an item was loaded with a Promise of the data loading. But that's a bit more complicated and depends on your data...

`Promise.all`: A very clever function for parallel threads with a little pitfall: If you get an error (`reject`) in one of the `Promise` elements, then **all** elements are `reject`-ed. This could lead to irritation, if you don't obey it...

@Sxderp That would be a nice solution, not sure, if that works. But `Promise.all` is good enough...
