### ISSUE TITLE
How to add my legacy script file to Firefox 57

### ISSUE THREAD

**Issue by erjdriver** [greasemonkey/greasemonkey#2756]
How do I add my legacy script file to Firefox 57?

I read that GM4 doesn't have access to the local file system.

Do I have to store it on a server and then point to from the browser and the GM will auto install it.

Then for subsequent edits, can I do it on the local GM4 >> script >> edit  tab window, or do I have to update the version on the server.

**Comment by Sxderp** [comment]
You can do a `localhost` python server or somesuch to host the files. Or you could use the `create new script` button and then paste the contents.

For subsequent edits you can use the `edit` option in the monkey menu, for any solution.

I'd like to add an 'import file' button, but I'm waiting around for some other merges / commit before I tackle that.

**Comment by erjdriver** [comment]
Where is this `create new script` button?

The edit option brings up the editor - but that editor is very wanting. I do the editing in another editor and then paste into into the GM editor tab - not a very efficient way of working.

**Comment by Sxderp** [comment]
> Where is this create new script button?

Oh, I forget about different published versions. The button was added in `4.1b4` and fixed in `4.1b5`. Latest is `4.1b6`. If you wish to use said version it's under [alternative versions](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta) on the AMO page.

**Comment by erjdriver** [comment]
Thank you for that link.

**Comment by arantius** [comment]
This is not a support forum, this is a bug tracker.

Please head to https://groups.google.com/forum/#!forum/greasemonkey-users for your future support questions.

**Comment by Eselce** [comment]
Thus is was a very good idea to bump `version 4.1` 15 minutes ago! Thanks...
