### ISSUE TITLE
Feature request - print line # when there's a async/await mismatch

### ISSUE THREAD

**Issue by erjdriver** [greasemonkey/greasemonkey#2757]
Right now, if there's an await inside a function without a matching async modifier to the function - GM4 just prints &lt;unavailable> and calls it a day.

I'm trying to migrate a 15K line script and getting this.

Not easy finding it and that browser editor doesn't help.

I request a feature where GM4 can print the offending line#.

**Comment by Sxderp** [comment]
Having better debugging would be great. This is not trivial and mostly limited by Firefox being garbage.

**Comment by arantius** [comment]
We definitely have no control over how Firefox does this.  If this request belongs anywhere, it's at bugzilla.  Otherwise this is #2584 .
