### ISSUE TITLE
Greasemonkey 4.1

### ISSUE THREAD

**Issue by js017** [greasemonkey/greasemonkey#2758]
The older Greasemonkey 3.17 had a better interface, it was easier to use, and had more options. The new versions don't have the user scripts list in tools, add-ons, Greasemonkey in the tools menu, or an advanced options menu anymore. You should change the new version to include those features. Have a good day. Thanks.

**Comment by Sxderp** [comment]
Sigh

**Comment by Sxderp** [comment]
Before someone else comes along and gets super defensive on this subject. I'm going to just say a few things. 

Unfortunately, some of the things you ask for are no long possible. Not for lack of trying, but actual lack of support from Mozilla in what they're allowing 'WebExtensions' to do. 

Modify the addon menu? No, not going to happen and never will happen. 

Advanced options? Eventually. The people who work on this project take their free time to write code, when they could be watching Netflix or something. As far as I'm aware the project doesn't support anyone financially and thus things get done when they get done. 

I understand as a user these changes are frustrating and can feel pointless or unnecessary. We also feel frustrated, frustrated at what Mozilla has given us. An environment wherein their holy grail of an add-on system is half-baked, half-implemented, and regression ridden.

There's also this stigma from Mozilla that it's the add-on developer's fault for things not working. And they push this image to the general user. This is quite sad. In actuality it's a little of both. Mozilla creates an ever moving target while developers struggle to keep up. Perhaps they could run faster. But indeed the ecosystem balances eventually.

**Comment by t33rex** [comment]
After the extension got updated my scripts no longer work (neither in FF 52.5.0 ESR nor in 57.0.2) and are no longer accessible/visible in the UI (although they are still in the gm_scripts directory)

Also clicking the extension icon and then "New user script" doesn't do anything at all.

**Comment by js017** [comment]
After using Firefox for a long time, I finally switched from Firefox to Waterfox because Firefox has basically ruined their browser quality with all the changes they've made, expecially to the XUL and WebExtensions add-ons. Eventually Firefox is going to lose a lot of users because of all of their ridiculous changes to their browser, and people will use other alternatives. Waterfox is based on Firefox, and is still being updated, with a focus on keeping user friendly and advanced features, and XUL support as well as WebExtensions support, so maybe you'd consider continuing to update Greasemonkey and make it compatible with Waterfox. Thanks.
