### ISSUE TITLE
Unable to Save new Created Scripts

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2759]
~~Version 4 broke a lot of scripts for me. Is there a way for me to go back to version 3?~~
Never done it before but it was easy. 

I am not sure how to create a new script also. I can open a new script tab but there is no save button.

**Comment by Eselce** [comment]
1) No, not with Firefox 57+ (the main reason why there is a version 4)
2) Use Ctrl-S (Cmd-S for Mac) - Buttons will be added later

**Comment by TimidScript** [comment]
Thanks
