### ISSUE TITLE
Store Scripts Under gm_scripts directory

### ISSUE THREAD

**Issue by TimidScript** [greasemonkey/greasemonkey#2760]
Is it possible to give back the option of storing scripts under gm_scripts directory?

 I have dozens of self created scripts that are hard linked to several profiles. I also use my own personal editor. With this new release, I am forced to use built in editor and testing over several profiles become a pain as I now have to manual force update across profiles with each little change.

**Comment by Eselce** [comment]
See #2753 (and maybe #2756)

**Comment by TimidScript** [comment]
Thank you. I was about to get rid of the thread as I found there blog post on it. Cannot say I am happy with the changes but there is little they can do. What a pain.
