### ISSUE TITLE
Unclear Message in Console

### ISSUE THREAD

**Issue by GuardianMajor** [greasemonkey/greasemonkey#2761]
I searched in the hopes that it was previously discussed but couldn't find anything on it, so please bear with me. Despite my attention to ensure the extension DOES NOT update to the 4.x version until all script conversions had been tested, somehow last night it managed to install 4.1 and this morning broke a ton of my scripts, that's fine, I will now have to go into fix mode, specially with everything that has `@grant none` but my issue is not this, my question is about a message that appears in the console, and I am not sure what it means.

> updater has no added remotes to handle  user-script-obj.js:349

and it seems to be located in `/src/user-script-obj.js` but for some reason cannot actually open it from the console which normally works fine when you get a message, you can click on it and see where in the script the issue is. But what I wanted to know is what this "error" or "warning" or "notice", not sure what to call it actually means. Any information to shed light on it would be appreciated.

Should be noted, that looking at the code, it seems to be handling the update of the script and perhaps checking for it, but not sure why when there is only one script running on a single tab, it keeps showing up, shouldn't it just check once per load? I am hoping to better understand what is going on and if this is feature/expected behavior or a "bug" of some kind - I don't want to assume.

**Comment by arantius** [comment]
This is benign.  It is informative, it is not an error.

**Comment by GuardianMajor** [comment]
Understood thanks. Just was trying to understand what it is trying to "inform" exactly. As I said, didn't say it was an error per se, just didn't know how to categorize it.

**Comment by Eselce** [comment]
@GuardianMajor It's just the information, that there's nothing to load (besides the main script).
If you read carefully, it's exactly what it says: "no added remotes" (fine, that's okay!),
but I can understand, why you thought, there may be something wrong with it...

**Comment by Eselce** [comment]
@GuardianMajor Additional notice: Don't trust the line numbers (not GM's fault!)
Line 349 looks like the top of the main script for me (meta data section or line 0?),
but the framework adds some 350 lines in front of the code (see other issues)...

**Comment by GuardianMajor** [comment]
@Eselce Yes, I wasn't quite worried about it as I just wanted to know what it was saying, nothing more. And despite the all clear intentions, the wording can easily lend itself as it notifying you of a problem as well, you already noted that.

As for the line numbers, yes I am aware that now it puts a crap load of lines ahead of things due to the overhead of how they are run, so the lines are no longer accurate, nor accessible like they were in the past, namely you can't click on it to open up and show you the source line that caused it, the console is completely useless now in that sense. 

But to clarify, I simply copied the console message, so the line number is with it, not that it is something I put there or expected to be accurate, in case that wasn't clear. I had a script with only 22 lines of code and it was showing an issue on line 489 so clearly impossible without accounting for all the wrapper and bootstrap codes that get put before/around it. SIGH, leave it to Mozilla to completely crap the bed with this nonsense, oh well. Thanks anyway though, appreciate the input.
