### ISSUE TITLE
Error Executing a Script - Cause Unknown

### ISSUE THREAD

**Issue by GuardianMajor** [greasemonkey/greasemonkey#2762]
I have a very simple script that has been working fine and meets all the requirements for the new implementation, however, it generates this error:

> 12:46:56.424 Could not execute user script: [Greasemonkey Script {script name}; 0.4] 
>  <unavailable> 1 execute.js:25

I looked at the source for `execute.js` under `/src/bg` and I see that it has a couple of TODO relating to document start being made to work right and also providing a more useful cause message. As of now, I am not certain what is causing it and without a clear cause, it is hard to figure out how to modify it/resolve it.

The only inclination I have, is that it might be related to `@run-at document-start` and so I decided to remove that requirement and it still results in the same outcome. The error refers you to line 25 which is simply the console output and the `err` is simply `<unavailable>` which I don't quite know how to interpret. 

So I am at a loss as to how to figure out what is ACTUALLY causing the problem so I can address it, any insight you can offer? I have tried to consult the documentation to see if it has been addressed but have not succeeded in finding anything and I did search the issues to see if it was addressed and didn't come across anything, but that doens't mean it wasn't discussed - so if it has been, would appreciate the reference so I can look into any suggestions already offered, if not then please provide some context on how to proceed, thank you.

**Comment by arantius** [comment]
https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help

Generally: comment out and/or wrap in `try {}` everything you can, then start removing them.  Painful but always works.
