### ISSUE TITLE
Greasemonkey script for FlickrAwardCounter (by Phazeshift) stopped working after Greasemonkey upgrade to v4.1 today - Help

### ISSUE THREAD

**Issue by Griffl01** [greasemonkey/greasemonkey#2763]
HI. I am not a techie but a user of the Greasemonkey script for the FlickrAwardCounetr written by Phazeshift.co.uk on my Firefox browser. It has been working well but stopped working today when Greasemonkey seems to have updated to version 4.1. When I press the Greasemonkey Icon on the Firefox browser it says it is active but nothing is happening.

I'm a Mac user running MacOS High Sierra 10.13.1. I run Firefox 54.0.1 (64 bit), Greasemonkey 4.1 (as of today).

I really need to get this script working to do my role on Flickr.

Any help would be very gratefully received and I'm sure I won't be the only one with this problem.

Thanks,

Lynn

**Comment by Eselce** [comment]
I dare to say, that this must be handled by the authors of that script
(especially, if it worked unter GM 4.0 before... or did you work with GM 3.17 before?)
(4.1 included FF 52+, not just FF 57+, as 4.0 did)
