### ISSUE TITLE
Unable to access Youtube functions

### ISSUE THREAD

**Issue by CrendKing** [greasemonkey/greasemonkey#2765]
### Summary
Youtube adds some utility functions to the `movie_player` element, such as quality level control. Firefox web console or other user script engines (e.g. Violentmonkey) can access and invoke these functions. However, Greasemonkey can't access them.

### Reproduce
Install the following script, open Firefox web console and visit any Youtube video.
```
// ==UserScript==
// @name YouTube
// @match https://www.youtube.com/watch?*
// ==/UserScript==
console.log(document.getElementById('movie_player').getAvailableQualityLevels)
```

### Expected result
Something like `function oH/a.A[b]()`

### Actual result
`undefined`

**Comment by arantius** [comment]
This is a result of an intentional design decision combined with the limitations of what webextensions makes available.  Hopefully better once #2549 is unblocked.
