### ISSUE TITLE
Menu doesn't open (Unchecked lastError value)

### ISSUE THREAD

**Issue by tukkek** [greasemonkey/greasemonkey#2775]
As mentioned first on #2651:

---------

I am having a very similar problem on Firefox 52.5.0 on Debian Linux. Menu won't open regardless of being in the toolbar or through the Firefox "Open menu" button. Should I open a new bug or will someone reopen this issue?

**This completely breaks Greasemonkey** since I can't even enable/disable it anymore (short of removing the extension itself) or access any functionality at all.

Everything was working fine until Firefox updated Greasemonkey on December 13, apparently.

Unlike the previous report, the menu doesn't render even on an empty tab.

Console log:

```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. ExtensionCommon.jsm:265
	withLastError resource://gre/modules/ExtensionCommon.jsm:265:9
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:316:11
userScriptsDetail is undefined  monkey-menu.js:34
	loadScripts moz-extension://1b66bdbb-7aea-4eb3-87e5-b163c6371dba/src/browser/monkey-menu.js:34:3
	onLoad/</< moz-extension://1b66bdbb-7aea-4eb3-87e5-b163c6371dba/src/browser/monkey-menu.js:138:11
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:71:14
	runSafeSync resource://gre/modules/ExtensionUtils.jsm:104:37
	runSafe resource://gre/modules/ExtensionCommon.jsm:123:32
	bound runSafe self-hosted:917:17
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:310:31
```

Other than that I'd like to thank all the development team. I've been using Greasemonkey for years and I can' t imagine browsing and working without it anymore :)

**Comment by tukkek** [comment]
@arantius asked me to post this as a new report.

**Comment by Eselce** [comment]
@tukkek That was because the symptom was the same, but the reason was different (see error message). That's why it's a new (different) issue...

**Comment by Sxderp** [comment]
The error

**Comment by Sxderp** [comment]
I think the lasterror bit is somewhat of a red herring. But looking at the rest of the log it seems that sending 'ListUserScripts' is returning undefined for some reason.

**Comment by tukkek** [comment]
> That was because the symptom was the same, but the reason was different

Of course, I understand :) I was just pinging him so he'd know I created the new issue as requested!

> If you don't mind sharing the database / script dump

I'm not sure I'll have time for that in the next days but I'll try to keep it in mind. However, you guys should probably set up some better debugging and fallback mechanisms (possibly clearing the DB). I mean, I don't even know how to hack the database so surely everything in there was put by Greasemonkey itself - so if anything in there is invalid, it most likely just boils down to another bug in GM...

Even if you consider something like a physical hard-drive error or operating system going crazy for some reason and invalidating the file, this is still something that could be caught and handled by the add-on? I mean, completely resetting the DB in case of an error like this is a bit heavy handed, but it's actually better than being stuck with an installation that doesn't offer basic functionality, surely?

**Comment by tukkek** [comment]
I have removed GM, reinstalled it from the AMO page and restarted Firefox. Is that supposed to clear the database? Because I still get the same error when trying to open the menu.

If it doesn't clear the DB, shouldn't GM do that when it's removed, so as to allow people with a "broken" DB to just reinstall it and start fresh in a couple of minutes?

**Comment by tukkek** [comment]
By the way, can you guys point me out how to remove my DB to get my GM working again? I can reproduce the error in one of my two computers but I'd like to have GM working again ASAP on at least one of them. Thanks!

**Comment by Sxderp** [comment]
> If it doesn't clear the DB, shouldn't GM do that when it's removed, so as to allow people with a "broken" DB to just reinstall it and start fresh in a couple of minutes?

As far as I'm aware there is no 'pre uninstall' hook (I could be wrong) for GM to catch and do cleanup. Although, Firefox _should_ be deleting the data. Well, it's suppose to.

**Comment by Eselce** [comment]
AFAIK, the database is purged, when you deinstall an AddOn like GM, so your removal could have prevented @Sxderp from finding any bug. Luckily (not for you), the error occured even after that. But even though, I have no idea, what's wrong with it (why userScriptsDetail is undefined)...

**Comment by Sxderp** [comment]
@Eselce I think Firefox is not deleting the data properly.

@tukkek If you rather not help us debug the issue and fix it in the code, and just want a solution for your immediate database issue then you can open the directory `{FFProfile}/storage/default` and look for a directory `moz-extension+++{UUID}` that corresponds to Greasemonkey and then delete it. Unfortunately, the UUID is randomly generated and I'm not sure how to figure out what one is Greasemonkey.

**Comment by tukkek** [comment]
> I think Firefox is not deleting the data properly

Which is exactly why I wanted to try a reinstall in one of my machines after it had been established it was a database error. I'll see if I can check out if the directory was wiped or not on that particular machine later. Even if the UUID is random I'm guessing it should be easy enough to figure out by the directory's contents...

@Eselce Seems you entirely missed the point when I mentioned I have two installs to test on and only need one of them to work ASAP? You don't need to lecture me on that when I addressed the issue before you even started writing your reply... Jesus, pay attention, will you?

**Comment by Sxderp** [comment]
> I'm guessing it should be easy enough to figure out by the directory's contents...

Not really.

**Comment by tukkek** [comment]
I'm looking at `~/.mozilla/firefox/ieyra6za.default/storage/default` (where `ieyra6za` is the only profile in this user account) and all I see are directories with the `http-++`prefix and website URLs (for example: `http+++www.forbes.com`). I'm guessing these are WebStorage backends? Each folder has a `idb` folder with 2 files inside it (a `.files` and a `.sqlite`).

Could it be that the database is entirely missing? Or maybe I'm looking at the wrong folder? I mean, if it was missing it could explain why some of the memory is undefined, wouldn't it?

There isn't a single `moz-extension+++` folder in here, even if I have several add-ons installed and working perfectly fine (including ones that do need some sort of non-trivial persistence) - just `http+++` and `https+++`.

**Comment by tukkek** [comment]
I also did a search under my my profile directory and no files or directories are all come up containing `moz-extension`. Hope this lead helps in solving the issue!

**Comment by tukkek** [comment]
Final clarification: I'm doing all of this on the machine in which I have **not** removed and reinstalled Greasemonkey. Everything was working fine in here up until the December 13 update, to the best of my knowledge.

I apologize for so many messages in sequence.

**Comment by Sxderp** [comment]
See #2675 , Greasemonkey currently saves the database under `storage/default`. What makes even less sense is that this data does not show up on the system that Greasemonkey hasn't been reinstalled.

It should be noted that a lot of functionality, like storage, is blackboxed from WebExtension authors. We're given a very high level API call and when it's used it's expected to 'work'.

Anyway. can you try with a fresh profile? `firefox --ProfileManager --no-remote`, install GM and see what happens.

**Comment by tukkek** [comment]
>  We're given a very high level API

Of course, I'm fairly familiar with API and Mozilla add-on development myself. 

I'll try the new profile later on tonight if I can.

Is there any chance the database is saved somewhere different on Linux? I know cross-platform applications such as Firefox sometimes use per-platform backends for storage transparently to the developer. Honestly, I can't see where else it would put data on Linux besides `$HOME` (we don't have a system registry or anything like that) but I though it'd be worth considering, since none of my other add-ons seem to have a folder in `storage/default` either.

**Comment by Sxderp** [comment]
> Is there any chance the database is saved somewhere different on Linux?

No, should be the same location. Although, I do notice that you're using the ESR version of Firefox, which might be doing something different. It may be worth just downgrading to 3.17 until you move to a newer version of Firefox.

**Comment by Joe136** [comment]
I played around with a fresh profile and my old prefs.js and found out:
if the setting 'Privacy & Security' -> 'History' -> 'Use custom settings for history' -> 'Accept cookies from websites' is disabled, GM don't work.
@tukkek: do you also have this setting?

**Comment by Sxderp** [comment]
> if the setting 'Privacy & Security' -> 'History' -> 'Use custom settings for history' -> 'Accept cookies from websites' is disabled, GM don't work.

This is a bug with Firefox and IndexedDB. Pretty sure Mozilla was working (heh) on a fix.

**Comment by tukkek** [comment]
> 'Privacy & Security' -> 'History' -> 'Use custom settings for history' -> 'Accept cookies from websites'

I don't use that but I do have cookies erased when I close Firefox (except from sites that I whitelist). This is not an add-on but a built-in feature on the Firefox privacy settings as well. I thought I might report that as well but I couldn't see how it would affect Greasemonkey.

Greasemonkey still doesn't work at all for me, for two weeks now. Was there anything else I could do to help you guys debug this? Sorry, I lost track.

**Comment by Sxderp** [comment]
1. Try with a fresh profile. `firefox --ProfileManager --no-remote`
2. Downgrade to GM 3.17 (since you're using FF ESR) and continue using that.
3. Downgrade to GM 3.17 and then upgrade back to 4.1. GM may attempt to remigrate the old scripts.

---

But as for the storage thing. Running on a RHEL6 system, FF 52.5.1 ESR (basically same as yours), I have a `moz-extension+++` directory under `storage/default`. Removing it just causes it to be recreated when the browser starts.

Is this the only extension that is broken? Missing the `moz-extension+++` directory seems really weird. Like something is broken with the Profile or FF itself.

**Comment by tukkek** [comment]
All other extensions working perfectly and I still definitely don't have any `moz-extension+++` directories under `storage/default`.

**Comment by Sxderp** [comment]
Another thing you could do, aside from the above, is restart Firefox and then open the browser console as soon as possible (`CTRL+SHIFT+J`). You should be able to see any errors during the initial loading of the extension. See if anything comes up in one of the background pages.
