### ISSUE TITLE
GM.setValue/GM.getValue don't work on Firefox ESR 52.5.2 with GM4.1

### ISSUE THREAD

**Issue by makyen** [greasemonkey/greasemonkey#2781]
In a fresh profile, I tried the following user script:

    // ==UserScript==
    // @name        Test getValue/setValue
    // @namespace   gm4-test
    // @description Test the getValue/setValue
    // @version     1.0.0
    // @match       *://*.example.com/*
    // @grant       GM.getValue
    // @grant       GM.setValue
    // ==/UserScript==

    console.log('GM:', GM);

    let random = Math.random();
    console.log('random: ', random);

    GM.setValue('testValue', random).then(() => {
      console.log('Random value saved');
      GM.getValue('testValue').then(value => {
        console.log('value: ', value);
        //Edge/TM requires the < to be quoted \<
        console.log('Stored value === retrieved value:', value === random, ((typeof value === 'number' && typeof random === 'number' && value === random) ? '-->PASS\<--' : '-->FAIL\<--'));
      });
    });

The output in the Web Console was:

    GM: Object { info: Object, getValue: GM_getValue(key, defaultValue), setValue: GM_setValue(key, value) }  setValue:282:1
    random:  0.5952992191721717  setValue:285:1

The output in the Browser Console was

    GM: <unavailable>  setValue:282
    random:  0.5952992191721717  setValue:285
    IndexedDB UnknownErr: ActorsParent.cpp:599  (unknown)
    Error opening script store DB! 5372393e-7df6-432-b785-bb90543f624 error { target: IDBOpenDBRequest, isTrusted: true, currentTarget: IDBOpenDBRequest, eventPhase: 2, bubbles: true, cancelable: true, defaultPrevented: false, composed: false, timeStamp: 1514490945407000, cancelBubble: false, originalTarget: IDBOpenDBRequest }  value-store.js:19:7
        scriptStoreDb/</dbOpen.onerror moz-extension://c6d52e2a-6e95-41b1-9e85-fd21f8e5fa12/src/bg/value-store.js:19:7
    UnknownError  value-store.js:17:17

It's expected that the value of `GM` is unavailable in the Browser Console. However, the reported error is not expected.

The expected output in the Web Console would be:

    GM: Object { info: Object, getValue: GM_getValue(key, defaultValue), setValue: GM_setValue(key, value) }
    random:  0.5952992191721717
    Random value saved
    value:  0.5952992191721717
    Stored value === retrieved value: true -->PASS<--

**Comment by Sxderp** [comment]
Unkown error. Generated from somewhere in the C code? I'm not sure there's much that could change in GM in regard to this. WebExtensions access the browser through very high level APIs. I could be wrong. Though, if you're using ESR I'd recommend just switching to 3.17.

**Comment by makyen** [comment]
I appreciate the recommendation to use 3.17. I'm already using 3.17 in all situations where that's possible.

I'm just reporting the issue, as GM4.1 is marked as compatible with FF52. The only reason I even ran GM4.1 on ESR52 was because it was in my [testing matrix for testing the gm4-polyfill](https://github.com/greasemonkey/gm4-polyfill/pull/10). From a personal standpoint, I'd always choose GM3.17 over GM4, for situations where it's possible to use GM3.

I have not explored why the error is generated. However, it's clear it's somewhere in the use of the [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API). The MDN [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API#Browser_compatibility) database doesn't indicate any changes in IndexedDB compatibility between FF52 and FF56. But, given that this does work in FF56, there clearly was something that changed. There may, or may not, be something which GM4 can change to have this be functional.

If GM4.1 wasn't already marked as compatible with FF52, I would recommend not caring about this and just keeping GM4 as a `strict_min_version` of FF57.

**Comment by erosman** [comment]
> The output in the Web Console was:

That was interesting so I tried it too.
I also get (FF58.0a1 GM4.1)
`Object { info: {…}, getValue: GM_getValue(), setValue: GM_setValue(), xmlHttpRequest: GM_xmlHttpRequest() }`

Does that mean `GM_getValue()` etc are already defined and available in GM4.1?

**Comment by arantius** [comment]
Have you tried with a fresh profile ( https://wiki.greasespot.net/Troubleshooting_(Users)#Fresh_Profile )?

**Comment by makyen** [comment]
@arantius My report/testing was from a fresh profile created specifically for the above report (as stated in the first sentence). I did, first, try it in a non-fresh profile, but had other issues.

**Comment by Eselce** [comment]
@erosman
> Does that mean GM_getValue() etc are already defined and available in GM4.1?

That's not the classical (legacy) function, you should look here: https://github.com/greasemonkey/greasemonkey/blob/master/src/bg/api-provider-source.js#L86-L100

**Comment by Sxderp** [comment]
A recent release of Firefox ESR (52.5.2, the one  you're using) did _something_ to indexedDB. While the bulletin would indicate that the issue is not directly related there's potential for side effects.

https://www.mozilla.org/en-US/security/advisories/mfsa2017-28/

**Comment by erosman** [comment]
Applogies @makyen for going off-topic
@Eselce I realise they are not the classic function but a promised based one ... but can they be used? Are they accessible?

**Comment by Eselce** [comment]
@erosman Well, they are just backend functions, more or less added to your internal code, I don't think, it's good practice to use them directly...

**Comment by Sxderp** [comment]
> A recent release of Firefox ESR (52.5.2, the one you're using) did _something_ to indexedDB.

It has to be this. I just tested with RHEL6 + FF ESR 52.5.1.

Direct copy / paste of the script. Browser console output:
```
GM: <unavailable>  setValue:282
random:  0.4429137653450075  setValue:285
Random value saved  setValue:288
value:  0.4429137653450075  setValue:290
Stored value === retrieved value: true -->PASS<--  setValue:292
```

**Comment by arantius** [comment]
Has that (52.2.1 works, 52.2.2 does not) been reported to Mozilla?

**Comment by Sxderp** [comment]
I have not reported it. And I haven't seen anything on Bugzilla.
