### ISSUE TITLE
Greasemonkey causes frequent bouts of unresponsiveness

### ISSUE THREAD

**Issue by DoomTay** [greasemonkey/greasemonkey#2783]
Maybe it's because I have several scripts installed, but there have been way too many times where Firefox says "A script in the extension Greasemonkey is causing Firefox to slow down"

**Comment by arantius** [comment]
I certainly don't experience this.  It seems likely to be one of your scripts, but you've provided no detail, so there's nothing I can do.

https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help#What_to_Say

**Comment by DoomTay** [comment]
I decided to investigate further

For the record, I have installed almost everything under [here](https://greasyfork.org/en/users/17147-doomtay), and I notice it the most [here](http://dashboard.at.ninjawedding.org/?showNicks=1) and when inputting a Google search from the "new Tab" page in privacy mode.

The only scripts that are enabled that would apply to that page are Dead Image Size Revealer and Image Map Revealer. There are other scripts that are for specific websites, and thus are categorized under "Other User Scripts". All those are enabled, but I don't think it should affect performance on the page above. Still, this is enough to trigger the popup, which is baffling because that page doesn't even _have_ any images.

**Comment by arantius** [comment]
Thanks.  It would be helpful if you could troubleshoot further yourself:

https://wiki.greasespot.net/Troubleshooting_(Users)#Fresh_Profile

What's the minimum set of things to add to a fresh profile to trigger this?

**Comment by DoomTay** [comment]
In the first scenario (loading up [a dashboard](http://dashboard.at.ninjawedding.org/?showNicks=1)) I only have Greasemonkey with [Image Map Fixer](https://greasyfork.org/en/scripts/15679-image-map-fixer) and [Dead Image Size Revealer](https://greasyfork.org/en/scripts/37193-dead-image-size-revealer) installed

The second scenario (the error popup occurring with a newly made tab) seems to be much rarer, but I noticed it occur if I were to install [Image Search Options](https://addons.mozilla.org/en-US/firefox/addon/image-search-options/), picking an image, and selecting "Search all" (you would have to have the option enabled)

**Comment by DoomTay** [comment]
I think the commit referenced the wrong issue. Especially since I still see the first scenario happen as of version 4.2
