### ISSUE TITLE
gm4-polyfill is leaking GM object to page scripts

### ISSUE THREAD

**Issue by eight04** [greasemonkey/greasemonkey#2784]
I think this issue needs its own thread.

As the discussion in https://github.com/greasemonkey/greasemonkey/issues/2776#issuecomment-354481462

https://github.com/greasemonkey/gm4-polyfill/blob/e6f01bf925a272a9563ff9b652b894bbd668e735/gm4-polyfill.js#L28

This line would leak `GM` object to the page script. I can confirm it on Tampermonkey 4.5.5564 (before introducing `GM.api`) and Violentmonkey 2.8.23, in Firefox 58.0b13.

I think it should be changed to:
```js
this.GM = {};
```
It works in both Tampermonkey and Violentmonkey in Firefox. I'm not sure about other environments. [Maybe there are some environments which don't support `this`](https://github.com/greasemonkey/gm4-polyfill/pull/10)? @makyen Also note that [other APIs are defined with `this`](https://github.com/greasemonkey/gm4-polyfill/blob/e6f01bf925a272a9563ff9b652b894bbd668e735/gm4-polyfill.js#L33).

Maybe @JasonBarnabe would like to inform [some script authors on GreasyFork who are using gm4-polyfill](https://greasyfork.org/en/scripts/code-search?utf8=%E2%9C%93&c=gm4-polyfill) to update their library.

A small test script to install:
```js
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match *://*/*
// @grant GM_openInTab
// @require https://rawgit.com/greasemonkey/gm4-polyfill/e6f01bf925a272a9563ff9b652b894bbd668e735/gm4-polyfill.js
// ==/UserScript==

console.log(typeof GM);
```
And try to access `GM` object and execute `GM.openInTab` in the browser console.

Related issue:
https://github.com/Tampermonkey/tampermonkey/issues/362

@derjanb @gera2ld

**Comment by makyen** [comment]
The issue I mentioned with `this` is only in strict-mode. The current polyfill doesn't use strict-mode, thus it's not currently an issue. If it was currently an issue, then other portions of the script would already not function.

**Comment by Sxderp** [comment]
Violentmonkey, at least last time I took a brief glance at the code, seemed to run scripts by injecting them through `<script>` elements. And unless Mozilla has made it so that elements injected by extensions are unavailable to the page (is this even a thing?), then, unless I'm missing something (I could be), everything is available to the page.

**Comment by eight04** [comment]
By defining `GM` object with `this.GM = ...`, Violentmonkey won't leak it to page scripts. I don't know how it works either.

**Comment by eight04** [comment]
https://github.com/greasemonkey/gm4-polyfill/pull/12
