### ISSUE TITLE
GM4 polyfill

### ISSUE THREAD

**Issue by Mottie** [greasemonkey/greasemonkey#2787]
1. Please enable the issues for https://github.com/greasemonkey/gm4-polyfill
2. Please add a version to the file.
3. According to the Greasemonkey docs for [`@require`](https://wiki.greasespot.net/Metadata_Block#.40require):

    > Note that since Greasemonkey 0.9.0, if Greasemonkey detects that the `@require` value(s) have been altered, these new values will be used (thus each `@require` shall be re-downloaded).

    I *think* this is only referring to the `@require` line in the userscript and not the content of the file.

    So according to the polyfill readme, the recommended

    ```js
    // @require https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
    ```

    would never update.

**Comment by arantius** [comment]
1. No.
2. Towards what end?
3. Your "think" is correct.  Scripts update when _their_ version changes.  That section of the docs just mean that if you (e.g.) add a new `@require`, it will be downloaded.

**Comment by Mottie** [comment]
Umm, ok... I guess it's too much extra work for me to update my userscripts to also work with GM4.

**Comment by Bluscream** [comment]
Wow @arantius you're such an ignorant person. Delete yourself!
