### ISSUE TITLE
Bad error handling when fetching @require file

### ISSUE THREAD

**Issue by StigNygaard** [greasemonkey/greasemonkey#2790]
I was (manually) updating a userscript, including a change of version for a required "sidecar" js-file.
Apparently an error happened when GM41 tried to update the "sidecar" file. That was probably not the fault of GM, but the way the error is handled is not too good. Instead of showing an error to the user (me), it updated the local cached "sidecar" file with the error-page:

![image](https://user-images.githubusercontent.com/5936108/34639600-e6ccd454-f2e2-11e7-91b0-8241361d2eff.png)

Of course my script didn't work after that...

The "sidecar" file is hosted on Greasy Fork, and I assume/hope there are some http error code returned besides the error page, so the problem can be handled in a better way.

Sorry, in the browser used (FF57/Win10) I'm still using GM41, so I don't know if it would be the same problem in GM42beta.

**Comment by arantius** [comment]
Agreed, this should be much better.

**Comment by arantius** [comment]
#2594
