### ISSUE TITLE
Scripts included with magic tld don't show up in "User scripts for this tab"

### ISSUE THREAD

**Issue by stonecrusher** [greasemonkey/greasemonkey#2795]
Firefox 57.0.4 (64-Bit)
Greasemonkey 4.1

The title says it all... [example](https://greasyfork.org/scripts/15222):
`// @include       http://*.imdb.tld/title/tt*`

~~The script is correctly applied but~~ in the greasemonkey popup it shows under "Other user scripts" instead of "User scripts for this tab". So one can't see all scripts which are active on the current tab.
 
Works fine when using
`// @include       http://*.imdb.com/title/tt*`

/edit
I didn't remember my version of the example script above was modified. It looks like magic tld isn't supported at all at the moment.

/edit2
Simple scripts using magic tld in @include work as intended (but not @match, see #2096).
Summary: I just had some weird issues with the script mentioned above and I'll investigate further.

**Comment by Sxderp** [comment]
Not sure what 'magic tld' is supposed to be, but in the code `// TODO: Accurate ".tld" support; blocked by http://bugzil.la/1315558`.

**Comment by stonecrusher** [comment]
@Sxderp 
See https://wiki.greasespot.net/Magic_TLD
And thanks for the info! Looking at the FF bug, arantius is already aware of it.

**Comment by arantius** [comment]
I'm seeing `.tld` not work at all right now.  Checking ...

**Comment by stonecrusher** [comment]
I'm sorry, you are right. I thought I was wrong because my testing environment here is a mess and caused lots of confusion (plus I didn't know about the difference of `@include` and `@match`).
