### ISSUE TITLE
Document GM.notification

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2796]
In v4 we have `GM.notification()`, but it's not mentioned on the wiki.  Document it.

**Comment by arantius** [comment]
https://wiki.greasespot.net/GM.notification

**Comment by NoneGiven** [comment]
@arantius Description was copy-pasted and not updated: "This method opens the specified URL in a new tab."

**Comment by tiansh** [comment]
Looks like the GM.notification API was implemented as

> GM.notification(text, title, image, onclick)
> GM.notification({ text, title, image, onclick, ondone }, ondone)

But the [document](https://wiki.greasespot.net/GM.notification) only described the first interface. It should be updated.

**Comment by LilDevil** [comment]
> But the [document](https://wiki.greasespot.net/GM.notification) only described the first interface. It should be updated.

Fixed.
