### ISSUE TITLE
Data containing circular reference used when saving script

### ISSUE THREAD

**Issue by badbrainz** [greasemonkey/greasemonkey#2806]
Offending line:
https://github.com/greasemonkey/greasemonkey/blob/829ff0f7702137e00088e0baa1ef8e5f9e4bb1c1/src/bg/user-script-registry.js#L81

This circular structure is saved to indexeddb and ends up being used in extension messaging. Firefox should complain but it doesn't.

Are there any side effects of referencing a `Object.assign({}, details)` object instead?

**Comment by Sxderp** [comment]
Solution is to just remove parsed details from the object. It's used in like one place and it really isn't needed. 

In my install / update rework I removed it (waiting on other PRs). I don't recall what needs to be done in the current code in order to safely remove it.

**Comment by Sxderp** [comment]
Solution is to just remove parsed details from the object. It's used in like one place and it really isn't needed. 

In my install / update rework I removed it (waiting on other PRs). I don't recall what needs to be done in the current code in order to safely remove it.

**Comment by Sxderp** [comment]
Solution is to just remove parsed details from the object. It's used in like one place and it really isn't needed. 

In my install / update rework I removed it (waiting on other PRs). I don't recall what needs to be done in the current code in order to safely remove it.

**Comment by Sxderp** [comment]
Solution is to just remove parsed details from the object. It's used in like one place and it really isn't needed. 

In my install / update rework I removed it (waiting on other PRs). I don't recall what needs to be done in the current code in order to safely remove it.

**Comment by Sxderp** [comment]
Solution is to just remove parsed details from the object. It's used in like one place and it really isn't needed. 

In my install / update rework I removed it (waiting on other PRs). I don't recall what needs to be done in the current code in order to safely remove it.

**Comment by Sxderp** [comment]
Solution is to just remove parsed details from the object. It's used in like one place and it really isn't needed. 

In my install / update rework I removed it (waiting on other PRs). I don't recall what needs to be done in the current code in order to safely remove it.

**Comment by Sxderp** [comment]
Solution is to just remove parsed details from the object. It's used in like one place and it really isn't needed. 

In my install / update rework I removed it (waiting on other PRs). I don't recall what needs to be done in the current code in order to safely remove it.

**Comment by arantius** [comment]
Yes, it's pretty easy to just parse again as/when needed.

**Comment by arantius** [comment]
a08b2d89bec7dc62a1df942a5b403eefd46f60ab fixed this, in 4.4
