### ISSUE TITLE
Version 4.1 has wrong version compatibility listed on Firefox's add-on page 

### ISSUE THREAD

**Issue by Jorlem** [greasemonkey/greasemonkey#2807]
It isn't visible on the main page, but version 4.1 of Greasemonkey is listed as compatible with Firefox v52+. Version 4.0 is correctly listed as v57+, while those prior to version 4.0 are listed as 52-56. 
Can be seen here:
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/

4.1 does not appear to work properly on Firefox 56 (at least, I noticed a few scripts stopped working until I downgraded back to 3.17), so those sticking with the old version of Firefox should not be getting updated to the new Greasemonkey.

**Comment by NoneGiven** [comment]
GM 4.1 works fine on FF 56, but that doesn't mean all your scripts will. People who don't want to update should turn off auto-update.
