### ISSUE TITLE
Fix GM.openInTab focus behavior

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2808]
https://wiki.greasespot.net/GM.openInTab

Says:
> open_in_background
>    Boolean Optional: force tab to/to not open in a background tab. Default (unspecified) behavior honors Firefox configuration.

But since webext, it does not honor default configuration (because we can't know it).  It defaults to background.

**Comment by Sxderp** [comment]
Support for browser default will have to be brought up with Mozilla.

**Comment by erosman** [comment]
May I ask, what code do you use?

`active: false/true` works fine in `tabs.create()`

**Comment by Sxderp** [comment]
It works. But in 3.x the functionally was deferred to what the user had set as the browser default. With the new API the tab is focused by default disregarding user preference.

**Comment by arantius** [comment]
It is?  I see it *not* focused unless I explicitly pass false, in GM4.  The opposite of what I'd naturally want.

```
// ==UserScript==
// @name     GM.openInTab() Focus Test
// @version  1
// @grant    GM.openInTab
// @include  *
// @exclude  *google*
// ==/UserScript==

GM.openInTab('https://www.google.com/');
```

**Comment by erosman** [comment]
ref: https://github.com/greasemonkey/greasemonkey/blob/829ff0f7702137e00088e0baa1ef8e5f9e4bb1c1/src/bg/on-user-script-open-in-tab.js


Where is `onApiOpenInTab()` coming from?

I think this is false because it was not set. `active: message.active,`

**Comment by Sxderp** [comment]
> It is?

I meant the WebExtension tabs API. Passing nothing into that will auto-focus the tab. Even if a user sets the preference for tabs to be opened in background.

**Comment by roger21** [comment]
well, I would be ok if we drop the 
> honors Firefox configuration
on that one and focus on the insert option #3080
