### ISSUE TITLE
RFE: Improve the Monkey Menu when many scripts are installed

### ISSUE THREAD

**Issue by erosman** [greasemonkey/greasemonkey#2809]
Note; I have 100+ scripts in the menu

It could be useful to:

- Move "New  user script..." to top
- Add the scrollbar to "Other scripts" keeping the menus static

**Comment by Sxderp** [comment]
> Move "New user script..." to top 

#2697

**Comment by arantius** [comment]
@Sxderp after merge, I'm seeing nested scrollbars, sometimes.

![image](https://user-images.githubusercontent.com/84729/38043925-5418cddc-3286-11e8-996d-dac4dec4db2e.png)

**Comment by Eselce** [comment]
Dito for me. Maybe the height is just too small because of the import/export merge. The right (outer) scroll bar should not appear...

**Comment by Sxderp** [comment]
@Eselce it is due to the import export merge. The script section is now taking up too much space. This should be easily fixed with one line css change.

**Comment by Eselce** [comment]
I agree... :smile:

**Comment by arantius** [comment]
When a script with a long name is installed now:

![image](https://user-images.githubusercontent.com/84729/38093127-096db858-3338-11e8-989c-785cf4cf7ca9.png)

(I'm working in this space so it might not be worth investing time in a fix until I finish that, but you're welcome to if you like.)

**Comment by Sxderp** [comment]
> When a script with a long name is installed now:

I believe the `.script-scroll` class just needs a bounding width. `width: 100%` or `max-width: 100%` should resolve it, I think.

**Comment by arantius** [comment]
Obsoleted by 36d47940d933f75461ccc61e1cf23505f64e29eb.
