### ISSUE TITLE
Unable to install scripts

### ISSUE THREAD

**Issue by Marcop68** [greasemonkey/greasemonkey#2810]
Hi all, I'm unable to add scripts to my Greasemonkey.
When I reach the installation page and click on install, I'm automatically redirected to the same installation page over and over again (see picture below), and the script is never downloaded and added to Greasemonkey.
![image](https://user-images.githubusercontent.com/35522409/35033270-48e2e2d4-fb6a-11e7-9838-083f4e539bd3.png)
I'm aware it may be a stupid problem, still I hope someone is able to help me.
I'm browsing with Firefox ESR 52.5.3 (32-bit).
Thanks a lot!

**Comment by n-o-o-b** [comment]
I wanted to install https://github.com/ParticleCore/Iridium/wiki/Download (https://raw.githubusercontent.com/ParticleCore/Iridium/beta/src/userscript/Iridium.user.js) but I didn't even get an install page. I switched to Violentmonkey and everything worked fine.

**Comment by Marcop68** [comment]
Oh got it. I switched to Tampermonkey and Google Chrome.

**Comment by Eselce** [comment]
There's a known bug with the [Raw] button on `GitHub` (still isn't accepted as input).
Will probably work in the future. Until then, there are several methods to paste/load/import that thing.
