### ISSUE TITLE
Anti adblock killer reek script don't work with Firefox

### ISSUE THREAD

**Issue by grysor** [greasemonkey/greasemonkey#2811]
Hello,i'm french excuse me for my poor language i use google translate.
I have Firefox quantum 57.0.4 .And the firefox adguard adblocker extension in the latest version with all the filters updated.
I installed greasemonkey extension for firefox + anti adblock killer script and the greasemonkey monkey head appears well at the top right in firefox.When I left click on it, greasemonkey is activated and anti adblock killer reek is activated too.
But when I go on this web page:
http://antiblock.org/?p=v3&demo

I always have the message telling me : "Please disable your ad blocker! Anti adblock killer does not work!
-I specify that I activated the anti adblock filter killer reek in adguard adblock in :
all filters> others
-I specify that I am under windows 10.
Otherwise, with the google chrome browser with tampermonkey + adblocker adguard extension, anti adblock killer script works very well and I do not have the message that tells me to disable adblock on the website http://antiblock.org/?p=v3&demo

-can you tell me how to fix this problem with firefox please?
Thank you in advance for your answer

**Comment by grysor** [comment]
edit
i specify that this is not a demo
On google chrome with tampermonkey + anti adblock killer which is compatible with adblock adguard, this message does not appear on the link that I mentioned
The adblock disable message has disappeared.
because anti adblock killer works on chrome.But not with firefox :(

here is the same open link with chrome :
http://zupimages.net/viewer.php?id=18/03/q0b6.png
the message: "please disable your adblocker" does not appear because anti adblock killer works fine :)
it's on firefox the problem :(

**Comment by StigNygaard** [comment]
I don't think your problem is caused by Greasemonkey. Maybe by a script you are running in Greasemonkey, but not by Greasemonkey itself

**Comment by grysor** [comment]
Hello StigNygaard 
I do not know. But in any case I only use one script in greasemonkey and it's anti adblock killer reek

**Comment by StigNygaard** [comment]
@grysor , contact the developer of adblock killer reek.

**Comment by grysor** [comment]
[quote="StigNygaard"]            

contact the developer of adblock killer reek. [/quote]

Yes I wanted :) But it does not work here in "contact" here  
https://reek.github.io/anti-adblock-killer/
I think it's because the dev stopped the development of his script that he also stopped the way to contact him.

But it does not matter! :) Because I found the SOLUTION to make work anti adblock killer reek with chrome! :
you need to install the extension for chrome: " Chrome store foxified "
Then install " Tampermonkey " extension
Then install script anti adblock killer reek and it works god fire! The message "disable your adblock" does not appear anymore on the link http://antiblock.org/?p=v3&demo
😃
