### ISSUE TITLE
Show number of running scripts in badge

### ISSUE THREAD

**Issue by FranklinYu** [greasemonkey/greasemonkey#2813]
This is a feature request. Both Tampermonkey and Violentmonkey shows the number of running scripts in current page. I guess they did it by [`setBadgeText()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/setBadgeText).

**Comment by Sxderp** [comment]
While this is easily doable now, it becomes more difficult if we switch to #2663.

**Comment by kkot** [comment]
It could be an option in preferences. I would also like to see if a user script is running on the current page or not.

**Comment by Eselce** [comment]
TODO: Move updateBadgeByDetails(), when #2663 is implemented.
TODO: Feature should be optional and user configurable.
