### ISSUE TITLE
[Feature] Editor MenuBar

### ISSUE THREAD

**Issue by ghost** [greasemonkey/greasemonkey#2814]
The editor isn't complete without a menubar, so I rolled my own.
![screenshot from 2018-01-19 00 58 50](https://user-images.githubusercontent.com/10160581/35142774-2ea0c63e-fcb4-11e7-9248-55fb22ac1ad7.png)

I understand that there are more important issues to deal with, so I'm leaving it to the devs to signal a pull request. With enough +feedback from the community, perhaps we can convince @arantius into merging this. Suggestions are welcome.

Branch is [here](/badbrainz/greasemonkey/commits/menu-bar).

Current menus:

**File**
- [x] Save
- [x] Next/Prev document

**Edit**
- [x] Undo/Redo
- [x] Indent More/Less/Auto
- [ ] Transpose line above/below
- [ ] Duplicate line
- [x] Jump to line
- [x] Fold/Unfold bracket
- [x] Fold/Unfold all brackets

**Search**
- [x] Find
- [x] Find next/prev
- [x] Replace
- [x] Replace all

**Options**
- [ ] Indent with tabs
- [ ] Indent unit 2/4
- [x] Wrap lines
- [x] Highlight brackets
- [x] Lint metablock
- [ ] Lint JavaScript

**Addons**
- [x] Find bracket
- [x] Show hints

Keyboard:

- [x] Accessibility (keymap)
- <kbd>Alt-F</kbd> File
- <kbd>Alt-E</kbd> Edit
- <kbd>Alt-S</kbd> Search
- <kbd>Alt-O</kbd> Options
- <kbd>Alt-A</kbd> Addons
- [x] Menu item shortcuts
- e.g., <kbd>Alt-F</kbd> + <kbd>s</kbd> Save

**Comment by Sxderp** [comment]
> I understand that there are more important 

Actually, no. I think this is very important. From issues created and messages on the mailing list not knowing how to save (no button at the time), makes me think some decent portion of users are unfamiliar with keyboard shortcuts. Therefore an action menu of sorts is necessary.

**Comment by arantius** [comment]
In general I like this.  Is it keyboard accessible like a standard menu though?

Should we consider (optionally?) popping the editor in a dialog instead of a tab, so e.g. `Alt-F` and such will/could work?  And (editor-)tab-navigation keys?

**Comment by Sxderp** [comment]
> Should we consider (optionally?) popping the editor in a dialog instead of a tab

I don't know about 'optionally', but I do like the idea of using a dialog / popup. I'm not sure how that affects `Alt-F` though. Wouldn't that still open the window menubar? Or can that be functionality be `preventDefault()`?

**Comment by arantius** [comment]
There is no browser level menubar in a dialog window.

**Comment by arantius** [comment]
> Save - As of beta3, the editor won't save individual sources, so this serves as Save All as well.
> Save all

Just call it save all and be done?  Implementing save-one-tab probably isn't worth the effort.

**Comment by arantius** [comment]
https://github.com/arantius/greasemonkey/tree/editor-menu-bar

I've tried this out and .. hmm.  It's quite a lot of added code (800 LoC, where all of Greasemonkey now is ~3.5k).  Improves discoverability of editor features which is nice.  But it doesn't "work".  At least not like any normal menu I've used before.

I can press Alt-F to open the file menu, but then I can't then press "S" to trigger save.  I can press Alt-F to open the file menu, but then I can't press down/enter to trigger save.  Down switches to the edit menu (!?).  This menu would probably give me more aggravation than pleasure, it looks like a standard menu but doesn't act like one.

Is there perhaps a compatibly licensed library for making a menu bar like this, which would already handle keyboard accessibility?

**Comment by arantius** [comment]
Oh it also breaks the tests:

https://travis-ci.org/arantius/greasemonkey/builds/333773577

**Comment by Sxderp** [comment]
> Oh it also breaks the tests:

I think that's because all the CodeMirror things are in the `karma.conf` excludes section. And this file, which attempts to use a CodeMirror object, is not.

**Comment by badbrainz** [comment]
I wasn't too thrilled about adding navigation, to be honest. My only issue is that Alt causes the browser's menu to appear, and a window popup (chromeless window?) is missing Min/Maximize buttons and it can't be attached to the sides of the screen. As for Up/Down/Enter navigation, this shouldn't be difficult to add. Menu shortcuts might be a boring task.

If navigation or code size is going to be an issue, I'll scrap the idea altogether.

There are no third party libs that I'm aware of.

**Comment by badbrainz** [comment]
Commit 1ba90cd9d97aa2f33ceafc24391125251bfd5557 adds better navigation.
- Up/Down selects menu items.
- Left/Right selects top menu.
- Alt-F then S triggers menu item.

Options and horizontal splitters are left out for now.

Please let me know if this is still off the table. I don't want to work on the remaining stuff if it is.
