### ISSUE TITLE
Native-like Monkey Menu needs fixes or roll-back

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2816]
The monkey menu after #2805 looks a lot better.  Except the little "next page" arrows look awkward when there are enough install scripts to trigger a scroll bar:

![screenshot from 2018-01-26 10 12 07b](https://user-images.githubusercontent.com/84729/35446149-d40f6008-0281-11e8-8ba6-341eeae58f89.png)

It seems like the scroll bar layers on top of, rather than beside, the content.

**Comment by Sxderp** [comment]
RIP, I remember testing this and not having any problems. Must be platform / X environment dependent. Of course, aesthetic compatibility is ideal.

**Comment by arantius** [comment]
This change needs either fixes or to be backed out.


See above problem, and issues mentioned in #2650, and I also get visual glitches on Windows.  On Windows every line seems much taller than on Linux, and if I scroll down I get:

![mm](https://user-images.githubusercontent.com/84729/35476309-ac800cf4-037b-11e8-8724-73e9ca15029f.png)

A bunch of non-erased garbage behind the real elements at the bottom.  If I scroll slowly, I can see each item, as it should disappear of the top instead pop in at the bottom, then disappear after a few further pixels of scrolling.


If I click into one script, the scroll bar keeps the height of the main view, giving me lots of nothing to scroll into.  If I do and scroll back up, I get black flashes.  If I do so slowly, they don't flash, I can get:

![mezer_01-27_16-04-28](https://user-images.githubusercontent.com/84729/35476320-e59569f8-037b-11e8-9388-6fd4d360e8ac.png)

Quite a lot of visual corruption.

**Comment by Eselce** [comment]
Can confirm the scrollbar and the "garbage". Happened to me as well (win system)...

**Comment by Sxderp** [comment]
The visual glitches aren't strictly caused by the changes. 

There's some Bugzilla posts about these issues. Of course, rolling back until Mozilla gets their shit together is always possible.

**Comment by arantius** [comment]
Maybe I haven't looked closely before (testing profiles usually don't have enough scripts installed to scroll...) but even if the cause is a buggy platform, I can't recall seeing things like this before.

**Comment by Sxderp** [comment]
> but even if the cause is a buggy platform, I can't recall seeing things like this before.

It's probably that the old styles didn't cause the issue to be prominent. I have a css fix that'll deal with the scrollbar, and somewhat resolve the graphical glitches, and inadvertently fix #2694 (lol).

I'll post shortly.

**Comment by arantius** [comment]
Fixed by #2818 .
