### ISSUE TITLE
Check Monkey Menu after #2818, on Windows

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2822]
I've merged #2818 but I need to be sure to check how that behaves on Windows, where the worst visual glitches were observed.

**Comment by Sxderp** [comment]
Just to have a copy of these links. Bugzilla issues regarding the graphical glitches.
https://bugzilla.mozilla.org/show_bug.cgi?id=1420865
https://bugzilla.mozilla.org/show_bug.cgi?id=1418677
https://bugzilla.mozilla.org/show_bug.cgi?id=1380622

**Comment by arantius** [comment]
Everything looks good.
