### ISSUE TITLE
Add build instructions to README

### ISSUE THREAD

**Issue by krichter722** [greasemonkey/greasemonkey#2824]
Users might want to quickly verify whether a bug exists in the current development version which makes it necessary to build the add-on based on the source repository. Therefore it's be nice to have build instructions or a link to such in `README`.

**Comment by Sxderp** [comment]
The repository is set up such that this is very easy. Could probably be added to the readme (all of two lines).

Clone the repo and then run `./package.sh` from inside the directory. You'll be left with a `.xpi` file that can be installed manually from `about:addons`.

If you're on Windows you'll have to do it a little differently. I haven't tested the following steps, but they _should_ work. Clone the repo and then from the root directory highlight (ctrl + left click) the following files/folders `_locales` `skin` `src` `third-party` `LICENSE.mit` `manifest.json`. Once they're selected right click and "send to -> zip folder". Then rename the `.zip` to be `.xpi`. You should be able to import from `about:addons`.

**Comment by StigNygaard** [comment]
If the Windows part can be confirmed, I think it would be nice to include those "the two lines" and the "5 lines Windows Instruction" to the README.

**Comment by Eselce** [comment]
I gave it a try (on a windows system). Some remarks:

- You can leave the .zip extension alone (`.xpi` `.jar` or `.zip` expected)
- Don't forget to allow signatureless addOns (about:config, `xpinstall.signatures.required` to `false`, 4th-last entry at the bottom)

(and Stig interrupted my post)

**Comment by arantius** [comment]
Don't even bother with all that.  Check out/download.  Head to about:debugging.  Hit load temporary add-on, pick any file at the top of the source tree.  Done.

**Comment by Eselce** [comment]
Wow! That's pretty easy!

**Comment by krichter722** [comment]
This issue has been closed without the issue being fixed. By providing the information in the issue you're handling this as support request, i.e. for a few users, adding it to `README` as requested would solve the issue for everyone.
