### ISSUE TITLE
New user script has no effect

### ISSUE THREAD

**Issue by krichter722** [greasemonkey/greasemonkey#2825]
After clicking on `New user script` of the Greasemonkey popup in Firefox 58.0.1 on Ubuntu 17.10 nothing happens. I expect a dialog to open which allows to define a user script.

I didn't find any clue where to get more debugging information from, but I'm willing to provide them if you tell me what you need.

experienced with 4.2

**Comment by Sxderp** [comment]
When creating a new user script no additional dialog will be opened. What should happen is a new tab be constructed that will auto-navigate to the built-in editor. This doesn't occur for you?

You can check the browser logs from `ctrl+shift+j`. Clear them (trash button in top left of the window) and then click on the `New user script` button.

**Comment by krichter722** [comment]
> When creating a new user script no additional dialog will be opened. What should happen is a new tab be constructed that will auto-navigate to the built-in editor. This doesn't occur for you?

No, that doesn't happen.

> You can check the browser logs from ctrl+shift+j. Clear them (trash button in top left of the window) and then click on the New user script button.

The log shows

```
[NoScript] Received message from content Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 3630 }  log.js:9:39
[NoScript] Received unkown message Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 3630 }  log.js:9:39
[NoScript] Received message from content Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 3635 }  log.js:9:39
[NoScript] Received unkown message Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 3635 }  log.js:9:39
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 514"  data: no]  (unknown)
```

**Comment by Sxderp** [comment]
Ah, I probably should have been more clear. Does the above dump include any error messages occurred when opening the Monkey Menu? If not could you get those as well?

Further, can you test on a fresh profile? From the command line you can run `firefox -P --no-remote` which will bring up the profile manager. Or you can navigate to `about:profiles` and create and launch a new one from the Firefox GUI.

As an aside, I believe 4.2 was when the Monkey Menu navigation was changed from onclicks to links. Could have something to do with it. Not entirely sure.

**Comment by arantius** [comment]
https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help

Have you tried a fresh profile?

**Comment by krichter722** [comment]
Sorry for not reporting back for so long. I just checked and have the save problem. However, I collected the following information which might advance this issue:

> Ah, I probably should have been more clear. Does the above dump include any error messages occurred when opening the Monkey Menu? If not could you get those as well?

After clearing the conobrowser log right before opening the Greasemonkey menu and clicking on "new user script" I get

```
[NoScript] Received message from content Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 52024 }  log.js:9:39
[NoScript] Received unkown message Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 52024 }  log.js:9:39
TypeError: window.document.location is null[Learn More]  selenium-browserdetect.js:52:13
[NoScript] Received message from content Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 52028 }  log.js:9:39
[NoScript] Received unkown message Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 52028 }  log.js:9:39
TypeError: "alert" is read-only
Stack trace:
./selenium-browserbot.js/BrowserBot.prototype.modifyWindowToRecordPopUpDialogs@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:45270:249
./selenium-browserbot.js/BrowserBot.prototype._modifyWindow@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:45223:44
./selenium-browserbot.js/BrowserBot.prototype.getCurrentWindow@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:45364:541
./selenium-browserbot.js/BrowserBot.createForWindow@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:45151:50
./commands-api.js@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:41912:834
__webpack_require__@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:30:12
./record-api.js@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:42058:326
__webpack_require__@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:30:12
./record.js@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:42083:292
__webpack_require__@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:30:12
[3]@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:50704:18
__webpack_require__@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:30:12
@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:73:18
@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:11:18
webpackUniversalModuleDefinition@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:7:11
@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:1:11
  record.js:45223:103
Use of Mutation Events is deprecated. Use MutationObserver instead.  record.js:42073:911
[NoScript] Received message from content Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 52034 }  log.js:9:39
[NoScript] Received unkown message Object { type: "canScript" } Object { id: "{73a6fe31-595d-460b-a920-fcc0f88432…", frameId: 0, url: "about:blank", envType: "content_child", extensionId: "{73a6fe31-595d-460b-a920-fcc0f88432…", contextId: 52034 }  log.js:9:39
Loading failed for the <script> with source “moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/prompt.js”.  blank:1
TypeError: "alert" is read-only
Stack trace:
./selenium-browserbot.js/BrowserBot.prototype.modifyWindowToRecordPopUpDialogs@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:45270:249
./selenium-browserbot.js/BrowserBot.prototype._modifyWindow@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:45223:44
./selenium-browserbot.js/BrowserBot.prototype.getCurrentWindow@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:45364:541
./selenium-browserbot.js/BrowserBot.createForWindow@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:45151:50
./commands-api.js@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:41912:834
__webpack_require__@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:30:12
./record-api.js@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:42058:326
__webpack_require__@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:30:12
./record.js@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:42083:292
__webpack_require__@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:30:12
[3]@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record.js:50704:18
__webpack_require__@moz-extension://f3c78399-b6d6-4a06-9476-067b7f3a4ffb/assets/record
```

in the log.

> Further, can you test on a fresh profile?

The issue does not occur with a fresh profile, so it's up to you as devs to decide whether you want to investigate this imo incompatibility with another add-on. I'm willing to support the investigation, but I'd be very happy if you could give me a pointer which add-ons to de- and re-activate for a trial-error reproduction of the issue since I have a lot.

**Comment by arantius** [comment]
> The issue does not occur with a fresh profile, so ...

So it's much more practical for you to figure out which part of your profile is doing it, than for us to guess at what it might be.

Copy your main profile to another one, start removing things one by one from that copy, until things work again?  Report which thing was the last one?  Start a fresh profile and install only that and GM, see if it still does it?

**Comment by omgitsraven** [comment]
Having the same issue here; Firefox 61, Windows 10, Greasemonkey 4.4.0; clicking "New user script" does nothing at all in my main profile, and works fine in a fresh profile. I've turned off all of my (other) extensions in my main profile but it made no difference. What else is there to try?

**Comment by omgitsraven** [comment]
might as well add what happens in my browser console when I click it:
```
17:32:04.500
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.principal]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///C:/Program%20Files/Mozilla%20Firefox%2064/browser/omni.ja!/components/nsBrowserGlue.js :: prompt :: line 2850"  data: no]
prompt jar:file:///C:/Program Files/Mozilla Firefox 64/browser/omni.ja!/components/nsBrowserGlue.js:2850:1

17:32:04.500
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.cancel]
nsBrowserGlue.js:2874
```
and then a moment later
```
17:32:05.430
IndexedDB UnknownErr: ActorsParent.cpp:600

17:32:05.430
Error opening user-scripts DB! <unavailable>
openDb/</dbOpen.onerror moz-extension://170887a0-7392-494a-8773-b4654ca36991/src/bg/user-script-registry.js:57:7

17:32:05.433
<unavailable> 
install/</< moz-extension://170887a0-7392-494a-8773-b4654ca36991/src/downloader.js:111:11

17:32:05.434
Error: undefined
downloader.js:105:7 
```

**Comment by Cerberus-tm** [comment]
Hmm I have not experienced this issue so far, but a few weeks ago I noticed that I get the following error in the console, whenever there is a userscript (any script) active on a page. This was in a virtual machine on Windows 7, where I had only Umatrix and Ublock installed in an otherwise clean profile:
`[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.principal]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///C:/Program%20Files/Mozilla%20Firefox/browser/omni.ja!/components/nsBrowserGlue.js :: prompt :: line 2998"  data: no]  (unknown)
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.cancel]  nsBrowserGlue.js:3022`

**Comment by arantius** [comment]
> 17:32:05.430 Error opening user-scripts DB! <unavailable> openDb/</dbOpen.onerror moz-extension://170887a0-7392-494a-8773-b4654ca36991/src/bg/user-script-registry.js:57:7

Something has corrupted your profile.
