### ISSUE TITLE
Test install in Firefox for Android

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2827]
I believe it's impossible to install scripts after #2719 in Firefox for Android.  Confirm.

**Comment by Sxderp** [comment]
Reasoning? I haven't checked but I don't see anything that would imply it wouldn't work. According to MDN the new API calls are available in FF for Android.

I'll take a look and report back.

**Comment by Sxderp** [comment]
The script dialog pops up fine and 'seems' to install.

I say 'seems' because there's a different problem. The Monkey Menu is borked. I'll hook up the debugger and see if I can figure it out.

**Comment by Sxderp** [comment]
Actually, what breaks Android is #2812 

```TypeError: navigator.storage is undefined```

According to MDN: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorStorage/storage
> Firefox 51 introduced NavigatorStorage, Navigator.storage, and the StorageManager.estimate() method. These are enabled by default in nightly builds but disabled by default in all other builds. You can enable these features by setting the preference dom.storageManager.enabled to true.

Looks like I'll have to re-add the conditional.

**Comment by arantius** [comment]
Tested in 4.3beta4, works well.
