### ISSUE TITLE
More monkey background color glitches

### ISSUE THREAD

**Issue by NoneGiven** [greasemonkey/greasemonkey#2833]
Version: 4.3beta4
Platform: FF58 on Windows 10

(1) Scroll up or down in your user script list, then click a script to open its details pane. During the transition animation to and from the details pane, the bottom section will be messed up. This only happens if you scroll first.

![image](https://user-images.githubusercontent.com/2163967/35828105-5f5dbb7a-0a8c-11e8-9626-8e9b028cbf90.png)

(2) In the script details pane, mouse over and then off the `Uninstall` item. It will not properly return to the "unselected" look when you mouse off.

![image](https://user-images.githubusercontent.com/2163967/35828207-acf4f3a8-0a8c-11e8-88e3-76b20703c6fc.png)

Edit: The precise behavior of the second one can apparently vary between displays/machines, but there's some weirdness either way.

**Comment by Sxderp** [comment]
It's a Windows thing. Pretty sure the transition effect is what makes it prominent, but it's not something we can eliminate altogether. Mozilla needs to fix their rendering engine. This is much better than what it was at first, and is actually still readable. I'm not sure what can be done short of going completely back to the old style (which probably still had glitches, just less noticeable).

See https://github.com/greasemonkey/greasemonkey/issues/2822#issuecomment-361719768 for links.

**Comment by Eselce** [comment]
Does anyone have the same issue under windows system as me?
I get some of the text strings clipped at the bottom (such that the baseline and lower is missing).
I've got the feeling, that it's just the translated strings, but it looks really strange...

**Comment by Sxderp** [comment]
> Does anyone have the same issue under windows system as me?

Not the same as pictured above? Could you post a picture?

**Comment by Eselce** [comment]
> Not the same as pictured above? Could you post a picture?

I've managed to show at least a part of that:

![](http://eselce.github.io/GitTest/misc/img/GM-string-glitch.png)

It also affects the `New script...` part and the 3 links at the bottom, as well as the submenus...

**Comment by Sxderp** [comment]
Are you using FF with some theme or are you using a fork? If it's a fork them it might be because of the `-moz` (which are really great and should be added to the standard...) attributes / values in the CSS.

**Comment by Eselce** [comment]
That one was the developers ed. Let me try out my main version...

**Comment by Sxderp** [comment]
I don't think that would make a difference. It might, but last I checked there wasn't much different between developer edition and release. If I recall correctly it was more like a glorified beta. Some additional features that eventually get moved into release.

**Comment by Eselce** [comment]
Nope. GM 4.3beta4 with
- 58.0.1 (64-Bit) Quantum
- 59.0b6 (64-Bit) Developer Edition (aurora)

**Comment by Eselce** [comment]
And as I can see it, it's only the locale strings. Not the script names. And they seem to be adjusted a bit lower (compared to the names and/or the icons)...

**Comment by Eselce** [comment]
I used to have it in order to compare FF 56.x and FF 57.x. No longer today. Now it's just to have two seperate installations. They don't differ much!

**Comment by Sxderp** [comment]
If you switch to English does the problem persist? It could be the characters are using more 'line-height' or some such.

Other things I'd suggest and see if it persists. Unfortunately I don't have access to FF57+ atm and it'd be a PIA to configure something up right now.
- Forcibly set static strings
- Add `after="{something}"` to one of the `a` tags (adds text in the same area as the arrow)
- Add `next-menu` to one of the `a` tags (will add an arrow to the end)
- Change the name of a script to something with non-ascii characters (and see if it breaks)

---

Some other tidbits.
Windows 10?
Scaling setting? Unless I'm mistaken your text looks larger than what's in the OP. May be related.

**Comment by Eselce** [comment]
> If you switch to English does the problem persist? It could be the characters are using more 'line-height' or some such.

Have you ever tried to switch the FF language pack? I'm still stuck with my german installation, but working on it. Settings ->(preferred) Language doesn't do anything (but selecting english pages? dunno).
EN-US language package installed => gave me a AddOns tab `Sprachen` (Languages), but didn't change a lot.
Still working on it...

Also checking things similar to those you mentioned (I will change sth. with my eclipse/GitHub system and install it temporarily - that worked already!) Maybe tonight...

8.1 (refused to upgrade 10)
probably no scaling (that graphic may be about 1/5th height and 1/5th width of the screen (not too big)

**Comment by Sxderp** [comment]
> Still working on it...

What's your Windows set at? I'm pretty sure there's a configuration option in FF that uses the OS locale and disregards pretty much all other settings. Might be behind `about:config` or somesuch.

**Comment by Eselce** [comment]
Must be `%LOCALE%`...

**Comment by Sxderp** [comment]
> ... did not work.

Almost missed this, only saw it because I almost never close tabs and happen to click on this particular tab. If you have an update just post another message.

Anyway I'll try installing a windows VM under a different language and see if I can reproduce. Sometime this weekend.

**Comment by Eselce** [comment]
I know, that I didn't produce a new notification. I did that, because there was almost no time between my posts (just your reply), and my try was almost immediately blown up (just saw the `%LOCALE%` entries in the `about:config` and made a (false) guess). I'm also heavily busy now, maybe tomorrow, or at the weekend as well for me...

**Comment by Sxderp** [comment]
I can't seem to reproduce the offset error. I've tried with different FF language installations, Windows display settings, FF font sizes, UI compact settings.

This is on Windows 10 1709.

**Comment by Eselce** [comment]
Maybe it's a Windows 8.1 thing? The data is correct, just the alignment fails...

**Comment by Sxderp** [comment]
Could be. I don't have any Windows 8 systems to test. Nor can I get ahold of one.

**Comment by arantius** [comment]
The issues I've seen most recently are minor but recently still present, Windows 7.

**Comment by arantius** [comment]
Right now on Win7, I see:

1. Every time the "uninstall" entry is deactivated, it retains (most of) its grey active background.
2. Scroll down the main view, click into any sub-view; a bunch of the dialog turns black while it's animating in, and back out.  Subsequent switches look OK.

**Comment by Eselce** [comment]
Number 1 seems to be gone, but now, there is a different grey active background (just baseline). Maybe only Win 8.1 (then it's okay, just broken).

**Comment by arantius** [comment]
These visual glitches are unfortunate, but only cosmetic, so I'm deferring any remaining fixes to the next release.

**Comment by arantius** [comment]
Working on this here:

https://github.com/greasemonkey/greasemonkey/compare/master...arantius:monkey-menu-rewrite

It doesn't have the brand new "scroll only the scripts" feature, but otherwise is a lot less code to do the same things.  And *fingers crossed* might address visual glitches.

**Comment by Sxderp** [comment]
Can't test at the moment, but there are two things with the menus that I'd like to know.
1. Does it support multiple different "next" or "arrow" menus? For example if #2770 is added, will transitions work properly going to the different menus?
2. Does it support nested "next" or "arrow" menus? Currently there isn't a use for this but it was something I figured might be useful down the line. For example, adding user includes / matches might be an extra nested menu.

**Comment by Sxderp** [comment]
Ah, a third thing.

3. Does rv-unless evaluate more than once? If you have some scripts, then remove  them all, does the visual 'break?' That is, do all the `<hr>` lines get removed properly when examining the 'top' menu?

**Comment by arantius** [comment]
Oh, I'm missing the little ">" arrows to indicate "will open a submenu".

> Does it support multiple [sub] menus?

No.  I don't build support for anything that isn't needed now.  I can imagine how to do this with very few changes though.

> Does it support nested [sub menus?

No, same thing.

> If you have some scripts, then remove them all, does the visual 'break?' 

This is a problem with the menu today, before any changes.  E.g., test profile...

Before:
![image](https://user-images.githubusercontent.com/84729/38102761-3cb1f0fc-3352-11e8-97c5-99cb913cb3ac.png)


After uninstalling the only installed script, and going back "up":
![image](https://user-images.githubusercontent.com/84729/38102742-26d7abc8-3352-11e8-99b3-b06fc8c82d2a.png)

Haven't tested yet in this branch, but I expect it will work.

**Comment by Sxderp** [comment]
> This is a problem with the menu today, before any changes. E.g., test profile...

OH. I forgot, I had a change in my monkey-menu.js that I had set to ignore. This issue is caused by this line (in current code) https://github.com/greasemonkey/greasemonkey/blob/712b357f373b0ca0ea96ef3d2fdc26ed4801a084/src/browser/monkey-menu.js#L322-L324.

The `active` / `inactive` scripts are never removed from the array.

**Comment by arantius** [comment]
> Well, hmm, the third link at the bottom (Get user scripts) is not withing the menu, it is scrolled (without scrollbar) when moving down.

Can you elaborate?  I don't know what you mean.

> Also (in the submenu), two horiz. lines were removed (below the header and below the details).

Yep, whoops.


That said, on Win7, I'm still seeing glitchiness, but not as much as before.  Only while scrolling the scripts (the only thing that scrolls), and isolated to the newly visible elements.

Also just noticed: mouseout should un-focus.

**Comment by Sxderp** [comment]
Maybe it's just me, but I feel like the whitespacing is off (there's less of it) around each menu item. If you look at a native FF menu there's actually quite a bit of whitespace.

**Comment by Eselce** [comment]
I don't know, if it's a Win 8.1 (misrendering) thing, but it was a bit unclear:
> > the third link at the bottom (`Get user scripts`) is not withing the menu, it is scrolled (without scrollbar) when moving down.
> 
> Can you elaborate? I don't know what you mean.

After opening the menu, `Get user scripts` is not shown (it's virtually below the menu window). When I move the mouse down below `Greasemonkey Wiki`, the menu scrolls (although there's no scroll bar), so that I can see the last line, but at the top, `Greasemonkey is active` disappears.

This is a sign of not having enough space for the menu items plus the fixed space for user script names.

**Comment by Sxderp** [comment]
Looking at the latest commit, he made the scroll bar section too large (380px). The latest master has it set to 350px to fix  the nested scroll bar issue.

**Comment by Eselce** [comment]
Oh, if it's the old one, then it should be okay...

BTW: Is it just me, maybe I'm biased, but if find it pretty unusual to have `Export` before `Import`. I feel like having a default order of `New` / `Open` / `Save` and `Import` / `Export`. While it's still just convention...

**Comment by Sxderp** [comment]
> Oh, if it's the old one, then it should be okay...

I meant, latest on Greasemonkey main branch.

Also: Whitespace? (before - after)
![before-after](https://user-images.githubusercontent.com/6609453/38119027-7650c81a-3384-11e8-980f-5e45bac2ca74.png)

**Comment by Sxderp** [comment]
Comparison of native FF back button hover (above) and GM new back button hover. Native FF has a margin around it.

![backbutton](https://user-images.githubusercontent.com/6609453/38119199-978b7312-3385-11e8-945c-978528e52ec2.png)

**Comment by arantius** [comment]
> pretty unusual to have Export before Import

Mostly *shrug*, but any given user needs to export before they can import?

**Comment by Eselce** [comment]
> >     pretty unusual to have Export before Import
> 
> Mostly shrug, but any given user needs to export before they can import?

I can easily follow that reasoning, but when I look around, it seems, that the natural order is quite often (if not always) `New` / `Open` / `Save (as)` / `Import` / `Export`. Whatever the reason is, I don't really know...

**Comment by arantius** [comment]
I don't think we can actually fix this, it's Firefox that's broken:

https://bugzilla.mozilla.org/show_bug.cgi?id=1418677#c20

So I'll address the general appearance items called out above and call this done.
