### ISSUE TITLE
Script with @require statement fails to install, Download error unknown

### ISSUE THREAD

**Issue by fletchowns** [greasemonkey/greasemonkey#2834]
This is with Greasemonkey 4.2 on Firefox 58.0.1 on Windows 10 64 bit. Seems to have started occurring with the Firefox 57 release back in November.

Source of the script:
```
// ==UserScript==
// @name           SomeTestScript
// @version        1.0
// @namespace      fletchowns
// @include        https://na*.salesforce.com/*
// @grant          window
// @require        https://code.jquery.com/jquery-2.1.1.min.js
// @require        https://na1.salesforce.com/soap/ajax/30.0/connection.js
// ==/UserScript==

alert('Hello world');
```

Externally hosted version for testing: https://fletchowns.net/files/SomeTestScript.user.js

When I try to install it, I get the following:
![image](https://user-images.githubusercontent.com/153107/35834701-c98314ce-0a8b-11e8-805b-9ffe39fd2f75.png)

**Comment by Sxderp** [comment]
Hrm, works for me.

1. Are you able to individually download the requires?
2. Did you try with a fresh profile?
3. RIP Windows?

**Comment by fletchowns** [comment]
Interesting! Thanks for taking a look @Sxderp .
# Yup I am able to individually download the requires
# Just tried it with a fresh profile and that seemed to fix it!
# Strangely, it was reported to me by many different users the day Firefox 57 shipped

Is there something I can do to my old profile to get it working again on there?

**Comment by Sxderp** [comment]
Depends on what you're willing to lose, for options that may not resolve your problem (thus leaving you in a worse state, having broken GM with no data).

- You can try removing scripts one by one.
- You can try entirely removing GM restarting the browser and adding GM.
- You can try cloning the latest master loading as temporary addon and see if it works.
- Other experimental things with other published experimental branches.

Note. Most of the above could potentially (probably will) cause some sort of user script data loss.

**Comment by fletchowns** [comment]
Thanks again for the suggestions. I tried removing GM, restarting the browser, and then adding GM. Still getting the download error upon script installation though.

**Comment by fletchowns** [comment]
Also tried clearing out `C:\Users\username\AppData\Roaming\Mozilla\Firefox\Profiles\vdxns7l1.default\gm_scripts` but that didn't seem to work either

**Comment by Eselce** [comment]
Works for me as well using GM 4.3beta4

**Comment by Sxderp** [comment]
> C:\Users\username\AppData\Roaming\Mozilla\Firefox\Profiles\vdxns7l1.default\gm_scripts

Unfortunately that's where GM 3.x stored scripts. 4.x uses a more restricted means of storing data (required due to WebExtensions). And would be somewhere like `...\vdxns7l1.default\storage\default\moz-extension+++A_BUNCH_OF_ALPHANUMERICS`. Unfortunately figuring out which one is GM is a little difficult.

If you have one of those folders that includes a file with a similar name to `gyreekansoem.sqlite` then it MIGHT be the GM folder. But I can't guarantee it. And thus you may be deleting some other extension's data.

**Comment by fletchowns** [comment]
Interesting, thanks for the additional details @Sxderp .

I did see a couple files in there with `gyreekansoem` and noticed that when I uninstall Greasemonkey, those folder did get removed as well. I don't have any other extensions installed so I was left with no more `storage\default\moz-extension*` folders.

Not sure what else to try at this point other than just nuking my old profile and starting fresh.

**Comment by Sxderp** [comment]
The only other thing I can thing of is some non-default preference that interferes with WebExtension functionality [1]. The biggest generally have to do with privacy. How restrictive are your data retention policies?

[1] A lot do. And they really shouldn't. YAY!

**Comment by fletchowns** [comment]
Whoops missed that last reply @Sxderp !

> How restrictive are your data retention policies?

In my Firefox preferences I had Tracking Protection set to Always. I changed it to Never and now I am able to install the userscript. Thank you!!

@arantius Is that worth adding to the documentation?

**Comment by Sxderp** [comment]
@fletchowns I don't think it's worth it. If I remember correctly FF 59 will have a fix. And that will be release in March (I think).

**Comment by Eselce** [comment]
FF 59 release: March 13, 2018. Marked in my calendar! ;-)

**Comment by fletchowns** [comment]
Still fails in FF59 with tracking protection enabled. :(
