### ISSUE TITLE
Cannot install some scripts from openuserjs.org

### ISSUE THREAD

**Issue by chenjiajia9411** [greasemonkey/greasemonkey#2837]
Firefox Version:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 ID:20180209102946
Greasemonkey Version:4.3beta4

When I tried to install [this script](https://openuserjs.org/scripts/joshu/BGM_TV_Bug_Fixer),the browser just returned a blank page and no installation popup turned up,also appeared when I attempted to install another [script](https://openuserjs.org/scripts/ruocaled/0.33333333333333333333333%E7%AD%89%E4%BA%8E1).

I also tried a brand new firefox with only greasemonkey installed but have no effect.

But if i disabled greasmonkey,the content of the script would show in the browser,so I guess this is a bug of greasemonkey.

**Comment by Sxderp** [comment]
Well, it's a partial bug. The two scripts you link have invalid `@match` patterns. The intended behavior is to just show the script. However, you will not get an install dialog. And I don't think `@match` will be extended to accept the invalid patterns. I don't know if there's an official 'standard' for those patterns, but they're used basically is if there was one.

**Comment by arantius** [comment]
> The intended behavior is to just show the script. However, you will not get an install dialog.

I disagree.  The script should be installed as if that `@match` wasn't even there.  Regardless of what kind of parse errors there might be, anything that isn't completely fatal should be ignored.

**Comment by Sxderp** [comment]
Even if it's installed, you still get hit with the script not behaving as intended. In this particular case since the only match / include keywords are invalid it would be treated as a global match. And the script would run everywhere. I believe this is a worse than not installing.
