### ISSUE TITLE
Global Exceptions in GM 4.x

### ISSUE THREAD

**Issue by kekkc** [greasemonkey/greasemonkey#2843]
Hi all,

this is known, but I haven't find an issue for it. We absolutely need global exceptions again (sites where no scripts should be executed, e.g. banking sites...).

Apart from the already implemented save button in editor, this was the most prominent feature I missed after the transition from GM3>GM4.

![global exceptions](https://user-images.githubusercontent.com/6283064/36072844-443170ea-0f27-11e8-80c0-7e33671c1b30.png)

**Comment by arantius** [comment]
Agreed.  I absolutely want this plus per-script user include/exclude settings.

**Comment by arantius** [comment]
I don't know what "this" you're referring to, but the images above are GM 3.  What I added recently (in a dev branch) to GM 4 is:

![image](https://user-images.githubusercontent.com/84729/42167683-bc20d4a0-7ddc-11e8-906b-6ae529fc1791.png)

**Comment by Cerberus-tm** [comment]
Oh, I should have noticed, what with the editor section and all. But the global excludes are great! I'll happily use that function for sensitive/difficult pages.
