### ISSUE TITLE
Don't hide scripts when prompting to install.

### ISSUE THREAD

**Issue by kevincox** [greasemonkey/greasemonkey#2851]
Currently when navigating to a URL ending in .user.js the navigation is blocked and an install dialog is presented. I see no reason to cancel this navigation as doing so blocks the user from reading the script if they don't want to install.

**Comment by Sxderp** [comment]
Checkout the latest beta. #2719 changed script detection to the background and it will now display the navigated content. Further improvements can be found in #2830.

**Comment by kevincox** [comment]
Thanks, those changes sounds great and resolve this issue.

**Comment by arantius** [comment]
>  Checkout the latest beta. #2719 changed script detection to the background and it will now display the navigated content...

I consider that a bug and I'm not promoting beta until it is fixed.  But also, don't reopen, because what you're describing is absolutely the intended behavior.

**Comment by kevincox** [comment]
Can you please explain why this is intended behaviour? It seems to me like unconditionally removing browser functionality isn't a great feature.

**Comment by Sxderp** [comment]
@kevincox further discussion should probably be made in #2817.
