### ISSUE TITLE
Script eval content not always being calculated

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2856]
Reproduce:

Open Monkey Menu and select new user script.
Do not touch anything in the editor (or just close it)
Navigate anywhere and look at browser console

```
Could not execute user script: [Greasemonkey script null/Unamed Script 359106; version1]
Error: executeScript requires either a 'code' or a 'file' property, but not both
```

Occurs because `evalContent` is null.

**Comment by Eselce** [comment]
Fun fact: That was my favorite setup for producing an error message... ;-)

**Comment by arantius** [comment]
14537f5e9058b7fbb08f0c8e655b1595b52edee6
