### ISSUE TITLE
Scripts not found after 4.3beta4 update

### ISSUE THREAD

**Issue by Maeyanie** [greasemonkey/greasemonkey#2861]
Did the path to scripts change in 4.2 or something? My scripts were all working yesterday, then today Greasemonkey thinks I don't have any.

They still exist on disk, in gm_scripts under my Firefox profile, just aren't showing up in Greasemonkey's list, and not executing on pages they should.

**Comment by Sxderp** [comment]
WebExtensions don't have access to the disk. Scripts are no longer saved nor read from disk.

**Comment by Maeyanie** [comment]
Ok... two questions then.
a) Why did it work before, then just suddenly stop yesterday, despite not even restarting Firefox?
b) If I can't store scripts on the disk, how is Greasemonkey supposed to work? Save them to RAM and re-enter them every restart? Put them on a website and have them loaded from there?

**Comment by Maeyanie** [comment]
Nope, it's worse than that, even if I click "new script", copy-paste one in, then save, it doesn't show up in the list. Something's definitely messed up on this system, and not sure what...

**Comment by Maeyanie** [comment]
Since this is now working and possibly-not-Greasemonkey's-fault, I'll close this... though still no idea what would cause it to suddenly stop working like that.

**Comment by Sxderp** [comment]
> If I can't store scripts on the disk, how is Greasemonkey supposed to work?

If you want to get literal, the scripts are stored on disk. However, Greasemonkey has no control over how the data is stored on disk. We tell Firefox "store this data, k thanks" and the rest is opaque to GM.

**Comment by Maeyanie** [comment]
Yeah, I must have migrated at some point in the past, since I did find the scripts in my gm_scripts were old versions from before the GM_xmlHttpRequest to GM.xmlHttpRequest change which went with the new extension types. So that directory still being there was unrelated to whatever caused the actual problem (and I still have no idea on that part.)

**Comment by Eselce** [comment]
In one case, I've lost all my GM 4.x scripts (Windows) that way. As if the database was cleared.
But I don't know, if it was due to intensive testing or because there was a bug, and it just occured once...
