### ISSUE TITLE
Re-figure translation strategy

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2862]
So I first picked a `gettext`-inspired strategy whereby the "original" (English) strings remain verbatim in the source, to later be translated into any other languages that we have data for.  I tried to push 4.3beta5 to AMO and it has rejected it because

> Error: String name should only contain alpha-numeric characters, _ and @ (https://mzl.la/2Eztyi5).

So e.g. our new string "[Greasemonkey script $1]" is invalid.  Probably the one with a newline in it, too? So:

1. Generally decide how to address this -- what should our translation strings' "names" be if not the literal English version?
2. Write a test to make sure we never repeat this failure in the future.

**Comment by arantius** [comment]
Back at [4.3beta4](https://github.com/greasemonkey/greasemonkey/blob/b681b991cf293c96aa0b8702faf0b8c9547d122c/_locales/en/messages.json) we've got spaces, dashes, dots, double quotes, colons, and periods in our string names, and it uploaded fine.  Is this a new rule, or is the rule not as strict as it claims to be?  

There's 140 complaints, which makes 35 per our 4 languages so far.  We've got [41 English strings](https://github.com/greasemonkey/greasemonkey/blob/master/_locales/en/messages.json) defined, with 6 (Cancel, Disabled, Edit, Enabled, Install, Save) that happen to not trip this rule?

**Comment by Eselce** [comment]
Okaaaaay, these restrictions to `name` and `placeholder name` are quite interesting...
How did this even work before with our `i18n.getMessage`?
There's also two hints, that the `placeholder name` is case insensitive (still bad style).

So we'll have to reorganize the keys, and thus we should catogorize the strings,
with the names using camel case or `_`, e.g. `{category}{Key}` or even `{category}{Sub}{Key}`.
That makes the code less verbatim (use comments?), but the structure of the `messages.json`
could improve (better than just lexicographical order of the english message text)...

**Comment by arantius** [comment]
We definitely have to pick some pattern for how to pick the "name"s.

What I liked about the existing approach:

* The string name by necessity will change, when the original/English value changes, forcing a re-translate/review of the new translated versions.
* Source is readable, you know exactly what this translated string means.

Our old XUL [locales](https://github.com/greasemonkey/greasemonkey/tree/3.x/locale/en-US) used more "name"y names, tried to namespace things, but ended up with problems:

* Has both `<!ENTITY Sort.Name "Name">` and `<!ENTITY newscript.name "Name">`.  When trying to group things by where/how they're used, messes get made.
* I'm pretty sure there were cases where we changed the English value of a given named string, but the translations didn't necessarily get updated.
* The abbreviated names often don't make (enough) sense in the source.  Quick, what text will `label.grpMatched` show?  How about `install.warning1` or `install.warning2`?  What's the difference between `editor.prompt` and `editor.please_pick_executable` ?

**Comment by arantius** [comment]
It's also worth taking time to consider something besides transifex.  I don't know what other people think fo it, but on my end it's awful.  Downloading the translation output is only available by clicking a link which does nothing but (eventually) send an email -- the email will have a link to a ZIP -- the ZIP will have awfully mangled names for each translation which must be fixed to the right layout.

Even a list of alternatives would be valuable now.

**Comment by arantius** [comment]
See commit 0fb3c9776b2c7d7bfb0b1045ffdcea26ea4c042c as referenced above.  I've taken a dirty pass at this, just so I could cut a beta to AMO.  Started with lowercase-and-underscore everything, truncated some things, and put UPPER names for placeholders.

**Comment by Eselce** [comment]
Parameters are all-uppercase? Nice idea. It's a compromise...
But then `gm_script_id_ver` should be `gm_script_ID_VER`, because it's parameters `$1` and `$2`.

Zip, layout? I've used `Download for use` (okay, just one language per access), could easily paste it into my eclipse and diff it...

**Comment by arantius** [comment]
> But then gm_script_id_ver should be gm_script_ID_VER, because it's parameters $1 and $2.

Yes, whoops!  As should it be `gm_script_ID`.  A tiny hint in the code to what the extra inserted values are for.

> Zip, layout? I've used Download for use (okay, just one language per access), could easily paste it into my eclipse and diff it...

I still have to go looking every time, too many features in their UI... If I open resources to messages.json, then there's a "ZIP" link, which opens a dialog with a "request ZIP" button, which as said does nothing but separately send me an email.  Once it arrives it's got a link to a ZIP (which I've got to click, close the empty tab that opens, then delete the worthless email), which looks like:

    $ unzip -l greasemonkey_messagesjson_2018-02-22T21_40_17Z_414bfeb1d0fd49a6bf57bcb69ecceb36.zip 
    Archive:  greasemonkey_messagesjson_2018-02-22T21_40_17Z_414bfeb1d0fd49a6bf57bcb69ecceb36.zip
      Length      Date    Time    Name
    ---------  ---------- -----   ----
         4871  2018-02-22 21:40   messagesjson_de.json
         5388  2018-02-22 21:40   messagesjson_ja.json
         4638  2018-02-22 21:40   messagesjson_zh_CN.json
         4632  2018-02-22 21:40   messagesjson_en.json
    ---------                     -------
        19529                     4 files

The four files, but with mangled names ("messages.json" without the dot, underscore, the language, dot json), which I have to move to language/messages.json for each one.  (If they support the "Chrome" type, why don't they just put the files at that place in the ZIP?  And I don't want English in there either.)

**Comment by Eselce** [comment]
I've seen these files before. Probably more practical, if you have many languages (>4).
The filenames didn't bother me, because I pasted (Ctrl-A, Ctrl-C, Ctrl-V) into eclipse instead of copying files.

**Comment by vitaliyg2** [comment]
Hi,

Downloading zip manually is not that convenient, but there is a transifex client, 
it takes some time to configure it, but it saves a lot of manual hassle in the long run.

https://docs.transifex.com/client/introduction

I would also suggest to check the Crowdin translation platform,
it is harder to get free plan for opensource project there,
but I think it is more convenient than transifex.

**Comment by Eselce** [comment]
This sounds quite reasonable!

**Comment by Eselce** [comment]
Please upload the current source file (48 items instead of former 41).
It may take a few days to have all languages "on board"...

BTW: Tested the transifex client some days ago. Pretty convenient.
FYI: My config file looks like this (omitted `_locales`, may be added):
```
[main]
host = https://www.transifex.com

[greasemonkey.messagesjson]
file_filter = <lang>/messages.json
minimum_perc = 0
source_file = en/messages.json
source_lang = en
trans.de = de/messages.json
type = CHROME
```

**Comment by arantius** [comment]
> Please upload the current source file (48 items instead of former 41).

Whoops, sorry for missing this before.  Done.

Otherwise, strategy now seems good enough to move forward with so closing.
