### ISSUE TITLE
Add tests for downloader

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2864]
We'll need to mock out the XHR responses, but test coverage here will be a nice thing.

**Comment by Sxderp** [comment]
You'll have to break any message passing into multiple tests. 

And for each you'll have to assume you get valid data in the message (stub out to return some specific object). 

If warranted, additional checks can be made to ensure correct data was passed into `sendMessage`.

**Comment by Sxderp** [comment]
As for mocking XHR, than doing that just stub the download class (which is a very thin wrapper over xhr) to resolve some preset data for the tests.
