### ISSUE TITLE
Dealing with errors in downloader

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2869]
Something is missing.

Before I get to the issues, I need to pose a question. Should all downloads be aborted if an error occurs? Some thoughts I came up with for both sides. Yes, they should be aborted, you're wasting resources downloading everything else when we already know the script is not going to be installed. No, they shouldn't be aborted, you can document additional errors that occur. Currently nothing is aborted.

The issues, if a download fails for some reason, then it will [throw an error](https://github.com/greasemonkey/greasemonkey/blob/7db5f084acc5be7cb79c5d8efc76fd35212f2bed/src/downloader.js#L157-L160) in `async start()` but there is nothing to [catch these errors](https://github.com/greasemonkey/greasemonkey/blob/7db5f084acc5be7cb79c5d8efc76fd35212f2bed/src/content/install-dialog.js#L113). Furthermore, it looks like there was some [tracker of errors](https://github.com/greasemonkey/greasemonkey/blob/7db5f084acc5be7cb79c5d8efc76fd35212f2bed/src/downloader.js#L10) (somewhat makes sense if downloads are not to be aborted) and it's even [checked for content](https://github.com/greasemonkey/greasemonkey/blob/7db5f084acc5be7cb79c5d8efc76fd35212f2bed/src/content/install-dialog.js#L17) [1], but nothing is ever added to this error list.

What it looks like is that the code can't decide if it wants to abort everything and report an error right away, or if it wants to sit around waiting for everything to possibly finish, tallying errors as they come in, and then report.  Currently, it does neither.

As an additional point, if `scriptDetails` is rejected then `async start()` will resolve without any errors. Which would imply that "all is well."

[1] This on progress error checking is broken in two ways. The first is that it loops over `message`? And the second is that, assuming `gDownloader.errors` ever had any content, if there was a single item still downloading and posting progress a new error list would be created and appended every time that progress was posted.

---

As an aside, it might be a good idea to split `async start()` up into multiple functions. It is a somewhat long.

**Comment by Eselce** [comment]
Maybe this fits in here (not fully): If you change the @name of a script to an existing name and save, that error is no longer handled. And it's silent. I also used a new script, saved it, then there were two scripts resulting.

Second: Suppose, I have a script on server1 with a @require on server 2, which is not reachable. Maybe even think about having a working update function. Do I want to download the script, when the @require could not be loaded? Do I want to unload that script? What, if you have a script from a server, that is no longer, but that @require'd resource has a new version with the same interface? Will it update? (Okay, this can only happen with a working update function, so we don't have to bother, yet.)

**Comment by Sxderp** [comment]
As for your second, I would hope that no changes are made unless all resources and metadata are accounted for.

**Comment by Sxderp** [comment]
As for your first, yeah, I don't see any errors. Though, I think a name check should be performed before any actual downloads occur. That way we don't waste resources and time attempting to downloading resources that aren't going to be saved.

**Comment by Sxderp** [comment]
I figured out more details behind your first problem and created another issue. #2873

**Comment by arantius** [comment]
I pushed a CL which tracks and routes error messages to the install dialog.

I feel like the buttons should probably remain, with install in the disabled state but cancel still available.  As its laid out now that will take some refactoring.

**Comment by arantius** [comment]
First non-testing time I tried to install after this, I got:

    TypeError: e.failedDownloads is undefined install-dialog.js:120:3
    TypeError: resultEl is null install-dialog.js:79:26

Error is "iconDownload is not defined".

**Comment by Eselce** [comment]
`#resultText`?

**Comment by Eselce** [comment]
The good message is: without `rv-if`, it works for me (second issue).
Although the window closes much too fast...
I guess, #2866 does not extend to this issue?

**Comment by Sxderp** [comment]
Some comments. The first is that I find the usage of `result` (variable / identifier naming) misleading. The identifiers should really be `error`. The dialog never shows a non-error result (success just closes).

Further, the commit is a good start but the progress listener needs some work. Honestly, the error checking inside of it can be removed (currently it's broken and doesn't even do any proper checks) and just use it to update the progress bar and use the `.catch` for the errors. Further, rather than using the progress listener to run `maybeEnableInstall()`, just run it in a `.then` from the downloader start.

**Comment by Eselce** [comment]
> The dialog never shows a non-error result (success just closes).

It shows Download successful message, if you omit the `rv-if`, then it closes (too) fast with a `New Tab` being empty (plus editor tab, if chosen).

**Comment by Sxderp** [comment]
> It shows Download successful message

"Shows". The javascript replaces it, but it's not displayed long enough to be relevant. As for having a distinction between "script has been downloaded" and "script has been installed", I don't think it's important to put any text on screen.

What should be done is what some of those old style installers do (ish). While the script is downloading show the progress. When it's complete set the progress bar value to null (unset the property) which will cause it to twirl. Keep it twirling until installed. Then just close the window.

**Comment by Sxderp** [comment]
> First non-testing time I tried to install after this, I got:

The `.catch` assumes the error that is thrown is the custom error from the downloader (bad assumption I suppose). We should switch to a custom name or class for errors we throw.

**Comment by Eselce** [comment]
Not sure about that auto close. Normally, the `Install` button morphs to `Finish` (or `OK`) to confirm the correct installation...

**Comment by Sxderp** [comment]
It autoclosed in GM 3. Did I miss something and it behaves differently now?

**Comment by Eselce** [comment]
I really don't remember anymore... :disappointed:

**Comment by juozaspo** [comment]
Trying to install an user script from Github using 4.3beta7 fails with error `User script download failed` in the dialog after I click install. After checking Browser Console, I see same errors as in earlier post made by @arantius. GM 4.3beta6 Works fine.

**Comment by Sxderp** [comment]
@juozaspo that issue should be resolve on current master. 

There are still some other UI improvements that are needed though.

**Comment by arantius** [comment]
Please let me know if there's something I've missed, but testing at current head makes me happy about the current behavior.

**Comment by arantius** [comment]
All above fixes are in the latest nightly build ( https://arantius.com/misc/gm-nightly/greasemonkey-2018.03.07nightly.xpi ).  Please try it out and confirm whether they cover these issues.
