### ISSUE TITLE
installFromDownloader (and downloader) not updating scripts properly

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2873]
Couple issues.
Reproduce.

1. Create a new script from the Monkey Menu
2. Paste the following and save
```javascript
// ==UserScript==
// @name     ItemNumber1
// @version  1
// @grant    none
// ==/UserScript==
console.log('Hello');
```
3. **First issue** Check the Monkey Menu. Rather than updating the current script GM basically did a "save as" and created a new script item "ItemNumber1"
4. Close your editors (don't uninstall any scripts yet) and create a new script from the Monkey Menu.
5. Paste the following and save
```javascript
// ==UserScript==
// @name     ItemNumber1
// @version  1
// @grant    none
// ==/UserScript==
console.log('This Content Will Change');
```
6. **Second issue** Open the Monkey Menu and click to edit each of your scripts. You'll notice that "ItemNumber1" has changed, even though you weren't editing it.

---

This has to do in part with the `downloader` not taking in the UUID from the editor and that `installFromDownloader` does no UUID checking and only checks against `namespace/name` (which I assume is to check if the script should be updated).

**Comment by arantius** [comment]
Thanks for the detailed report.  I totally _meant_ to pass UUID in this case.  But I re-wrote this a few times, moved from background to content scope, etc.  Missed getting this right in one of those passes, clearly.
