### ISSUE TITLE
Opening several user script install dialogs at once does not work

### ISSUE THREAD

**Issue by zuckel** [greasemonkey/greasemonkey#2876]
I have several user scripts bookmarked in a bookmark folder. If I open them all at once (there are 8) then most install dialog windows will be completely empty. Only between 1 and 3 of them will contain the expected install dialog.

There are two errors in the browser console, but they are also there if I open only a single tab.
- TypeError: cannot use 'in' operator to search for 'canGoBack' in 'browser'
- TypeError: browser.messageManager is undefined

**Comment by arantius** [comment]
> install dialog windows will be completely empty

What happens if you right-click in or resize the empty window(s)?

**Comment by zuckel** [comment]
Right-clicking or resizing will both show the expected content. I am on Ubuntu 17.10, FF 58.0.2 btw.

**Comment by arantius** [comment]
In that case this is completely unrelated to opening several scripts, it's https://bugzilla.mozilla.org/show_bug.cgi?id=1402110 and Mozilla's bug, not ours.
