### ISSUE TITLE
Programatically trigger install

### ISSUE THREAD

**Issue by JasonBarnabe** [greasemonkey/greasemonkey#2878]
When you click an install button on Greasy Fork, it will trigger an XHR request to increment the install counter and then navigate to the .user.js page. When the .user.js page loads, Greasemonkey triggers the install dialog and then navigates back to the previous page.

The problem with this is that sometimes the navigation will cancel the XHR and so the install does not get counted by Greasy Fork. I could try some trick with `setTimeout` but I was wondering if there was a way to tell Greasemonkey to install a URL without navigating away from the page, or if there was some other solution to this issue.

**Comment by arantius** [comment]
This sort of change (no navigation) is already coming in 4.3.
