### ISSUE TITLE
The "bg/value-store can delete a value" test is flaky

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2879]
https://travis-ci.org/arantius/greasemonkey/builds/346962147

It times out semi-regularly.  What's taking two seconds?

**Comment by Sxderp** [comment]
Am I missing something? I don't see any timeouts? Nor have I ever experienced one while running the tests locally.

**Comment by arantius** [comment]
D'oh, I hit restart and apparently it overwrote the timeout.

* https://travis-ci.org/arantius/greasemonkey/builds/333846252
* https://travis-ci.org/arantius/greasemonkey/builds/333781317

There's a couple I never retried, and I have seen it locally (rarely) as well.

**Comment by Sxderp** [comment]
Perhaps hiccups in opening and closing indexeddb? Each test opens and closes the database two or three times (once for each operation).

**Comment by arantius** [comment]
https://github.com/greasemonkey/greasemonkey/commit/b8eb199e180d9367bbe193e6319637c7f01b5e89#commitcomment-28087425

https://travis-ci.org/greasemonkey/greasemonkey/builds/352882389

**Comment by arantius** [comment]
Gonna call the above commit a "fix", until/unless another failure is observed.
