### ISSUE TITLE
Install dialog broken

### ISSUE THREAD

**Issue by zuckel** [greasemonkey/greasemonkey#2883]
The install dialog will show just fine.
When clicking the Install button, the dialog window will turn empty with the following error in the browser console:
```
TypeError: resultEl is null
install-dialog.js:79:26
```
This happens irrespective of the new checkboxes' state.

**Comment by Eselce** [comment]
Already being fixed #2869

**Comment by Eselce** [comment]
https://github.com/greasemonkey/greasemonkey/issues/2869#issuecomment-369403506

**Comment by Sxderp** [comment]
#2880 would resolve this.
