### ISSUE TITLE
Unable to save script

### ISSUE THREAD

**Issue by vitaliyg2** [greasemonkey/greasemonkey#2885]
There is an error in console:
ReferenceError: iconDownload is not defined[Learn More]
downloader.js:161:7

Greasemonkey 4.3beta7

**Comment by Eselce** [comment]
Found! Thank you...

**Comment by arantius** [comment]
b49e7204199f707f5ddafeb27d454193e704217c

**Comment by arantius** [comment]
All above fixes are in the latest nightly build ( https://arantius.com/misc/gm-nightly/greasemonkey-2018.03.07nightly.xpi ).  Please try it out and confirm whether they cover these issues.
