### ISSUE TITLE
Greasemonkey appears to be slowing firefox down

### ISSUE THREAD

**Issue by Question2** [greasemonkey/greasemonkey#2892]
According to about:performance greasemonkey is slowing firefox down even though i am not currently browsing any web pages which use greasemonkey or greasemonkey scripts at all.

Why is it doing this? It shouldnt be using any resources on sites that dont use anything greasemonkey related.

This is on Firefox 52.6 ESR 64 bit.

Greasemonkey has slown down Firefox frequently. When this happens, the slowdown is generally important.less

    Full name: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}.
    Impact on framerate: 7 high-impacts, 89 medium-impact (1 alerts).
    CPU usage: 1% (total 841927ms).
    System usage: 1% (total 108818ms).
    Blocking process calls: 0% (total 0ms).
    Measure start: 569 seconds ago.
    Processes: 24184 (parent)

**Comment by arantius** [comment]
A) You don't say what version of Greasemonkey.
B) I'll wager that it's some script you've installed rather than Greasemonkey itself.

**Comment by Question2** [comment]
@arantius : It was grease monkey 3.17. I updated it and its not even listed in about:performance anymore so i guess it must have been fixed in a previous version.
