### ISSUE TITLE
cant create any new scripts

### ISSUE THREAD

**Issue by isobyte** [greasemonkey/greasemonkey#2895]
Today found that grease-monkey had updated up to 4.2
Last time i was try ed to use this plugin was in 3.17- version
anyway.
Problem is then i write whole script and saved it , after reload script code is wiped out.
Other way my point is grease-monkey woun't save a write(d) script.
Why?

**Comment by arantius** [comment]
You haven't provided enough (nearly any) detail to answer your question.

https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help
