### ISSUE TITLE
No indication that a script is "installing"

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2898]
Before https://github.com/greasemonkey/greasemonkey/commit/2aed0b1e13ee779be42f0d7e0105ec427a4b161b the progress bar was reused as a "spinner" for the time frame between "clicking install" and getting the "finished" message. Granted, this time frame is generally less than half a second, but it could potentially be longer,  say IO blocking or something. Now there is no indication that clicking "install" has done anything, aside from the eventual closing of the window or display of error message.

**Comment by Sxderp** [comment]
> reused as a "spinner"

This was done by removing the "value" attribute which caused the bar to strobe.

**Comment by arantius** [comment]
What about the period after the download is complete but before the install button is pressed?

**Comment by Sxderp** [comment]
> What about the period after the download is complete but before the install button is pressed?

The progress bar was solid. Value stayed at 1.

**Comment by Sxderp** [comment]
What's the ruling for the time period in https://github.com/greasemonkey/greasemonkey/issues/2898#issuecomment-371214038? Is keeping it a value 1 acceptable? I don't think it should be hidden because that causes the UI to jump, and then jump again if it's reshown after pressing "install". Perhaps a darkening of the color (assuming that's doable) to indicate that it's "finished / locked" ?

**Comment by arantius** [comment]
> ... the time frame between "clicking install" and getting the "finished" message. 

I just made a script with 128 `@require`s (each of which is ~14k) as a stress test (so over 1.8 million bytes, 23k dense lines), plus threw in a timer:

    $ git diff
    diff --git a/src/content/install-dialog.js b/src/content/install-dialog.js
    index 5bc79425..f8aa155a 100644
    --- a/src/content/install-dialog.js
    +++ b/src/content/install-dialog.js
    @@ -63,10 +63,14 @@ document.getElementById('btn-cancel').addEventListener('clic
     /****************************** INSTALL BUTTON *******************************/
     
     function onClickInstall() {
    +  console.time('install');
       gProgressBar.removeAttribute('value');
       let disabled = document.getElementById('install-disabled').checked;
       let openEditor = document.getElementById('open-editor-after').checked;
    -  gDownloader.install(disabled, openEditor).then(finish).catch(err => {
    +  gDownloader.install(disabled, openEditor).then(() => {
    +    console.timeEnd('install');
    +    finish();
    +  }).catch(err => {
         gRvDetails.errorHeader = _('install_failed');
         gRvDetails.errorList = [err.message];
         document.body.className = 'error';

This crazy stress test script took ~300ms to install.  A similar test with 100 `@resource`s took ~100ms.  I'm on a pretty powerful machine now, but scale back to a realistic script and even down to a slower machine, and I still doubt the utility of such a change.
