### ISSUE TITLE
Pick new translation system

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2906]
See also #2862

Transifex seems to not be best for our needs.  Most critically, it's causing e.g.

https://github.com/greasemonkey/greasemonkey/commit/708944c1f1f8ec689d390f9aeb3335ed7b7d8dfa#diff-8dd89ce0c58ebdb57be57d03a1c156a5L141

The placeholders for all strings that use them are not present in the version that comes out of Transifex, so those strings are broken.  At least one user has suggested Crowdin, so experiment with (at least) that platform.

**Comment by eight04** [comment]
I had made a script to fix the placeholder problem: https://github.com/eight04/webext-tx-fix

**Comment by Eselce** [comment]
Nothing new! It's not as if solutions were missing... :slightly_frowning_face:

**Comment by Eselce** [comment]
Many steps with `transifex`? Have you tried to install the tx client?
For me, it's just clicking a one-line-batch:
`tx --debug --traceback pull`
or just
`tx pull`
(for all 5 languages) and
`tx pull -s`
for the source file (english).

**Comment by Eselce** [comment]
Got an announcement...

I can't confirm, that I am able (or willing) to move to crowdin under current conditions.
My initial examinations done in march were not very promising. I've aborted those tests...

**Comment by Eselce** [comment]
The issues with this new provider still hold! They are not solved...

**Comment by arantius** [comment]
What issues?

**Comment by Eselce** [comment]
E.g. nobody apart from you will be able to apply for an open license agreement. That was, what stopped me for the moment. (Dunno why french strings are missing!)

**Comment by arantius** [comment]
> apply for an open license agreement

How is that relevant?  The project already exists.  You don't need a special license to be a translator?

**Comment by Eselce** [comment]
To sign up, the obvious choice is an [open license](https://crowdin.com/page/open-source-project-setup-request):

> Before submitting this form, please ensure your project meets the following criteria:
> 
> 1. You have created translation project in Crowdin.
> 2. The project is licensed under an approved license from the Open Source Initiative.
> 3. Your project source code is available for download to the public.
> 4. You do not have Commercial products related to the Open Source project you are requesting a license for.
> 5. **You are the project lead.**
> 6. You have been working on your open source project for at least 3 months.
> 7. You have an active community of collaborators.
> 8. You keep the News section on your site up to date.
> 9. You release updated builds on a regular basis.

**Comment by arantius** [comment]
The quoted link is the "project set up" page.  You don't need to set up a project, it already exists, like i said.  You just need to https://crowdin.com/join

**Comment by Eselce** [comment]
Hmm, that join page looks like being able to sign up as well. I'll give it a chance!

**Comment by Eselce** [comment]
Works (if you approve). Can you please tell me,
- where my french strings have gone (shows 0% in overview)
- where the chinese traditional (zh_TW) and chinese simplified languages (zh_CN) have gone?

**Comment by Eselce** [comment]
... and please approve my joins (it's 17 idle hours now)...

**Comment by Eselce** [comment]
Hmm, can't use my spare time at the weekend... :-1:

**Comment by arantius** [comment]
> ... and please approve my joins (it's 17 idle hours now)...

Please learn manners.  You, as best I can tell, sent the invite request then nagged me via messages there in under an hour (!).  Then nagged here.  Again.  Does that really seem appropriate?  How much of my time am I supposed to dedicate to serving you?

We should be working _together_.  Relax.
