### ISSUE TITLE
Bare script does not install correctly

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2915]
Try installing https://github.com/greasemonkey/greasemonkey/blob/master/test/scripts/bare.user.js -- you'll get a dialog like

![image](https://user-images.githubusercontent.com/84729/37845792-0df563fc-2ea2-11e8-9669-58ca50564430.png)

With a details section that's completely empty.  It should communicate the (default) `@include *`.

**Comment by Sxderp** [comment]
This needs the `prepDefaults` part of #2904
