### ISSUE TITLE
AMO no longer supports Beta versions

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2924]
[AMO has discontinued support for Beta versions](https://blog.mozilla.org/addons/2018/02/28/discontinuing-support-for-beta-versions/): it only supports signing self-hosted (unlisted) versions now.
<sup>_Before that, they were listed in https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta_</sup>

I've posted this issue in order to suggest you to consider restoring the beta channel for Greasemonkey.

You could host the beta versions in GitHub, like e.g. uBO and uMatrix FF betas, or, in your site, https://www.greasespot.net .

**Comment by Eselce** [comment]
Oops, I thought, GM has taken it off with version 4.3. But that would explain it...

**Comment by arantius** [comment]
http://arantius.com/misc/gm-nightly/
