### ISSUE TITLE
No script options?

### ISSUE THREAD

**Issue by p1nkyy** [greasemonkey/greasemonkey#2925]
Script options disappeared altogether. For example, W.A.R Links Checker Premium (https://greasyfork.org/en/scripts/2024-w-a-r-links-checker-premium) is supposed to have some options in it, with GM, none at all. Kindly fix please.

**Comment by p1nkyy** [comment]
Ooo, sorry I didn't know the exact term. So unless it's done from the author's side, it's impossible then? So sad I have to switch. Thanks for answering @Eselce !

**Comment by Eselce** [comment]
The framework (and so to say, the syntax/language) of Greasemonkey scripts has changed a bit with GM 4.0+.

Unless the authors review (almost all) of their scripts, those won't work properly (only the really simple ones).
As there are lots of these scripts, many users complain, "woah, all my scripts are broken".
It's not that bad though, but there are really, really many scripts around...
