### ISSUE TITLE
Long description causes version to flow off Monkey Menu

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2927]
See picture, before and after rework.

![before-after](https://user-images.githubusercontent.com/6609453/38167267-17a79bde-34f8-11e8-806f-be26f5675eac.png)

**Comment by Eselce** [comment]
This will impact the home page link as well. Before, it was smaller, but the height was almost "unlimited" (within the window height), that's why there was a horizontal line below the details...

**Comment by Eselce** [comment]
... and the title is no longer aligned centered?

**Comment by arantius** [comment]
> that's why there was a horizontal line below the details...

I fail to see how an extra \<hr\> with nothing beneath it can be related?

In general, we just need to enable scrolling here.  Right now, the detail view inherits its height from the main view.  Ideally it would just get the "right height" but the _current_ implementation doesn't allow that.

**Comment by Eselce** [comment]
> > that's why there was a horizontal line below the details...
>
> I fail to see how an extra <hr> with nothing beneath it can be related?

The additional &lt;hr&gt; created the impression of a (detail) box.
As the submenu was "open ended", it looked a bit weird for me.
Best solution: adjust the height. Second best: box the details in.

```
< NAMEOFTHESCRIPT
-------------------------
o ACTION1
o ACTION2
o ACTION3
-------------------------
| DETAILS               |
-------------------------


```

**Comment by Sxderp** [comment]
> Right now, the detail view inherits its height from the main view. Ideally it would just get the "right height" but the current implementation doesn't allow that.

See my comment https://github.com/greasemonkey/greasemonkey/issues/2928#issuecomment-378087136

**Comment by arantius** [comment]
> The additional <hr> created the impression of a (detail) box.

Does any stock Firefox menu do this?  If I open the library/more/help section, they just put their items then stop, with whitespace.

Also: none of them ever shrink the window, when navigating to a subsection (thus, all the whitespace).  They only ever (rarely) grow it for a complex subsection.

**Comment by Sxderp** [comment]
> Also: none of them ever shrink the window, when navigating to a subsection (thus, all the whitespace). 

Pretty sure they shrink, I was playing with this the other day. I don't have access to 57+ right now to do any checks right now.

**Comment by Eselce** [comment]
As I said, the best solution is to resize the window. The rest is a matter of individual taste... :smile:

**Comment by arantius** [comment]
I see, stock Firefox menu:

![image](https://user-images.githubusercontent.com/84729/39544966-b788dc6a-4e1d-11e8-8b3b-d0d6f9fc1c45.png)

Then, after opening anything with a ">" (in this case, "More"):

![image](https://user-images.githubusercontent.com/84729/39544871-74373aba-4e1d-11e8-8bf6-19a67a565e3c.png)

In the rare case that there is *more* content (I think only "Library", if you have enough history/data) than would fit, the menu/window might grow larger, but I can't find any sequence of actions that ever makes it smaller than the starting size.

**Comment by arantius** [comment]
Before/after commit 52b560cde83d1d67dc5d3b00b3844f206856780f:

![image](https://user-images.githubusercontent.com/84729/39546924-f46f31e6-4e23-11e8-8714-f63a6b30bb54.png)![image](https://user-images.githubusercontent.com/84729/39546930-fb5b44e0-4e23-11e8-9f88-071f4c6bea90.png)

**Comment by Eselce** [comment]
> In the rare case that there is more content (I think only "Library", if you have enough history/data) than would fit, the menu/window might grow larger, 

Try `Text Encoding >` just in your own example...

**Comment by Sxderp** [comment]
> I see, stock Firefox menu:

You're looking at the wrong menus. On a new profile go to customize and stick the "Library" on the toolbar (or the "overflow menu"). Open the Library -> Bookmarks -> Bookmarking Tools. The menu definitely gets smaller.
