### ISSUE TITLE
Inferior keyboard navigation with rework Monkey Menu

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2928]
Firstly, small bug prevents arrow movement from working at all. [This](https://github.com/greasemonkey/greasemonkey/blob/237e7183c7f03c09101fe71fd226aa2a14932717/src/browser/monkey-menu.js#L228) needs to be changed to `[tabindex="0"]`. The original is an invalid selector.

After the above change is done here are some issues that I've found.
1. When initially opening the menu, if you arrow all the way to the bottom it'll eventually wrap to the user script detail page.
2. After pressing "enter" to go to the details page you cannot focus up / down with the arrow keys. You have to tab first. Previously when you navigated to the details page pressing "ArrowDown" would put you on the "enable/disable" button and pressing "ArrowUp" would put you on the "back" button.
3. Selection history is lost when navigating back to the main menu. Previously you could go back and you're selection would be on the same script, or one above/below if you uninstalled the script.

**Comment by Eselce** [comment]
Okay, that fits in here: Yesterday I tested the new menu with Win 8.1/FF 60...

Cursor navigation was totally broken, navigation with `<TAB>` and `<SHIFT>-<TAB>` was partly possible.
The oddest thing was your first topic: Below the bottom line, it wrapped to detail page (partly) with main menu left and detail page right, clipped at the sides. Very strange effekt... :smile:

**Comment by arantius** [comment]
I fear we'll have to do re-binding of the `tabindex` values to really fix this, which I was hoping to avoid.

**Comment by arantius** [comment]
Spoke too soon.  There's some complex interactions, but it's doable.

**Comment by arantius** [comment]
FWIW new version mirrors the main Firefox menu as closely as possible.  So first tab/arrow down selecting the first thing is intentional.

**Comment by Sxderp** [comment]
Took a look at the branch, looking better but it's still missing remembering previous (page) selection.

**Comment by Sxderp** [comment]
Also this is very minor, and probably not worth fixing but the current 'page' disappears right before you transition. Therefore you don't actually see it transition 'away'. You just see the other page transition 'in'.

**Comment by Sxderp** [comment]
Gah, I keep thinking of things after I close this tab.

Assuming we keep the WIP commits. #2927 can probably be resolved by taking the `section.clientHeight` (or is it offsetHeight, the one that includes padding and borders?) [hereish](https://github.com/arantius/greasemonkey/commit/775d9371ca66602c0edd47b44ee1fbb1204e57d9#diff-6ba827f37e1348164a6c4d6c5d015654R220) and assign it to `document.body.height`.

**Comment by arantius** [comment]
I believe the above commits resolve all the mentioned items that aren't already tracked in a separate issue.
