### ISSUE TITLE
No hover effect in menu on first (extension load) if GM is in overflow menu

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2930]
Reload greasemonkey (load as temporary, restart, etc). Put the icon in the overflow menu. Open the GM menu. There's no item highlighting when you hover over the entries. If you press the back button and re-open the GM menu the highlighting is working.

This is probably a Firefox bug, perhaps something to do with not focusing the html document root of an extension.

**Comment by arantius** [comment]
Right now I'm seeing up/down completely fail, due to the `tabindex` selector mentioned elsewhere.

I also observed occasional (timing issues?) failures to grab keyboard focus even when directly on the toolbar.

**Comment by arantius** [comment]
Also confirmed, but what can we do about it?

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1464424
