### ISSUE TITLE
Accessing and editing files with the help of NiklasGollenstede's native-ext

### ISSUE THREAD

**Issue by brunoais** [greasemonkey/greasemonkey#2932]
Even if as an extension to greasemonkey, are there any opinions or tests for making code to work in conjunction with [NiklasGollenstede's native-ext](https://github.com/NiklasGollenstede/native-ext) to provide back file editing in the user's preferred editor?

**Comment by brunoais** [comment]
@arantius almost 2 months went by. Any news?

**Comment by Cerberus-tm** [comment]
Wow, this sounds great! This would be the thing I'm waiting for the most. The readme sounds attractive, e.g.:

> Proposed solution
> 
> It seems that there is no way around Native Messaging. If you want to implement functionality that exceeds the APIs provided by the Browser, it is the only way forward.
> Therefore, both developing and installing and updating the native applications needs to be as easy as possible, to lower the barrier to entry for developers and users.
> This software aims to do that. Once everything is implemented as intended, the development - deploy - update cycle should be as follows:
> 
>     The developer can include node.js modules in the extension package
>         the script modules are written in same language as the rest of the extension
>     The user installs this free and open software with as few clicks as possible
>         this only needs to be done once
>         since this software has no own functionality and the protocol is simple, no updates should be necessary (once the API is finalized)
>     The extension prompts the user to download and run a very short and simple script that registers the extension with this software
>         the script places a file with its extension IDs in a predefined directory and calls a refresh script (writing the IDs is technically necessary)
>         scripts are so generic that they can be generated automatically, users who don't trust the scripts can perform their actions manually in about 30 seconds, see Installation
>     The extension can now contact this software without further user interaction
>         NativeExt locates the extension installation and makes the included node.js modules available to be executed it's slightly modified node.js process
>         to update the "native application", it is enough to update the extension with new node.js modules
>         this way, the versions of the extension and the native application always match

**Comment by brunoais** [comment]
@arantius 4 months went by. Any news?

**Comment by arantius** [comment]
The "news" is that I'm a volunteer, not an employee.  Nagging like this makes me want to work on your pet issue *less*, not more.

**Comment by brunoais** [comment]
I'm just confused about on which state this is. I may work on this, as an extension for greasemonkey... But I do need extension points to attach to.
@arantius I will wait until you have the time, then. I just have no idea in what state this issue is. It is attached to pony milestone which I have no idea what is and no one in the mailing list answered me either...

**Comment by cmalard** [comment]
Just discovered it in the [reStyle extension](https://addons.mozilla.org/fr/firefox/addon/re-style/), [suggested by Stylus](https://github.com/openstyles/stylus/wiki/Styling-Firefox-UI).
Would be awesome :tada:
