### ISSUE TITLE
Name conflict when creating backup zip archive.

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2933]
In order to prevent name conflicts a counter is appended to scripts that have the same name when creating the files in the zip archive. The problem is that the first time a name is found no counter is appended to the filename. Therefore, specific script names can cause conflicts. Below is a simple mapping of `scriptname` -> `filename`.

`example.com/RedBorder` -> `RedBorder.js`
`example.org/RedBorder` -> `RedBorder_(1).js`
`example.net/RedBorder_(1)` -> `RedBorder_(1).js`  [Conflict!]

The solution is to just remove the [else statement](https://github.com/greasemonkey/greasemonkey/blob/77d860bea43cbcb1fc39dd67e101c5ec3c6e2404/src/bg/export-db.js#L59-L61) and make the reassignment unconditional. The result would be:

`example.com/RedBorder` -> `RedBorder_(1).js`
`example.org/RedBorder` -> `RedBorder_(2).js`
`example.net/RedBorder_(1)` -> `RedBorder_(1)_(1).js`

**Comment by Eselce** [comment]
Is that compatible to the other file formats?
Is `..._(1)` supposed to be a sensible @name,
and if yes, why not use an extension that is not?
I'd prefer to have a use case script called `SCRIPT`
saved as `SCRIPT.user.js` or at least `SCRIPT.js`...

**Comment by Sxderp** [comment]
This is just to keep files unique in the archive. Users aren't going to see the file names unless they dig through the archives. As for whether `..._(1)` is a sensible script name, I don't know. But just changing what we use as an identifier will not solve the problem.

> Is that compatible to the other file formats?

I'm not sure what you mean.

> I'd prefer to have a use case script called SCRIPT
saved as SCRIPT.user.js or at least SCRIPT.js...

This would be nice, but it's not doable. Every script in the archive needs to have a unique filename. If we don't append some unique identifier to *every* file (not just duplicates) then there's eventually going to be some conflict between what we use as an identifier and what some other script names itself.

**Comment by Eselce** [comment]
other file formats = e.g. Tampermonkey style (I know, the resulting names are within the files themselves)

not doable: I know all your arguments, but you can **not** avoid conflicts, if you are using file name extensions that are usable as script names. So either choose a name extension, that is valid as filename (in the zip file) and not in a script name, and use it only in these special cases **or** you can as well use this comprehesive name scheme:

```
000_scriptA.user.js
001_scriptB.user.js
002_scriptC.user.js
...
999_scriptWhatEver.user.js
```
If you don't, what about having a script named `RedBorder_(1)_(1)` in your example? Still a conflict!

**Comment by Sxderp** [comment]
> So either choose a name extension, that is valid as filename (in the zip file) and not in a script name,

I don't think there's any limitations on script names. Pretty sure they're just read literally and saved as is.

> If you don't, what about having a script named RedBorder_(1)_(1) in your example? Still a conflict!

No, it'll just become `ReadBorder_(1)_(1)_(1).js`.

> **or** you can as well use this comprehesive name scheme:

The essence of your solution is no different than mine, you append some unique identifier to _every_ script. Doing it to _every_ script will not cause conflicts. For mine it's a two column index (basename + count), for yours it's a single column index (global count).

Anyway, we're going in circles. As suggested, in order to resolve the problem it may be more performant, as well as easier to read, to change the method of unique identification, rather than modify the current method to ensure uniqueness.

**Comment by Eselce** [comment]
> No, it'll just become `ReadBorder_(1)_(1)_(1).js`.

Err, yes... :smile: You'd get `ReadBorder.js`, `ReadBorder_(1)_(1).js` and `ReadBorder_(1)_(1)_(1).js`...

But then, you could as well just add a `~` for `ReadBorder.js`, `ReadBorder~~.js` and `ReadBorder~~~.js`, and forget about the counter...

I only suggested to have the expected (trivial) filename for almost every script and a modified name for a few of them. Those don't need a proper counter.

You could also name the files 1, 2, 3, ..., but that's not very readable. I would want these files to be able to be extracted into a directory and accessed by the file system in a readable manner. That's why I suggested `counter_scriptname`, which is always unique!
