### ISSUE TITLE
Dark GTK theme makes menu items unreadable

### ISSUE THREAD

**Issue by majutsushi** [greasemonkey/greasemonkey#2940]
I'm on Linux and use a dark GTK theme. This causes the Greasemonkey menu items to be displayed as white text on a white background, making them unreadable, unless I hover over them. I suspect that the background colour of the menu is specified somewhere, but the text colour isn't.
![greasemonkey](https://user-images.githubusercontent.com/465527/38587988-b8bf203c-3d77-11e8-9085-789692c69af3.png)

**Comment by arantius** [comment]
Which version of Greasemonkey?

Can you try the latest nightly build?  https://arantius.com/misc/gm-nightly/

**Comment by majutsushi** [comment]
This was with version 4.3. The nightly version fixes the issue for me, thanks!
