### ISSUE TITLE
Script stopped in iframe

### ISSUE THREAD

**Issue by Ndattebayo** [greasemonkey/greasemonkey#2945]
I have some script who was working in older version before v4, but not until.

In iframe the script run but after few ms it stopped.

You can try it using :
window.addEventListener("message", function(mess){
You can send a message just after the page begin loading but if you try send a message to the Iframe after 1 second, that fail.

That the same thing if you try to get var with await getValue. The main script run but async scripts sometimes failed.

**Comment by Eselce** [comment]
Duplicate #2574

**Comment by Sxderp** [comment]
Would be resolved using content script / user script registration handlers.

**Comment by Eselce** [comment]
Still a duplicate...
