### ISSUE TITLE
Improve backup export format

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#2949]
The contents of the backup ZIP should have one directory per script; name mangled as necessary for guaranteed uniqueness.  Inside of each of those:

* The `.user.js` as originally named (infer from downloadUrl).
* Each of the requires as originally named (infer from URL), unless they are not unique, then minimally mangled.
* Each of the resources, named as the URL implies, minimally mangled if necessary.
* If there are `GM.setValue()`s available, those serialized into one JSON file.
* An extra JSON file for any settings that can't be computed from the above.  *Exclude* anything that can be computed, especially the evalContent.  (The result should be size efficient; see [comment](https://github.com/greasemonkey/greasemonkey/issues/2922#issuecomment-386007319) on #2922 .)

"Minimally mangled" means keep the name as close as possible, especially with the right extension, as their original source form.  Any name that would be unique without mangling should be kept as is, only things that must be mangled should be.

It might be worth manually constructing such a ZIP and seeing how well VM/TM import it; letting them at least install the script itself would be ideal.  Checking that the above design does not break this is good.

The import facility should be able to import this ZIP and have each script fully functional, even if there's no internet connection/URLs of resources or requires no longer resolve/etc.

**Comment by Sxderp** [comment]
Name mangling was discussed in another issue. The "only mangle when needed" is much harder to do in practice. There's a bunch of edge cases. It's much easier to "minimally mangle" everything by applying a uniquely identifying prefix. 

Why make name checking more complex then it needs to be? I find it incredibly unlikely that anyone is going to be upset that the name of their files have been prefixed with some number.

**Comment by arantius** [comment]
I agree that it's easier, but it's much worse.  It's worth the effort IMO.

>  I find it incredibly unlikely that anyone is going to be upset that the name of their files have been prefixed with some number.

I would be.  Not a lot, but I'd definitely be happier if it didn't happen.  Especially in the (common?) case where it doesn't add any value, because there was no collision to avoid.

**Comment by arantius** [comment]
> .. (without you) ..

An odd thing to call out.  You think I wasn't reading it?  You were all doing fine, I didn't need to interrupt.  (I merged it, after all.)

> ...the current solution...combined namespace + name...

Then we're talking about different things.  The made up folder name, to store all the files for each script: I don't care nearly as much what that is.  The current scheme is fine.

When it comes to storing each `@resource` and `@require` as their own file: A) I want to do this, and B) this means another level of (possible conflicts), and C) I care very much about making the names as close to the "original" as possible.  (And D) the conflicts seem less likely.)

---- 

Also: we don't store the `@resource` URL anywhere, just the name it's assigned.  So the URL isn't (easily) available for inferring a file name from.  Boo.  Maybe re-parse the meta for this unusual case?  And in a second way, which can output the name/URL pairs?  Hmm.

**Comment by Eselce** [comment]
> > .. (without you) ..
>
> An odd thing to call out. You think I wasn't reading it? You were all doing fine, I didn't need to interrupt. (I merged it, after all.)

I didn't mean to appear rude. Take it as a factual info - even better with your remarks: Just forget about my remark...

And obviously, I almost totally messed up that reply. I mixed the base file (and directory) names with the file names of dependencies. I don't know why, because I understood the first posting correctly. After some replies, I forgot, what it was about. I guess, I was distracted by real life! :smile:

**Comment by Sxderp** [comment]
> Also: we don't store the @resource URL anywhere, just the name it's assigned. So the URL isn't (easily) available for inferring a file name from. Boo. Maybe re-parse the meta for this unusual case? And in a second way, which can output the name/URL pairs? Hmm.

I think having duplicate `@resource` names is invalid. Make a folder and put the resources into it using the variable name as filename? Why parse the URL of a resource when it's 'known' as some arbitrary, pre-defined, name?

**Comment by arantius** [comment]
I'm referring to inferring the file name from the URL it was downloaded from.  If it isn't clear, I want the files in the ZIP to resemble the files originally downloaded as close as possible.  E.g. if you have a `foo.user.js` with a `// @require bar.js`, you should be able to just install the copy in the backup ZIP (if extracted), because all the names are already just right.

Also I later realized that the output of parsing the meta *does* already expose both the name=>content map as well as the name=>URL map, so this was pretty easy to do after all.  (With an extra "parse the content" step added.)

**Comment by Eselce** [comment]
Hmm, just from a user's viewpoint: If I'd install some scripts, maybe edit them later (main script & @require), then export them to a zip file, I would really expect to store the data, not just the filenames.

The filenames would only come into play, if there were a possibility to refresh the links mentioned in the main script. Until then, I would expect to save the edited versions of the data. How else could I save my edits?

Please just think about it, when you export all scripts, purge the database, and import the backup zip, wouldn't you expect to restore the whole lot in exact the same version as before?

**Comment by arantius** [comment]
Of course?  I'm just changing how that (possibly edited) data is laid out in the ZIP.

**Comment by Eselce** [comment]
> I'm just changing how that (possibly edited) data is laid out in the ZIP.

Canonically in the same way as the edit tabs (@require): `name` => `code`.

Am I missing sth?

**Comment by arantius** [comment]
https://github.com/greasemonkey/greasemonkey/compare/master...arantius:export-format-2949

This branch is in a good enough state to let people look at it now.  I ended up changing more than I planned at first.  Most importantly, it has tests.  Next most, the files/data are laid out in a way that a human can read (each require/resource is its own file).
