### ISSUE TITLE
Is there any issue with FF59 GM4.3 "New user Script" on Mac?

### ISSUE THREAD

**Issue by erosman** [greasemonkey/greasemonkey#2953]
Someone has told me that they have a problem with installing scripts and when they click on "New user Script" on Mac, nothing happens.
I don't use Mac to test it.
Is that true?

Update Reference: Martii/greasemonkey/issues/14

**Comment by arantius** [comment]
Seems like a corrupted profile

**Comment by erosman** [comment]
@arantius Did you check Martii/greasemonkey#14 before closing?

**Comment by Sxderp** [comment]
Could be a corrupt profile. But I assume @Martii is familiar with standard new profile testing. Whether this is something we can do anything about I'm not sure. Getting `undefined` in the error is _very_ enlightening. Was this ever working? If so some regression testing against Firefox or Greasemonkey (or some combination thereof) would be beneficial.

**Comment by erosman** [comment]
@Sxderp Can someone verify and if it is an issue, reopen this topic?

**Comment by Sxderp** [comment]
Unable to reproduce on OSX Yosemite (10.10.5) with Firefox 60.0.1.

**Comment by erosman** [comment]
@Sxderp Would you mind checking the new details posted by Martii Martii/greasemonkey#14 ?

_PS. The user who reported the issue isnt advanced enough to check them._

**Comment by Sxderp** [comment]
The white page is definitely a known issue and is not something we can control completely. There are some mitigations in place but the rendering is squarely on Mozilla's internal event handling not dealing with first paint properly. There's some issues open on it.

In the past there's been rare circumstances were indexedDB code / structure has changed and Firefox fails to migrate existing databases to the new internal format thus causing corrupt storage within the profile. This normally only occurs if you downgrade Firefox and use a profile that had previously been used in a newer version.

--

Rereading the title of the issue, it says Firefox 59 and Greasemonkey 4.3. @erosman has the user attempted updating both to the latest? GM 4.4 was released a few days ago.
