### ISSUE TITLE
Firefox for Android could not support certain script

### ISSUE THREAD

**Issue by ivysrono** [greasemonkey/greasemonkey#2959]
[userscript/MyNovelReader.user.js at master · ywzhaiqi/userscript](https://github.com/ywzhaiqi/userscript/blob/master/scripts/MyNovelReader.user.js)

Not work: 
Android 8.1 ( RR 6.0 ) + Firefox 60 + Greasymonkey 4.4

Working:
Win 10 + Firefox 60 + GM 4.4
Win 10 + Firefox 60 + Violentmonkey 2.9.4
Android 8.1 + Firefox 60 + Violentmonkey 2.9.4

**Comment by ivysrono** [comment]
Thanks, I have updated.

**Comment by Eselce** [comment]
@ivysrono Would be better not to update, but to post new information about the issue.
Furthermore: You've specified the platforms, etc. So far so good. But the main problem with your request is the term "does not work". Please specify more closely: In what situation or for what code segment, what do you expect and what is really happening, that is unexpected/wrong. Idealy, you'd have a little example code, that has its focus close to the problematic code. Such as

```javascript
// ==UserScript==
// @name         testscript
// @description  Test script for Greasemonkey 4.4.0
// @grant        none
// ==/UserScript==
let expected = ...;
let expression = ...;
console.error("Expected:", expected, "Received:", expression);
```
