### ISSUE TITLE
Clarify why the new Download permission is needed

### ISSUE THREAD

**Issue by Powersource** [greasemonkey/greasemonkey#2961]
So firefox just told me that I need to accept the new permission that greasemonkey requires to update it:  
"Download files and read and modify the browser's download history"

I didn't see it mentioned in the [blogpost](https://www.greasespot.net/2018/05/greasemonkey-44-release.html) so I thought I'd ask.

**Comment by Sxderp** [comment]
For exporting the database. It's much simpler to utilize the Downloads API to initiate the save request. It's possible to do without but the code is not quite as clean. Honestly there should be a 'save this file' API (that prompts the user) that doesn't require Downloads permissions, but unfortunately there isn't.

**Comment by arantius** [comment]
That.

**Comment by eight04** [comment]
In Firefox >= 60, `downloads` could be put in `optional_permissions`:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/optional_permissions

**Comment by arantius** [comment]
I want to do other Fx-60-minimum changes in the next release anyway, so that sounds great.
