### ISSUE TITLE
Convert Download permission to optional

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2962]
ref: https://github.com/greasemonkey/greasemonkey/issues/2961#issuecomment-391563678
ref: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/optional_permissions

Not everyone will be using the export feature. Only request the permission if a user attempts to export the database.

**Comment by arantius** [comment]
First I tried the most obvious thing, request the permission immediately before starting the "download", but that was in the background and:

    Error: permissions.request may only be called from a user input handler

So, I moved it to the monkey menu event handler.  Nothing ever happens, I get no dialog and the promise is never resolved/callback is never called (browser vs. chrome API).  Does this API not work from a browser action?

Actually, I tried the sample https://github.com/mdn/webextensions-examples/tree/master/permissions -- it seems to fail in the same way?  Clicking "granted" for history does nothing at all.

**Comment by arantius** [comment]
Broken somewhere between stable and nightly.  Sigh.

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1464436

**Comment by Sxderp** [comment]
It still may not work in the browser action due to window focus and the browser action autoclosing when focus is lost. No testing though.

**Comment by arantius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1432083

**Comment by voidstarstar** [comment]
@arantius It sounds like that bug may have been fixed and deployed in the latest version of Firefox.
