### ISSUE TITLE
Incorrect script version/description in script submenu

### ISSUE THREAD

**Issue by Klaster1** [greasemonkey/greasemonkey#2963]
**What happens:**
Previous script version/description is shown for current opened script submenu.

**How to reproduce:**
1. Install several scripts with description in meta.
2. Navigate to script 1. Remember what description says.
![image](https://user-images.githubusercontent.com/2667662/40571899-60fa61be-60cb-11e8-8b0e-d5414580130c.png)
3. Navigate back using the arrow left to the script title.
4. Open another script submenu, see this:
![image](https://user-images.githubusercontent.com/2667662/40571922-8d0920d8-60cb-11e8-844e-7943e7d7b2ce.png)

The second script description should look like this:
![image](https://user-images.githubusercontent.com/2667662/40571939-9da52f22-60cb-11e8-8618-7c581c9c585e.png)

All of the scripts above were installed at least a week ago.

GM version: 4.4.0
FF version: 60.0.1

**Comment by Sxderp** [comment]
The problem is the use of `rv-if`.

https://github.com/greasemonkey/greasemonkey/blob/18e21a4d5d9372e035629eed88e3954f4346322b/src/browser/monkey-menu.html#L128-L136

Changing to `rv-show` resolves the problem.
