### ISSUE TITLE
Takes too long to insert userscript into pages

### ISSUE THREAD

**Issue by Keith94** [greasemonkey/greasemonkey#2965]
I ran into this bug using GM + [Iridium](https://github.com/ParticleCore/Iridium/wiki/Download#userscript), a userscript for YouTube, where the script doesn't load fast enough.

Here is some info if that helps: https://github.com/ParticleCore/Iridium/issues/468

**Comment by arantius** [comment]
Can you be more specific?  I can't understand how "takes too long" can explain 
"doesn't load in certain tabs "

**Comment by Keith94** [comment]
Sorry, but I don't know much more than that.

The bug that I described is apparently caused by GM, since the add-on version of Iridium doesn't have that issue.

@ParticleCore Were you able to debug this and don't mind providing more info?

**Comment by ParticleCore** [comment]
@arantius What Keith means is that Greasemonkey is noticeably taking too long to inject userscripts that require to be injected during/run at `document-start` when comparing to the WebExtension version and comparing to the same Userscript running on TamperMonkey.

**Comment by arantius** [comment]
> require to be injected during/run at document-start 

4.x does not support this.  #2526

**Comment by ParticleCore** [comment]
@arantius Don't know if it might help with that, but I hope it does:

>Use this API to register content scripts. Registering a content script instructs the browser to insert the given content scripts into pages that match the given URL patterns.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts#Browser_compatibility
