### ISSUE TITLE
IndexedDB permission

### ISSUE THREAD

**Issue by lilithfr** [greasemonkey/greasemonkey#2967]
Hello,

I have issue with greasemonkey 4.4.0, I cannot create new script.
It seems an issue with the IndexedDB but I don't find any way to solve it.
Here the messages in the console:

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.principal]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///C:/Program%20Files/Mozilla%20Firefox/browser/omni.ja!/components/nsBrowserGlue.js :: prompt :: line 2998"  data: no]  (unknown)
	prompt jar:file:///C:/Program%20Files/Mozilla%20Firefox/browser/omni.ja!/components/nsBrowserGlue.js:2998:1
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.cancel]  nsBrowserGlue.js:3022
IndexedDB UnknownErr: ActorsParent.cpp:600  (unknown)
Error opening user-scripts DB! <unavailable>  user-script-registry.js:57:7
	openDb/</dbOpen.onerror moz-extension://50cc45d1-2d5a-4f4c-99a5-960fe36db82f/src/bg/user-script-registry.js:57:7
<unavailable>  downloader.js:111:11
	install/</< moz-extension://50cc45d1-2d5a-4f4c-99a5-960fe36db82f/src/downloader.js:111:11
Error: undefined  downloader.js:105:7

Alex.

**Comment by arantius** [comment]
This isn't a support forum.  Your best bet is probably to uninstall, restart Firefox, then reinstall Greasemonkey.
