### ISSUE TITLE
wiki not responding

### ISSUE THREAD

**Issue by mlemaudit** [greasemonkey/greasemonkey#2969]
Hello,

I don't know if it is the right place, but I can't reach the wiki pages (wiki.greasespot.net), neither in http or https.

Regards,
M

**Comment by arantius** [comment]
You already reported this, no need to do it twice.  And I already know.

**Comment by FranklinYu** [comment]
Is this issue fixed? I’m still seeing the issue for Wiki site, for both HTTP and HTTPS. Is it shut down?

**Comment by arantius** [comment]
You're not "still" seeing it, as if this has been happening constantly since July.  It happened again, in the past couple hours.  It's on a cheap server that occasionally goes down.

There's always https://web.archive.org/web/20190211225539/https://wiki.greasespot.net/Main_Page

**Comment by FranklinYu** [comment]
Is it because of the traffic, or the web host simply need regular maintenance?

**Comment by FranklinYu** [comment]
I saw that it is back up again. Is it because of the traffic, or the web host simply need regular maintenance?
