### ISSUE TITLE
Stop storing blobs as array buffers

### ISSUE THREAD

**Issue by Sxderp** [greasemonkey/greasemonkey#2972]
[Messaging blob from background (via IndexedDB) to content corrupts the blob](https://bugzilla.mozilla.org/show_bug.cgi?id=1461426)

Looks like it was fixed.

**Comment by arantius** [comment]
And?

**Comment by Sxderp** [comment]
What do you mean "And?" Storing the blobs as array buffers was a stop-gab measure to work around bugs in Firefox. It seems that the bugs are fixed. This should be tested and confirmed. If it works then the conversion to array buffers is now redundant.

**Comment by arantius** [comment]
... Pending several months for the above mentioned fix to make its way to stable?

**Comment by Eselce** [comment]
Expected event horizon should be FF 62, I guess.
