### ISSUE TITLE
Useless!  Unable to install https://openuserjs.org says forbidden

### ISSUE THREAD

**Issue by molitar** [greasemonkey/greasemonkey#2974]
Greasemonkey has become useless if I am unable to install user scripts.. What is this crap forbidden and not allow option to install anyway?

**Comment by iPherian** [comment]
I just tried openuserjs and got a 404 error on a random script. Is that what you mean? It's a server problem anyway.

**Comment by molitar** [comment]
No I actually got denied. 

https://openuserjs.org/scripts/lomacks/Reddit_Mouseover_Popup_Image_Viewer

It is a really old one but still worked in my older browser so was going to test but when I tried to install got error forbidden.

**Comment by iPherian** [comment]
I tried it, the server responds with 403 forbidden. It's not greasemonkey. You could try telling the script author to fix his url.

Or get the source code from openuserjs and paste it into GM. Click gm icon -> add user script. It won't auto-update, so get the true script when the guy fixes it.
