### ISSUE TITLE
Something has corrupted my profile

### ISSUE THREAD

**Issue by omgitsraven** [greasemonkey/greasemonkey#2976]
According to this thread: https://github.com/greasemonkey/greasemonkey/issues/2825#issuecomment-400849913 something is wrong with my GreaseMonkey profile? I've already uninstalled the extension, restarted Firefox, and reinstalled it; that didn't fix the issue. Is there somewhere I can browse (or even just wipe) the data that GreaseMonkey has saved in my profile?

**Comment by omgitsraven** [comment]
Deleting all greasemonkey-related entries from `about:config` did not help.

**Comment by Sxderp** [comment]
Look for a folder called storage/default in your profile and (make a backup first) delete it. Or more specifically delete the moz-extensiom folders in it. 

Doing this WILL cause data loss for other sites and potentially other extensions. 

If you want to be slow you can try deleting them one by one. 

Further I've had success resolving the issue myself by deleting one or some of the sqlite files in the base of the profile. I don't remember which, I think it was storage.sqlite. 

MAKE FULL BACKUPS OF YOUR PROFILE WHEN FIREFOX IS NOT RUNNING. PREFERABLY TWO. YOU HAVE BEEN WARNED.

**Comment by omgitsraven** [comment]
Deleting storage.sqlite fixed it for me, thank you so much! I haven't noticed any other side-effects of deleting it yet, but I've kept a backup just in case.
