### ISSUE TITLE
Experimental Scratchpad API

### ISSUE THREAD

**Issue by KOLANICH** [greasemonkey/greasemonkey#2978]
https://github.com/KOLANICH/webext-experiment-scratchpad
I guess the editor they have is of much better quality than the one made here. So maybe we should use it instead of what we have.

**Comment by arantius** [comment]
Single editor?  Have to close it to (resolve the promise, and thus) save?

**Comment by KOLANICH** [comment]
Yes. You call the API and get the promise. When user closes the editor, the promise is resolved. Save and open act on files, not on contents, so user can open a fike he wishes or save the content into a file. I'm not happy with the params like `prettyPrint`, I prefer them to be methods called on the object returned by API, but since WebExtensions Experiments framework is promise-driven with the same restrictions on message passing, doing this will require complication.  So I have implemented the simplest API. It is completely possible to add events and more api here, but not right now, I guess some refactoring of experiments framework is needed because it is pain to work with it - it's very poorly documented, violates single definition rule, gives many room for mismatches and if something mismatches, one has to debug browser to reverse engineer what goes wrong.
