### ISSUE TITLE
Select All in script takes few seconds

### ISSUE THREAD

**Issue by erosman** [greasemonkey/greasemonkey#2983]
With the last 2 upgrades, I have noticed that Select All (cmd+a) takes few (4-5) seconds for a script with 3800  lines of normal (not minified) code.

I often have to select all, delete and paste a new script.

Is there a reason for this?
Are there listeners that are causing this behaviour?

**Comment by Cerberus-tm** [comment]
I can confirm this. At least on a fairly old laptop, select all takes some time.

**Comment by erosman** [comment]
I am on a good-spec modern laptop and the issue was not present before.

**Comment by Sxderp** [comment]
This issue has been sitting here, but it might be an upstream issue with CodeMirror. Did the third-party library get updated between when you were not seeing the problem and now?

**Comment by arantius** [comment]
We're using 5.36.0 ( https://github.com/greasemonkey/greasemonkey/blob/master/third-party/codemirror/README.md ), latest is 5.40.0 ( https://codemirror.net/doc/releases.html ).  I don't see any performance related items in the release notes.

Also of interest: https://codemirror.net/6/

> We are rewriting CodeMirror ...

**Comment by erosman** [comment]
Personally, I write/edit script elsewhere and then copy paste into GM by using select-all delete & paste.

Today I had to do that for a large (ish.. only 3900 lines of normal code) script and every time I had to wait 5+ seconds for the select-all which is quite frustrating.


Off-Topic: @arantius There is no need to upload sources with GM unless you are self-minifying the code. In case of libraries, a link to the actual official source is enough. Due to uploading sources, GM is now in the Admin queue.

**Comment by badbrainz** [comment]
I think _shoelace.css_ might be hurting performance somehow. To test, add this rule to _edit-user-script.css_:
```css
/* this override shoelace's textarea rule (see Forms section) */
.CodeMirror textarea {
  white-space: pre;
}
```

**Comment by arantius** [comment]
I guess I mostly never use "large" scripts, I've never seen this.  Until today.  I tried out [Picviewer CE+](https://greasyfork.org/en/scripts/24204-picviewer-ce) and indeed see the select all action take multiple seconds.  (It's a 9.8k line and 478kbyte (!!) script, all in one file.)

**Comment by Cerberus-tm** [comment]
Ouch, that is a long script! Out of curiosity, were you using a fairly new/fast computer?

@badbrainz Hey, that sounds interesting! Where is this shoelace.css file, and where is the edit-user-script.css file? Is it somewhere inside the extension, or can this be fixed using a userstyle?

**Comment by arantius** [comment]
Um, 12 core 3.5ghz Xeon.  So, yes.

And: [shoelace.css](https://github.com/greasemonkey/greasemonkey/blob/master/third-party/shoelace/shoelace.css).

**Comment by Cerberus-tm** [comment]
I suppose that counts! The longest script I've written myself is more like 2000 lines (I'm no programmer).

So when I switch to the new Firefox, I'll create a userstyle containing Badbrainz's css and hopefully be unaffected.
