### ISSUE TITLE
privacy.firstparty.isolate=true breaks GM.xmlHttpRequest

### ISSUE THREAD

**Issue by adamhotep** [greasemonkey/greasemonkey#2985]
I get **cookies is undefined** and **Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set** when running a GM userscript calling `GM.xmlHttpRequest()` with `privacy.firstparty.isolate` ([First-Party Isolation](https://www.bleepingcomputer.com/news/software/another-tor-browser-feature-makes-it-into-firefox-first-party-isolation/)) enabled (set to `true`):

![gm xmlhttprequest privacy firstparty isolate](https://user-images.githubusercontent.com/6454774/42841421-8c039ce8-89f9-11e8-8558-53a856d4bb7e.png)

For now, this means I'm disabling First-Party Isolation, but I'm hoping there's a solution or workaround that will make this work better.

In the event it matters (it shouldn't, I'm on FF 61), I have followed the [ghacks workaround](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1.1-Setting-Extension-Permission-Exceptions) to explicitly allow GM to set cookies.

**Comment by eternal-sorrow** [comment]
Any updates on this?

**Comment by eternal-sorrow** [comment]
Welp, I use neither First-Party Isolation nor Greasemonkey anymore, but hey, better late than never...
