### ISSUE TITLE
is there has any sync version for getValue?

### ISSUE THREAD

**Issue by bluelovers** [greasemonkey/greasemonkey#2987]
is there has any sync version for getValue?

**Comment by Cerberus-tm** [comment]
I'd really love to have this as well. I forgot why this isn't possible any more (was it because Firefox made it impossible for web extensions?). With a synch version of getValue and setValue, we wouldn't need to refactor old scripts that are 2000 lines and written by someone else (which I have found myself unable to do).

**Comment by arantius** [comment]
No.

**Comment by Cerberus-tm** [comment]
@Sxderp OK, thanks, I understand. At least we can use Tampermonkey/Violentmonkey for those scripts that really need it. For some reason, they can still use sync getValue, right?

**Comment by Eselce** [comment]
I wonder, in which cases you can't cope with a `getValue` situation without a sync implementation. Okay, it may be less comfortable to code (or rewrite the code), but it should be possible in an async way...

**Comment by Cerberus-tm** [comment]
@Eselce I could be wrong, but I can't think of a way to solve the following use case. I have this userscript which adds events to result links in Google when you click on them. When you click on a search result, it saves the keywords that were used in the Google search, using `setValue`. Then, when the page behind the result is opened (as a result of the click), it uses `getValu`e to get those keywords, and it highlights them on the page. I can't replace the click events that are already attacked to those Google links, so I can't put the opening of the new page inside an async `setValue` function. (The `getValue` function I could make async.) As a result, I'm getting a race condition: will the `setValue` finish before the browser navigates away from the page? I haven't actually tried to move to async, but I'm sure this race condition would be bad coding, right? And I can't think of any way to get around it. But I'm no programmer, so I hope I'm missing something.
