### ISSUE TITLE
I can't uninstall user script??

### ISSUE THREAD

**Issue by chromeisstupid** [greasemonkey/greasemonkey#2990]
Or, should I say, I uninstalled it, but the changes it made are still active. I even made a new profile (I use Firefox), but the changes are still here... Do I need to restart PC to make it work?
It was this one: https://cable.ayra.ch/tampermonkey/view.php?script=youtube_old_design.user.js

**Comment by Sxderp** [comment]
Looks like the script sets a cookie. Clearing cookies / cache should resolve it. As for creating a new profile, that should have resolved the issue too (assuming you activated said profile).

I think there may have been some user mixup. But for the short term try getting Firefox to clear cookies for YouTube. This should be doable in the preferences menu / page.

**Comment by arantius** [comment]
It's pretty bad netiquette to repeat yourself. You sent this support request to the list AND the issue tracker.
