### ISSUE TITLE
Edited script updated without prompting

### ISSUE THREAD

**Issue by RGBoorman** [greasemonkey/greasemonkey#2993]
Hi,

I had a heavily modified script that was just overwritten by an update - the first I've ever seen on this script after installing it years ago. Is there any way to roll back to my version?
I would also like to suggest that their should be a warning before an update is applied to any modified script to prevent this sort of thing happening in the future,

Regards.

**Comment by arantius** [comment]
No there's no way to roll back.

There was a warning though I admit it wasn't super visible: https://www.greasespot.net/2018/08/greasemonkey-47-release.html
