### ISSUE TITLE
"New user script" doesn't open a new tab

### ISSUE THREAD

**Issue by seishun** [greasemonkey/greasemonkey#2994]
Using Greasemonkey 4.7, Firefox 61.0.2. When clicking "New user script", nothing appears to happen, but "Unnamed Script XXXX" is added to the "User script for this tab" list.

The following errors show up in the browser console:

```
[Show/hide message details.] [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.principal]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/browser/omni.ja!/components/nsBrowserGlue.js :: prompt :: line 2850"  data: no]
prompt
jar:file:///C:/Program Files (x86)/Mozilla Firefox/browser/omni.ja!/components/nsBrowserGlue.js:2850:1
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.cancel] nsBrowserGlue.js:2874
[Show/hide message details.] [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.principal]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/browser/omni.ja!/components/nsBrowserGlue.js :: prompt :: line 2850"  data: no]
prompt
jar:file:///C:/Program Files (x86)/Mozilla Firefox/browser/omni.ja!/components/nsBrowserGlue.js:2850:1
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.cancel]
```

Same happens on a fresh profile.

**Comment by Eselce** [comment]
Experienced that as well (`GM v4.7`), but I can't say, when it started...

**Comment by arantius** [comment]
Confirmed in 2018.08.28 nightly; Firefox is `Built from https://hg.mozilla.org/releases/mozilla-release/rev/975058795980dfbba1daedfe5fc82d1abcb5638b`, 61.0.2.  Most relevant error seems to be:

    TypeError: content is null ext-browser-content.js:234:9 

That's not our code, though, so .. it's something we're passing?  The error has no traceback attached.

**Comment by arantius** [comment]
This works in 4.6, fails at head.  Git bisect tells me:

    5cb38357954bc0bd797d5e70b186ede581b7196a is the first bad commit
    commit 5cb38357954bc0bd797d5e70b186ede581b7196a
    Author: Anthony Lieuallen <arantius@gmail.com>
    Date:   Fri Jul 20 15:34:31 2018 -0400
    
        Track install and edit time.
        
        Don't (auto) update a script that's been edited since install time.
        
        Refs #2531
    
    :040000 040000 5ed933a6eb8717e5ef810b7e46c1bf7ec44bc25a 9f13ac5508a51d3b0c0b2aff45e02a5e3ec1d50b M      src
    :040000 040000 260f6f0e18145a4fbfdad57439d3cb40b5baabb5 109c86127e79cb4f8d5ae9ad383784c00c996c9f M      test

5cb38357954bc0bd797d5e70b186ede581b7196a is the bad commit that introduced this.  A first look through confuses me about how/why.

**Comment by Sxderp** [comment]
Your problem is here: https://github.com/greasemonkey/greasemonkey/commit/5cb38357954bc0bd797d5e70b186ede581b7196a#diff-6ba827f37e1348164a6c4d6c5d015654R299
Curly braces were added. Therefore the anonymous function is now a 'block' rather than a line. Blocks don't return anything (unlike a line which will return whatever the expression evaluates to). 'undefined' is immediately resolved and `window.close` is executed.

**Comment by arantius** [comment]
Thanks @Sxderp !  That was it.
