### ISSUE TITLE
Tabs opened by GM.openInTab can not be closed?

### ISSUE THREAD

**Issue by ivysrono** [greasemonkey/greasemonkey#2995]
https://github.com/greasemonkey/greasemonkey/issues/1685?#issuecomment-13054476

GM_openInTab returns window object so you can use close() method to close the tab.

https://wiki.greasespot.net/GM.openInTab#Returns :
GM.openInTab returns undefined

**Comment by arantius** [comment]
Can't pass a handle from the extension background to the content script, AFAIK.
