### ISSUE TITLE
New user script does not open editor

### ISSUE THREAD

**Issue by krusch** [greasemonkey/greasemonkey#2997]
New user script does not trigger any action. Reinstalling Greasemonkey did not make a difference either.

Firefox 60.2.1esr (32-bit) on Windows 7 64bit

**Comment by arantius** [comment]
Sounds like #2994.

**Comment by krusch** [comment]
@arantius Not exactly, unlike in #2994 no new script is created and there are no warnings on the console either.  It appears as if nothing at all happens clicking the link in the menu.

**Comment by arantius** [comment]
How does the latest [nightly build](https://arantius.com/misc/gm-nightly/) act?
