### ISSUE TITLE
New Script Does Not Get URL

### ISSUE THREAD

**Issue by GuardianMajor** [greasemonkey/greasemonkey#2998]
I have noticed that unlike the past and other script managers currently, when you are page X and you click on new script, you will not get:

1. The script editor opening up
2. The URL of the current page (for include/match lines)
3. We don't have a way to create a header template (have to type everything up each time)
4. To edit the script, can we get a "right click" hook that will open it for editing (better usability)

\<suggestions removed\>

**Comment by arantius** [comment]
You've made a laundry list issue.   There's seven different things above.  It's unnecessarily difficult to track all the separate items, so such issues tend to get ignored.

If you file individual issues for individual changes, they're easier to understand and to track, so they're more likely to be acted upon.

**Comment by Sxderp** [comment]
For point number four there was a pull request filed but I believe it was rejected.

**Comment by Eselce** [comment]
> For point number four there was a pull request filed but I believe it was rejected.

#2899 is marked as "Pony", and I still don't get what that means. Sorry, "Pony" is german for sth. else... :grin: 

I'd find that especially useful. And I'm also used to it (from Tampermonkey)...

**Comment by Eselce** [comment]
That was one out of several interpretations, that I had.

If it's this one, I don't agree!

**Comment by Cerberus-tm** [comment]
@derjanb I, too, have often wondered what this "Pony" could mean. Since you seem to understand its meaning, could you explain it in one explicit sentence? That would be much appreciated!

**Comment by GuardianMajor** [comment]
@arantius You are right and I am profoundly sorry about that, that's why I put them at the end as a TL/DR/RL and the actuall issue was presented first. I usually avoid that, but felt it was better than littering the issues list for each one.

The main concern is the lack of opening the new script for editing and also not grabbing and inserting the url of the page that initiated the new script.

@sxderp Interesting, I wonder why, it is a behavior that has long been in play all over place and even in GM in the past, so I felt it was a no brainer but be interested in knowing why it was rejected. Maybe I can realize a downside.

@eselce, @cerberus-tm Don't quote me on it, but I believe from years of development experience it refers to a very low priority, will take a long time (as in Pony Express being the slowest form of delivery) and it may or maynot eventually come.

**Comment by Eselce** [comment]
@GuardianMajor (no quote, just a reference) Another sensible explanation. Similar to `Features`? I'll just sit and wait, as it's probably not really rejected (`Closed`). Just wanted to point out, that it could be useful and comfortable...

**Comment by GuardianMajor** [comment]
@arantius I know that you expressed upset with the issue because it also included suggestions below it, and I apologized for that and explained why I did it. But that doesn't change the single overarching element of the issue which is at the top and if you can put aside whatever feelings, I believe it legitimately deserves an answer and your input. Thank you.

**Comment by Sxderp** [comment]
@GuardianMajor I would close this issue and reopen a new one with the content you wish addressed. This thread has been completely derailed.

**Comment by GuardianMajor** [comment]
@Sxderp I appreciate and respect your recommendation; however, the issue has not been off topic and the issue is stated correctly, I could remove the suggestions portion in an edit if it is so offensive, which I don't personally get why, but to open a new one seems like a wasteful and unnecessary. Unless the only reason is pride and making a point, which I feel would be unprofessional and I have too much respect for @arantius to assume he would stoop that low.

**Comment by Cerberus-tm** [comment]
@GuardianMajor Ah, thank you for the explanation.

I think most of your suggestions would be desirable features! But they would indeed be more appropriate in separate issues.

**Comment by GuardianMajor** [comment]
@Cerberus-tm Fair enough, as you see I have already redacted the bottom of the issue so they are not there anymore.

**Comment by GuardianMajor** [comment]
Oh that is just me showing interoperability of the components which revolve around the same core. Think of it as steps showing the flow.

**Comment by arantius** [comment]
Posting one issue per topic makes it easy to discuss that issue, decide what to do, track (and close) when it's done.

Posting several issues per topic makes it much harder to do each of those things.  If you want strangers on the internet to give away their free time just to make your life easier, you should do it in the way that makes it easier for them.

P.S. Closing as this issue has indeed significantly derailed.
