### ISSUE TITLE
Provide Right-Click to Edit/Open Script/Editor

### ISSUE THREAD

**Issue by GuardianMajor** [greasemonkey/greasemonkey#3004]
With issue #2998 being summarily closed, here is the issue revised: 

Unlike the past and other script managers currently, when you have a script already, can we get a "right click" hook that will open it for editing (better usability than the layered menus).

**Comment by Cerberus-tm** [comment]
I would love to see this. This is an action I carry out very frequently, and it would save considerable time and energy when added up. And it doesn't get in the way for those who don't use it.

**Comment by Eselce** [comment]
Fixed #2899

**Comment by Eselce** [comment]
@GuardianMajor It's been some time since, but where did you find a clear rejection other than "not really interested in"?

**Comment by GuardianMajor** [comment]
I took this as a clear rejection:

> I'm not likely to merge this. I never liked this feature, it's non-discoverable. It's impossible on some platforms. It's a very small enhancement against GM4 (left click, left click "edit" is the current method, and that's not much more work than "right click").
https://github.com/greasemonkey/greasemonkey/pull/2899#issuecomment-415049688

**Comment by Eselce** [comment]
That was the one, that I was referring to as well. I get, he doesn't like it, but maybe there's the possibility to make life easier for a bunch of users who find it very useful...

**Comment by GuardianMajor** [comment]
@Eselce Exactly, that's my point exactly and feel doesn't hurt to be there, even if you don't think it mass appeal.
