### ISSUE TITLE
Unexplained Failure to Run the Script

### ISSUE THREAD

**Issue by GuardianMajor** [greasemonkey/greasemonkey#3007]
Take this basic script:
```
// ==UserScript==
// @name         Testing
// @description  Error Test Case
// @version      1.2.3
// @namespace    Test.Case
// @author       Anyone
// @include      *whatever*
// @require      https://code.jquery.com/jquery-3.3.1.min.js
// ==/UserScript==

(function(){
  var a = "something";
  var b = "else";

  this.$ = this.jQuery = jQuery.noConflict(true);

  console.log("I started");

  run1();

  $(window).on('load', function(){
    $(document).ready(function(){
      run2();
      run3();

      function run2(){
        console.log("I am function 2 inside $(document)\nb="+b);
      };
      function run3(){
        console.log("I am function 3 inside $(document)\nScript should stop when I am done");
      };
    });
  });

  function run1(){
    console.log("I am function 1 outside $(window)\na="+a);
  };
})();
```

This script fails to run and shows this error in the console:

> Could not execute user script [Greasemonkey script Test.Case/Testing; version 1.2.3] 
>  <unavailable> execute.js:29:7
> 	executeUserscriptOnNavigation/< moz-extension://fc9bafbf-c177-4465-9ec4-49311b13e396/src/bg/execute.js:29:7

Clicking the error link to see where and what, produces this:

> Security Error: Content at moz-nullprincipal:{6facd6c6-5c1c-4b07-b4b9-596dd9b9bec6} may not load data from moz-extension://fc9bafbf-c177-4465-9ec4-49311b13e396/src/bg/execute.js. 

So manually cut and past and you get this:

```
'use strict';
/*
This file is responsible for observing content navigation events and triggering
content script executions.

TODO: Make document_start execution time work as intended.
*/

function executeUserscriptOnNavigation(detail) {
  if (false === getGlobalEnabled()) return;

  const userScriptIterator = UserScriptRegistry.scriptsToRunAt(detail.url);
  for (let userScript of userScriptIterator) {
    let options = {
      'code': userScript.evalContent,
      'matchAboutBlank': true,
      'runAt': 'document_' + userScript.runAt,
    };
    if (detail.frameId) options.frameId = detail.frameId;
    chrome.tabs.executeScript(detail.tabId, options, () => {
      let err = chrome.runtime.lastError;
      if (!err) return;

      // TODO: i18n?
      if (err.message.startsWith('Message manager disconnected')) return;
      if (err.message.startsWith('No matching message handler')) return;

      // TODO: Better indication of the root cause.
-->      console.error(
          'Could not execute user script', userScript.toString(), '\n', err);
    });
  }
}
```

As you can see, it doesn't tell you anything useful or even a hint of what is wrong, so have to suppose it is something to do with the extension and not the code, although if you think there is something in the code that is causing this, would appreciate a heads up.

Sorry, forgot to add: GM 4.7 / FX 62.0.3 (64-bit)

**Comment by arantius** [comment]
Looks like you call function1 twice, but never define it.  (Missing keyword?)

**Comment by GuardianMajor** [comment]
I don't call function1 twice, it is called once before the $(window) and is defined at the very bottom of the script. No? But I do see one issue that I overlooked, let me look at it again and see if it still happens. Thanks.

**Comment by makyen** [comment]
@GuardianMajor You *are* trying to call all of `function1`, `function2`, and `function3` twice, without defining any of them. Where you appear to be *intending* to define each of those is missing the `function` keyword to indicate that you are defining a function. Thus, instead of defining a function at those points, you are attempting to execute a function which doesn't exist. If that didn't cause a fatal error, then the block of code after it (what you appear to intend to be the function) would then be executed.

In addition, having your code in a `$(window).on('load',` callback isn't a good idea without checking for the current state of the `window` wrt. loading, as that event *may* have already fired (under some conditions).

**Comment by GuardianMajor** [comment]
@makyen You are correct and I already acknowledged that and updated the code above. As for the callback, can you please tell me what you mean by check the current state, given that 'load' is the state and means it is done, hence why document gets called, right? What would you recommend please?

**Comment by arantius** [comment]
> ...and updated the code above...

Don't do that.  Now there's a bunch of comments that make no sense, because what they're referring to is gone.

Either way, this does not seem to be an issue with Greasemonkey.

**Comment by GuardianMajor** [comment]
I apologize, my sincere intention was to provide a correct test case, I am very sorry it wasn't meant to mess things up. The "previous edit" versions are always visible so anyone can see what was change, again I am sorry that wasn't my intention.

**Comment by arantius** [comment]
Somehow I've always missed where the previous versions were available, even though I looked for them.  Now I see it, and that makes things better.

**Comment by arantius** [comment]
Are you still saying the most recent version fails?

**Comment by makyen** [comment]
@arantius Being able to see prior versions of comments is a new GitHub feature. IIRC, it's only been available for a few months. Looks like it was implemented in late May. Prior to that, there was no access, at all, to prior versions of comments.

**Comment by GuardianMajor** [comment]
Yes, I am still having this problem where it completes, the page reloads and keeps going. The only thing I didn't include in the test case which I am hoping is not critical is that there is a `localStorage.getItem('a')` and `localStorage.setItem('b')` occurring, but I don't think that would cause this behavior would it?
