### ISSUE TITLE
[BUG] Facebook: Edit Search

### ISSUE THREAD

**Issue by goodboi69** [greasemonkey/greasemonkey#3009]
When typing in the search bar on Facebook a drop-down of recent searches appears. And on the top right of that drop-down there is an 'Edit' button. By clicking this button you can edit and see your search history. If Greasemonkey is Enabled, you are unable to click the 'Edit' button on Facebook. By disabling Greasemonkey, you can then click said button. Please look into this.

Edit: I should also mention that I do not have any scripts for Facebook.

**Comment by Cerberus-tm** [comment]
Can you provide more info? OS, browser version number, GM version number.

Have you tested this in a new, empty browser profile with no other extensions but GM, and without any scripts installed?
