### ISSUE TITLE
Script not running in mozilla, but functional in chrome

### ISSUE THREAD

**Issue by NuclearVampire** [greasemonkey/greasemonkey#3010]
Attempting to run a script on firefox that is functional on chrome and *used* to be functional on firefox, but after a firefox update, stopped working.  Tested in a new profile, no other addons running, and received this error when attempting to run script located here, https://github.com/Seedmanc/Booru-Augmentation-Project 

Type error for parameter details (Error processing runAt: Invalid enumeration value "document_body") for tabs.executeScript. execute.js:20
1539774361142	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 122"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:122
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:132
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:314
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:243
1539774361156	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 122"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:122
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:132
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:314
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:243
1539774361164	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 122"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:122
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:132
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:314
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:243
1539774361200	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 122"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:122
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:132
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:314
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:243
1539774361207	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 122"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:122
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:132
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:314
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:243
1539774361217	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 122"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:122
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:132
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:314
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:243
1539774361244	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 122"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:122
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:132
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:314
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:243

Error occurs on any booru type page, specifically on image pages, since the desired function was the ability to quickly add and remove tags, but. It doesn't run, even as it functions in chrome. 

Running win 7, firefox 62.0.3, greasemonkey 4.3.

(I hope this is asked in the correct spot, if not, I do apologize.)

**Comment by Sxderp** [comment]
I think this is caused by the `run- at` property in the script metadata 'document-body' is an invalid option. 

As I recall, I don't think GM validates that the property is one of the three supported values (-idle, -start, -end). 

GM should either complain on install (prevent install or somesuch) or install but default the `run-at` property and spit out a warning when the script is run. 

I like the complain on install.

**Comment by arantius** [comment]
It is definitely `@run-at`.  We indeed should limit to known/supported values.  My gut says treat any unknown value as `document-end`.  (That's all we truly support today, anyway.)

**Comment by Cerberus-tm** [comment]
I would prefer the latter option, because many users won't understand how to fix this themselves in the script. Various scripts might still work with the default.
