### ISSUE TITLE
Can't intercept ajax requests in Greasemonkey

### ISSUE THREAD

**Issue by FullMetalLion** [greasemonkey/greasemonkey#3015]
Here is a valid snippet of javascript code, that works in Tampermonkey and if pasted directly into the browser's console:

```
(function(open) {
    XMLHttpRequest.prototype.open = function() {
        this.addEventListener("readystatechange", function() {
            console.log("readyState: "+this.readyState);
        }, false);
        open.apply(this, arguments);
    };
})(XMLHttpRequest.prototype.open);
```

When an xhr is made, we expect the output
```
readyState: 1
readyState: 2
readyState: 3
readyState: 4
```
As the console.log fires four times. However, in Greasemonkey we get nothing, as the function never fires.

Here's a simple example website involving an ajax request so you can test it yourself:
https://fullmetallion.github.io/ajax/example

**Comment by makyen** [comment]
In which version of Firefox and GM are you doing this? What is the actual userscript (i.e. the entire code) that you are doing this in?

Most importantly, are you sure that you are executing this code in the page context? If you are not making an effort to run in the page context with code that you have not shown, then it's not unlikely that your code is not running in that context. The most common issue (in extensions and userscripts) for code which is attempting to override window properties for the page's JavaScript, is not actually making the change in the page context. This issue produces exactly the type of results which you are reporting ("It works if I run it in the console, but not in my code").

**Comment by FullMetalLion** [comment]
Ah, that's it; I just had to write
```
(function(open) {
    window.XMLHttpRequest.prototype.open = function() {
        this.addEventListener("readystatechange", function() {
            if(this.readyState == 4){removeBlockedMessages();}
        }, false);
        open.apply(this, arguments);
    };
})(window.XMLHttpRequest.prototype.open);
```

Thanks!

**Comment by FullMetalLion** [comment]
Oh, wait, I mistakenly believed this had fixed my problem while in fact it had not.
I am using Firefox 63.0.1 (64-bit) and GM 4.7

Here is the userscript:
```
// ==UserScript==
// @name     intercept
// @version  1
// @grant    none
// ==/UserScript==
console.log('intercept');
(function(open) {
    XMLHttpRequest.prototype.open = function() {
        this.addEventListener("readystatechange", function() {
            console.log("readyState: "+this.readyState);
        });
        open.apply(this, arguments);
    };
})(XMLHttpRequest.prototype.open);
```
How would I execute this code in the page context?

**Comment by Sxderp** [comment]
Perhaps you need to access the wrappedJSObject and cloneInto? 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts

**Comment by arantius** [comment]
This is expected.  GM4 does not yet support `@grant none`.

**Comment by Finomosec** [comment]
I solved this problem using exportFunction and unsafeWindow. This might work for what you are trying to do as well.

```
var oldSend = unsafeWindow.XMLHttpRequest.prototype.send;
unsafeWindow.XMLHttpRequest.prototype.send = exportFunction(function(data) {
    // modify data
    oldSend.call(this, data);
}, unsafeWindow);
```

**Comment by Finomosec** [comment]
And in order to modify the response i used this:

```
if (!unsafeWindow.XMLHttpRequest.prototype.getResponseText) {
	unsafeWindow.XMLHttpRequest.prototype.getResponseText = Object.getOwnPropertyDescriptor(unsafeWindow.XMLHttpRequest.prototype, 'responseText').get;
}
Object.defineProperty(unsafeWindow.XMLHttpRequest.prototype, 'responseText', {
	get: exportFunction(function() {
		var responseText = unsafeWindow.XMLHttpRequest.prototype.getResponseText.call(this);
                // modify responseText
		return responseText;
	}, unsafeWindow),
	enumerable: true,
	configurable: true
});
```
