### ISSUE TITLE
XMLHttpRequest/GM.xmlHttpRequest ignore cookies

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [greasemonkey/greasemonkey#3020]
My script works fine in scratchpad without any problem regardless without the workaround

I was making a script and and i needed to fetch data from another page on the same site but this page requires you to be logged in to get the data, but when the request is made it acts as though i am not logged in when the request is made with XMLHttpRequest/GM.xmlHttpRequest
everything is same origin complaint, but if i make a XMLHttpRequest via scratchpad it works as expected

Changing this setting to this makes my script work:
![screenshot_2019-02-09_19-27-39](https://user-images.githubusercontent.com/564653/52528023-fcd94e00-2ca0-11e9-914c-20fb87d44bae.png)

when a request is made via XMLHttpRequest/GM.xmlHttpRequest via GM cookie data is not transmitted when the browsers is set to only block cookies from sites that have not been visited, in spite of the target domain being the same as current domain, again this is not reproduce-able in a scratchpad only in GM

**Comment by Cerberus-tm** [comment]
Could you clean up your question? It is a bit hard to read now...

**Comment by GM-Script-Writer-62850** [comment]
Sorry, is that better?
