### ISSUE TITLE
Splitting a script into multiple files

### ISSUE THREAD

**Issue by robert-git** [greasemonkey/greasemonkey#3021]
I have the same question as this person:
https://stackoverflow.com/questions/49699692/greasemonkey-4-x-working-with-multiple-js-files

Prior to Greasemonkey 4.x, I had a script that was getting too big and complex, so I split it into multiple js files.  The js files were placed in the script directory, and the script included them with @require keys in the metadata block.  This worked, but after the upgrade to Greasemonkey 4, it stopped working.

Is there any way in Greasemonkey 4.x to split a script into multiple files?  Or is it now only possible for scripts to be implemented in one monolithic file?

**Comment by arantius** [comment]
This isn't a support forum, but https://wiki.greasespot.net/Metadata_Block#.40require
