### ISSUE TITLE
Any interest in this general idea?

### ISSUE THREAD

**Issue by globewalldesk** [greasemonkey/greasemonkey#3023]
Hello! I'm co-founder of Wikipedia (really; I'm globewalldesk here on Github) and now CIO of Everipedia.

I just had an idea for a strategy for how to decentralize social media, forcing Big Tech to give back control and privacy to their users (or else making them irrelevant). [Read more here.](https://larrysanger.org/2019/02/how-to-decentralize-social-media-a-brief-sketch/) A big part of the idea is something like Greasemonkey. Can developers interested in this idea please contact me at larry *at* everipedia.com? Thanks.

**Comment by Cerberus-tm** [comment]
That sounds like an interesting idea. Decentralising social media would be great. Could you be more specific about Greasemonkey's part in all this?

**Comment by arantius** [comment]
It looks like you want to have a discussion, which would better belong at https://groups.google.com/forum/#!forum/greasemonkey-users ?

But....

> Here’s the killer feature. Create at least one (could be many competing) browser plugins that enable you to (a) select feeds and then (b) display them alongside a user’s Twitter, Facebook, etc., feeds. (This could be an adaptation of Greasemonkey.) In other words, once this feature were available, you could tell your friends: “I’m not on Twitter. But if you want to see my Tweet-like posts appear in your Twitter feed, then simply install this plugin and input my feed address.

This sounds nothing like Greasemonkey to me.  This sounds (roughly) like some combination of an RSS reader and an email client.  Or if you want a persistent archive, usenet?

**Comment by globewalldesk** [comment]
Well, the suggestion is that Greasemonkey would take content published elsewhere, as by Indieweb.org feeds, and then simply to insert the content into Twitter, Facebook, and other feeds.

This isn't a Greasemonkey feature per se, but a separate plugin that could be written using Greasemonkey. It's just a suggestion. TNW liked the idea, for what it's worth: https://thenextweb.com/contributors/2019/02/20/how-to-decentralize-social-media-according-to-wikipedias-co-founder/

**Comment by kekkc** [comment]
>“I’m not on Twitter. But if you want to see my Tweet-like posts appear in your Twitter feed, then simply install this plugin and input my feed address. You’ll see my posts pop up just as if they were on Twitter. But they’re not! And we can do this because you can control how any website appears to you from your own browser. It’s totally legal and it’s actually a really good idea.”

Have not seen a thread in the forum, but I like the idea to have your data in control while still able to interact with social platforms. Question would be if heavy social media will use this plugin and if a GM script is the most feasible here to reach many people (or if seperate addons for different browser would make more sense, because they're more easily to setup for a mass of users)
