### ISSUE TITLE
Reports script errors to web console (page console, control-shift-K), not only to browser console

### ISSUE THREAD

**Issue by Cerberus-tm** [greasemonkey/greasemonkey#3029]
I noticed that (some?) script errors are reported in the browser console, but not in the page console (control-shift-K). Would it be possible to report script errors in both consoles? That would be helpful in debugging scripts. (Violentmonkey does report the same error in both consoles, in the same script I tested.)

**Comment by Sxderp** [comment]
Programmatic content scripts will fix this. Without, there's no way. I would link the issue number but I'm on mobile.

**Comment by Cerberus-tm** [comment]
@Sxderp Good to know! The issue is probably this:
https://github.com/greasemonkey/greasemonkey/issues/2663

**Comment by Sxderp** [comment]
> I do wonder how Violentmonkey manages to report the same error in both consoles...

Pretty sure they don't use content scripts. Rather they inject `<script>` tags into the page. This comes with its own set of limitations.

**Comment by Cerberus-tm** [comment]
Ah, I see. Is the limitation that those tags can and will be blocked by CSPs? Or is it something else.

**Comment by arantius** [comment]
It's several things but CSP is a big one.  Mostly having a security barrier between the script and the page.

**Comment by Cerberus-tm** [comment]
Good to know. I shall mention this to people whenever discussing the differences between GM and VM. So if I have a scrip that doesn't work in GM, I should probably only activate it in VM if it is limited to trusted domains like Youtube.
