### ISSUE TITLE
My script(s) don't show....for some reason...but installs fine...

### ISSUE THREAD

**Issue by DumbJoe** [greasemonkey/greasemonkey#3032]
According to this page: https://wiki.greasespot.net/Greasemonkey_Manual:Monkey_Menu It should show here: ![imgur link](]https://i.imgur.com/ghPONxw.png) 

But mine shows nothing(see above screenshot) there as if I have not installed any scripts whatsoever there......

**Comment by DumbJoe** [comment]
oh dunno why that imgur link points back to this topic, should be pointing here: https://i.imgur.com/ghPONxw.png

**Comment by arantius** [comment]
Which script did you install?  How do you know you installed it?

**Comment by DumbJoe** [comment]
> Which script did you install? How do you know you installed it?

adsbypasser.full.es7.user.js and youtube_old_design.user.js

How do I know? It said it installed successfully when I clicked install.....

**Comment by DumbJoe** [comment]
Nevermind....tried installing them again and now shows fine....
