### ISSUE TITLE
Greasemonkey 4 - Word Wrap and Page Listing All Scripts?

### ISSUE THREAD

**Issue by gaveitatry** [greasemonkey/greasemonkey#3037]
I'm trying to make the switch from Firefox 56.0.2 to Firefox 66.0.5.  Not sure if I will succeed or not.  I've ran into a lot of problems and have had to do some crazy things like install Linux for the first time in my life and edit the contents of the omni.ja file.  Anyway, one of the things I will need to adjust to is Greasemonkey 4 (or an alternative, if there is a good/better one).

In Firefox 56.0.2, on Greasemonkey 3, you can enable wrap text in the script editor window.  And I never used Tampermonkey before, but I glanced at it just now and it seems to have word wrap as the default setting.  Is there a way to have word wrap in Greasemonkey 4?  I mean, I guess someone could create a script that makes those pages have word wrap, but... I don't really want to do that.  I want it to be a default feature.

In Firefox 56.0.2, we also had a dedicated page that listed all of the installed user scripts.  Tampermonkey seems to have that too.  Do you have anything like that?  I haven't yet begun creating or importing user scripts, but it would be weird if the only place to find a list is in the popup window.

EDIT: Just tried Violentmonkey for the first time and it has the word wrap and I think the interface, pages, and popups are a lot better.  So I will probably switch to them since they have dedicated, easy-to-read pages for installed scripts.  The only problem with them is that their Violetmonkey icon is ugly (compared to yours).  And even though their interface is good, it could be better.  But maybe I can learn to change all of that.  If you think you can make Greasemonkey better for me, let me know.  I'll come back, probably.

**Comment by StigNygaard** [comment]
First-World problems...

**Comment by gaveitatry** [comment]
See the below screenshot:

![firefox_2019-05-24_17-04-07](https://user-images.githubusercontent.com/14252057/58358827-2ed48180-7e46-11e9-9ee2-751a10c69676.png)

Hey Stig Nggr.  I don't think living in a first world country has anything to do with this issue.  All other user script managers have word wrap in their editors.  Hell, even Greasemonkey 3 did for many years.  Greasemonkey 4 has been around for almost two years and still doesn't.  I'm simply pointing that out and making a request.  I noticed you deleted your comment after your attempt to troll me.  I know you are a white guy, but since you suffer from white guilt, maybe you are better off being Stig Nygaard from Africa, since you prefer third world countries.

Anyway, I am closing this ticket.  I'm not wasting time holding my breath for Greasemonkey 4 to do something they should have done two years ago.  At one time, it was the number one user script manager in existence.  Now it is one of the worst.  It's clear that they just don't have the same motivation and dedication to excellence as they once had.  Bye Stig Nggr.
