### ISSUE TITLE
Feature request: Add abstractions for changing HTTP answers

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [greasemonkey/greasemonkey#3046]
As you know, scripts in GreaseMonkey are loaded in the page, if no page is loaded they simply won't work

This poses a problem, how do you grab content from HTTP 401/402 answers?

Please add an abstraction that provides an API for grabbing info like HTTP error codes, redirect destinations and other info that generally can be carved out by `curl -I $website` answers

**Comment by arantius** [comment]
This is not going to happen.  Greasemonkey is a way to inject JS into pages.  This is an orthogonal feature which would add significant complexity.  

WebExtensions can do this and it's pretty straightforward to write a simple WebExtension.

**Comment by TanyaEleventhGoddess** [comment]
Oh well, thanks anyway
