### ISSUE TITLE
"@require filename.js" works with installed script, not newly-created one

### ISSUE THREAD

**Issue by suiryc** [greasemonkey/greasemonkey#3047]
Hi,

Running Greasemonkey 4.9 in Firefox 68.0.2

For long scripts, it's easier to split the code in multiple files.
As mentioned in #3021, the way to go is relying on `@require`.
Let's say I'm fiddling with an installed script, and add
```
// @require filename.js
```
A new tab for `filename.js` is created and I can use it to write some code that will be useable from the main userscript code.
As a side note: the initial content of this tab is the main userscript code while I would expect it to be empty, but I can empty it manually.

However, if I create a new script (personal script) and try to do the same, I can't save it due to an error: `filename.js is not a valid URL`. Should this work (as when done with an installed script), or is there another way to create a new (personal, not installed) script and split it in multiple files ?

**Comment by arantius** [comment]
https://wiki.greasespot.net/Metadata_Block#.40require
"The URL specified may be relative to the URL the script is being installed from. "

The parameter to require is a URL, not a file name.  This never works, *unless* the URL refers to a file that can be downloaded.  If it's not an absolute URL, it's a URL relative to the install URL, which does not exist for a local only "New user script...".

The simplest workaround is to provide the full URL for any empty page, which will successfully download.  And then you can edit it.

A way to make this cleaner might be nice.

>  As a side note: the initial content of this tab is the main userscript code while I would expect it to be empty, but I can empty it manually.

Full steps please.  This is not what happens to me in any method I tried.

**Comment by suiryc** [comment]
Indeed there is no install URL for a local only "New user script".
I would find it nice if greasemonkey could handle "require" of relative names in this case, or any other alternative method, allowing to have multi-files local-only scripts (with all 'files' managed by greasemonkey itself).

What I worked with was a legacy script (unmaintained) that I simply changed through greasemonkey. So for example:
1. Install any script, e.g. https://greasyfork.org/fr/scripts/368851-insert-lorem-ipsum
2. Insert the require
```
// @require filename.js
```
3. The `filename.js` tab contains the same code than the installed userscript, in its original version (does not include any modification made locally). If I replace this content by whatever code, it works as I would expect: as if the code was executed before the main userscript.

For the time being it serves me as a workaround to what I needed: my own version of a script, split in multiple files, all managed by greasemonkey locally. Hoping that this quirk remain working.

**Comment by arantius** [comment]
Thanks for the detailed steps!  This is a quirk of how greasyfork works;

https://greasyfork.org/scripts/368851-insert-lorem-ipsum/code/Insert%20Lorem%20ipsum.user.js

Is "the" install URL for this script, but:

https://greasyfork.org/scripts/368851-insert-lorem-ipsum/code/filename.js

Also serves the same script!  So if you install from greasyfork, this accidental workaround (require `anything.js` and the download won't fail) exists.

**Comment by suiryc** [comment]
Ok, thanks for the explanation.
Somehow I am lucky to have modified a script installed from this site then.
