### ISSUE TITLE
Not so hot auto reload

### ISSUE THREAD

**Issue by ghost** [greasemonkey/greasemonkey#3048]
a) Allow the user to whitelist a development local domain or IP where you can add a script that will automatically check for updates every second (only while the tab is focused?), or
b) that you can at least bookmark its URL and reload it without having to wait and click on Install.

Auto reloading the page would get annoying while testing (and not the intended behavior for testing), so instead the user would be responsible to reload the page itself when he wants to.

For security, this script could only work temporarily (until you close the browser or require manual "reinstall" every N minutes). There could be a warning color in the Greasemonkey icon or in other places making it clear that it's running.

**Comment by arantius** [comment]
Why?  What is your goal?

**Comment by duracellcell** [comment]
Since it's not possible to use an external editor (#2513), this change could make it easier to develop and test while using the alternative method of loading the script from a local server.

**Comment by AnnanFay** [comment]
> the alternative method of loading the script from a local server

From reading this I assume for development people are running a local server so it's served with the correct mime type and bookmarking their scripts. So to update the script you save the file, click the bookmark, wait 5 seconds, click install then reload the page?

It's this process I was looking for in #3079 but people didn't understand my question. The extra 2 button clicks are enough hassle that I'll probably just keep using my current method.
