### ISSUE TITLE
User data collection and privacy policy

### ISSUE THREAD

**Issue by dockerest** [greasemonkey/greasemonkey#3050]
Maybe you are aware but I've seen a few posts in forums talking about Greasemonkey's privacy policy and that your privacy policy lists user data collection. It could be just a competitor trying to put you in a bad light.

Could you clarify?

1. What data is being collected right now?
2. Is it opt-in or opt-out?
3. Is the data sold to 3rd-parties?

The website privacy policy could be removed if you are not collecting data or at least move to this repository and make it clear what is going on.

It's too bad that Mozilla did not added your extension to the Recommended list.

**Comment by arantius** [comment]
> Maybe you are aware but I've seen a few posts in forums ...

The internet in general, and "forums" in particular, are fraught resources.  In general I don't go seeking out falsehoods.

>  What data is being collected right now?

Nothing.  Back in version 3.x (so just under two years ago), we did some basic gathering of [stats](https://github.com/greasemonkey/greasemonkey/blob/3.x/modules/stats.js), but that was never ported to version 4.x.

> Is it opt-in or opt-out?

It _was_ opt in.

> Is the data sold to 3rd-parties?

That's a bit insulting.  Nobody has ever been financially compensated in any way for this project.  When data was tracked, it was exclusively for guiding development.

**Comment by Cerberus-tm** [comment]
Yeah, that sounded a bit paranoid. I wonder where he found this privacy policy, since I don't believe there is one. In all fairness, he did say "It could be just a competitor trying to put you in a bad light".

**Comment by arantius** [comment]
AMO required listing a privacy policy, back when we were indeed gathering usage stats ( https://web.archive.org/web/20170830170635/https://addons.mozilla.org/En-us/firefox/addon/greasemonkey/privacy/ ).

**Comment by dockerest** [comment]
>The internet in general, and "forums" in particular, are fraught resources. In general I don't go seeking out falsehoods.

That's why I created this issue. So I can link to it and end the FUD. They always say information is outdated so the words of the maintainer can put an end to it.

>That's a bit insulting. Nobody has ever been financially compensated in any way for this project. When data was tracked, it was exclusively for guiding development.

I apologize if I offended you it was not my intention.

https://www.greasespot.net/p/privacy-policy.html

And this post clears things up but they are, of course, not linking to it.
https://www.greasespot.net/2012/11/anonymous-statistic-gathering.html

>We do not sell, trade, or rent Users personal information to others. We may share generic aggregated demographic information not linked to any personal information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.  We may publish aggregated statistics based on this information online.

Even if it's boilerplate this kind of paragraph always leads to people talking that it could be circumvented and that there's no such thing as anonymous aggregate data. I will not bother you with questions anymore.

**Comment by arantius** [comment]
> Even if it's boilerplate ...

Which of course it is.  It's gone now, there's no longer any data gathered that it could apply to.

> I will not bother you with questions anymore.

Sounds like you're coming from an honest place, don't worry.
