### ISSUE TITLE
Prevents some Google Sheets from loading

### ISSUE THREAD

**Issue by impala75** [greasemonkey/greasemonkey#3051]
Hello,
I've just identified that among my Firefox extensions, Greasemonkey is the one preventing some Google Sheets from opening correctly. They load without end and their tabs, when they have some, can't be displayed. These are very simple sheets, without complicated formulas.

**Comment by Cerberus-tm** [comment]
Do you have an example URL that we could test this on? I don't remember being affected by this issue.

**Comment by impala75** [comment]
Hello,
As the files are private I've just create one to test on, from one of these files: https://drive.google.com/open?id=1XpDCV6Y52Vn34JaiTW0U6rVKSL6FvhH0xXXiuGuLeQw

The only user script I use with Greasemonkey is Anti-Adblock Killer.

**Comment by Cerberus-tm** [comment]
Hmm when I tried it, the spreadsheet would load fine with Greasemonkey enabled. I could click on tabs just fine, and everything looked normal, no continuous loading. However, I did need to allow certain scripts in Ublock Origin, or Google Sheets wouldn't load or wouldn't load properly. So are you sure the problem lies with Greasemonkey? Do you use Ublock?

**Comment by impala75** [comment]
Hello,
Yes I am sure that on my side the problem lies with Greasemonkey, in the sense that, when I activate Greasemonkey, the file doesn't load properly, and when I deactivate it, it does. I have tested that many times with always the same results.

I use uBlock too. I've just deactivated it to test the file, but that does not solve the problem.

I will try the test you suggest and keep you informed.

**Comment by arantius** [comment]
Link also loads fine for me.  This sounds a lot like some particular script you're running is the actual problem.

**Comment by impala75** [comment]
Well, I as said, I only use one script: Anti-Adblock Killer (a very well-known script, if I'm not mistaken). So if it is guilty of this, it will be easy to know :).

**Comment by impala75** [comment]
So yes, it is, indeed.
Doesn't anybody of you use this script too?

**Comment by arantius** [comment]
"So yes, it is, indeed." that script has this cause?  Ok.

**Comment by impala75** [comment]
Yes, apparently Anti-Adblock Killer causes this.

**Comment by Cerberus-tm** [comment]
@impala75 Since the problem lies with the script and not with Greasemonkey, perhaps you might consider changing your review on Mozilla.org?
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/reviews/

**Comment by impala75** [comment]
done

**Comment by Cerberus-tm** [comment]
Great!
