### ISSUE TITLE
Unable to copy a script from the editor

### ISSUE THREAD

**Issue by flarn2006** [greasemonkey/greasemonkey#3052]
Whenever I select all and copy in the built-in editor, pasting just gives me a single `-` character. Considering I don't know of any other way to export scripts, this is a big problem.

**Comment by arantius** [comment]
https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help#What_to_Say

**Comment by flarn2006** [comment]
Oops sorry; I was in a rush and annoyed at the time I reported this. Here you go:

*Operating System:* Arch Linux
*Firefox version:* 69.0.1
*Greasemonkey version:* 4.3
*Exactly which script, if any, is causing a problem?* It's one I made. I'd post it, but the only way I know of to get it out of the editor (see also #3053) is by copying it to the clipboard, and of course that's not an option.
*Exactly which page, if any, is exhibiting this problem.* Well it's the script editor, so I guess moz-extension://1b5a7ce0-a8d3-41eb-b985-98bb4ea6c884/src/content/edit-user-script.html.

**Comment by flarn2006** [comment]
Actually, after doing some testing, it appears that this happens any time you attempt to copy more than 1,001 characters.

**Comment by arantius** [comment]
I just copied 57,450 characters out of a script first try.

**Comment by Cerberus-tm** [comment]
I've never experienced this issue either (just some delays in copying/pasting). So could it be something specific to your system?

**Comment by flarn2006** [comment]
Can you try with this script?
https://flarn2006.github.io/stegasuras.user.js

**Comment by Cerberus-tm** [comment]
I've tried it with that script, but I could copy the entire script from the GM editor into an external text editor just fine.

**Comment by flarn2006** [comment]
Ah okay; must have just been on my side then. Sorry to waste your time!

**Comment by Cerberus-tm** [comment]
@flarn2006 OK, I hope you manage to solve the issue!

**Comment by AnnanFay** [comment]
Related: https://github.com/codemirror/CodeMirror/issues/3486
