### ISSUE TITLE
Can't figure out how to export a userscript I've created

### ISSUE THREAD

**Issue by flarn2006** [greasemonkey/greasemonkey#3053]
The only option I see for accessing a userscript's code is to open it in the built-in editor, where copying the script to the clipboard doesn't work (#3052). If there is an option to export it to a file, or open it in an external editor, it isn't obvious where that option is, and if there isn't an option to do that, there should be.

I can't even find the file that contains the script. There's the gm_scripts directory in my Firefox profile, but that one script is missing for some reason. I guess that means they're stored somewhere else now. But I even tried running `strace` on Firefox, and the only file it opens is some SQLite database in the extension's storage, and I don't see the JavaScript code anywhere in there.

**Comment by arantius** [comment]
![Monkey-menu](https://user-images.githubusercontent.com/84729/65834053-1b7a6c80-e2a5-11e9-8440-f7792f2285c2.png)

**Comment by flarn2006** [comment]
Weird, the "Export a backup" and "Import a backup" options are missing from my menu. Anything you know of that may prevent them from appearing?
