### ISSUE TITLE
GM_addStyle does not work on Android

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#3056]
I just wrote https://arantius.com/misc/greasemonkey/hacker-news-mobile-skin.user.js -- at first I used `GM_addStyle()`.  The script didn't work.  Pasted an equivalent in-line in the script, and it worked.  Hard to test on mobile so I don't have more detail yet.

**Comment by Cerberus-tm** [comment]
Oh, I thought GM_addStyle had been removed? Or is the mobile version completely different?

**Comment by arantius** [comment]
It's against current guidelines (built-in APIs only do what a user script can't do on its own), but it's grandfathered in.  Mobile is the exact same code from our side, so if it doesn't work, it's something about the mobile browser itself.

**Comment by Cerberus-tm** [comment]
Good to know.
