### ISSUE TITLE
"Content scripts will have the same permissions as the page they are injected in": will Greasemonkey be affected?

### ISSUE THREAD

**Issue by Cerberus-tm** [greasemonkey/greasemonkey#3061]
In a recent [entry ](https://blog.mozilla.org/addons/2019/09/03/mozillas-manifest-v3-faq/)on Manifest V3 and how Firefox will deal with it, the Mozilla Add-ons weblog says the following:

> **Cross-origin communication**: In Manifest v3, content scripts will have the same permissions as the page they are injected in. We are planning to implement this change.

Will this affect Greasemonkey, by making userscripts subject to the CSP of a particular website, allowing the website to block functions in userscripts? Or is that entirely unrelated? I thought Greasemonkey used content scripts but perhaps that is wrong.

**Comment by arantius** [comment]
Given the "Cross-origin communication" heading, I'm guessing this could break GM_xhr for talking to other domains?

But, as long as they don't break BG<->CS communication (how could they, this would break a lot of things!) we'll be fine.  We just pass messages to the background script, which uses /its/ permission to do this.

**Comment by cnleo** [comment]
@arantius you mean "In Manifest V3, the only allowable background presence type will be ServiceWorkers."?

https://docs.google.com/document/d/1nPu6Wy4LWR66EFLeYInl3NzzhHzc-qnk4w4PX-0XMw8

I my opinion, if both chrome/ium and firefox engines switch over to manifest v3. This is the end of the web as we know it. It must be clear that the future is for Browser forks without that v3 stuff in there. For Browser without any kind of advertising network relationship.

Just my 2 cents.

**Comment by Cerberus-tm** [comment]
Ah, I see. So as long as "the same permissions" applies to cross-origin communication only, it should only affect GM.xmlHttpRequest. And, otherwise, the restriction can be or is already worked around because the background script will do the things that need permissions and pass its results on to the content script.  But would that mean that a userscript could still e.g. inject a <script> element?

**Comment by Cerberus-tm** [comment]
@cnleo As you can see on that page, Firefox is not planning to adopt everything from V3, and some of the things it will adopt will be changed.

**Comment by Sxderp** [comment]
> And, otherwise, the restriction can be or is already worked around because the background script will do the things that need permissions and pass its results on to the content script.

Greasemonkey already does this. Of course this will break some of my personal scripts because I was using (abusing?) the cross-origin-ness of content scripts to avoid the message passing to the background (I was basically skipping overhead).

**Comment by Cerberus-tm** [comment]
> 
> 
> > And, otherwise, the restriction can be or is already worked around because the background script will do the things that need permissions and pass its results on to the content script.
> 
> Greasemonkey already does this. Of course this will break some of my personal scripts because I was using (abusing?) the cross-origin-ness of content scripts to avoid the message passing to the background (I was basically skipping overhead).

Ah, good to know. Out of curiosity, how are you abusing this? What kind of code does that?

**Comment by Sxderp** [comment]
> Ah, good to know. Out of curiosity, how are you abusing this? What kind of code does that?

Missed this.
I didn't use the GM_xhr function. The GM_xhr function sends a message to the background with your request information saying "please send this request and give back the response". I didn't do that, I made the requests directly.

**Comment by Cerberus-tm** [comment]
OK, thanks. So at least we'll be able to use GM.xmlHttpRequest (I presume that's the one you're referring to) as normal and accomplish what we always have.
