### ISSUE TITLE
script stops reloading a website if after some time, server sends "server not found/page not found".

### ISSUE THREAD

**Issue by Dani3lNL** [greasemonkey/greasemonkey#3062]
I have a script containing this line

`setTimeout(function(){ location.reload(); }, 5*1000);`

now after a few minutes, the website content shows the (Firefox) message "server not found" (in tab title) and "page not found" in content window, and greasemonkey stops the every-5-seconds reloadings.
Is this a Firefox (Developer edition) bug or greasemonkey bug? I'll wait for your response and then we'll see if this should be reported also to Mozilla on bugzilla.mozilla.org or not.

**Comment by arantius** [comment]
Can't inject scripts into system (error) pages.

**Comment by Dani3lNL** [comment]
@arantius uhm, so? This a Firefox bug, not Greasemonkey bug? o_O

**Comment by arantius** [comment]
It's not a bug, it's just the way (Firefox) works.

**Comment by Dani3lNL** [comment]
I'm in contact with a bugzilla person, will see what he responds
