### ISSUE TITLE
Save script error - fictional name collision

### ISSUE THREAD

**Issue by adamhotep** [greasemonkey/greasemonkey#3063]
After upgrading to Firefox 71.0 (full version info is below), I can now neither add nor modify userscripts.

When I try to save edits to an existing script, even in adding a trailing newline, I get a "script save error." This is also true of new scripts. For example:

> Script save error
> * User script save failed: script named "Unnamed Script 245870" already exists in namespace null.
> 
> The editor contents have not been saved. Fix this error and try again.

Following the advice in [arantius's comment in issue 2847](https://github.com/greasemonkey/greasemonkey/issues/2847#issuecomment-371172344), I reloaded the script and it reverted to the original template, but then adding a trailing newline and trying to save resulted in the same error.

This is independent of the script name and namespace; I've tried variations with unique garbage names and/or namespaces.

This is using Greasemonkey 4.9 on Firefox 71.0 (64-bit) with Debian's firefox 71.0-1 package,
`Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0`

The error text and check come from [af15dc1](https://github.com/greasemonkey/greasemonkey/commit/af15dc1718f6cf770fe93acd3e450041dd0adaaa) but I doubt that's the source if this issue.

PS: existing userscripts work fine (except those that need to be edited...)

**Comment by jhnc** [comment]
debian has released 71.0-2 to fix bugs [#946249](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946249) and [#946547](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946547)

**Comment by adamhotep** [comment]
Yup, upgrading to 71.0-2 solved it. Thanks!
