### ISSUE TITLE
High CPU CPU usage with Firefox 71

### ISSUE THREAD

**Issue by undeference** [greasemonkey/greasemonkey#3064]
After updating to Firefox 71 … several minutes after starting Firefox, its CPU usage goes up and stays high. about:performance blames Greasemonkey. Disabling the extension in about:addons instantly lowers Firefox CPU usage. "Disabling" the extension with the Greasemonkey menu (i.e., unticking active) does not.

This happens even if the extension is "disabled" (i.e., enabled in about:addons but not marked active), and even if Firefox has only about:blank open.

The debugger shows Greasemonkey repeatedly (like a few times per second) requesting the same script URLs, probably trying to update.

**Comment by Cerberus-tm** [comment]
Which version of GM are you using?

When you were using the same version of GM on Firefox 70, the issue did not occur?

**Comment by undeference** [comment]
> Which version of GM are you using?
> 

2019.9.30.15113nightly

> When you were using the same version of GM on Firefox 70, the issue did not occur?

Correct

**Comment by arantius** [comment]
Exactly which version of Firefox?  On Linux?  What's the "User Agent" line at about:support say?

**Comment by undeference** [comment]
```
rpm -q firefox
firefox-71.0-8.npgo.fc30.x86_64
```
```
Version 	71.0
Build ID 	20191203065540
User Agent 	Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
OS 	Linux 5.3.15-200.fc30.x86_64
```

**Comment by undeference** [comment]
After each XHR request, I see this
```
 ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. ExtensionStorageIDB.jsm:812
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:812
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:695

```

I wonder if it's possibly related to https://bugzilla.redhat.com/show_bug.cgi?id=1779570. I started testing with an official Firefox release and have yet to see this issue, so I think it may be. I'll wait a bit before reporting on the Red Hat bugzilla.
