### ISSUE TITLE
Script does not load on raw.githubusercontent.com pages

### ISSUE THREAD

**Issue by wesinator** [greasemonkey/greasemonkey#3065]
**Update**: see https://github.com/greasemonkey/greasemonkey/issues/3065#issuecomment-583770358

<br>
Try the following snippet of code on https://raw.githubusercontent.com/greasemonkey/greasemonkey/master/peg.txt
and
https://releases.llvm.org/2.8/LICENSE.TXT

```javascript
// ==UserScript==
// @name     plain text check test
// @version  1
// @grant    none
// @match  *://*/*
// ==/UserScript==

//setTimeout(function() {
  //console.log($("pre"));
	if (document.contentType == "text/plain") {
  	console.log("plaintext file detected");
	}
//}, 5000);

```

It works on the latter license.txt file , but not the peg.txt (files on raw githubusercontent)
Why?

both have `document.contentType == "text/plain"`
![image](https://user-images.githubusercontent.com/5124946/70874610-e666e780-1f80-11ea-8fbd-dec340c3dd05.png)

Firefox 71.0
Ubuntu 18.04

**Comment by arantius** [comment]
> It works on the latter license.txt file , but not the peg.txt (files on raw githubusercontent)

What does this mean?  What (value of `document.contentType`) are you seeing, and what do you expect?

**Comment by wesinator** [comment]
> > It works on the latter license.txt file , but not the peg.txt (files on raw githubusercontent)
> 
> What does this mean? What (value of `document.contentType`) are you seeing, and what do you expect?

It's the same contentType `text/plain` on both of the example URLs as expected. (as my screenshot shows)

However, the script only runs on the license.txt . 
Unexpectedly, it does not run on any raw.githubusercontent.com pages

**Comment by wesinator** [comment]
@arantius So userscripts just aren't loading at all on `raw.githubusercontent.com` locations for some reason:

```js
// ==UserScript==
// @name     test userscript
// @version  1
// @grant    none
// @match  *://*/*
// @run-at  document-idle
// ==/UserScript==

console.log("loaded userscript")

```
https://raw.githubusercontent.com/greasemonkey/greasemonkey/master/peg.txt 
![image](https://user-images.githubusercontent.com/5124946/74091089-b2400c80-4a81-11ea-95d1-6c1c38113b22.png)


doesn't work on any githubusercontent pages
but it loads on any other site

Removing `// @run-at  document-idle` has no effect

Firefox 72.0.1 x64
Ubuntu 18.04 (GNOME)

Do you know what's going on here ?!

**Comment by arantius** [comment]
I see an error logged:

   Missing host permission for the tab

Which doesn't make a lot of sense, given ( https://github.com/greasemonkey/greasemonkey/blob/master/manifest.json#L66 ) the "<all_urls>" permission.  Maybe a bad interaction with Content-Security-Policy.  `chrome.tabs.executeScript()` just does nothing, including not calling the error callback.

**Comment by wesinator** [comment]
It doesn't work on this location in Tampermonkey either, fwiw

**Comment by wesinator** [comment]
reported a bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1616135 

I also encountered this in another extension using [tabs.executeScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript)
