### ISSUE TITLE
What is the correct way of reloading scripts during development?

### ISSUE THREAD

**Issue by AnnanFay** [greasemonkey/greasemonkey#3079]
How do people reload scripts while editing them? I have tried looking online and in the issues here but cannot figure out the proper way of doing it.

I am currently using **Firefox 56 from 2017** to do development because it's the latest version which will reload local script files as I edit them (GM3.17). I have the build process copy the scripts into the `gm_scripts` and it generally works. This is however a horrific 'solution'.  I must be missing something obvious which other developers are doing.

What is the correct way to get a greasemonkey script to automatically reload during development when I edit it in an external file or when a file is generated from a build process?

**Comment by Cerberus-tm** [comment]
I'm not sure I understand: why would you want to reload a script? What does that mean? You don't mean reloading a web page?

**Comment by AnnanFay** [comment]
@Cerberus-tm I write scripts by iteratively improving them. I need to run the script in the browser each time I make an edit to detect any mistakes I have made and see if my most recent changes had the intended effect. That way I know any mistakes are caused by the most recent changes.

1. Write script
2. Run in browser
3. Detect bugs
4. Fix bugs
5. Go to 2

Repeat steps 2-4 a few hundred times because I make many mistakes.

**Comment by arantius** [comment]
Scripts run at page load time.  Reload the page.

(Most scripts modify the page, there's no "re-run the script" without reloading the page to give it a fresh page to modify, anyway.)

**Comment by AnnanFay** [comment]
> So I do mean reloading the web page, though that's just an implicit consequence of needing to reload the userscript.

@arantius I do not mind reloading the page to reload the script and am not looking for this. **How do I update the script?**

I think you are misunderstanding my question. I am using Sublime Text to edit my script and I am using NPM and Grunt to compile a `user.js` file on the hard drive. I then need to update the script in the browser so I can test it.

How can I update the script which is stored in GM after editing it in a source code editor?
