### ISSUE TITLE
Certain characters in the @name field make GM create backups with an incorrect structure

### ISSUE THREAD

**Issue by lkintact** [greasemonkey/greasemonkey#3083]
1. Add a new script with the `@name` field containing a slash (`/`), for example this one:
```
// ==UserScript==
// @name        example.com - enable/disable colors
// @namespace   example.com
// @description switches colors on and off on example.com
// @include     https://example.com/*
// @version     1
// @grant       none
// ==/UserScript==

function switchColors() { }
```
2. Choose "Export a backup..." from the drop-down menu and save the backup zip file.
3. The hierarchy inside the backup is as follows:
  - `example.com - enable--disable colors` (folder)
     - `example.com - enable` (folder)
        - `disable colors.user.js` (file)
     - `.gm.json` (file)

Apparently this structure is incorrect, because trying to import the backup results in a frozen progress bar and a "TypeError: zip.file(...) is null" error in the Web Console (Ctrl+Shift+K).

4. If the `@name` field in step 1 didn't contain the slash, and the corresponding line was
`// @name        example.com - enable disable colors`, the hierarchy inside the backup file would be
- `example.com - enable disable colors` (folder)
  - `example.com - enable disable colors.user.js` (file)
  - `.gm.json` (file),

and in that case the backup would be imported without any problems.

There seem to be other chars causing the problem, like `<`, `>`, `*`, `:`, maybe some others - perhaps it depends on what the OS allows in file paths.

Greasemonkey: 4.9
Firefox: 76.0.1
OS: Windows 10 Home 1803.

**Comment by Sxderp** [comment]
Forward slash (and NUL) are invalid characters in all filesystems. I can't really think of any but some filesystems may have further restrictions. Some OSes (Windows) put restrictions on characters that can be used (like `<` , `>` , `:`) or file names (`COM`), but those restrictions aren't inherent to the filesystem.

Anyway, What's required is some method to encode and decode these characters in a lossless manner that would be accepted on all platforms and filesystems.

First thought being base64 encode everything. Two obvious drawbacks. It's not human readable and you could run into file length issues. Though file length issues could happen even without base64 but wouldn't happen as quickly.

HTML escape could also work. Either everything or just special case known invalid characters.
