### ISSUE TITLE
User scripts do not get run on iframes

### ISSUE THREAD

**Issue by andlaus** [greasemonkey/greasemonkey#3086]
I want to write a user script for a site which involves an iframe. According to [this](https://stackoverflow.com/questions/37616818/apply-a-greasemonkey-tampermonkey-userscript-to-an-iframe), greasemonkey user scripts ought to run for iframes by default if the include rules match, yet I could not make it work. I thus created a [simple test](https://poware.org/gm_ift.html) for which the script

```javascript
// ==UserScript==
// @name     Unnamed Script 354832
// @version  1
// @grant    none
// @include    https://poware.org/gm_*
// ==/UserScript==

console.log("HELLO", window.top === window.self);
```

is supposed to produce two messages on the javascript console, one `true` and one `false`. Yet only the `true` message appears with greasemonkey. Finally I've checked if the test behaves as expected with tampermonkey/chromium (it does), so I suppose that this probably is a bug in greasemonkey or in firefox?

**Comment by arantius** [comment]
#2574
