### ISSUE TITLE
Greasemonkey Get and Set Value not working and killing script with no error in GM 4.0+

### ISSUE THREAD

**Issue by Armingleggings** [greasemonkey/greasemonkey#3087]
```
// ==UserScript==
// @name     Netflix saw it button
// @description     Apparently Netflix can't afford enough storage space or programmers to make it easy to know which shows you've seen before. This fixes that. Unfortunately, it will only store data in one browser at a time so you have to use the same computer and browser for the data to store. Sorry about that, but I'm not a Netflix tech so this is the best we got.
// @version  1
// @include     https://www.netflix.com/*
// @grant    none
// @grant    GM.getValue
// @grant    GM.setValue
// @require https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js 
// ==/UserScript==


$(document).ready(function() {  
  $('[data-tracking-uuid]').each(function(){
    id= $(this).data('tracking-uuid');
    console.log(id);
    console.log(typeof id);
    GM.setValue(id,1);
    console.log(GM.getValue(id));
    if(GM.getValue($(this).data('tracking-uuid')))
      $(this).closest('.title-card-container').addClass('g_watched');
  });
});
```

As you can see, I'm testing persistant storage, but it's not giving me the results I'd expect. When I check the console, I can see the id and the id's type is string (which GM.setValue requires). On the very next line when it tries to set the value, it stops executing JS and no other lines run. No error is thrown. It just dies.

It was the same when I didn't have the setvalue there and just had getvalue (which should return null if it hasn't been set before). What am I doing wrong? This is Greasemonkey > 4.0 so this should be the proper syntax, but without any kind of error or feedback, I'm stuck.

**Comment by tobbexiv** [comment]
Hi,

I get errors in Firefox console.

Regarding your coding:
* If you paste code, it is recommended to format it as such. Makes reading easier and avoids linking people :)
* Your code misses `// ==UserScript==`
* If you `@grant none`, nothing is granted and the other, later grants are ignored.
* The GM functions return promises. ==> Your current coding cannot work. See also https://wiki.greasespot.net/Greasemonkey_Manual:API

**Comment by Armingleggings** [comment]
The beginging userscript statement was truncated, but is in my code. I've updated the post per your suggestions.

As for grant, I thought it was like htaccess permissions, but if not, that would definitely create problems! I've also never used promises nor does that make sense for local storage, but the example shows how to overcome that with awaits. I will try it, thank you!

**Comment by Eselce** [comment]
You should use `await` or `.then()`. It's not as complicated as it seems to be!

**Comment by Sxderp** [comment]
> You should use `await` or `.then()`. It's not as complicated as it seems to be!

This is correct and should be elaborated on. The `getValue` and `setValue` are asynchronous and return promises that should be `await`ed or have their `.then` method invoked with a callback.

However, Promises should be automatically returned and the code shouldn't just die on invocation of a asynchronous function. I'd expect this part:
```javascript
    console.log(id);
    console.log(typeof id);
    GM.setValue(id,1);
    console.log(GM.getValue(id));
```

To log a Promise which, according to the OP, it's not. I haven't done any testing, this is just my 30 second analysis.

**Comment by tobbexiv** [comment]
The failing is due to the `@grant none` which prevents that anything is granted (this was tested by me). Then, `GM.*` is undefined leading to an error.

Once this incorrect grant is removed, @Sxderp describes what will happen.

**Comment by Cerberus-tm** [comment]
It would be really nice if all errors from faulty code in a Greasemonkey script were to appear in the **web console**, the one that is show in the lower part of the page when you press shift-control-K. Currently, only some errors are shown there, alas. Others are shown only in the browser console (shift-control), which is a mess.
