### ISSUE TITLE
Greasemonkey running on every pages it shouldn't

### ISSUE THREAD

**Issue by Armingleggings** [greasemonkey/greasemonkey#3088]
`// ==UserScript==
// @name	Netflix saw it button

// @description	Apparently Netflix can't afford enough storage space or programmers to make it easy to know which shows you've seen before. This fixes that. Unfortunately, it will only store data in one browser at a time so you have to use the same computer and browser for the data to store. Sorry about that, but I'm not a Netflix tech so this is the best we got.

// @include	https://www.netflix.com/*

// @require https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js 

// ==/UserScript==
`
It's pretty simple so what's wrong? Why is it running on non netflix pages?

**Comment by Sxderp** [comment]
Does it work if you change include to match?

**Comment by Armingleggings** [comment]
Nope. Still runs on non-netflix sites.

**Comment by Armingleggings** [comment]
Aw hell. I figured it out. It's not running on non-netflix sites, it's running on my blog because I dropped the code in as a sample and it's interpreting it and running it instead of just displaying it. Gawd...
