### ISSUE TITLE
Revive i18n of @name and @description

### ISSUE THREAD

**Issue by esperecyan** [greasemonkey/greasemonkey#3089]
I would like to see the localization feature that existed in Greasemonkey 3.x implemented.

https://wiki.greasespot.net/Metadata_Block#.40name
https://wiki.greasespot.net/Metadata_Block#.40description
> As of Greasemonkey 2.2: can be localized for multiple languages, for example: 
> ```
> // @name       Example Script
> // @name:cs    Uživatelské skripty
> // @name:es-MX Ejemplo Script 
> // @name:ru    Пользовательские скрипты
> ```
> Add a colon and the locale code, which is the ISO 639 language code and optionally a hyphen and ISO 3166 country code, when disambiguation is necessary. When the user's browser is configured with the matching primary language, that value will be displayed instead. 

It has been already implemented in Violentmonkey and Tampermonkey, as well as in the repository “Greasy Fork”.
https://violentmonkey.github.io/api/metadata-block/
https://greasyfork.org/help/meta-keys

**Comment by arantius** [comment]
This should be straightforward, the values are parsed out and saved ( https://github.com/greasemonkey/greasemonkey/blob/master/src/parse-user-script.js#L121 ).  They're just never read.  Pull requests welcome; please make sure to add unit tests as well (localization is very hard to test by hand).
