### ISSUE TITLE
Greasemonkey doesn't transfer 3.17's scripts and there's no way to export/import them

### ISSUE THREAD

**Issue by mzso** [greasemonkey/greasemonkey#3094]
I have a bunch of scripts with 3.17, but I see no way whatsoever to transfer them to the new greasemonkey.
One would hope that happens automatically, but it doesn't. Even worse that the old version doesn't have an export feature.

**Comment by mzso** [comment]
Well, I took the pain of updating FF56 and greasemonkey as well, to current in a different profile. Only to find that it exporting doesn't  work... It fails silently.

There's only this in the error console:

```
Promise rejected while context is inactive: Ignoring @match pattern http://* because:
Error: @match: Could not parse the pattern: http://*
monkey-menu.js:219
    activate moz-extension://f8dff6f5-8278-4561-9497-63e7ce3aee3c/src/browser/monkey-menu.js:219

```

**Comment by mzso** [comment]
Apparently for some reason it got hung up on a script that had a` @match http://*` line. Such a silly thing to get hung upon. And silently, non the less. I don't think script content should break such functionality. One might have half written scripts disabled or ones filled with typos.

**Comment by arantius** [comment]
A lot of work was done, back in 2017, to make the transition as smooth as possible.  That said, it's been three years, version 3.x is not supported any longer.

**Comment by makyen** [comment]
@mzso Your worst case should be that the 3.X version stored each script in a separate directory and file within the profile directory. All of those were in the *gm_scripts* directory within your profile directory. You should be able to access all of your scripts in the subdirectories under that directory. You may have to do a considerable amount of copy and pasting in order to get them into GM4, but you should have easy access to the files containing each individual script. The userscript storage data is contained in a .db file for each script in the *gm_scripts* directory.

For the vast majority of users, the process of moving scripts from 3.X to GM4 was automatic. It's unfortunate that that process didn't work for you. As has been mentioned, at this point, there isn't going to be an automatic solution for problems you experience with this situation.

Something that may help to get the scripts into GM4: You can set up the files to be served via a HTTP/HTTPS server on your localhost, or some web space which you have access to. That would allow you to install each script with just a click on the appropriate file, rather than needing to go through the effort of copy & pasting the text.

**Comment by Cerberus-tm** [comment]
@makyen About servicing files via a server on localhost: would that allow one to keep editing the file on one's hard drive, without requiring the Greasemonkey editor? So one could simply save the file in one's favourite Windows editor, like Sublime Text, and the script would be updated into Greasemonkey automatically?

**Comment by makyen** [comment]
@Cerberus-tm Sort-of, with caveats (i.e. it's useful, but not a complete solution). If the script is installed from the localhost served location, then changes to the file will, eventually, be automatically detected, if the change meets the userscript manager's change detection criteria (e.g. a version number change). As far as I know, this works with all userscript managers which have automatic update detection. The automatic detection will work just like installing the script from any other web location.

In other words, if the change isn't one which would be automatically detected (e.g. a version number change), then the script will not be automatically updated. In addition, the automatic detection will only happen at the time the userscript manager would normally run a check for updates. So, it's helpful, but doesn't *really* solve being able to edit using an external editor and having the update automatically detected upon save.

I primarily edit userscripts using an external editor, with only very rare edits using any of the userscript managers' integrated editors. I do serve the userscript files on localhost. To update after an edit, I use a combination of copy and pasting (select all; copy; select all; paste; save; all of which is just a few quick standard key combinations, or mouse clicks), manually clicking on a listing of the file in the browser from either a directory listing or an HTML file containing a list of the userscripts I edit (e.g. just keep the list of the files open in a tab), and allowing the automatic detection to take place. For the locally served files, I find the automatic detection to be primarily useful to keep browser profiles which I don't use every day updated (i.e. those will tend to run a check for updates shortly after I begin using the profile after not using it for a while). Overall, it is not as convenient as being able to have immediate detection of a save of the externally edited file, but it's not that bad (a few extra seconds and keys when wanting to test a change).

**Comment by Cerberus-tm** [comment]
@makyen Thank you for your detailed reply. Then I agree with you that this server thing isn't really useful for writing and testing scripts on the fly.

I've been using an Autohotkey script for a few years which seems to be reliable, allowing me to edit Greasemonkey scripts in Sublime Text. But it uses ugly work-arounds like key presses, as you suggested. And it takes several seconds to automatically open-or-create the file when I start editing a userscript, and about a second to apply a script change and initiate an auto-refresh of the browser tab. So it's super ugly. Oh, well, I'll just continue to live with it.

**Comment by Janaue** [comment]
> For the vast majority of users, the process of moving scripts from 3.X to GM4 was automatic. It's unfortunate that that process didn't work for you. As has been mentioned, at this point, there isn't going to be an automatic solution for problems you experience with this situation.


Hello

I have firefox portable 56 and greasmonkey 3.17 on it with all my scripts in the folder gm_scripts. Can you tell me what is the automatic procedure to get all this updated to gm4 ? I am fine with updating FF 56. Should I just let firefox update itself and it would install GM4 for me?

My ultimate goal is to import those scripts into Violent monkey on portable firefox 83, but there are so many scripts in the folder gm_scripts that I would like to try the automatic method first, so I was thinking of first going form GM 3.17 to GM4 then exporting all the scripts and importing them in VM in FF 83.
