### ISSUE TITLE
4YI: A bug in Firefox WebExtensions content scripts environment affecting GM

### ISSUE THREAD

**Issue by KOLANICH** [greasemonkey/greasemonkey#3097]
### How to reproduce it?
1. install a userscript from https://gist.github.com/KOLANICH/5c85e09af65d87b24a3763c1316f099e
2. open any page
3. see browser console

### What is the expected result?
`after` message is printed.

### What is the actual result?
It is not. `TextEncoder` in `content_scripts` environment returns typed arrays (and their buffers) that seem to belong to another context.

### Environment
- Browser: Firefox
- Browser version: Developers Edition
- GreaseMonkey version: any
- OS: any

https://bugzilla.mozilla.org/show_bug.cgi?id=1681809

**Comment by Cerberus-tm** [comment]
I'm trying to understand the implications: is this a security risk? Or could it result in failing functionality of Greasemonkey?

**Comment by KOLANICH** [comment]
>I'm trying to understand the implications: is this a security risk?

IDK. May be yes and may be no. Needs additional research.

>Or could it result in failing functionality of Greasemonkey?

Some valid userscripts are broken and need a workaround making them a bit less efficient:

```javascript
new Uint8Array([...utf8Enc.encode("a")])
```

**Comment by arantius** [comment]
I think I have to agree with the VM people: this is a Firefox bug, I'm not sure what GM could change.  What sort of response do you expect?

**Comment by KOLANICH** [comment]
> What sort of response do you expect?

I don't expect any. If anyone encounterd this bug, he goes first to Google, second to GM bug tracker. So to just inform people that such a bug exists.
