### ISSUE TITLE
Monkey menu items which should be disabled are not

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#3101]
Clearest steps:

1. Monkey menu, New User Script..., save.
2. Open monkey menu to that script, open user script options
3. The "auto update disabled" item should be disabled, it should appear greyed out, clicking it should do nothing.

Today with Firefox 84 and GM 4.10.0 this works as expected.  With Firefox 86 (Nightly) the behavior is correct but the appearance is not.  The DOM does not contain the "disabled" attribute, so the CSS does not match.  (The JS object for the DOM node does have a disabled attribute, which is true, however!)

**Comment by Cerberus-tm** [comment]
Hmm could this issue be solved by Greasemonkey itself, or is it an error caused by Mozilla?

**Comment by arantius** [comment]
No idea yet!  Just recording it, as I discovered it while looking into \<menuitem\> changes.  Worst case we switch to a different HTML element.  (A less semantic one? =/ )

**Comment by arantius** [comment]
I spent some time (more than obviously necessary!) switching menuitem->div, to see if that was related.  Nope.  The state is:

        $0.disabled
        true
        $0.getAttribute('disabled')
        null

The JS object has a disabled property, set to true, but the DOM node has no "disabled" attribute, so our CSS looking for that attribute doesn't match it.

**Comment by Cerberus-tm** [comment]
Hmm then I wonder how Firefox/Mozilla normally mark disabled menu items.

Maybe add a property specific to Greasemonkey, then, if that is at all possible? Like `$0.state = 'disabled' or something? (I know nothing about making Firefox extensions.)

**Comment by poke** [comment]
This appears to be caused by [Bug 1680596: Hide <menuitem> behind a flag](https://bugzilla.mozilla.org/show_bug.cgi?id=1680596). When enabling the setting `dom.menuitem.enabled`, the menu items are correctly greyed out again.

I guess the change makes Firefox forget that the `HTMLMenuItemElement` exists which also means that the `disabled` property on it is not linked to anything.

Switching to `div` elements also makes no sense because divs don’t have a `disabled` property either, so no DOM attributes will be set. It could work if you used a `button` or `label` element. But the question remains what one should _actually_ use when building menus if the `<menu>`/`<menuitem>` elements are now phased out for real.

**Comment by arantius** [comment]
I tried to reproduce this and failed, a minimal test case ( [browser-disabled-test.zip](https://github.com/greasemonkey/greasemonkey/files/5863202/browser-disabled-test.zip) ) works as expected.

**Comment by arantius** [comment]
Aha.  I thought I had ruled it out by switching to divs, separately, but reproducing with \<menuitem\> elements produces exactly this failure: setting the JS property `disabled` does not create a DOM `disabled` attribute: [browser-disabled-test.zip](https://github.com/greasemonkey/greasemonkey/files/5863262/browser-disabled-test.zip)  (So in this case, the CSS doesn't turn it red)

**Comment by arantius** [comment]
Given that information this is "easy" to fix, except my easy fix re-triggers #3103.

**Comment by poke** [comment]
> (So in this case, the CSS doesn't turn it red)

I was looking at it with the `dom.menuitem.enabled` still enabled and was really confused what you meant here :joy: But yeah, after restoring the setting, it indeed no longer works with the menuitem elements.

> Given that information this is "easy" to fix, except my easy fix re-triggers #3103.

If you like, you could share the work you have so far in a PR and I can take a look from a CSS perspective and see how we could fix that.

I was trying yesterday to see if I could “quickly” replace the menu items by a button based approach but stopped when I realized that the shoelace library brings in a lot of default styles that I would have to overwrite there. But if you already have a working draft with divs for that, then imo the hardest part is already done 😄 

Btw. seeing how complicated it is to make a native-looking menu, I really really miss the good old XUL days…

**Comment by arantius** [comment]
> If you like, you could share the work you have so far

https://github.com/greasemonkey/greasemonkey/compare/master...arantius:no-menuitem

For some reason the only broken thing I can see is the header of an individual script's options.

> Btw. seeing how complicated it is to make a native-looking menu, I really really miss the good old XUL days…

+1000

**Comment by poke** [comment]
I will test that out in a bit and see if I can find anything. I do have a first guess just from looking through the code though. Can you try adding  `display: block` to the `gm-menu` style definition? Custom elements don’t have block-level styling by default so that might be what breaks compared to the `menu` element (the `gm-menuitem` already has `display: block` as one of its rules).

**Comment by arantius** [comment]
block on gm-menu doesn't seem to change anything -- and no big surprise, the problem is in the \<header\>, which is a sibling (not descendant) of the \<menu\>

**Comment by arantius** [comment]
I've figured it out: If you have few scripts installed (like my dev/test profile has) then the content of the user script options section is taller than that of any other section, and the browser popup has auto-sized its height to the shorter top level menu.

Because there's two places I missed turning "menu" into "gm-menu" -- and both sets the Y overflow for the relevant menu!

**Comment by arantius** [comment]
🤦 Which leaves us right back where we started: the made up \<gm-menuitem\> element also doesn't set the DOM disabled attribute, when the JS property is set to true.  _That_ is apparently the behavior (a menuitem is an element that has a special meaning for "disabled") which we're losing.

**Comment by arantius** [comment]
https://arantius.com/misc/gm-nightly/greasemonkey-2021.01.26.nightly.9bf7f1d4.xpi

Nightly build with the above fixes for those interested in testing (which is highly appreciated!).

**Comment by Cerberus-tm** [comment]
Thanks for fixing this! I'll test it as soon as I update to Firefox 85 (the issue is only with 85+, right).

**Comment by poke** [comment]
Works fine on my end, glad you found a way to solve this!

![Menu items in gray when disabled](https://user-images.githubusercontent.com/132240/106069561-02850400-6103-11eb-9b14-50628a569aae.png)
