### ISSUE TITLE
[Feature Request] add api to get whether current page is active

### ISSUE THREAD

**Issue by Allen-B1** [greasemonkey/greasemonkey#3105]
This can be done with a combination of `document.hidden` to see whether the tab is active and the WebExtension [`windows`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows) APIs.

**Comment by makyen** [comment]
What benefit are you looking for beyond what is possible from the APIs already available to all web pages?

**Comment by Allen-B1** [comment]
Nevermind, I didn't know that `blur` and `focus` responded to unfocusing a browser window.
