### ISSUE TITLE
TypeError: T is undefined

### ISSUE THREAD

**Issue by netsamb** [greasemonkey/greasemonkey#3109]
I am reloading a web page with greasemonkey which loads jQuery with @require. I haven't changed the script but a few weeks ago the script starting occasionally not loading and writing the error "TypeError: T is undefined" in the log.  Pressing F5 will fix it, but the page will fail to load again after about 7 or 8 times.

**Comment by istarogh** [comment]
"T" sounds like a minified variable name.  Maybe try switching to an unminified jQuery for a while and take note of what the error then says is undefined?

If it's "document", and if your script is a @run-at document-start script, it might be [this problem](https://github.com/jquery/jquery/issues/3333).  TLDR: occasionally document.documentElement, which a subcomponent of jQuery called Sizzle references, is not yet defined at document-start.

I struggled with that problem for a while and eventually had to split a script of mine into a regular (@run-at document-end) script and a @run-at document-start script that I painfully rewrote without jQuery :(.
