### ISSUE TITLE
[feature request] Return 'Script Sets' to individual script pages

### ISSUE THREAD

**Issue by realAzazello** [greasemonkey/greasemonkey#3131]
https://greasyfork.org/discussions/greasyfork/105545-script-sets-gone

{We already know this request is going to be rejected, if similar past ones are indicative. Still...putting out there.}

Instead of killing this feature, why not re-organize it:-- we're not asking it to be "developed further", just put somewhere else on script-pages so it can still be used & useful to site members.

Also, perhaps more members would use the feature if it were re-advertised/-announced, as it is a carryover from earlier versions of (Vanilla Forums?).

**Comment by decembre** [comment]
Yes, that"s a strange idea to remove it.

And the "Not used by many users" is a small argument:
Some use it now, appreciate it and watch the others User's sets userscripts be curiosity.

It's like AMO deleted its collections feature on  its site:
in fact let in use but not visible for the others users and degrade the usability of the function - in brief delete its interest without completely delete if .
Many users on AMO protest without they heard them.

But Greasyfork is not AMO, it is ?
;-)

**Comment by realAzazello** [comment]
Request moved to proper repo: https://github.com/JasonBarnabe/greasyfork/issues/1019
