### ISSUE TITLE
Uncaught Error: Permission denied to access object when calling function set on window.wrappedJSObject

### ISSUE THREAD

**Issue by munro** [greasemonkey/greasemonkey#3139]
Here's the script I'm using

```javascript
// ==UserScript==
// @name     Whyyyyy
// @version  1
// @grant    none
// @match    <all_urls>
// ==/UserScript==

window.wrappedJSObject.myTest1 = function () {
  console.log("Hello!");
};

window.myTest2 = function () {
  console.log("World!");
};
```

And then whenever I try to call these from the console, I get a permission error.  If I run the script from my dev console, everything works fine though.  I'm trying to write a script that monitors what browser APIs websites are using. :smile

```javascript
myTest1()
```
```javascript
Uncaught Error: Permission denied to access object
    <anonymous> debugger eval code:1
```

And then just for reference, `myTest2()` doesn't work either—but that's because I used `window` instead of `window.wrappedJSObject`.

```javascript
myTest2()
```
```javascript
Uncaught ReferenceError: myTest2 is not defined
    <anonymous> debugger eval code:1
```

**Comment by Discostu36** [comment]
I have a similar issue when trying to access a window object.

````javascript
const articleObject = unsafeWindow.Fusion.globalContent.elements;
articleObject.forEach(element => {
    //do something
 });
````
````console
Error: Permission denied to access object
````

**Comment by arantius** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts

You probably need to `exportFunction()`.

**Comment by Discostu36** [comment]
Thank you, as I only want to read the object, not edit it, changing `forEach()` to `map()` solved the problem.
