### ISSUE TITLE
Questions about user script hosting

### ISSUE THREAD

**Issue by mperry2** [greasemonkey/greasemonkey#3141]
I saw on the wiki that I can put a script on a web server. I didn't see anything in the wiki about how to set this up or how it works. Will the script update automatically if I make changes to it on the web server? If so, what do I need to put in my script to point it to the URL on the web server?

**Comment by arantius** [comment]
There's nothing to do.  Just host the file.  (Updates will be checked for, from whatever URL it was originally installed.)

**Comment by mperry2** [comment]
I didn't install any scripts. I created them myself in the editor. So it sounds like I need to put them on a server, delete it from Greasemonkey, then install it from the server. Is that correct?

**Comment by Sxderp** [comment]
That is correct.
