### ISSUE TITLE
No support of `GM_*` functions, no `abort` of `GM.xmlHttpRequest`?

### ISSUE THREAD

**Issue by AlttiRi** [greasemonkey/greasemonkey#3142]
I have installed Greasemonkey 4.11 from Firefox Store. 
Firefox 100.0.2. The same with 91.9.1esr.

`GM_xmlhttpRequest`, `GM_log` do not exist.
`GM.xmlHttpRequest` does not return `{abort}` object.

The example from 2015 year' issue — https://github.com/greasemonkey/greasemonkey/issues/2154:
```js
// ==UserScript==
// @name        Abort Test
// @namespace   gmscripts
// @include     http*://*/*
// @grant       GM_log
// @grant       GM.xmlHttpRequest
// @grant       GM_xmlhttpRequest
// ==/UserScript==

const req = GM_xmlhttpRequest({ // ReferenceError: GM_xmlhttpRequest is not defined
//const req = GM.xmlHttpRequest({ // It works.
  method: "GET",
  url: "https://github.com/",
  onload(gmResponse) {
    console.log(gmResponse.responseText);
  },
  onabort() {
    console.log("on abort");
  }
});

req.abort();  // TypeError: req is undefined
GM_log("completed"); // ReferenceError: GM_log is not defined
```

...does not work. 

What's the problem?

I think it should work.

**Comment by AlttiRi** [comment]
Well, while Firefox logs the errors with the uncommented lines.

`GM_log("abort OK")`, and `GM_xmlhttpRequest` look to be working. I see the result of `console.log(gmResponse.responseText);` and `"abort OK"` text.

**Comment by w35l3y** [comment]
Starting at version 4, there isn't `GM_*` anymore.
https://wiki.greasespot.net/GM.xmlHttpRequest

`GM.*` returns a promise.
That is the reason why you don't have `req.abort()`

I haven't tested it, but try using:
```
const req = await GM_xmlhttpRequest(...);
req.abort()
```
or
```
GM_xmlhttpRequest(...).then(req => req.abort())
```
