### ISSUE TITLE
GM.xmlHttpRequest() memory leak

### ISSUE THREAD

**Issue by swcen** [greasemonkey/greasemonkey#3145]
GM.xmlHttpRequest() in Firefox on Windows 11 leaks memory.

The Firefox version is 102.0.1(64-bit), and greasemonkey version is 4.11.

To test, the attached user script (PagerDumper.user.js) is activated in https://www.yahoo.com. This script repeatedly executes a function in a timer every second, and this function gets the webpage body, and uses GM.xmlHttpRequest() to "POST" the content  to a local TCP socket.

With this script activated, the browser contains multiple processes, and the memory footprint of the "webIsolated=https://yahoo.com" process (as measured in the "about:memory" tab) keeps increasing, at a pace about a few MB a second. Clicking "GC" or "Minimize memory usage" button in the "about:memory" tab has little effect in reducing the memory footprint, so the memory footprint is not of left-over garbage. Eventually, this process's memory footprint consumes most of entire available memory, and Firefox may crash.

In some previous versions of Firefox when GM_xmlhttpRequest() was supported, scripts similar to this PageDumper.user.js have not experienced similar memory leak issues.

[PageDumper.user.zip](https://github.com/greasemonkey/greasemonkey/files/9060815/PageDumper.user.zip)

**Comment by swcen** [comment]
This seems is an issue of Firefox itself. Tested Tampermonkey version of the script in Firefox and got the same issue. But the same script on Chrome browser works perfectly fine.

**Comment by Cerberus-tm** [comment]
> This seems is an issue of Firefox itself. Tested Tampermonkey version of the script in Firefox and got the same issue. But the same script on Chrome browser works perfectly fine.

Interesting, do you know whether a bug has been filed on Bugzilla?
