### ISSUE TITLE
Code highlighting thrown off by template literal

### ISSUE THREAD

**Issue by bvandergiessen** [greasemonkey/greasemonkey#3149]
In the built-in editor, code highlighting usually works; it makes the code easier to read. But a _template literal_ can throw it off course: after such a string construction (with backticks, dollar sign and braces) the highlighter seems to regard the rest of the document as a string. 

Here's an example, where the template literal is 

```js
`Bookmark voor ${window.tweetLink}`
```

and everything after it is considered part of some giant string:

<img width="600" alt="Code highlighting thrown off" src="https://user-images.githubusercontent.com/11797190/190119846-a6559a22-1ca2-491c-b204-3b238eaddbe8.png">

This problem is only with the code highlighter; the interpreter runs everything correctly.

**Comment by arantius** [comment]
Thank you for the detailed and clear report.  We use (an old version of...) CodeMirror for our editor, so the problem is there.

Their online demo ( https://codemirror.net/try/ ) seems to work OK with this test string, so perhaps we just need to update to a newer version.
