### ISSUE TITLE
User scripts aren't executed on support.mozilla.org/addons.mozilla.org

### ISSUE THREAD

**Issue by CendioOssman** [greasemonkey/greasemonkey#3150]
I'm not sure if this is some undocumented safety feature, but user scripts are not executed on the domains support.mozilla.org and addons.mozilla.org. The monkey menu claims the script is active under "User scripts for this tab", but no effects of the script are seen. Not even doing something simple as `console.log("Hello!");`.

Seen with Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0 and Greasemonkey 4.11.

**Comment by arantius** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts

Mozilla documents the locations where they don't allow content scripts to run.  Greasemonkey executes user scripts as content scripts.

**Comment by CendioOssman** [comment]
Thank you for that link. That was unfortunately well hidden (at least from a user's point of view).

I don't suppose Greasemonkey can detect this block and show in the UI that scripts aren't running?
