### ISSUE TITLE
Unable to install some scripts

### ISSUE THREAD

**Issue by Gersonzao** [greasemonkey/greasemonkey#3153]
I'm using Firefox ESR 102.3 with the latest Greasemonkey version. It works just as its supposed to in Tampermonkey
For example: https://greasyfork.org/en/scripts/449705-yuhan-user-script-%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E-%E7%99%BE%E5%BA%A6%E5%BF%85%E5%BA%94%E8%B0%B7%E6%AD%8Cf%E6%90%9C-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-csdn-github-%E5%BC%80%E5%8F%91-%E6%9B%B4%E5%A4%9A-%E4%BC%98%E5%8C%96-%E7%BE%8E%E5%8C%96-%E5%87%80%E5%8C%96-%E5%A2%9E%E5%BC%BA
![image](https://user-images.githubusercontent.com/85644671/193476543-b8366a37-dfb1-411e-8fa2-4b22bb2a2fd7.png)

**Comment by Gersonzao** [comment]
It can only be fixed by the author https://github.com/violentmonkey/violentmonkey/issues/1593#issuecomment-1264767958

**Comment by arantius** [comment]
Indeed, that script is broken.
