### ISSUE TITLE
Is there a way to view storage set by GM.setValue?

### ISSUE THREAD

**Issue by ArchivingToolsForWBM** [greasemonkey/greasemonkey#3156]
I was wondering if there is a way to easily view the data stored on the browser when GM.setValue is executed.

**Comment by Cerberus-tm** [comment]
Can you explain what you mean, exactly?

**Comment by ArchivingToolsForWBM** [comment]
On firefox, open the devtools, on the storage tab, you'll see a directory on the left pane showing various sites that store your data as well as extensions. But I cannot find where the GM.setValue data is located on there. I tested [this example](https://wiki.greasespot.net/GM.getValue). It works, but I do not know where to view the storage value though a debugger.

**Comment by Cerberus-tm** [comment]
Ah, I see. I rarely use that tab, but it appears to show only data stored which correspond to the active tab? I believe GM.setValue is browser wide, so perhaps that is why it doesn't appear there?

**Comment by arantius** [comment]
Yes and no.

No: These values are stored in ( https://github.com/greasemonkey/greasemonkey/blob/11e340b4dadee868191e72a3ef888f75c6eabbc1/src/bg/value-store.js#L15 ) an IndexedDB instance, tied to the installed script (based on the random-at-install-time UUID of the script).  Identifying the correct DB would be hard, and I've never seen good tools to introspect into an IndexedDB.  (And indeed, these are cross-origin.  Invisible to the page-tied normal web developer tools.)

Yes: There's both https://wiki.greasespot.net/GM.listValues and https://wiki.greasespot.net/GM.setValue so it's only a few lines in your script to dump the values that it has set.  (Not something you'd want to do often/permanently, but maybe as a menu command.)
