### ISSUE TITLE
`GM_registerMenuCommand` not working in Firefox Greasemonkey

### ISSUE THREAD

**Issue by fiammanda** [greasemonkey/greasemonkey#3158]
`// @grant GM_registerMenuCommand` is enabled.
Same script works in Firefox Tampermonkey.

**Comment by Cerberus-tm** [comment]
Greasemonkey unfortunately switched from using GM_ to GM., rendering many scripts inoperable. (Especially the asynchronous GM.getValue and .setValue prevent many people from even trying to update existing scripts.) So have you tried it with a dot instead of an underscore?

**Comment by fiammanda** [comment]
> Greasemonkey unfortunately switched from using GM_ to GM., rendering many scripts inoperable. (Especially the asynchronous GM.getValue and .setValue prevent many people from even trying to update existing scripts.) So have you tried it with a dot instead of an underscore?

Thank you so much! I used dot in the script but leave the underscore in metadata, as wiki (https://wiki.greasespot.net/GM_config) hasn't changed.

**Comment by Cerberus-tm** [comment]
I don't know about GM_config, either that specific command was not updated, or the Wiki was not updated. But GM.registerMenuCommand is in the API list:
https://wiki.greasespot.net/Greasemonkey_Manual:API

The Meta section should be the same as in the actual code.

**Comment by makyen** [comment]
[GM_Config](https://github.com/sizzlemctwizzle/GM_config/) is a third-party package. It was modified in 2021, and might sort-of function in Greasemonkey. when used with Greasemonkey 4.X, the values will be stored to the `localStorage` of the domain for the page in which the menu is invoked.

The page https://wiki.greasespot.net/GM_config was last modified in 2015, so is *way* out of date. Given that the package isn't written to be compatible with Greasemonkey 4.X, it's probably better to just delete that page of the wiki. The alternative would be for someone to re-write it to be compatible with Greasemonkey 4.X and maintaining compatibility with other userscript managers by using the shim.
