### ISSUE TITLE
@nocors metadata block

### ISSUE THREAD

**Issue by sjehuda** [greasemonkey/greasemonkey#3160]
**UPDATE:** This suggestion has been rejected by https://github.com/violentmonkey/violentmonkey/issues/1781

Discussion at https://openuserjs.org/discuss/nocors_metadata_block

I think it would be useful to add `@nocors` metadata block (similarly to `@noframes`) which would be productive in the sense of coding and consequently make userscript managers to behave in a uniform fashion.

[no-www](https://openuserjs.org/scripts/sjehuda/no-www) is using `GM.xmlHttpRequest` which doesn't seem to be supported with all userscript managers.

Example script
```js
// ==UserScript== 
// @name        no-www
// @namespace   org.openuserjs.sjehuda.no-www
// @description www. is deprecated. Redirect to URL without www.
// @author      Schimon Jehudah, Adv.
// @homepageURL https://no-www.org/
// @supportURL  https://openuserjs.org/scripts/sjehuda/no-www/issues
// @updateURL   https://openuserjs.org/meta/sjehuda/no-www.meta.js
// @copyright   2023, Schimon Jehudah (http://schimon.i2p)
// @license     MIT; https://opensource.org/licenses/MIT
// @run-at      document-start
// @include     *
// @grant       GM.xmlHttpRequest
// @version     23.03
// ==/UserScript==

if (!location.host.startsWith('www.')) return; // exit (else, continue)

var newURL = location.href.replace('://www.','://');

GM.xmlHttpRequest({
  method: 'GET',
  url: newURL,
  onprogress: console.log('Checking for no-www...'),
  onload: function(response) {
    if (response.finalUrl == newURL) {
      location.href = newURL;
    } else {
      console.log('Please contact webmaster to remove www. https://no-www.org/');
    }
  },
  onerror: function(response) {
    console.log('Error requesting for no-www')
  }
})
```

If `@nocors` was introduced, this script could have been shorter.
```js
fetch(newURL)
  .then((response) => {
     if (request.reseponseURL == newURL) {
       window.open(newURL,'_self');
     }
  })
```

**Comment by sjehuda** [comment]
> You can then use `gmXmlhttpRequest` and be compatible with all userscript managers of which I'm aware in nearly all circumstances.

This is nice. This should be on the documentaton.
Thank you

**Comment by sjehuda** [comment]
@makyen is it possible to handle three (3) variables?

Apparently, in another program it is `GM.xmlHttpRequest` https://github.com/stsyn/random-stuff/issues/1#issuecomment-752079478

**Comment by makyen** [comment]
@sjehuda I'm not sure what more you need. The code I provided above requests an `@grant GM.xmlHttpRequest` and already uses `GM.xmlHttpRequest` when `GM_xmlhttpRequest` isn't a function (which will be the case in Greasemonkey 4). The constant `gmXmlhttpRequest`, will automatically be set to the one which is available. I'm unsure what third variable you're asking for.

Admittedly, `gmXmlhttpRequest` should probably be called `gmXmlHttpRequest`, just from a naming convention point of view (now changed above).

**Comment by sjehuda** [comment]
I meant to ask this: How can I apply your solution, in case I have more than 2 libraries that do the same thing?

```js
// @grant       GM_xmlhttpRequest
// @grant       GM.xmlHttpRequest
// ==/UserScript==
const gmXmlHttpRequest = typeof GM_xmlhttpRequest === 'function' ? GM_xmlhttpRequest : GM.xmlHttpRequest;
```

**Comment by arantius** [comment]
Rejected for largely the same reasons as VM: it's somewhere from impractical to impossible to add.
