### ISSUE TITLE
Can't log messages to any console?

### ISSUE THREAD

**Issue by monnier** [greasemonkey/greasemonkey#3161]
I'm trying to write a greasemonkey script (Greasemonkey 4.11 in Debian stable's Firefox 91.13.0esr) but I'm struggling to debug it.
I checked the various things in the FAQ to make sure the script is active (the monkey icon is colorful, the script is listed under "User script for this tab", and it has the little checkmark next to "Enabled").

As a sanity check I started the script as follows:

```
// ==UserScript==
// @name     Test script
// @version  1
// @grant    none
// @match    https://*.umontreal.ca/*
// ==/UserScript==

GM_log("STEF1");
unsafeWindow.console.log("STEF2");
console.log("STEF3");
```

Then I visited my home page at https://www-labs.iro.umontreal.ca/~monnier/ but those messages don't appear anywhere (neither in the console of Ctrl-Shift-i nor in Ctrl-Shift-j).  I also tried to rotate those 3 in case the first line fails and causes the whole script to bail out, but to no avail.

All the info I found via web searches seems out of date (typically refers to Firebug or old versions of Greasemonkey).

Am I doing something wrong?

**Comment by Cerberus-tm** [comment]
Maybe `@match` doesn't work in Greasemonkey? Try `@include` instead. It is strange that the script should be listed for this tab, but it's worth a try.

I don't know how unsafeWindow works in Greasemonkey, but maybe it doesn't work with `grant none`?

GM_log won't work with newer version of Greasemonkey, I think.

Maybe try a script that has nothing but `console.log("STEF3");` : that should always work. And use `@include   *` for testing.

**Comment by monnier** [comment]
Thanks.  It looks like I bumped into a pilot error: your test worked fine as well even with `@match` and even though I thought I had already tried that.  Not sure what I did different/wrong that time, but in any case now it works, thank you very much!

**Comment by Cerberus-tm** [comment]
> Thanks. It looks like I bumped into a pilot error: your test worked fine as well even with `@match` and even though I thought I had already tried that. Not sure what I did different/wrong that time, but in any case now it works, thank you very much!

Such things happen to everyone!

**Comment by arantius** [comment]
https://wiki.greasespot.net/GM_log confirms that it doesn't exist since Greasemonkey 4.0.  (We have `console.log()` now.)
https://wiki.greasespot.net/Metadata_Block#.40match confirms `@match` support.
https://wiki.greasespot.net/UnsafeWindow `unsafeWindow` is also documented.
