### ISSUE TITLE
New metablock @filetype

### ISSUE THREAD

**Issue by sjehuda** [greasemonkey/greasemonkey#3164]
This is a request to add new API ~~to GM.xmlHttpRequest, or~~ to the core of the Greasemonkey extension, that can influence a change in `document.contentType`.

See https://github.com/greasemonkey/greasemonkey/issues/3164#issuecomment-1613389503

---

I have a [feed reader userscript](https://openuserjs.org/scripts/sjehuda/Newspaper) which partially fails when page content/mime type contains `xml`.

Further [investigating and testing](https://openuserjs.org/garage/Loading_functions_after_document_is_replaced_by_new_document), namely with extensions like [Open in Browser](https://addons.mozilla.org/firefox/addon/open-in-browser/) and [Header Editor](https://addons.mozilla.org/firefox/addon/header-editor/), the failures are a result of content-type being set to `xml`.

The errors are as follows: (line position may not be accurate due to recent update)

```
Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at infoSquare (userscript:org.openuserjs.sjehuda.newspaper/Newspaper:2195:17)
    at Element.<anonymous> (userscript:org.openuserjs.sjehuda.newspaper/Newspaper:2049:7)
```

```
Uncaught TypeError: Cannot set property 'display' of undefined
    at XMLDocument.<anonymous> (VM96 Newspaper:2127)
```

Attempts to [forge response type](https://openuserjs.org/garage/Forging_content_type_mime_type) either with Fetch or XHR have also failed.

**Is there a solution or should a new metablock or API similar to `webRequest.onHeadersReceived` be added?**

**Comment by sjehuda** [comment]
The following attempt to influence a change to `document.contentType` has failed.

```js
    gmXmlhttpRequest({
      method: 'GET',
      url: document.documentURI,
      headers: {
        "Content-Type": "text/plain",
        "Accept": "text/plain"
      },
      onprogress: function(request) {
        request.responseType = 'text';
      },
      onload: function(request) {
        request.overrideMimeType = 'text/plain';
        if (document.URL.startsWith('file:') ||
            request.status == 200) {
          myResolve(request);
        }
        else {
          myReject("File not Found");
        }
      },
      onerror: function(request) {
        console.log('Error Error Error')
      }
    })
  });
```

**Comment by arantius** [comment]
Getting the document again will never change the type that it was when it was loaded.

You'll need to be a lot more specific about specifically what you want, and how/why it would improve your use case.

**Comment by sjehuda** [comment]
> Getting the document again will never change the type that it was when it was loaded.

Yes, so I've found out.

> You'll need to be a lot more specific about specifically what you want, and how/why it would improve your use case.

I have wrote a userscript that converts structured data files (i.e. XML and JSON) into human readable HTML files.

Overhaul, the program works as expected; documents are processed and forged successfuully into HTML.

The problem comes after the document is placed into viewport.

Using event listeners, the program offers extra functionality, mostly for accessibility, yet it also offers **critical** functionality such as _Provident Image Load_ (aka "lazy" load) which is essential, due to bandwidth and hardware resources.

All the extra functionalities work well when `document.contentType` (read only) _does not_ contain `xml`, because, once `document.contentType` has `xml`, any code that contains `querySelector` would fail because the `document` is believed to be whatever `document.contentType` (an XML), because the web browser doesn't check the document after it has been loaded.

An error message from the program suggests the file processed is XML when in reality it is an HTML:
```
Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at infoSquare (userscript:org.openuserjs.sjehuda.newspaper/Newspaper:2287:17)
    at Element.<anonymous> (userscript:org.openuserjs.sjehuda.newspaper/Newspaper:2141:7)
```

**Comment by sjehuda** [comment]
I have added to [Newspaper userscript](https://openuserjs.org/scripts/sjehuda/Newspaper) an info message that is displayed at the top of a page when `document.contentType` includes `xml`.

Interestingly, when executing `document.contentType` from the userscript, the content type is correct `text/html`, yet we are here and the browser determination is a setback.

Test page (`application/xml`): https://lzone.de/liferea/blog/feed.xml

**Comment by sjehuda** [comment]
I think it would be most appropriate to incorporate the capability of the program [Open in Browser](https://github.com/Rob--W/open-in-browser) into metablocks as follows:

```
// @filetype text/xml text/html
// @filetype application/xml text/html
// @filetype application/rss+xml text/html
// @filetype application/atom+xml text/html
```

`@filetype`: `@mimetype` would be good too
`text/html`: `text/plain` would be good too

**Comment by arantius** [comment]
Infeasible without significant refactoring (we don't know this information when we're running scripts https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCommitted#details_2 ), the cost/benefit of potentially breaking existing scripts by changing how they run doesn't seem worth it.

**Comment by sjehuda** [comment]
I have managed to overcome this setback, namely by passing the HTML element `newDocument` and processing it in all ways feasible (see `preProcess`) and then replacing `document` by `newDocument`. See [v24.04.06 vs. v24.04.08](https://greasyfork.org/scripts/465932-newspaper/diff?v1=1356285&v2=1355403).

There was also another matter which required to create an element and change CSS Stylesheet in order to get the expected behaviour, because JavaScript attribute `style` does not work with `document.contentType` that ends with **XML**. See [v24.04.08 vs. v24.04.09](https://greasyfork.org/scripts/465932-newspaper/diff?v1=1356499&v2=1356285).

Two functions remain not to work upon XML:
- Switching mode (bright and dark) due to attribute `style`.
- Dialog settings.

> Dialog settings _might_ be possible. I will try.
