### ISSUE TITLE
Firefox for Android support

### ISSUE THREAD

**Issue by arantius** [greasemonkey/greasemonkey#3173]
https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/

It was recently announced that extensions are (finally) coming back to Firefox for Android.  An email addressed to me said "Again, we’d love to have your extension be part of the general availability release when it debuts later this year."

Research feasibility and/or implement Firefox for Android support.  I don't know when "later this year" is, exactly.

**Comment by arantius** [comment]
After the above changes, I've: Installed a script, seen it run, opened the editor, changed a script, used a registered menu command.  Everything seems to work so far.

**Comment by Cerberus-tm** [comment]
Interesting. Block requestions before completion: does that mean the Javascript on the (unedited) page should be unable to make any requests to the Internet until all userscripts are loaded? Or is it only about requests from userscripts?

**Comment by arantius** [comment]
Sorry by "requests" I was referring to messages sent between content and background.  I.e. https://github.com/greasemonkey/greasemonkey/blob/master/doc/Messages.md

**Comment by Cerberus-tm** [comment]
> Sorry by "requests" I was referring to messages sent between content and background. I.e. https://github.com/greasemonkey/greasemonkey/blob/master/doc/Messages.md

Ahh that makes sense.

**Comment by arantius** [comment]
When `GM.openInTab()` is called:

    Error: Type error for parameter createProperties (Property "openerTabId" is unsupported by Firefox) for tabs.create.

on Android.  On desktop, it works.

**Comment by arantius** [comment]
Warnings from AMO:

* browserAction.setIcon is not supported in Firefox for Android version 57.0
  Warning: This API is not implemented by the given minimum Firefox for Android version
  src/bg/options.js line 68 column 8
* extension.getURL is deprecated
  Warning: This API has been deprecated by Firefox.
  src/bg/options.js line 71 column 18
  
  And a whole bunch from HTML files inside codemirror; files we should probably remove.

**Comment by arantius** [comment]
Need to confirm but I'm pretty sure this breaks `GM.registerMenuCommand()`.  RMC works by opening a port (`chrome.runtime.connect`) between content and background.

If I add `console.log('registered menu commands at', new Date());` to the script registering the command and

    port.onDisconnect.addListener(port => {
      console.warn('port closed!');
    });

To `function GM_registerMenuCommand()`, then load a page (and otherwise do nothing with that browser) I see:

    registered menu commands at Date Tue Nov 14 2023 11:15:29 GMT-0500 (Eastern Standard Time)
    port closed at Date Tue Nov 14 2023 11:15:59 GMT-0500 (Eastern Standard Time)

In the tab's console.  After ~exactly 30 seconds, the port is closed (because the background page suspended?) and the command gets broken.  If I keep opening the menu to check, more often than every 30 seconds, causing a message (many messages) to be sent to the background script, I can keep the port alive for at least several minutes.

(I'm scared that there are several other such subtle bugs hiding from this "simple" change to a non-persistent background script.)

**Comment by arantius** [comment]
This should be done.  I could use your help testing this!  Checkout or download Greasemonkey's source code, then follow [the documentation](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/#install-and-run-your-extension-in-firefox-for-android) for installing an extension during development.

Any testing results, positive or negative, would be great.
