### ISSUE TITLE
New user script does not run and cannot rename the script and docs are out of date

### ISSUE THREAD

**Issue by solongtony** [greasemonkey/greasemonkey#3187]
I recently installed the latest version of Greasemonkey. I created a user script, but there was no opportunity to choose a name. It named itself "Unnamed Script xxxxxx" where each x is a digit. I do not see any way to rename it. When I load a page it does not run, even though Greasemonkey is active and the user script is enabled. I did not specify anything for include or exclude. I simplified it down to an alert statement, it still doesn't run. I added * to the include and it still doesn't run. I looked for documentation from Greasemonkey. The project on Github and Source forge both do not have documentation. The documentation that Google suggests is https://wiki.greasespot.net/Greasemonkey_Manual and it is out of date. It does not have the latest Greasemonkey UI.

**Comment by Cerberus-tm** [comment]
To edit: simply click on the userscript's name in the menu, then Edit.

> I added * to the include and it still doesn't run.

I just tried creating a new userscript and changing nothing, not even adding an `@includ`, except adding `alert()`. And it worked fine, on every page. Maybe you can post your full script here? Or test again?
