### ISSUE TITLE
GM.openInTab() does not work on Android Firefox

### ISSUE THREAD

**Issue by chasingdragonflies** [greasemonkey/greasemonkey#3189]
https://github.com/greasemonkey/greasemonkey/issues/3173#issuecomment-1807179472
This was pointed out earlier, but idk if attempt was made to fix it.

```javascript
GM.openInTab("https://failed.org", false)
```

**Comment by arantius** [comment]
Fixed in 7444f226643e75c8dc964309b7dd03046238544c
