### ISSUE TITLE
Automatic updates should delay appropriate after the browser opens before starting

### ISSUE THREAD

**Issue by binki** [greasemonkey/greasemonkey#3193]
I think that updates should be checked immediately if the `updateNextAt.` value is in the past. However, some people suggest that waiting 15 minutes after browser boot-up is a requirement.

Use cases for immediate check:

* User opens their browser after a few weeks. Scripts have released updates for compatibility with changes to websites. The first website the user visits is such a website. The user encounters a bad experience because the userscript associated with that site had not been updated yet.
* User is on Android and backgrounds Firefox after a few minutes of use. Android kills or pauses the process before the browser has even been running long enough for 15 minutes. The next time the browser opens, the 15 minute timer is started from 0 again.

Argument against immediate check:

* Browser startup time is longer (though the check will technically be running after the browser GUI has loaded, it might contribute to post-start sluggishness). See https://github.com/greasemonkey/greasemonkey/pull/3191#discussion_r1683124964

I’d rather the extension ask the browser to run the first update check at its leisure, whenever the browser stops feeling sluggish. I do not know if there is an API for this. If not, I think that a 1 minute timer would be sufficient to allow the browser to be responsive and short enough to ensure that updates can run on Android.

**Comment by arantius** [comment]
Looks like this was missed in the initial implementation, but we always should have:

* Avoided executing background tasks immediately upon browser start-up
* Separated each update check in time

**Comment by binki** [comment]
Right now, there is logic which adds a 10 second delay between every script update ( https://github.com/greasemonkey/greasemonkey/blob/d15e0dad6ced7f9639699ed420c3fdba8344b113/src/bg/updater.js#L130 ) . Does this satisfy the requirement to separate each update check in time and immediate browser start-up? Could that one value be tuned to be 1 minute instead of 10 seconds and the (apparently accidental) initial 15-minute delay removed?

I think the following needs to happen:

* Address the accidental 15-minute delay. I think this could be done just by changing the order of the `background/scripts` key so that `updater.run.js` is after `user-script-registry.run.js`. Another approach would be to have the script registry provide an initialization `Promise`, but I suspect that this initialization must run synchronously and immediate so that scripts can be loaded into restored tabs.
* Decide on the tuning values.
   * How long before the first check after startup? 1 minute?
   * How long between each script check (I think this is what your “separated each update check in time” is asking for)? 1 minute?
* Implement the chosen tuning values.

**Comment by arantius** [comment]
The 15 minute delay was indeed meant only for a broken/error path.  Simply delaying the first check seems to address everything left.  I've already got a (not yet pushed) commit.

**Comment by arantius** [comment]
7823aa1acbe7356b4bb27fe70b42024df73a2cca (above) resolves this
