### ISSUE TITLE
Tabview youtube no longer works

### ISSUE THREAD

**Issue by hitmonray** [greasemonkey/greasemonkey#3196]
Pages barely load if it all. Video might play for a second then stop. Chat / comments never load.

started happening randomly 2 days ago. disabling tampermonkey everything works normal. 

tabview youtube is the only tampermonkey script enabled. 

using brave browser on windows

**Comment by arantius** [comment]
A) This is the Greasemonkey repository, not Tampermonkey.
B) Greasemonkey does not support Brave.
C) It sounds like you're reporting a problem with a particular script, not Greasemonkey (nor any other particular user script manager).

https://wiki.greasespot.net/Greasemonkey_Manual:Getting_Help#Where_to_Say_It
